### ISSUE TITLE
On really thin screens, Send Message option is not available

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#1381]
# Observed

## Thin Screen

<img width="1280" alt="screen shot 2015-10-05 at 16 13 30" src="https://cloud.githubusercontent.com/assets/191496/10282655/4608a3da-6b7c-11e5-9990-6ab02b99e45e.png">

## Slightly Wider Screen:

<img width="1280" alt="screen shot 2015-10-05 at 16 13 13" src="https://cloud.githubusercontent.com/assets/191496/10282673/5d22cc9e-6b7c-11e5-8a24-faf3c92260b4.png">

# Expected

I guess the button should be active on any size of screen!

# Related

- #1380
- #1263

**Comment by garethbowen** [comment]
Ok this is quite confusing and does look like a bug. The logic is...

On health centers the send message button actually shows a dropdown of "send message" and "message all". The message all doesn't work on mobile yet so I disable the button.

**Comment by alxndrsn** [comment]
Shouldn't that be controlled by `.mobile-only` vs `.desktop-only` rather than by screen width?

**Comment by garethbowen** [comment]
`.mobile-only` and `.desktop-only` hides things based on screen width...

**Comment by alxndrsn** [comment]
lol

**Comment by alxndrsn** [comment]
what happens in landscape mode?

**Comment by garethbowen** [comment]
On landscape it renders as if it were a mid-sized device, which in this case means the call button is disabled. Obviously using screen resolution is a really crude way to detect whether a device can make a phone call or send an sms.

We could add another layer of complexity and assume if it's running in the android container then it can call. Then it would give a false positive for tablets without a phone connection running the app.

@abbyad What do you think? Should we assume...
a) only small devices can make phone calls, ie: phones in portrait mode
b) small and medium devices can make phone calls, ie: phones in portrait or landscape mode, and tablets in portrait mode.
c) assume anyone running in the android container can make phone calls, ie: phones and tablets in the native app, but _not_ phones nor tablets using the browser.
d) some combination of the above?

**Comment by abbyad** [comment]
This does seem tricky, especially that in v0.6 we haven't been using a SMS gateway yet. 

Currently in a desktop browser the SMS button action changes when the window is resized. I am leaning towards giving a consistent experience for a user on a particular device, regardless of the screen size.

**Mobile app:** Always call/sms
**Mobile browser:** In some ways it would nice if the have the same behaviour as the mobile app, but this is not ideal in every case. For instance, a nurse may be using a tablet in a clinic on wifi, and want to message a group of CHWs. For now I would *treat this like a desktop browser*.
**Desktop browser:** Always send sms via webapp, no calls

@diannakane do you agree?

**Comment by diannakane** [comment]
Agreed. I think it's fair to assume that mobile phone users will be in our mobile app, and if you find yourself on the mobile browser, you'll either be in a tablet or on your phone but not a regular user of it there, such as a supervisor checking in on something on the go, but who primarily works from their desktop.

I see your point about wanting a consistent experience on a particular device, but I also think it's fair and not unexpected to package features by 1) mobile app and 2) browser (mobile or desktop).

**Comment by garethbowen** [comment]
This is made obsolete by the FAB rework.
