### ISSUE TITLE
Make webapp date widget easier to use

### ISSUE THREAD

**Issue by sglangevin** [medic/cht-core#2272]
When creating people in v2.6.x, the widget being used to select the birthdate is difficult to use in the webapp. It's not immediately clear how to scroll back through the years, particularly when creating a CHP or an area's primary contact. Let's update the date widget to something more user-friendly, perhaps by allowing the user to type something into the date box instead of selecting from the calendar.

**Comment by sglangevin** [comment]
@diannakane we should probably create an idea card or design issue for this one.

**Comment by diannakane** [comment]
Is this different than this:
https://github.com/medic/medic-design/projects/1#card-1430963

**Comment by sglangevin** [comment]
Yes - this issue is referring to the web/desktop view widget (e.g. in Chrome on a laptop). That design card is for Android phones.

**Comment by diannakane** [comment]
OK I will add it.
https://github.com/medic/medic-design/projects/1#card-1521131

**Comment by abbyad** [comment]
@amandacilek do you know if this is still an issue? If not feel free to close it. If it is please connect with @MaxDiz to prioritize accordingly. Thanks!

**Comment by amandacilek** [comment]
Yes I just checked and I think this is still an issue. When clicking in the "Date of Birth" field, a calendar pop-up displays (which is helpful), but does not let you type directly in the field area or even see what is there (which is unhelpful). 

Note how the widget location blocks visibility and access to the entry field:
![Screen Shot 2019-03-19 at 4 54 40 PM](https://user-images.githubusercontent.com/26235957/54649615-381d2880-4a68-11e9-8cea-8f9c2f38efec.png)

A quick-fix, that involves no changes to the UI of the date widget, would be to reposition it so it appears below the field, and then do as Sharon suggests and allow users to either use the calendar widget OR type directly into the box. IMO it's ok if the calendar widget still automatically pops up, as long as it doesn't prevent manual entry.

**Comment by amandacilek** [comment]
Ticket #3482 is related to this. That ticket describes the preferred solution - that clicking in the text box does not immediately open the date picker but does allow you to manually type in a date. To the right of, or below the input box there can be a button with a calendar icon and/or the word "Calendar" or "Select date" which when clicked opens up the calendar pop-up.

**Comment by garethbowen** [comment]
This is ready for AT in `2272-fix-positioning-of-datepicker`.

The fix chosen here fixes the alignment of the popup which is sufficient for now. Issue #3482 covers a more comprehensive solution.

Test this thoroughly on mobile.

**Comment by ngaruko** [comment]
Looks good on the web...
**_Before_** 
![image](https://user-images.githubusercontent.com/6979995/67733294-da6fa680-fa62-11e9-97ce-1735f4c2e995.png)

**_After_**
![image](https://user-images.githubusercontent.com/6979995/67733532-81544280-fa63-11e9-85b5-21552bac4510.png)

**_On the mobile app_**, the date picker is at a fixed position, ie not relative to the position of the date textbox. So, if one scrolls down a little and the date text box is in the middle of the screen, the date picker is on top, like in in the screenshot.
![image](https://user-images.githubusercontent.com/6979995/67735824-3b4ead00-fa6a-11e9-850e-78868f565ac6.png)

**Comment by garethbowen** [comment]
On the phone we revert to the native android date picker, so I think this is as expected.

@ngaruko Feel free to merge and close!
