### ISSUE TITLE
Fill out LG's rules tests

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#2503]
Alex made an example test against #1836 (see: https://github.com/medic/medic-projects/commit/3a2e2233a9f9baee8a7d80090908d10697d7b734)

We should write "the rest" of the tests.

In doing this we may be able to abstract away some of the pieces we feel that tech leads should not deal with. The most obvious being the bootstrapping and de-bootstrapping of nools before each test.

This ticket is complete when there is reasonable coverage of LG's rules, what is written is understandable by tech leads / rules writers, and could be duplicated / used as a base of understanding for other 2.x deployments.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by SCdF** [comment]
Yes we should still do this. We only did one example, and we need to expand, both with LG and in general into a system where people can actually unit test the partners core business rules.

**Comment by garethbowen** [comment]
Closing as ancient.
