### ISSUE TITLE
clean up contacts during import

### ISSUE THREAD

**Issue by mandric** [medic/cht-core#2628]
There is some code in the webapp that makes using the contact data more efficient.  Use this code during import, and bulk update (prune) any documents that exist on LG, starting with okellowa user.

**Comment by estellecomment** [comment]
Example doc with excessive recursion of parents and contacts : see https://github.com/medic/medic-projects/issues/592#issuecomment-239379980

**Comment by estellecomment** [comment]
Any time in the hierarchy you have `x.y.z.contact.parent` then `contact.parent` == `z`, so it's redundant. You should be able to remove all `contact.parent` fields inside the doc. 
Though I don't know if that's needed for any features of the UI. I'd vote fixing the UI and keeping the data sane, over keeping the data redundant (but maybe that's not possible?)

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
Yeah we should do this - at least clean up the import script so it doesn't happen again.

**Comment by abbyad** [comment]
Is this still relevant, or to be superceded by any work in #5678?

**Comment by garethbowen** [comment]
I think they're not necessarily related but could be done at the same time. #5678 is mostly about batching in the admin app, whereas this cleanup could apply to the medic-conf APIs too.

**Comment by garethbowen** [comment]
Please reopen if it happens again.
