### ISSUE TITLE
Add a hierarchy link to the top left of the people and places RHS view

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#2819]
See the spec: https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.qkrffmrtf0zt

There are examples on Zepplin also.

For example:

![image](https://cloud.githubusercontent.com/assets/583851/19271339/3440ea44-8fbc-11e6-977d-5715bc529a6e.png)

From what I understand this link should read `< PARENT_PLACE`, and link to the parent place. If the user does not have access to the parent place (ie CHP who can't download the branch) we would instead display nothing.

**Comment by sglangevin** [comment]
A little further down in that doc it says: The title is not the text of the back button, it is the title of the page. This ticket is the opposite of what I've understood in conversations with @diannakane but perhaps that was a previous iteration. Dianna, can you clarify?

**Comment by diannakane** [comment]
@sglangevin that must be referring to mobile.

**Comment by abbyad** [comment]
@diannakane this would replace the "Belongs to", right?

Desktop view:
![image](https://cloud.githubusercontent.com/assets/789512/19480749/952eb3e2-9519-11e6-9c25-772d2e968cee.png)

**Comment by abbyad** [comment]
Moving this to the backlog for now since the functionality seems to be covered by the "Belongs to" field.

**Comment by diannakane** [comment]
The back button and "belongs to" serve different purposes so ideally we
will have both.

The back button allows you to get back to where you came from. In the
majority of cases, this is the parent place. In two cases, where you came
from is not your parent place. This has been outlined in the spec and
agreed to by Stefan and Estelle.

The "belongs to" field shows the entire hierarchy of where that place
exists. In the future, you will be able to jump to another place in the
hierarchy using links, if you have access to that level of place. In future
versions, this will also be used to edit the location of a person or place
from the person or place profile.

**Comment by SCdF** [comment]
> The back button allows you to get back to where you came from. In the
majority of cases, this is the parent place. In two cases, where you came
from is not your parent place. This has been outlined in the spec and
agreed to by Stefan and Estelle.

This is not what you and I discussed. Specifically, I tried to be clear about the difference between a back button such as in a browser, and a link that goes to your parent, including the differences between mobile and desktop. We agreed that:
 - On mobile the `<` link at the top would go "back" (when I say back, I always mean like a browser back button). We discussed that it already works this way, but there are gaps in our Android-specific back button functionality, which we are addressing in #2820 
 - On desktop the user already has a back button, and the link would effectively replicate the current state of the belongs to link, but be at the top. Which is what this ticket is for. The belongs to link would change later to be a collection of breadcrumbs showing all parents.

If we are still not on the same page it would help if either:
 - We referred to it as a back button, and then didn't explain it's functionality, because the term "back button" already has functionality associated with it, because it's something the browser already has. It can then be implemented without any text, using `browser.history.back()`. I would then argue we shouldn't include it at all, unless there is evidence that on desktop people are not aware of how to use the existing native back button.
 - Stopped referring to it as a back button, and defined what it did concretely, based on inputs that don't include where you just came from[1]. I feel like we have already done this: it is a link to the parent place.

A lot of ink has been spilled over this feature, and I'm concerned that we keep circling back on old conversations.

[1] FWIW it is a technical challenge to introspect where you just came from, especially if you have to do it multiple times. You cannot get it from the browser for security reasons, even inside the same domain / website. We would have to store our own history as we went, presumably in a cookie or other form of local storage.

**Comment by diannakane** [comment]
It is the same as what we talked about, just described in a different way.
The spec hasn't changed.
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.qi8rme5a3bqd

In most cases "take me back" = "parent place." The spec describes the two
exceptions to that rule.

**Comment by diannakane** [comment]
Updated spec with @estellecomment to clarify behavior of the back button:

> Software back button takes you back to where you came from: it does the same thing as the browser back button, in both desktop and mobile (this is on purpose : people don’t necessarily use the browser back button on desktop or the hardware back button on mobile, so it makes sense that the app has its own navigation buttons). https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.qi8rme5a3bqd

We've removed the label next to the back button to make it consistent with mobile and easier to implement. Styling of mobile button doesn't change from the current. Back button in desktop RHS mockup here: https://zpl.io/28Bjam

![image](https://cloud.githubusercontent.com/assets/1675870/20171749/c7743420-a73a-11e6-9bd2-6e8c92ca6fbe.png)

**Comment by SCdF** [comment]
This could just be me, but that button looks like it collapses / hides the RHS. If it's just me then ignore, though I'd be interested to know if other people saw it that way. I wonder if having it and the icon and document name beside one another would help with that.
