### ISSUE TITLE
Pressing the HBB on mobile while filling a form should give same warning as when closing form (X)

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#3086]
Steps to reproduce:

1. medic mobile (alpha.dev)
2. Press tasks icon (Flag)
3. Select one of the items on the list >> Form open
4. Press the HBB
**Expected**: When the user press the close button on the form title bar, there is a warning popup. One would expect the same warning if the user presses the HBB since they are also exiting without finishing to complete the form:
![image](https://cloud.githubusercontent.com/assets/6979995/22358313/eb99702c-e4a2-11e6-8830-92fbdb7894c9.png)

**Actual** : App closes the form without warning.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by abbyad** [comment]
This seems relevant given that this was just reported again! Marking as scheduled.

**Comment by latin-panda** [comment]
Not a problem in CHT Android v1.5, CHT v15. Even clicking HBB multiple times, the confirmation modals displays

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/72f58211-7676-4d7a-aca6-0a4f697f15bc" />
