### ISSUE TITLE
Discrepancies in date and numeric translations

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#3336]
With release of https://github.com/medic/medic-webapp/issues/3282 in 2.10.3 dates are translated (with noted exception below), but we are not consistent throughout app in how we are dealing with numerals and dates. This issue will list some discrepancies and we can spawn off issues to deal with these individually as needed. The only blocker for a project is already a separate issue (#3335).

## Reported date is not translatable
From app settings: `  "reported_date_format": "ddd, MMM Do, YYYY [at] h:mm A",` the in between words are not translated. We may want to consider using translation keys here or specifying that the default date localization should be used for that locale.
![image](https://cloud.githubusercontent.com/assets/789512/24619590/775ff862-1868-11e7-9bf0-89608c34072a.png)

## Standalone numbers and phone numbers are not translated 
Just pointing out that these are not currently translated. We have yet to hear that these need to be translated, and as per #3335 it is prefered that numbers are _not_ translated.
### Outgoing messages
![image](https://cloud.githubusercontent.com/assets/789512/24619997/0f20c8c4-186a-11e7-886d-1b85403e4864.png)
### Contact summary
![image](https://cloud.githubusercontent.com/assets/789512/24618632/bbc4dd90-1865-11e7-8095-174a7cc22752.png)
### Relative dates (numbers in full date are translated)
![image](https://cloud.githubusercontent.com/assets/789512/24619473/18c82a7c-1868-11e7-8274-48cff150a796.png)

**Comment by sglangevin** [comment]
What happens if the project is using Bikram Sambat dates for outgoing SMS? Will those show up correctly in the Reports tab as Bikram Sambat dates? If we are going to consider an app-wide strategy for translation, we may want to consider splitting out the handling of dates so that we have more flexibility in how they display.

**Comment by alxndrsn** [comment]
No Hindi users will be using bikram dates AFAIK.

**Comment by garethbowen** [comment]
> Reported date is not translatable

In app_settings we have a date format and a datetime format which are hardcoded and not translated. These are passed straight to moment.js so I suspect we can't translate hardcoded words. Instead I think we should move these settings into translations so each language can define a different value, which will allow for translating hardcoded words, but also allow for completely different date formats per language which will be needed sooner or later.

**Comment by abbyad** [comment]
> Contact summary

This is the number of visits: `contact.profile.visits.of = {{count}} of {{total}}`, or in this case the Hindi `{{total}} में से {{count}}`

> Relative dates

I was just pointing out that even when the numbers in a date field were translated to Devanagari, the ones in relative dates were not, which is somewhat expected because we were not translating digits anywhere else in the app, except those done by moment.js (which is now fixed by 3335).

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
I keep coming back to this and getting confused by it. I think these are four separate issues and need to be raised individually. You've commented on some that you're not sure if they should be done, and some of these may have since been fixed.

@abbyad Can you please create an issue for each item that should be fixed and close this one out?

**Comment by abbyad** [comment]
Ya, in listing these I was stating the current state of affairs without specifying importance. I think our tech leads closest to projects most affected by this should weigh in.

cc @bishwas-medic, @sglangevin

**Comment by derickl** [comment]
Seems potentially related to #3192, #3245, #3219

**Comment by dianabarsan** [comment]
#7294 hopefully handled everything that's an app-formatted date, but none of the other number-formatting mentioned in the issue. 

We could edit to remove the "Contact summary" and "Relative dates" sections.

**Comment by garethbowen** [comment]
@abbyad With the improvements from Derick and Diana I think we should close this, and either create a new one with the remaining issues, or wait for a user/partner to request further changes. What do you think?

**Comment by abbyad** [comment]
Good plan. To summarize for posterity the following is the current status of what has been resolved, and the remaining ones are intentionally left as such, unless otherwise indicated with an issue:

- [x] Reported date is not translatable
- Standalone numbers and phone numbers are not translated
  - Outgoing messages
    - [ ] Scheduled message number
    - [ ] Patient ID in outgoing message #3245
    - [ ] Phone number displayed in app
  - [x] Contact summary
  - [x] Relative dates (numbers in full date are translated)

If any of this is wrong let me know and I'll update.
