### ISSUE TITLE
"Next" button does not appear on click "New Person" when creating a new district...in Firefox

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#3397]
Tested on Local Install
Works in Chrome but not in Firefox
Steps:
1. Deploy app (with Firefox)
2. People's tab >> Click New District on the LHS FAB
3. Fill in district name 
4. Click 'New District' button
5. Expected (and happening with Chrome) >> The 'Submit' button gets hidden and next button gets visible
6. Observed: >> Submit button still there. No 'Next' button

**Comment by garethbowen** [comment]
This is when using the default generated new district form.

**Comment by sglangevin** [comment]
We're generally not deploying the default forms right now. We are deploying the Standard version of the forms or customized forms that are built for a specific partner.

**Comment by ngaruko** [comment]
So....I guess we can close/dismiss this @sglangevin ?

**Comment by sglangevin** [comment]
You'd have to retest with a fresh instance - I believe @henokgetachew is uploading the Standard contact forms on all new instances.

**Comment by garethbowen** [comment]
Please reopen if it happens again.
