### ISSUE TITLE
Loading a form in firefox creates a mysterious error message

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#3445]
E.g. http://localhost:5988/medic/_design/medic/_rewrite/#/reports/add/postnatal_care

Form seem to work fine, but the following appears in the console:

<img width="762" alt="screen shot 2017-05-04 at 23 40 32" src="https://cloud.githubusercontent.com/assets/191496/25712074/2f085f90-3123-11e7-8e75-1e796dca9dd9.png">

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
Weird!

**Comment by garethbowen** [comment]
Closing: very minor and only outputs in Firefox.
