### ISSUE TITLE
HBB can take you back to the login screen if you logged in that session

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#3520]
Hardware back button is all sorts of broken right now on android, e.g.: https://github.com/medic/medic-webapp/issues/3461, so I suspect this is a regression.

**Comment by latin-panda** [comment]
Not navigating back to the login in CHT Android v.1.5. It was fixed [here](https://github.com/medic/cht-core/blob/64fd3b2d315fc8e060f157940fb41fcd446af750/webapp/src/ts/services/navigation.service.ts#L56)
