### ISSUE TITLE
Move d3.js-using stuff into a separate angular module

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#3869]
To avoid CHWs having to download and load `d3.js` when they never actually need the code, move it into a separate angular module (in a separate JS file?)

**Comment by garethbowen** [comment]
The perfect solution to this is to create a lazily loaded component for anc analytics and reporting rates which contains all the code, templates, styles, and dependencies that are only needed by those pages. Unfortunately this is only natively supported in angular 2+. There are ways to do through libraries it but it's probably overkill when we're planning to move off angular 1 in the medium term anyway...

For now we can just configure browserify to create a d3 dependency bundle which is only included on the pages that need it which will get us half way there...

**Comment by kennsippell** [comment]
Note on performance impliations of this:
Current master minified script weight: 2.66 MB
Minified script weight without d3, nvd3, angular-nvd3: 2.25 MB

@SCdF mentioned d3 may just be for legacy use cases and can be easily removed

(Also 4% of css)

**Comment by garethbowen** [comment]
Moved to 3.11.0 as it's being removed as part of dropping the reporting rates feature which is happening with the angular migration.

**Comment by garethbowen** [comment]
Feature dropped.
