### ISSUE TITLE
Write an e2e test around select2 functionality

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#3900]
select2 is very fiddly and seems to break a lot.  A pair of e2e tests with a form containing only a single select2 (and no translations or other unrelated stuff) would be really helpful.  We should test filling the form in for the first time, and editing an existing report.

**Comment by garethbowen** [comment]
@alxndrsn PRs welcome.

**Comment by vimemo** [comment]
Same conditions, same priority/status.
