### ISSUE TITLE
Implement a quick DHIS2 connector in Sentinel

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#4015]
- Decide whether to use transitions or schedules
 - Consume dhis2 forms, map them and push them to dhis2
 - Pro mode, deal with retries?

More details to come.

**Comment by garethbowen** [comment]
We could also have a transition to generate the docs, and a schedule to submit them for the best (and worst) of both worlds.

**Comment by SCdF** [comment]
The plan:

Create a sentinel transition that filters on DHIS2 documents and:
 - Takes their fields and uses config to convert them into a DHIS2 compatible data structure
 - Stores that data structure (for historical reasons) against the document as a log (when, rev, data)
 - Attempts to send that data to DHIS2
 - On success, add some kind of success status to the document (see below)
 - On failure, count that as a transition error, and ideally pull out DHIS2's / the networks's reasoning into a displayable error message

Also, add a button that allows you to retry a failed push to DHIS2. This would work by removing the errored transition note in the document (which, as it's a change, will in turn re-submit it through sentinel). This would either be on each individual report, or a mass button somewhere that does it for all of them. Whichever is easier. This button would be hidden unless you have configured DHIS2 integration.

Also, consider adding a schedule that automatically retries failed DHIS2 pushes every few hours (ideally only those that failed due to network issues).

Outstanding technical questions:
 - Best way to show a success of a document. Might just be adding a property onto the root object and exposing that in a DHIS2 status area when viewing the report?
 - Does the green / red dot on reports get affected by transition failures? Or just by some other validation?
 - What are sentinel's rules for re-running transitions after failure. If a transition fails and you modify the document, will that transition run again?

Next steps:
 - Answer those technical questions
 - @michaelkohn to provide (publicly or privately) the DHIS2 enketo form and the mappings in some format

… and then I think we can get cracking.

**Comment by garethbowen** [comment]
DHIS2 integration has been done in a different way.
