### ISSUE TITLE
Add big warning or break grunt dev if patches have not been applied

### ISSUE THREAD

**Issue by alxndrsn** [medic/cht-core#4225]
If you forget to run `grunt mmnpm` (or presumably, `grunt exec:applypatches`) before running `grunt dev`, you can end up with some surprising regressions while developing.

It would be very helpful to check if the patch step has been performed and either refuse to start `grunt dev`, or print a big warning when this is the case.

**Comment by SCdF** [comment]
`grunt dev` doesn't exist anymore, and I thought (the old) `grunt dev` ran `mmpm` for you? Do you mean a different grunt target?
