### ISSUE TITLE
Contact parent (and .parent.parent) objects are not hydrated

### ISSUE THREAD

**Issue by derickl** [medic/cht-core#4262]
The expected behaviour when accessing contact parent object is to have access to all parent attributes as per pre-2.13.

From 2.13 (also seen in 2.14-beta), the parent and parent's parent objects are not hydrated in the task rules. In the existing task rules, we rely on these parent properties to customise logic. 

As of now, these  rules could be in an unusable state'.

LG KE will be rolling out 2.13 next week and it would be great having this fixed in the course of the week.

**Comment by sglangevin** [comment]
@derickl please provide more information. Where are you accessing these parent properties? Please include config examples to explain what you are trying to do that no longer works.

**Comment by derickl** [comment]
A case in point is that I need to do under one follow ups.

For this I'll need to only pick person contacts, belonging to a family

```
if (c.contact.type === 'person' && c.contact.parent.type === 'clinic'){
/*TASK STUFF*/
}
```

Given the parent attribute is not fully hydrated, `c.contact.parent.type` will evaluate to undefined and that condition fails.

**Comment by sglangevin** [comment]
For this one, please use `c.contact.parent.parent.parent` as a replacement. Per our conversation on slack, sounds like there might be some cases where a direct replacement isn't possible, so we need to identify those and look for workarounds. Hydrating all of the lineage in the task rules is a performance hit and I want to avoid it if possible. It is being considered, but let's see what workarounds we have for now.

**Comment by binokaryg** [comment]
In ebpp-indonesia (growth monitoring), there is a requirement to show Parent/Household names (`parent.name`) in the task title and Parent/Household's contact information (`parent.parent_number, parent.primary_caregiver_number`) in the task summary. This information would be helpful in identifying the children before filling the growth monitoring form. From 2.13 onwards, I am not able to get these values in `rules.nools.js` until the first growth monitoring is filled. When the first GM form is filled, I can pull this information to the form and then later access in subsequent GM forms for the same child.

**Comment by sglangevin** [comment]
Slight update to my previous comment - you will need to check for each parent along the way, so something like `c.contact.parent && c.contact.parent.parent && c.contact.parent.parent.parent` - you could also consider writing a function if that check is used a lot.

For @binokaryg, you should be able to use the contact-summary to get this information about the patient and feed it into the form as a workaround for now. So instead of displaying that information on the task summary screen, you could display it on the first page of your form. Would that be sufficient for now?

**Comment by binokaryg** [comment]
Yes @sglangevin, I am showing the information on the first page of my form for now by pulling it from `inputs/contact/parent` group in the form, which is better than nothing. If I could also show the clinic name in the task title, that would be great, but it does not seem to be possible yet. Thanks for your help.

**Comment by garethbowen** [comment]
@derickl Did the workaround from Sharon work? Can we close this or is there anything more we can do here?

**Comment by kennsippell** [comment]
@binokaryg In medic-conf 3.x, it is now possible to show the parent's name in the task title by passing the parent data through the form. https://github.com/medic/medic-conf/issues/205

**Comment by kennsippell** [comment]
In 3.8, we are looking to re-evaluate how we generate tasks. This could be kept in mind for that process, but imo until some of the issues in our task system are solved. hydrating all contacts will significantly bloat our memory use and could really hurt some of our heavier users. Refer to https://github.com/medic/medic/issues/5540 for more details.

**Comment by kennsippell** [comment]
After task/targets refresh in 3.8.1, recommend closing this as `won't fix`. Hydrating all contacts before passing them into nools would be a very costly performance change.

**Comment by MaxDiz** [comment]
closing this issue based on @kennsippell recommendation. May be worth revisiting in the future if we change how nools is utilized
