### ISSUE TITLE
Items beneath menu can show through

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#4272]
Text from below the Submit Report menu on the Reports tab LHS shows through ever so slightly on the top edge if there is a scroll bar:

## Menu on Reports tab LHS shows text from beneath

![image](https://user-images.githubusercontent.com/789512/37064484-1d5b4094-216b-11e8-9425-fe68ac4a8066.png)

## Menu from People tab RHS looks normal
![image](https://user-images.githubusercontent.com/789512/37064642-c170d9aa-216b-11e8-956b-f31cfc5c1823.png)

As seen at 100% on Chrome version 64.0.3282.186 on Windows 10. Cannot reproduce if the zoom is set to 90% or 110%, or if the scroll bar is absent with less items. I would put this to a lower priority than 3 if we had one.

**Comment by latin-panda** [comment]
Closing. The actionbar was removed, and this is not a problem in the FAB.
