### ISSUE TITLE
Styling updates to people & reports pages on desktop

### ISSUE THREAD

**Issue by sglangevin** [medic/cht-core#4347]
Small updates to page styling. Broken up by page below. Can be done anytime - doesn't rely on other changes to the UI.

## People:
- [ ] Add a gray gear icon to the top right of the profile card. The icon is 24x24px, color is #A7A9AC, and it is located 20px from the top edge of the card and 20px from the right edge of the card.
- [ ] Include breadcrumbs for any person or place profile for which the logged in user has access to the parent information. This moves the top profile card down. Only move the card down if breadcrumbs are displaying. Breadcrumbs are clickable links, 16px, blue (#007DC7) and located 20px below the top bar and 20px above the top profile card. They should wrap if the text is longer than the profile card width. Breadcrumbs should list all levels of the hierarchy above the profile you are viewing that the currently logged in user has access to. Between each level is a > symbol in our normal dark gray (#333333). See Invision for more details.

## Reports:
- [ ] Add a gray gear icon to the top right of the profile card. The icon is 24x24px, color is #A7A9AC, and it is located 20px from the top edge of the card and 20px from the right edge of the card.
- [ ] ADD IN SOMETHING ABOUT BUFFER SPACE OR TEXT WRAPPING
- [ ] On the LHS, add two new buttons at the top of the list of reports for select mode and for export. Export should function exactly the same as it does currently and select mode functionality & styling will be updated in a later issue [issue number]. These two buttons are in a box that is at the top of the list of reports, which is the full width of the LHS and 40px high. 
- [ ] The select icon is 20px in from the left edge, followed by the word Select. After Select, there is 10px of space, then a 20px tall 1px wide vertical line (#D1D3D4), then 10px of space, then the export arrow icon followed by the word Export. Icons are 24x24px and #A7A9AC. Text is 14px (H5) bold and #777777.
- [ ]There is a 3px gray line at the bottom of the box (within the 40px height, not below). It is #A7A9AC.

See the [invision prototype](https://invis.io/E4FQKC4A2Y6#/277821159_05-1_People_1440_-_Person_Main) for more details.

**Comment by michaelkohn** [comment]
@n-orlowski please see if there is anything still relevant in this ticket and if not, please close it or split off bits to a new ticket.
