### ISSUE TITLE
Update enketo-core to 5.9.2

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#4386]
Going to the latest caused issues with the db-object widget. I think we need to [merge the upstream changes into our xslt library](https://github.com/medic/enketo-xslt/compare/master...enketo:master).

Also ensure jquery gets bumped in sync with the enketo jquery dependency.

**Comment by alxndrsn** [comment]
# TODO
- [ ] review enketo-transformer changes (`1.21.3` -> `latest`)

**Comment by garethbowen** [comment]
This has missed out on the 3.0.0 release - bumping to 3.1.0

**Comment by kennsippell** [comment]
This enketo-core bump will also bump bootstrap-datepicker. As of such, `webapp/src/js/enketo/bootstrap-datepicker.hi.js` can be deleted and references replaced in `webapp/src/js/enketo/main.js`. See #4830.

**Comment by garethbowen** [comment]
I haven't found the time to work on this so I'm going to unassign it from myself. The ideal solution is to do the XHTML -> HTML step on the server (#4450) which makes upgrading much easier (now and in the future) and also improve client side performance. This requires a native XSLT library to be included in the server build so should be discussed with infrastructure.

**Comment by garethbowen** [comment]
Moving to 3.9.0. The PR is almost there, but I worry that it may be a destabilising change that needs to be tested against a range of configurations.

**Comment by garethbowen** [comment]
The PR is still a while from being ready for AT so I'm moving this out of 3.9.0 so it doesn't block the release.

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by garethbowen** [comment]
Closing as ancient. Upgrading to latest enketo-core is covered by #6345
