### ISSUE TITLE
Configuration code `reporting_unit` shown to user

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#4389]
As part of #3627 the phone number for scheduled messages is determined when the message is ready to be sent. As a result there is no number associated to each message in the Reports tab, but we are showing `reporting_unit` in the UI:

![image](https://user-images.githubusercontent.com/789512/38500154-938da8ac-3bd7-11e8-9f7d-e2a20edb7810.png)

Users would not know what `reporting_unit` is, so we should either show:
1) the phone number for that person at the time the page is loaded. _This would be consistent with previous versions, but in reality not incredibly useful._
1) the name of the person at the time the page is loaded, along with a phone number if available. _This makes it more useful to know _who_ the message is going to._
1) a generic translation label shown instead. For instance, `reporting_unit` could be "patient's CHW": eg "**scheduled** in a month to _patient's CHW_". This may be easier to implement for now, and still useful.
1) Combine all of the above for full context, name, and number.

Curious what others think about these, cc @amandacilek. From my perspective option 1 just restores previous functionality, and option 2 restores functionality but in a more useful way. Option 3 may be simpler to implement, and perhaps more useful than the name + number anyhow, so that may be suitable to close this off for 2.15.

Tested on beta.dev running `2.15.0-beta.4`.

Created as a new issue, but this could have been part of AT for https://github.com/medic/medic-webapp/issues/3627.

**Comment by garethbowen** [comment]
@abbyad I think I've found this report but it's not saying "reporting_unit" any more. Can you link the actual report you found? Can you reproduce it? Does it magically come right after some time? Maybe sentinel is attaching the reporting unit between when you saw it and when I did...

**Comment by garethbowen** [comment]
I'm not sure how this is possible... did you photoshop the screenshot?! When formatting the data record the messages (including the recipient) are generated synchronously. `reporting_unit` is converted into `doc.from` which should always be populated.

**Comment by abbyad** [comment]
The only photoshopping I did was removing the phone number... I can see the number showing well for SMS reports, and fails on [app form](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/8d28d7ec-7091-483f-b2ad-350151847a0b) -- but only when the user's associated contact doesn't have a phone number. This is therefore mostly a config issue because with https://github.com/medic/medic-webapp/issues/3412 these messages should go to patient's chw, not `reporting_unit`.

Lowering the priority as this is not a blocker anymore, but should we perhaps consider putting a red note if there is no number available to receive the messages? 
cc @amandacilek

**Comment by garethbowen** [comment]
@abbyad Is it ok if we move this out of 2.15.0?

**Comment by abbyad** [comment]
Yes, as long as we fix the config (which relies on #4410) it makes sense to push this one out.

**Comment by garethbowen** [comment]
Done, thanks.

**Comment by amandacilek** [comment]
Hm, I prefer option 2. 

I agree that option 3 is at least better than the current "reporting_unit" but it still sounds a little confusing. Would "patient's CHW" be true and applicable in all cases? Or would we need a series of phrases depending on the situation?

Not quite sure I understand Marc's second question 
> should we perhaps consider putting a red note if there is no number available to receive the messages?

Does this mean unknown number/recipient? Or does it mean error/the message will not be sent? If the scheduled message won't be sent that seems like an error we should surface in an even more prominent place, right?

**Comment by abbyad** [comment]
> I agree that option 3 is at least better than the current "reporting_unit" but it still sounds a little confusing. Would "patient's CHW" be true and applicable in all cases? Or would we need a series of phrases depending on the situation?

If this were a generic thing, we would have set translations that could be customized. For instance, `reporting_unit` could be "Submitter", `primary_contact` could be "Primary Contact". For projects that have different terminology we could easily have project specific translations (eg "Patient's CHW" instead of "Primary Contact"). Options for this may come out of how we access the primary contact info as part of #4410.

> Does this mean unknown number/recipient? Or does it mean error/the message will not be sent? If the scheduled message won't be sent that seems like an error we should surface in an even more prominent place, right?

That means both 😄 If there is no number for the recipient the message will not be sent. @amandacilek, this is not a rush for this version, so we have a bit more time to design this -- is that something you can take the lead on?

**Comment by sglangevin** [comment]
For this release, we should focus on maintaining current functionality, which means we should display the phone number that the message will be sent to. How were we handling cases where there was no phone number in previous versions? Did we fall back on a different number? I'd prefer we just continue with previous functionality and we can add this to the backlog of items to improve in future versions.

**Comment by garethbowen** [comment]
Closing as ancient. Please reopen if it happens again.
