### ISSUE TITLE
CPU Usage of the app has increased and trainings now require increasing instance size

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#4448]
I will update this issue with more details as I do more investigation.
This affects versions 2.13 and beyond.  Whenever number of trainees is greater than 30 or 40, the instance becomes very slow if using m3.medium on AWS.  Increasing instance size for the duration of the training is required right now to alleviate the issue.

**Comment by sglangevin** [comment]
Marking as triaged - awaiting further details from @henokgetachew.
