### ISSUE TITLE
Hook feedback up to monitoring

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#4482]
We're currently ignoring feedback docs.

We should watch for them and push them to a slack channel, or to email, or something that people will action.

Probably the simplest is @henokgetachew 's existing monitoring.

**Comment by garethbowen** [comment]
AT this at the same time as #6133

**Comment by ngaruko** [comment]
LGTM.
Tested along with #6133 
![image](https://user-images.githubusercontent.com/6979995/80051926-88b95c00-856d-11ea-9e69-e0457e7592ba.png)
Good to merge @garethbowen

**Comment by garethbowen** [comment]
Merged.
