### ISSUE TITLE
Make it easier to debug forms

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#4748]
@abbyad reports that configurers often want to debug xform values and follow the instructions in [this post](http://medicmobile.cloud.answerhub.com/questions/209/how-can-i-debug-the-values-of-a-xform-in-progress.html).

Find a way to make it easier to access, such as a button to display the string on screen. The hard part is going to be working out how to show the button only when needed.

**Comment by kennsippell** [comment]
Debugging a form today, I made a new bookmark in Chrome with url as `javascript:(function() { const scope = angular.element('/*/div[id=report-form]/*/form').scope(); if (!scope) angular.reloadWithDebugInfo(); else console.log(scope.$parent.form.getModel().getStr()) })()`. 

Clicking the bookmark dumps debug information. An idea for an out-of-code solution. Maybe wouldn't work great on mobile.

![screenshot from 2018-10-23 11-47-39](https://user-images.githubusercontent.com/9014751/47373325-990f2300-d6b9-11e8-8273-92f93ce8e506.png)

**Comment by garethbowen** [comment]
This got harder again in 3.7 when the controllers were renamed so prioritising so we can decouple the magic string from the implementation details. Instead of a button suggested above we could instead just have a magic global function that just works and assume that people doing this will be comfortable with using the console. This isn't great for mobile users though.

Consider a range of options for exposing this debugging information.

**Comment by abbyad** [comment]
> [...] magic global function that just works and assume that people doing this will be comfortable with using the console. This isn't great for mobile users though.

I think a global function would be great for now. There would be no loss in functionality since the current method on mobile relied on being connected to a computer's dev console. We can revisit this if we need an in-app debugging in the future.

**Comment by kennsippell** [comment]
Ready for AT on `4748-debug-form`. 

When a form is open within the webapp (new contact, new report from contact page, clicking a task), type `window.debugFormModel()` in chrome or firefox's developer console. You should see an xml string written to the console with a bunch of data for the structure of the form.

**Comment by ngaruko** [comment]
LGTM.
Back to @kennsippell  for a merge!
![image](https://user-images.githubusercontent.com/6979995/79282774-27a8dd00-7f0a-11ea-807a-4db361a3fe1b.png)
