### ISSUE TITLE
Allow supervisors to see CHW targets and support display of aggregate targets widgets

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#4839]
[Product initiative detail ](https://docs.google.com/document/d/1EQHQI11XqI8aQeUsnmlrD3ny83fj5N6MZATrLzsm_-I/edit#heading=h.q31g948sivit)

Read more details and view additional screenshots in the MVP deck: https://docs.google.com/presentation/d/1AbOxkGgggUoI0QzRmwVqfX0AqC6aG6CByNd-CzdRgaI/edit?usp=sharing

**TECHNICAL STRATEGY**

We do not have the capacity for managers to see all of their CHW’s patients and documents (setting aside current unsupported/experimental workflows), without some kind of 100x performance improvements. The goal of this MVP is to provide a way for supervisors to view CHW performance data without requiring all of the patient reports offline. We hope to enable supervisors to have much smaller data sets and still accomplish what they need to do.

A clearly helpful thing is exposing CHW’s tasks and targets to their supervisors. This gives supervisors insight into what the CHW is doing, needs to do and has done, without requiring that they can see all of the patients and their documents. This MVP focuses on targets first - investigating how we can periodically write a CHW's targets into a document that can be synchronized to the supervisor's device.

Note to QA team: we should proactively test with high-volume instances.

**DESIGN OVERVIEW**

Note: All of the following require supervisor access/visibility to CHW targets in order to work.

**Support new performance condition card on CHW profile**
- Should be just adding another card type to the contact summary
- The data is based directly on CHW targets and is subject to the same limitations as the widgets/calculations on Targets
- The time period of the data will match what we already have, meaning we will only support data from the most recent month/time period
- As usual, the exact metrics displayed on the card and the total number of metrics displayed will be configurable per partner/project

**Ability to display targets last updated date on performance card**
- The “Date targets last updated” gives crucial context as it is the date when the performance data was last updated (i.e. “This information was true as of this date”)
- The targets "report" gets generated every 24 hours regardless of whether there is a new action by the CHW
- Should be styled just like any other condition card field and should appear first in the condition card

**Support display of aggregate targets widgets**
- Display aggregate performance metrics across all of a supervisor’s CHWs
- Calculating averages may need to be a new widget type??
- Some values may be totals, while others may be averages (total / # of values)
- Should support aggregate values on both count widgets and percentage widgets (depends on what gets recorded in the CHW report)
- Should also support goals - if the group of CHWs is performing on average below the goal, the value will be highlighted in red. If the group of CHWs is performing on average above the goal, the value will be highlighted in green. 
- If there is no goal, the value should be the default black
- Stefan says: Targets page is just like it is now, but unlike CHWs where targets are based on reports completed, Supervisor targets are based on CHW target documents. Should fit the current way targets get calculated (ie nools)
- Marc says: Seems like we need to store numerator and denominator so that we can calculate totals. We also need a way to add numbers to the target, as opposed as counting every target instance as a 1.

![screen shot 2018-09-19 at 12 43 09 pm](https://user-images.githubusercontent.com/26235957/45777081-a09a6280-bc09-11e8-88fc-dcd2a229f632.png)

**Comment by amandacilek** [comment]
Here are some additional notes / options from @SCdF :

- When CHW Nools creates targets, write them to CouchDB documents and have those sync to supervisor phones
- - Pros: simple; raw targets may be useful for analytics
- - Cons: lots of small docs; may perform just as badly (network / sync time / PouchDB performance) as having the whole doc; it’s not clear analytics could usefully parse raw targets

- Summarize CHW targets on their phone periodically (once every 24hrs?) into a single document per month, and sync to supervisor phones
- - Pros: much less data to move around
- - Cons: can be more out of date (eg by 24hrs); might not be as useful as raw data, needs to be thought on; presumes targets still only care about month-long / month-relevant targets, needs to be validated

**Comment by MaxDiz** [comment]
@garethbowen wondering if we should break this out into a separate issue. There have been a number of different requests for exposing timestamp data recently. Would it be worth exploring a more comprehensive solution?

> Ability to display targets last updated date on performance card- the “Date targets last updated” gives crucial context as it is the date when the performance data was last updated (i.e. “This information was true as of this date”)

**Comment by garethbowen** [comment]
@MaxDiz Currently target information on the phone is completely up to date with replicated data. For example, if a CHP submits a visit report for a patient then the "visits this month" target should immediately show one more visit. The request you quoted is, as far as I can tell, specifically about supervisor target widgets which may have been generated on the server and replicated down so we need to expose the date the information was generated. This only makes sense when the server side target generation feature exists so I don't think it can be done before the rest of this issue.

I'm really interested to hear about the other feature requests. Can you Slack me with details?

**Comment by dianabarsan** [comment]
Ready for AT on `4839-aggregate-targets` - along with #4840.

Some information about the Target Aggregates page:
- There is a new permission `can_aggregate_targets` which makes the new page available
- it is available for both online AND offline users if they are configured with a home place(!)
- It should only aggregate the current month's targets
- it should aggregate correctly when target reporting intervals are customized (via the uhc setting)
- it should aggregate target docs belonging to the primary contacts of the places parented by the user's home place
- Will only display targets that have a truthy value for the `aggregate` attribute
- the aggregate value for a count target without goal will be the sum of all `pass` values for every chw
- the aggregate value for a percent target without goal will be <sum of numerators> * 100 / <sum of denominators>

Configuration updates:
- Medic-conf branch: `4839-target-aggregates`
- Targets now allow a new `aggregate` property. Only targets that have a truthy value for this attribute should appear in the Target Aggregates page
- You will need to run the branch medic-conf to push this updated configuration.

Targets on the contact detail page:
- A new variable is made available to the `contact_summary` configuration function, called `targets`.
- It represents the current `target` document, hydrated with the configuration of every target value it contains.
A detailed example of the target doc can be found here:
https://github.com/medic/medic-docs/blob/master/development/db-schema.md#targets

Following this example, the `target` variable would look like this:
```
{
  "_id": "target~2000-01~user-contact-guid~org.couchdb.user:agatha",
  "type": "target",
  "user": "org.couchdb.user:agatha",
  "owner": "user-contact-guid",
  "updated_date": 523435132468,
  "targets": [
    {
      "id": "deaths-this-month",
      "translation_key": "my_target_title",
      "type": "percent",
      "goal": "20"
      ...
      "value": {
        "pass": 0,
        "total": 15
      }
    },
    ...
  ]
}
```
- the configurer can choose what to do with this information: create a new card with one field per target or multiple cards, or simply ignore.
- when there is no `target` document to pass to the `contact_summary` function (for example when viewing a non-chw contact), the value will be `undefined`.

More information about config updates here: https://github.com/medic/medic-docs/pull/177

**Comment by kennsippell** [comment]
Optional nit -- When an online user navigates to the Analytics tab, should they be shown the "target aggregates" instead of prompted to choose. "targets" is disable for this user and is not really a valid option for them.

**Comment by dianabarsan** [comment]
@kennsippell I intentionally didn't touch targets at all. 
We could add this separately, though :)

**Comment by garethbowen** [comment]
I've merged the medic-conf PR ready for its release. This is a backwards compatible change so it's safe to defer the cht-core PR if necessary.

**Comment by ngaruko** [comment]
Permissions and related error messages seem to be different for the two tabs. The 'targets` page has the classic message (`Targets are disabled for admin users. If you need to see targets, login as a normal user.`) while the `aggregates` page has `No target selected.` 
![image](https://user-images.githubusercontent.com/6979995/81133478-e013ef00-8fa5-11ea-99dc-e9dc33b1d218.png)

Is this intentional @dianabarsan ? Or are admins allowed to see these aggregates as well?

**Comment by dianabarsan** [comment]
@ngaruko yes, admins are allowed to see aggregate targets as well.

**Comment by ngaruko** [comment]
LGTM then @dianabarsan .
Please feel free to merge and close.

**Comment by dianabarsan** [comment]
Merged.
