### ISSUE TITLE
Remove continuous replication code from the API changes endpoint

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#4874]
Breaking off this task from #4805 into a separate issue.

* [x]  Remove continuous replication code from the API changes endpoint

**Comment by dianabarsan** [comment]
This is ready for AT on `4874-remove-continuous-replication`.

**Comment by ngaruko** [comment]
Tested upgrade from 3.3.0 to branch.
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/6979995/170412215-0a05e2b3-2742-463c-8c78-a2b531f7cd77.png">

**Comment by dianabarsan** [comment]
@ngaruko 
Did you also try the upgrade as an offline user, where the user gets the popup when upgrading from 3.3 to latest? That's what this change affects.

**Comment by dianabarsan** [comment]
Merged to `master`.
