### ISSUE TITLE
When builds fail the script to upload failure info is erroring because of AWS Access Key

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#4877]
When a build fails we are uploading images, reports, and logs to s3. However, there is an error being show now that shows `The AWS Access Key Id you provided does not exist in our records.` Likely the key is out of date and needs updated. 

Assigned SRE for AWS access update. 

**Steps to reproduce**:
Fail a Webapp build

**What should happen**:
The images, reports, and logs should be uploaded to S3

**What actually happens**:
An error is shown indicating the upload failed and `The AWS Access Key Id you provided does not exist in our records.`

Failed Build log-  Search for the error shown above to see in the travis log.
https://api.travis-ci.org/v3/job/438953135/log.txt

**Environment**:
Travis-ci

**Comment by garethbowen** [comment]
@henokgetachew This is becoming a real pain and should be a quick fix - could you have a look when you get on please?

**Comment by garethbowen** [comment]
@henokgetachew Here's the configuration: https://github.com/medic/medic-webapp/blob/master/.travis.yml#L24-L26

Here's the commit which added it: https://github.com/medic/medic-webapp/commit/a1f26bd75deeb395f7d314e7d2dcbfc11481ae60

**Comment by kennsippell** [comment]
@henokgetachew @Hareet Any updates or ETA on this one? Would be very nice to get access to this data from test runs.

**Comment by henokgetachew** [comment]
I have taken care of this.  Let me know if you still run into issues.

**Comment by garethbowen** [comment]
@henokgetachew On a recent build we got this:

> upload failed: tests/logs/couch.log to s3://medic-e2e/BUILD_14897/JOB_14897.2/couch.log An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

And the upload doesn't exist in the upload folder. Is there something we need to change on the travis config?

**Comment by henokgetachew** [comment]
It looks like this has been broken for a while.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/3198821/51741673-a5d05800-20a8-11e9-8977-86ef64f3b356.png">

The travis change made to the repo is found here: https://github.com/medic/medic-webapp/pull/3975.
This means that this change never worked(?) (cc: @ngaruko).  I have just regenerated new keys and also given an account for @kennsippell to be able to fix this.  I'll get to it on Monday otherwise.

**Comment by kennsippell** [comment]
I'm stuck at `Either user is not authorized to perform iam:ChangePassword or entered password does not comply with account password policy set by administrator` using a 20 character password with lowercase, uppercase, numbers, and special characters. Let's look Monday then.

**Comment by garethbowen** [comment]
@henokgetachew The most recent files uploaded to s3 were uploaded in July 10th 2018 so it definitely worked after that PR you linked.

![screenshot from 2019-01-28 09-54-31](https://user-images.githubusercontent.com/2064938/51806758-dc91b280-22e2-11e9-9b02-def22cb62252.png)

https://s3.console.aws.amazon.com/s3/buckets/medic-e2e/BUILD_11972/JOB_11972.2/test-results/?region=us-east-1

**Comment by garethbowen** [comment]
@henokgetachew This is still causing issues for us. Do you think you'll be able to find the time to look at it soon?

**Comment by garethbowen** [comment]
Thanks @Hareet ! This is awesome.
