### ISSUE TITLE
Don't delete user-settings when deleting users

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#4889]
When deleting users we remove them from the user db and also [delete their user settings in the medic db](https://github.com/medic/medic-webapp/blob/master/api/src/services/users.js#L374). This is fine but it makes it hard for analytics later on because then we can't work out who was a user once.

Change this to instead set a flag on the user settings that the user is inactive and record the date they were deleted.

Spawned from this issue: https://github.com/medic/medic-projects/issues/1894

**Comment by latin-panda** [comment]
On this ticket:
1.. Delete the user-setting from _User DB (prevent login of un-existing users)
2.. Keep the user-settings from Medic DB and add new property flag. Even though it has a copy of the roles, permission checks appear to be done against User DB (in case of bypass) plus login already blocked.
3.. On user create, we check if settings from Medic DB already exist and block user creation.

**Comment by SCdF** [comment]
This is ready for AT in `4889-dont-delete-user-settings`.

**Comment by ngaruko** [comment]
LGTM
Feel free to merge @latin-panda (once conflicts on the branch are resolved )

**Comment by dianabarsan** [comment]
Moving to 3.10, as it's been merged into master before `3.10` was branched out.
