### ISSUE TITLE
Clean up the horti staging database

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5129]
The horti staging db ( https://staging.dev.medicmobile.org ) stores all our published artefacts so they can later be installed. Currently all tags (released versions) and branches (features in development) get published there and stored indefinitely. Once a branch gets merged/released there's no need to keep the build artefact around any more. Currently it's using 35GB which costs money and clogs up the horti UI with old branches.

Find a way to purge (or delete if purging isn't available) old feature branches. The simplest way is simply to delete them 3 months after the latest release. Be very careful not to delete tag releases.

If purging works then also update the `scripts/travis/cleanup.js` to purge instead of deleting the testing releases.

**Comment by SCdF** [comment]
> Be very careful not to delete tag releases.

FWIW the build server already blocks this for releases and betas via `validate_doc_update`. I have no idea if that function runs for purges though, I imagine not?

**Comment by garethbowen** [comment]
Prioritising so as to save some money on hosting fees. It should be simple enough to do...

**Comment by garethbowen** [comment]
Merged. No AT required.
