### ISSUE TITLE
Can't set breakpoint in lambda functions inside sourcemap files

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5206]
For webapp codebase in developer builds, I can't set a breakpoint in this function in Chrome dev tools:

```
    const func = () => {
       alert('sad');
    };
```

but I can set a breakpoint in this function:

```
    const func = function() {
       alert('happy');
    };
```

I believe this is because of how browserify generates our sourcemap. As we move to ES6 and increase our use of lambdas, I often can't debug a code path. I end up changing lambdas to the `function` syntax, re-building, and then debugging until I hit the next lambda. I find this hurts my productivity.

**Comment by garethbowen** [comment]
I think the solution is dropping browserify...

**Comment by garethbowen** [comment]
Closed as this will be fixed by dropping browserify.
