### ISSUE TITLE
Show dialog when user clicks "Sync Now" in hamburger

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5207]
When somebody manually triggers a sync through the hamburger menu, we should improve the feedback loop to users by opening a dialog which communicates in-depth details of the sync.

Some suggested data to include in that dialog:

* Current status of sync
* Time of last sync
* Progress of current sync (number of read/writes)
* A cancel button
* If the sync fails, detailed errors with troubleshooting tips

**Comment by abbyad** [comment]
One difficulty I see with the Sync Now button is that it closes the menu, so you don't see the result of sync. I was going to open a separate issue for that, but think it could be related to this one since it relates to the feedback loop when using that feature. 

To me, the "sync now" is like the pulling down interaction to refresh a browser page or list of emails, and I think that a dialog would be cumbersome so doesn't require much more info. @kennsippell was this issue opened before seeing the output of this [improvement to the sync status](https://github.com/medic/cht-core/issues/3977#issuecomment-564483170)? Which info do you think it still important to show here?

**Comment by kennsippell** [comment]
@abbyad Yes, this issue was significantly impacted by the fix for https://github.com/medic/cht-core/issues/3977.

When the user manually clicked "Sync Now", I personally feel that we should strengthen the  feedback given to the user regarding the outcome of that manual sync -- particularly when that sync fails. As you say, a modal dialog maybe isn't necessary but some UI indication does seem helpful to me. Another option may be a "sync complete" or "sync fail" overlay that appears for a second. 

This is all anecdotal only and I don't have a specific user scenario in mind here, nor can I speak to how this should be prioritised.

**Comment by n-orlowski** [comment]
<img width="786" alt="Sync" src="https://user-images.githubusercontent.com/59581790/136991155-92aaf92c-a305-46a7-b37b-c988f30f86dd.png">
Hi team,

Worked with @m5r on this and am proposing we use the existing snackbar component to provide manual sync feedback (similarly to how we use it to confirm task completion). Sync time is indeterminate so showing a progress bar isn't feasible and I agree that a dialog feels cumbersome.. My assumption is that the "pull down to refresh" is an advanced UI pattern and not the friendliest for our users so I suggest we keep the Sync button where it is, have it close the menu and provide success/fail messages with CTAs as needed.

The screenshot shows 2 Sync states in the menu (all synced, or reports to sync) with the time of last sync. I don't think we need to keep the 3rd line of "connection timeout" if we are providing live feedback (but if anyone feels differently, LMK!). 

Once a user taps sync now, the menu closes and they should see a snackbar that confirms that the sync is in progress. I've added an affordance to cancel, however I'm not entirely sure we should include that functionality.. 

Secondly, we should show users when a sync fails (reason why + CTA to retry), and when the sync is complete. 

Feedback appreciated, thanks!

**Comment by abbyad** [comment]
That sounds like it would work well!

**Comment by m5r** [comment]
This is ready for AT on branch `5207-db-sync-user-feedback`  
[PR link](https://github.com/medic/cht-core/pull/7385)

**Comment by ngaruko** [comment]
Tested the following:
1. Sync progress 
![image](https://user-images.githubusercontent.com/6979995/142127980-ebd29d21-e494-4512-95eb-a3426d2cbbea.png)

2. Sync complete 
![image](https://user-images.githubusercontent.com/6979995/142128030-89c29699-6752-492d-ae2c-af55a908f463.png)

3. Sync failed (with retry option)
![image](https://user-images.githubusercontent.com/6979995/142128093-145b71f3-ac63-45c0-a64a-7622f1c130ac.png)

4. Retry button works (offline > sync > see retry option > back online quickly > then press retry)

https://user-images.githubusercontent.com/6979995/142129949-83e08f87-a5e3-4291-b20f-aaa990292136.mov


Two things to note:
a) In @n-orlowski [suggestion above](https://github.com/medic/cht-core/issues/5207#issuecomment-941178017) there is a `cancel` option but it looks like that was not implemented. Do you insist on that @n-orlowski ? I am not sure if it is a usual use case (where a user decide to cancel mid-sync).
b)The snackbar  with `retry` disappears a little too quickly for the user to be able to check and rectify what's wrong (eg check/enable network connection) and come back to it. Again, I guess this is not a biggie as the sync feature is only 2 touches, ie the user can easily sync again if that was the case. 
Your thoughts @n-orlowski ? @kennsippell ?

**Comment by n-orlowski** [comment]
Hi @ngaruko, I think it's fine to omit the cancel option - I had doubts about it's use case as well. As for the retry disappearing, best practice is to keep messages visible for 4-5 seconds unless tapped. Thanks!

**Comment by ngaruko** [comment]
Thanks @n-orlowski for the clarification.
Ready to merge @m5r .
