### ISSUE TITLE
Add a Display page to the admin app to group UI configuration tasks together

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5382]
- [ ] **Create a new high level page called “Display”**. 

- [ ] **Create three tabs on the Display page:** 
- _Date & time_ (contains “Date display format” and “Datetime display format” fields from the old Settings page)
- _Languages_ (contains accordions of languages available and the add new language button.)
- _Translations_ (retains all of the existing content from the tab currently called “Application text”)

**Comment by garethbowen** [comment]
Blocked by #5716

**Comment by garethbowen** [comment]
Blocked on #5381 being merged

**Comment by garethbowen** [comment]
Ready for AT in `5382-admin-display-page`

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/69673570-71319080-10ff-11ea-9f3c-c52a9d5265c0.png)

The Settings page have been stripped of most of its functionality. The only left features there are `Default application language` and `Language for outgoing messages`. It seems logical to either rename it or remove it. IMO, those two things could fit logically well in the `/display/languages` tab 
What do you think @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/69673448-33cd0300-10ff-11ea-8e40-8a6f96061ac2.png)

**Comment by garethbowen** [comment]
@ngaruko This is included in this issue: https://github.com/medic/cht-core/issues/5437 . Unfortunately that issue has a bunch of other improvements so I don't want to add it to 3.8.0.

@peter-ochieng How would you feel about just merging the default languages dropdowns in to Display > Languages and dropping the Settings tab altogether?

**Comment by peter-ochieng** [comment]
@garethbowen Sure,I can make that change.

**Comment by peter-ochieng** [comment]
@garethbowen Can you re-review the changes.

**Comment by garethbowen** [comment]
Ready for AT in `5382-admin-display-page`

**Comment by wtekeu** [comment]
AT'ing this issue

**Comment by wtekeu** [comment]
@peter-ochieng looking good except:
1. when I rename a language, the new name does not appear in the drop downs
2. when I delete a language the drop downs do not reflect the change (the language still appear)

**Comment by peter-ochieng** [comment]
@wtekeu I've made a small change, please AT this ticket again.
Thanks

**Comment by wtekeu** [comment]
@peter-ochieng looking great! But I think you should get it reviewed. It should be possible to update the lists without having to reload the page. There is a listener `changeListener` and a callback associated with this listener. Maybe something like `$scope.enabledLocales = _.pluck(docs, 'value')` in `getLanguages`

**Comment by peter-ochieng** [comment]
Thanks @wtekeu , @garethbowen made the change you mentioned.
Could you AT this ticket again?

**Comment by wtekeu** [comment]
LGTM.
