### ISSUE TITLE
Move "Settings > Backup & restore" to "Backup app code" in the admin app

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5383]
Move “Backup & restore” from the Settings page into a separate high level page, and name the page “Backup app code”.

**Comment by garethbowen** [comment]
> and name the page “Backup app code”.

Translation modified in POE to be exported before release.

**Comment by garethbowen** [comment]
Ready for AT on `5383-move-backup`

**Comment by newtewt** [comment]
:+1:
