### ISSUE TITLE
Rename and reorder admin app navigation

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5384]
Assumes that tickets #5381 #5382 #5383 have already been completed.

- [x] Change the overall site name to “App Management”
- [x] Rename the “Upgrade instance” page to “Upgrades”
- [x] Rename “Import & export” to “Import & export data”
- [x] Rename "Forms" to "App forms"

- [x] Reorder the pages in the main navigation list as follows:
- **Display** > 3 tabs (Date & time, Languages, Translations)
- **Users** > single page
- **Roles & permissions** > 2 tabs
- **SMS** > 3 tabs (Basic SMS settings, SMS forms, Test message)
- **App Forms** > single page (only the content from the Forms-> XML tab should remain)
- **Targets** > single page
- **Images** > 3 tabs (Icons, Branding, Partners)
- **Outgoing messages** > 4 tabs
- **Upgrades** > single page
- **Import & export data** > 5 tabs (Messages, Reports, People, User feedback, Audit logs)
- **Backup app code** (formerly Backup & restore tab on settings)

Like this:
![screen shot 2019-02-14 at 1 40 28 pm](https://user-images.githubusercontent.com/26235957/52819455-2f4ac880-305e-11e9-8331-4db150cabf99.png)

**Comment by dianabarsan** [comment]
Description updated to avoid confusion.

**Comment by garethbowen** [comment]
Starting AT

**Comment by garethbowen** [comment]
AT passed.
