### ISSUE TITLE
Update text on admin app Display page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5385]
Assumes that #5382 is already done

**Languages tab**
- [x] Add text above the accordion: “Enabled languages will be available to users as an option when they select their primary language. We recommend picking 1-3 supported languages and disabling the rest. Of the enabled supported languages, there should be 0 missing translations.” 
- [x] Change the “Edit” button/text next to individual languages to say “Edit name”
- [x] Change “Export” and “Import” button/text next to languages to say “Download” and “Upload”

**Add new language/Edit language pop-up window**
- [x] Add text at the top: “Ideally any new languages added would incorporated into the CHT core so that they can be made available to other partners. Please reach out if you have questions about adding a new language.”
- [x] Add text below the language code field: “The recommended country codes follow the ISO standard, which can be referenced here.” (link "here" to https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes)

**Translations tab**
- [x] Add text at the top: “Please note that any changes or additions you make here to the translations are not currently being saved or tracked anywhere else.”
- [x] Change button text for “Add translation” to “Add new translation key”

**Add translation pop-up window**
- [x] Change the title "Add translation" to "Add translation key"

**Comment by garethbowen** [comment]
Reviewed, ATed, and merged. Great work @peter-ochieng
