### ISSUE TITLE
Update text on admin app User page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5386]
**Main page**
- [x] Add a page title “Users” at the top of the page above the button and table

**Add/edit user pop-up windows**
- [x] Add text below “User name” field title:  “This is what you will use to log in to the app.”
- [x] Add text below “Full name” field title: “Note: This is not currently displayed anywhere in the app.”
- [x] Add text below “Phone” to describe desired format: “Please enter a valid phone number without dashes or punctuation.”
- [x] Add text below “Place” field title: “All users must be associated with a place and contact record in the system to be placed correctly in the hierarchy and see appropriate data when they log in.”

The window for adding a new user and editing an existing user should be different. Relates to ticket #4098 
- [x] For new users, change the button text at the bottom from “Submit” to “Add user” 
~For current users, change the button text at the bottom from “Submit” to “Save”~

**Comment by garethbowen** [comment]
> For current users, change the button text at the bottom from “Submit” to “Save”

I decided not to do this - we use "submit" widely.

**Comment by garethbowen** [comment]
Ready for AT in `5386-update-users-text`

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/67356255-14016700-f5b6-11e9-984e-54a074a2a324.png)
