### ISSUE TITLE
Update text on admin app App forms page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5388]
Assumes #5381 and #5384 are already done. 

This "Forms" page should now only be one page (no tabs) with the content from the original Forms > XML tab. The JSON forms have been moved to the SMS -> SMS Forms tab. 

- [ ] Both: Change “Upload forms” title to “Upload app forms”
- [ ] SMS Forms only: Edit the text at the top of the upload forms section to say "The file should contain a JSON encoded list of form definitions. You may only upload one app form file at a time and any existing forms will be overwritten.”
- [ ] Both: Change “Installed forms” title to “Installed app forms”
- [ ] Both: Change the “Import” buttons to say “Upload”
- [ ] Both: Add titles/headers above the table columns in the installed forms section (e.g. "form icon",  "form title").

**Comment by garethbowen** [comment]
Ready for AT in `5388-admin-app-forms`

**Comment by ngaruko** [comment]
> This page should now only be one page (no tabs) with the content from the original Forms > JSON tab.
Seems like this page has the contents of `XML` tab instead. @peter-ochieng 
![image](https://user-images.githubusercontent.com/6979995/70473121-469afb00-1b35-11ea-82d7-f03f60546c3d.png)

**Comment by dianabarsan** [comment]
I think there's a little bit of confusion in the issue description. 
According to : https://github.com/medic/cht-core/issues/5381 , the JSON forms should have been moved to SMS -> SMS Forms, which they have been. 
The part about "This page should now only be one page (no tabs) with the content from the original Forms > JSON tab." directly contradicts "Create three tabs on the SMS page: SMS forms (formerly the “JSON” tab on the forms page)". 

@ngaruko I believe you were inspecting the old Forms tab - which indeed now only contains the XML forms, while the SMS forms exist in SMS -> SMS Forms. 

The PR that @peter-ochieng submitted changes translations that are used on both pages ("Installed forms" and "Upload app forms"), changes the helper text on the SMS forms page and adds headers in the XML forms page. 

I think that:
1. Changing the translations in both templates is done. 
2. Headers maybe should be added in both templates?

**Comment by garethbowen** [comment]
I've updated the description to remove some confusion here.

**Comment by peter-ochieng** [comment]
@dianabarsan The suggested header changes are part of this ticket #5387 which have already been pushed to master.
@ngaruko Maybe you can AT this ticket again based on the updated description from @garethbowen ?

**Comment by ngaruko** [comment]
Thanks @garethbowen , @dianabarsan and @peter-ochieng for the edits and clarification. Looks good 👍
