### ISSUE TITLE
Update text on admin app Targets page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5389]
**Main page**
- [x] Add text explanation of what “Disable” does at the top above the Disable button: “If you click “Disable”, the targets tab will be hidden for all users.”
- [x] Also at the top, add note about what it means to set a negative goal “If target goals are enabled, all Unique IDs must have a value in the “Goal” field. If you don’t want a certain target to have a goal associated with it, enter a value of “-1”. ”

**Edit target page**
- [x] Add text below the “Name” section: “If you add translations for the target name here, you will still need to add them on the languages page as well.”
- [x] Add text below "Goal" field title: “If target goals are enabled, all Unique IDs must have a value in the “Goal” field. If you don’t want a certain target to have a goal associated with it, enter a value of “-1”. ”

**Comment by garethbowen** [comment]
Ready for AT in `5389-update-targets-text`

**Comment by ngaruko** [comment]
LGTM. Will request @amandacilek to review though. Two little nitpicks to take note of:
a) In the text on top of the main page `If disabled the targets tab will be hidden for all users. A goal of -1 will show a target with no goal.`, the second sentence should read `A goal of -1 will show_**s**_ a target with no goal.` 

b) On Edit target page, the 4th checkbox in the ticket description seems to suggest some emphasis on the uniqueness of IDs in the 'Goal' field?

**_Before_**
![image](https://user-images.githubusercontent.com/6979995/67344837-7138f080-f595-11e9-8455-9438e52912a3.png)

**_After_**
![image](https://user-images.githubusercontent.com/6979995/67349523-a3058380-f5a4-11e9-8976-437ab18d0f99.png)

![image](https://user-images.githubusercontent.com/6979995/67349563-be708e80-f5a4-11e9-94f7-f48c5635af1f.png)
