### ISSUE TITLE
Update text on admin app Images page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5391]
**Icon tab**
- [x] Add text at the top “Images uploaded here are used throughout the application in various places as specified in the application code. For example, the image that appears for a particular widget in the Targets page is specified in the Target code. You can upload images one at a time, and if you upload an image with the same name as an existing image, it will be overwritten with the new file. It is recommended that images be under 500 KB in size, in one of following formats (.svg or .png), and named using the following syntax: “icon-[simple descriptor].” The Community Health Toolkit has an icon library for use by all implementers that can be found here.” (link here to Medic icon library https://github.com/medic/icon-library ) 
- [x] Change button text “Submit” to “Upload icon” 

**Branding tab**
- [x] Add text below the "Title" field explaining where the text will be displayed: “This text will be displayed in the tab heading on browsers only.”
~Change button text next to title to “Save”~
~Change the button text for the logo and favicon to “Upload image”~

**Partners tab**
- [x] Add text at the top explaining where the logos/names will be displayed: “Any partner logos that are added here will be displayed on the “About” page of the app.”

**Comment by garethbowen** [comment]
> Change button text next to title to “Save”
> Change the button text for the logo and favicon to “Upload image”

I decided not to do these two ideas because they are inconsistent with other language in the admin app.

**Comment by garethbowen** [comment]
Ready for AT in `5391-update-images-text`

**Comment by ngaruko** [comment]
LGTM
