### ISSUE TITLE
Update text on admin app Backup page

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5394]
Assumes #5383 has already been created

- [x] Change text at the top: “Here you can download or upload the application settings in JSON format. This JSON contains most of the application code other than forms, icons, and translations.” 
- [x] Change “Backup current settings” to “Backup application code” 
- [x] Change “Upload new settings” to “Upload application code”

**Comment by garethbowen** [comment]
Done and ready for AT. The translations have been updated in POE but no code changes were required.

**Comment by ngaruko** [comment]
LGTM in POE.
![image](https://user-images.githubusercontent.com/6979995/68094889-9fa9ba80-ff09-11e9-9670-3fbbcf4794c9.png)
 To be imported -
