### ISSUE TITLE
Add explanatory text about permissions to the admin app

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5440]
Add explanatory text about what the various permissions mean. Some are fairly self explanatory but others aren’t (for example, “can_view_unallocated_data_records”). It is hard for someone not intimately familiar with our app to understand what all of these mean. 

Suggest that a developer make the first pass looking at the code to see what each permission actually does. When the first pass is done, please loop in @jillrshah to help review the language.

A suggestion from Gareth is that we shouldn't even show the key in the UI - just the translated explanation. If we go this route, we might want to still have titles for each, but something that is more user friendly. For instance, "can_bulk_delete_reports" could be titled "Can bulk delete reports" with some explanatory text below describing what that means (i.e. “This feature allows a user to select more than one report at a time and delete the selected group in a single action.”)

**Comment by ngaruko** [comment]
LGTM.
