### ISSUE TITLE
Fix the timing of the new lazy loading spinner on contact RHS sections

### ISSUE THREAD

**Issue by amandacilek** [medic/cht-core#5518]
This ticket raises a small UX issue with lazy loading contact RHS sections (ticket #5086).

From @isaacholeman: "It looks like the UX issue that @ngaruko noted in ticket #5086 is a real issue especially for facility-based users, even if it's low priority because it won't affect our most typical low-end-Android-user."

Problem: We've implemented lazy loading on the contact RHS sections so that each section initially loads with a spinner and then renders the content when it is ready. The problem actually arises with faster connections and faster machines: in these cases, the spinner still shows up for a split second and then disappears, which looks a bit glitchy (see Bede's video of this happening on ticket #5086).

What should happen: If you have a fast connection, and the contacts page content loads quickly, you should not see the "loading" spinner at all.

Potential solution: Maybe we should time the spinner and not attempt to show it if the content loads quickly enough (say within half a second or so).

**Comment by garethbowen** [comment]
It's really impossible to know if the form will load quickly. We could delay showing the spinner but we would still end up with a chance of showing it for a split second and then disappearing.

As most of our target devices are low end showing the spinner is appropriate.
