### ISSUE TITLE
Make our audit-whitelist test a more courteous user of the API

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5521]
A couple of times recently our build has failed due to the audit endpoint being temporarily unavailable.

```
Running "exec:audit-whitelist" (exec) task
>> (node:8950) UnhandledPromiseRejectionWarning: StdErr in shared-libs/server-checks: npm ERR! code ENOAUDIT
>> npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.
>> 
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     /home/travis/.npm/_logs/2019-03-20T00_07_10_136Z-debug.log
>> (node:8950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
>> (node:8950) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
diff --git a/98793c4709528cf3bfcf08f57efd38abdbf6ea51 b/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
index 98793c4..e69de29 100644
--- a/98793c4709528cf3bfcf08f57efd38abdbf6ea51
+++ b/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
@@ -1,3 +0,0 @@
[-[high] Regular Expression Denial of Service for tough-cookie (#525) in .-]
[-[high] Regular Expression Denial of Service for minimatch (#118) in sentinel/src/lib/pupil-]
[-[high] Insufficient Entropy for cryptiles (#720) in tests/scalability-]
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:audit-whitelist" failed. Use --force to continue.

Aborted due to warnings.
```

Instead of failing, if we get this specific message we should wait and retry a couple of times.

I thought about just ignoring and continuing the build, but that runs the risk of silently failing if the audit endpoint is moved/taken down and always returns this error, so it's safer I think to retry a few times but still fail if necessary.

**Comment by dianabarsan** [comment]
I've noticed that it sometimes takes even more than a couple of minutes until npm's API responds (tested locally).

**Comment by kennsippell** [comment]
In discussions today with @dianabarsan and @garethbowen, decided it is maybe best to 1) introduce a workflow so this is run whenever a package-lock file changes, and 2) add this to the release management steps. This means it won't be run on every commit, we will be more respectful users of the API, and likely not require any sort of retry logic.

**Comment by garethbowen** [comment]
I've disabled npm audit in the build as it was failing the build too frequently: https://github.com/medic/medic/commit/4096310040b46e52846536cb249673631ea7f627#diff-35b4a816e0441e6a375cd925af50752cR984

**Comment by garethbowen** [comment]
Whatever we decide here we should also implement for `medic-conf` - it's riddled with vulnerable dependencies.

**Comment by garethbowen** [comment]
This would solve the vast majority of our medic-conf vulnerabilities: https://github.com/pouchdb/pouchdb-server/pull/386

**Comment by garethbowen** [comment]
@kennsippell I've created a new npm library handle this: https://github.com/medic/audit-dependencies . Because it's a new repo I can't do a PR - would you mind reviewing that before I start adding it to our products?

**Comment by kennsippell** [comment]
@garethbowen The library looks good. I don't love that the code-style is very callback heavy instead of using Promises or alike - but I love that it is in its own package. I think this actually might generalise well, and may be useful to other parties. To that end, I might suggest making the name a bit more generic instead of with the `@medic/` name - maybe `npm-audit-ci` or `npm-audit-whitelist`.

`npx` is sweet!

**Comment by garethbowen** [comment]
I don't like callbacks either but it's what the stock `fs` module uses which is used heavily in this lib so I felt it wasn't worth wrapping everything in Promises. One day the stock modules will take promises...

I've renamed the package and repo to `audit-cache`.

**Comment by kennsippell** [comment]
Instead of `fs.writeFile` would (fs.writeFileSync)[https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options] work? Then you don't need promises or callbacks. Same for `readFile` > `readFileSync`.

**Comment by garethbowen** [comment]
The sync operations are much cleaner to read but worse to run. It's like putting a busy waiting loop in all your code.

**Comment by garethbowen** [comment]
This isn't working reliably so we should fall back to using a manual process to check for vulnerabilities.
