### ISSUE TITLE
Measure and if possible improve CouchDB GET performance via API

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5550]
While doing some performance benchmarks (see Context below) I noticed that attachment GETs are really slow for what they are.

This may be true for all GETs, and could be due to our new security code making sure you're allowed to GET the thing you're asking for.

We should measure the performance of GET requests (and honestly authenticated interactions with api in general), work out if we're adding overhead and how much, and see if there are ways we can improve the code to remove those overheads.

Obvious things would be caching certain critical pieces of data, though it's unclear what we could easily cache (apart from UserCtx). At the very least we should understand what is going on.

Context: https://docs.google.com/document/d/1kXjsF-orndz0-V5UFf_Esx5J-ogeQ6_tALCwE1K0tvA/edit#heading=h.29bkt8nfi7kw

**Comment by garethbowen** [comment]
This looks like a significant performance issue and it affects almost every interaction with the server and impacts performance both by slowing down the response time and adding additional load to the server.

Scheduling for 3.7.0.

**Comment by newtewt** [comment]
I'm able to replicate, sync, create docs with attachments, delete, and get new docs. Seems like everything is working as expected still.
