### ISSUE TITLE
Investigate Geckoview as a replacement for Crosswalk

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5551]
When doing some performance tests recently (see Context below) I noticed that Firefox seems to have a much more performant implementation of IndexedDB than Chrome does (or PouchDB uses it in a way that Firefox likes more, or something).

Especially with Crosswalk EOL'd, and with us definitely wanting to squeeze as much performance out of the phones we're deployed to as possible, it may be worth checking out [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView) as an alternative.

Things we care about:
 - Does our app work correctly in general
 - While PouchDB generates views faster, are other things faster? Or slower? Or the same? The performance of common actions (esp those picked out so far for Telemetry) should be looked into
 - As noted: Chrome *does* replicate faster than Firefox (and thus potentially Geckoview). We should see if this is true
 - Does it allow us to easily increase / make infinite our quota (the main reason we use Crosswalk today)
 - Does it get updated frequently? Does it allow us to stay closer to modern browsers (right now we're on Chrome 53 until we work out how to build Crosswalk again or move off it)?
 - Is is easy to integrate with and to build and use on Android?

Context: https://docs.google.com/document/d/1kXjsF-orndz0-V5UFf_Esx5J-ogeQ6_tALCwE1K0tvA/edit#heading=h.29bkt8nfi7kw

**Comment by garethbowen** [comment]
We're moving towards using Webview instead of either.
