### ISSUE TITLE
Expired tasks don't disappear from the Tasks tab when they expire

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5564]
1. Configure a task which will emit with a dueDate of today, and an expiry date of tomorrow.
1. Set your clock to 11:55pm, refresh the page, navigate to the 'tasks' tab and see the task.
1. Wait 5 minutes, and you should see the dueDate "today" change to "yesterday" and turn red.
1. Set your clock to tomorrow + 11:55pm, refresh the page, and view the task.

Expected: After 5 minutes, this task should disappear because it has expired.
Observed: Wait 5 minutes, and you will see the dueDate "tomorrow" change to "2 days ago". Refresh the tab and the expired task will disappear.

There is some [code in LiveList which is run at midnight](https://github.com/medic/medic/blob/master/webapp/src/js/services/live-list.js#L543) which refreshes the description of the task. There is an expectation that we should maybe also remove expired tasks here.

**Comment by garethbowen** [comment]
Moving to 3.8.0 so it can be considered with the other tasks work.

**Comment by kennsippell** [comment]
Ready for AT on `tasks-v2`

**Comment by wtekeu** [comment]
I am AT'ing this fix

**Comment by wtekeu** [comment]
Am I doing something wrong?

Branch `tasks-v2`

Created the task
<img width="595" alt="Screen Shot 2019-12-06 at 11 59 17 PM" src="https://user-images.githubusercontent.com/1445164/70348547-e5bbac00-1830-11ea-85d2-429ee63b83e5.png">

Set clock to friday 11.55pm

At saturday 12.03 am refresh

<img width="600" alt="Screen Shot 2019-12-07 at 11 55 30 PM" src="https://user-images.githubusercontent.com/1445164/70348603-097ef200-1831-11ea-8ad6-10e496bbf7e7.png">

set clock to Saturday 11.55pm

on sunday 12.03am refresh

<img width="586" alt="Screen Shot 2019-12-08 at 12 02 21 AM" src="https://user-images.githubusercontent.com/1445164/70348691-3a5f2700-1831-11ea-90a3-661da7b3c79f.png">

```javascript
  {
    icon: 'infant',
    title: 'task.infant.title',
    appliesTo: 'contacts',
    appliesToType: [ 'person' ],
    actions: [ { form:'patient_assessment_over_5' } ],
    events: [ 
      {
        id: 'patient_assessment_over_5-q1',
        days:1, start:1, end:3,
      }
    ],
    resolvedIf: function(c, r, event, dueDate) {
      // Resolved if there a family survey received in time window
      return isFormFromArraySubmittedInWindow(c.reports, 'patient_assessment_over_5',
                 Utils.addDate(dueDate, -event.start).getTime(),
                 Utils.addDate(dueDate,  event.end+1).getTime());
    }
  }
```

**Comment by kennsippell** [comment]
`days:1, start:1, end:3,`

This task is configured to show 1 day before the due day, and stay until 3 days after the due date. If you do the same process you're doing but make it say "4 days ago" it should disappear just by switching between tabs and not having to refresh the page.

**Comment by wtekeu** [comment]
LGTM.

After "4 days ago" after waiting for 12.03am and switching between tabs
