### ISSUE TITLE
following README: couch is @127.0.0.1, not @localhost

### ISSUE THREAD

**Issue by srsudar** [medic/cht-core#5609]
(Originally posted on #4826)

When following the README, I began by installing couchdb. I used the standalone installation, as suggested, and accepted all the defaults. The default bind address, as of 2019-04-28, on Ubuntu, was `127.0.0.1`. The README mentions `COUCH_NODE_NAME=couchdb@localhost`.

Later in the process, eg when trying to run `grunt api-dev`, the command was failing, claiming that the `couchdb@localhost` did not exist.

I examined the couch nodes:

```
curl -X GET "http://localhost:5984/_membership" --user admin:pass
```

The output indicated that the node was `couchdb@127.0.0.1`, not `@localhost`. Changing to `COUCH_NODE_NAME=couchdb@127.0.0.1` allowed the command to succeed.

Not sure if this is something with my network configuration, or just due to the defaults in couch changing, but it might be worth mentioning that the nodes can be inspected.

**Environment**:

Ubuntu bionic

**Comment by kennsippell** [comment]
I've gone through this same error and fix. But I'm also on Ubuntu bionic - so maybe a different OS has a different default?  I've sent a quick poll to other developers to see what people are using in their environment.

**Comment by kennsippell** [comment]
This changed in CouchDB 2.1.1. http://docs.couchdb.org/en/stable/whatsnew/2.1.html#upgrade-notes

> The default node name has changed from *couchdb@localhost* to *couchdb@127.0.0.1*

**Comment by derickl** [comment]
I _believe_ the default on OS X is `couchdb@localhost`

**Comment by garethbowen** [comment]
@kennsippell This has been merged. Can you confirm it's fixed? Is there more to do?

**Comment by kennsippell** [comment]
> COUCH_NODE_NAME: the name of your CouchDB's node. The Docker image default is nonode@nohost. Other installations may use couchdb@127.0.0,1. You can find out by querying CouchDB's membership API

Final seems right for both Mac and Ubuntu
