### ISSUE TITLE
Update process needs to be clearer

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#5618]
During our site visit Siaya was upgraded to 3.4. CHWs were opening the app after the upgrade and getting a 404. @dianabarsan  determined it was due to the user still replicating using an old version(2.14) and still downloading all the docs still for the new version. The hope is that we can detect an update has occurred and indicate this to the user that they're still downloading docs to get onto the latest client version. The way we were confirming is the sync status in the hamburger menu. Because of this people were shutting down the app and assumed it was broken.  

**Describe the solution you'd like**
It would be nice to show a progress bar saying how much work is left to be done(doc downloading, indexing, etc..) or a message that says the update occurred and we are still processing.

**Comment by latin-panda** [comment]
It'll be addressed in https://github.com/medic/cht-core/issues/7492. Closing to simplify
