### ISSUE TITLE
Remove use of AngularJS $scope.$broadcast

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5624]
As part of the Angular 7 migration (#4750), we need to refactor to avoid all use of `$scope.$broadcast`. 

File | Broadcasted
-- | --
`admin/src/js/controllers/delete-user.js` | UsersUpdated
`admin/src/js/controllers/edit-user.js` | UsersUpdated
`webapp/src/js/controllers/inbox.js` | ClearSelected
`webapp/src/js/controllers/inbox.js` | formLoadingComplete
`actionbar.html` | Uses $scope.emit for SelectAll, DeselectAll, VerifyReport, ToggleVerifyingReport, EditReport
`webapp/src/js/controllers/messages.js` | UpdateContactConversation
`webapp/src/js/controllers/reports.js` | VerifiedReport
`webapp/src/js/services/android-api.js` | HideContent

**Comment by rmhowe** [comment]
This may have some overlap with https://github.com/medic/medic/issues/5635, worth checking on the status of 5635 before starting work on this.

**Comment by garethbowen** [comment]
This is a refactor - everything should work just as it did before. Things to AT:

- Task completion: After you complete a task it is deselected (on desktop) and you see the task list again (on mobile)
- Bulk select, select all, deselect all, etc
- Report verification: All three state of verification (verified, has errors, undefined)
- Editing SMS (JSON) reports
- Navigation: hardware back button, the < button, etc
- Messages: on change the LHS and RHS are updated
- Reports form type filter

**Comment by garethbowen** [comment]
Ready for AT in `5624-remove-broadcast`

**Comment by ngaruko** [comment]
LGTM.
