### ISSUE TITLE
Calculate data for DHIS2 reports

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5661]
Every month CHPs are expected to submit a DHIS2 report which records information such as "Number of households visited". We have enough information to automate the calculation of much of this data so we can make the reporting much more efficient and less error prone by prepopulating the form. Note that as well as the aggregate data we also need to be able to view the items that contributed to this total (#5660), using the above example we need to show not only the number of households visited, but also the names of the households.

It may be possible to configure nools to generate a task which has collects all the data and passes it to the form using global variables to store data as the families are being processed.

Alternatively we could create a new doc type to store this data and create a new instance each month on the phone.

Analyse the implementations and prove and/or implement the correct approach.

**Comment by michaelkohn** [comment]
A couple considerations to keep in mind.

#### Disaggregation - period
While the MVP (based on the MoH 515 / Kenya) will be disaggregated by month and use the Gregorian calendar, we should keep in mind that there are some DHIS2 dataSets that are based on other periods (weekly, for example). In addition, some countries use different calendars so it may not always align with the Gregorian calendar. 

#### Disaggregation - orgUnit
Calculations at the CHW Area level will relate to activites for that specific CHW Area (ie `place`). When aggregating data across CHW's (ie for the supervisor), it won't always be aggregating based on the CHW Area's `parent`, but rather based on a metadata field on the CHW Area (though I presume this will be easier with configurable hierarchies).

During our design work in Kenya looking at the MoH 515, we found that there was one MoH 515 submitted per Community Health Unit (CHU), and that there was generally* a 1-to-1 relationship between a supervisor and a CHU, but there is *not* a 1-to-1 relationship between the supervisor and the CHW Area's `parent` (the `district_hospital`, in this case). Each CHW Area has a `supervisor` specified as a metadata field and we'll need to aggregate at that level.

This diagram tries to illustrate this.

![DHIS2 Siaya Mapping](https://user-images.githubusercontent.com/10096985/66397239-1a5ee300-e9fb-11e9-9802-6964b1665b51.png)

*There were some exceptions to "1 supervisor looks after 1 CHU", though in these situations the Supervisor actually had separate logins for each CHU so it can still be thought of as a 1-to-1 Supervisor to CHU.

**Comment by kennsippell** [comment]
Ready for AT in branch `dhis2`
Documentation at https://github.com/medic/medic-docs/pull/175
Requires this medic-conf change to test https://github.com/medic/medic-conf/pull/285

**Comment by ngaruko** [comment]
Done AT @kennsippell .  Back to you to 'merge'
