### ISSUE TITLE
Update the levels displayed in breadcrumbs across the app

### ISSUE THREAD

**Issue by amandacilek-zz** [medic/cht-core#5697]
We use breadcrumbs to display contextual information about where a person/place belongs in the app hierarchy. Depending on the user, sometimes the breadcrumbs can contain redundant and unnecessary information. In this example, I am Amanda Cilek, and "Amanda Cilek's Area" is the place I belong to. I do not need to see "Amanda Cilek's Area" in the breadcrumbs of every single report that I have submitted.
![Screen Shot 2019-05-28 at 4 52 21 PM](https://user-images.githubusercontent.com/26235957/58519816-03190a80-816a-11e9-9255-5acbc8f7763d.png)

This request is to update how we handle breadcrumbs so that we show all levels **except for** the level the user themselves belongs to, the top-most level. The data underneath will still have the entire hierarchy, we'll just choose how much to show based on the logged in user. For example, when I look at my reports tab in the above instance, I should no longer see "Amanda Cilek's Area" at the end of every breadcrumb. However if my manager logged in and looked at the same reports, my manager _would_ still see "Amanda Cilek's Area".

This update should apply to wherever breadcrumbs show on the **LEFT HAND SIDE** of the app (currently Messages and Reports, but also Tasks once [#5710](https://github.com/medic/cht-core/issues/5710) is done). 

Wherever breadcrumbs are shown on the **RIGHT HAND SIDE**, we should continue to show all breadcrumbs as users often use these as a shortcut to navigate back to the top level.

**Comment by MaxDiz** [comment]
Hi @garethbowen This issue should be completed alongside #5710 (currently scheduled in v3.8) to make it functional. I also have a call with @amandacilek and @yembrick this week to review any outstanding design work on these issues and will report back

**Comment by garethbowen** [comment]
Ok. Adding to 3.8.0.

**Comment by maremegaye** [comment]
From the above Amanda’s post to now few breadcrumbs have been deleted. Hereunder a table that describes the breadcrumbs deleted and those not deleted across different users and different projects. 
- For the CHW, we will need to delete the breadcrumbs in the report tab
- For the Supervisor, we will delete the breadcrumbs in the report and message tabs
- For the Admin view, we will need to delete the breadcrumbs of the message tab

https://docs.google.com/document/d/1t9wSTpNHnxyprVy-EX5MxGD8_YMTZ1qIZrg9gVb93LQ/edit

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by MaxDiz** [comment]
removing from v3.12 so can be considered alongside #5997 and #5886 (to be scheduled)

**Comment by latin-panda** [comment]
Hi @michaelkohn and @elvisdorkenoo 

Have you defined where the changes are going to be (ie messages, targets, contacts, reports) and what we expect to see? 

I see the PR is on the way, this information will help the Code Review and AT. Thanks!

**Comment by elvisdorkenoo** [comment]
hello @latin-panda, 

> Have you defined where the changes are going to be (ie messages, targets, contacts, reports) and what we expect to see?

Yes, the last two paragraphs are added by @michaelkohn to give more clarifications.

**Comment by latin-panda** [comment]
Cool! 
I didn't notice the issue's description was updated, because I read it few weeks ago then I assumed it was the same and I was looking for a new comment with updated info. 
Thanks for the clarification!

**Comment by bedengaruko** [comment]
1. Created a new hierarchy : Health Centre > Area > Household > Person
2. Submitted a couple of reports for the person
3. Submitted a task generating report for the person (pregnancy)
4. Note results
>**_> Online user sees the whole hierarchy_** 
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/113735421/191630893-68d9f368-71be-4420-a1df-824a33ef0b90.png">
>> **_Offline user does not see area, only household  (on the LHS)_** >>
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/113735421/191631167-b0cb9cfa-ae05-4881-9b37-856c848a720c.png">
 
>> _**Same with Tasks**_ 
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/113735421/191631242-f8f6c7fe-a7f4-4fa3-b2f5-bed720c40961.png">
_**>> Messages Tab >**_ 
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/113735421/191631414-c28b7d09-8b55-4178-8c70-085bba4b152f.png">
