### ISSUE TITLE
Update webapp e2e tests to be executed as an offline user

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#5704]
Most of our webapp workflows target offline users, while all of our webapp e2e tests, except one, run as an online user account. 
In order to have our e2e test coverage be closer aligned with actual usage, we should update webapp e2e tests that cover workflows usually performed by offline users to be tested using offline user accounts.

Given that offline users require syncing (likely manual, in this case) to get updates from the server, we might consider grouping all these e2e tests, so they run using one set of settings/forms, if flakyness and complications around needing to sync and refresh become problematic. 

Some webapp e2e tests might make sense to be run as online users, candidates could be tests around Messages tab and everything that requires SMS (for example registration_by_sms, sms-gateway).

**Comment by tatilepizs** [comment]
Closing this ticket because we are doing this work incrementally every time that we need to modify an e2e test. There is not a specific PR related to this ticket
