### ISSUE TITLE
"Select a Language" dialog appears without content for >10 seconds during "Loading rules..."

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5781]
**Describe the bug**
On the first load for a user with heavy documents who has not yet selected their language (eg. performance testing seed data), an empty dialog with title "Select a Language" appears in parallel with the "Loading rules..." stage of bootstrapping. Only after the loading rules completes are there contents in the dialog. On my Techno F1, this dialog appears empty on the screen for 10-20 seconds before being populated with content.

**Expected behavior**
We probably shouldn't show this dialog until the dialog's content is ready to be loaded.

**Comment by garethbowen** [comment]
I wonder how useful the dialog is. Assuming the default language is configured correctly, this would only be useful for projects where different users prefer different languages. Perhaps we should check if this is true for any current projects.

If it is useful, then we should also consider showing a language selector on the login page. Changing this would mean the login page and bootstrap messages are shown in the users language and the dialog wouldn't show at all. Leaving the selector unchanged would result in the current behaviour which would then benefit from Kenn's suggestion.

**Comment by garethbowen** [comment]
This dialog is being removed as part of fixing #6280 - closing.
