### ISSUE TITLE
Move scope functions to redux actions

### ISSUE THREAD

**Issue by rmhowe** [medic/cht-core#5791]
As part of the ongoing changes to get ready to [move to Angular 7](https://github.com/medic/medic/issues/4750), this issue is for moving functions off of scope and into redux actions.

**AT:** Parts of the app touched include:

This is effectively a refactor with no new features added.

**Comment by kennsippell** [comment]
If anybody is wondering how we are tracking toward removing the use of `$scope`, here are the occurrences of the `$scope` keyword for our past four releases:

"Total" counts the number of occurences within the entire webapp repository
"Webapp Only" counts the number of occurrences within the webapp folder inside the webapp repository

Release|Webapp Only|Total
--|--|--
3.3|924|1375
3.4|951|1486
3.5|782|1317
3.6|656|1193
3.7 (master)|656|1193

**Comment by rmhowe** [comment]
Thanks @kennsippell, the [latest issue](https://github.com/medic/medic/issues/5635) which will be hopefully be released as part of 3.7 brings webapp `$scope` references down to 253.

**Comment by rmhowe** [comment]
WIP branch: `5791-reduxify-scope-functions`

Current state of the branch:
- Global `$scope.clearSelected` function has been converted to a redux action, including removal of the `$scope.$broadcast` "ClearSelected" event.
- `$scope.setSelected` within `messages` and `reports` have been converted to redux actions
- `ServicesActions` has been created. Ideally in redux: actions should import services, and services should not import actions. There appear to be valid use cases for services importing actions in this app however, for example reading and writing the `lastChangedDoc` property. This means a circular dependency is likely to happen eventually if the importing is happening both ways (and indeed I came across such a circular dependency). For this reason I created a separate `ServicesActions` for use when a service needs to dispatch an action. In general however I think this should be avoided, and actions should be dispatched from either components/controllers or complex action dispatchers.

**Comment by garethbowen** [comment]
Ready for AT in `5791-reduxify-scope-functions`. This is a refactor of many different components in the app so needs a broad smoke test.

**Comment by ngaruko** [comment]
Did a broad smoke test. Looks good. Seeing a couple of issues, but they happen to be on other branches as well:
a) The warning modal does not appear when one tries to exit a form in the middle of completing the form
b) Not translated keys text overflows cards on the 'Analytics page'. Not a big issue since we do not expect to display translation keys in production:
![image](https://user-images.githubusercontent.com/6979995/68182571-951d1d00-fffe-11e9-95de-56b100bac05c.png)

**_(Investigating a) atm)_**

**Comment by garethbowen** [comment]
I wanted to get that PR ATed and merged, but there are still a few $scope functions left. Moving back to In Progress to finish this off!

**Comment by garethbowen** [comment]
The latest PR removes all $scope functions except for in Modals (where we use a legacy service) and $scope.destroy (which is needed until we migrate to angular 2+). I think after this is merged we've done all we can until actually upgrading...

For AT, this refactors a range of functions. Focus on:

- Global: first run prompts (language, tour, config, etc)
- Messages: selecting, creating, marking as read
- Contacts: selecting, viewing deceased, editing, and cancelling edits
- Reports: facility filter, editing, bulk delete mode

**Comment by garethbowen** [comment]
Ready for AT in `5791-remove-more-scope-fns`

**Comment by ngaruko** [comment]
LGTM

**Comment by garethbowen** [comment]
@ngaruko The references in your screenshot are in the `/admin` dir which we're leaving on angular v1 for now so not included in this issue. There are a handful of references still in `/webapp` but they are references we cannot remove until we upgrade to angular v2+.
