### ISSUE TITLE
Add offline-user e2e tests for tasks 

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5794]
Based on discussion in #5790 we should add some e2e tests which log in as offline users and test some basic actions with tasks. One additional test for creating task for a logged in user with replication depth + needs_signoff.

**Comment by kennsippell** [comment]
Should cover this use case: https://github.com/medic/medic/issues/5899

**Comment by garethbowen** [comment]
Delaying to 3.9.0 so we don't block 3.8.0 on this.

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by dianabarsan** [comment]
We now have two e2e test that were added recently around tasks: 
- one that tests task due dates display: https://github.com/medic/cht-core/blob/master/tests/e2e/tasks/task-due-dates.wdio-spec.js
- one that tests household tasks landing page: https://github.com/medic/cht-core/blob/master/tests/e2e/tasks/tasks-group.wdio-spec.js

Their coverage is somewhat limited to what they are testing and the config is extremely simple (custom for every test).

**Comment by dianabarsan** [comment]
I think so!
