### ISSUE TITLE
Fix widget wrapping when displaying multiple columns

### ISSUE THREAD

**Issue by amandacilek-zz** [medic/cht-core#5807]
On larger displays with multiple columns of widgets, if there is an extra one or two widgets at the end they should align left and conform to the columns above, instead of centering.

![Screen Shot 2019-07-15 at 12 19 36 PM](https://user-images.githubusercontent.com/26235957/61242580-ed03e100-a6fa-11e9-85e5-82a7833a3e5e.png)
When there are three columns of widgets, any widgets in the final row should start in the column on the far left, and fill to the right. In this case, the final widget should be in the first column on the left-hand side.

![Screen Shot 2019-07-15 at 12 19 49 PM](https://user-images.githubusercontent.com/26235957/61242669-32281300-a6fb-11e9-9fdf-2e2088120bb6.png)

When there are two columns of widgets, the current look is even worse! Widgets at the end should not break free of the established columns, as this makes them look special in some way. The last widget should be in the first column on the left-hand side.

**Comment by latin-panda** [comment]
@Benmuiruri please add your tickets to a milestone. In this case this one is in 4.7
