### ISSUE TITLE
Timestamp on image vs data is slightly different when capturing mrdt image. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#5823]
**Describe the bug**
The timestamp shown on the image is different from the timestamp that is received the app and stored in the report.  Trying to track down the difference and if this is a needed fix.  The time in the image is 21.226 and the json doc is 21262. Doc and image are attached below. 

**To Reproduce**
1. Process a mrdt capture form with new webapp, new rdt app

**Expected behavior**
The time stamped in the corner is slightly different from the one recorded in the json doc. 

**Environment**
- Instance: gamma.dev
- Browser: android app
- Client platform: android
- App: webapp/rdtcapture
- Version: 3.6.0

``` {
  "_id": "9aead82b-137b-4fea-aef5-f2fe1d9b59f9",
  "_rev": "2-96d054949c2ed1a62109a9d749223eaf",
  "form": "new_mrdt_demo",
  "type": "data_record",
  "content_type": "xml",
  "reported_date": 1563544106404,
  "contact": {
    "_id": "b7d0dbd5-beeb-52a8-8e4c-513d0baece8e",
    "parent": {
      "_id": "8606a91a-f454-56e3-a089-0b686af3c6b7",
      "parent": {
        "_id": "fc9928ae-9f48-5d2d-8a0f-222b2389f77f"
      }
    }
  },
  "from": "+16143291528",
  "hidden_fields": [
    "mrdt_time_taken"
  ],
  "fields": {
    "name": "Red 1",
    "mrdt_image_data": "",
    "mrdt_time_taken": "21262",
    "meta": {
      "instanceID": "uuid:75dc7b6f-e6b6-47f6-b841-08f46965c87a",
      "deprecatedID": ""
    }
  },
  "geolocation": {
    "latitude": 39.9627502,
    "longitude": -82.9607632,
    "altitude": 206.8000030517578,
    "accuracy": 32.29600143432617,
    "altitudeAccuracy": null,
    "heading": null,
    "speed": null
  },
  "_attachments": {
    "content": {
      "content_type": "application/xml",
      "revpos": 1,
      "digest": "md5-+xmO6qQZRUotEHDCA5iz6g==",
      "length": 279188,
      "stub": true
    },
    "user-file/new_mrdt_demo/mrdt_image_data": {
      "content_type": "image/png",
      "revpos": 1,
      "digest": "md5-qvGB9IDzKM5sYJR8I0P84A==",
      "length": 209077,
      "stub": true
    }
  }
} 

```

![c32f11e1-9ac8-492b-b760-ff8263049421](https://user-images.githubusercontent.com/10531066/61540185-24300600-aa0b-11e9-9636-d4aef94252ad.png)

**Comment by garethbowen** [comment]
Closing. The difference is so small it's not concerning. Reopen if a more significant discrepancy is found.
