### ISSUE TITLE
appliesToType on the contact summary cards and fields should accept arrays

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#5856]
**Describe the bug**
The documentation for cards and fields shows that `appliesToType` should accept an array. When providing an array to cards an error is displayed. When providing one to fields it does nothing. 

**To Reproduce**
1. Confgure your contact-summary.templated.js to have an array for one of the fields. 
2. Apply that config `medic-conf --url=https://localhost compile-app-settings upload-app-settings`
3. Launch the webapp and log in as offline user
4. Navigate to a contact. An error will display

**Expected behavior**
The contact summary documentation shows that appliesToType for cards and fields should accept an array. 

https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#fields

https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#cards

**Logs**
```
inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3 Configuration error in contact-summary function: e.appliesToType.charAt is not a function
(anonymous) @ inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3 Error setting selected contact
(anonymous) @ inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3 Error: Configuration error
    at inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
    at inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
    at inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
    at c.$digest (inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3)
    at inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
    at Object.completeTask (inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3)
    at inbox.js?_sw-precache=d83fc895f2d7387a70fa86b0d566f6f5:3
```

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: webapp/config
- Version: 3.6.0

**Comment by garethbowen** [comment]
We should either fix the code or the documentation - preferably the code!

**Comment by kennsippell** [comment]
Ready for AT on `5856-appliestotype-and-arrays`

**Comment by ngaruko** [comment]
**_LGTM_**
**Before**
![image](https://user-images.githubusercontent.com/6979995/69700867-6c48fd00-1150-11ea-9d10-612cc1eeeff0.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/69701006-cba70d00-1150-11ea-911d-a3e1e8f6ac54.png)
