### ISSUE TITLE
Reports with errors trigger tasks when created/modified but not on reload

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5866]
**Describe the bug**
If a new report with errors is created or an existing report with errors is modified, that report is passed into the RulesEngine and can trigger a task or a target. When the webapp is reloaded, that report is not passed into the RulesEngine and different tasks/targets will appear.

**To Reproduce**
1. Clean webapp
1. Update a task in config to log the contact/reports which get passed into partner code. 
1. Create a new report with errors (eg. `await PouchDB('medic-user-ac1').put({ _id: 'test_report', patient_id: 'c8314e6b-8ac6-5a5a-b959-6f58cc015cfe',  type: 'data_record', form: 'test', errors: ['error'] })`)
1. You will see that this report is passed into the partner task/target code.
1. Reload the page
1. You will see that this report is not passed into the partner task/target code.

**Expected behavior**
Tasks and targets should be the same before and after a reload. We apply the same filters to reports on startup as we do when reports are created/modified.

**Performance Impacts**
In `RulesEngine.js` we have this line: [Search('reports', { valid: true }, options),](https://github.com/medic/medic/blob/master/webapp/src/js/services/rules-engine.js#L226) which filters the reports to only valid reports.  This filter causes the `medic-client/reports_by_validity` index to be built, which can take a long time during bootstrap. If we queried all reports instead of valid reports, this bug would be fixed and application startup times would improve.

**Comment by abbyad** [comment]
Seems related to https://github.com/medic/medic/issues/4043. Would this issue be irrelevant if we solved the other one?

**Comment by kennsippell** [comment]
@abbyad This issues pertains to the consistency of data entering nools, while #4043 relates to the optional helper functions which we recommend partners to use when processing the data in nools.

There are several ways to fix this issue 1) decide that reports with errors should never trigger/resolve tasks and thus should never enter nools, or 2) decide that reports with errors should enter nools and it is the responsibility of partners to appropriately ignore the reports with errors. 

If we do the first, then #4043 is irrelevant.  However, my leaning was toward the second because it improves performance at startup - all projects are currently paying to warm the `medic-client/reports_by_validity` view even if they don't have SMS workflows and the view is irrelevant. That said, I don't have much context related to tasks in projects running SMS workflows - and perhaps the first option is better for some reason?

**Comment by kennsippell** [comment]
Ready for AT on `tasks-v2`

**Comment by ngaruko** [comment]
Seeing `Error fetching tasks` on mobile (and web actually)
![image](https://user-images.githubusercontent.com/6979995/69993728-48067980-15b1-11ea-9ca1-fdb0c2013c3e.png)

```
Error getting tasks for all contacts Error: Rules Engine: Updates to the nools schema are required
    at Error (native)
    at t.existingRulesStateStore.then.r (https://10455358.ngrok.io/js/inbox.js:3:233698)
    at https://10455358.ngrok.io/js/inbox.js:3:665858
    at https://10455358.ngrok.io/js/inbox.js:3:665997
    at c.$digest (https://10455358.ngrok.io/js/inbox.js:3:671466)
    at https://10455358.ngrok.io/js/inbox.js:3:673440
    at completeTask (https://10455358.ngrok.io/js/inbox.js:3:694012)
    at https://10455358.ngrok.io/js/inbox.js:3:605326(anonymous function) @ inbox.js:3
inbox.js:3 Replication started after 300.163 seconds since previous attempt
```
Do you think it os related @kennsippell ?

**Comment by kennsippell** [comment]
@ngaruko I don't believe this is OS-related. You'll need to deploy the default configuration using `~/medic-conf/src/bin/medic-conf.js --local compile-app-settings upload-app-settings -- --debug` using the medic-conf branch `tasks-v2`. In production, we'll push this configuration update before we deploy the webapp 3.8 upgrade.

**Comment by ngaruko** [comment]
LGTM

**Comment by ngaruko** [comment]
Will leave the PR  and the branch intact until we are done with all `tasks` related issues
