### ISSUE TITLE
Offline users download all their previous feedback docs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#5902]
**Describe the bug**
When a user is setup on a new device, they download all docs from their meta-db. Previously, the meta-db only contained `read` docs, which are relevant to the user, so the replication is not filtered. However, since https://github.com/medic/medic/commit/a0c57b1908f7b14dbcf008d0f84564d00fb1ff70 , users also store their `feedback` docs in the meta DB, which will also be downloaded when users setup a new device. These docs occupy storage space without being of any use whatsoever. 

**To Reproduce**
1. Login as an offline user and create a feedback doc (you can do this from the hamburger menu -> Report bug). 
2. Refresh the page to trigger meta db sync. 
3. Wipe device data and login with the same user. Wait until all networking is finished. 
4. Check your local meta db and observe that you have downloaded the feedback doc you created before. 

**Environment**
- Instance: any 3.5 + instance
- App: webapp
- Version: 3.5+

**Comment by garethbowen** [comment]
This goes for telemetry docs as well.

**Comment by garethbowen** [comment]
It would also be worth considering implementing purge on these docs. This would be hardcoded to just purge all feedback and telemetry docs that have been successfully replicated. This could be done either server side or client side. Client side has the benefit of being simpler to implement but purging server side would mean the initial replication would ignore the docs for free.

**Comment by dianabarsan** [comment]
Ready for AT on `5902-dont-replicate-feedback`. 

This should work like: 

In Sentinel:
1. After every meta db replication, purge what's been replicated that time. 
2. After running replication for the first time, all previously replicated (this works by checking if the doc exists/(ed) in the main `meta` db) feedback and telemetry docs should be deleted from the individual users databases 

In Webapp:
1. After replicating the meta db upwards, the `seq` of the meta database is saved.
2. A new action is added during bootstrapping ("Clearing metadata...") that clears a maximum of 1000 replicated feedback/telemetry docs (this works by stopping at the seq we saved in step 1). 
(so if the user has 10.000 feedback docs, they'll see this event the next 10 times they boot up the app). 

To help AT, our "Testing page" includes an action that generates a selected number of blank-ish feedback docs.

**Comment by newtewt** [comment]
This is working as expected. I do need to figure out why 1 document doesn't seem to be purging but after that I think we are good to close this out.

**Comment by dianabarsan** [comment]
@newtewt There's an issue with this, so not ready to close and it requires more work to fix. 
What's happening is: 
- we wanted to delete feedback documents locally (so they don't take up space)
- I added a "filter" function to the meta sync so it won't upload these deletes 
- adding the "filter" function invalidated the old checkpointer (the checkpointer _id is a sort of hash of all replication details, including the stringified filter function), which means that once the offline user got the new code, the first meta sync would start from scratch (from seq 0). 
- If the "one time purge" has already ran on the remote DB, every old feedback document has already been purged, hence non-existing, so they will be uploaded again. 
- Because the same _rev will be used, their replication to the conglomerate meta will not happen, so they won't be tagged to be purged again. 

Thinking about alternatives:

a) don't delete locally - this is bad because users local databases keep growing. 
b) use a `validate_doc_update` function in the `_design/medic-user` instead of a replication filter function to stop replicating locally "purged" docs upwards. This requires a migration to add this function to all users meta databases.

**Comment by garethbowen** [comment]
Ready for AT on `5902-dont-replicate-feedback`

**Comment by newtewt** [comment]
I think this is working as expected. I did find one scenario where if you were to replicate a feedback doc on one device. Then log in another device before the replication occurs it would pull down the doc. However, it eventually was purged locally from both instances. I don't think we should handle this case but I'll leave it up to you to decide.

**Comment by dianabarsan** [comment]
@newtewt that behavior is expected and can't be prevented, unfortunately, without introducing some kind of filter (which we can't do because https://github.com/medic/cht-core/issues/5902#issuecomment-623368269) . If it was purged locally in the end, I'm satisfied :)

**Comment by dianabarsan** [comment]
Merged.
