### ISSUE TITLE
Provide a UI to perform testing tasks on the phone

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5935]
**Describe the issue**
There are some things that only engineers need to do when developing or testing something but shouldn't be easily accessible in the UI because they would confuse users or potentially be dangerous to use if you don't know what you're doing.

**Describe the improvement you'd like**
We should provide a hidden "developer console" to make these actions easy for our team to do. On Android Google has hidden these options behind multiple clicks on a particular image. Consider doing this with multiple touches of some element on the About page. Add a warning dialog before loading the page as we don't want anyone to accidentally find it.

On the page add buttons to:
- initiate a purge replication
- wipe all offline data (pouchdb, cookies, etc) and reload

**Describe alternatives you've considered**
- We could force people to use a specific URL but that's hard to do in the android wrapper.
- We could expose functions that people could type in the browsers dev console but that's hard to do in the android wrapper.

**Comment by newtewt** [comment]
Force sentinel to run immediately instead of 5 minute check.

**Comment by garethbowen** [comment]
I've also moved the Debug functionality from the About page to here. Before it was only showing for "localhost" so users didn't accidentally leave it on. Now it's more useful.

**Comment by garethbowen** [comment]
> Change url Android app is using.

That's baked into the Android app. You can use the unbranded app to configure this.

> Force sentinel's scheduling to run immediately instead of 5 minute check.

This would be better done via server side configuration than in the app. Feel free to raise a new issue.

**Comment by garethbowen** [comment]
Read for AT in `5935-testing-page`

For AT: You can access this page by going to the About page and clicking on the "About" heading 6 times with less than 1 second between each click (just spam it!).

**Comment by ngaruko** [comment]
LGTM. 
![image](https://user-images.githubusercontent.com/6979995/69292145-35637a80-0c6a-11ea-9052-2b48b2db2d47.png)
