### ISSUE TITLE
Remove `update_sent_forms` transition

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#5939]
Sentinel Reminders have been reworked in 3.7 (https://github.com/medic/medic/issues/5475). 
As a result of this rework, the `update_sent_forms` transition, that reminders functionality depended on, is no longer used and can be removed.

**Comment by dianabarsan** [comment]
This is ready for AT on `5939-remove-update-sent-forms-transition`.

**Comment by garethbowen** [comment]
@dianabarsan This should be labelled "breaking change" right, just in case anyone is still using it?

I think if you load an old configuration then sentinel will crash with `Unknown transition "${key}"`

**Comment by dianabarsan** [comment]
Yes, you're right.

**Comment by tatilepizs** [comment]
**Config:** Standard
**Environment:** Local
**Platform:** WebApp 
**Browser:** Chrome

Using branch `5939-remove-update-sent-forms-transition` reminders are working as expected.

![image](https://user-images.githubusercontent.com/94494491/167887997-17ca765f-3105-4476-929f-65e151a0e4ad.png)

And loading an old config the sentinel will show the error

![image](https://user-images.githubusercontent.com/94494491/167894578-f06f3b14-1fab-4863-9fb1-e26d544ee2c3.png)

**Comment by garethbowen** [comment]
Merged.
