### ISSUE TITLE
Create new API endpoint to replace settings

### ISSUE THREAD

**Issue by wtekeu** [medic/cht-core#5940]
**Is your feature request related to a problem? Please describe.**
Currently, the endpoint `/api/v1/settings?replace=1` does not really replace the settings document but updates it by overwriting properties with matching key therefore existing properties without matching keys in the request are not deleted.

**Describe the solution you'd like**
Ideally, we should build an endpoint that is backward compatible that allows us to truly replace the settings document.

**Additional context**
This endpoint is used by `medic-conf` to upload the app settings.

**Comment by garethbowen** [comment]
If you can come up with a good name this could be done as a new param, for example, `/api/v1/settings?overwrite=1`. We need to clearly document the difference between `replace` and `overwrite` (or whatever it's called).

**Comment by wtekeu** [comment]
Ready for AT `5940-create-overwrite-settings-api`

**Comment by ngaruko** [comment]
LGTM.
At the moment there is no implementation in medic-conf yet, ie no code calling this endpoint in the current form. Testing can only be done by curl or other way to call the api outside medic-conf
