### ISSUE TITLE
Replace underscore with lodash in replication

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#5942]
**Describe the performance issue**
We're currently doing two calls to `underscore`'s `uniq` function in our replication code:
here: https://github.com/medic/medic/blob/master/api/src/services/authorization.js#L185
here: https://github.com/medic/medic/blob/master/api/src/services/authorization.js#L234

This is done because we might end up with duplicates when querying views that will result in multiple changes for a single doc (CouchDB will return a change as many times as it's id exists in the request list). 

Unfortunately, the implementation of `underscore`'s `uniq` (and likely other array functions) has very poor performance and is also resource blocking.
```
const _ = require('underscore');
const uuid = require('uuid');
_.uniq(Array.from({ length: 100000 }).map(() => uuid()));
```
This code snippet takes a whooping 39 seconds to execute on my machine. Granted this is an extreme case, but there have been misconfigured users that have this many docs. It would be nice to not block API sorting their allowed doc ids.

**Describe the improvement you'd like**
Straight up replacing `underscore` with `lodash` looks like a good solution.
```
const lodash = require('lodash');
const uuid = require('uuid');
lodash.uniq(Array.from({ length: 100000 }).map(() => uuid()));
```
This code snippet takes 0.39 seconds to execute. 

**Describe alternatives you've considered**
Alternatively we could write our own array/object functions and put them into a shared lib. 

**To Reproduce**
Create a misconfigured offline user (to have a significant impact, have at least 50 000 docs). Login with that user and start replicating. 
In the same time, logged in as an online user, try to browse the app and observe if it's responsive or not. 

**Environment**
- App: api
- Version: 3.7

**Comment by garethbowen** [comment]
Perhaps we should consider replacing underscore with lodash throughout the codebase in a later version. My understanding is it's much faster in part because it doesn't handle edge cases as well, but if we're not relying on those edge cases I don't know of any reason not to use it.

**Comment by dianabarsan** [comment]
100% agree. I was planning to write up an issue to cover this tomorrow. :)

**Comment by dianabarsan** [comment]
We have multiple places where there's potential to pass extremely large data sets to underscore where we could have significant improvements. I have one example I ran into and planned to change next release: https://github.com/medic/medic/blob/master/shared-libs/search/src/search.js#L40 - I suspected this was the source of the browser crash that happened here: https://github.com/medic/medic/issues/5724

**Comment by dianabarsan** [comment]
Ready for AT on `5942-lodash-replaces-underscore-in-authorization`

**Comment by garethbowen** [comment]
Reopening to include in 3.6.1 release.

**Comment by garethbowen** [comment]
Backported to `3.6.x`
