### ISSUE TITLE
Rename `medic` repo to `cht-core`

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#5944]
Given that this repo is the _Core Framework_ for the _Community Health Toolkit_ we should rename the repo accordingly. After discussion we decided on the repo name `cht-core`. As part of this change we should also update all links to this repo from our own website, as well as all links from this and all other repos in the `medic` org.

**Comment by garethbowen** [comment]
- [x] Announced in `#general`
- [x] Announced in `#development` with update instructions
- [x] Medic and CHT websites scanned for old links (updates pending)
- [x] Checked travis and it appears to be working
