### ISSUE TITLE
Consider replacing underscore with lodash throughout our codebase

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#5946]
**Describe the issue**
`underscore` is proving to be having very poor performance when working with large data sets.
See https://github.com/medic/medic/issues/5942, where running a `uniq` over 100,000 uuids takes more than 30 seconds, where such an operation should be well below half a second. 

Besides the offline user replication, we also deal with potentially large data sets in our `Search` library, which also uses `underscore` across the board to process arrays. Our `search` library runs both on devices and server-side. 

**Describe the improvement you'd like**
`lodash` is looking like a good, performant and compatible alternative (most used `underscore` functions exist in `lodash`, having same name and same accepted parameters - there are exceptions though, so it won't be a 100% effortless replacement).

**Describe alternatives you've considered**
Alternatively we could write our own array/object functions and put them into a shared lib.

**Comment by garethbowen** [comment]
Ready for AT in `5946-no-underscore`

**Comment by garethbowen** [comment]
AT instructions:

This affects just about all the code in the app including sentinel and api. Particularly test the searching and filtering paths as they've changed the most.

**Comment by ngaruko** [comment]
1- Filtering by place seems to be broken (no errors in the console) - Did you want to have a second look at this @dianabarsan ? (Tested on local with `cht ` config and see data in the repo)
![image](https://user-images.githubusercontent.com/6979995/74621664-98e64100-51a2-11ea-8397-99cbb017f3e0.png)

2 - There are conflicts on the branch-

**Comment by dianabarsan** [comment]
@ngaruko I believe what you are seeing for the places filter was introduced with https://github.com/medic/cht-core/issues/4423. 
To have the places filter load when you first click it is normal behavior, I believe, and it should populate as it receives data. 
Are you logged in as an offline user? In that case, it might also be that the view the places filter is using must also be warmed (it uses `medic-client/contacts_by_type`). Did you load the People
s page before loading the reports page? That would assure that the view is already warmed. 

I tried the places filter locally, both offline and online accounts, and it looks like it works as expected.

**Comment by dianabarsan** [comment]
I also resolved the conflicts.

**Comment by ngaruko** [comment]
Thanks @dianabarsan
