### ISSUE TITLE
Login page redirection doesn't work

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5955]
Part of this is covered and blocked by: #5954 (service workers cache dynamic login page elements)

Regardless of this caching issue, even if the redirect url gets set correctly into the login page it still doesn't work as expected. Instead, you either get redirected to the admin app if you're an online user, or the default page of the main app if you aren't.

**Comment by eljhkrr** [comment]
Ready for AT on `eljhkrr:redirect`

**Comment by SCdF** [comment]
Hey @eljhkrr, thanks for working on this!

For us to be ready for AT we first need the PR to be accepted by a core developer or similar member of the product team. Currently it has been reviewed by Kenn, but required changes and hasn't been marked for approval. 

I've requested myself to review it (and will get to it today!), though if you feel someone else would be more appropriate select them as you'd like. I've also moved this ticket back into in progress.

We also unfortunately need the PR to be created against the main repo and not a fork because forks don't create [a build](https://staging.dev.medicmobile.org/builds/releases) that a QA can install. @garethbowen / @ngaruko do we have a workaround / intended approach for this situation? I know builds no longer fail if they are forks, but they still don't generate a build.

**Comment by garethbowen** [comment]
The only workaround currently is QA deploying from source. We don't really want to encourage people to install untrusted builds so we can't make it too easy. Ideally we'd have some artefact that could be manually distributed, which we could have a look at once the build artefact is a Docker image.

**Comment by garethbowen** [comment]
Ready for AT in `5955-fix-login-page-redirection`. I recommend ATing #6280 first...

**Comment by garethbowen** [comment]
To reproduce...

1. In a browser, log in to the app
2. Click on the Reports tab
3. Select the second report in the list
4. Notice that the URL has `/#/reports/<uuid>` at the end.
5. Log out
6. Log in again

Actual: You see the first tab is selected (Messages, if available), and no list item is selected.
Expected: You see the Reports tab is active and the report you selected in step 3 is selected and rendered on the RHS.

Test this in the Android app also, but as it's easier to see and confirm in the desktop browser start there.

**Comment by brad1905** [comment]
AT has passed for desktop browser and Android app and this is ready to be merged
