### ISSUE TITLE
deploy-info e2e test doesn't work locally

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5956]
[This test](https://github.com/medic/medic/blob/master/tests/e2e/api/routing.js#L160-L169) never works locally because it relies on deploy-info having some deploy info, which isn't available unless the ddoc has been built for horti.

We should either disable / auto-pass this test locally, or change how we build locally so that there is a local deploy-info.

**Comment by dianabarsan** [comment]
I believe this has been fixed when we switched our e2e utils to use `request-promise-native` instead of `request`. 

Would someone mind confirming?

**Comment by SCdF** [comment]
Can confirm this now passes!
