### ISSUE TITLE
MessageQueueCtrl unit test is flaky

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#5960]
```
1) queries settings and loads translations before querying, loads first page

     MessageQueueCtrl controller init

     Error: Uncaught AssertionError: expected undefined to equal 'my date format' (/home/travis/build/medic/medic/node_modules/chai/chai.js:239)
```

I can't get this to fail locally (and thus reproduce what's going on) but it often fails on Travis.

**Comment by SCdF** [comment]
(cc @dianabarsan I'm not sure if you've seen this one and it was one of the ones you were attempting to deal with)

**Comment by dianabarsan** [comment]
I've seen this one :) thanks :)

**Comment by dianabarsan** [comment]
Adding another karma test to the list:
```
1) splits comma separated permissions
     auth directive
     Error: Uncaught AssertionError: expected true to equal false (/home/travis/build/medic/medic/node_modules/chai/chai.js:239)
```

Both these tests have something in common: they require Sinon stubs that return promises to be resolved in a `setTimeout` callback. 
I have no idea what could have changed to cause this behavior.  The test above has been around since 2016. I do not get any failures locally.

**Comment by garethbowen** [comment]
Similar: #6398

**Comment by garethbowen** [comment]
I split the Auth failure off as its own issue: #6439

**Comment by garethbowen** [comment]
@dianabarsan I think this can now be closed, unless there was something else you wanted to do with it?

**Comment by dianabarsan** [comment]
Yup, happy to close!
