### ISSUE TITLE
Forms show error message upon opening

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#5980]
**Describe the bug**
Some forms (eg New Pregnancy)come with `This field is required` error message upon opening.

**To Reproduce**
1. Go to '[reports](http://localhost:5988/#/reports/)' page
2. Click on 'Submit report'
3. Pick up for like `New Pregnancy` or `Pregnancy visit`
4. See `This field is required` error on the form.

**Expected behavior**
The form should be 'clean', only flag the error message when the user attempt to proceed without selecting the patient's name.

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/65481315-e78bf980-dee8-11e9-9471-9d6641c28369.png)

**Environment**
- Instance: local
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.6.* but has been this way for a while

**Comment by dianabarsan** [comment]
@jkuester I'm wondering if this changes with latest Enketo updates.

**Comment by jkuester** [comment]
Just want to confirm that I have tested both the standard `pregnancy` and `pregnancy_visit` forms. I was able to recreate the behavior on `3.15` but not on https://github.com/medic/cht-core/tree/6345-enketo-uplift so I think it is safe to say this has been fixed by the Enketo updates!

**Comment by jkuester** [comment]
@medic/quality-assurance this is ready for AT on https://github.com/medic/cht-core/pull/7256

**Comment by ngaruko** [comment]
Looking good at the moment
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/6979995/181194121-b2c55f6e-d2ec-4cf8-af2f-9f9fd3bd9222.png">
