### ISSUE TITLE
Remove the red count bubble from the Reports page

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5985]
**What feature do you want to improve?**
Remove the red count bubble from the Reports page. There’s nothing there that specifically requires attention (maybe excepting the mRDT workflow). We don’t want users to have to click through and “read” every single report in the list in order to get rid of the bubble, as that list can get long very quickly.

**Additional context**
This is a issue which derived from discussion in #3943.

Although we recently made a change to lazy-load this bubble (https://github.com/medic/medic/issues/5859), eliminating it would have further performance benefits and allow us to eliminate the `medic-user/read` index from all `medic-user-` databases.

**Comment by garethbowen** [comment]
I'm not 100% convinced by this. I think it's a good idea for smartphone based CHP workflows, however there are some SMS workflows where the clinic user is expected to read every submitted report. In those cases I suspect having a read count is useful so they can see when a new report comes in. We should investigate more to see if anyone is using this in production before dropping it altogether. One compromise would be to use a permission so it can be turned on when needed.

**Comment by n-orlowski** [comment]
Closing this issue as it is being addressed in https://github.com/medic/cht-core/issues/6290
