### ISSUE TITLE
Store PA risk scores in the patient

### ISSUE THREAD

**Issue by ecsalomon** [medic/cht-core#5998]
**Is your feature request related to a problem? Please describe.**
Currently, predictive algorithm risk scores are calculated in the app in both tasks and targets and in the contact summary. This creates duplication of code, is a potential source of technical debt, and leads to unnecessary computation.

**Describe the solution you'd like**
A better implementation of risk scoring is to set a minimum refresh window (e.g., 1 day, 1 week, 1 month) and store the risk score and its calculation date in the patient to be accessible by tasks, targets, forms, and contact summary. Scores would then be recalculated only when the age of the risk score is greater than the minimum refresh window.

**Describe alternatives you've considered**
Risk scores loaded to the contact page from the server side are infeasible in an offline-first context where we cannot guarantee that they will reach the phone in time to be of use.

**Additional context**
Depending on the approach taken in our screening work with PIH, this may be useful for implementation in that project in April 2020.

This is also relevant as we consider expansion and scale-up of our predictive algorithms initiatives through recently launched data science partnerships. These partnerships would be looking to close out in mid-2020, with implementation possibly in late 2020.

**Comment by ecsalomon** [comment]
Duplicate of #5708?

**Comment by MaxDiz** [comment]
@garethbowen please see above ^^ comment. The issues look like duplicates to me, but you're much closer to the work than I am

**Comment by garethbowen** [comment]
Yes let's close this as a duplicate. The other one has a little more discussion and is actually scheduled. @ecsalomon Please add any additional information to the other issue so it describes everything you need.
