### ISSUE TITLE
Alert when outbound pushes are repeatedly failing

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6001]
Currently if outbound pushes fail (e.g., the server they are sending to are offline) the sentinel log is updated with an error and the push is retried in 5 minutes.

This scales fine for a small amount of pushes, but will probably not scale to larger numbers of pushes.

Ideally if there is a failure we should be able to alert a responsible person about it.

**Comment by SCdF** [comment]
I'm putting improvement and technical issue on here as it's not clear to me if this is actually more coding (we don't have any kind of hook to send any kind of alert manually from code) or infrastructural, hooking into existing logs.

**Comment by garethbowen** [comment]
Either way I think this is an improvement as it impacts the users (in this case the server admin users).

**Comment by michaelkohn** [comment]
2 cents:

**Delivery options:** Slack (like couch2pg), email, SMS, etc...

**Frequency:** Real time, after a task has been retried `n` times, on a schedule (cron job runs every 15 minutes to see if there are any failed tasks in the queue and sends a notification if so).

**Bonus:** This could potentially be generalized so that we can have configurable actions based on the result of an outbound push. Even for successful transmissions, we may want to alert or trigger an update of something else (like ‘verifying’ a report).

**Comment by garethbowen** [comment]
For delivery options it should hook in to the instance monitoring rework documented here: https://docs.google.com/document/d/1LnfQrhBTbVC7zaGjJ2kCSsGJ23-E_Ii-D17Y0Z6WiK4/edit#

**Comment by kennsippell** [comment]
Have we considered switching to existing cloud-based queues instead of continuing to invest in a custom queue implementation? For example: https://aws.amazon.com/sqs/ 

Queues are one of those things that are easy to get started but hard to get scaling smoothly. This issue would be elegantly handled, as would monitoring.

**Comment by SCdF** [comment]
@kennsippell not that specific branded technology, or queues specifically, but yes we have considered not reinventing the wheel and using an external solution. Outbound was built the way it was because it was the fastest way to solve a particular problem, but it was never definitely intended to last forever.

As mentioned in related tickets (#6159, #6158), I agree that if we're building up steam in terms of what we've built not being enough, so IMO it's time to re-open the conversation!

**Comment by MaxDiz** [comment]
outbound push is integral to our current approach to interactive messaging. Adding to v3.10 based on outcomes from prioritization meeting April 16, 2020.

**Comment by MaxDiz** [comment]
Related https://github.com/medic/cht-core/issues/6158

**Comment by SCdF** [comment]
In 3.9 we added a monitoring API, which includes a count of how many queued outbound tasks their are.

Also in 3.9 we changed outbound to send immediately, and only gets queued if there was a problem.

So AFAICT, we already have this covered minimally, because if the outbound queue count is >0 then an outbound request has failed in the last ~5 minutes.

@garethbowen / @nomulex what is the proposed plan for using the new monitoring API that is getting released in 3.9? Is there anything that needs to happen that would be encompassed by this ticket, in terms of dealing with outbound specifically?

The next suggestion in complexity would be either:
 - Start recording counts of failures and have a separate monitoring output that counts how many tasks with >10 failures
 - (preferred) Use the datetime on tasks to have a separate monitoring output that counts how many tasks with >60min task age

**Comment by garethbowen** [comment]
I think the minimal solution (monitoring when the queue is > 0) is fine for now. We can refine this in future releases to expose more detail to reduce the noise but I propose we go with the minimal solution and see how it performs in a real world scenario before trying to work out how to improve it.

Therefore I propose we close this issue. @SCdF Does that work for you?

**Comment by SCdF** [comment]
Yep I'm happy with this.

For those reading in the future, this was addressed with the `/api/v1/monitoring` API, and the `outbound_push.backlog` result, with >0 meaning something is failing.
