### ISSUE TITLE
Format data for sending to DHIS2

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6002]
https://github.com/medic/medic/issues/5661 introduces the ability to calculate data for sending to DHIS2. Prior to sending this data to DHIS2 (or downloading it as a file to be uploaded), we'll need to format it in a way that DHIS2 can process. The DHIS2 documentation related to these formats can be found [here](https://docs.dhis2.org/master/en/developer/html/webapi_data_values.html#).

While there are a number of different formats supported, here is an example payload to help illustrate a few points. 

~~~JSON
{
  "dataSet": "pBOMPrpg1QX",
  "completeDate": "2019-10-03",
  "period": "201909",
  "orgUnit": "DiszpKrYNg8",
  "dataValues": [
    { "dataElement": "f7n9E0hX8qk", "value": 21 },
    { "dataElement": "Ix2HsbDMLea", "value": 17 },
    { "dataElement": "eY5ehpbEsB7", "value": 14 }
  ]
}
~~~

A `dataSet` is essentially a grouping of `dataElements` for the purposes of data entry. In Kenya, the **MoH 515 CHEW Summary** is an example of a `dataSet`, and the core dimensions that describe data in DHIS2 are as follows (*All data values will at a minimum have these 3 dimensions*):

- The **where** : *organisation unit* (ex. Bondo CHU)
- The **what** : *data element* (ex. Total Deliveries)
- The **when** : *period* (ex. September 2019)

Data can also be disaggregated further using `categoryOption` and `categoryOptionCombo`.  The diagram below attempts to illustrate the relationship between all these dimensions.

So for each of the calculations we define in https://github.com/medic/medic/issues/5661 , at a minimum we'll need to map to a `dataElement`, and possibly a `categoryOptionCombo` as well.

![DHIS2 Data Set Hierarchy](https://user-images.githubusercontent.com/10096985/66392678-4b85e600-e9f0-11e9-8d88-db7465b0370d.jpg)

**Comment by kennsippell** [comment]
Ready for AT in branch `dhis2`
Documentation at https://github.com/medic/medic-docs/pull/175
Requires this medic-conf change to test https://github.com/medic/medic-conf/pull/285

**Comment by ngaruko** [comment]
LGTM. Back to you @kennsippell  for a merge
