### ISSUE TITLE
Run CHT-Reference-App tests through travis

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6009]
The tests in `medic/config/default/test` are not current run through travis. To ensure these stay running, we should connect them to travis.

Might want to fix https://github.com/medic/medic-conf-test-harness/issues/6 before that for performance reasons.

**Comment by garethbowen** [comment]
Pushing back to 3.9.0 as there's no urgency on this one.

**Comment by kennsippell** [comment]
This has passed CR. I don't believe it needs to be ATed. 
Can't merge it quite yet, since the base branch is waiting for this one https://github.com/medic/cht-core/pull/6155.

**Comment by kennsippell** [comment]
This a test-only change, so skipping AT
