### ISSUE TITLE
Timeout option is not set during replication

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6023]
**Describe the bug**
During initial replication, the `timeout` option to PouchDB is [set to 10 minutes](https://github.com/medic/medic/blob/master/webapp/src/js/bootstrapper/index.js#L103).  During routine replications, the `timeout` option is [not set](https://github.com/medic/medic/blob/master/webapp/src/js/services/db-sync.js#L52) and uses PouchDB's default.

**Expected behavior**
The two replications should have matching timeouts.

**Additional context**
We should make this change in 3.8 along-side the features around writing tasks to disk since that feature is expected to increase the document count which will increase the time spent in _changes requests.

**Comment by dianabarsan** [comment]
Ready for AT on `6023-set-replication-timeout`.
The change only affects post-bootstrap replications.

**Comment by ngaruko** [comment]
LGTM
