### ISSUE TITLE
Outbound can halt scheduler execution permanently

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6025]
**Describe the bug**
We have noticed (cc. @senseibara) instances where the outbound push scheduled task appears to freeze, in one case a week before we restarted sentinel. This doesn't kill Sentinel completely, instead somehow the outbound promise chain never resolves (or rejects), which causes the scheduler to not progress, which also means nothing ever gets rescheduled.

No reproduction steps right now, it happened once once and there wasn't any interesting log output. Restarting sentinel pushed it forward (it processed 20 documents and then froze again, restarting it once more processed the last dozen or so).

The only two guesses I have are:
 - There is an instance where we haven't coded the flow right and we're breaking the promise chain (e.g. we manually create a promise because we're mixing in callbacks, and `resolve()` or `reject()` never get called)
 - Some piece of I/O that we're doing doesn't have a default timeout configured and is blocking indefinitely

**Comment by SCdF** [comment]
I looked through our code and couldn't find any reason that it should hang other than outbound requests, so I added an explicit timeout to them.

It's not clear that this will fix the issue but it's a fine start. If after this we still get issues we should turn on debug logging in production until we catch it happening again, as that should point more clearly to the location in the code where its hanging.

@nomulex has this happened again btw? Do you think this is worth back-porting into a point release (3.6.x or 3.7.x would be supportable candidates), or just leave it for 3.8.0?

**Comment by nomulex** [comment]
@stefan  If we see that the fix works then I propose we back port to 3.6.x.

**Comment by SCdF** [comment]
I had a bit of a brain issue and merged the PR to master before AT!

I've also asked Alex if he'd be happy with doing this in 3.7.1 instead of 3.6.x.

For backporting, the git hash is db13af1

**Comment by ngaruko** [comment]
LGTM on `3.7.1`. Just to confirm if I understood the above conversation between @SCdF and @nomulex . Are we still backporting this to 3.6.X?

**Comment by garethbowen** [comment]
@ngaruko This code hasn't been merged to 3.7.1 yet. How did you test it?

**Comment by ngaruko** [comment]
@ngaruko It was tested this on `master , 3.7.0`, my bad!
![image](https://user-images.githubusercontent.com/6979995/67827390-bf6d6700-fb34-11e9-9e59-48dcce9f0324.png)

**Comment by dianabarsan** [comment]
Backported to `3.7.x`
