### ISSUE TITLE
Title test too long for mobile 340px view port width

### ISSUE THREAD

**Issue by ghost** [medic/cht-core#6028]
**Pregnancy danger sign follow up** too long to fit into header of mobile view task form. Is there a way to limit character count to 26 followed by ...
This would hold true if for all headers in forms for mobile views.

1. Go to Task tab
2. Select Pregnancy danger sign follow up task.

View port width is set to 340px.

![header text](https://user-images.githubusercontent.com/5149601/66948335-5b618380-f009-11e9-9cd2-6ed80c3b4548.png)

**Comment by garethbowen** [comment]
We shouldn't limit the number of characters because, for example, a translation with a lot of the letter i will be able to fit more letters than one with a lot of the letter w. Use the text overflow css property to apply ellipsis if the title runs over, and consider changing the English translation of the form title so it doesn't hit this limit on our target devices.

**Comment by nomulex** [comment]
@garethbowen , Is this something we can achieve in css with something like [this](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp)?

**Comment by garethbowen** [comment]
@nomulex Yes absolutely that's how it should be done. I think there are two parts to this:

1. modifying the CSS so it looks better, and
2. thinking about modifying the configuration so the title fits (if possible).

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by latin-panda** [comment]
This issue happens in tasks, reports and contacts.

I think this work doesn't need to be a FR and doesn't require user training. After it passes AT then it can be merged into the next CHT-Core release (3.16.0 or 4.0.0)

@michaelkohn do we want this in 3.16.0? Then we'll coordinate with @njogz (release manager) 
cc: @elvisdorkenoo

**Comment by michaelkohn** [comment]
If it can make it into 3.16 without delaying the release, that'd be great. If not, then let's put it in the next release after 3.16.

**Comment by latin-panda** [comment]
Feature was merged

**Comment by latin-panda** [comment]
@njogz this is ready for v3.16.0, currently only available in master branch.
