### ISSUE TITLE
Inconsistent field label in CHT Reference App - Blue skin color

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6029]
Minor inconsistency in the field labels. 

Form | Field | Label:EN
-|-|-
delivery|blue_skin|Blue skin color
pnc_danger_sign_follow_up_baby|blue_skin|Blue skin color (hypothermia)

The preference is to update the label in the `delivery` form to be **Blue skin color (hypothermia)**

**Comment by abbyad** [comment]
This change is now included as part of #6082, which will be included in 3.7.1. Once we verify that it is fixed there we can close this issue.

**Comment by garethbowen** [comment]
Scheduling in 3.7.1. Ready for AT in `6052_Misiing_labels`

**Comment by newtewt** [comment]
Looks to be updated.

**Comment by garethbowen** [comment]
Merged to `master` and backported to `3.7.x`
