### ISSUE TITLE
Age is missing when using unknown for birth date and entering years. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6040]
**Describe the bug**
Selecting unknown for the birth date while creating a new person. Then entering years into the required fields. Will not display anything on the profile page for the Age. 

**To Reproduce**
1. Navigate to new person form
2. Enter all fields and select unknown for the birth date. 
3. Enter a year and month value for the age. 
3. Submit the form.
4. The age is not showing on the contact summary. 

**Expected behavior**
The age should display whether it is entered as years or as a date of birth. 

**Environment**
- Instance: localhost-default cht config
- Browser: Chrome
- Client platform: linux
- App: webapp
- Version: 3.7.0

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Ready for AT on `6040_age_failing`

**Comment by ranjuts** [comment]
The solution suggestion might cover this as well. Flagging just in case --- the age is also not displayed in the Summary. @nomulex 

![Screen Shot 2019-10-22 at 5 50 27 PM](https://user-images.githubusercontent.com/5404004/67286133-93306580-f4f8-11e9-838a-1e2774ed4e2f.png)

**Comment by newtewt** [comment]
@nomulex  this is working for the forms changed in your PR. Looks like the create place forms need to be updated as well. When creating a person while creating a place the same issue occurs.

**Comment by newtewt** [comment]
@nomulex  I've fixed the age issue when creating a person during place creation. Can you review the PR  https://github.com/medic/cht-core/pull/6058

**Comment by newtewt** [comment]
The age is now calculated appropriately when entering years and months.
