### ISSUE TITLE
Missing labels for report form fields

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6052]
**Describe the bug**
The fields labels in the report view are not defined for the ANC Reference App forms, leaving the default long field names showing. We should add field translations for all forms in the ANC Reference App config.

**To Reproduce**
1. Open Reports tab
2. Submit (or open) a report (tested with `Pregnancy danger sign follow-up`)
3. See the field titles in the report view

**Expected behavior**
We should have easy to read field labels instead of the long field ID. For example `Visited Clinic` instead of `report.pregnancy_danger_sign_follow_up.danger_signs.visit_confirm`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/67329856-717bb200-f4e9-11e9-8895-fac4cc443d98.png)

**Environment**
- Instance: cht.app
- Browser: Chrome 77
- App: webapp
- Version: 3.7.0-beta.3

**Comment by garethbowen** [comment]
@nomulex How are you getting on with this? We're getting close to releasing 3.7.1 and it'd be great to include this in that release. Let me know if I can help.

**Comment by nomulex** [comment]
Hi @garethbowen  , I have sent in a PR [here](https://github.com/medic/cht-core/pull/6082) to @abbyad

**Comment by garethbowen** [comment]
Ready for AT in `6052_Misiing_labels`

**Comment by newtewt** [comment]
I see a few missing labels still. Should we fix before moving on?

report.pregnancy.anc_visits_hf.anc_visits_hf_past.visited_dates_group.visited_dates_count
report.death_report.patient_id
report.death_report.patient_uuid

**Comment by abbyad** [comment]
@newtewt where are you testing, and are you using the forms from 3.7.1?

This field doesn't seem to exist in the pregnancy report:
`report.pregnancy.anc_visits_hf.anc_visits_hf_past.visited_dates_group.visited_dates_count`

These fields appear to be hidden in the latest XLSForm so shouldn't show for newly submitted reports using the new forms:
`report.death_report.patient_id`
`report.death_report.patient_uuid`

**Comment by newtewt** [comment]
I'm using the xmls as they are committed in `6052_Misiing_labels` branch.  

After converting the forms with medic-conf the later are hidden. Just something to keep in mind that whatever is committed is what will eventually be applied as default. 

 `report.pregnancy.anc_visits_hf.anc_visits_hf_past.visited_dates_group.visited_dates_count` still displays when viewing a new pregnancy report after converting and uploading.

**Comment by abbyad** [comment]
Ah, the `visited_dates_count` isn't in the XLSForm, but is in the XForm, so it must be a generated field for the `visited_dates` repeat group. I'll add that one now.

I don't get why you had to reconvert the `death_report` though. Those fields were hidden in the branch for this issue: https://github.com/medic/cht-core/blob/a35d0f01a4870f59d6c226095189f92955cb3ef2/config/default/forms/app/death_report.xml#L120-L121

The fields are also hidden in the current `master` and `3.7.x` branches.

It may be worth testing on a fresh push of the config as it is in the 3.7.1 beta.

**Comment by garethbowen** [comment]
Merged to `master` and backported to `3.7.x`
