### ISSUE TITLE
Use relative date of death in list of deceased persons

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6053]
The list of deceased persons shows the relative date of death, except when it is the current day, in which case it shows the time as 00:00. We should use a relative date for _all_ dates of death, and not the time.

For instance in the example below it should be `Died today`, and then continue `Died x {units} ago` as it is already.

![image](https://user-images.githubusercontent.com/789512/67331071-50b45c00-f4eb-11e9-8ce6-a918ef809a11.png)

_Screenshot from cht.app on 3.7.0-beta.3_

**Comment by abbyad** [comment]
As part testing for this I was seeing the "days ago" not corresponding to the calendar days, which may be due to a timezone issue. For example marking a date of death as yesterday at 11am EDT in the report shows as "2 days ago" when looking at the report at 3:30pm EDT.

@garethbowen do you want a separate issue for this, or tackle it here?

**Comment by garethbowen** [comment]
Make a separate issue for that one - I don't want it to get missed!

**Comment by garethbowen** [comment]
Ready for AT in `6053-better-formatting-for-died-today`

**Comment by ngaruko** [comment]
LGTM
**on master**
![image](https://user-images.githubusercontent.com/6979995/69024753-fb576600-0a28-11ea-9730-b5cec283bdca.png)

**branch**
![image](https://user-images.githubusercontent.com/6979995/69024772-1a55f800-0a29-11ea-85c4-1de1fd7ce967.png)

Pinging you @abbyad as a reminder to raise another issue for the [comment](https://github.com/medic/cht-core/issues/6053#issuecomment-545603195) above.
