### ISSUE TITLE
Death reporting transition requires patient_id

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6056]
**Describe the bug**
https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/transitions/death_reporting.js#L69
Instead, it should require a `patient`, linked by either accepted fields: `patient_id` or `patient_uuid`.
This effectively stops processing of death reports that are submitted "offline"

**To Reproduce**
1. Install "default" configuration
2. Login with an offline user. Stay offline to make sure you don't sync.
3. Create a new person. Create a death report for that person.
4. Sync.
5. Observe that the person is not reported as "Deceased" even after Sentinel has processed the death report. 
6. Make sure the person has a "Medic ID" and submit a death report again. Sync.
7. Observe that the person is now reported as "Deceased" after a second sync.  

**Expected behavior**
The patient doc should not be required to have a "patient_id" field. The first submitted report should have been sufficient.

**Environment**
- Instance: any
- App: webapp, sentinel
- Version: any, including 3.8

**Comment by dianabarsan** [comment]
Ready for AT on `6056-death-reporting-patient`

**Comment by ngaruko** [comment]
LGTM
