### ISSUE TITLE
Refactor the registration transition

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6061]
**Describe the issue**
https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/transitions/registration.js
The registration transition:
- is considerably large
- is almost entirely callback based
- uses an old testing workaround to expose methods for testing by `module.export`-ing everything. 

This makes it hard to read, follow and extend.

**Describe the improvement you'd like**
Due to the updates that it will receive [for adding places by sms](https://github.com/medic/cht-core/issues/5614) within this release, it's an opportune moment to refactor it to be entirely Promise based, to not export every function, and leverage `rewire` for testing.

**Comment by dianabarsan** [comment]
Ready for AT on `6061-refactor-registration`
Please make sure that all `registration` functionality works as expected: new patients, clearing and creating schedules, setting expected date, setting birth date etc.

**Comment by ngaruko** [comment]
LTGM - Will pay a little more attention during RT around registration .
