### ISSUE TITLE
Configurable contacts not correctly mapped as SMS recipients

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6071]
**Describe the bug**
When using configurable hierarchy type contacts (using `type` and `contact_type` properties) and generating SMS messages that have `place_type` recipients (like `clinic` or `ancestor:whatever`), all SMS messages will end up being sent to the `reporting_unit`.

**To Reproduce**
1. Have a contact hierarchy that has `type: contact` and `contact_type` properties. I can be the classic `district_hospital`, `health_center`, `clinic`. Our `message-utils` library doesn't care about what contact types we have actually configured. 
2. Have an SMS message that should be sent to to someone within this hierarchy, generated by a report submitted by another contact than the desired recipient.
3. See that the actual message `to` ends up to be the `reporting_unit`. 

**Environment**
- Version: 3.7, 3.8

**Comment by garethbowen** [comment]
Ready for AT in `6071-fix-sms-recipient-mapping`.

@dianabarsan I think we should release a 3.7.1 with this as all configurable hierarchy will break all messaging - what do you think?

**Comment by dianabarsan** [comment]
@garethbowen I agree.

**Comment by newtewt** [comment]
Cool! I'm seeing the messages getting mapped if they are custom or not and to the different levels.

**Comment by dianabarsan** [comment]
Backported to `3.7.x`
