### ISSUE TITLE
Timeouts for /api/v1/users leave user at "loading app..." forever

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6084]
**Describe the bug**
If a request to /api/v1/users-info results in a 500 timeout response there is an error on the server, but the user is left in state "Loading app…" with no indication of failure.

**To Reproduce**
1. Navigate to webapp
1. Login as user with lots of documents
1. Spoof connection to server to result in a 500 response for the request to `/api/v1/users-info`

Observed behavior: User is left in initial replication screen showing "Loading app…" forever

**Expected behavior**
The user should see an error when the replication has failed to proceed

**Logs**
```
2019-10-31 14:32:49 ERROR: Server error: { error: 'timeout',
  reason:
   'The request could not be processed in a reasonable amount of time.',
  status: 500,
  name: 'timeout',
  message:
   'The request could not be processed in a reasonable amount of time.' } 
RES bb50cbce-4926-4ec1-a578-0227f094b90d ::1 - GET /api/v1/users-info HTTP/1.1 500 35 60042.720 ms
```

**Environment**
- Instance: dev
- Browser: chrome
- Client platform: linux
- App: webapp
- Version: master

**Comment by garethbowen** [comment]
@kennsippell Does refreshing the page/app call the API again and (assuming the call succeeds) workaround this bug?

**Comment by kennsippell** [comment]
@garethbowen Yep. Just need the UI indication that a reload is necessary.

**Comment by garethbowen** [comment]
TIL...

1. The fetch API doesn't have a timeout, so what I think is happening is nginx or the load balancer is killing the request probably after 30s but the client is never notified. This means it will keep waiting with no chance of success. The API log happens after the connection is dropped so the client is never notified.
2. The fetch API never throws, so if API responds with some sort of failure the client will check `response.warn` which isn't set and then continue with the initial replication without warning.

We need to add a timeout mechanism so the user isn't waiting forever, as well as check the status code on the response and handle any errors.

**Comment by garethbowen** [comment]
I managed to reproduce this by throwing an error deep in the purged-docs service. What happens is...

1. The request to `/api/v1/users-info` fails and is ignored by the client as it uses fetch and fetch never rejects
2. Then the request to `/purging` fails and is ignored by the client as it also uses fetch
3. Finally we request `/medic/_changes` to start the replication which throws an unhandled rejection in API and never responds to the request so the client hangs there waiting.

![Screenshot from 2019-11-05 13-20-48](https://user-images.githubusercontent.com/2064938/68168850-1ceb3300-ffcf-11e9-90bf-e8f1a73324a2.png)

```
2019-11-05 13:21:49 INFO: Form with ID "form:nutrition_screening" does not need to be updated. 
REQ 5668739c-d749-418e-94d9-6028dee57e30 ::1 - GET /api/v1/users-info HTTP/1.1
caught error Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-05 13:21:51 ERROR: Server error: { Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'Error: gareth\n    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]: 'gareth' } 
RES 5668739c-d749-418e-94d9-6028dee57e30 ::1 - GET /api/v1/users-info HTTP/1.1 500 35 80.200 ms
REQ 9f88fdfe-aa4e-403c-8070-c148e522104d ::1 - GET /purging HTTP/1.1
caught error Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-05 13:21:51 ERROR: Server error: { Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'Error: gareth\n    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]: 'gareth' } 
RES 9f88fdfe-aa4e-403c-8070-c148e522104d ::1 - GET /purging HTTP/1.1 500 35 14.270 ms
REQ 6e6ecd0d-67f2-462b-8074-99b2d5d52526 ::1 - GET /dbinfo HTTP/1.1
RES 6e6ecd0d-67f2-462b-8074-99b2d5d52526 ::1 - GET /dbinfo HTTP/1.1 200 208 3.997 ms
REQ 01271638-ece2-47fc-b96b-55d57a886b4e ::1 - GET /medic/_local/q9MXN81ln4dzP1qWDLUdOA%3D%3D? HTTP/1.1
RES 01271638-ece2-47fc-b96b-55d57a886b4e ::1 - GET /medic/_local/q9MXN81ln4dzP1qWDLUdOA%3D%3D? HTTP/1.1 304 0 4.136 ms
REQ b638f027-a264-4109-9186-f32e0792dfe0 ::1 - GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&initial_replication=true&since=0&limit=100 HTTP/1.1
caught error Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-05 13:21:51 ERROR: UNHANDLED REJECTION! 
2019-11-05 13:21:51 ERROR:   Reason: { Error: gareth
    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'Error: gareth\n    at db.exists.then.exists (/home/gareth/src/medic/cht-core/api/src/services/purged-docs.js:16:27)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]: 'gareth' } 
REQ 615d7fbd-5635-4420-9429-b9ca1a536dfa ::1 - GET /service-worker.js HTTP/1.1
RES 615d7fbd-5635-4420-9429-b9ca1a536dfa ::1 - GET /service-worker.js HTTP/1.1 200 - 15.873 ms
```

I think it's acceptable to ignore errors in the first two requests. The first one is trying to detect if there's going to be too many docs to replicate - it's a nice to have but we shouldn't block on it. The second one is detecting purging but we can do that next time we log in. If we catch and respond when the changes feed fails then the bootstrapper will try again as expected, including the other two requests.

**Comment by garethbowen** [comment]
This is a difficult one to AT. The original reproduction involved slowing down couchdb enough that a 60s timeout would be thrown. My reproduction was to manually insert an error into the same spot in the code which is just before the `if (!exists) {` check on line 15 of `/api/src/services/purged-docs.js`.

**Comment by garethbowen** [comment]
Ready for AT in `6084-handle-bootstrap-errors`

**Comment by dianabarsan** [comment]
A way to "slow down" CouchDB so it won't respond in time is to change one of the views in `_design/medic` to trigger view re-indexing, for a significantly large DB. All not-indexed view queries will respond with 
```
{ 
  error: 'timeout',
  reason: 'The request could not be processed in a reasonable amount of time.',
  status: 500,
  name: 'timeout',
  message: 'The request could not be processed in a reasonable amount of time.' 
} 
```

**Comment by ngaruko** [comment]
LGTM - Thanks @dianabarsan for the note...
