### ISSUE TITLE
Reduce inbox.js bundle size to meet targets for 3.7 release (800kb)

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6087]
**Describe the bug**
If a module in the `shared-libs` folder has an npm dependency (for example `shared-libs/search` and `shared-libs/lineage` both require `underscore^1.9.1`). The webapp's bundled script inbox.js includes one copy of the library for each shared-lib with the dependency. So in this case, there are 3 copies of underscore^1.9.1 (one for search, one for lineage, and one for webapp).

However, this does not seem to reproduce for all dependencies.

**To Reproduce**
To measure the size of the minified script, run: `grunt build-js minify && ls -l ~/webapp/build/ddocs/medic/_attachments/js`

1. View the current size of the script for master (2968125).
1. Go into the source for `shared-libs/search` and replace `require('underscore')` with `{}`. This will allow the code to build, but it won't function.
1. Repeat this process for `shared-libs/lineage`

**Expected behavior**
This shouldn't significantly change the size of the inbox.js script. Only a few characters have changed. Underscore is required elsewhere, so it should still be included once and only once in the bundle.

**Observed behavior**
Script weight reduces significantly 18kb (18038) for each shared-lib. Total of 36kb for this example with underscore. 
I can reproduce this for lodash for ongoing work with tasks/targets improvements.
However, removing `moment` from `shared-lib/search` and `shared-libs/message-utils` in the same fashion did not result in any savings. No repro for `google-libphonenumber` either. I'm not sure why.

**Additional context**
These are the shared-libs used by webapp and their dependencies.

Shared-lib | Dependencies
-- | --
Registration-utils | -
lineage | Underscore^1.9.1
Phone-number | Google-libphonenumber
Bulk-docs-utils | -
Message-utils | Underscore Moment Mustache Object-path Gsm Google-libphonenumber Bikram-sambat-bootstrap
search | Moment Underscore^1.9.1
Task-utils | -
Translation-utils | -

This is causing test failures for https://github.com/medic/cht-core/issues/5657.

**Comment by garethbowen** [comment]
The reason google-libphonenumber and moment don't affect the library size may be because of the browserify alias overrides here: https://github.com/medic/cht-core/blob/master/Gruntfile.js#L186-L187

A quick fix would be to override underscore and lodash too but that's risky if other libraries require different versions. We also need to find a way to do this automatically so any new dependencies in shared-libs don't get included twice.

**Comment by kennsippell** [comment]
Interesting -- good point.

I personally find it confusing to have so many package.json files within a single repository. I'm unclear on the advantages of having 20 different directories inside the same repository manage their dependencies indepenently (and redundantly)? Would we consider just moving to have all dependencies for the repository installed and managed via a single package.json at the root of the branch?

**Comment by kennsippell** [comment]
Some mixed successes with aliasing. The proposed change for tasks-v2 now increases the script weight above our maximum gzipped bundle size of 800kb. This issue tracks an investigation to get the inbox.js bundle size back down to 800kb. https://github.com/medic/cht-core/pull/6041/files

I've tried:
1. Moving the new code from shared-lib/rules-engine into webapp/src/js/modules/rules-engine without affect
1. Create browserify aliases for lodash and underscore. Saves ~15kb.
1. Profiling and compare the browserify list of included files via `browserify --list`. This is a super interesting list to go through and see if we can optimize something to get back under the 800kb quota.

**Comment by garethbowen** [comment]
Let's do the low hanging fruit and then just bump the bundle size limit. We definitely don't want the shared libs causing duplicate identical dependencies so if we can alias those away that's a great start. I'm hoping we'll get a decent improvement when we replace the build stack with webpack and maybe do some tree shaking which is scheduled for 3.9.0.

**Comment by kennsippell** [comment]
Ready for AT on `6087-reduce-bundle-size`

**Comment by garethbowen** [comment]
No AT required - any bugs will be caught in smoke testing.
