### ISSUE TITLE
Refactor Auth service to return boolean not throw

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6092]
**Describe the issue**
The Auth service throws if the user doesn't have permission to do a thing. This was chosen because we expected to call the Auth service to ensure the user can do the thing they asked to do. However it's turned out we use it a lot just to decide whether or not to present the action when not having the permission is not an error case. This means we've ended up with a lot of code like

```js
Auth('can_edit').then(() => true).catch(() => false)
```

**Describe the improvement you'd like**
Change the Auth service to always return a boolean. Update the calling code to check the boolean and throw if desired.

When implementing this also consider whether there is enough common code in the API auth.js module to warrant making a shared-lib for auth.

**Describe alternatives you've considered**
We could have two implementations but because the boolean is overwhelmingly desired we should implement this one as default. We can add a separate implementation for throwing if that becomes popular.

**Comment by kennsippell** [comment]
Available for AT in `6092-auth`

This specifically impacts:
* Admin console
* Viewing of tabs
* Viewing tasks on contact tab
* Tour
* Rules engine

**Comment by ngaruko** [comment]
LGTM
