### ISSUE TITLE
Modal service throws unhandled rejection

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6100]
**Describe the issue**
When a modal dialog is shown with the Modal service and the users cancels it the promise is rejected. Most of the time the developer forgets to handle this rejection because we don't want to do anything special. Even if they do remember it's annoying repetitive boilerplate, eg: `.catch(() => {})`.

The downside is you get an alarming error message in the console which may also be generating useless feedback docs.

![Screenshot from 2019-11-11 11-14-25](https://user-images.githubusercontent.com/2064938/68551697-75f61380-0474-11ea-890b-608d519249d5.png)

To reproduce
1. Go to the hamburger menu
2. Click on User Settings
3. Click Edit User Profile to bring up the dialog
4. Dismiss the modal by either pressing escape, clicking the `x`, or clicking the background.

**Describe the improvement you'd like**
Add this to the modal service:

```js
.then(() => true)
.catch(() => false);
```
Update all callers to make sure this is the desired behaviour and to remove the error handling code that is now unneeded.

**Describe alternatives you've considered**
...

**Comment by garethbowen** [comment]
This may be made obsolete by replacing the modal service as part of upgrading angular.

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by michaelkohn** [comment]
Do we have an indication if the angular upgrade resolved this?

**Comment by garethbowen** [comment]
I'll check this (and a few others that are hopefully solved for free) after the merge.

**Comment by garethbowen** [comment]
Cannot reproduce with latest Angular. Closing as done.
