### ISSUE TITLE
Retry upwards replication

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6103]
PouchDB does upwards replication in batches of 100 documents. For every batch, API will check each doc to determine whether the user is allowed to edit or create it, in the context of the current batch: if a batch contains a new contact that the user is allowed to create, and a report about this contact, API will allow saving of both the contact and the report.

However, if a new contact and a report about the new contact become decoupled, and are part of separate batches, with the report batch being uploaded first, API will not allow the creation of a report about an unknown contact. Saving the report after the contact is created will succeed.

To enable webapp to automatically retry the upload of such reports, we can listen to the `denied` event, which PouchDB emits when receiving a `forbidden` error, and "touch" the forbidden doc to generate a new rev that's pushed at the end of the changes feed.

**Comment by garethbowen** [comment]
Ready for AT in `6103-retry-forbidden-doc-replication`

**Comment by kennsippell** [comment]
Beginning AT

**Comment by kennsippell** [comment]
@dianabarsan I ATed using a script which 1) creates a new contact, 2) creates 105 reports for that contact, 3) edits the contact. Then I sync twice.

On `master`, I am seeing the contact doc and 5 reports sync. 100 reports are missing (expected). 
On `6103-retry-forbidden-doc-replication`, I am seeing the same after 1 sync (expected) with the forbidden messages.
After the second sync, I see the missing 100 reports sync.

Branch is ready to merge -- but rebuilding after conflict resolution (just some indenting).

**Comment by dianabarsan** [comment]
@kennsippell build has passed. Please proceed at your discretion.

**Comment by kennsippell** [comment]
I also tested that a document which should be forbidden attempts to sync upward 4 times. I also tested that mRDT reports can sync even though the contact is not present on the client.
