### ISSUE TITLE
Tab name inconsistencies in Guided Tour vs. Default config

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6104]
**What feature do you want to improve?**
Tab name consistency across: (1) App; (2) Guided Tour table of contents; (3) Guided Tour step titles.

**Describe the improvement you'd like**
Ideally, the name of the tabs in the Guided Tour ToC and steps would match the name of the tabs in the app.

**Additional Info**
- Observed in v3.7.0 using the Default config
- Consider addressing in https://github.com/medic/cht-core/issues/5680

## **Tab name in app = People**
<img width="1195" alt="Screen Shot 2019-11-11 at 3 41 38 PM" src="https://user-images.githubusercontent.com/10096985/68588522-c8e2c180-049a-11ea-9322-d9a52e675c53.png">

## **Tab name in Guided Tour ToC = Contacts**
<img width="1212" alt="Screen Shot 2019-11-11 at 3 41 46 PM" src="https://user-images.githubusercontent.com/10096985/68588573-ef086180-049a-11ea-8c97-bced103fe60c.png">

## **Tab name in Guided Tour = People**
<img width="1193" alt="Screen Shot 2019-11-11 at 3 58 05 PM" src="https://user-images.githubusercontent.com/10096985/68589155-44913e00-049c-11ea-895f-17402a5b29c6.png">

## **Tab name in app = Targets : Tab name in Guided Tour = Analytics**
<img width="1210" alt="Screen Shot 2019-11-11 at 4 28 48 PM" src="https://user-images.githubusercontent.com/10096985/68590979-c7b49300-04a0-11ea-8fcf-fc261a10ddcb.png">

**Comment by garethbowen** [comment]
Ready for AT in `6104-tour-name-consistency`

**Comment by ngaruko** [comment]
-
![image](https://user-images.githubusercontent.com/6979995/68731086-bcde3780-0633-11ea-863c-b02abef41c65.png)

![image](https://user-images.githubusercontent.com/6979995/68731096-c49ddc00-0633-11ea-80fc-fc3b11c27072.png)

![image](https://user-images.githubusercontent.com/6979995/68731107-ce274400-0633-11ea-8431-251e81850a5c.png)

on branch
