### ISSUE TITLE
Call 'db.close' for ephemeral PouchDB objects to avoid memory leaks

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6106]
**Describe the issue**

There is a "_known_" PouchDB memory leak bug documented here: https://github.com/pouchdb/pouchdb/issues/6225
We use scoped PouchDB objects when interacting with user databases and purge databases.
Some operations create large numbers of these database objects that never get garbage collected. 

Easiest way of demonstrating this is to start sentinel with the `--inspect` flag and use chrome's memory profiler (accessed via  'chrome://inspect/#devices') to record and view heap snapshots.

Baseline:
![image](https://user-images.githubusercontent.com/35681649/68605997-233d4b80-04b6-11ea-9aaa-a37748f759c0.png)

After 1000 deletes:
![image](https://user-images.githubusercontent.com/35681649/68606031-35b78500-04b6-11ea-96ca-9f086ca98c9e.png)

After 2000 deletes:
![image](https://user-images.githubusercontent.com/35681649/68606048-3f40ed00-04b6-11ea-8c8a-7efd585fac52.png)

**Describe the improvement you'd like**
To ensure that these objects get GC-ed properly, we need to call the `close` method manually.
Affects both API and Sentinel.

**Comment by dianabarsan** [comment]
This issue also affects Webapp via Telemetry service:

![image](https://user-images.githubusercontent.com/35681649/69569966-77bcec80-0fc7-11ea-94e2-4a71419e63e2.png)

After 100 tab switches between reports and contacts (Search service stores Telemetry):
![image](https://user-images.githubusercontent.com/35681649/69570005-928f6100-0fc7-11ea-9f35-0e10fcea4ab3.png)

**Comment by dianabarsan** [comment]
Ready for AT on `6106-pouch-db-close`

**Comment by ngaruko** [comment]
LGTM.
