### ISSUE TITLE
Batch processing of sentinel changes

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6108]
**Describe the performance issue**
Sentinel watches the couchdb changes feed and adds all changes to a queue for processing. This works fine most of the time but if it gets behind for whatever reason (bulk updates, crashed and restarted, etc) then all those changes are retrieved from couchdb and stored in memory. The objects are reasonably small and they get cleaned up as they're processed so we've gotten away with this for now but if we did run out of memory then Sentinel would get stuck.

**Describe the improvement you'd like**
When we initialise the changes feed we should put a limit on how many results to get. This takes some load off couchdb and limits the number of objects in memory.

The implementation is a little tricky as we should only fetch the next page of the backlog once the previous page has been processed out of the queue. I suspect this means the changes request can no longer be `live`. We can watch for the `queue.drain` event before issuing another changes request.

**Describe alternatives you've considered**
None.

**To Reproduce**
Steps to record the performance metrics:
1. Stop sentinel
2. Make 70,000 changes
3. Start sentinel
4. Track memory usage

**Measurements**
Memory spiked at 120MB and then gradually reduced.

**Environment**
- Instance: localhost
- Browser: N/A
- Client platform: N/A
- App: sentinel
- Version: 3.8.x, master

**Comment by wtekeu** [comment]
Ready for AT: `6108-batch-processing-changes-by-sentinel`

**Comment by dianabarsan** [comment]
Assigning myself for AT.

**Comment by dianabarsan** [comment]
This seems to be working as expected.
I pushed 100.000 changes and waited for Sentinel to process, monitoring resources in the meantime.
Memory consumption alternated between 35MB and 50MB (idle Sentinel uses 28MB).
All changes were processed as expected.

The logging is a bit chatty and incorrect: every time the queue is drained, I see a `DEBUG: transitions: queue drained, we restart the listener`
even though the listener *isn't* restarted. for example: sentinel queue is clear, I push a doc, sentinel processes it,
queue is drained while not exceeding the 100 doc limit.

**Comment by SCdF** [comment]
We changed the log output so that it is more correct (by no longer mentioning the listener).

Merged.
