### ISSUE TITLE
Unable to dismiss Guided Tour if you navigate to a different tab at the end of the tour

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6111]
**Describe the bug**
During a Guided Tour, if you navigate to a different tab at the last step of the tour, the buttons become non responsive and it's not possible to get rid of the tour step.  
- I've been able to replicate this on different tours (ie Contacts, Reports, etc...)
- It only happens if you navigate to a different tab (not just a different screen within the same tab)
- The only way to get rid of the tour step is to go back to the table of contents

**To Reproduce**
![Screen-Recording-2019-11-12-at-9 41 35-AM](https://user-images.githubusercontent.com/10096985/68648865-6fc66c80-0532-11ea-9d1c-33ddb90d671d.gif)

**Expected behavior**
Perhaps dismiss the tour if the user navigates to a different screen or tab.

**Environment**
- Instance: https://openhie.dev.medicmobile.org
- Browser: Chrome
- Client platform: macOS
- App: webapp
- Version: v3.7.0

**Comment by SCdF** [comment]
Ready for AT on `6111-dismiss-tour-on-transition`

**Comment by brad1905** [comment]
Guided Tour window now dismissed when switching to a different tab.
