### ISSUE TITLE
Deleting a report in mobile view doesn't redirect to list

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6118]
**Describe the bug**
When deleting a report in mobile view, post deletion, instead of being redirected to the reports list, you end up on an empty "report-content" page. 

**To Reproduce**
1. Either use a phone or use a desktop browser to simulate a mobile (narrow) view
2. Go to Reports and open a Report
3. Delete the report
4. Notice you're not redirected to the reports list, and you need to click the top "back arrow" to view the reports list again. 

**Expected behavior**
You should be redirected to the reports list. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/68842863-c1582e00-06cf-11ea-8c14-1df3ff87b552.png)

**Environment**
- Instance: local
- Browser: any
- App: webapp
- Version: 3.8.0

**Comment by dianabarsan** [comment]
I've noticed another issue, which might be connected: you can't select the same report consecutively in mobile view.

**To Reproduce**

1. Open the reports tab in mobile view
2. Click on one report. You should be redirected to the report content page. 
3. Click the back "arrow" link in the header. You should be back to the reports list.
4. Click on the same report.
5. Notice that nothing happens. Clicking on a different report will open the new report. 

I'm assuming we have an issue with deselecting reports, whether the cause is a deletion or back navigation and it may a case of two birds with one stone. 

**Video:** 
https://photos.app.goo.gl/7yyG53TB7roKPvx36

**Comment by dianabarsan** [comment]
Ready for AT on `6118-deleting-report-should-redirect-to-list`

For AT, please be aware of an existent race condition (read https://github.com/medic/cht-core/pull/6137#pullrequestreview-326968918) which may or may not be fixed by https://github.com/medic/cht-core/pull/6138. 

Ideally we should make sure that report deletes work as expected after both these PRs are merged.

**Comment by ngaruko** [comment]
LGTM
**before**
![image](https://user-images.githubusercontent.com/6979995/70189789-17614400-1759-11ea-841b-70f8760a1674.png)

**after - web**
![image](https://user-images.githubusercontent.com/6979995/70189896-65764780-1759-11ea-8cc8-b241b23c09ed.png)

**Mobile**
![image](https://user-images.githubusercontent.com/6979995/70190155-0d8c1080-175a-11ea-9790-1cabf619cc85.png)
