### ISSUE TITLE
Add permission control for sentinel access

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6120]
**What feature do you want to improve?**
Currently all users with valid credentials can access the sentinel DB. The only users who really need this is the sentinel user itself, along with couch2pg users (for `-info` docs).

**Describe the improvement you'd like**
Add some sort of permission gating access to only those users who need it. This needs to be configurable as part of user creation (ie roles and permissions) since couch2pg users need to have this permission as well.

**Additional context**
This was briefly prototyped here: https://github.com/medic/cht-core/pull/5662

**Comment by ngaruko** [comment]
LGTM
Tested by adding `sentinel` role to a user in `couchdb`:
```
 "name": "bede-sentinel",
  "type": "user",
  "roles": [
    "sentinel"
  ],
```
Before 
```
curl http://bede-sentinel:Password1234@127.0.0.1:5984/medic-sentinel/000ae7c3-c1d4-5ddd-bd74-524c6d3aeab6-info
{"error":"forbidden","reason":"You are not allowed to access this db."}
```
After
```
 curl http://bede-sentinel:Password1234@127.0.0.1:5984/medic-sentinel/000ae7c3-c1d4-5ddd-bd74-524c6d3aeab6-info
{"_id":"000ae7c3-c1d4-5ddd-bd74-524c6d3aeab6-info","_rev":"2-2341b856ca852e592f10615b05386f4b","type":"info","doc_id":"000ae7c3-c1d4-5ddd-bd74-524c6d3aeab6","initial_replication_date":"2020-06-11T22:04:12.911Z","latest_replication_date":"2020-06-11T22:04:12.911Z","transitions":{}}

```
Back to you @latin-panda to merge and close.
