### ISSUE TITLE
Translations in the App Settings app aren't recognized until you refresh

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6121]
**Describe the bug**
If you create a new translation, it isn't available until you refresh the page. I wasted several minutes trying to figure out why my key wasn't being translated.

**To Reproduce**
![translation_trim](https://user-images.githubusercontent.com/10096985/68854708-b0b6b080-06ed-11ea-9070-b6d90f124b4f.gif)

**Expected behavior**
I would expect my translations to be available when I click the submit button after creating the translation. 

**Environment**
- Instance: https://openhie.dev.medicmobile.org/
- Browser:  Chrome
- Client platform: MacOS
- App: Admin App
- Version: v3.7.0

_This was discovered while looking at https://github.com/medic/cht-core/issues/6119_

**Comment by garethbowen** [comment]
Ready for AT in `6121-app-settings-translation-update`

**Comment by ngaruko** [comment]
Looks good. Translations propagate without the need to refresh. Ready to merge...

**Comment by peter-ochieng** [comment]
Merged to master
