### ISSUE TITLE
Lineage hydrateDocs yields inconsistent results and possibly crashes when hydrating the same lineage

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6122]
**Describe the bug**
Our Lineage library tries to fully hydrate docs without relying on circular references.
When you have a case of "circular lineage" - for example hydrating a person that is primary contact of its place - we should have one "iteration" of hydration for each level.
This works fine in most cases, however, we do rehydrate contacts for every doc we with to hydrate. If any of these docs have the same lineage (for example reports submitted by the same person), our code will re-hydrate the contact object every time, resulting in a deeply nested doc.
This can prove very problematic when you have **many** docs to process at the same time:
I had added 8000 identical reports which were generating outbound tasks. Our outbound task job doesn't batch, so the script ended up trying to hydrate all 8000 docs at once.
Besides taking a LONG time and eating up a lot of memory (as the objects grew more deeply nested and much larger in size), the process failed with a `RangeError: Maximum call stack size exceeded`.
The range error happened in a `JSON.stringify` call, which apparently reported by others to throw this error when trying to stringify a too deeply nested object (https://github.com/Level/levelup/issues/276).
The error is also shown in this integration test: https://github.com/medic/cht-core/blob/lineage_new_integration/shared-libs/lineage/test/integration.js#L798 shown to fail here https://travis-ci.org/medic/cht-core/jobs/611909779#L5991

**To Reproduce**
We currently have (at least) 2 places where unlimited docs are hydrated in bulk: the due_tasks script and the outbound tasks script, both running as Sentinel schedule.
You will need to create docs that either have a "scheduled_task" in "scheduled" state that should be sent now or outbound tasks to be created for every doc.
1. Create some (thousands) of docs that are submitted by the same person, that is primary contact of its place.
2. Start Sentinel.
3. After a (potentially long) while, you should see a `RangeError: Maximum call stack size exceeded` in the Sentinel log.

Alternatively, you can script and run lineage.hydrateDocs yourself to check results similar to the interation test linked above.

**Expected behavior**
No matter how many times a "lineage" branch appears in the docsToHydrate, results should be identical.

**Logs**
```
2019-11-14 09:48:23 ERROR: Error running tasks: RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at deepCopy (/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:3:41)
    at /home/diana/projects/medic/shared-libs/lineage/src/hydration.js:41:34
    at Array.forEach (<anonymous>)
    at fillParentsInDocs (/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:40:13)
    at mergeLineagesIntoDoc (/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:99:5)
    at /home/diana/projects/medic/shared-libs/lineage/src/hydration.js:353:11
    at Array.forEach (<anonymous>)
    at /home/diana/projects/medic/shared-libs/lineage/src/hydration.js:333:22
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  [stack]: 'RangeError: Maximum call stack size exceeded\n    at JSON.stringify ' +
    '(<anonymous>)\n    at deepCopy ' +
    '(/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:3:41)\n    ' +
    'at /home/diana/projects/medic/shared-libs/lineage/src/hydration.js:41:34\n  ' +
    '  at Array.forEach (<anonymous>)\n    at fillParentsInDocs ' +
    '(/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:40:13)\n   ' +
    ' at mergeLineagesIntoDoc ' +
    '(/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:99:5)\n    ' +
    'at /home/diana/projects/medic/shared-libs/lineage/src/hydration.js:353:11\n ' +
    '   at Array.forEach (<anonymous>)\n    at ' +
    '/home/diana/projects/medic/shared-libs/lineage/src/hydration.js:333:22\n    ' +
    'at processTicksAndRejections (internal/process/task_queues.js:89:5)',
  [message]: 'Maximum call stack size exceeded'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/68876297-e6b75d00-070c-11ea-85de-6b670338de97.png)

**Environment**
- Instance: local
- App: Sentinel
- Version: 3.8

**Comment by kennsippell** [comment]
Ready for AT on `6122-fix-lineage-bulk-hydration`

**Comment by ngaruko** [comment]
LGTM
