### ISSUE TITLE
Batch all sentinel operations

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6125]
**Describe the issue**
Currently, Sentinel runs a number of tasks on a schedule. Some of these tasks query the database, searching for specific docs that need to be updated.
The two examples I have are `due_tasks` and `outbound`.
https://github.com/medic/cht-core/blob/master/sentinel/src/schedule/outbound.js#L29
https://github.com/medic/cht-core/blob/master/shared-libs/transitions/src/schedule/due_tasks.js#L41
Both of these (and maybe others too) run queries without limit over the whole database. They run smoothly when Sentinel is up to date and running correctly.
If it fails or stops for whatever reason, and the queue becomes too large, we will be in an irredeemable situation where we would have to hotpatch instances in order to clear the queue.

**Describe the improvement you'd like**
We should not have any unlimited database queries that are prone to have documents queued up.
The selected limit should be a big enough number that it doesn't lengthen process periods with too long pause intervals but also be safe to execute under any circumstance. My initial though would be a limit of 1000, but that's just an idea.

**Describe alternatives you've considered**
We could also consider refactoring these scripts so they operate in batches until their queue is finished, although it wouldn't necessarily be an improvement, as for long queues you could end up blocking Sentinel from executing other scheduled tasks for long periods.

**Comment by garethbowen** [comment]
Related to #6108

**Comment by SCdF** [comment]
Ready for AT in `6125-sentinel-batches`

AT:
 - Large numbers of scheduled items (scheduled tasks, outbound requests etc) shouldn't block other scheduled items

**Comment by newtewt** [comment]
@SCdF  @dianabarsan  I was able to create a bunch of outbound tasks and they triggered fine. I'm not real sure how to generate a ton of schedueld tasks and have them process. Any ideas?

**Comment by dianabarsan** [comment]
I would suggest you create a schedule that would add multiple schedule messages in the current week and an SMS form with a registration that generates these messages,  then just spam the  Admin -> SMS -> Test Message with that form. 

I'll update this post with a sample config shortly.

**Comment by dianabarsan** [comment]
Also, if you create  > 1000 scheduled tasks, it would process only 1000 per run.

**Comment by newtewt** [comment]
This is working now as expected, seeing the batched amounts go out. @dianabarsan  feel free to merge and close.

**Comment by dianabarsan** [comment]
Merged.
