### ISSUE TITLE
Files containing tests should use the .spec.js extension

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6132]
**Describe the issue**
When working in the cht-core repository, code and the code's tests often have the identical filename. However, sometimes they have the same base filename but the tests have a `.spec.js` extension. I find it easier to disambiguate a file based on this spec.js extension.

**Describe the improvement you'd like**
We should just do a one-time change to rename every file containing tests to include the `.spec.js` extension.

**Comment by ngaruko** [comment]
@garethbowen I had a look at this and it looks like we have got quite a number of test files that do not have the `.spec.js` extension. Do you think we should go ahead and rename all of them. Tests in `/config`, `/tests` and `/webapp` look sorted. So the following will be renamed:

- admin/tests/unit/*
- api/tests/integration/*
- api/tests/mocha/*
- sentinel/tests/unit/*

**Comment by garethbowen** [comment]
@ngaruko Yes I think so. It's not critical given our directory structure, but it makes things like specifying specs for mocha cleaner and easier.
