### ISSUE TITLE
Instance monitoring

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6133]
**Is your feature request related to a problem? Please describe.**
Our old monitoring infrastructure which relies on executing scripts on the server using SSH no longer works with the v3 infrastructure. Instead we want to provide a public API which returns a bunch of common metrics. This can be used by external partners as well as our Medic Ops team.

**Describe the solution you'd like**
Discussed in [this proposal](https://docs.google.com/document/d/1LnfQrhBTbVC7zaGjJ2kCSsGJ23-E_Ii-D17Y0Z6WiK4/edit).

1. Expose an API
2. Write a bot to query servers which support the API and store the result
3. Work with the SREs to integrate with the existing grafana instance to allow configuring of dashboards to view the monitoring data

**Describe alternatives you've considered**
None.

**Additional context**
Also solves: https://github.com/medic/cht-core/issues/4138

**Comment by garethbowen** [comment]
Related: https://github.com/medic/cht-core/issues/4482

**Comment by garethbowen** [comment]
Related: https://github.com/medic/medic-bot/issues/8

**Comment by garethbowen** [comment]
Example OpenMetrics (Prometheus) API output for integration testing:

[monitoring-output.txt](https://github.com/medic/cht-core/files/4183617/monitoring-output.txt)

**Comment by garethbowen** [comment]
Ready for AT in `6133-instance-monitoring-api`

These issues are solved in the same branch so AT them at the same time: #6239 #4482 

- follow the API documentation in the branch
- make sure metrics are accurate and useful
- work with @Hareet to ensure the output can be integrated into our monitoring stack

**Comment by ngaruko** [comment]
LGTM, just tested the endpoint `/api/v1/monitoring`.  Is this the output SRE is expecting on your end @Hareet ?
```
{
    "version": {
        "app": "6133-instance-monitoring-api",
        "node": "v13.7.0",
        "couchdb": "2.3.1"
    },
    "couchdb": {
        "medic": {
            "name": "medic",
            "update_sequence": 475,
            "doc_count": 88,
            "doc_del_count": 8,
            "fragmentation": 1.0026379124902745
        },
        "sentinel": {
            "name": "medic-sentinel",
            "update_sequence": 9533,
            "doc_count": 2015,
            "doc_del_count": 90,
            "fragmentation": 1.416540328211897
        },
        "usersmeta": {
            "name": "medic-users-meta",
            "update_sequence": 228,
            "doc_count": 228,
            "doc_del_count": 0,
            "fragmentation": 1.0660895817470177
        },
        "users": {
            "name": "_users",
            "update_sequence": 667,
            "doc_count": 9,
            "doc_del_count": 21,
            "fragmentation": 4.773976253937485
        }
    },
    "date": {
        "current": 1587604057011,
        "uptime": 885.642242446
    },
    "sentinel": {
        "backlog": 0
    },
    "messaging": {
        "outgoing": {
            "state": {
                "due": 1,
                "scheduled": 0,
                "muted": 0
            }
        }
    },
    "outbound_push": {
        "backlog": 0
    },
    "feedback": {
        "count": 225
    },
    "conflict": {
        "count": 0
    }
}
```

**Comment by Hareet** [comment]
Looks Good !

I can navigate JSON and export to Prometheus gauge metrics. The server is collecting them, but it'll take some more configuration before it's easy to add new endpoints, and show up in grafana.

Also found this: https://github.com/gesellix/couchdb-prometheus-exporter
I'll need to expose some couchdb ports on internal k8s services, but I'll plan to play around with this exporter at some point.

**Comment by garethbowen** [comment]
Awesome, thanks @Hareet . Given that you're working with the JSON output does that mean we can drop support for the OpenMetrics format?

**Comment by Hareet** [comment]
@garethbowen Yup, that should be fine.

**Comment by garethbowen** [comment]
Merged!
