### ISSUE TITLE
Request persistent storage

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6134]
**Describe the performance issue**
It's possible now or in the future that the browser will delete users data to free up space.

**Describe the improvement you'd like**
 In browsers that support it we should request that the data is made persistent. If denied then it'll be treated the same as it is now, but if successful then the data will never be deleted unless the user explicitly requests it.

**Describe alternatives you've considered**
- Our version of crosswalk may get around this by allowing 100% disk space usage, but we may not always use crosswalk and this is another layer of protection on top of crosswalk.
- Using native android storage but that is slower than keeping it in the browser and doesn't work in the browser.

**Comment by garethbowen** [comment]
Ready for AT in `6134-request-persistent-storage`.

AT instructions
- In Chrome/Android nothing much may happen.
- In Firefox you will be prompted to allow persistent data.
- Either way you will see a message in the console with "Persistent storage granted: storage will not be cleared except by explicit user action" or "Persistent storage denied: storage may be cleared by the UA under storage pressure.".

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/70028877-a27ff400-160a-11ea-9274-ffd33b3deb40.png)
![image](https://user-images.githubusercontent.com/6979995/70029020-f8549c00-160a-11ea-81e3-eb725c0f309b.png)
