### ISSUE TITLE
Hyperlinks to tasks don't load the task in the url

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6139]
**Describe the bug**
Navigating to a url like http://localhost:5988/#/tasks/74395069-3bc5-44f9-b666-6950488bb720~pregnancy-home-visit~0 in the browser doesn't automatically load the task with the id in the url.

**To Reproduce**
1. Open webapp
1. Navigate to tasks tab
1. Click on a task
1. Confirm the task opens and url should match something like http://localhost:5988/#/tasks/something
1. Refresh the page 

**Expected behavior**
The task should be open in the tasks-content pane
**Environment**
- Instance: dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: master (3.8 development)

**Comment by kennsippell** [comment]
This requires some synchronization between the tasks controller and the tasks-content controller which I'm not totally clear on how to achieve. Possible regression from https://github.com/medic/cht-core/commit/634965e506b0b78e8235d16dcbe5f8b75ec104c1#diff-6cfb3f6437d46a11d602a7f9a39e23bd. Not sure of the pattern to achieve this in angular, so electing to not fix in https://github.com/medic/cht-core/pull/6041

**Comment by ecsalomon** [comment]
Currently, the URL gives the `_id` of the emission. It would be a little more straightforward to go from doc to app or app to doc for debugging if the task's `_id` matched the URL (and the expected behavior @kennsippell outlined above happened).

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by dianabarsan** [comment]
This should be already "fixed" with the Angular upgrade.

**Comment by garethbowen** [comment]
Marking for AT in 3.11.0!

**Comment by newtewt** [comment]
With a the proper user logged in and pasting the url of a task. We now go directly to that task and it is loaded in the page. Refreshing loads the task. Tried with a couple different people and different task types. Pasting goes to the right person/task.
