### ISSUE TITLE
Image attachments are stored on the report twice

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6145]
**Describe the bug**
MRDT reports have the image saved as an attachment as well as the base64 version included in the XML attachment so the image content is duplicated. This doubles the requirements for storing and syncing the doc.

**To Reproduce**
1. Submit a report with a photo
2. Sync it to the server
3. View the doc in fauxton
4. See that the photo is included as an attachment on its own *and* included in the XML attachment.

**Expected behavior**
The photo is only included once.

**Environment**
- Instance: MUSO
- Browser: Chrome
- Client platform: Android
- App: webapp
- Version: 3.7.2

**Additional context**
Initially raised in https://github.com/medic/medic-projects/issues/7075

**Comment by garethbowen** [comment]
This appears to only affect the MRDT widget - regular images are not stored inline.

**Comment by dianabarsan** [comment]
Ready for AT on `6145-duplicate-mrdt-attachments`

**Comment by wtekeu** [comment]
I am AT'ing this fix

**Comment by ngaruko** [comment]
LGTM
**master**
![image](https://user-images.githubusercontent.com/6979995/70191821-e126c300-175e-11ea-9dd2-43fcdf398932.png)
![image](https://user-images.githubusercontent.com/6979995/70206521-b2274600-178c-11ea-9178-85885c489668.png)

**branch**
![image](https://user-images.githubusercontent.com/6979995/70206554-ce2ae780-178c-11ea-8473-03875162c8ef.png)
