### ISSUE TITLE
Data from user's meta database is not being replicated to `medic-user-meta` 

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6147]
**Describe the bug**
Data from `medic-user-XXXX-meta` is not being replicated to `medic-users-meta`. 

**To Reproduce**
1. Log in as an offline user
2. From the hamburger menu, tap on "Report Bug" 
3. Enter text and submit
4. After 30 minutes, with a data connection, local changes should sync to the `medic-user-XXXX-meta` DB in Couch
5. Even after several days, data doesn't get replicated to `medic-users-meta`

**Expected behavior**
There should be a [replication](https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#replications) set up in [app_settings.json](https://github.com/medic/cht-core/blob/master/config/default/app_settings.json) for the default config so that data from individual user meta DBs is automatically replicated to `medic-users-meta`.

**Screenshots**
<img width="1115" alt="Screen Shot 2019-12-02 at 9 20 11 AM" src="https://user-images.githubusercontent.com/10096985/69935420-df05ff80-14e5-11ea-9f38-e13c3cf8ace2.png">

**Environment**
- Instance: openhie.dev.medicmobile.org
- Browser: Chrome
- Client platform: MacOS
- App: Couch
- Version: 3.7.0 ([Default config](https://github.com/medic/cht-core/tree/master/config/default))

cc: https://github.com/medic/cht-core/issues/4898

**Comment by ngaruko** [comment]
The`medic-users-meta` still doesn't seem to update after submitting a feedback - and  `medic-user-xxx- meta` is updated. Am I missing something here @peter-ochieng 

**before**
![image](https://user-images.githubusercontent.com/6979995/79933394-0ca71180-84a4-11ea-8c60-c7449130e20d.png)

**after**
![image](https://user-images.githubusercontent.com/6979995/79941389-46821300-84b8-11ea-9b21-d642aec218c4.png)

**Comment by SCdF** [comment]
@ngaruko those screenshots show the end result, but not what you did, and so are not as helpful as you think they might be.

Can you please post the actual steps you followed to achieve this result? Have you confirmed that you got the new default config? Have you made sure that the syncing happens? Have you waited long enough?

**Comment by ngaruko** [comment]
Thanks @SCdF . I ran the test as in the [description](https://github.com/medic/cht-core/issues/6147#issue-530922368) above , with a 30 minutes wait. Upon a talk with @garethbowen , he checked the changes in the [`app_settings.json` file](https://github.com/medic/cht-core/pull/6359/commits/9fc600011279bdb740557dc77ae82020f2597fad)  and realised we run this replication once overnight. So, I had to change the `cron` fields to run more frequently (`"cron": "* * * * *"`  and upload the settings. Now it works !
![image](https://user-images.githubusercontent.com/6979995/80036009-146ac280-8545-11ea-8ccd-b12c917756fb.png)
Feel free to merge and close this @peter-ochieng .

**Comment by peter-ochieng** [comment]
Merged to `master`
