### ISSUE TITLE
Report content patient hyperlinks point to '/contacts' list

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6149]
**Describe the bug**
Report-content fields patient hyperlinks link to `/contacts` list page instead of the specific contact the report is about.

**To Reproduce**
1. Open a report that has a `patient_id` field that contains a uuid or a `patient_name` field
2. Click on the links from the fields.
3. Notice you're being redirected to `/contacts` instead of the patient document

**Expected behavior**
The link should point to the correct contact.

**Environment**
- Instance: gamma.dev
- App: webapp
- Version: 3.8.0

**Additional context**
There seems to be a connection between the report fields and the outcome.
For example: https://gamma.dev.medicmobile.org/#/reports/2b529cc2-c372-42c6-b45b-9df99204ed7b
Here the `ID` link is correct, while the `Name` link is not.

For example: https://gamma.dev.medicmobile.org/#/reports/83636684-050b-4a76-8007-cdbd9b53ace1
Both the `patient_id` link and the `patient_name` links are incorrect.

**Comment by garethbowen** [comment]
Ready for AT in `6291-case-id`. This PR also fixes #6356 and #6291 so test those at the same time!

**Comment by brad1905** [comment]
Please provide some additional info on how to reproduce this issue, which report fields result in incorrect patient_id and patient_name links? @dianabarsan

**Comment by dianabarsan** [comment]
@brad1905 there are very comprehensive reproduction steps in a duplicate issue: https://github.com/medic/cht-core/issues/6334#issue-589020292

**Comment by brad1905** [comment]
AT passed, ready to merge

**Comment by garethbowen** [comment]
NB: This is waiting on #6291 to pass AT before merge.

**Comment by garethbowen** [comment]
Merged.
