### ISSUE TITLE
Fix race condition when deleting reports

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6161]
We have a race condition when deleting reports, where in mobile view, the user could end up seeing an empty ReportsContent page when deleting a report instead of being redirect to the list.
This is caused by the Changes listener in ReportsContent controller, which calls `ctrl.removeSelectedReport` when receiving a delete, regardless of the `selectMode`. This function will call `globalActions.settingSelected(true);` which in turn will call `setShowContent(true);`, thus ending up displaying the empty ReportsContent page. 
In most situations, the ReportsContent controller is reinitialized by the route change when executing the delete. 

I believe fixing the deletion handling in ReportsContent is the way to go, as it will fix another issue where, as an admin, receiving a deletion of the selected report would not redirect to the list, instead keep you on an empty ReportsContent page. 

We could have it do something like this:
```
if (change.deleted) {
  if (ctrl.selectMode) {
    ctrl.removeSelectedReport(change.id);
  } else {
    ctrl.unsetSelected();
  }
}
```

**To Reproduce**
1. Login as an admin in 2 tabs and switch to mobile view
2. Open the same report in both tabs.
3. In one of the tabs, delete the report. Switch to the other tab.
4. Observe that you are seeing an empty ReportsContent page and the URL still contains the ID of the deleted report.
If you refresh, you should see something like:
```
Error selecting report Error: Document not found: <The report uuid>
```
And then be redirected to the reports list. 

**Expected behavior**
When receiving a delete of the selected report, correct deselection should happen, whether in selectMode or not. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/70252443-1dbbe400-178a-11ea-87f9-ce3ad4982271.png)

**Environment**
- App: webapp
- Version: 3.8

**Comment by wtekeu** [comment]
Ready for AT: `6161-fix-race-condition-deleting-reports`

**Comment by ngaruko** [comment]
LGTM - Can you please merge this @dianabarsan ? Since @wtekeu is no more!

**Comment by dianabarsan** [comment]
Merged into `master`.
