### ISSUE TITLE
Add implicit configs that were lost when `config.default.json` was removed

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6163]
In 3.7 we removed `config.default.json` and replaced it with the `default` config. 
However `default` config doesn't contain all settings that are required for app functionality, like the "sms" section or the "replications" section (already dealt with here: https://github.com/medic/cht-core/issues/6147).

The "sms" section is now required for every SMS project that upgrades from an older version and uses `medic-gateway`. 
https://github.com/medic/cht-core/blob/master/api/src/services/messaging.js#L303

Along with "sms", there might be more missing implicit configs. 

**To Reproduce**
1. Deploy a 3.5 instance with 3.5 version of `standard` config. 
2. Generate some messages to be sent. 
3. POST to `/api/sms` to see that you get some results. 
4. Generate some more messages (calling 'api/sms' will have changed the status on the previous ones)
5. Upgrade to 3.7 (or 3.8). 
6. POST to `api/sms` again.
7. Observe that the response is an empty array. Check the admin message queue to verify that there are indeed pending SMS messages. 

**Expected behavior**
`/api/sms` should return 25 pending sms messages after an upgrade. 

**Environment**
- Instance: 3.5 (or lower) upgraded to 3.7 (or 3.8).
- App: api and/or sentinel

**Comment by garethbowen** [comment]
*Workaround*

update the `settings` doc with:

```json
"sms": {
  "outgoing_service": "medic-gateway"
}
```

**Comment by garethbowen** [comment]
Scheduling for 3.8.0 to at least fix the SMS config so upgrades go smoothly.

**Comment by dianabarsan** [comment]
Ready for AT on `6163-add-implicit-defaults`.

**Comment by dianabarsan** [comment]
Assigning myself for AT.

**Comment by dianabarsan** [comment]
LGTM!

### changes_controller
When `settings` doesn't contain `changes_controller` section and requesting `medic/_changes` as offline user:
#### master:
Browser console:
```
Replication started after 300 seconds since previous attempt
GET http://127.0.0.1:6500/medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=<SEQ>>&limit=100 500 (Internal Server Error)
Error replicating from remote server CustomPouchError {code: 500, error: "Server error", status: 500, name: "Server error", message: "changes rejected", …}
Possibly unhandled rejection: {"code":500,"error":"Server error","status":500,"name":"Server error","message":"changes rejected"}
Replication failed after 0.082 seconds
```
Api:
```
GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=<SEQ>&limit=100 HTTP/1.1
ERROR: Server error: TypeError: Cannot read property 'reiterate_changes' of undefined
    at initFeed (/home/diana/projects/medic-master/api/src/controllers/changes.js:271:56)
    at processRequest (/home/diana/projects/medic-master/api/src/controllers/changes.js:311:10)
    at /home/diana/projects/medic-master/api/src/controllers/changes.js:431:17
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  [message]: "Cannot read property 'reiterate_changes' of undefined"
}
RES 04d23618-8b76-4356-a8fd-d7554df98f88 ::ffff:127.0.0.1 - GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=<SEQ>>&limit=100 HTTP/1.1 500 35 13.600 ms
```

#### proposed:
Browser console:
```
Replication started after 126 seconds since previous attempt
Replication succeeded after 1.387 seconds
```

Api:
```
REQ 9dd1ad3f-03ae-4663-b6b8-6f46a366d976 ::ffff:127.0.0.1 - GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=<SEQ>>&limit=100 HTTP/1.1
RES 9dd1ad3f-03ae-4663-b6b8-6f46a366d976 ::ffff:127.0.0.1 - GET /medic/_changes?timeout=600000&style=all_docs&heartbeat=10000&since=<SEQ>&limit=100 HTTP/1.1 200 - 101.771 ms
```

### sms

When `settings` doesn't contain `sms` section (while there are "pending" sms messages) and POST-ing to `/api/sms`
#### master:
```
{
  "messages": []
}
```

#### proposed:
```
{
  "messages": [
    {
      "content": "dsadada",
      "to": "+40788525252",
      "id": "0cfddeec-3de6-4f57-9bb1-478ae9f15b8c"
    },
    {
      "content": "11111",
      "to": "+40788525252",
      "id": "0e9cf537-a0ee-4333-8ed3-cff73672f847"
    },
    {
      "content": "22222",
      "to": "+40788525252",
      "id": "89fa39f4-99da-4390-8d32-8caee1655112"
    },
    {
      "content": "3333",
      "to": "+40788525252",
      "id": "e093bc4c-2192-42f4-9712-b90a2e0493e8"
    }
  ]
}
```

Looking at the the `config.default.json`, these are the settings that required implicits as a result of recent updates (last 2 years).
