### ISSUE TITLE
Db-doc access fails when accessing a report about a deleted contact

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6164]
In an attempt to make db-doc access quicker for offline users, I implemented a reverse authorization mechanism that created a "scoped" version of the authorization context, relevant just to the requested doc. However, I completely overlooked tombstones. 

As such, when requesting a report that is about a deleted contact, an offline user will receive a faulty 403 error. 

**To Reproduce**
1. Login as an offline user. 
2. Create a report about an existent contact.
3. Delete the contact and sync. 
4. Wipe data from the device / browser and login fresh.
5. Notice that you get a 403 error when trying to get the report's attachment. 

**Expected behavior**
Replication should complete without error. All docs that are received via the _changes feed should be valid for download. 

**Environment**
- App: api
- Version: 3.8

**Additional context**
Introduced during the development of 3.8. Related issue: https://github.com/medic/cht-core/issues/5550

**Comment by dianabarsan** [comment]
Ready for AT on `6164-handle-db-doc-deletions`

**Comment by ngaruko** [comment]
LGTM
