### ISSUE TITLE
Installation instructions lead to errors

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6166]
The [install instructions](https://github.com/medic/cht-core/blob/2a238abb32624b9111bec9a81f57f54cddc64d54/INSTALL.md) make for easy installation of the CHT Core Framework, but it is possible to be tripped up by the following:
- Directory for `docker-compose` not specified
- Password in test data command doesn't match the default password
- Need to use (undocumented) flag for self-signed-certificate (`--accept-self-signed-certs`), otherwise errors with `ERROR RequestError: Error: self signed certificate`

As part of AT all instructions should be followed to see if any other updates are needed.

**Comment by SCdF** [comment]
Merged, no AT required
