### ISSUE TITLE
Sentinel doesn't restart its follow feed on error 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6169]
**Describe the bug**
In Sentinel, if the changes feed that we follow to process docs (https://github.com/medic/cht-core/blob/master/sentinel/src/lib/feed.js#L10) throws an error, it is never restarted. Not even when new (valid) settings are pushed. 

This puts Sentinel into a blocked state where only a restart OR (hacky) pushing a faulty transition config and then pushing a correct one (which will cause a `detach` and `attach` https://github.com/medic/cht-core/blob/master/sentinel/src/transitions.js#L16)

**To Reproduce**
1. Deploy 3.8 (or 3.7). Ensure that you have `generate_patient_id_on_people` enabled. 
2. Stop Sentinel. Edit the sentinel-meta-data document to use an incorrect seq (for example a number):
http://127.0.0.1:5984/medic-sentinel/_local/sentinel-meta-data
```
{
  "_id": "_local/sentinel-meta-data",
  "_rev": "0-2371",
  "processed_seq": 2500
}
```
3. Start Sentinel
4. Notice a single error in the console:
```
ERROR: transitions: error from changes feed: {
  error: 'bad_request',
  reason: "Malformed sequence supplied in 'since' parameter.",
  status: 400,
  name: 'bad_request',
  message: "Malformed sequence supplied in 'since' parameter."
} 
```
5. As an admin, create a new person in the webapp. Wait and observe that it does not receive a `patient_id`. 
6. Checking the Sentinel console, it does not report processing the person doc. 

**N.B.** 
In this example, even restarting Sentinel won't make it function correctly. 
If it attempted to restart the feed every time it received an error, you would see the above error message logged over and over, not just once.

**Environment**
- App: Sentinel
- Version: 3.7

**Additional context**
Discovered when an upgrade from 2.x -> 3.x went wrong: After replicating docs from Couch 1.x to Couch 2.x, the `local/_sentinel_meta_data` was not created to have it's `processed_seq` equal to the `update_seq` of the new db (so docs would not be processed twice). 
Upon starting, Sentinel started feed, with the `since` parameter coming from the legacy metadata document (https://github.com/medic/cht-core/blob/master/sentinel/src/lib/metadata.js#L5) that existed in `medic` database, using a the old Couch 1.x seq format (numbers). 
Because API was doing all the heavy lifting with syncronous transitions, it took days to discover that Sentinel was in fact blocked. 
Restarting Sentinel at this point, would make it start processing docs since 0  (because the legacy metadata doc is deleted immediately after being read: https://github.com/medic/cht-core/blob/master/sentinel/src/lib/metadata.js#L7)

**Discussion** 
In the above scenario, what would have been the correct behavior?

Do we want to avoid Sentinel starting from 0 when upgrading from 2.x and missing the step of creating the metadata doc with the DB'a current `update_seq`?

If Sentinel had logged the error more frequently or more obviously, it would have probably prompted people earlier in the process.

**Comment by garethbowen** [comment]
I'm comfortable restarting from 0 in this case as it's the only way to ensure no changes are skipped. Our upgrade steps say to create the metadata doc so it shouldn't happen, and after everyone's on couch 2 it won't happen again. If it's taking too long to process it can be stopped and manually bumped.

**Comment by dianabarsan** [comment]
Ready for AT on `6169-retry-changes-listener`.

**Comment by ngaruko** [comment]
LGTM
Should we backport this to 3.7 @dianabarsan ?

**Comment by dianabarsan** [comment]
We are not backporting to 3.7, @ngaruko . If you're done with AT, we can close and merge into `master`.

**Comment by ngaruko** [comment]
LGTM on local install.
