### ISSUE TITLE
Having a doc with a non-numeric `reported_date` breaks everything

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6170]
We use the default CouchDB reducer `_stats` for two views, `medic/reports_by_form_and_parent` and `medic-client/contacts_by_last_visited`. 
See the documentation for `_stats` here: https://docs.couchdb.org/en/2.3.1/ddocs/ddocs.html#_stats
It requires that we **only emit numeric or numeric array values** and will throw an error while indexing or querying views if any doc does not comply.
In the view map functions, we do not insure that the emitted value is a number. 

**To Reproduce**
1. Deploy 3.8 or 3.7.
2. Login as an admin, make sure you have at least one report in the instance. 
3. Open a report in fauxton - this report has to emit `medic/reports_by_form_and_parent` (https://github.com/medic/cht-core/blob/master/ddocs/medic/views/reports_by_form_and_parent/map.js), so make sure it has all the required fields.
4. Edit the report, setting the `reported_date` field to a string. The content doesn't matter, just that it's a non-empty string. Save! 
5. As an admin, refresh the reports list.
6. Error fetching reports.

**Logs**
The `http://localhost:5988/medic/_design/medic/_view/doc_summaries_by_id` request throws a 500 error:
```
{"error":"invalid_value","reason":"The _stats function requires that map values be numbers or arrays of numbers, not '<<\"oh joy\">>'","ref":4089041121}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/70371977-422ad400-18e2-11ea-8e79-2923af87153d.png)

**Environment**
- App: all
- Version: any version that uses `_stats` reducer for at least one view. 

**Additional context**
We should make sure that we emit numbers when we pass values to a `_stats` reducer. 
As a workaround, we can search for documents that have faulty fields and edit them to unblock instances.

**Comment by garethbowen** [comment]
Not a high priority as this has existed for a while and relies on invalid data being submitted.

**Comment by garethbowen** [comment]
@dianabarsan convinced me this is worth doing in 3.8.0...

**Comment by dianabarsan** [comment]
Ready for AT on `6170-typesafe-stats`

For AT, make sure you edit a report to have a faulty `reported_date` and a home_visit to have a faulty `reported_date` and a faulty `fields.visited_date` (a random string instead of a string representing a valid date)

**Comment by wtekeu** [comment]
At'ing this issue

**Comment by wtekeu** [comment]
LGTM.

`master`
<img width="431" alt="Screen Shot 2019-12-09 at 2 45 29 PM" src="https://user-images.githubusercontent.com/1445164/70467184-b99f6580-1a92-11ea-9e85-c52722d4faa7.png">
<img width="706" alt="Screen Shot 2019-12-09 at 2 45 46 PM" src="https://user-images.githubusercontent.com/1445164/70467193-c02ddd00-1a92-11ea-84e6-b27a0fdd4115.png">

`6170-typesafe-stats`
<img width="479" alt="Screen Shot 2019-12-09 at 2 44 49 PM" src="https://user-images.githubusercontent.com/1445164/70467223-cd4acc00-1a92-11ea-9d6e-56d363dd87bd.png">
