### ISSUE TITLE
Map tile fetching blocked by CSP for geopoint questions

### ISSUE THREAD

**Issue by derickl** [medic/cht-core#6183]
By default, geopoint questions are rendered showing a map.
<img width="772" alt="Screenshot 2019-12-13 at 10 47 35" src="https://user-images.githubusercontent.com/83162/70803278-c12d7a00-1dc4-11ea-8486-2169e5b7e459.png">

Unfortunately the map area is empty since tile fetching is blocked by CSP as illustrated by the error logged below:

```
Refused to load the image 'https://a.tile.openstreetmap.org/1/0/0.png' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".
```

Users are this unable to select points on a map for locations of interest.

I'm testing this on 3.7.x, on OSX 10.15.2, Chrome 79

**Comment by dianabarsan** [comment]
Ready for AT on `6183-fix-csp-for-geopoint-widget`

**Comment by ngaruko** [comment]
LGTM - tested along #6184 
Ready to merge @garethbowen
