### ISSUE TITLE
Unread reports & messages menu bubbles no longer appearing

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6185]
**Describe the bug**
The messages and reports unread bubbles no longer showing up. 

![image](https://user-images.githubusercontent.com/35681649/70918743-3d73c780-2028-11ea-8532-d6df47bcd38d.png)

**To Reproduce**
Steps to reproduce the behavior - as online user:
1. Login as an online user that has at least one unread report.
2. After app is loaded, check the app header and observe that we're missing the unread count bubbles.
Optional steps: 
3. Keep the tab open for 5+ minutes, with an open console
4. Observe error:
```
TypeError: a is not a function
    at m (inbox.js?_sw-precache=98e740f6597031936f0d30c38add790a:3)
    at c.$digest (inbox.js?_sw-precache=98e740f6597031936f0d30c38add790a:3)
    at c.$apply (inbox.js?_sw-precache=98e740f6597031936f0d30c38add790a:3)
    at inbox.js?_sw-precache=98e740f6597031936f0d30c38add790a:3 undefined
```

As offline user, there is no error (because a specific code path is not executed), but you still do not see the unread bubble.

**Expected behavior**
For offline users, the unread bubble should be updated in real time. For online users, the unread bubble should be updated on app load and then every 5 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/70918665-1c12db80-2028-11ea-8058-671b181f36aa.png)

**Environment**
- Instance: gamma.deb
- App: webapp
- Version: 3.8

**Comment by garethbowen** [comment]
Reviewed and ATed in one go.
