### ISSUE TITLE
Architecture v3: Medic-API & Medic-Sentinel containers

### ISSUE THREAD

**Issue by Hareet** [medic/cht-core#6190]
**What feature do you want to improve?**
Running Medic-API & Medic-Sentinel in individual containers to satisfy [implementation of architecture v3](https://github.com/medic/cht-core/issues/6189).

**Describe the improvement you'd like**
Medic-API/Sentinel should run in an isolated container with the following guidelines:
- Generate user docs based on logins generated from CouchDB init scripts for Production environments
- Ensure CouchDB is secure
- Entrypoint scripts reference environment variables (COUCH_URL, etc) after logic to determine self-host or k8s
- Docker image should be built & published via CI
- On container reboot, medic-api should not over-write any installations/passwords. 
- Medic-API should reference image tag inside container, and ensure the correct image has had CouchDB preparation(view warming)
- Uninterrupted Development workflow

**Comment by garethbowen** [comment]
Done in 4.0.0. If anything is remaining let's create separate specific and up to date issues for those bits.
