### ISSUE TITLE
Broken link in Sentinel error message

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6192]
With https://github.com/medic/cht-core/pull/6035 the following helpful link became stale:
![image](https://user-images.githubusercontent.com/789512/71905597-79391300-3136-11ea-8589-d399425824ed.png)

Should now be https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#enabling-a-secure-couchdb

**Comment by ngaruko** [comment]
LGTM
