### ISSUE TITLE
Bad date notice shown running docker locally

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6194]
**Describe the bug**
The bad date setting notice shows up even when the date is correct on my device.

**To Reproduce**
1. Setup the docker image using the [easy deployment instructions](https://github.com/medic/cht-core/blob/master/INSTALL.md) (on a computer running Windows 10 in Eastern Timezone)
2. Load the app
3. See the `Bad date setting` modal

**Expected behavior**
The bad date notice should only appear if the date of the browser is significantly different from that of the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/71910903-c4f0ba00-3140-11ea-9713-8d383904750b.png)

**Environment**
- Instance: localhost
- Browser: Chrome 79
- Client platform: Windows
- App: webapp
- Version: 3.7

**Additional context**
Occurs on a laptop on UTC-5. Setting the timezone to various other timezones, including UTC, and reloading the app in the browser does not resolve the problem.

**Comment by garethbowen** [comment]
What date/time does the server think it is?

**Comment by abbyad** [comment]
🤦‍♂ 13 days ago.

I would have thought that the docker container's clock would match the host's, but I suppose not.

**Comment by abbyad** [comment]
Whenever I try to set the date, even with sudo, I get `Operation not permitted`.

**Comment by garethbowen** [comment]
@abbyad Can we close this as Won't Fix? I think it's an issue with Docker or your machine, not the CHT. The "bad date" warning in this case is absolutely correct!

**Comment by abbyad** [comment]
Ya, closing as I can't reproduce anymore anyways.

**Comment by abbyad** [comment]
Experienced this again recently, and looks related to [this Docker issue](https://github.com/docker/for-win/issues/4526). This has been released, so hopefully won't happen again, but if it does the steps from [an earlier incarnation of the issue](https://github.com/docker/for-win/issues/72#issuecomment-245939850) immediately and accurately resync'ed the date and time.

![image](https://user-images.githubusercontent.com/789512/78283371-ae61c100-74eb-11ea-9cda-04553e99d10c.png)

**Comment by abbyad** [comment]
Time drift is still happening and the previous fix isn't working now that it using WSL2 instead of Hyper-V. It is reproducible, and seems to be a [known problem](https://github.com/microsoft/WSL/issues/5324). Unfortunately the suggested fix of running `sudo hwclock -s` and it's derivatives don't work for me: 
```
sh-4.3# sudo hwclock -s --debug
hwclock from util-linux 2.27.1
hwclock: cannot open /dev/rtc: No such file or directory
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.
```

The time does resync if I shutdown Docker containers and wsl (`wsl --shutdown`), and restart the containers. I don't think we need to do anything for this now, but wanted to update this issue for posterity -- for myself and anyone else that may stumble across this issue.
