### ISSUE TITLE
Clicking on contact name in report does not open contact details

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6206]
**To Reproduce**
1. Go to 'report.'
2. Click on 'any report'
3. Click name associated with report
4. App goes to main contact page/screen

**Expected behavior**
App should open the actual contact

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Firefox, Chrome, android
- Client platform:  MacOS
- App: webapp, mobile app
- Version: 3.8

**Comment by dianabarsan** [comment]
@ngaruko I believe this is a duplicate of https://github.com/medic/cht-core/issues/6149 (which is scheduled in 3.9). Could you please check if it's indeed the case?

**Comment by ngaruko** [comment]
Definitely, thanks @dianabarsan

**Comment by dianabarsan** [comment]
Removed from 3.8, so it won't show up in the release notes as a bug we fixed.
