### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6208]
**Describe the bug**
Some translations are missing, like `state.duplicate `

**See** : https://github.com/medic/cht-core/blob/master/ddocs/medic/_attachments/translations/messages-en.properties#L1063-L1074

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/72690865-19eef000-3b85-11ea-8294-6308be25e588.png)

**Environment**
- Instance:  gamma.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform:  MacOS
- App: webapp
- Version: 3.8

**Additional context**
There might be other missing translations.

**Comment by abbyad** [comment]
Thanks for raising this. To make sure we don't miss any, please list any other translation key that you encounter in the app.

**Comment by SCdF** [comment]
@peter-ochieng can you take a look at this please, I'm super swamped this week

**Comment by dianabarsan** [comment]
@ngaruko This is a branch that adds the `state.duplicate` translation: `6208-missing-translations`.

**Comment by ngaruko** [comment]
LGTM. Not sure if there are other missing translations we haven't come across yet. Will raise issues as they show up, unless there is a way to find them all and fix them at once @garethbowen ?

**Comment by SCdF** [comment]
There isn't really. Some code search fu will find some but not others. The
only true test is real time: if there is a warning logged in the console
that means it's missing.

**Comment by ngaruko** [comment]
Just double checking @peter-ochieng ... have we backported this to 3.8? Reopening temporarily to make sure I do not miss this. Feel free to close it again if yes.

**Comment by peter-ochieng** [comment]
@ngaruko I've back ported to 3.8.x.
