### ISSUE TITLE
Ability to make target widgets invisible

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6211]
**What feature do you want to improve?**
As part of #6002, target documents will be used to drive our workflow for integrating with DHIS2. For some partners, this will result in many new targets being written and added to the UI (eg. `MoH Kenya 515` will result in `75` new targets). 

Many of targets we may never need users to review manually (eg. popullation statistics) and so they should calculate and aggregate in the `target` document, but not display in the UI. Long-term it would be nice to organize the page under headings or sections, but our feedback from projects is that this many new indicators will be too cluttered with the current UI and many will need to be hidden.

**Describe the improvement you'd like**
Add a `visible` attribute onto the target configuration. When false, the target will calculate and aggregate into target documents, but will not display in the UI. Defaults to true.

**Comment by dianabarsan** [comment]
Ready for AT on `6211-invisible-targets`. 
To be able to create targets with the `visible` attribute set to false, please checkout this branch of medic-conf: [`6211-invisible-targets`](https://github.com/medic/medic-conf/tree/6211-invisible-targets). (Both PRs need to be merged when AT is concluded).

**Comment by garethbowen** [comment]
I've merged the medic-conf part of this so it can be included in its release. It's backwards compatible so it won't matter if the cht-core part of this issue gets bumped.

**Comment by SCdF** [comment]
Taking for AT

**Comment by SCdF** [comment]
@dianabarsan it is intentional there is no documentation updated for this change? I.e., are we hiding it (no pun intended) for now?

**Comment by SCdF** [comment]
@dianabarsan this passes my limited ATing skill, with the notable exception that there is no documentation (unless you come back and tell me that it's intentional). Back to you.

**Comment by dianabarsan** [comment]
@SCdF thanks for the review and pointing out I forgot about documentation!

**Comment by SCdF** [comment]
@dianabarsan documentation looks good, AT looks good, merge away!
