### ISSUE TITLE
Console errors on upgrade page

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6212]
**Describe the bug**
There is an error showing in the console during the upgrade. Apparently benign but worth looking into IMO
**To Reproduce**
1. Go to '/admin'
2. Click on 'Upgrades'
3. check the dev console
4. See error in console

**Expected behavior**
Clean console, no errors
**Logs**
If applicable, include the server or browser logs.
``` 
TypeError: Cannot read property 'major' of undefined
    at Object.compare (version.js:42)
    at Scope.$scope.potentiallyIncompatible (upgrade.js:127)
    at fn (eval at compile (angular.js:16418), <anonymous>:4:265)
    at Scope.$digest (angular.js:19132)
    at angular.js:19432
    at TaskTracker.completeTask (angular.js:21231)
    at angular.js:6812
```
**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/72857977-25c4e880-3d24-11ea-8fe4-68955f2efb0b.png)

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome
- Client platform:  MacOS
- App: webapp, admin
- Version:3.8

**Additional context**
Error in Firefox
![image](https://user-images.githubusercontent.com/6979995/72858380-7be65b80-3d25-11ea-9b89-d09b85ebc6d1.png)

**Comment by garethbowen** [comment]
Ready for AT in `6212-upgrade-page-errors`

**Comment by ngaruko** [comment]
LGTM
