### ISSUE TITLE
The `can_edit` permission doesn't stop you from editing documents (only uploading those edits)

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6215]
The `can_edit` permission is used in two places in our code base: whether or not someone has permission on arbitrary writes (decided in api's routing), and whether or not upward sync should be enabled (in client side db-sync code).

This creates a confusing situation if `can_edit` is disabled for offline users. The user is still completely capable of creating new reports, editing existing reports, etc. However, *upwards replication simply never occurs*, with no indication that anything is wrong.

A `can_edit` permission check should wrap all write attempts (e.g. creating forms, editing forms etc) so disable the ability to perform those actions, and present a proper "read only" view.
 
Or, if that is too hard, we should not allow offline users to be configured without this permission.

Or, if _that_ is too hard, we should warn in the console on boot (ie in the db sync code that checks this permission) very loadly that this user is basically misconfigured, and it's going to look like they are successfully making changes when they are not.

**Comment by SCdF** [comment]
It's also worth mentioning that there may be a perception that this is determining **just** edit capability (ie you can create but not edit). We would want to make sure our documentation is clear that edit means editing *and* creating.

**Comment by dianabarsan** [comment]
I don't think there is a perception of `create` vs `edit` in this case. 
We do a similar check in `api` (here: https://github.com/medic/cht-core/blob/master/api/src/routing.js#L662) and filter _every_ put/post/delete through this. 
Historically, this was part of the auditing process: https://github.com/medic/cht-core/blob/2.18.x/api/audit-proxy.js#L37

**Comment by latin-panda** [comment]
Similarly with the verification feature in Reports, there are `can_verify_reports ` and `can_edit_verification`. 

If `can_edit` is false but `can_verify_reports` and `can_edit_verification` are true, the online user can still verify and edit a verification of a report. 

I brought up the topic in today's stand up, we think for simplicity `can_edit` enable `create`, `update` and `delete` actions of any document in `medic` data base, when user is online or offline. 
That means the user can't verify or delete reports. The `can_verify_reports `, `can_edit_verification`, `can_delete_reports` and `can_bulk_delete_reports` won't be effective, if `can_edit` is **false**.

I'm going to fix the verify reports and the bulk delete reports to behave like this. 
cc: @garethbowen

**Comment by garethbowen** [comment]
My understanding of the intention of `can_edit` is that you can not make any changes to the main couchdb database, which includes any deletions. So I think we should modify API so that `can_edit` overrides `can_bulk_delete_reports` and update the UI accordingly. This _may_ break some configurations but I doubt anyone allowed that on purpose.

And using the same logic, `can_edit` would override the verify permissions.

So I agree with the standup conclusion - `can_edit` makes the db immutable.

**Comment by latin-panda** [comment]
This is ready for AT. Please check the PR description for details.
[CHT Core PR](https://github.com/medic/cht-core/pull/7733)
[CHT Docs PR](https://github.com/medic/cht-docs/pull/752)

**Comment by latin-panda** [comment]
fyi @ngaruko & @tatilepizs :) 
Thanks!

**Comment by ngaruko** [comment]
1. Disable can edit > 
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/6979995/189008818-e1286ac9-87f8-49a3-be75-a30346390332.png">

2.  Check buttons on report 
**_Before:_** <img width="1113" alt="image" src="https://user-images.githubusercontent.com/6979995/189007721-8a2d9ec4-b977-48e5-b460-cce43b6d87fb.png">
**_After:_** 
![image](https://user-images.githubusercontent.com/6979995/189008705-9e1d510a-9a55-47d9-bafa-cd66ce50090d.png)
I wonder if it would be better to hide the grey banners if there is no action to display @latin-panda ? Alternatively, we could leave the icon showing and flash an error message when the user attempts to do an action for which they are have no permission - seems to be a little more transparent, just in case the user or configurer made an error and ticket off a permission and the user will have a proper visual of what went wrong?

**Comment by latin-panda** [comment]
Thanks @ngaruko, it's quite hard to hide the grey banners and we decided to leave it like that ([see Gareth comment](https://github.com/medic/cht-core/pull/7733#discussion_r954358515)) This action buttons will be eventually replaced/refactored by the FAB work as part of the evolution UI/UX that CT is working.

**Comment by latin-panda** [comment]
Merged.
