### ISSUE TITLE
Number of tasks for person not shown on profile

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6220]
**Describe the bug**
There is a spot for the number of tasks per person, yet it doesn't show a number.

**To Reproduce**
1. Go to a patient's profile
2. Complete an pregnancy registration that would result in a Task creation
3. Go to the patient's household
4. See that there is a task for the person, yet on the person's row the task number is missing 

**Expected behavior**
The number of tasks should be shown for each person if greater than 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/73213410-2394cc80-411e-11ea-9cee-0c0c87b1ba0d.png)

**Environment**
- Instance: localhost running default config
- Browser: Chrome
- Client platform: Windows
- App: webapp
- Version: 3.7.0

**Comment by dianabarsan** [comment]
We've fixed this in `3.5.0` (https://github.com/medic/cht-core/issues/5639) and it seems we've regressed again. 
Should this call for a release test?

**Comment by garethbowen** [comment]
For UAT: When testing this also write up a release test issue so this gets manually tested each release so we don't regress again.

**Comment by dianabarsan** [comment]
Ready for AT on `6220-show-task-count`

**Comment by ngaruko** [comment]
LGTM @garethbowen 
Added a note on the release testing project to verify this as part of RT.

![image](https://user-images.githubusercontent.com/6979995/79705100-84403980-8308-11ea-86ef-867e0eb279f1.png)
