### ISSUE TITLE
Outbound calls code to delete broken tasks unneccessarily

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6223]
```
[2020-01-27 01:12:00] 2020-01-27 01:12:00 WARN: Found 0 tasks that could not have their associated records loaded:
[2020-01-27 01:12:00] 2020-01-27 01:12:00 WARN: Deleting invalid tasks
[2020-01-27 01:12:00] 2020-01-27 01:12:00 INFO: checking schedule again in 2 minutes
```

It shouldn't proceed with this logic if there are zero items that need fixing, as the WARN implies there is importance to what is going on.

**Comment by SCdF** [comment]
AT in `6223_skip-unneeded-code`

**Comment by SCdF** [comment]
This is part of #6306 as it was covered in the refactoring I did there. When it's ready to be AT'd that will be against `6306-immediate-outbound`

**Comment by garethbowen** [comment]
Ready for AT in `6306-immediate-outbound` - do at the same time as #6306

**Comment by brad1905** [comment]
This issue has passed AT. Log shows that call to Delete invalid tasks does not occur after change. 
Note related issue #6306 has not yet been successfully resolved. @SCdF. 

<img width="562" alt="6223-after" src="https://user-images.githubusercontent.com/62311678/81034813-273a9c80-8e4d-11ea-84b3-c42efcccd6a5.png">
<img width="568" alt="6223-before" src="https://user-images.githubusercontent.com/62311678/81034816-2a358d00-8e4d-11ea-859b-1e98f731ecdd.png">

**Comment by newtewt** [comment]
@brad1905 @SCdF  does this need re-tested after changes to #6306 or can we close? The branch this was in has been merged.

**Comment by SCdF** [comment]
@newtewt it's probably fine, but if you've got the time it might be worth retesting since this code did move around a bit.

**Comment by newtewt** [comment]
@SCdF  I did a quick check on this. There is no warning in the log about deleting tasks when none exists and I saw an invalid task get deleted when there was one.

**Comment by SCdF** [comment]
Great, thanks @newtewt !
