### ISSUE TITLE
Misaligned "Title" columns in admin console > SMS > SMS Forms

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6231]
**Describe the bug**
![Screenshot from 2020-02-02 22-35-29](https://user-images.githubusercontent.com/9014751/73631100-de383980-460c-11ea-818c-b5555d3abcd3.png)

**To Reproduce**
https://gamma.dev.medicmobile.org/admin/#/sms/forms
`3.8.0.beta-5`

1. Admin console
1. SMS tab
1. SMS Forms tab
1. Look at the title column and it's alignment

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome
- App: admin
- Version: 3.8.0

**Comment by garethbowen** [comment]
Ready for AT in `6231-misaligned-heading`

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/74389584-834fdf00-4e63-11ea-987f-fcec3fa0319a.png)
