### ISSUE TITLE
Adjust UHC colours to be consistent with the medic color palette

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6234]
**What feature do you want to improve?**
The colors for UHC success (teal) and warning (yellow) do not match the Medic color palette.

**Describe the improvement you'd like**
Instead of:

```css
@visits-goal-incomplete: #C38813;
@visits-goal-done: #538E8D;
```

Use:

```css
@visits-goal-incomplete: @yellow-dark;
@visits-goal-done: @teal-dark;
```

**Describe alternatives you've considered**
I tried the non-dark options but they were difficult to read as they were too light.

**Additional context**

![Screenshot from 2020-02-05 16-44-22](https://user-images.githubusercontent.com/2064938/73809053-cc39df00-4836-11ea-8e59-bbf7dcc65a1e.png)

**Comment by garethbowen** [comment]
Ready for UAT in `6234-uhc-colour-palette`

**Comment by newtewt** [comment]
@garethbowen  this is good to go. I see the updated colors after applying the branch.

**Comment by garethbowen** [comment]
Merged.
