### ISSUE TITLE
The number of Feedback docs is incorrect

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6239]
**Describe the bug**
We show a count of the total number of feedback docs but it includes docs of other types.

**To Reproduce**
1. Make sure your medic-users-meta database has some feedback docs and some telemetry docs - any system that has been running over the end of the month will have a telemetry doc and feedback docs can be created through the UI, then forcing replication then waiting for them to appear in the meta db.
2. Go to: Admin > Import & Export data > User Feedback
3. View the number of feedback docs shown where it says `Showing 20 of <total>`
4. Compare this to the actual number of docs in the medic-users-meta db. The shown number will match the total number of docs, _including_ telemetry docs.

**Expected behavior**
The shown number should only include the feedback docs.

**Logs**
None

**Screenshots**
![Screenshot from 2020-02-10 14-35-28](https://user-images.githubusercontent.com/2064938/74115265-4db4b700-4c13-11ea-8c05-970050424e77.png)

**Environment**
- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: admin
- Version: 3.8.0

**Comment by garethbowen** [comment]
AT this at the same time as #6133

**Comment by ngaruko** [comment]
Looks different still
![image](https://user-images.githubusercontent.com/6979995/77731263-73810880-7067-11ea-982b-e0fc193d35ce.png)

![image](https://user-images.githubusercontent.com/6979995/77731240-69f7a080-7067-11ea-91c1-30a4504289f8.png)

**Comment by ngaruko** [comment]
LGTM
**_On master:_**
![image](https://user-images.githubusercontent.com/6979995/78522886-f9990e00-7822-11ea-8d1a-ac51e8d084c7.png)

**_On branch:_**
![image](https://user-images.githubusercontent.com/6979995/78523102-cb67fe00-7823-11ea-93fc-61f67c946dda.png)

Back to you @garethbowen for a merge.

**Comment by garethbowen** [comment]
Merged.
