### ISSUE TITLE
CouchDB admins can't login in the app

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6249]
**Describe the bug**
CouchDB admins - created by the CoudhDB Config api (https://docs.couchdb.org/en/stable/intro/security.html#creating-a-new-admin-user) can't login in the app.

**To Reproduce**
1. Create a new CouchDB admin using the configuration API: https://docs.couchdb.org/en/stable/intro/security.html#creating-a-new-admin-user
2. Try to login with the new admin in the medic app.
3. You get an `Incorrect user name or password.` error even though you used the correct credentials.
Logging into fauxton with the same credentials works (you would actually be already logged into fauxton with your user)

**Expected behavior**
An admin user should be able to log in the app.
Admin users are required to do specific admin operations, like uploading forms, updating settings, adding new languages and others.

**Logs**
Browser log:
```
script.js:14 POST http://127.0.0.1:6500/medic/login 401 (Unauthorized)
```

Api log:
```
REQ cc040c98-64f0-4985-9eff-9a776538133c ::ffff:127.0.0.1 - POST /medic/login HTTP/1.1
2020-02-18 13:38:44 ERROR: Error getting authCtx [object Object]
RES cc040c98-64f0-4985-9eff-9a776538133c ::ffff:127.0.0.1 - POST /medic/login HTTP/1.1 401 33 32.566 ms
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/74741592-c516c600-5265-11ea-9985-dc13da9ccf81.png)

**Environment**
- App: api
- Version: 3.9

**Additional context**
It looks like we've regressed from 2.x to 3.x when we started setting the locale cookie after login.
Relevant piece of code:
https://github.com/medic/cht-core/blob/master/api/src/controllers/login.js#L139

We could catch the 404 error that this promise throws and allow users without `user-settings` to login into the app.

**Comment by dianabarsan** [comment]
Before anyone else wanders why our e2e test pass as an admin user (or why they can login locally as an admin):
1. We create the `user` doc in the `_users` database in the `secure-couchdb` grunt task (https://github.com/medic/cht-core/blob/master/Gruntfile.js#L480) - which is run before our e2e tests AND it was part of our installation instructions (https://github.com/medic/cht-core/blob/6ba75c33ce106584721ed60bf93b5530bac2dc01/README.md#enabling-a-secure-couchdb) - now part of our development instructions: https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#enabling-a-secure-couchdb

2. When api starts on a fresh database, it runs a migration called `extract-user-settings` which will create `user-settings` documents in `medic` for every `user` in the `_users` db.

**Comment by dianabarsan** [comment]
Ready for AT on `6249-allow-admin-login`.

**Comment by ngaruko** [comment]
LTGM
Feel free to merge and close @dianabarsan

**Comment by dianabarsan** [comment]
Merged into `master`.
