### ISSUE TITLE
Use CODEOWNERS file to allow app services team "write" permission to repo

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6258]
**Describe the issue**
There is a little remote/rebase process overhead that comes from working from a clone of the repository. It isn't impossible to deal with, but it would be more streamlined if our App Services team had permission to push branches directly. 

**Describe the improvement you'd like**
Give app services team write permission to the cht repos.
Use CODEOWNERS file to make core devs the code owners.
In branch protection for `master`, turn on 'Require review from Code Owners"
https://help.github.com/en/enterprise/2.16/user/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by garethbowen** [comment]
Done.

**Comment by garethbowen** [comment]
This didn't work well in practice - it assigned and spammed the entire team to the review, so we reverted it.
