### ISSUE TITLE
medic-conf `create-users` command fails when `generate_patient_id_on_people` transition is on

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6259]
**Describe the bug**
Cannot run `medic-conf create-users` while `generate_patient_id_on_people` is enabled.

**To Reproduce**
1. `medic-conf create-users --url=https://openhie.dev.medicmobile.org`
1. Result is `StatusCodeError: 409 - {"code":409,"error":"Document update conflict."}`
1. Disable `generate_patient_id_on_people` transition
1. Can create users

**Expected behavior**
You should be able to create users with transitions enabled.

**Environment**
- Instance: openhie.dev.medicmobile.org does not repro on dev
- Client platform: Ubuntu Bionic
- App: webapp + medic-conf
- Version: master

**Additional context**
This is a regression in 3.8.0. Labeling as Priority 0 as "production issue"

**Comment by dianabarsan** [comment]
Can be ATed on 6259-users-get-before-put .

**Comment by ngaruko** [comment]
@dianabarsan ... @kennsippell mentioned in the description above it "does not repro on dev", what configuration/settings did you use to fix/test this issue? Thanks

**Comment by dianabarsan** [comment]
@ngaruko unfortunately, this is a race condition between API and Sentinel that no configuration guarantees to generate. The instance @kennsippell observed this on, I believe, was using `default` config. 

I would try to disable all transitions except `generate_patient_id_on_people`, make sure Sentinel's queue is clear and it's not processing any tasks (like scheduled messages or purging) and maybe have a large-ish (couple thousand docs) offline user doing initial replication while you're calling the API endpoint to create a user. 
Also, when creating users via medic-conf, make sure that you pass names for the contact and place, not uuids. 

This is what happens in API when a user with a new place and contact is created:
(a) new place doc is created (and saved)
(b) new contact doc is created under place from (a) (and saved)
(c) the place doc from (a) is updated to set the primary contact from (b) *this is where the bug happens*
(d) new user is created
(e) new user settings is created

In the meantime, Sentinel picks up the new place (a) and `generate_patient_id_on_people` sets a `place_id` on it, creating a new rev. On step (c), API doesn't read the place doc from the DB, just updates with the old rev it has in memory, therefore conflict. 

So, essentially, try to make Sentinel faster and API slower and *mabe* you'll be able to replicate.

**Comment by ngaruko** [comment]
Thanks @dianabarsan . Good to go. Have you back ported this to 3.8.x ?

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.8.x`
