### ISSUE TITLE
Minor CSS updates to admin app

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6270]
Allowed for smaller width screens (eg 1280)
Icons should be constrained to a consistent size
Loading spinner shouldn't be elliptical
Add loaders to the translations table and upgrade page
Improve sizing of columns in app forms page to reduce text overlap
Don't show navbar while the app is loading

**Comment by SCdF** [comment]
Ready for AT in `admin-tweaks`.

**Comment by brad1905** [comment]
AT has passed and this is ready to be merged
