### ISSUE TITLE
Modal dialogs are replaced by the same dialog

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6272]
**Describe the bug**
When the ddoc is updated twice the first "update require" modal dialog is closed and a new one shown.

**To Reproduce**
1. Load the app
2. In a separate tab log in to futon
3. Find the `_design/medic-client` ddoc
4. Save the ddoc with no changes and wait for replication to the app
5. Notice that a "app update" dialog is shown. Don't touch anything...
6. Go back to futon and save the ddoc again
7. Notice that the dialog is closed and a new identical one opened in its place.

**Expected behavior**
There should be no change to the dialog.

**Screenshots**
![Screenshot from 2020-03-06 16-00-38](https://user-images.githubusercontent.com/2064938/76074571-ab92af80-5fc3-11ea-8c91-b52243a2991e.png)

**Environment**
- Instance: localhost
- Browser: Any
- Client platform: Any
- App: webapp
- Version: master

**Comment by garethbowen** [comment]
Ready for AT in `localtoast`

**Comment by garethbowen** [comment]
This change adds additional Snackbar notifications when running on `localhost` so developers will know which stage of the deployment is complete.

**Comment by ngaruko** [comment]
LGTM (according to expected behaviour in description above). However, should we have the modal and toast when the `_design/medic-client` ddoc was never touched before saving @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/79299526-65245f00-7f38-11ea-8ecb-1492479374cb.png)

**Comment by garethbowen** [comment]
@ngaruko What do you mean by "medic-client ddoc was never touched"? Are you saying you didn't change that doc? The medic-client ddoc is updated automatically by API when, for example, a new version of the app is pushed. Is it possible this is what happened here?

**Comment by ngaruko** [comment]
@garethbowen - What I did was to open the ddoc and save it without changing a thing ... then back to the UI, there were the toast and the modal. 
[localtoast.zip](https://github.com/medic/cht-core/files/4484484/localtoast.zip)

**Comment by garethbowen** [comment]
@ngaruko Right - the modal (and toast) should be there. This issue is if it changes twice then the first modal is closed and a second modal is shown which is jarring to the user. Looking at your video it's hard to tell but it looks like it is working as expected. It's easier to see if you have both windows visible so you can make sure the modal doesn't change on the second ddoc update.

**Comment by ngaruko** [comment]
Thanks @garethbowen . The modal does not change on the second save. Feel free to merge and close!
