### ISSUE TITLE
Specifiying contactLabel in tasks configuration breaks task list rendering

### ISSUE THREAD

**Issue by derickl** [medic/cht-core#6274]
**Describe the bug**
Tasks, by default, get their contact labels from the contact object. However, If you are generating a tasks for a contact you have no access to, you can specify that using the `contactLabel` configuration by either setting it as a static string or resolving it using a function. Using any form of `contactLabel` breaks tasks rendering. i.e, no tasks are shown on the task list and surprisingly, no errors are logged on the browser console.

**To Reproduce**
1. Add as contactLabel definition on a task as per https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#tasks
2. Compile and upload your app settings. Sync the app and reload.
3. The valid task disappears

**Expected behavior**
The task should render with the appropriate contact label.

**Logs**
No logs are dumped on the browser console.

**Environment**
- Instance: cmmb-ke.dev
- Browser: (Firefox (73), Chrome (80)
- Client platform: OSX 10.15.3, Ubuntu 18
- Version: 3.8
- medic-conf: 3.1

**Additional context**
Fiddling around the medic-conf codebase, it seems the web app expects contactLabel to be an object which is not consistent with what has been documented [here](https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#tasks) and [here](https://github.com/medic/cht-core/blob/b2bc4b1ce44513cf446873e9caed940d143e3266/shared-libs/rules-engine/src/transform-task-emission-to-doc.js#L60)

**Comment by garethbowen** [comment]
Scheduled for `3.9.0` but this should be considered for backporting to `3.8.x`

**Comment by dianabarsan** [comment]
Ready for AT on `6274-fix-task-contact-label`. 
Do we move this to `3.8.1` ?

**Comment by garethbowen** [comment]
Yes. Done!

**Comment by ngaruko** [comment]
LGTM - Feel free to have a second look @derickl .

**Comment by garethbowen** [comment]
Merged into `master` and backported to `3.8.x`

**Comment by garethbowen** [comment]
@magp18 Can you please open a new bug issue with reproduction steps?
