### ISSUE TITLE
Tasks not appearing on person profile before syncing has succeeded in 3.8.0

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#6287]
**Describe the bug**
When working with 3.8.0, there is a delay before a task that is meant to show up immediately appears. A task meant to show immediately after a form submission doesn't show until after syncing has happened. 

**To Reproduce**

1. configure for a task to show immediately after profile creation (person-create)
2. observe the task not appearing on the just created person's profile
3. after while click "Sync now" in the hamburger menu and observe the task show up after syncing completes 

**Expected behavior**
The task should appear immediately.

**Logs**
n/a

**Screenshots**

**Environment**
- Instance: local docker set up
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.8.0

**Additional context**
 I'm using a local docker setup for this on a browser.

**Comment by garethbowen** [comment]
Consider including in 3.8.1

**Comment by kennsippell** [comment]
To clarify, this works as expected on the tasks tab but the task list on the contact's profile doesn't refresh automatically.

**Comment by kitsao** [comment]
I also noticed that clicking on a task when on a contact's profile doesn't open the task form, rather it takes the user to the tasks list. On tasks list, clicking on the same task doesn't open it immediately, the user has to do some other unrelated action such as click on other tasks, which open as expected, close and open the former for it to open.

**Comment by benkags** [comment]
https://github.com/medic/cht-core/issues/6287#issuecomment-598887855
The tasks don't show immediately in the tasks tab for me

**Comment by dianabarsan** [comment]
@benkags I'm unable to replicate on current master. 
Can you please share your configuration - both the task config and the form you're using to create the person. 
Also, it would be useful to have more information, like: what type of device are you using for testing? how many docs does your user have? 
Thanks!

**Comment by kitsao** [comment]
Follow up to my [comment](https://github.com/medic/cht-core/issues/6287#issuecomment-599446867) above, were you able to reproduce the same @dianabarsan? Should it be a separate issue altogether?

**Comment by dianabarsan** [comment]
@kitsao I am also unable to replicate the task linking/redirection issue. Could you please share your configuration?

**Comment by kitsao** [comment]
[CMMB-KE config](https://github.com/medic/config-cmmb-ke/tree/v3.8.0)
```
instance: https://cmmb-ke.dev.medicmobile.org
user: demo
password: V1s10n@2030
```
Steps to reproduce:
1. Login and navigate to `Test test test Household` > `Test test test`
2. Do a `Monthly Screening` on the `Actions` tab. 
```
Is Test test test pregnant? = Yes
How many antenatal care visits has Test test test done so far during this pregnancy? = 0
```
Complete the form and submit.

3. Notice the `Pregnancy confirmation and FP referral follow up` on the person's profile
4. Click on the task. Notice it takes you to the tasks list under tasks tab
5. Click on the same task. Notice the behavior...it doesn't open the action form
6. Click another task to open. Click back the initial task. Notice the action form opening

Let me know how it goes @dianabarsan

**Comment by dianabarsan** [comment]
Thanks @kitsao ! 
I can replicate your issue (clicking on tasks on a person's profile doesn't open the task directly in tasks list) in your instance and a local 3.8 deployment, however not in a local `master` deployment. 

This is a different issue than the one @benkags reported, so I believe we should track it separately.

**Comment by kitsao** [comment]
Noted @dianabarsan. Creating a new issue in a few.

**Comment by benkags** [comment]
@dianabarsan 
When filing this ticket was working with a local docker setup running 3.8 as indicated in the description above. There is now an instance that you can use to replicate this: https://itech-rsa.dev.medicmobile.org/

Use the login credentials in [this doc (indicated as 'For internal testing')](https://docs.google.com/document/d/179UeJ67b-6GaHCpVTt0r5lyRwgbngz2U5LJZle4Myr4/edit?usp=sharing)

To reproduce:
1. Go to "New person" and enroll a new person
2. Observe no task show up in the "Tasks" section of the person's profile and in the tasks tab
_There should be a task namely "Send scheduled messages to MMC" show up but it doesn't._
3. Manually trigger syncing(twice) to have the task show up.

The config for this instance is [here](https://github.com/medic/medic-projects/tree/itech-rsa/zazic-zimbabwe).

**Comment by dianabarsan** [comment]
@benkags 
The reason you are not seeing the task before the sync is because your configuration only generates the task when: 

```
if (schedule && c.contact.patient_id && pilot_users.indexOf(c.contact._id) == -1) {
``` 
Taken from: https://github.com/medic/medic-projects/blob/itech-rsa/zazic-zimbabwe/rules.nools.js#L119

Notice that you're checking for `c.contact.patient_id`. This field is generated by sentinel. so it's expected to do two syncs (one to upload the contact and one to download the updated contact) in order to trigger the task. 

If you remove the requirement for `c.contact.patient_id`, you should see the contact immediately. Can you please confim?

**Comment by benkags** [comment]
Thanks @dianabarsan!
That was actually it.
