### ISSUE TITLE
Current language not being picked up by elements in repeat groups

### ISSUE THREAD

**Issue by derickl** [medic/cht-core#6288]
**Describe the bug**
When you change a user's language from English to say Chichewa, the app  UI and most form components UI use the right translations. The exception to this is in elements in a repeat group which are defaulting to English.

**To Reproduce**
1. Upload the attached XLS form
2. Change the current user's language
3. Choose 'Repeat' form from the action bar.
4. Add one repeat element
5. Open the list to review the values.

I'm currently testing using english and swahili. For my case, values in Swahili are just abbreviations
of the default english values.

**Expected behavior**
All values should be translated (respecting the current language choice)

**Logs**
Nothing is logged in the browser console.

**Screenshots**
Before changing the user language (english)
<img width="522" alt="Screenshot 2020-03-11 at 16 11 02" src="https://user-images.githubusercontent.com/83162/76420399-1a507e00-63b3-11ea-9d05-fe63e2306751.png">

After changing the user language (swahili)
<img width="490" alt="Screenshot 2020-03-11 at 16 11 39" src="https://user-images.githubusercontent.com/83162/76420432-289e9a00-63b3-11ea-8ce7-06d0552745ea.png">

Notice the values in the second list (in the repeat group) from the second screenshot are still in their long form (my proxy for not translated)

**Environment**
- Instance: (pih-malawi.dev, cmmb-ke.dev)
- Browser: (Firefox 73, Chrome 80)
- Client platform: (MacOS 10.15.3, Ubuntu 18)
- App: (webapp)
- Version: (3.8.x)

**Additional context**
This affects both report and contact forms.

Sample XLS
[repeat.xlsx](https://github.com/medic/cht-core/files/4318603/repeat.xlsx)

**Comment by kitsao** [comment]
cc @kitsao

**Comment by dianabarsan** [comment]
@derickl can you please share the form XLS?

**Comment by derickl** [comment]
Updated the original comment @dianabarsan

**Comment by dianabarsan** [comment]
I'm seeing the same behavior when rendering this form in `3.6.x` but not on `3.5.x`.

**Comment by dianabarsan** [comment]
There's a bug in `enketo-core` that is related to this issue: https://github.com/enketo/enketo-core/issues/596

Before server-side form generation, we were implementing what is described as the "crude solution" in the closing comment, where we would change the default form language to the user's language _before_ generating the html and model. 
After server-side form generation, we're relying on `enketo`'s language lib, which clearly is lacking the necessary functionality.

**Comment by dianabarsan** [comment]
Ready for AT on `6288-correct-form-language-for-dynamic-elements`

**Comment by derickl** [comment]
LGTM @ngaruko

**Comment by garethbowen** [comment]
Merged to `master` and backported to `3.8.1`
