### ISSUE TITLE
Make changing your password less jarring

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6292]
**What feature do you want to improve?**
Currently when you change your own password you unceremoniously get dumped back onto the login page, unclear of what happened and whether the password changed correctly (it has, to its credit).

**Describe the improvement you'd like**
We should either not log the user out when they change their password, or at least tell them that it was successful and that they are about to redirected to log back in.

**Describe alternatives you've considered**
None that I'm aware of

**Additional context**
I'm guessing it didn't used to be like this, but as we've gotten better at detecting 403s (or something similar).

**Comment by garethbowen** [comment]
I think we could fairly easily establish a new session and set the session cookie transparently then notify the user it succeeded without them having to log in again.

I'd say this is low priority because I doubt people change their password often.

**Comment by SCdF** [comment]
> I'd say this is low priority because I doubt people change their password often.

Agree. However, BRAC wants to enable this inside their 2020 SoW, so unless anything changes they'll deploy with that capability this year. 

I haven't looked into it, but I'm wondering if this is actually due to the issue that @peter-ochieng is working on (#5772), where logouts just redirect instead of prompting.

**Comment by dacar1988** [comment]
Hi @garethbowen and @SCdF! I propose this solution https://github.com/medic/cht-core/pull/6786 for this problem. Please let me know what you think about that. Thank you.

**Comment by garethbowen** [comment]
Thanks @dacar1988 ! I'll make sure it's reviewed this week.

**Comment by mrsarm** [comment]
Moved to 3.11.0 release, thanks to the @dacar1988 contribution that is in review here: https://github.com/medic/cht-core/pull/6841

**Comment by mrsarm** [comment]
The ticket is ready for AT, but the PR was merged in the Angular 10 branch `4750-angular-10-take-2`, so not sure when it should be tested (while testing the Angular 10 branch or separately).

**Comment by newtewt** [comment]
Looks good on the current master. I've tested on both web and android versions. Both do a refresh of the app and then you're good to go. Checked that you can create and sync afterwards as well. The only caveat would be longing in to the same account on multiple devices. You get logged out on sync. Which is only likely in testing.
