### ISSUE TITLE
Telemetry around end user actions

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-core#6295]
As backlog curator for end users it would be helpful to have telemetry around user actions to help prioritize issues effectively. Having data to support when possible (for example, https://github.com/medic/cht-core/issues/6226) is much more compelling than anecdotal issues (ex. https://github.com/medic/cht-core/issues/5886). 

Telemetry and user tracking will also help validate whether these design improvements are effective and demonstrate clearer results.

**Comment by garethbowen** [comment]
We have a range of specific telemetry points being collected currently ([documentation](https://github.com/medic/medic-docs/blob/master/user/telemetry.md). The downside of this approach is it only gathers specific actions, but the upside is it's very resource friendly because we don't gather a lot of data that's not wanted.

Can you think of any additional data points you'd like to have recorded?

**Comment by n-orlowski** [comment]
@garethbowen the exhaustive list is [here](https://docs.google.com/document/d/1c2UHfzaue4sNvQkiwRc93PBEdML9J9DlFNuQ23suk4k/edit). A specific example where this would be helpful is for triaging the in-app tour overhaul and being able to understand how often it is used, which tours users refer to the most + where users drop off and if the tour results in more relevant actions taken (to determine the

**Comment by ecsalomon** [comment]
It would be really nice to have telemetry data on how much time is spent on different app sections or pages (e.g., messaging, contacts, tasks, targets)

**Comment by garethbowen** [comment]
@ecsalomon That'd be awesome. Can you be more specific about which questions you're trying to answer?

I'm thinking about how to implement this and there may be challenges to work out how long the user actually spends on the a tab. Is it a problem if the "time spent" includes things like chatting to the patient while on the Contacts tab, or the Tasks tab loaded and the CHW puts the phone down and comes back to it tomorrow?

It would be much easier to get good data by restricting the criteria to specific activities which are likely to be completed in one go.

**Comment by ecsalomon** [comment]
@garethbowen Good question! Here are some questions I think we would be interested in:

- Does adding a new target increase the amount of time spent on the targets tab? How long does that increase last?
- Does adding a new widget to patient profiles or turning on high risk flagging (#5775) increase the amount of time spent on the contact tab?
- Does enabling UHC mode increase time spent on the contacts tab?

It would definitely be good to exclude any time the phone screen is dimmed or off, if that's possible.

**Comment by n-orlowski** [comment]
@garethbowen  if we could find out how often users switch between tabs per session that would help inform the nav update

**Comment by helizabetholsen** [comment]
@n-orlowski and @ecsalomon thanks for raising this topic. There are also use cases for telemetry as we continue to think about impact monitoring and analytics for TPs and self-hosted partners, as well as broader research initiatives and even partnership considerations (see link to this conversation https://medic.slack.com/archives/C024KSXQX/p1597926749003100?thread_ts=1597845786.288400&cid=C024KSXQX)

**Comment by ecsalomon** [comment]
Adding some timeline info here: We are exploring implementing UHC mode with a partner either late this year or early next year, and it would be valuable to some of the metrics mentioned above (e.g., time spent on contacts tab) for that deployment.

**Comment by n-orlowski** [comment]
Closing this out as more specific telemetry requests are captured in separate issues (ex https://github.com/medic/cht-core/issues/6651 and the larger [telemetry initiative](https://docs.google.com/document/d/1c2UHfzaue4sNvQkiwRc93PBEdML9J9DlFNuQ23suk4k/edit#heading=h.q31g948sivit))
