### ISSUE TITLE
Use the browser language as the default language

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6313]
**Describe the bug**
Going to the login page for the first time always shows in the system default language even if you have a browser/system language set.

**To Reproduce**
1. Go to App Management > Display > Languages
2. Set the "default application language" to English
3. Set the primary language in your browser to "Hindi". The method for doing this differs by browser so search for how to do it for your particular flavour.
4. Clear all your cookies and data
5. Load the login page and notice how it's translated to English.

**Expected behavior**
The login page should be translated to your browser's primary language, in this case Hindi.

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: api
- Version: 3.8.0

**Additional context**
The locale should be resolved in this order...

1. Use the `locale` cookie. This is set by the user on a previous login, or by the administrator during user setup so most likely to be correct.
2. If no `locale` cookie is set, use the browser default. This is passed in the request's `accept-language` header. This may not match with the two letter code that we use so make a best effort here. Furthermore it may not match one of the supported languages for this project.
3. If the browser default doesn't match any supported language, use the project "default application language" set in configuration.
4. If the "default application language" in the project config isn't set (very unlikely), default to English.

Step 2 is the step that's not happening yet.

**Comment by garethbowen** [comment]
Consider using this [`locale` library](https://github.com/florrain/locale) to find the supported language that most closely matches with the given `accept-language` header.

**Comment by AshleyWWW** [comment]
I've got the functionality done, I just need to set up my dev environment to run the tests myself before I submit the pull request.

**Comment by garethbowen** [comment]
Ready for AT on `AshleyWWW:master`.

NB: this is from an external contributor so we don't have a published build for this - you'll have to have a dev environment to test it fully.

**Comment by ngaruko** [comment]
LGTM
**Before**
![image](https://user-images.githubusercontent.com/6979995/85634338-475d3e00-b6cf-11ea-837b-e5343d86cf23.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/85636305-3d8a0980-b6d4-11ea-9152-9f6185e3eecf.png)

**Comment by garethbowen** [comment]
Merged
