### ISSUE TITLE
Refactor the way we deal with asynchronous loading tasks in webapp

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6327]
Related issue: https://github.com/medic/cht-core/issues/6323
and related comment: https://github.com/medic/cht-core/pull/6324#pullrequestreview-379877096

We should refactor the task-content Controller and move all the selection logic into the redux action, so it would execute seamlessly after tasks are loaded, and have the controller just update based on the state.

**Comment by garethbowen** [comment]
Bumped to 3.11.0 as the current solution works.

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by dianabarsan** [comment]
This has already been worked on with the migration to Angular 10. I think this can be closed.
