### ISSUE TITLE
Upgrade page doesn't show branches available to upgrade to if there are no betas to upgrade to

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6328]
The branches block of upgrades has a typo where it decides to show only if there are *betas* to upgrade to, as opposed to branches.

To workaround this you can always directly call the upgrade api. This will automatically update the upgrade page to show the upgrade log like normal.

See: https://github.com/medic/cht-core/tree/master/api#upgrades

Example: 

```sh
curl -X POST https://user:password@your-url/api/v1/upgrade 
	-d '{"build": {"namespace": "medic", "application": "medic", "version": "your-build-name"}}' 
	-H 'Content-Type: application/json'
```

**Comment by SCdF** [comment]
AT via: `6328-upgrade-page-typo`

**Comment by ngaruko** [comment]
LGTM
**_Before_** 
![image](https://user-images.githubusercontent.com/6979995/78611449-1f71f180-78bb-11ea-8b88-236dc3d2de2a.png)

 **_After_** 
![image](https://user-images.githubusercontent.com/6979995/78611138-5dbae100-78ba-11ea-96ef-dd0586e4091c.png)
Back to you @SCdF for a merge (would be good to merge it to get the UI going for easy testing)

**Comment by SCdF** [comment]
Merged
