### ISSUE TITLE
Add hydration api

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#6331]
**Is your feature request related to a problem? Please describe.**

Our latest work in Client-Initiated Health Assessment workflows design, has pointed to the need for an API that returns a hydrated payload. In an example use case, in a RapidPro flow initiated by a client, and using the phone number to identify the client in CHT, CHV and CHV area details are needed in the steps following workflow initiation. 

While we can use (for now) CouchDB view calls to retrieve some useful information, we cannot perform hydration easily

**Describe the solution you'd like**
An api where you pass a collection of doc ids and hydrated versions of those documents are returned.

**Describe alternatives you've considered**
This can be hacked in RapidPro (by essentially looping upwards and requesting each doc) but it's dodgy and not very efficient.

**Additional context**
#6325, put together for purposes of CIHA prototyping introduces a hydrate-only API endpoint, where when given a list of UUIDs, returns hydrated payloads for those. We really just need to formalise this by pulling it out of this branch, adding tests etc.

It's also worth mentioning that in the future we'd also want to add actual apis to solve these problems (ie a get person by phone api): CouchDB views being exposed as external apis isn't a great long term solution (eg no versioning), but for now we are going to run with it.

**Comment by dianabarsan** [comment]
Ready for AT on `6331-hydration-api`. Documentation here: https://github.com/medic/cht-core/blob/6331-hydration-api/api/README.md#hydrate

**Comment by SCdF** [comment]
Taking on for AT

**Comment by SCdF** [comment]
Mostly works, however one problem: Incorrect auth against this API results in redirection to the login page. It should return a 401 instead. Back to you @dianabarsan

**Comment by dianabarsan** [comment]
@SCdF 
This is the more of our (maybe all) API endpoints.
The way we respond to unauthenticated requests depends in whether the requests has an `Accepts` header. https://github.com/medic/cht-core/blob/master/api/src/server-utils.js#L74

As an example, you can try accessing `https://gamma.dev.medicmobile.org/api/v1/users` in a browser that is not logged into the instance.

**Comment by SCdF** [comment]
@dianabarsan no worries, I'll raise a ticket about more generally solving this, feel free to merge as is!

**Comment by SCdF** [comment]
Raised: https://github.com/medic/cht-core/issues/6399

**Comment by dianabarsan** [comment]
Merged.
