### ISSUE TITLE
Generate service worker at runtime

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-core#6338]
**What feature do you want to improve?**
The service worker is generated when the app is built wherein we cache pseudo-static assets like branding and translations. The challenge with this approach is that in order to support dynamic element update (#5954) we have to use a network-first cache policy to ensure the correct assets are served to users. This isn't really true to the spirit of offline first and results in a lot of redundant requests when assets haven't changed.

**Describe the improvement you'd like**
The ideal scenario would be to generate the service worker at runtime when the dynamic assets are updated.

**Additional context**
This is a good opportunity to explore the capabilities of the workbox library.

**Comment by latin-panda** [comment]
Just a FYI: There's an open [issue](https://github.com/medic/cht-core/issues/6514) to migrate from sw-precache to Workbox.

**Comment by dianabarsan** [comment]
A sad interaction here is that, whenever the service worker is updated, regardless of which caches are busted, users get a "new update available" dialog, which tells them to refresh the page to use the new resources.
For changes to login page only, the refresh is not necessary. 

I'm looking for feedback if this is a big issue. How often do login page elements change (translations and branding)? 

As a fix, I've looked for a short time if there's any way to tag resources somehow and filter out which changed and whether we should trigger the dialog, but this has the potential of a too complicated solution for a small problem. 
Another option would be to have two service workers, one for app resources which do require a refresh to run the new code, and one for other resources, which don't require refresh. 

Appreciate feedback :)

**Comment by garethbowen** [comment]
I suspect those elements won't change much after the initial development phase so it's probably ok to prompt for refresh spuriously.

Two service workers would also be fine. In some ways that would be good because only the login page SW has to be generated at runtime so the app SW could still be generated at build.

I'm not a big fan of the filtering approach as it seems to fragile IMO.

**Comment by dianabarsan** [comment]
This is ready for AT on `6338-live-service-worker`. 

The service worker file is now generated and updated in API:
- once on startup, after migrations
- every time the main ddoc is updated
- every time translations are changed (or languages are added or removed)
- every time the branding doc is changed

Clients should get a reload popup every time the service worker file received an update.

**Comment by ngaruko** [comment]
The service worker file is now generated and updated in API:

- **once on startup, after migrations**


```
2021-10-05 23:21:34 INFO: Merging translations… 
2021-10-05 23:21:35 INFO: Translations merged successfully 
2021-10-05 23:21:35 INFO: Running db migrations… 
2021-10-05 23:21:35 INFO: Database migrations completed successfully 
2021-10-05 23:21:35 INFO: Generating service worker 
```
**

- every time the main ddoc is updated (small edit to `/ddocs/medic/validate_doc_update.js of the

** 
```
Caching dynamic URL "/medic/login" with dependency on user-supplied string
Caching dynamic URL "/medic/_design/medic/_rewrite/" with dependencies on ["/Users/bede/Medic/cht-core/api/src/public/appcache-upgrade.html"]
Total precache size is about 16 MB for 26 resources.
2021-10-05 23:43:23 INFO: Service worker generated successfully 
```

- **every time translations are changed (or languages are added or removed) - changed name of existing language in UI**


```
2021-10-05 23:56:14 INFO: Detected translations change - reloading 
RES 1d431a2d-bcc0-4cf9-acfe-56a003a3e1dc ::ffff:127.0.0.1 - GET /medic/_changes?
...
....
Total precache size is about 16 MB for 26 resources.
2021-10-05 23:56:16 INFO: Service worker generated successfully 
RES 5cf5a9e9-d6ed-416b-bae5-69bb36e55726 ::ffff:127.0.0.1 - GET 
```

- **every time the branding doc is changed (changed branding in the UI)**


```
REQ 606fd45a-a98b-40e1-a375-201980647933 ::ffff:127.0.0.1 - GET /medic/branding? HTTP/1.1
RES 77ceb86b-3658-46fa-9f0e-238b9896205a ::ffff:127.0.0.1 - GET /medic/branding? HTTP/1.1 200 397 544.647 ms
REQ a346d787-1911-495f-b02d-887e5a92b597 ::ffff:127.0.0.1 - GET /medic/branding/googs.jpeg?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1
RES 317f4f96-7e07-4a5e-add4-ad754afcca82 ::ffff:127.0.0.1 - GET /medic/branding/lego.png?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1 200 90380 500.608 ms
REQ 25cd9985-9207-4a62-b78a-caea73b7d47c ::ffff:127.0.0.1 - GET /medic/branding/googs.jpeg?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1
RES 606fd45a-a98b-40e1-a375-201980647933 ::ffff:127.0.0.1 - GET /medic/branding? HTTP/1.1 200 397 377.509 ms
REQ fd5b0709-d593-49fc-ab6d-acf50c30da17 ::ffff:127.0.0.1 - GET /medic/branding/lego.png?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1
RES 25cd9985-9207-4a62-b78a-caea73b7d47c ::ffff:127.0.0.1 - GET /medic/branding/googs.jpeg?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1 304 0 186.008 ms
RES a346d787-1911-495f-b02d-887e5a92b597 ::ffff:127.0.0.1 - GET /medic/branding/googs.jpeg?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1 200 12236 319.279 ms
REQ 62d97158-5510-4dfe-97ff-8559f489cec4 ::ffff:127.0.0.1 - GET /medic/branding/lego.png?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1
RES fd5b0709-d593-49fc-ab6d-acf50c30da17 ::ffff:127.0.0.1 - GET /medic/branding/lego.png?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1 200 90380 194.933 ms
RES 62d97158-5510-4dfe-97ff-8559f489cec4 ::ffff:127.0.0.1 - GET /medic/branding/lego.png?rev=2-31678617f03d995a73a0c37f424d5b6c HTTP/1.1 200 90380 221.431 ms
.....
.....
Total precache size is about 16 MB for 26 resources.
2021-10-05 23:59:58 INFO: Service worker generated successfully 
```

**Comment by dianabarsan** [comment]
@ngaruko were you also seeing the elements on the login page updated after the service worker was updated?

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by dianabarsan** [comment]
The end user is supposed to get a modal to reload when the service worker is updated.

**Comment by ngaruko** [comment]
@dianabarsan I will check for these and confirm. I did most testing in the backend. Didn't pay as much attention to the UI.
