### ISSUE TITLE
enketo widgets cannot be built using webpack

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6344]
**Describe the issue**
All of the cht-core defined widgets have this factory loader syntax around them. [Example](https://github.com/medic/cht-core/blob/master/webapp/src/js/enketo/widgets.js#L1). From what I can tell, this appears to be on cht-core widgets only and not on the enketo-core widgets.

```
if ( typeof exports === 'object' && typeof exports.nodeName !== 'string' && typeof define !== 'function' ) {
  var define = function( factory ) { // eslint-disable-line
    factory( require, exports, module );
  };
}
```

This wrapper prevents the widgets from being built using webpack. This makes supporting our custom enketo widgets in the medic-conf-test-harness more difficult. https://github.com/medic/medic-conf-test-harness/issues/46

I suspect this may block the upgrade to a modern angular build system with tree shaking (haven't investigated, just a guess).

**Describe the improvement you'd like**
Can we safely remove this wrapper?

**Comment by garethbowen** [comment]
The enketo widgets in the version of enketo-core that we use _do_ have this wrapper. I'll refactor these somewhat when upgrading to a newer enketo-core ( #4386 ) but we can't use the es6 that enketo-core now uses until we drop browserify for the cht-core builds. We'll probably end up using [commonjs syntax](https://webpack.js.org/api/module-methods/#commonjs) which should work with webpack. Does that make sense in the short term?

**Comment by kennsippell** [comment]
Ya. I actually didn't realize how closely integrated the widgets are with our angular services.

> Several of the widgets directly call angular services (Android-datepicker, bikram-sambat-datepicker, db-object-widget, mrdt, notewidget, phone-widget, simprints). The angular services called are: Language, $translate, MRDT, Select2Search, Enketo, Markdown, Settings, DB, Simprints.
medic/medic-conf-test-harness#46

I suspect the harness can't easily integrate with our widgets at this time.
