### ISSUE TITLE
Search Everything does not function as expected

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6356]
**Describe the bug**
The search reset feature does not work as expected. It correctly resets the search results on the LHS, but doesn't clear out the "Search Everything" box.  In addition, if you then tap on the search button again, with the same text in it, it does _not_ perform the search using that text.  The problem exists in both the Reports tab and the People tab.

**To Reproduce**
Steps to reproduce the behavior
![searchbug](https://user-images.githubusercontent.com/10096985/79405471-784c2480-7f62-11ea-8b45-ae88c4e9aaa4.gif)

**Expected behavior**
When I click on the curly arrow next to the eyeglass, it should reset the search results on the LHS (as it does today) _and_ clear out the "Search Everything" box.  

**Logs**
N/A

**Environment**
- Instance: cht.app.medicmobile.org
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.7.1

**Additional context**

**Comment by garethbowen** [comment]
Ready for AT in `6291-case-id`. This PR also fixes #6291 and #6149 so test those at the same time!

**Comment by brad1905** [comment]
Working as expected, "Search Everything" is cleared.

**Comment by newtewt** [comment]
@garethbowen  can we close this one out?

**Comment by garethbowen** [comment]
@newtewt The PR also fixes 2 other issues so I don't want to merge until those have passed AT.

**Comment by ngaruko** [comment]
I have been seeing a weird behaviour with just one report and the search field . The report is one of the test/demo data loaded by ` medic-conf csv-to-docs upload-docs `. In the search, if one type the surname/last name, the report shows in the search. However, if the first name is used, no result shows. It seems to happen only on this particular report.
Steps to reproduce - 
1 - Launch `medic` on local host
2 - upload test data (`csv-to-docs upload-docs`)
3 - one report will be loaded (Pregnancy registration for `Adelia Akiyama`)
![image](https://user-images.githubusercontent.com/6979995/81742034-940c0180-94f3-11ea-858a-dcb2f1a7d37e.png)
4 - Search everything with surname (`akiyama`) >>> the report shows as expected
5- Now, clear and search by first `adelia`
6 - no results 
[adelia.mov.zip](https://github.com/medic/cht-core/files/4618314/adelia.mov.zip)

Note: It doesn't seem to happen with new created reports and it is not on this particular branch, but I thought it might be worth looking into.
Your thoughts @garethbowen ?

**Comment by garethbowen** [comment]
Merged.
