### ISSUE TITLE
Ability to swap colors/position of the No-Yes buttons in the confirmation modal 

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#6373]
**What feature do you want to improve?**
Posting this comment from a partner verbatim for design consideration

> When someone cancels the submission of the report, currently, the default in red for “are you sure you want to leave” is a red YES. I think that the default should be a “NO” here so that people do not mistakenly cancel but have to confirm a little more proactively. Just put default to red NO and then make them move cursor to say yes.

**Describe the improvement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by benkags** [comment]
cc @n-orlowski

**Comment by SCdF** [comment]
I don't think we'd want the *ability* to swap these: there should be one answer that we consider correct. I do think this is an interesting perspective and one we should fold into whether we want to make the product-wide decision to revisit this dialog.

**Comment by n-orlowski** [comment]
Great point, the red yes button is definitely confusing. My reco would be to keep our desired outcome (ex. keep them in the form) as the primary cta (on the right side) and the alternative as a text link (on the left) which is @benkags 's proposed solution for this particular case. 

@SCdF could we use green/red buttons for confirmation/cancellation messaging respectively, product-wide? These should be used sparingly however, for `Submits` or `Deletes` for example.

Lastly, best practices in these instances is to be as prescriptive as possible (and avoid "are you sure" messaging) so potentially we could look at:

This form is not finished until you submit. You will lose your data if you leave now.
Leave form (text link) / Stay on page (primary button, likely blue makes sense in this case)

LMK your thoughts!
