### ISSUE TITLE
Labels for select_ fields are grey, black for other fields

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6374]
Seen in 3.8 on the cht-covid.dev instance.  

For some of the `select_` fields, the question (label) text is grey. For other fields, the question (label) is black.  I think this is a bug but want to confirm.  If it is a bug, please raise in medic/cht-core

![Screen Shot 2020-04-08 at 12 24 35 AM](https://user-images.githubusercontent.com/10096985/78744417-816c3e80-792f-11ea-9f8f-1da52fd9e78e.png)

**Comment by michaelkohn** [comment]
Transferred to cht-core

**Comment by garethbowen** [comment]
Agreed this is a bug - we should be consistent. I think they should all be the darker colour (almost black), eg:

![Screenshot from 2020-04-28 13-09-26](https://user-images.githubusercontent.com/2064938/80435786-98f87f00-8951-11ea-8e98-7f2bcb4be0c4.png)

@n-orlowski What do you think?

**Comment by n-orlowski** [comment]
Yes please!

**Comment by SCdF** [comment]
Code reviewed **and** AT'd. In the process we found a second issue around text colouring of the LHS add report menu, both of which have been fixed (I checked the RHS action menu, it is also fine):

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/583851/80573195-715bf200-89f7-11ea-97ec-f8680c8e7521.png)

</details>
