### ISSUE TITLE
Error when editing scheduled message from webapp

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6385]
**Describe the bug**
We have a feature in webapp that enables us to edit scheduled messages groups from the report detail page. All edits are failing with an error.

**To Reproduce**
1. Open a report that has "scheduled" Scheduled messages
2. Edit one of the groups (click on the "Edit" link underneath the group's title)
3. Don't make any changes (or do, it doesn't matter) and click Save
4. You get a "Error updating group" error. If you made any changes to the group, they were not saved (refresh the page to check).

**Expected behavior**
The group should be edited and the popup should disappear.

**Logs**
Browser logs show:
```
angular.js:15567 Error submitting modal TypeError: Cannot read property 'deleted' of undefined
    at remove (edit-group.js:60)
    at edit-group.js:79
    at processQueue (angular.js:17945)
    at angular.js:17993
    at Scope.$digest (angular.js:19112)
    at angular.js:19432
    at TaskTracker.completeTask (angular.js:21231)
    at angular.js:6812
```

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/35681649/80595384-52785280-8a2d-11ea-92fb-8d200d33410a.png)
.

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.9

**Comment by dianabarsan** [comment]
This should already be fixed with the migration to Angular 10.

**Comment by garethbowen** [comment]
Marking for AT.

**Comment by newtewt** [comment]
I think there is still work to be done here. In some cases it works fine. In others I get the same error.  I'm using the standard config and editing messages on a New Pregnancy.  Deleting then saving also seems to trigger the same error and again in some messages and not others. 

```
inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3 Error submitting modal TypeError: Cannot read property 'deleted' of undefined
    at inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3
    at inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3
    at inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3
    at inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3
    at c.$digest (inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3)
    at inbox.js?_sw-precache=1a6ea198940ff26ad36995abacd8e3fb:3

**Comment by newtewt** [comment]
Neverminded on that comment. I don't know if my browser had updated after updating. It is working now.  I am deleting, editing, creating messages with no errors. Working in both chrome and firefox.

**Comment by dianabarsan** [comment]
> I don't know if my browser had updated after updating
It hadn't :) There is no more `inbox.js` :) m
