### ISSUE TITLE
Error on report not cleared

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6386]
**Describe the bug**
If you exit a report after getting an error message (eg missing required field), all subsequent forms will show the error until a form is submitted successfully, or you reload the page.

**To Reproduce**
1. Open a form
1. Omit a required field on the final page
1. Click **Submit**
1. See `Error saving report` next to **Submit**, and `Error: Form is invalid` in console.
1. Exit the report and confirm
1. Open any form
1. See `Error saving report` text adjacent to **Next** and **Submit** buttons throughout form.

**Expected behavior**
Save errors on one form should not be shown on other forms.

**Logs**
```
inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3 
Error submitting form data:  Error: Form is invalid
    at inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3
    at inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3
    at inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3
    at c.$digest (inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3)
    at inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3
    at Object.completeTask (inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3)
    at inbox.js?_sw-precache=9763010dc1f9f8c594277aa18fb01c7f:3
```

**Screenshots**
### Valid error
<img src="https://user-images.githubusercontent.com/789512/80636311-44c1cd80-8a2b-11ea-99e8-da900b847617.png" width=50% />

### Invalid error when starting another form
<img src="https://user-images.githubusercontent.com/789512/80635644-29a28e00-8a2a-11ea-9994-73ffb69d1361.png" width=50% />

**Environment**
- Instance: localhost
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: Windows
- App: webapp
- Version: 3.8ish, using the 6291-case-id branch

**Additional context**
Most forms have a summary page and without required fields on last page they won't run into this problem. Some deployments ask CHWs to confirm info on the summary page, in which case they can run into this scenario.

**Comment by garethbowen** [comment]
This is the same error as was fixed on the Contacts tab in #5813 and should be fixed in the same way.

**Comment by garethbowen** [comment]
There is a very similar bug here too.

1. Open a form
2. Omit a required field on the final page
3. Click Submit
4. See Error saving report next to Submit, and Error: Form is invalid in console.
5. Provide a value and blur the field

**Expected**
The "error saving report" should go away.

![Screenshot from 2020-07-01 15-39-31](https://user-images.githubusercontent.com/2064938/86200537-14c0b300-bbb1-11ea-8311-5855626ca3c6.png)

**Comment by garethbowen** [comment]
This also affects the "actions" forms on the Contacts tab, and the forms on the Tasks tab.

**Comment by dianabarsan** [comment]
Ready for AT on `6386-clear-submission-error`

**Comment by ngaruko** [comment]
LGTM atm.
As part of this or maybe a separate issue, shall we consider disabling/greying out the the `submit` until all required boxes are ticked ? @garethbowen ?

**Comment by garethbowen** [comment]
Yes I think that's a separate issue to check the state of the validation. The error message that's being cleared here is a generic message that could be to do with having no internet connection, or similar.

I think we should raise an issue to have two messages - one for "validation error" which disables the submit button and clears when something changes, and one for everything else which let's you try again.

**Comment by ngaruko** [comment]
Raised #6521

**Comment by garethbowen** [comment]
Merged.
