### ISSUE TITLE
Error when selecting incoming message from deleted contact

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6387]
**Describe the bug**
This was already reported and partially fixed by https://github.com/medic/cht-core/issues/5812
Still happens when the 1st message in the conversation is an "incoming" message instead of an outgoing message.

**To Reproduce**
1. Make sure "update_clinics" transition is enabled.
2. Create a contact with a phone number
3. From admin SMS -> Test message section, send a message from the contact's phone number.
4. In webapp, delete the contact
5. In webapp, go to the messages tab and open the message from the contact.
6. Observe that the thread is not displayed and the bottom of the LHS list displays `Error fetching messages`.

**Expected behavior**
Conversation should load with Unknown Sender (or similar).

**Logs**
```
Error fetching contact conversation TypeError: Cannot read property 'messages' of undefined
    at messages-content.js:134
    at processQueue (angular.js:17945)
    at angular.js:17993
    at Scope.$digest (angular.js:19112)
    at angular.js:19432
    at TaskTracker.completeTask (angular.js:21231)
    at angular.js:6812
```

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.9

**Comment by garethbowen** [comment]
Adding to 3.11.0 - deleted contacts are fairly rare but we should handle this gracefully and messages are getting more use lately.

**Comment by garethbowen** [comment]
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by dianabarsan** [comment]
This should be fixed by the upgrade to Angular 10: 
![image](https://user-images.githubusercontent.com/35681649/109273951-8c67e000-781b-11eb-8854-db756f323086.png)

**Comment by garethbowen** [comment]
Great! Moving to 3.11 for AT.

**Comment by newtewt** [comment]
This is working as expected. The messages load but have unknown sender.  

@dianabarsan I notice that reports have the contact name even after deleting. I assume we don't store that data on the messages?

**Comment by dianabarsan** [comment]
> I notice that reports have the contact name even after deleting

Reports can have a `patient_name` field that we use, but that depends entirely on the form. 
If you delete the `patient_name` field (or rename it), your report should say "Unknown subject". 

>  I assume we don't store that data on the messages
That's correct, we don't store sender/receiver information on the message, just uuids.
