### ISSUE TITLE
LHS Contact Action labels don't render at 400px or below

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6394]
**Describe the bug**
Labels for LHS actions do not render their text if your device's horizontal resolution is 400px or less.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have config that gives you more than one contact form to create. 
2. Open up the contact page so that you can see this
3. Use whatever tooling you like to resize the browser to 400px wide or below

<details>
<summary>At 401px</summary>

![image](https://user-images.githubusercontent.com/583851/80972268-d52a5480-8e15-11ea-8a30-da2814e34fac.png)

</details>

<details>
<summary>At 400px</summary>

![image](https://user-images.githubusercontent.com/583851/80972319-df4c5300-8e15-11ea-9c96-c73581aa7e89.png)

</details>

**Additional context**
This also gets rid of a lot of other text, and so is probably _somewhat_ intentional, but is clearly not a good idea in this specific case. I also haven't looked around the rest of the app, it may be that we are losing more text that we shouldn't be elsewhere.

Deployment used in screenshots: https://covid-demo-ke.dev.medicmobile.org/#/contacts/

Priority for this may be blocking, pending investigation by @derickl . MoH are using Nokia 1 phones, which are in theory 480px wide, but it looks like they are applying some kind of zooming at the OS level to reduce that resolution (125% maybe: (480/125)*100 = 384 :thinking: ). If we can work around it and get them to run a higher resolution this may not be important, otherwise it's blocking the MoH from proceeding. Awaiting update from @derickl

**Comment by SCdF** [comment]
Yeah so this is totally zoomed at 150% (480/150)*100 = 320:  

![image](https://user-images.githubusercontent.com/583851/80973353-2b4bc780-8e17-11ea-9ff9-068fb86f8d47.png)

**Comment by derickl** [comment]
I could not get a workaround @SCdF so this would be a P0 that would literally block our deployment with MoH

**Comment by kennsippell** [comment]
cc: @MaxDiz @abbyad

**Comment by SCdF** [comment]
Okey dokey, I've chucked it in our current release. It shouldn't be a huge piece of work so it is unlikely to delay anything significantly

**Comment by derickl** [comment]
For context - this affected all but the facilitator's phone during our demo yesterday to the MoH which left the users very frustrated.

**Comment by PhilipNgari** [comment]
Thanks guys! it is a major decision point on the tool adoption and  may need us to consider it for a slice release that can salvage the situation. in his own words the MoH data manager "the rest of the app forms look pretty user friendly and I like them,however the LABELS are a big concern for me and my  team will ask how I intend the users to know what the ICONS represent".  Special time ahead of us. I appreciate every ones effort  in looking for a solution for this.

**Comment by SCdF** [comment]
I've fixed this so that while the main LHS action label is hidden on small resolutions as intended, the action list labels no longer are:
![image](https://user-images.githubusercontent.com/583851/81063776-5d6d3000-8ed0-11ea-85ae-19984a0b8107.png)

**Comment by MaxDiz** [comment]
@garethbowen the current workaround should be ok for testing scheduled this week. Full scale, live deployment is scheduled for May 11th. We may need to create a 3.8.2...

additional conversation: https://medic.slack.com/archives/C3TJFFKK7/p1588673346009600

**Comment by antonykhaemba** [comment]
Hi @SCdF 
I have noticed that from the screen shots you shared, `people` tab label has disappeared. Does that mean after the fix, both the `register` and `people` labels will have to disappear? cc @MaxDiz 

cc @PhilipNgari @SMurithi

**Comment by garethbowen** [comment]
@antonykhaemba No, this change will not change the tab labels. If you check the original screenshot at 400px it also didn't have labels on the tabs - these are only shown on 401px and above. To reiterate we will make every effort to ensure the _only_ change is to the labels on the add contacts menu.

**Comment by garethbowen** [comment]
Contrary to my comment an hour ago (ahem) I've decided to change some other things about the menu to make it consistent with the Add Report menu. I've prepared a new branch with a different approach than the one @SCdF took.

This is all branched off master so it may look a little different in `3.8.x` but it gives you a comparison of just the changes.

| Before | After |
|---|---|
| ![before-phone-lhs](https://user-images.githubusercontent.com/2064938/81119764-8b5d7d80-8f7f-11ea-9758-a3414abdf945.png) | ![after-phone-lhs](https://user-images.githubusercontent.com/2064938/81119774-92848b80-8f7f-11ea-9a18-4bf002af7c41.png)  |
| ![before-phone-rhs](https://user-images.githubusercontent.com/2064938/81119848-b47e0e00-8f7f-11ea-901f-d13656dfe80a.png) | ![after-phone-rhs](https://user-images.githubusercontent.com/2064938/81119859-b9db5880-8f7f-11ea-8c52-a237e63b397c.png) |
| ![before-tab-lhs](https://user-images.githubusercontent.com/2064938/81119880-c19afd00-8f7f-11ea-8e63-9ae8c5435096.png) | ![after-tab-lhs](https://user-images.githubusercontent.com/2064938/81119886-c495ed80-8f7f-11ea-98d5-3692d2a0958c.png) |
| ![before-tab-rhs](https://user-images.githubusercontent.com/2064938/81119894-ca8bce80-8f7f-11ea-95ec-110b7f6b2cb8.png) | ![after-tab-rhs](https://user-images.githubusercontent.com/2064938/81119901-ccee2880-8f7f-11ea-8362-a8f77ae205d7.png) |

**Comment by kitsao** [comment]
@garethbowen the screenshots look great! Looking forward to testing. cc @antonykhaemba @SMurithi @PhilipNgari

**Comment by garethbowen** [comment]
Ready for AT on `6394-restructure-html-to-match-add-report-menu`

**Comment by newtewt** [comment]
I have tested this using the browser's(chrome, firefox) device scaling and went well under 400 px and seeing it work. I've also tested on my pixel 2 and kyocera phones I have but neither have dimensions under 400. This is working as expected in those conditions.

**Comment by garethbowen** [comment]
Merged into `master` for release in 3.9.0. We can backport to a patch release later if needed.
