### ISSUE TITLE
Pregnancy registration allows first pregnancy and previous miscarriage risk factors

### ISSUE THREAD

**Issue by brad1905** [medic/cht-core#6395]
During a pregnancy registration the user is allowed to specify risk factors of "first pregnancy" and "previous miscarriage" which should not be allowed.  

1. Create female person within a household
Person should be within childbearing age range
2. select new action, Pregnancy registration 
3. Risk factors form allows user to select Y to "first pregnancy" and Y to previous miscarriages or stillbirths 

**Expected behavior**
miscarriages and stillbirths question should not display if first pregnancy is answer Y 

**Environment**
master

Chrome
Android 

**Additional context**
<img width="751" alt="first pregnancy with prev miscarriages" src="https://user-images.githubusercontent.com/62311678/80984555-dbeba400-8de2-11ea-91bd-77b6765c004d.png">

**Comment by latin-panda** [comment]
@Benmuiruri Please check if this is still an issue. 
If yes, then please involve QA from the start (before starting development) and fix the [pregnancy form](https://github.com/medic/cht-core/blob/master/config/default/forms/app/pregnancy.xlsx). There's a possibility that you need to fix e2e tests after fixing this.

**Comment by latin-panda** [comment]
@Benmuiruri some resources that might help:
- Info about form configuration in XLS [here](https://xlsform.org/en/).
- Building cht app forms [here](https://docs.communityhealthtoolkit.org/apps/tutorials/app-forms/)
