### ISSUE TITLE
Scoping: Investigate IVR options 

### ISSUE THREAD

**Issue by ranjuts** [medic/cht-core#6396]
**Potentially required for Remote CHW onboarding**. Immediately relevant in Kenya (C-EBS national scale with MOH) and MOH Zambia. 

Africa's Talking is a potential in Kenya esp given we support an integration with them already.  Viamo needs to be explored in Zambia as Africa's talking does not provide IVR there. We have had initial partnership conversations [with Viamo](https://medic.slack.com/archives/C024RRXT2/p1587030649318300)

Would be able to leverage the same providers in other countries (e.g. Viamo in Nepal, Uganda etc)

@shreyakb please add any further context that's helpful.

**Comment by MaxDiz** [comment]
Based on this cut-sheet, Viamo offers service in each of the locations mentioned: https://viamo.io/wp-content/uploads/2020/03/Viamo-Capabilities-Statement-Epidemic-Response.pdf

Twilio also offers service in some, but not all, locations: https://support.twilio.com/hc/en-us/articles/223183068-Twilio-international-phone-number-availability-and-their-capabilities

Any additional info you can provide on project deployment requirements and constraints would be helpful.

**Comment by abbyad** [comment]
Assigning myself as I have been having conversations with providers. It is possible that we won't have an IVR system that is compatible across all our deployment countries, so please add countries and deployment timelines to this issue.

**Comment by ranjuts** [comment]
I started this spreadsheet to keep track of requests but there are many unknowns. https://docs.google.com/spreadsheets/d/1AXvteiBp--OpuUdz4PuuKPyaKMY-yKvHgvcgHUOx8uE/edit#gid=0

**Comment by benkags** [comment]
Just had a chat with an Africas Talking Developer on an unrelated issue to do with CIHA and I brought up IVR. He recommends https://mteja.io/. It's a sister company and AT has been using it for their IVR needs internally instead of their own voice offering. 

I have not had a look into it yet but wanted to leave it here an an option we may want to explore.

**Comment by abbyad** [comment]
Thanks @benkags, will keep this in mind too!

Current countries of operation for Mteja: Kenya, Uganda, Nigeria, South Africa, Philippines, USA
![image](https://user-images.githubusercontent.com/789512/86608394-7a79ba00-bf78-11ea-8ec8-a274b9f018a9.png)

**Comment by garethbowen** [comment]
@abbyad Can we remove this from 3.10.0, and either put it in 3.11.0 or track it separately from product releases?

**Comment by abbyad** [comment]
We are tracking it with releases for scheduling purposes. We are aiming to wrap up the investigation by the end of next week, so it should be fine to leave in 3.10 and will close ahead of the release.

**Comment by abbyad** [comment]
Some thoughts from the investigation are in this [internal doc](https://docs.google.com/document/d/1XAlgfTNUJDaLdA04FDtyfjPSIaLCFeUAFU1gMUrS3Ic/edit#). I think this gives us enough to move forward and to close this issue.

@ranjuts please comment in the doc where additional info is needed, and any questions you may still have. We can create a new issue for any more IVR-related work.
