### ISSUE TITLE
Age not displaying on Contact Summary in Default config if you enter a year or month instead of actual birth date

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6397]
**Describe the bug**
In the Default config, when viewing a contact, the age is not displayed for contacts whose age was entered as a number instead of a date. 

**To Reproduce**
1. Create a contact with an age entered in # of years OR # of months
2. View the contact summary for that contact (it's blank)
3. Edit the contact and enter a specific birth date
4. View the contact summary for that contact (the # of years is displayed)

**Expected behavior**
We should show the age on the contact summary regardless of how it was entered.

**Screenshots**
See below

**Environment**
- Instance: https://localhost
- Browser: Firefox
- Client platform: MacOS
- App: webapp
- Version: I've tested it on 3.7 and 3.8.1 and it didn't work on either

![Age Issue](https://user-images.githubusercontent.com/10096985/81033247-d2088600-8e60-11ea-89bd-ad0b1b58eb78.gif)

**Comment by latin-panda** [comment]
@ngaruko Me and Ben are trying to reproduce this one but so far no luck, can you please check if this is still an issue? If yes, please let us know here in the ticket the steps to reproduce. 

We tested with v4.4

**Comment by ngaruko** [comment]
@latin-panda . I will attempt to reproduce this, and report back if it is still an issue.

**Comment by latin-panda** [comment]
@ngaruko Thanks! 
cc: @Benmuiruri to continue the follow up

**Comment by ngaruko** [comment]
This one seems to work @michaelkohn . If there are instances that still run 3.7 or 3.8, we could check if they are having this problem?
[Video](https://www.loom.com/share/d754e8c05eb94442a4ebf5248a5aa509)

**Comment by michaelkohn** [comment]
Ok. I'll go ahead and close this ticket then.
