### ISSUE TITLE
Change the Create Report button icon to better indicate what it does

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6403]
**What feature do you want to improve?**
The Create Report button in the right hand side action bar of the contacts tab is ambiguous because it's a simple plus icon with no indication that it creates a new report.

![Screenshot from 2020-05-06 11-05-35](https://user-images.githubusercontent.com/2064938/81124983-f3fe2780-8f8a-11ea-80d6-5e47f89ea34a.png)

**Describe the improvement you'd like**
Update the icon so it's obvious what will happen if you click it. The obvious choice is to use the Report icon with a stacked plus to match the create place and create person buttons, eg:

![Screenshot from 2020-05-06 11-18-06](https://user-images.githubusercontent.com/2064938/81125089-4b9c9300-8f8b-11ea-9a27-f7e5575b90b8.png)

This is consistent but this is not very inspired.

**Describe alternatives you've considered**
Some other icon...

**Additional context**
Some changes to this section were made in #6394

**Comment by abbyad** [comment]
Should this be closed as we schedule https://github.com/medic/cht-core/issues/4346 and https://github.com/medic/cht-core/issues/4726 instead?

**Comment by garethbowen** [comment]
#tinywins

**Comment by latin-panda** [comment]
@n-orlowski What icon can we use for this scenario?

**Comment by n-orlowski** [comment]
@latin-panda Going with Gareth's suggestion above for consistency makes sense to me!

**Comment by ngaruko** [comment]
Tested on branch `6403-change-report-add-icon`
**_Web_**:
![image](https://user-images.githubusercontent.com/6979995/137033321-343a2e1c-d9ee-4b6d-9249-7ebfbca68368.png)

**_Mobile_**
![image](https://user-images.githubusercontent.com/6979995/137033468-bb567742-9724-46ca-8227-4d822b184b52.png)

 Good to merge @latin-panda

**Comment by latin-panda** [comment]
Thanks Bede!
This is merged to the main branch.
