### ISSUE TITLE
User name autofilled with "medic" 

### ISSUE THREAD

**Issue by brad1905** [medic/cht-core#6404]
Form to add new user has user name autofilled

1. Log in to App management as user "medic"
2. Click "Users"
3. Click "Add User"
4. User name is autofilled with "medic"

**Expected behavior**
The User name field should be blank when adding a new user.

**Comment by dianabarsan** [comment]
Is it possible your browser just autocompletes because you saved these credentials? Can you try in an incognito window or another browser?

**Comment by garethbowen** [comment]
I've noticed the same thing with the password field. We should be able to make sure these fields do not autocomplete with the right combination of attributes.

**Comment by latin-panda** [comment]
I have turn off the autocomplete for this field.

**Comment by latin-panda** [comment]
Adding this resource as reference: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by SCdF** [comment]
Ready for AT in `6404-username-autofill-off`

**Comment by newtewt** [comment]
I'm seeing this occur in Firefox but couldn't get it to happen in Chrome. After the branch is applied. I don't see the autofill happen in either browser. 

@JenniferMuli  feel free to merge.
