### ISSUE TITLE
Missing translation: `state.duplicated`

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6415]
**Describe the bug**
Missing translation for `state.duplicate`, so the key appears in the app for messages on reports.

**To Reproduce**
You can try to get this state to occur on a report's messages, but simpler to just look for the translation in the App Management page.
1. Go to **App Management** page
1. Click on **Display** and then go to **Translations** tab
1. Search for `state.duplicate`
1. See that it is missing.

**Expected behavior**
Should show the label "duplicate", not key itself.

**Screenshots**

<img src="https://user-images.githubusercontent.com/789512/81338217-3fdbca00-907a-11ea-931d-1b3a5ff27cdb.png" width=50%>

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: Windows
- App: webapp
- Version: `6291-case-id` branch, which is somewhere between 3.8 and 3.9.

**Additional context**
This was meant to be solved in #6208, but [master doesn't have `state.duplicate`](https://github.com/medic/cht-core/blob/fb053239a2b13bec82f2428f3e59802657eb9b6a/ddocs/medic/_attachments/translations/messages-en.properties#L1119-L1130), and **it is not in POEditor**. [Quicklink to our documentation on translations process](https://github.com/medic/medic-docs/blob/master/development/translations.md#adding-new-keys).

**Comment by garethbowen** [comment]
This was removed on Feb 10 in this commit: https://github.com/medic/cht-core/commit/86e62d66be8a0bba15e675f88e59463f3d48e471

**Comment by abbyad** [comment]
Could you tell why that happened? Was it overwritten accidentally because it wasn't in POEditor so the alphabetised export didn't include it?

**Comment by garethbowen** [comment]
It's possible the translations were imported to POE as part of the pre-release process, then the key was added, then they were exported from POE just before release. Release documentation: https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_major.md

Maybe we should document that immediately before exporting you should import again to make sure none are missed.

**Comment by abbyad** [comment]
Works well! Passes AT, ready to merge.

#### Before and After
<div>
<img src="https://user-images.githubusercontent.com/789512/81434542-4fb7e480-9134-11ea-812b-6512b2c09dbb.png" width=45%>
<img src="https://user-images.githubusercontent.com/789512/81434548-5181a800-9134-11ea-97de-47857ac596f1.png" width=45%>
</div>
<br>
The missing `case_id` translation is expected, given that the separate branches haven't been merged into master yet.

**Comment by garethbowen** [comment]
Merged.
