### ISSUE TITLE
Allow you to configure outbound to send the same record multiple times

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6419]
**What feature do you want to improve?**
Prior to 3.9, every time a document changed (either by a human or programmatically, including by sentinel itself) and it passed a `relevant_to` function, an outbound push was queued, unless one was already queued. Every 5 minutes or so, sentinel's scheduler would pick up these queued outbound tasks and executed them. 

In [3.9.0](#6312) we added an [optimisation so that outbound tasks now send immediately if they can](#6306). This would have changed the logic above from "up to once every 5 minutes or so, with whatever data is the latest" to "every single time the document changes, or if the external service is down up to once every 5 minutes or so, with whatever data is the latest".

Because this was confusing, and because more writes happen than you'd think (because of sentinel for example), we did the easiest thing to simplify this logic. In 3.9.0, a configured outbound push only sends to the external service once.

**Describe the improvement you'd like**

There are legitimate use cases where you would want to send the same document multiple times. The most obvious example is using outbound to keep a contact in sync with an external EMR or similar. If the phone number changes in CHT, that change should be pushed to the EMR. However, their may also be other situations and examples, and we need to learn about these to make sure we are supporting the right situations.

**Describe alternatives you've considered**
There may be various ways to work around this depending on the deployment, but there are potentially situations where this is not possible.

**Additional context**

I think there are three really obvious solutions here, all which have pros and cons and can be variously combined:
 - Add a `sync: true` flag, which defaults to false, and when set to true will resend whenever it can whenever it thinks anything has changed. The pros is that this will always keep external services up to date, the cons is that this will definitely send pointless updates, and if the semantic meaning of sending a push is important to you (ie it indicates a "thing" happened) this will not work for you.
 - Internally hash the REST output, store it against the info doc and only send if the prior send was different to this one. Pros: no extra configuration to get wrong. Cons: will break in subtle and unsolvable ways if people configure outbound mappings to not be deterministic / idempotent, an obvious example being adding a timestamp onto your external REST request
 - Add a `uniqueness: [...]` property, which lets you somehow define what things constitute uniqueness, and then hash *that* as above. Pros: solves the deterministic issues above, Cons: more configuration to configure

**Comment by SCdF** [comment]
After talking with Marc we are going with the middle option above.

**Comment by SCdF** [comment]
Ready for AT at `6419_outbound-multi-send-support`

**Comment by ngaruko** [comment]
Seems to fire multiple errors at once @SCdF 
```
Last login: Tue Jul  7 17:43:05 on ttys008
You have new mail.
➜  ~ docker exec -it medic-os /bin/bash

root@0b6b145fbd0f:/srv# less /srv/storage/medic-sentinel/logs/medic-sentinel.log 


















S38MoJhgYtFbyuGQ==/node_modules/@medic/outbound/src/outbound.js:29:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2020-07-07 06:03:59]   [message]: 'CouchDB config key \'medic-credentials/textit.in\' has not been populated. See the Outbound documentation.' } 
[2020-07-07 06:03:59] 2020-07-07 06:03:59 ESC[31mERRORESC[39m: Failed to push f88e2fab-eb91-4645-80d1-50a8aa96ad3f to textit-patient: { Error: CouchDB config key 'medic-credentials/textit.in' has not been populated. See the Outbound documentation.
[2020-07-07 06:03:59]     at secureSettings.getCredentials.then.password (/srv/software/medic-sentinel/md5-ilPkKkS38MoJhgYtFbyuGQ==/node_modules/@medic/outbound/src/outbound.js:29:13)
[2020-07-07 06:03:59]     at <anonymous>
[2020-07-07 06:03:59]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2020-07-07 06:03:59]   [stack]: 'Error: CouchDB config key \'medic-credentials/textit.in\' has not been populated. See the Outbound documentation.\n    at secureSettings.getCredentials.then.password (/srv/software/medic-sentinel/md5-ilPkKkS38MoJhgYtFbyuGQ==/node_modules/@medic/outbound/src/outbound.js:29:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2020-07-07 06:03:59]   [message]: 'CouchDB config key \'medic-credentials/textit.in\' has not been populated. See the Outbound documentation.' } 
[2020-07-07 06:03:59] 2020-07-07 06:03:59 ESC[32mINFOESC[39m: checking schedule again in 4 minutes 

```

**Comment by SCdF** [comment]
@ngaruko apart from the double logging is this AT complete? I'll take a quick look but it's very minor and may just be an artefact of how we report transition failures, and I'm guessing you also see this on master right now as well?

**Comment by ngaruko** [comment]
@SCdF If you are still looking at the error logging, there is even a less elegant error log I see when I use the wrong `flow_number`. Obviously most of it comes from the third party api (`textit`), but it looks quite challenging to look. 
[outbound-error.txt](https://github.com/medic/cht-core/files/4887444/outbound-error.txt)
Other than that, it is good to merge - and yes, it is on master as well

**Comment by SCdF** [comment]
I've reopened the ticket responsible for making clean error logs and we'll continue that conversation there. Since the scope of this ticket passed AT, I'll merge it.

**Comment by SCdF** [comment]
Merged
