### ISSUE TITLE
Db-doc doesn't allow unallocated data_records

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6421]
**Describe the bug**

**To Reproduce**
1. Enable an offline user to be allowed to view unallocated data records (config + permission)
2. Create a public SMS form and send this form from an unknown phone number
3. As the offline user, attempt to access the resulting doc with a direct request: `<host>/medic/<doc_id>`
4. Get a forbidden result

**Expected behavior**
You should see the contents of the doc.

** NB **
To enable offline users to download unallocated docs, you need to 
1. add/change `district_admins_access_unallocated_messages` to be `true` at the root of your app_settings 
2. change your role to allow `can_view_unallocated_data_records` permission

**Environment**
- Instance: local
- App: api
- Version: 3.9

**Comment by dianabarsan** [comment]
Ready for AT on `6421-db-doc-unallocated`

**Comment by ngaruko** [comment]
LGTM.
Feel free to merge this @dianabarsan .

**Comment by dianabarsan** [comment]
Merged.
