### ISSUE TITLE
Support resolving tasks concerning unknown contacts

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6425]
**Describe the bug**
We can no longer rely on `action.modifyContent` to inject contact information into reports generated by task actions.
This causes tasks that are about unknown contacts to generate reports that are unattached (are missing their subject).
This workflow is used where supervisors with replication depth receive `needs_signoff` reports about patients they can't see.

**To Reproduce**
1. Create a supervisor with replication_depth low enough that they don't see patients.
2. Create a chw under this supervisor.
3. Configure a form with needs_signoff.
4. Configure a task for the supervisor triggered by the `needs_signoff` form. Configure this to be resolved if the task action is executed.
5. Submit the `needs_signoff` form as the CHW.
6. Sync as the supervisor and check if you have generated the task.
7. Complete the task.
8. Your task does not resolve (it's still in the list) and inspecting the resulting report, it's missing all patient information.

**Expected behavior**
The resulting report should have the same patient information as the generating report.

**Environment**
- Instance: local
- App: webapp
- Version: 3.9

**Additional context**
When written to disk, tasks are minified and they only retain a "forId" property representing `action.contact._id`, while `action.contact` is deleted.
https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/transform-task-emission-to-doc.js#L77
When rehydrating the task, we rely on the `forId` contact to exist in order to repopulate `action.contact`: https://github.com/medic/cht-core/blob/master/webapp/src/js/controllers/tasks-content.js#L109

We should either:
a) keep `action.contact` when the contact is unknown - this allows more information besides a uuid to be injected into the resulting report 
b) use a stub when rehydrating and contact is unknown - this means that the resulting report will only have the uuid available and no other information.

**Comment by dianabarsan** [comment]
This is considered a blocker for upgrading existing projects which rely on this working. Some of these projects are required to upgrade to 3.9 to access other new features, like DHIS2 itegration. 

Bumping this to High Priority and scheduling for 3.9.

**Comment by garethbowen** [comment]
Ready for AT in `6425-suportt-clearing-tasks-from-unknown-contacts`

**Comment by dianabarsan** [comment]
@derickl @kennsippell Would you mind checking if this meets your needs for the projects that are blocked? Thanks!

**Comment by newtewt** [comment]
@dianabarsan  @brad1905  and I are working through this. We are seeing the task clear now but we thought that that patient data would be represented in the report that was clearing the task. Is that correct? 

The patient_uuid field is being set to the submitter of the task report and not the original patient on the report that clears the form. 

```
report.off.patient_uuid
80002
report.off.patient_id
report.off.patient_name
```

**Comment by newtewt** [comment]
ACtually after further review I think it's working right. Need to confirm on @brad1905 's instance first.

**Comment by newtewt** [comment]
The issue was that the user(chw supervisor) we were seeing clicking on the patient id was going to the contacts page which threw me off. It is linking to the correct patient_id and a user that can see that patient can navigate to them.

**Comment by newtewt** [comment]
This seems to be working as expected @dianabarsan . I'm able to now clear tasks as a supervisor and the report has the expected id associated.

**Comment by dianabarsan** [comment]
@newtewt 
Sorry for not being clear, Due to urgency, we went with option b) use a stub when rehydrating and contact is unknown - this means that the resulting report will only have the uuid available and no other information. 
This was both quicker and safer.

**Comment by newtewt** [comment]
Yeah! That's what we were seeing. Feel free to merge @dianabarsan

**Comment by dianabarsan** [comment]
Merged!
