### ISSUE TITLE
Infinite spinners when loading tabs as admin

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6433]
**Describe the bug**
As admin when accessing data we request it from the server. If the server is down the spinner keeps spinning forever with no indication that the request failed.

**To Reproduce**
1. Log in to the webapp as admin
2. Take the server down (alternatively go offline).
3. Click on the Contacts tab
4. Note that the spinner never goes away.

**Expected behavior**
The spinner should be hidden and a useful error message shown instead.

**Logs**
```
Error fetching user settings TypeError: "NetworkError when attempting to fetch resource." angular.js:15567
    consoleLog Angular
    getHomePlaceId contacts-content.js:77
    Angular 6
        processQueue
        scheduleProcessQueue
        $digest
        evalAsync
        completeTask
        timeoutId
```

**Screenshots**
![Screenshot from 2020-05-18 09-51-35](https://user-images.githubusercontent.com/2064938/82160972-30b41200-98ed-11ea-9ff8-0f620c552b9d.png)

**Environment**
- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: webapp
- Version: latest master ~3.9.0

**Additional context**

This also affects the Messages and Analytics tabs so fix those too. Check all tabs and sections with loaders.
This probably also happens for other errors so it may not just affects admins, it's just easy to reproduce with an admin user. Check that we handle other errors correctly.

**Comment by mrsarm** [comment]
I checked the error details and I could reproduce the error well, and I could see that in some tab sections like _"Reports"_ or _"People"_ this is solved showing an error message in the same place the spinner was loading:

![Screenshot_20200630_110749](https://user-images.githubusercontent.com/1608415/86136858-ef557b80-bac2-11ea-9e06-b50aabbda956.png)

Both with the same message and markup, so I'll reuse the same markup for the rest of the tab sections.

**Comment by garethbowen** [comment]
Added to 3.10.0 because if not merged any solution will probably be broken by the 3.11.0 angular refactor.

**Comment by garethbowen** [comment]
Ready for AT in `6433-fix-infinite-spinners`

**Comment by ngaruko** [comment]
Looks good  - Maybe we could improve on the error message to be more specific but that would be a different improvement issue.
