### ISSUE TITLE
Age displayed as 0 or blank despite valid age entered 

### ISSUE THREAD

**Issue by brad1905** [medic/cht-core#6435]
New person added to household shows blank in Age field instead of displaying a valid age. 

1. click People tab
2. Select Health Facility
3. Select Area
4. Select Household
5. Click New person 
6. Enter valid Full name
7. click checkbox Date of birth unknown
8. Enter years 33
9. Select Female
10. Enter valid Phone Number
11. Select Role Patient
12. Click Submit
13. Person created shows blank in Age field

**Expected behavior**
The person's age should display as entered.

**Environment**
- Browser: (eg: Firefox, Chrome)
- Client platform: (MacOS, Android)
- App: webapp
- Version: master

**Additional context**
Using a birthdate instead of an age had same result
![android-Screenshot_20200518-131835_Chrome](https://user-images.githubusercontent.com/62311678/82257848-a16b2680-990d-11ea-8016-98564c1216b4.jpg)
<img width="1135" alt="desktop-Screen Shot 2020-05-18 at 1 19 02 PM" src="https://user-images.githubusercontent.com/62311678/82257854-a3cd8080-990d-11ea-8cae-57c7ed000ace.png">
[gsmith.txt](https://github.com/medic/cht-core/files/4646563/gsmith.txt)

**Comment by garethbowen** [comment]
Closing as ancient. Please reopen if this happens in production.
