### ISSUE TITLE
Sentinel will skip changes entirely in certain conditions

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6440]
**Describe the bug**
These are, in fact, two bugs.

First bug is: if sentinel receives lots of changes in one tick, it will queue up multiple handlers of these changes in the event loop. They're synchronous and they'll be executed in one tick.
If, while executing, we're passing the imposed (100) sentinel change queue limit, we cancel the changesFeed - over and over - without null checking. This throws an error that prevents the act of enqueueing to happen.

The second bug is: when we pass the imposed queue limit threshold, we store the last_seq in a variable and we use that instead of the DB value (from sentinel-meta-data) when we restart the feed.
We also kill the change-queue (dump all changes we queued up) when we receive a settings change that breaks transitions config!
So all changes in between memory `last_seq` and `sentinel-meta-data.processed_seq` are straight up skipped when the queue is killed.

I haven't been able to replicate bug#1 locally, but it's failed multiple times on Travis. So I assume it's performance related.
Replicating bug#2 might require some scripting and quick reactions.

**To Reproduce Bug2**
1. Enable `generate_shortcode_on_contacts` transition (or `generate_patient_id_on_people`)
2. Create 200 persons in one batch (you can go for more if you want, but about 200 should be enough).
3. Watch the sentinel output to see an entry like: "Transitions: queue size 101 greater than 100, we stop listening"
4. Very quickly after this, you should break the config (simplest is to enable an non-existent transition) - it's helpful to have a script that does this. After this, Sentinel should stop processing docs (because config is broken).
5. Fix the config. No need to hurry for this one :)
6. At this point, Sentinel should start processing docs (because the config is fixed). Wait for it to process all docs. Optionally, you can repeat steps 3-4.
7. Once everything is processed and the queue is clear, check the "person"s you added in step 2) to see if all have a patient_id. Some will not! <- this is the bug.

**Expected behavior**
All person contacts should be processed!

**Logs**
Bug#1 will output something like:
```
>> Error in .on("change", function): TypeError: Cannot read property 'cancel' of null
>>     at Changes.<anonymous> (/home/diana/projects/medic/sentinel/src/lib/feed.js:53:19)
>>     at Changes.emit (events.js:310:20)
>>     at tryCatchInChangeListener (/home/diana/projects/medic/sentinel/node_modules/pouchdb-core/lib/index.js:20:10)
>>     at Object.Changes.opts.onChange (/home/diana/projects/medic/sentinel/node_modules/pouchdb-core/lib/index.js:58:5)
>>     at /home/diana/projects/medic/sentinel/node_modules/pouchdb-adapter-http/lib/index.js:1040:18
>>     at Array.filter (<anonymous>)
>>     at fetched (/home/diana/projects/medic/sentinel/node_modules/pouchdb-adapter-http/lib/index.js:1030:35)
>>     at /home/diana/projects/medic/sentinel/node_modules/pouchdb-adapter-http/lib/index.js:273:9
>>     at runMicrotasks (<anonymous>)
>>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Environment**
- Instance: local, Travis
- App: Sentinel
- Version: 3.9

**Additional context**
This is, most likely, introduced in 3.9 by https://github.com/medic/cht-core/commit/c68c5fd2497e43201eac87cfbed8efab2ac811ea

**Comment by garethbowen** [comment]
Ready for AT in `6440-fix-sentinel-queue`

**Comment by dianabarsan** [comment]
Just an addendum as @newtewt found another issue (bug3):

To replicate, follow the same steps as to reproduce bug2, but increase the number of contacts to 300 and brick the settings soon after your upload is done (no need to wait for the log entry). 
Same as before, if the bug exists, there should be contacts without `patient_id` when sentinel has "apparently" finished. 
If you restart sentinel, you'll notice that it will process everything that was remaining.

**Comment by newtewt** [comment]
I uploaded a bunch of data using medic-conf. Recreated the issue in master and now with the latest change it is working fine. I can't get the first error to occur either. @dianabarsan  feel free to close.

**Comment by dianabarsan** [comment]
Merged.
