### ISSUE TITLE
Support submission of forms for places in SMS

### ISSUE THREAD

**Issue by IreneAchola** [medic/cht-core#6444]
**What feature do you want to improve?**
Creation of places was recently introduced in SMS. Households can now be created and new patients added in their respective households, however, SMS does not support submission of other forms for these places e.g. household_visit,off/muting forms.

**Describe the improvement you'd like**
To be able to submit forms (acceptable reports) for places. (place-centric workflows)

**Describe alternatives you've considered**
Submitting household forms on household heads, but this will only work for some forms.

**Additional context**
It would be helpful to have this improvement, for instance in cases where a family has moved out of an area. Instead of having to OFF/mute each person individually, it would be more reasonable to mute the household.
It would also be useful to align with indicators like MoH indicators.

**Comment by MaxDiz** [comment]
may be related to: https://github.com/medic/cht-core/issues/6409

**Comment by leah-ngaari** [comment]
cc @korirm , @PhilipNgari and @SMurithi

**Comment by MaxDiz** [comment]
Based on discussion with the Roadmap planning team, we are adding to v3.10 as bug, if turns out to be more than a bug, we will bump to v3.12 as an improvement. This request is relevant to the SMS reference app for MoH Kenya, but is not currently an active deployment.

**Comment by dianabarsan** [comment]
I don't understand tagging as a "bug" as it was never part of any feature request. 
Places first appeared as "subjects" in SMS as part of https://github.com/medic/cht-core/issues/5614 , which only covered **creation** and at no point mentioned place centered workflows.

**Comment by dianabarsan** [comment]
At the moment, transitions, mainly "registration", requires the subject to be a "person" explicitly (it will add an error if the form lacks a `patient_id` field filled with a valid person shortcode). 

We also do not hydrate the "place" (reports have `patient`, not `place`). So we don't consider places as actual "subjects" in terms of workflows. 

It's a completely new feature, I believe.

**Comment by MaxDiz** [comment]
Thanks for the quick investigation @dianabarsan . Based on your response, I will bump this to v3.12 and re-tag as an improvement.

**Comment by antonykhaemba** [comment]
Hi @MaxDiz 
Is it possible to move this request to v3.10, we are likely to deploy the project in August 2020. Delays might affect the deployment of MOH SMS projects.

cc @IreneAchola @leah-ngaari and @PhilipNgari

**Comment by PhilipNgari** [comment]
@max  I would propose we consider this to be released in the next release.There is possibility of a deployment in  1 month time or so.

**Comment by MaxDiz** [comment]
It's too late to add non-production related issues to v3.10. I am adding to v3.11 to try to meet the tbd deployment timeline

**Comment by dianabarsan** [comment]
Ready for AT on `6444-places-workflows-sms`

**Comment by newtewt** [comment]
Sending an sms report with `place_id` associates the subject to the place. 
SMS schedules are created and cleared by `place_id`
Admin app is showing the messages. 
When both `place_id` and `patient_id` are present. The `patient_id` takes priority. 


I'm still working on some of these based on the not of changes in the PR. 

When you get back could you clarify these areas?
Updates schedules to build correct message context that includes place and place registrations.
Updates message-utils to include place registrations.
Updates due-tasks to generate place messages correctly.

**Comment by newtewt** [comment]
Also, is there a cht-docs change for this?

**Comment by dianabarsan** [comment]
> Updates schedules to build correct message context that includes place and place registrations.
> Updates message-utils to include place registrations.

Both of these target the same result, to include place and place registration in the message context so {{variables}} resolve correctly.
Place registrations should be handled exactly like patient registrations, with the caveat that patient registrations take precedence. 
When your context is correctly set up, you should be able to access place and place registration fields/data in your message context, just like you would for a patient.

> Updates due-tasks to generate place messages correctly.

due-tasks takes scheduled tasks that have a `message_key` (so their messages context should be generated right before the message should be sent), so we have to pass correct context so the place related {{variables}} resolve correctly in the message context. 
This loosely translates to: if you have translated scheduled messages for a place, the generated message should resolve place {{variables}} correctly.

> Also, is there a cht-docs change for this?

I'll work on that today!

**Comment by newtewt** [comment]
I'm creating messages now with the data available on the place ex: the name, type.  Using the `{{name}}` and `{{type}}`
Registering new people also still works in genearting the data correctly. 

```messages.schedule.registration.followup_anc_pnc = {{contact.name}}, did {{patient_name}} {{patient_id}} require care? To register pregnancy, send 'P {{patient_id}} <Weeks since LMP>'. For PNC, send delivery report using 'D {{patient_id}} <Delivery Code> <Days Since Delivery>'. Thank you!```

When `patient_id` and `place_id` are defined on the report. The messages are generated and data is for the patient. 

I think this is ready to merge @dianabarsan

**Comment by dianabarsan** [comment]
PR to update documentation: https://github.com/medic/cht-docs/pull/457

**Comment by dianabarsan** [comment]
Merged to `master`.
