### ISSUE TITLE
Upgrade UI only considers *.app.medicmobile.org as "production"

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6447]
In production instances we only show supported upgrades, i.e. real releases.

In every other instance we also show upgrades to betas and branches.

We do this by reading the URL. Which worked fine in the old days, but now lots are self hosting you could argue this isn't correct.

We should either:
 - be OK with self hosting installing arbitrary things, but probably add a clear warning that releases "below this line" are not supported in any way.
 - Change this logic to use the `process.env.NODE_ENV === 'production';` check instead

**Comment by SCdF** [comment]
Unsure if this is a [bug or an improvement](https://s3.amazonaws.com/neowin/forum/uploads/post-48-1086855312.jpg). I feel like the first option is an improvement, and the second option is a bug. YMMV.

**Comment by garethbowen** [comment]
I'm calling this a bug as it's not working as expected.

**Comment by latin-panda** [comment]
Just wondering, @garethbowen If this is in Webapp, can we do it during or after the upgrade of Angular? 🤔

**Comment by garethbowen** [comment]
@latin-panda The upgrade UI is all in the `admin` app, which is not going to be upgraded to angular 10 right away so I think it can be done during the upgrade of `webapp`.

**Comment by garethbowen** [comment]
Ready for AT in `6447-always-show-releases-upgrade-ui`

**Comment by ngaruko** [comment]
LGTM @latin-panda 
Just two nitpicks (not probably linked to this work):
a) for releases with long name, the name goes over adjacent row 
![image](https://user-images.githubusercontent.com/6979995/92673143-83b74680-f36e-11ea-9009-34d6254fa4d1.png)
b)On each release there is a warning (`This release may be incompatible with your current release`). It seems to show on ever release: not sure how `potentiallyIncompatible(release)` is defined/verified in the code in order to NOT show the warning IF the release is compatible

**Comment by latin-panda** [comment]
Hi @ngaruko,
A) I have truncated the long names and added a tooltip to expose the full name.
<img width="1212" alt="Screen Shot 2020-09-14 at 12 38 15 pm" src="https://user-images.githubusercontent.com/66472237/93040193-8a083400-f688-11ea-9d4a-468c7c06261b.png">
B) The rules as based on version, based version and current version: https://github.com/medic/cht-core/blob/a2f86650e0af3e4147e9919fdcbef031cb02db47/admin/src/js/controllers/upgrade.js#L120 
Do you think there is an issue with this rule? We can open a separate ticket.

**Comment by ngaruko** [comment]
@latin-panda 
A) Looks good thanks
B) Makes sense - the comment in the code makes it clear :
`unless their version  is in the form 1.2.3[-maybe.4] (ie it's a branch) we can't tell and will just presume maybe it's bad`...
Feel free to merge and close.
