### ISSUE TITLE
Publish a dev version of the docker-compose.yml

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-core#6455]
**Describe the issue**

My local cht-core was working until I made some config changes. 

1. Why does a config change prevent the service from starting?
2. This error is not prescriptive to help app builders fix the issue, as per the screenshot below

![Screenshot from 2020-06-01 10-34-53](https://user-images.githubusercontent.com/63068738/83440187-605e3080-a43c-11ea-84c5-669d45425619.png)

3. When using docker, can't access the fauxton. So the only work around is to delete couchdb and restart
4. Even restarting does not change the situation.

Could there be any workaround for this?

**Comment by SCdF** [comment]
@Marina-Kenf it looks like you uploaded an invalid form. Googling for error code 6 we get here: http://xmlsoft.org/XSLT/xsltproc.html, which somewhat unhelpfully says "6: error in one of the documents".

So API fails to start because when it tries to precompile forms that you uploaded at one is invalid somehow, and that step crashes API. If you can work out _how_ you made them invalid, this would be helpful to know. It's probably pretty serious (like not valid XML).

On accessing Fauxton, you're right you can't access it because API is down. However, if you can exec into medic-os as you've done to read logs, and use `curl` to interact with CouchDB. 

We should definitely improve our error reporting here: we could at least say *which* XML file caused issues, which would make it easier to delete it or read it from CouchDB. Note that if you were running in DEBUG logging mode you would probably be able to work this out, but this docker compose file isn't setup that way. Perhaps it should be.

As to whether this should bring API down, that's an interesting question.

**Comment by SCdF** [comment]
Actually an easier workaround is to just expose the CouchDB port in your docker-compose.yml file.

If you edit it with this:

```
...
 haproxy:
    container_name: haproxy
    image: medicmobile/haproxy:rc-1.16
    volumes:
      - medic-data:/srv
    ports:
     - 5984:5984
...
```

(basically, you're adding the `ports:` line and the mapping below it)

You can now access futon over 5984, so `http://localhost:5984/_utils`.

If you're already using CouchDB locally, change the first `5984` to a different unused port and access it there.

**Comment by kennsippell** [comment]
> As to whether this should bring API down, that's an interesting question.

imo Invalid configurations shouldn't crash the API.  If an app builder does somehow upload an invalid configuration like this, it's a poor experience with a high burden of education/diagnosis to investigate via docker/couchdb. Currently, App Builders have to:

1. bash into docker
1. read through the logs
1. understand the log output enough to know which config component specifically is causing the problem (in this case, a bit difficult)
1. establish a connection to the database
1. delete or alter the configuration directly in couchdb

The ideal App Builder experience would be via medic-conf, which requires a running API.
If this happens on a dev instance (or even in production), SRE would become involved to resolve the issue.

**Comment by garethbowen** [comment]
> Docker Compose Updates to expose port 5984 and enable debug logging by default. Or provide a different yml for app builders to enable this by default?

What about medic-conf validates the XML before uploading so we can catch and report useful errors before pushing the XML? For example, API could have an endpoint to attempt compilation and report errors with enough info for debugging?

> API service shouldn't crash on "error transforming xml" + improved logging to identify which XML file caused the error

I'm not convinced that's the right approach. If we solve the issue above to catch these errors earlier then this should not happen. The problem with logging and continuing is it'll appear like everything is working until the form just doesn't show up on the phone.

We should definitely improve the logging to tell you which file failed at the very least!

**Comment by kennsippell** [comment]
> The problem with logging and continuing is it'll appear like everything is working until the form just doesn't show up on the phone.

You could replace the form with a stock form that just says "compilation error" or alike.

> What about medic-conf validates the XML before uploading so we can catch and report useful errors before pushing the XML? For example, API could have an endpoint to attempt compilation and report errors with enough info for debugging?

Sounds fine. My major point is just that App Builders should be able to fix/avoid this from within medic-conf.

> Docker Compose Updates to expose port 5984 and enable debug logging by default. Or provide a different yml for app builders to enable this by default?

I do think that App Builders would benefit from this development docker configuration. For bug investigations (like this one), but also for other failure pattern investigations. It would help build familiarity with the core. Is the docker image mostly used by app builders, is the right place to make that change in the [public docker docs](https://github.com/medic/medic-docs/blob/master/installation/public-docker-image-setup.md) or I can do this as an app services internal document.

**Comment by SCdF** [comment]
> > Docker Compose Updates to expose port 5984 and enable debug logging by default. Or provide a different yml for app builders to enable this by default?

> I do think that App Builders would benefit from this development docker configuration. For bug investigations (like this one), but also for other failure pattern investigations. It would help build familiarity with the core to have the same log level that devs have. Is the docker yml mostly used by app builders, such that I could make that change in the [public docker docs](https://github.com/medic/medic-docs/blob/master/installation/public-docker-image-setup.md) or I can do this as an app services internal location.

I think it would be cool to ship two compose files, one which is prod ready (possibly including [only showing prod ready releases](https://github.com/medic/cht-core/issues/6447)) and is the default, and another which [extends](https://docs.docker.com/compose/extends/#understand-the-extends-configuration) that file but makes changes for "dev" (all releases, debug logs, looser port exposure). I have toyed with this idea for core dev, but never got anything I liked

**Comment by SCdF** [comment]
> What about medic-conf validates the XML before uploading so we can catch and report useful errors before pushing the XML? For example, API could have an endpoint to attempt compilation and report errors with enough info for debugging?

This is a super good idea: IMO we should be providing apis in API for most all logic that medic-conf does, so it can be versioned and altered correctly against the actual server is runs against

**Comment by Marina-Kenf** [comment]
> http://localhost:5984/_utils
 
I have added the 5984 port but there is no way to assess because the localhost is no more available.
My docker is stucked here since more than 20 minutes.

![docker-not -running](https://user-images.githubusercontent.com/63068738/83495559-c20bb280-a4af-11ea-975a-c562b934a0eb.png)

**Comment by SCdF** [comment]
This log screenshot is not enough to determine what is going on. Please attach the entire log file. For example, can you tell higher up if haproxy started correctly?

**Comment by Marina-Kenf** [comment]
After issue #6456 (consequence of this one) is resolved, haproxy started correctly.
Current config is the default as the one causing the error has been wiped during the workaround.

But the topic still remains entire if this occurs again, as app builders does not have enough information to fix the issue.
> We should definitely improve our error reporting here: we could at least say _which_ XML file caused issues, which would make it easier to delete it or read it from CouchDB.

This would be nice.

**Comment by garethbowen** [comment]
I've raised [this issue](https://github.com/medic/medic-conf/issues/331) to add xform validation and more useful logging info.

This issue should now cover providing a dev version of the docker-compose.yml.

**Comment by garethbowen** [comment]
Delayed to 3.12.0 while we investigate a more holistic approach.

For now, the workaround is to modify the docker-compose file as suggested in [this comment](https://github.com/medic/cht-core/issues/6455#issuecomment-637047221).

**Comment by mrjones-plip** [comment]
I'm going to close this in favor of #7061. Let me know if you have any concerns with this!

@garethbowen  - I think we can use some of your ideas in your PR - but for now, I'll close it for you (again  - open to input if anyone thinks this is a bad idea!)
