### ISSUE TITLE
Rename configuration fields to be consistent with DHIS2 and make names localizable

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6457]
Current CHT/DHIS2 integration configuration uses terminology that is not entirely consistent with DHIS2. Excerpts from the documentation are below and the full documentation is [here](https://github.com/medic/medic-docs/blob/74c1e4cb20b1cc2e45d81de8181347a9264c4646/configuration/dhis-integration.md#example-configuration).

A few suggestions:
-  In `app_settings`, rename `guid` to `id`
- In `app_settings`, rename `label` to `translation_key`
- Make `translation_key` translatable

We might also consider changing `dhis` to `dhis2`, though who knows if there will ever be a DHIS3. 

For reference, [here](https://docs.dhis2.org/master/en/dhis2_developer_manual/web-api.html#sending-data-values) is DHIS2 documentation for sending data sets.

# App Settings

CHT Core....
```
{
  "dhisDataSets": [
    {
      "guid": "VMuFODsyWaO",
      "label": "MoH Monthly Report"
    }
  ],
}
```

From DHIS2, if you download metadata for Data Sets, it looks like this: 
```
"dataSets": [
    {
      "lastUpdated": "2020-06-01T17:48:22.355",
      "id": "Xa2mJ5ExpMP",
      "created": "2020-06-01T15:58:56.545",
      "name": "AAA-data set1",
      "validCompleteOnly": false,
      "dataElementDecoration": false,
      "publicAccess": "rw------",
....
```

# Contact document

```javascript
{
  "_id": "my_place",
  "type": "health_center",
  "dhis": {
    "orgUnit": "HJiPOcmziQA",
  }
}
```

# Targets.js

```javascript
module.export = [
  {
    id: 'births-this-month',
    type: 'count',
    icon: 'icon-infant',
    translation_key: 'targets.births.title',
    subtitle_translation_key: 'targets.this_month.subtitle',
    goal: -1,
    appliesTo: 'contacts',
    appliesToType: ['person'],
    appliesIf: contact => !!contact,
    date: (contact) => contact.contact.date_of_birth,
    dhis: {
      dataElement: 'kB0ZBFisE0e',
    }
  },
]
;
```

**Comment by garethbowen** [comment]
Instead of `name` can we use `translation_key`? That would make it consistent with other places we have translatable strings.

**Comment by michaelkohn** [comment]
Sure

**Comment by garethbowen** [comment]
Although I see the name is exported as well. What is the `name` used for in the export? Maybe we should have both an export name and a translation key?

**Comment by michaelkohn** [comment]
DHIS2 does not need the `name` of the Data Set when you are importing it, so I'm not 100% sure why `name` would be included in the export.

**Comment by garethbowen** [comment]
@kennsippell Do you know? Is it just a human readable string to make it easier to scan the file?

**Comment by kennsippell** [comment]
@garethbowen Where do you see `name` being exported? The `contact.name` is used in the admin/src/js/controller/export-dhis.js to create a list of "human readable" orgUnits. But I don't expect to see a name in the exported payload. Here is an [example payload](https://github.com/medic/cht-core/blob/master/api/tests/mocha/services/export/dhis.spec.js#L52).

Do you mean that the `label` is being exported? When using the "Human Readable" mode for DHIS2 exporting, the dataSet.guid is replaced with the dataSet.label. This label wasn't made to be a translation key in the MVP since 1) admin console doesn't support translations, and 2) it didn't seem necessary for the human readable export format (unsure if anybody even uses this).

I did purposefully just use `dhis` instead of `dhis2` incase there is eventually a dhis3 etc.

**Comment by garethbowen** [comment]
> 1) admin console doesn't support translations

Actually it does, for example, the DHIS2 export page is fully translated. We just don't necessarily ship all the admin console translations for all the supported languages out of the box.

> Where do you see name being exported?

I saw it in the description of this issue: "From DHIS2, if you download metadata for Data Sets, it looks like this:". It could be that the documentation is wrong?

**Comment by kennsippell** [comment]
@michaelkohn can confirm, but I think he is exporting a dataset via DHIS2. The CHT only supports the exporting of a dataValueSet.

**Comment by michaelkohn** [comment]
Correct. Currently the `label` field in the CHT is just what shows up in the dropdown of the Admin App.  Likewise, the `name` field in DHIS2 is what shows up in the dropdown in the Data Entry app. So we would be translating the contents of a drop down, NOT the field label. This value does not get sent to DHIS2.

<img width="363" alt="Screen Shot 2020-06-01 at 6 25 15 PM" src="https://user-images.githubusercontent.com/10096985/83464054-baabc100-a43d-11ea-93bf-169bf1005605.png">

![Screen Shot 2020-06-01 at 6 26 42 PM](https://user-images.githubusercontent.com/10096985/83464114-e333bb00-a43d-11ea-8ee4-99318666994e.png)

**Comment by michaelkohn** [comment]
> I saw it in the description of this issue: "From DHIS2, if you download metadata for Data Sets, it looks like this:". It could be that the documentation is wrong?

I included the DHIS2 metadata export so you could see what they call the `id` and `name` fields (what we are calling `guid` and `label`).

**Comment by garethbowen** [comment]
I've put this in 3.9.0 because changing the configuration schema after release would break backwards compatibility.

**Comment by SCdF** [comment]
Ready for AT in `6457-fix-dhis-config-schema`

**Comment by newtewt** [comment]
@garethbowen  The admin app doesn't seem to respect your selected language on your profile because none of it is translated or maybe I'm missing all the keys for Spanish. Adding a new translation_key for the DHIS dataset though shows the English translation in the drop down even though my users account is set to Spanish. 

![image](https://user-images.githubusercontent.com/10531066/83562813-3104fd80-a4e8-11ea-9892-1c8b4116d971.png)

**Comment by newtewt** [comment]
I'm also seeing an extra property when I download my app_settings. 

```
    "dhisDataSets": [
        {
            "id": "test1test2test4",
            "translation_key": "data.dhis",
            "$$hashKey": "object:1244"
        }
```

**Comment by newtewt** [comment]
Otherwise I think the changes for this are working ok. The export is occuring and using the updated values. 

As an aside I am confused how this works in general. I used our births-this-month example and see the target as my offline user but when exporting the value is 0 in the `dataValues`

**Comment by garethbowen** [comment]
> I'm also seeing an extra property when I download my app_settings.

I think that'll be unrelated to this change. I think what's happening is when rendering the dhisDataSets angular adds the $$hashKey for internal use, then at some point you've saved the config anywhere in the app management app which has saved the property inadvertently. Please raise a separate issue for this.

**Comment by garethbowen** [comment]
Merged and backported to `3.9.x`. I've also merged the medic-docs PR but not the beta docs site one as it's waiting for review.

**Comment by michaelkohn** [comment]
FWIW.... I'm seeing some inconsistencies in how we name properties and deal with translation keys.

---

#### In some of our documentation I notice that the `property` is a normal field name like "**title**" and the `type` is of `translation key`.  See [tasks.js](https://docs.communityhealthtoolkit.org/beta/apps/reference/tasks/#tasksjs)

![Screen Shot 2020-06-03 at 10 19 56 AM](https://user-images.githubusercontent.com/10096985/83655340-50edfd00-a58c-11ea-8921-94c97cc152b7.png)

---
#### Sometimes I see that the `property` is called "**translation_key**" with a `type` of `translation key`. See [targets.js](https://docs.communityhealthtoolkit.org/beta/apps/reference/targets/#targetsjs)

![Screen Shot 2020-06-03 at 10 21 38 AM](https://user-images.githubusercontent.com/10096985/83655453-724ee900-a58c-11ea-887a-132e78b188ef.png)

---
#### Sometimes the `property` is a normal field name but with no `type` column. See [hierarchy](https://docs.communityhealthtoolkit.org/beta/apps/reference/hierarchy/#app_settingsjson-contact_types).

![Screen Shot 2020-06-03 at 10 22 35 AM](https://user-images.githubusercontent.com/10096985/83655644-a6c2a500-a58c-11ea-8c98-218fd3201e55.png)
---
#### Sometimes the `property` is called "**translation_key**" with a type of `string`.  See [JSON forms](https://docs.communityhealthtoolkit.org/beta/apps/reference/json-forms/#app_settingsjson-forms)

![Screen Shot 2020-06-03 at 10 23 55 AM](https://user-images.githubusercontent.com/10096985/83655789-c528a080-a58c-11ea-86ac-c11e75f09e46.png)

**Comment by garethbowen** [comment]
Thanks for flagging that! The property names are inconsistent for historical reasons and can't be changed without breaking backwards compatibility so I'm ignoring those for now. I think the type should be "string" because "translation_key" is a Medic convention. The fact that it's a translation key should be explained in the description. @abbyad What do you think?

**Comment by michaelkohn** [comment]
FWIW... my preference is that it should be something like this:

|Property|Type|Description|Required|
|---|---|---|---|
|`name`|`string`|Translation key for the name of the data set as displayed in the UI. e.g. `dhis.dataset.name.moh515`|Yes|
