### ISSUE TITLE
Remove redirect from log out.

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6479]
**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as admin on the admin portal (https://gamma.dev.medicmobile.org/admin/#/users)
2. Log out and try to log in as a restricted user. 
3. The user is redirected to the same admin page , ie https://gamma.dev.medicmobile.org/admin/#/users, and since the restricted user does not have permissions to access the admin page, I get an error.
`{"error":"forbidden","reason":"Insufficient privileges"}`

**Expected behaviour**
Log out should redirect to the main login https://gamma.dev.medicmobile.org/medic/login) regardless of where the user was (web app or admin portal) without redirect

**Logs**
![image](https://user-images.githubusercontent.com/6979995/84199435-42a66080-aaf9-11ea-8220-20e9a331fbb8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/84199255-f0fdd600-aaf8-11ea-9aa7-2c33a7bb9041.png)

**Environment**
- Instance: gamma.dev, master
- Browser: Firefox, Chrome
- Client platform:  MacOS
- App:  webapp, admin
- Version:3.9

**Comment by garethbowen** [comment]
Logging out from the webapp also adds the current URL as a redirect, which has a similar problem if you then log in as someone with different permissions. I also wonder if we're leaking information when we do this, if someone else has access to the device.

I propose we don't append the current URL on logout from app management or the webapp. This will solve the immediate problem. The bug will still occur if you end up on the login page due to session timeout and then log in as someone different but that's probably ok.

The other solution is to also include the initial username and ignore the redirect URL if the new username doesn't match, but I think this is overkill for this bug.

**Comment by garethbowen** [comment]
Low priority because most devices only have one user, and it's recoverable if they do.

**Comment by dacar1988** [comment]
Hi @garethbowen! Can I work on this issue?

**Comment by garethbowen** [comment]
@dacar1988 Yes please! Any issues with the "help wanted" label are good candidates for contributions. Our [contributions doc](https://github.com/medic/cht-core/blob/master/CONTRIBUTING.md) has more info about how to contribute.

**Comment by dacar1988** [comment]
Hi @garethbowen and @ngaruko! I opened this draft PR: https://github.com/medic/cht-core/pull/6689
Can you please have a look?
As I say into the PR description, I could not run tests present in the branch build because I do not have permissions to create branches.
Thank you very much.

**Comment by garethbowen** [comment]
Ready for AT in contributor's repo: `dacar1988:6479-remove-redirect-from-log-out`

**Comment by mrjones-plip** [comment]
Yay!  So happy to see this ticket being worked on: yay for external developers (Thanks @dacar1988!) and yay I hit this problem often when testing.  Thanks all!

**Comment by dacar1988** [comment]
Thank you. I am happy it is useful.

**Comment by dianabarsan** [comment]
This solution has been migrated to work with Angular, and now should be AT-ed on `dacar1988:6479-remove-redirect-from-log-out-migration-to-angular-10`.

**Comment by ngaruko** [comment]
LGTM.
Tested on `dacar1988:6479-remove-redirect-from-log-out-migration-to-angular-10` - 
When a user logs out as admin from the admin portal, and logs in as a restricted user, the user is redirected to a functional app page.
back to you @dianabarsan and @dacar1988 to merge.
