### ISSUE TITLE
Allow enough space to show list of forms in Reports Filter. 

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#6481]
**Is your feature request related to a problem? Please describe.**
It is not convenient to filter Form Types on Reports tab in Web App because there's no enough space for form names on drop down. 

![image](https://user-images.githubusercontent.com/6102813/84241055-a68f5000-ab1e-11ea-9948-fd8f04597a5f.png)

**Describe the solution you'd like**
I'd like to see the full name for forms when I'm selecting form types from the drop down. 

**Describe alternatives you've considered**
Expand the space available for form filter at least to fit form name or Wrap the form name. 

**Additional context**
Filter appears showing full form name in one particular mobile resolution only.

**Comment by yrimal** [comment]
Given that, there's similar issue in other filter as well, I think better would be to expand space for drop-down and allow line wrap as well. 

![image](https://user-images.githubusercontent.com/6102813/84745399-38da9c80-afd4-11ea-9dab-1de494de2462.png)

**Comment by garethbowen** [comment]
Yes, the same fix should be applied to all filters on all tabs.

**Comment by garethbowen** [comment]
Ready for AT on `6481-report-filters-dropdown-padding`. Ensure that all dropdowns work as expected on desktop and mobile, and that long menu items are wrapped.

**Comment by ngaruko** [comment]
LGTM
Also tested filtering by place and on mobile phone
![image](https://user-images.githubusercontent.com/6979995/86204787-71759b00-bbbc-11ea-9a76-fa6e4a9ac337.png). 
![image](https://user-images.githubusercontent.com/6979995/86204812-84886b00-bbbc-11ea-8dbf-7c8db1af688e.png)
