### ISSUE TITLE
Migrate all medic-docs references

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#6489]
**Describe the improvement you'd like**
All references to `medic-docs` in comments, readmes, and templates should be reviewed and migrated to the relevant URL in [docs.communityhealthtoolkit.org](https://docs.communityhealthtoolkit.org/)

**Comment by ronna** [comment]
Hi @abbyad 
 searching through the repo t I found  cht-docs\content\en\apps\examples\anc\anc-reference-app-overview.pdf 
page 8: Forms Documentation link pointing to: (https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#form-properties)

**Comment by ronna** [comment]
@abbyad 

I have started working on the issue here: https://github.com/ronna/cht-core/tree/6489-Migrate-all-medic-docs-references- Please confirm if I am on the right path. I have edited a couple of files so far: https://github.com/ronna/cht-core/commit/56bb51d75ed6a98a7eefa0caaa669d16daee69fb

**Comment by abbyad** [comment]
It is definitely moving in the right direction!

You may find it helpful at this point to create a [draft pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). It will make it easier to make some comments on file changes, even if it is not yet complete.

Nice work!

**Comment by ronna** [comment]
@abbyad I have created the draft pull request

**Comment by abbyad** [comment]
Closing now that #6682 has been merged. Nice work @ronna on your first contribution!!
