### ISSUE TITLE
Guard against xpath string concatenation regression

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6490]
**Describe the issue**
We use `medic/openrosa-xpath-evaluator` to evaluate xpath in Enketo forms, and one non-standard feature is that you can concatenate string values with either the `+` operator or the `concat()` function. At some point we're going to upgrade to a version that deprecates use of the `+` operator but because it's a dependency of a dependency it's hard to know when that'll happen. Because the `+` operator is used widely for different values it's difficult to work out if we're using it for concatenation at all.

**Describe the improvement you'd like**
1. Write a test which runs against the version of `openrosa-xpath-evaluator` so we will be notified when it fails and can document it correctly in the release notes.
2. Document the deprecation of the `+` operator so app builders don't use it in future.
3. Investigate writing a test in the [configuration test harness](https://github.com/medic/medic-conf-test-harness) to detect configurations that use `+`.

**Describe alternatives you've considered**
- Sticking on an old version of Enketo forever.
- Patching the official version with some bespoke code.

**Comment by garethbowen** [comment]
@njogz Can this issue be closed now?

**Comment by njogz** [comment]
@garethbowen yes it can be closed.
