### ISSUE TITLE
Exporting App Settings seems to be adding extra elements for configured sms forms. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6491]
**Describe the bug**
Uploading the standard config which contains SMS forms. Then using the admin page to backup the app settings. Shows a bunch of extra elements in the config. Starting at 0 and going to the count of number of sms forms configured. 

**To Reproduce**
1. Upload standard config
2. Go to the admin page > backup app code > Download current settings.  
3. Review the JSON for app_Settings. 

**Expected behavior**
We should only show sms forms in there expected location. 

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: linux
- App: admin

- Version: 3.9

**Additional context**
See attached app_settings.json for example of the improper output. 
 

[app_settings.txt](https://github.com/medic/cht-core/files/4781106/app_settings.txt)

**Comment by garethbowen** [comment]
@newtewt To help us narrow this down could you check in the database directly using...

1. fauton/curl for the doc with id `settings`, and
2. the GET settings API

It's be useful to know which of those are correct and which have the incorrect format.

**Comment by newtewt** [comment]
@garethbowen 

1. The doc in couchdb viewed from fauxton shows the extra.
2. Can I hit the API with a curl or something else?

**Comment by garethbowen** [comment]
Thanks for that. Yes you can hit the API with a curl but there's no need - if it's in the DB then it will (almost certainly) be returned from the API.

This also means it's not the export that's the problem because it's just spitting out what's in the DB but somewhere else. Can you think of anything else you might've done to get to this point? For example, how did you upload the standard config?

**Comment by latin-panda** [comment]
Hi @newtewt 
I uploaded the standard app settings and made the backup (also checked the settings in the DB) but looks like it's okay (see attachment) 
[app_settings.json.1594623370432.txt](https://github.com/medic/cht-core/files/4911366/app_settings.json.1594623370432.txt)
Do you remember any other step or additional information that we can use to reproduce the issue? Thanks!

**Comment by newtewt** [comment]
@latin-panda  I tried this morning to recreate the issue on 3.9. I cannot.  I don't believe there were any other steps.  I'm going to close this and if we notice it again we can reopen.
