### ISSUE TITLE
Touch area of items in the hamburger menu should be larger

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-core#6492]
**What feature do you want to improve?**
The touch area of the menu items in the hamburger menu is 30px tall making it likely for users to accidentally press the wrong item. Best practice would me to make the line items 45px tall.

<img width="265" alt="Screen Shot 2020-06-16 at 10 04 41 AM" src="https://user-images.githubusercontent.com/59581790/84805587-577f6a00-afb9-11ea-8e04-082416c3c3ee.png">

**Comment by garethbowen** [comment]
This is small and low risk. Doing it now.

**Comment by garethbowen** [comment]
Ready for AT on `6492-increase-dropdown-clickable-area`

**Comment by ngaruko** [comment]
![image](https://user-images.githubusercontent.com/6979995/85656097-78a43100-b704-11ea-968a-70560572903f.png)

![image](https://user-images.githubusercontent.com/6979995/85656201-9a9db380-b704-11ea-950e-f47448ff4d61.png)

To 42px
![image](https://user-images.githubusercontent.com/6979995/85656943-80b0a080-b705-11ea-80b0-30774ddccd47.png)
 Should that be enough @n-orlowski ?

**Comment by n-orlowski** [comment]
@ngaruko should be fine thanks!

**Comment by garethbowen** [comment]
Merged.
