### ISSUE TITLE
Guided tour erratic when user has no access to any tab

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6502]
**To Reproduce**
1. Create a user with no access to tabs, say `Data Entry` access level 
2. Login as the user created
3. A `Select Tour` modal is displayed as shown in the screenshot below.

**Expected behavior**
The tour should be disabled in cases like these

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/85078844-7d0aae80-b219-11ea-96e9-5fa4c504cbdb.png)

**Environment**
- Instance: localhost
- Browser:  Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.9

**Additional context**
Not a practical use case scenario, thus low priority.

**Comment by jimbo108** [comment]
I've fixed this in my local branch -- still need to write a unit test and create PR.  Aiming to do so in the next 3 days.

**Comment by jimbo108** [comment]
Created PR #6539 to address this issue.

**Comment by garethbowen** [comment]
Ready for AT. This was developed by an external contributor so it's not available on the market but you can deploy using a dev environment on the `jimbo108` fork, `master` branch.

**Comment by ngaruko** [comment]
Looks Ok. The tour does not show for users with no access to the app tabs. However, there is a small glitch in the behaviour: the tour pops ups again after being dismissed. Not sure if we really should spend much time of this feature  @garethbowen ?

[tour.mov.zip](https://github.com/medic/cht-core/files/4951581/tour.mov.zip)

**Comment by garethbowen** [comment]
I think that's unrelated to this. I think that's happening because when you select the tour it adds a `tour=true` parameter to the URL. Then when you reload that parameter is used to kick off the tour again. Can you test that in `master` and make sure the bug exists there too? If it is, please raise a separate issue for that.

**Comment by ngaruko** [comment]
@garethbowen Agree - Will raise a different issue

**Comment by garethbowen** [comment]
Merged. Thanks @jimbo108 !!
