### ISSUE TITLE
add entries to .gitignore so it ignores medic-conf files

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6510]
**Describe the issue**
By definition, you need to run `medic-conf` in the directory where you CHT configs are. This means it puts additional files into this repo in `config/default`.  These files, in turn, get flagged for being added when git runs and notices new, untracked files.

**Describe the improvement you'd like**
Add entries to `.gitignore` that excludes files from `cht-core` but doesn't prevent key components to a config from being edited or added.

**Describe alternatives you've considered**
You can use either `git clean` to remove the untracked files or a [global git ignore](https://stackoverflow.com/questions/7335420/global-git-ignore), but these are kludgy and are likely to miss files we hadn't thought of.

**Comment by mrjones-plip** [comment]
For example, I found these in my `config/default` directory and saw I could safely delete them with `git clean f`:

```
config/default/.snapshots/                 
config/default/forms/contact/clinic-create.xlsx
config/default/forms/contact/clinic-edit.xlsx                         
config/default/forms/contact/district_hospital-create.xlsx            
config/default/forms/contact/district_hospital-edit.xlsx
config/default/forms/contact/health_center-create.xlsx
config/default/forms/contact/health_center-edit.xlsx
config/default/json_docs/                               
config/default/upload-docs.1592857574355.log.json       
config/default/users.csv                                            
```

**Comment by newtewt** [comment]
The list provided above we should be able to exclude.  
```
config/default/.snapshots/                 
config/default/json_docs/                               
config/default/upload-docs.1592857574355.log.json       
config/default/users.csv  
```
Snapshots are for detecting changes based on your system and the configured system. 
Json docs and users.csv are generated by csv-to-docs and shouldn't be committed. The csv folder that contains the data represented as csvs should be committed when changed. 
The log can also be excluded. 

The xlsx files shouldn't be altered by medic-conf. Have you done anything to them or do you have more detail on what commands you ran?

I'll have a PR shortly for the above items.

**Comment by newtewt** [comment]
Ahh I see now why those xlsx were created. Default config is creating them using the generic `PLACE_TYPE-edit.xlsx`. I don't think we should exclude these in gitignore as they could be changed and committed. I'm also pretty sure that medic-conf will create them every time you run the `convert-contact-forms` so just committing them won't work either.

**Comment by mrjones-plip** [comment]
Yeah, @newtewt  - I thought some of those we might not be able to safely add to `.gitignore` based on what I thought might be happening.  Thanks for confirming! Even we can't add them all, some will be better.

**Comment by latin-panda** [comment]
Closing this one as it got resolved in https://github.com/medic/cht-core/pull/6512, PR is already merged.
