### ISSUE TITLE
Ability to generate a downloadable file on CHT

### ISSUE THREAD

**Issue by antonykhaemba** [medic/cht-core#6511]
**Is your feature request related to a problem? Please describe.**
As part of Covid-19 Surveillance integrated system, CHT tool is used as the primary data collection tool. Rapid Response Team (RRT) use CHT tool to register suspected cases, collect samples and fill the case investigation and lab request form. Once a case investigation is submitted, the report is pushed to KenyaEMR. According to the MOH guidelines lab samples are supposed to be sent to the testing lab accompanied with a `manifest`.  A manifest is a list which has names of suspected cases whose samples have been collected and additional details that are captured on the case investigation and lab request form. 
Currently all samples are taken to central point in a County and then RRT's are expected to compile manually a manifest list that will accompany samples. Many RRT and Counties are experiencing challenges in creating the manual manifest and it is taking long for the teams to create manifests which is delaying the process of sending samples to the testing labs. 

**Describe the solution you'd like**
Generate a downloadable file on CHT that can be shared with the testing lab, downloadable file can be in form of an excel sheet or pdf.

**Describe alternatives you've considered**

**Additional context**
Variables captured on the manifest; the variables have been highlighted in red- https://docs.google.com/spreadsheets/d/1WRXxlb-hKRucNK9niyGeDbL1C_rvlEl-Qfjsm7t7CTY/edit#gid=214645271

cc @PhilipNgari @derickl @michaelkohn @kitsao

**Comment by garethbowen** [comment]
We have [an API](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv2exportreports) to export a CSV from the CHT containing reports that match given search criteria. If that contains everything you need you could start by exporting that and then write a script which converts it to whatever format you like. Would that work?

**Comment by kitsao** [comment]
Makes sense @garethbowen. Here's a possible solution @antonykhaemba .

1. Configure the `manifest` as a form that would be triggered as a task upon submission of a `case_investigation` report that has a lab section completed. 
2. The work of the `manifest` is to collate the details required and the work of the rapid responder of contact tracer would be to submit it.
3. The user filters reports of `type = 'manifest'`, exports and shares that with the coordinating office. See sample attached.

[reports-202006241054.xlsx](https://github.com/medic/cht-core/files/4824970/reports-202006241054.xlsx)

**Comment by MaxDiz** [comment]
@antonykhaemba Checking back to see if this issue has been solved with current functionality and can be closed

**Comment by antonykhaemba** [comment]
Not yet, we are still discussing with the Apps team on how well this can be handled on CHT @MaxDiz

**Comment by antonykhaemba** [comment]
Closing this for now.
