### ISSUE TITLE
Run Scalability Suite On a Server against a Server. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6513]
**Describe the issue**
Currently we run our scalability suite against gamma.dev from a QA's local machine. There are so many variables with this and in an attempt to cut down on some. We'd want to start running these on a server(AWS) against a test instance. This will allow us to control the machine executing and the machine running against. Hopefully to have the same set of variables each release.

**Describe the improvement you'd like**
A few things are needed for this to happen. My initial thought is this should likely be two machines. One hosting our app and the other executing. That could be an improvement to the process down the road. Thought being running on the same machine is consuming extra resources. I also feel like steps 4-7 could probably be dockerized.

1. Using github actions. I want to spin up an AWS machine.  Will require credentials to do this. Hopefully restricted so they cannot make any changes to any other machines. Likely using the self hosting method.
2. Clone our `cht-core` repo to this machine. 
3. Install our software on this machine and set a branch. @Hareet  mentioned piping the config to the ec2 init scripts
4. Run Medic-conf to apply standard config. 
5. Seed our standard config data using medic-conf.
6. Install Jmeter 
6. Execute Scalability tests with Jmeter.
7. Store the results somewhere. I assume we could use a directory where our UI tests are storing their results in AWS. EX: `      S3_PATH=s3://medic-e2e/BUILD_$TRAVIS_BUILD_NUMBER/JOB_$TRAVIS_JOB_NUMBER` Storing the results is used for comparing previous runs against older versions.
8. Tear it all down. 

**Describe alternatives you've considered**
We could use a paid solution like blazemeter to run the tests but we'd still have to setup an instance with our software, data, config. The other option which we have been doing is described in the issue portion.

**Comment by Hareet** [comment]
Let's get Steps 1-3 automated and running then we'll wrap up 4-8.

@nomulex 
We'll need to create an IAM user that is limited to starting/stopping 1 AWS Instance at a specific time. Try to make that restricted to a Spot Fleet of 1 instance if possible. Once you have tested those credentials, you can hand them over to Nick.

@newtewt You can use the self-hosting scripts found in medic-infrastructure to bootstrap dependencies and get cht-core up and running. An issue I for-see is related to `set a branch`. You can have the init scripts point to the self-hosting setup, but setting a custom branch means you'll have to add logic that waits for couchdb to come up before CLI-ing horti to update the application. You could also save the state of the instance post self-hosting setup and continually spin that saved instance up, but it still leads to you having to deal with the horti CLI to update the application to a specific branch.

There's good documentation on bootstrapping AWS ec2 with init-scripts or saving to an AMI after you manually do install everything. I would prefer the former.

**Comment by nomulex** [comment]
I have created the credentials to create a spot fleet and sent them to @newtewt on slack.

**Comment by newtewt** [comment]
@Hareet @nomulex  if I request a spot instance using and specify the `prepare.sh` file in user-data. I believe it would fail because the `docker-compose.yml` is not copied as well. Am I missing a step?

**Comment by nomulex** [comment]
@newtewt  would it make sense to make two requests one to create the instance etc and one to  push the compose file and any other files you need

**Comment by newtewt** [comment]
@nomulex  I think that's going to be the solution. I was hoping to use the `user-data` option on the request so it processes that script at launch but without moving it around I'm not sure that it's possible.

**Comment by nomulex** [comment]
Removing this from the SRE dashboard since all necessary access was granted.

**Comment by garethbowen** [comment]
@newtewt I think this can be closed now, right?

**Comment by newtewt** [comment]
@garethbowen need an approval and a final review now that this has become a proper PR.

https://github.com/medic/cht-core/pull/6558

**Comment by newtewt** [comment]
Will also need medic-conf to be released so the force option is available on the npm installed version.

**Comment by garethbowen** [comment]
Good point. Approved.
