### ISSUE TITLE
Improve SMS reminders so they can be configured to be sent to places anywhere in the hierarchy

### ISSUE THREAD

**Issue by ashish-medic** [medic/cht-core#6516]
**What feature do you want to improve?**

Currently, this feature sends reminders only to all the clinic level contact person. Trying out `"recipient": "health_center"` didn't work as expected. We have `recipient` option for registrations,patient_reports, and notifications but it looks like this option is missing for the reminder.

**Describe the improvement you'd like**
 The option of selecting the recipient so that this feature can send to SMS reminder to any configurable hierarchy.   

**Describe alternatives you've considered**
Adding "recipient" for reminder like others configuration 

**Additional context**
Here is the example I have used for testing it out the workflow where I need to send daily SMS at 5:30 for health center contact person, the reminder is sent to people at the clinic level even though  "recipient": "health_center" is added.
```
"reminders": [
    {
      "form": "hf_daily_report",
      "text_expression": "at 5:30 pm on Sunday",
      "cron": "",
      "mute_after_form_for": "",
      "message": "Don't forget to submit daily report",
      "recipient": "health_center"
    },
    {
      "form": "hf_daily_report",
      "text_expression": "at 5:30 pm on Monday",
      "cron": "",
      "mute_after_form_for": "",
      "message": "Don't forget to submit daily report",
      "recipient": "health_center"
    }
  ],
```

**Comment by MaxDiz** [comment]
Hi @ashish-medic to clarify, you're looking for something similar to this for "Reminder", correct?

<img width="802" alt="Screen Shot 2020-06-29 at 10 34 46 AM" src="https://user-images.githubusercontent.com/46463417/86026537-2c533c80-b9f5-11ea-99da-db77f9e9e501.png">

**Comment by MaxDiz** [comment]
May be worth fixing this issue at the same time: https://github.com/medic/cht-core/issues/3233

**Comment by ashish-medic** [comment]
@MaxDiz yes that's something similar I was looking for. But, in the case of "reminder" when "recipient": "health_center" then SMS  reminders should go to all the persons at the health facility, and when the recipient is `clinic` then all the persona at the clinic level should get the reminder.

**Comment by MaxDiz** [comment]
potential add to v3.10 for covid response. Relevant conversation: https://medic.slack.com/archives/C3TJFFKK7/p1593592078014500

**Comment by garethbowen** [comment]
I've had a look at the implementation of reminders. The `recipient` configuration is ignored completely, and instead the recipient is hard coded to `reporting_unit`, which explains what you're finding. The reminders have been set up to always SMS to "leaf nodes", which is the lowest level of places, in this case clinics. We should allow people to configure the contact type or user role that we want to send a message to. And, obviously, we should document this feature.

With regards to scheduling it's very late in the 3.10.0 development cycle to add a new improvement and adding it now will delay release. Is this an urgent request that's worth delaying the other 3.10.0 features for?

As this change is sentinel only we could consider adding it to 3.11.0. This is my preferred solution.

**Comment by ashish-medic** [comment]
Bringing the slack conversation back here:
- This feature is one of the necessary piece for new workflow for MoH - Nepal which includes DHIS2 integration between CHT and has data points for COVID related information like

  - Number of clients in COVID Clinic
  - Number of isolation beds available
  - Number of people in isolation - COVID Suspected
  - Number of people in isolation - COVID Confirmed
- This feature acts as Daily SMS reminders to Health Facility contact person so that they don't miss out on the HF level daily reporting.
So, the feature is part of a new workflow with CHT and DHIS2 integration which including forms having COVID data attached to it. 
It would be helpful if we can deliver this as a bundle ie. SMS reminder, and DHIS2 forms. As for scheduling this work, it would be helpful if its schedule for 3.10.0 :)

**Comment by MaxDiz** [comment]
Thanks for the additional info @ashish-medic . Based on your description, I think the daily reminders can wait until v3.11. I realize it's not an optimized workflow, but the critical health reporting information from DHIS2 would still be available for facility personnel to check. 

As a temporary alternative, perhaps we could look into:
1) educating facility personal to the availability and value of the DHIS2 information
2) implementing a simple RapidPro workflow that triggers at a specific time everyday and asks facility personnel to confirm that they have viewed the daily DHIS2 report

**Comment by ashish-medic** [comment]
@MaxDiz those are very plausible ideas, but one of the strengths of CHT is a task, target, and reminder/schedule, and using these features helps users to increase the reporting rates. This workflow is about reporting/submitting Dhi2 forms in a timely manner with COVID response in mind. This feature will be highly advantageous for MoH Nepal COVID response.

Talking about RapidPro workflow there is a significant effort required to upgrade this project to v3.9 to use rapid pro and then again upgrade to v3.11. Data privacy concerns that have not yet been vetted with the partner and the operation cost of using RapidPro is yet to decided by the deployemnt and partnership team

**Comment by nnbhandari1** [comment]
@ashish-medic Considering the associated cost, I do not think an SMS reminder would be necessary atm. However, it would be a great function if the SMS was free. 
Can the app notify the user on a daily basis?

**Comment by nnbhandari1** [comment]
@ashish-medic, @ranjuts , and I had a quick discussion regarding the SMS reminder feature. Although the feature is very helpful, we concluded, that given the time crunch and the current requirement, it would be most helpful to launch the app at the earliest possible. We can upgrade our system later on in time to give an added experience to our users. 

-

**Comment by MaxDiz** [comment]
adding to v3.11 based on above conversation

**Comment by garethbowen** [comment]
I think this is reasonably safe and the initial dev work is out of the way so I'm bumping it up to 3.10.0.

**Comment by dianabarsan** [comment]
Ready for AT on `6516-remind-anyone`. 
Documentation PR: https://github.com/medic/cht-docs/pull/216

**Comment by ngaruko** [comment]
LGTM - Pinging @ashish-medic to double check that the behaviour matches what is required?

**Comment by ashish-medic** [comment]
The following code is working as expected. LGTM 
```
  "reminders": [
    {
      "form": "hf_daily_report",
      "text_expression": "every 5 mins",
      "cron": "",
      "mute_after_form_for": "",
      "message": "Don't forget to submit daily report",
      "contact_types": ["health_center ]
    }
  ],
```

**Comment by ngaruko** [comment]
Thanks @ashish-medic

**Comment by garethbowen** [comment]
Code and documentation merged.
