### ISSUE TITLE
Upgrading doesn't apply replication configuration which means `users-meta` is empty

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6519]
**Describe the bug**

In #4898 (3.5.0) we moved feedback and telemetry docs to being stored in the users meta database for performance reasons. This also included a new configuration option for replication which allowed users to set up replications from one db to another based on a configured cron ([documentation](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/replication/)). This was set up to be a generic reusable configuration for replicating from any db to any other db.

Later on we realised it wasn't working because the configuration wasn't included by default which was patched in #6147 (3.9.0) so the default config included a replication config.  

We also progressively made the replication code more specific so it's only really useful for replicating `medic-user-{username}-meta` dbs to the `medic-users-meta` db (eg: we added filtering so we only replicate feedback and telemetry docs). This means the generic configurable component isn't actually useful.

Now that you know the history, here's the bug: projects that don't have replications configured don't replicate docs into the `medic-users-meta` db which breaks the expectations of the analytics, monitoring, and exporting code.

**To Reproduce**
1. Push a configuration without replications configured
2. Log in as a restricted user and generate feedback docs using the hamburger menu item
3. Force your meta db to sync (takes 30 minutes but can be forced on the `/testing` page)
4. Find the doc in your user's meta db on CouchDB
5. Wait 24 hours

**Expected behavior**
The doc should eventually replicate to the `medic-users-meta` db. It's ok if this takes up to 24 hours to go.

**Logs**
None.

**Screenshots**
None.

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: sentinel
- Version: 3.9.0

**Additional context**
The workaround is to configure the replication, as in the `/config/default/app_settings.json`

**Comment by garethbowen** [comment]
There are multiple solutions to this problem. Initially I was thinking that we should include a default configuration in code which would apply if the app settings were undefined. However, because this code is now only useful for the meta data replication which we rely on working I think we should just hardcode this replication and remove the config option altogether.

**Comment by garethbowen** [comment]
@dianabarsan @SCdF I'm curious what you think about my proposed solution. I also think we should include this in 3.10.0 so it just works out of the box.

**Comment by dianabarsan** [comment]
I'm ok with hard-coding and dropping the configuration altogether!

**Comment by SCdF** [comment]
Agree, just hard code it.

**Comment by garethbowen** [comment]
Ready for AT in `6519-hardcode-users-meta-replication`. The replication steps above should be enough to test this, but ensure the `app_settings.replications` configuration is empty first to prove that it's not longer used.

There's an associated docs PR here: https://github.com/medic/cht-docs/pull/200

**Comment by brad1905** [comment]
Working as expected, verified docs replicated to the medic-users-meta db

**Comment by garethbowen** [comment]
Merged!
