### ISSUE TITLE
Work out definitively how CouchDB authentication maintains fresh authentication tokens

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6528]
There has been some confusion recently about exactly how our authentication tokens are maintained, and what users need to do to maintain them.

We use CouchDB authentication. In production systems we set the auth timeout to 1 year. This means that when you call `_session` and authenticate the token you get back is valid for one year (provided you don't invalid it and all tokens for that server by changing CouchDB's secret key).

The confusion lies in how these tokens get refreshed. One partner has come back to us and noted that users are being logged out exactly one year after they were first created, which implies they are never triggering the creation of fresher tokens for some reason.

Specifically, what interaction with CouchDB will result in this timeout being extended? For example, does it happen when users refresh the app? Or when any background synchronisation happens? Or only if they explicitly login again?

We should work this out, document it correctly, and if it's "wrong" (ie the product team would expect it to happen at a certain time and it isn't) fix it.

Tasks:
 - [x] work out how authentication freshness works with CouchDB
 - [x] work out if auth is working correctly inside the CHT ecosystem
 - [ ] add some kind of automated test so we notice in the future if we accidentally erase the headers required for this to work
 - ~~work out the cause of issues our partners are having~~ this should be done in specific partner tickets

**Comment by SCdF** [comment]
This conversation has some more internal details: https://medic.slack.com/archives/CEQTMKFT8/p1594192795003500

**Comment by SCdF** [comment]
This was brought up in the CouchDB slack by @nomulex. The gist is that how the code works right now means that any interaction with CouchDB in the _last 90% of the session time_ should result in the session being regenerated.

So if the timeout is set to 10 minutes, then as long as the device syncs somewhere inside 1:00->9:59 it should result in their session being extended by another 10 minutes.

We should make sure this is what is happening in the CHT.

**Comment by SCdF** [comment]
The partner currently has 3.5.0, so this was tested on this build and 3.9.0 (latest release at the time). Timeout was set to `600`, so 10 minutes.

3.5.0
 - sync, offline for 11minutes, online, sync. Expected: logged out. Result: success: unknown error on sync*, logged out on reload
 - sync, online for 9 minutes, continually sync for 2 min or until it fails. Expected: say logged in. Result: success
 - sync, online for 7:30 minutes, sync, offline for 7:30 minutes, online, sync. Expected: stay logged in. Result: success
 - sync, online for >10min, sync. Expected: stayed logged in. Result: success

3.9.0
 - TODO (but it's unlikely that it will be different)

*3.5.0 didn't understand that this was a logout.

**Comment by SCdF** [comment]
Worth mentioning that this reupping mechanism is done via the `set-cookie` header, which CouchDB will return in the response when it considers it appropriate:

![image](https://user-images.githubusercontent.com/583851/87426534-353c3480-c5d7-11ea-924d-fb1fa2f96cb2.png)

This doesn't appear to be the case right now (as noted in the screenshot), but there is potential in the future for us to lose this header accidentally as we add more manual work into the API layer and run out of direct forwards.

We should write some tests to make sure if we mess this up in the future we notice. I've added a TODO to the top of this ticket so we don't forget.

**Comment by Patrickyk** [comment]
We have had spontaneous logouts from our 3.6 implementation . Normally after pushing updates  and a few users  are logged out every two weeks .
If the token is unchanged and is not expired are there other factors that can cause it to become invalid ?

**Comment by Hareet** [comment]
https://calnetweb.berkeley.edu/calnet-technologists/incommon-sectigo-certificate-service/addtrust-external-root-expiration-may-2020

> Devices that received security updates after mid 2015 should have the modern USERTrust RSA Certification Authority root certificate (valid until Jan 2038) in their operating system or browser truststores and should be largely unaffected.

> Legacy devices that have not received updates to support newer roots will also likely be missing other essential security updates and support for standards required by the modern Internet. We strongly encourage decommissioning these devices if their software cannot be upgraded.

Our legacy devices fall into `Condition 1`:
> The client is too old and does not have the USERTrust RSA Certification Authority root in its operating system or vendor managed truststore.

Reading through the link, it looks like our only option is to create `Trust Chain Path C`:
> Conditions 1 and 2 may be addressed by configuring the server to send Trust Chain C.

> AAA Certificate Services [Root] (Exp: Dec 31, 2028)
USERTrust RSA Certification Authority [Intermediate 2] (Exp: Dec 31, 2028)
InCommon RSA Server CA [Intermediate 1] (Exp: Oct 5, 2024)
End Entity [Leaf Certificate]

> Certificates issued by the UC Berkeley Authority from April 30, 2020 through InCommon (Sectigo) will include a link to download Trust Chain C.  We encourage you to use Trust Chain B unless you specifically need Trust Chain C for legacy device compatibility or to work around broken client issues.

@SCdF I think we can do what you were saying on the call. We need to get a new certificate from someone who can provide Trust Chain C.

**Comment by mrjones-plip** [comment]
It sounds like @Hareet has a good fix re root certs (and is certainly WAY more in the know about cht-core than me), but @SCdF  - I know that HAProxy can be configured to log both egress and ingress headers if we're concerned about checking historically what's happening on that instance. Unsurprisingly, Hareet will know more about this and our default logging config too ;)

**Comment by iesmail-znz** [comment]
@SCdF , I tried all 4 scenarios on my testing instance running version 3.5.0, and my results match yours.

**Comment by SCdF** [comment]
@Patrickyk thanks for this additional data point! I'm not sure these issues are related, but it's certainly weird and in the same ballpark. Your issue is even weirder though honestly: updates are pushed via replication (sync) which in theory requires that the user's cookie is valid. It's not clear to me how your users have a valid cookie that allows them to get updates, but that cookie isn't valid enough when they perform a refresh.

The endpoints queried _are_ different (`/dbinfo`, `/_changes` and others for periodic sync, explicit `GET _session` for refresh) but the mechanism (passing the cookie and receiving a fresh one back if required) remain the same.

Regardless, we'll take a look and validate how updates work from this perspective.
> Normally after pushing updates 

You're talking about config updates here right, not new versions of the CHT?

> If the token is unchanged and is not expired are there other factors that can cause it to become invalid ?

Yes, the CouchDB secret key for the server. However, if you were changing that everyone on the system would be logged out immediately (because it would invalidate all existing cookies) so I don't think it's relevant. It's possible that the clock accuracy on clients could also matter, so that would be something to look at for users that get logged out unexpectedly, but I'm not completely sure. We are getting deep into the weeds of HTTP here 

I think though, if you can raise another more specific support ticket for your issue that is probably a good idea for now.

**Comment by SCdF** [comment]
The only work to be done on this ticket (unless we get more information that shows that there is a bug in how we expose authentication) is to write some tests to make sure we never drop these headers.

**Comment by Patrickyk** [comment]
@SCdF thanks  very helpful. Will revert after investigation.

**Comment by garethbowen** [comment]
This investigation focused on the AuthSession cookie which does appear to be working as expected. However if the `userCtx` cookie expires it will also result in the appearance of being logged out. This is being tracked in [this issue](https://github.com/medic/cht-core/issues/6583).

**Comment by garethbowen** [comment]
We've added a [manual release test](https://github.com/medic/medic-release-testing/issues/87) and a little automated testing to try and pick up future regressions in our session management.

I think this investigation is now complete - please reopen if there's something more to be done.
