### ISSUE TITLE
Sentinel might process changes when it shouldn't

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6533]
We have a mechanism where Sentinel would stop processing changes if any of the enabled transitions is misconfigured.
Right now, because of how our queue is paused and resumed when it reaches certain length, we might get in a situation where sentinel processing is resumed even if it was stopped due to a misconfigured transition.

**To Reproduce**
A little disclaimer that this a total race condition that I happened to witness in an e2e test. This is what the e2e test did:
1. Edit a doc (doesn't matter which doc, the idea is to have something in your queue)
2. Immediately edit `settings` with a misconfigured transition
3. Immediately after you see that "'Transitions are disabled until the above configuration errors are fixed." Update another doc.
4. Watch the Sentinel log and notice that your second doc is actually getting processed, but no transitions run over it.

**Expected behavior**
The 2nd doc should not have been processed.

**Logs**
When the race condition happens, you would see something like:
```
change event on doc <your 1st doc>
Reloading configuration
Loading transition ....
......
Failed loading transition <your misconfigured transition>
....
Transitions are disabled until the above configuration errors are fixed.
saved changes on doc <your 1st doc>
transitions: queue drained
transitions: processing enabled <- this is the bug.
change event on doc <your 2nd doc>
```

**Environment**
- Instance: local
- Client platform: Linux
- App: Sentinel
- Version: 3.10

**Additional context**
I tried to replicate this outside of my flacky e2e test, but couldn't write a reliable script that always triggers this.
The change I'm making is so, when the queue is drained, only an working (unpaused) queue will resume processing.

**Comment by garethbowen** [comment]
Ready for AT in `6533-sentinel-queue-drain-paused`

**Comment by ngaruko** [comment]
Is there a reliable way to 'reproduce' this @dianabarsan ? or the actual flaky test that triggers it?

**Comment by dianabarsan** [comment]
Sorry, I found no reliable way to reproduce. 
Example of the failing e2e test: https://medic.slack.com/archives/C024KTGRW/p1597900898002300

**Comment by ngaruko** [comment]
Thanks @dianabarsan . I ran e2e tests multiple times on the branch and they seem stable. Short of any other way to reproduce, we could mark it closed and monitor the behaviour over time. Back to you!

**Comment by dianabarsan** [comment]
@ngaruko is this ready to merge? It's still in `AT in progress`.

**Comment by dianabarsan** [comment]
Merged into `master`.
