### ISSUE TITLE
Adhere to play store privacy policy requirements update 

### ISSUE THREAD

**Issue by MaxDiz** [medic/cht-core#6538]
Google recently announced an [update](https://support.google.com/googleplay/android-developer/answer/9914283) to their Google Play Policies, which takes effect Aug 12, 2020. Adherence is mandatory, else risk de-listing. Included in this update, they require developers to:

> Post a privacy policy in both the designated field in the Play Console and within the app itself. The privacy policy must, together with any in-app disclosures, comprehensively disclose how your app accesses, collects, uses, and shares user data. Your privacy policy must disclose the types of personal and sensitive data your app accesses, collects, uses, and shares and the types of parties with which any personal or sensitive user data is shared.

For the in-app disclosure, UI requirements include:
- Must be displayed in the normal usage of the app and not require the user to navigate into a menu or settings
- Must present the consent dialog clearly and unambiguously;
- Must require affirmative user action (e.g. tap to accept, tick a check-box);
- Must not interpret navigation away from the disclosure (including tapping away or pressing the back or home button) as consent; and
- Must not utilize auto-dismissing or expiring messages.

These Google Play requirements are in addition to any requirements prescribed by applicable local privacy and data protection laws. Since the CHT is deployed in various countries around the world, each with their own data privacy rules, we should make the in-app disclosure configurable.

Additional info on the user data policy can be [found here](https://support.google.com/googleplay/android-developer/answer/9888076#personal_sensitive). 

**Complete with this ticket**:
- [ ] updated data policy in the Play Console
- [ ] configurable in-app data policy

**Comment by MaxDiz** [comment]
@abbyad can you link to the privacy policy language?

**Comment by garethbowen** [comment]
@n-orlowski Have you got time to investigate what this would look like in the app?

**Comment by n-orlowski** [comment]
Sure do! Will propose a few options by EOD

**Comment by abbyad** [comment]
> @abbyad can you link to the privacy policy language?

The privacy policy will be different between deployments. You can see a sample with this [draft privacy policy for one upcoming deployment](https://docs.google.com/document/d/17lKWxlzGXwZSXxoj9bTvyYlPp-ptSBkcHumnserQv4E/edit?usp=sharing) (private link). The format can be updated as needed to plain text, markdown, or other.

**Comment by n-orlowski** [comment]
<img width="1420" alt="privacy-flow" src="https://user-images.githubusercontent.com/59581790/87581628-1ba9f400-c68e-11ea-9b25-e89a1ff3e758.png">

Aligned on this flow with @garethbowen :

- On load we would check to see if the latest version of the policy has been accepted, if not we'd display the first screen
- The policy is quite long to scroll through so the Accept button should be sticky / always visible
- If a user declines the policy they will see a modal that confirms that the app will close
- We will also include a Policy page accessed via the hamburger menu

**Comment by garethbowen** [comment]
Another few requirements...

- We need to allow translation but this can be as simple as allowing configuration of multiple blobs of formatted text, one for each language.
- We need to track when the user accepted the policy, which language they accepted, and which version they accepted.
- We need to show the prompt and require acceptance again on future start ups if the policy is updated from the one they accepted, or if a policy is added when before there was none.
- The acceptance is user specific, not device specific so replicate the acceptance in the users db.

**Comment by dianabarsan** [comment]
If language matters, what should happen if the user changes their language?

**Comment by garethbowen** [comment]
> If language matters, what should happen if the user changes their language?

Good question. I think we should show the policy again on next load. It's not likely to happen but just in case they didn't understand the policy the first time so clicked through and changed their language in app.

**Comment by garethbowen** [comment]
As for format, markdown would be ideal but would require including a markdown generating library to be included which I'm reluctant to do for just this feature. I think plain old HTML is the way to go, relying on `ng-bind-html` to sanitize it and only allow "safe" elements through (ie: no `script` injection).

**Comment by garethbowen** [comment]
Ready for AT.

- Read the [documentation](https://github.com/medic/cht-docs/pull/248).
- Install the `6538-privacy-policy` cht-core branch.
- Install the `6538-privacy-policy` medic-conf branch.
- Test configuring the Privacy policies using medic-conf and the App Management app
- The Privacy Policy should should be shown next time each user logs in on browser or android app.
- They should not be able to get around it, but should be able to close the app/tab.
- After acceptance and replication you should see the status on the user settings doc in the `medic` db.
- If they log in again on the same device or a different device they should not see the policy again.
- Upload the same privacy policy again, replicate, and reload the app and ensure the user is not prompted to accept it again.
- Change the privacy policy for the user's language, replicate, and reload the app and you should be prompted to accept the new one.
- Change the user's language, reload the app, and you should be prompted to accept the policy in the new language.

**Comment by ngaruko** [comment]
LGTM - As far as the `infrastructure` goes. Obviously part of the policy has to do with the wording of the policy the `html` documents. Please note: the Privacy policy also shows for `admins` on the web,  not sure if that's intentional @garethbowen ?

**Comment by dianabarsan** [comment]
@ngaruko It was intentional from my part, it makes sense to me that, if there is a privacy policy, _everyone_ has to accept it. 
I've also included this detail in the PR description. 
Does anyone object?

**Comment by dianabarsan** [comment]
Merged into `master`.
