### ISSUE TITLE
Change /users/info api to deal with task documents

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6545]
**What feature do you want to improve?**
The `/users/info` api was added as a means to warn configurers and users when replicating too many docs. 
This endpoint is called with specific parameters (`roles` and a `facility_id`) when adding/editing users (via admin console or medic-conf).This configurer-side request completely disregards which user we're editing.

This endpoint is _also_ called when performing an initial replication on the device. The user-side request is different, it uses no parameters and identifies the user by their authorization context (session cookie). 
The big difference is that this request knows who the authorized user is. 

Before 3.8, the configurer-side request and user-side request yielded identical results.
After 3.8 and the task/targets refactor, tasks are now persistent on disk and are replicated. They also have a special replication_key so they're only replicated by the user that created them, so knowing who the user is relevant now.   
After 3.8 the user-side `/users/info` request will count all of the user's tasks towards the replication warning limit. 

**Describe the improvement you'd like**
We should align the configurer-side request and the user-side request, so you don't end up being warned on one side and not warned on the other. 
Warning that the user replicates too many docs because they have too many tasks isn't actionable. The only way the number of tasks is reduced is by purging, which only happens 60 days after a task is in a terminal state. 
I suggest we **exclude counting task documents** towards the replication warning limit. 

**Describe alternatives you've considered**
As an addendum rather than complete alternative, we could split the warning and warn separately about number of tasks. 
We could also change the endpoint to accept a new parameter, user_id, which can be called by configurers and get the result that counts the user's tasks as well, and change how the endpoint is called when editing users. 

**Additional context**
This was brought forward by a TL that was confused why a user with 300 docs (as the configurer-side request reported) had a warning during initial replication that they were replicating 20.500 docs (yes - the user indeed had 20k tasks). 

We should also consider the API reporting part, and probably split the number of docs between tasks and non-tasks.

**Comment by garethbowen** [comment]
> I suggest we exclude counting task documents towards the replication warning limit.

Sounds good!

> yes - the user indeed had 20k tasks

Having ~70x more tasks that docs sounds like a misconfiguration. Should raise a new issue to warn about that somehow...

**Comment by dianabarsan** [comment]
The instance in question was a test instance. I'm assuming the configuration changed a lot, and with every configuration change, "old" tasks get canceled and new tasks get generated. And they just .. pile up in large numbers. 

Even if we would warn, it wouldn't be actionable, for the same reasons I've iterated above. Also, the reason of the large number of tasks might not be because of the current configuration, but one before, but we've only now passed the warn threshold. 

Are you suggesting we have a server-side way of detecting obsolete tasks (that were generated by old configs) and purge them ahead of time?

**Comment by garethbowen** [comment]
I was hoping to detect misconfiguration which could impact performance, but ideally these would be caught earlier (eg: in the config test harness) so let's not worry about it now.

**Comment by dianabarsan** [comment]
This is ready for AT on `6545-users-info-tasks`. 
Documentation PR here: https://github.com/medic/cht-docs/pull/524

**Comment by ngaruko** [comment]
Tested on local 
api response has total vs warn docs:
```
![image](https://user-images.githubusercontent.com/6979995/133372357-805c5052-ed6a-4367-bb1d-672f86444646.png)

UI reflecting the above
![image](https://user-images.githubusercontent.com/6979995/133372853-e9298c2d-621e-4c4d-9ba2-89a5a834f080.png)

 Also shows when updating/creating user
![image](https://user-images.githubusercontent.com/6979995/133372868-7b547dfa-e39d-4c56-bf5d-2dd5aa0cd8e1.png)

However, tasks are NOT excluded from `warn_docs` count. I created a 3 baby delivery report which generated 4 tasks (one for mother and 1 for each baby) and the docs count went up by 5 for both total_count and warn-count. Am I missing something @dianabarsan ?
```
{"total_docs":10045,"warn_docs":10045,"warn":true,"limit":10000}
```

**Comment by dianabarsan** [comment]
> 3 baby delivery report 

Did you add the delivery report before or after counting 10040 docs?

Delivery reports create additional docs, like contact docs for each baby. So that would be 4 extra docs (1 report + 3 contacts). Depending on how you filled the form, it could generate other docs as well (it's a complicated form). 
So at least 4 of the new docs are accounted for, the 5th is an unknown. 

I think we should try a simpler config scenario.

**Comment by ngaruko** [comment]
@dianabarsan - the delivery report was created after the 10040 docs. Yes the scenario is a little complex as it creates  more contacts and 4 tasks. But I was expecting the `total_docs` to be higher than the `warn_docs` in any case, as the former include the task count...or not?
I will try a less complicated scenario, that creates only tasks without creating extra docs... and see how it goes.

**Comment by ngaruko** [comment]
PS: Just created another report, which generated a task (danger sign follow up). So, if I understand correctly, I this would increase the `total_count` by 2, ie report + task and the `warn_count` by 1, just the report. Am I correct ? But both went up by 1 count - 
![image](https://user-images.githubusercontent.com/6979995/133387924-2ec3eb56-9a08-461c-a7c8-0ef4eac10549.png)
![image](https://user-images.githubusercontent.com/6979995/133388141-60053fd8-4350-4c71-aaa7-435a11ccbc97.png)

**Comment by dianabarsan** [comment]
@ngaruko if you call `users-info` as an admin, with passing `facility_id`, the endpoint will never count tasks, because tasks are connected to the user that generates them, not to a facility_id + a role. 
Effectively, this change should have no effect on the `users-info` call as an admin. 

To actually get the endpoint to count tasks, you have to call it as an offline user - in that case, the request will know which user to count tasks for.

**Comment by ngaruko** [comment]
@dianabarsan Thanks for the clarification . Looks good with office user credentials. Ready to merge:
```
curl http://andra:Secret_1@localhost:5988/api/v1/users-info\?facility_id\=8935e9d8-0b2a-5eb0-ae54-ad1377a60097\&\&role\=chw
{"total_docs":10052,"warn_docs":10047,"warn":true,"limit":10000}% 
```

**Comment by dianabarsan** [comment]
Merged to `master`.
