### ISSUE TITLE
API service doesn't boot successfully if there is a label named "submission" in the xform

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#6557]
**Describe the bug**
Medic-api doesn’t boot successfully if there is a label named ‘submission’ in the xform.

The LG’s config outputs the logs below when it gets to the form:death_report during an upgrade to v3.9.0 resulting in the api failing to boot.
 
_My assessment of what is happening._

[This](https://github.com/medic/cht-core/blob/a6b10893a83a12e7799e10ec866e9bc0b5be407a/api/src/services/generate-xform.js#L34) seems to be the line throwing the error. I’m not quite sure of the logic that leads to executing this file which seems lie the [file](https://github.com/enketo/enketo-transformer/blob/21c067e61f7b79d26846bf19d48a228dfab04fdc/src/xsl/openrosa2html5form.xsl#L206) throwing the error above. That looks to me like a regex testing for the work ‘submission’. Please excuse my unfamiliarity with this stuff. 
‘Grepping’ for “submission” in the app forms dir brings up death_report xml. 
```
grep "submission" -r forms/app/
forms/app/death_report.xml:            <submission/>
forms/app/death_report.xml:      <bind nodeset="/death_report/group_diagnosis/submission" readonly="true()" relevant=" /death_report/group_diagnosis/confirm_reported_death  = 'yes'" type="string"/>
forms/app/death_report.xml:      <input ref="/death_report/group_diagnosis/submission">
kags@kags-PC:~/workspace/medic_mobile/code/livinggoods/config-lg/lg-kenya$ 

```
Horti brings up the api when form doc is deleted from CouchDB. Editing the field label to anything other than ‘submission’ also seems to fix the problem and the api boots as expected.

**To Reproduce**
1. Upload a form with the a label "submission"  to an instance running v.3.6.1 
2. Try to upgrade the instance to v3.9.0
3. Observe the api never booting and observe logs similar to the ones in this ticket from the horti's logs

**Expected behavior**
The upgrade should be seemless.

**Logs:**
 
```
Watching for deployments
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:client_review" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:community_event" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:clinic:create" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:clinic:edit" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:district_hospital:create" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:district_hospital:edit" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:health_center:create" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:health_center:edit" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:person:create" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:contact:person:edit" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:covid_19_follow_up" 
2020-07-22 12:45:30 DEBUG: Generating html and xml model for enketo form "form:death_report" 
2020-07-22 12:45:30 ERROR: xsltproc stderr output:  
2020-07-22 12:45:30 ERROR: ERROR: Submissions element(s) not supported.
 
2020-07-22 12:45:30 ERROR: Fatal error initialising medic-api 
2020-07-22 12:45:30 ERROR: Error: Error transforming xml. xsltproc returned code "0", and signal "null"
    at ChildProcess.<anonymous> (/home/kags/.horticulturalist/deployments/medic-api/md5-O3yLnjz8HcvO7g+wuf0kiw==/src/services/generate-xform.js:34:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  [stack]: 'Error: Error transforming xml. xsltproc returned code "0", and signal "null"\n' +
    '    at ChildProcess.<anonymous> (/home/kags/.horticulturalist/deployments/medic-api/md5-O3yLnjz8HcvO7g+wuf0kiw==/src/services/generate-xform.js:34:23)\n' +
    '    at ChildProcess.emit (events.js:315:20)\n' +
    '    at maybeClose (internal/child_process.js:1021:16)\n' +
    '    at Socket.<anonymous> (internal/child_process.js:443:11)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at Pipe.<anonymous> (net.js:674:12)',
  [message]: 'Error transforming xml. xsltproc returned code "0", and signal "null"'
} 
2020-07-22 12:45:38 INFO: Waiting for API to be ready... 
2020-07-22 12:45:48 INFO: Waiting for API to be ready... 
2020-07-22 12:45:58 INFO: Waiting for API to be ready... 
2020-07-22 12:46:08 INFO: Waiting for API to be ready... 
2020-07-22 12:46:18 INFO: Waiting for API to be ready... 
2020-07-22 12:46:28 INFO: Waiting for API to be ready... 
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment**
- Instance: (eg: alpha.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, medic-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Related and very cryptic: https://github.com/enketo/enketo-transformer/issues/65

**Comment by dianabarsan** [comment]
My impression is that "submission" elements are reserved for something: https://github.com/enketo/enketo-transformer/blob/21c067e61f7b79d26846bf19d48a228dfab04fdc/src/xsl/openrosa2html5form.xsl#L108

**Comment by garethbowen** [comment]
I agree it looks like a reserved element type. I'm not sure there's much we can do about this other than improve error handling and work around it by changing the name.

NB: We have an issue scheduled to [catch these errors earlier](https://github.com/medic/medic-conf/issues/331) which will reduce the severity of this issue.

**Comment by enyachoke** [comment]
@dianabarsan  @garethbowen  We are testing the upgrade to 3.9.1 at LG and have run into this issue can we remedy this at db level since we can't upload configs with the fix?

**Comment by mrsarm** [comment]
Moved to in progress in the 3.11 release because this issue is addressed in https://github.com/medic/medic-conf/issues/331 and https://github.com/medic/medic-conf/issues/375 that I'm going to move to AT today.

**Comment by mrsarm** [comment]
Ready for AT.

Check comments here: https://github.com/medic/medic-conf/issues/331#issuecomment-789126267

**Comment by newtewt** [comment]
@mrsarm  is the only fix here a validation check in `medic-conf` that's done in the other issue?

**Comment by mrsarm** [comment]
Yes @newtewt , is not that now users can push labels with "submission" as name, but is that now they will prevented to do so.

**Comment by newtewt** [comment]
There needs to be a `cht-core` change too. I can bypass `medic-conf` and upload broken forms through the admin app. Unless we are ok with ignoring that hole.

**Comment by mrsarm** [comment]
Good point, you are right, but that won't be solved for now I think, unless upload forms in that way is widely used, we can close the ticket just warning about that once the other ticket is closed.

**Comment by dianabarsan** [comment]
If the `medic-conf` solution adds a new endpoint to API where forms are verified, is it not feasible to use the same endpoint prior to uploading the form via admin app ?

**Comment by mrsarm** [comment]
Yeap, I'll move the ticket to development again, I thought that the upload from the admin was mostly used for testing, but either way we should implement the change.

**Comment by mrsarm** [comment]
Added the validation of the XML form to the "App Management" > "App forms" view, and also improved how errors are displayed in the form as requested in https://github.com/medic/cht-core/issues/5402.

Before the changes, if there was an error in the form upload, even one as simple as forget to upload either the XML or the JSON file, the error was displayed with a generic message "Upload failed", and the real error message was only available in the console logs:

![Medic - Apps forms - Upload failed](https://user-images.githubusercontent.com/1608415/112655114-d6e67780-8e2e-11eb-92b0-e27f7c930023.png)

Now the error is displayed with a proper message:

![Medic - Apps forms - Upload failed detailed](https://user-images.githubusercontent.com/1608415/112656984-b5868b00-8e30-11eb-9f9f-aadb87e59724.png)

And here is the the same form when you try to submit an XML file that does not pass the API validations:

![Medic - Apps forms - Upload failed - XForm validation](https://user-images.githubusercontent.com/1608415/112657216-f4b4dc00-8e30-11eb-89a2-96855a8b9510.png)

@dianabarsan could you review the changes in the PR? Gareth already did but only the API changes, now the same PR also has the Admin view changes: https://github.com/medic/cht-core/pull/6947

**Comment by mrsarm** [comment]
@newtewt this ticket is addressed in the same PR than https://github.com/medic/medic-conf/issues/331

**Comment by ngaruko** [comment]
Tested as part of [medic-conf #331](https://github.com/medic/medic-conf/issues/331).
Also tested the UI response where trying to load the form via the admin portal 
![image](https://user-images.githubusercontent.com/6979995/114111272-b558b600-992d-11eb-9fc0-200984d1fda8.png)
Ready to merge @mrsarm
