### ISSUE TITLE
Have an upper time limit to generating task documents

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6564]
**What feature do you want to improve?**
Currently, the rules-engine will consider any emission due in the future as timely. We do, however, consider emissions due more than 60 days in the past as not timely. 
https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/task-states.js#L125

**Describe the improvement you'd like**
I find no obvious advantage in generating and storing these far-into-the-future tasks. They will, most likely, become "stale" and be canceled by config changes and updates to the dataset. This breeds a rapidly ever-growing task collection for every user, that puts strain on the device and on the server. 

My proposal is to have an upper time limit to timely emissions, maybe (very generously) 6 months or 1 year, but we could probably go with less and have no impact on user's performance. The interval is TBD. 

**Describe alternatives you've considered**
None. 

**Additional context**
It's happened in production that some task configs generated emissions for more than 10 years in the future.

**Comment by garethbowen** [comment]
This issue keeps coming up and causes significant disruption in production and is probably an easy win to implement.

@kennsippell @dianabarsan Do either of you have a feel for what the upper limit should be? 1 year is a really safe option, but 6 months seems about right to me.

**Comment by dianabarsan** [comment]
I would go as low as possible. 

Do we have any value from task documents being generated in advance? 
Is it useful for debugging or impact metrics? 
What is the chance that the configuration won't change in that time span and render the future tasks useless (and cancelled)? 

Maybe 3 or 6 months?

**Comment by garethbowen** [comment]
Ready for AT in: https://github.com/medic/cht-core/pull/7597
Documentation here: https://github.com/medic/cht-docs/pull/684

**Comment by ngaruko** [comment]
Tested with a pregnancy form with generated a number of future tasks, up to 40 weeks. 
On master, tasks with a `startDate` over 180 days are synced to client:
![image](https://user-images.githubusercontent.com/6979995/177227062-874414af-60e4-4a46-b6e1-4f921d29d1ba.png)

On the branch only tasks with startDate before 180 days are synced:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6979995/177227022-460a6eee-227f-4c21-ae84-7154eb32e395.png">

**Comment by garethbowen** [comment]
Merged.
