### ISSUE TITLE
Security issue medic-infrastructure#147

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6567]
This is a placeholder issue for https://github.com/medic/medic-infrastructure/issues/147

**Comment by garethbowen** [comment]
AT instructions in the linked issue. Work with @Hareet to figure out how to set up the environment to AT this.

**Comment by ngaruko** [comment]
LGTM - comment on issue : [medic/medic-infrastructure#147](https://github.com/medic/medic-infrastructure/issues/147)
