### ISSUE TITLE
Allow for monitoring and alerting of SMS failure rate

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6572]
**What feature do you want to improve?**
Our [monitoring api](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv1monitoring) doesn't include any reporting of SMS that failed to send via medic-gateway or an SMS aggregator. This would be very useful for alerting when something has gone wrong with SMS delivery.

**Describe the improvement you'd like**
Include the failure rate in the monitoring api endpoint. I'm not sure if this should be a total for all time or if it would be better to have a percentage or count of failures in the last time period (eg: 7 days). Consider which of these metrics is most useful for alerting and include one or a combination of metrics.

**Comment by michaelkohn** [comment]
Please allocate any time spent on this to `Project | 214 Research` in Clicktime.

**Comment by latin-panda** [comment]
Hi @mrjones-plip! What are the most useful metrics for the end user? Is there anything else they need for this case? :) Thanks!

**Comment by helizabetholsen** [comment]
@yrimal, I think it would be useful to add input on how we could use these metrics for monitoring app health, so I'm also pinging @kennsippell here for visibility.

I'd imagine we'd want these data per device (?) and in aggregate across deployments. 

- # of failures for all time, year, quarter, month, and week
- % of failures for all time, year, quarter, month, and week

Can we add a list of phone numbers that commonly result in failure -- or another endpoint? This might be useful for programmatic types of intervention

**Comment by mrjones-plip** [comment]
I reached out to Derick to get some App Serv. perspective on what would be helpful, so I presume he'll be back in touch when he comes online as it's 11.30pm there. I'll keep this ticket updated!

**Comment by derickl** [comment]
It's great that we are looking at adding visibility to gateway transactions. Having a weekly summary (at a minimum) would be great. Are we able to do daily? @helizabetholsen's metrics would be a good start

**Comment by mrjones-plip** [comment]
Thanks @derickl ! I'll consider your comment as a vote for errors/day.  We can then aggregate up from easily to errors/week.  Let me know I'm getting this wrong!

FYI @JenniferMuli  - moving  this back to "ready for dev" with Derick's comments.

**Comment by dianabarsan** [comment]
I have a few questions about @helizabetholsen 's comment: 

> % of failures for all time, year, quarter, month, and week

What should we consider for the "total" here - and I am linking [to the docs site page explaining message states](https://docs.communityhealthtoolkit.org/apps/guides/messaging/sms-states/#message-states-in-medic) - messages in which states should be part of the "total"? Also, another question would be what quantifies as a failure (in terms of states). 

My initial thought was to just count messages that we "intended" to send (so exclude statuses like "duplicate", "cleared", "muted", "denied") and only count messages that are "failed" as failures. 
However, there's still a question about whether we should count messages in "temporary states", for example "forwarded-to-gateway". A message could be blocked in this state if some service in the pipeline is not working properly. Should this be reported by monitoring? Should it be a different metric altogether? 

Another question is how to group these messages by date: by the date they were supposed to be sent, or by the date that their state was updated the last time?

**Comment by garethbowen** [comment]
I think there are two separate issues here. The original intent for this issue is to have a simple interface that can start alerting system administrators if the error rate or unsent message backlog starts climbing. This would be built in to the monitoring API and able to be integrated into prometheus or any other scripted monitoring solution, and is designed to help finding and resolving issues quickly.

The data that @helizabetholsen requested are long term app health metrics. This information should already be available in postgres but it'll need a little SQL magic to pull it out.

These two have quite different use cases so should be two separate issues. I suggest we keep this one about the monitoring API, and investigate whether the additional postgres data contains enough information to solve Helen's use case as a separate issue.

**Comment by dianabarsan** [comment]
I was thinking of adding some this new data to the monitoring API: 
| Path | Type | Description | 
| --- | --- | ---- | 
| `messaging.outgoing.delivered` | number | number of messages in `delivered` or `failed` states | 
| `messaging.outgoing.failed` | number | number messages in `failed` state |
| `messaging.outgoing_7_days.due` | number | number of messages that should have been sent within the last 7 days (includes delivered and failed) | 
| `messaging.outgoing_7_days.scheduled` | number | number of messages that were scheduled to be sent within the last 7 days | 
| `messaging.outgoing_7_days.muted` | number | number of messages that were scheduled to be sent within the last 7 days and are muted | 
| `messaging.outgoing_7_days.delivered` | number | number of message that were scheduled to be sent within the last 7 days that are in `delivered` or `failed` states | 
| `messaging.outgoing_7_days.failed` | number | number of message that were scheduled to be sent within the last 7 days that are in `failed` state |

Not sure about the `outgoing_7_days` naming, open to suggestions and all feedback.

**Comment by mrjones-plip** [comment]
I think this makes sense if I'm following correctly.  So `messaging.outgoing.delivered` is for all time and `messaging.outgoing_7_days.delivered` is just the past 7 days (or more precisely, the past 168 hours from the moment you made the query), yeah?

**Comment by garethbowen** [comment]
Why does `*.delivered` include "failed"?

For naming, what about:

```
messaging: {
  outgoing: {
    total: { delivered: 0, failed: 0, ... },
    seven_days: { delivered: 0, failed: 0, ... },
  }
}
```

That way the schemas are consistent between the two even if one only has a subset of properties.

My only concern other than naming is that if messages start failing a lot then we want alarms to start going off as soon as possible. With the granularity set to "last 7 days" it might take a day or two before the 100% failure rate is visible in above the noise. What do you think? Would it be useful to have a count of errors in the last 100 messages, or something?

**Comment by dianabarsan** [comment]
> Why does *.delivered include "failed"?

Typo ... I meant "sent" but probably failed a Paste.

**Comment by garethbowen** [comment]
> I really like improved structure. Are we worried about scripts that need to be rewritten to support both old and new structure?

D'oh! I forgot that would break the existing schema. Yes that would have to be either done in a backwards compatible way either duplicate the value and deprecate the old part OR bump the API version. I think it's fine to bump the version, and it's not widely used yet so feel free!

> Having 100 pending messages could just be a short-termed bottleneck, and not necessarily indicate failure.

Good point! I guess there's two things we're looking for:

1. Is the backlog being processed. Could be measured with something like how many are currently `scheduled` to be sent.
2. How many messages are being failed. Could be measured with of the last 100 messages in a terminal state, how many failed.

**Comment by dianabarsan** [comment]
Cool! So, besides the `seven_days` section, I was thinking about adding a `last_hundred` (???? naming is hard) section that will contain counters of the last 100 updated messages, grouped by statuses: 
```
"last_hundred": {
  "pending": {
    "pending": 80,
    "forwarded-to-gateway": 9,
    "received-by-gateway": 1,
    "forwarded-by-gateway": 10
  },
  "final": {
    "sent": 10,
    "delivered": 90,
    "failed": 10
  },
  "muted": {
    "denied": 25,
    "cleared": 25,
    "muted": 25,
    "duplicate": 25
  }
}
```

Scheduled is skipped because there's only one scheduled status, and we already know how many scheduled messages we have from other sections.

**Comment by garethbowen** [comment]
Very detailed! To make sure I understand could you write a formula for alerting if the backlog is being processed?

For example, you could alert about failure rates by checking if `last_hundred.final.failed > THRESHOLD`.

**Comment by dianabarsan** [comment]
Yea, sure:
I'm just gonna pick some random threshold values: 

`last_hundred.pending.pending` > `50` = we have an unsent backlog that hasn't yet reached gateway. having this number up all the time points to an unhealthy message volume. 
`last_hundred.pending.forwarded-to-gateway` > `50` = might indicate a problem with Gateway, since messages are not updated
`last_hundred.pending.received-by-gateway` > `50` = same as above
`last_hundred.pending.forwarded-by-gateway` > `50` = I'm not 100% about this one, because it depends on which "gateway" is used. It might be a warning for failure if gateway forwards but statuses don't change

`last_hundred.final.failed` > `30` = alert for failure

The muted section is more useful for trends, and how they are interpreted depend on the project and the workflows. If SMS workflows are frequently cancelled, I'd expect to see a majority of "cleared" here. If muting is enabled, we could have some "muting" values sometimes. 
If "duplicate" is trending up, it could mean we had a problem where some services started generating identical messages.

**Comment by garethbowen** [comment]
That's amazing! Thanks for explaining.

**Comment by dianabarsan** [comment]
Ready for AT on `6572-sms-failure-monitoring`. 
Documentation PR: https://github.com/medic/cht-docs/pull/505 describes the new endpoint and the updates to the existent endpoint.

**Comment by ngaruko** [comment]
LGTM,
The api call returns data on outgoing messages
```
"curl http"::5988/api/v2/monitoring{
   "version":{
      "app":"6572-sms-failure-monitoring",
      "node":"v14.16.0",
      "couchdb":"2.3.1"
   },
   ....
....
   "sentinel":{
      "backlog":0
   },
   "messaging":{
      "outgoing":{
         "total":{
            "due":10,
            "scheduled":0,
            "muted":7,
            "failed":0,
            "delivered":10
         },
         "seven_days":{
            "due":10,
            "scheduled":0,
            "muted":7,
            "failed":0,
            "delivered":10
         },
         "last_hundred":{
            "pending":{
               "pending":0,
               "forwarded-to-gateway":0,
               "received-by-gateway":0,
               "forwarded-by-gateway":0
            },
            "final":{
               "sent":10,
               "delivered":0,
               "failed":0
            },
            "muted":{
               "denied":7,
               "cleared":0,
               "muted":0,
               "duplicate":0
            }
         }
      }
   },
```
Tested with gateway to see if state changes are recorded 
![image](https://user-images.githubusercontent.com/6979995/120127613-f4133a00-c213-11eb-85d6-cbf4500925a8.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
