### ISSUE TITLE
Large grey banner shown above content on mobile

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6575]
**Describe the bug**
There's a block of grey "whitespace" on the content panes in the mobile view which leaves less room for the content. This affects the Contacts, Tasks, and Reports tab. Check other tabs too.

**To Reproduce**
1. Log in as a user who has access to more than 3 tabs on a mobile device
2. Go to the Reports tab
3. Select a report
4. See grey bar just under the yellow heading.

**Expected behavior**
The page should be optimised to show as much content as possible.

**Logs**
None.

**Screenshots**
![Screenshot from 2020-08-06 15-14-32](https://user-images.githubusercontent.com/2064938/89487057-b1055780-d7f8-11ea-904c-dc682a5c3809.png)
![Screenshot from 2020-08-06 15-14-44](https://user-images.githubusercontent.com/2064938/89487060-b19dee00-d7f8-11ea-94cc-cb1c4830efb1.png)
![Screenshot from 2020-08-06 15-14-52](https://user-images.githubusercontent.com/2064938/89487062-b2368480-d7f8-11ea-8259-ddea88eb47c9.png)

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.9.0

**Additional context**
Introduced in this PR: https://github.com/medic/cht-core/pull/6216

**Comment by dianabarsan** [comment]
Ready for AT on `6575-remove-grey-bar`

**Comment by ngaruko** [comment]
The top of forms looks good.
There is still a bit of large grey space at the bottom of some forms...but I guess it shouldn't be an issue as it only shows after scrolling and does not take prime estate like the top block @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/89604576-ab267980-d8bf-11ea-8927-294538ff59e2.png)

**Comment by garethbowen** [comment]
@ngaruko I think that's fine. The main problem with the bar at the top of the form was it didn't scroll away so it was permanently taking up screen space. As long as the new one only shows when you scroll right to the bottom of the report I'm ok with it.

**Comment by garethbowen** [comment]
Merged.
