### ISSUE TITLE
Improve performance of subject lookups in authorization service

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6577]
**Describe the performance issue**
When determining whether a document is sensitive, we immediately search for it's submitter in the subjects array. 
https://github.com/medic/cht-core/blob/master/api/src/services/authorization.js#L453

**Describe the improvement you'd like**
Don't immediately search for the submitter, do it only per-need basis if the report is validated by the other "isSensitive" checks. 
We could, also, improve lookup times by keeping the subjects array sorted and leveraging binary search. 

We could use [_.sortedIndexOf](https://lodash.com/docs/4.17.15#sortedIndexOf). This would force us to cast all subjects to strings because of inconsistent results when dealing with mixed arrays: https://github.com/lodash/lodash/issues/4885
We could also write our own binary search function that casts before comparing. 

**To Reproduce**
1. Create a rather large offline user. Say 10k contacts and at least 15k reports. 
2. Request `_changes?limit=1` with this offline user and note the request time.

**Measurements**
The `_changes` requests will be most impacted by this improvement, because it loads all ids that the user is allowed to see. For smal users, the difference won't be noticeable. 
`_bulk_docs` and `_all_docs` requests perform subject lookups, but given the limited size of the requests (max 100 docs when replicating from Pouch), the difference will not be noticeable.

**Comment by garethbowen** [comment]
@dianabarsan PR approved - is this ready for AT?

**Comment by dianabarsan** [comment]
Yes. Ready for AT. 
In the end, the implementation only targets the `_changes` requests (which were affected the most). It was too fragile and intricate code-wise and had too little benefit to be worth implementing to affect the other endpoints. 

In real life situations, the difference will be barely noticeable, but it does reduce time where it, probably, hurts the most: api clock time. 

User with 20,000 contacts and 20,0000 reports, measuring duration of a `_changes` request. I'm also listing the actual time it took to process results received from CouchDB in API for every request - these numbers aren't available unless you add code to track these metrics and log them to console.

| Version | Request (API process clock time) | Req (apct) | Req (apct) | Req (apct) |
| ----- | ----- | ----- | ----- | ----- | 
| master | 10537 (137) ms | 10687 (148) ms | 10582 (143) ms | 10441 (133) ms | 
| proposed | 10432 (78) ms | 10381 (79) ms | 10355 (87) ms | 10341 (78) ms |
| difference | 105 (59) ms | 306 (69) ms | 227 (56) ms | 100 (55) ms |

**Comment by newtewt** [comment]
@dianabarsan  I've verified that the isSensitive portion is working as it did before this change. Also confirmed that the `_changes?limit=1` is returning when the user has large amount of data(10k docs).

**Comment by dianabarsan** [comment]
Thanks @newtewt !

**Comment by dianabarsan** [comment]
Merged into `master`.
