### ISSUE TITLE
Wrong error message shown when editing a user that replicates too many docs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6578]
**Describe the bug**
Instead of displaying the warning that the user is replicating too many docs, a generic "Error updating user" error is displayed.

**To Reproduce**
1. Login as an admin and go to App Management
2. Open the users page.
3. Edit a user that you know has more than 10.000 docs. Hit save.
4. See the "Error updating user". The 2nd click actually edits the user, this is just the visual message that is displayed that is the problem.

**Expected behavior**
The admin should see a warning about the user replicating too many documents.

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/89532183-0ee66f00-d7fa-11ea-97f3-e616a7a6e1ef.png)

instead of 

![image](https://user-images.githubusercontent.com/35681649/89532391-61c02680-d7fa-11ea-82db-9b07ee244114.png)

**Environment**
- Instance: local
- App: admin
- Version: 3.10

**Additional context**
This is a regression caused by https://github.com/medic/cht-core/commit/4b24613af5f3b13aaad01935c28ac6797817a048 , which caused the "wrong" catch block to catch the error from the `api/v1/users-info` endpoint.

**Comment by garethbowen** [comment]
Ready for AT in `6578-show-warning-for-large-users`

**Comment by ngaruko** [comment]
LGTM
Feel free to merge @dianabarsan

**Comment by dianabarsan** [comment]
Merged into `master`.
