### ISSUE TITLE
Rebranding apps and renaming repos

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6586]
**Describe the issue**
We have a mix of the legacy `medic` prefix and the new `cht` prefix for our repos and apps. In general we should use the `cht` prefix for everything that is useful to people outside of Medic Mobile, for example, `cht-infrastructure` is public has scripts for hosting that a self-hosting partner could use, while `medic-infrastructure` is private and has scripts for the Medic Mobile hosting stack.

**Describe the improvement you'd like**

Change the following repo names

- [x] medic-conf -> cht-conf
- [x] medic-conf-test-harness -> cht-conf-test-harness
- [x] medic-gateway -> cht-gateway
- [x] medic-android -> cht-android
- [x] medic-couch2pg -> cht-couch2pg
- [x] medic-nootils -> cht-nootils

Also

- [x] Change the cht-cli command line name to `cht` to make it easy to type and use. If possible keep `medic-conf` as a deprecated alias so we don't break backwards compatibility. 
- [x] Rename the medic gateway apps but leave the package ID unchanged, ie: Medic Gateway -> CHT Gateway ([here](https://github.com/medic/medic-gateway/blob/master/src/main/res/values/strings.xml#L3))
- [x] Rename some of the [default strings in medic-android](https://github.com/medic/medic-android/blob/master/src/main/res/values/strings.xml)
- [ ] Think about any other rebranding that should be done at the same time.
- [x] Change the cht-conf NPM name to match, and update README so the old npm package is deprecated

**Describe alternatives you've considered**
We could leave the names alone - it's not hurting anyone...

**Comment by garethbowen** [comment]
Scheduled for 3.12.0 in order to align with other branding work going on as requested by @abbyad 

This should be done early in the release cycle so it disrupts development as little as possible as there will be few outstanding branches.

@kennsippell Will the proposed changes be disruptive to your team?

**Comment by abbyad** [comment]
Also pinging @derickl on this issue.

**Comment by kennsippell** [comment]
Is there any possibility that medic-conf would one-day get a frontend and not just be a CLI tool? In general, the concept of moving GUI components of the admin console from the cht-core into a frontend for medic-conf has been discussed. If this is a possibility, then potentially cht-cli is not a great name for that repo.

The name medic-cli-test-harness doesn't really make sense. It isn't a test for the cli, or even related to the cli, or used via a cli.

It sounds like there are no proposed changes here which are not backward compatible? If we keep the medic-conf alias etc then I don't believe this will be too disruptive.

**Comment by garethbowen** [comment]
> The name medic-cli-test-harness doesn't really make sense.

@kennsippell You're right, not sure what I was thinking there. I think it was an overzealous find and replace on `medic-conf`! Have you got a better suggestion? Maybe "cht-conf-test-harness"?

**Comment by derickl** [comment]
We definitely need to include good migration notes (if needed) for a smooth transition.

**Comment by abbyad** [comment]
> Is there any possibility that medic-conf would one-day get a frontend and not just be a CLI tool? In general, the concept of moving GUI components of the admin console from the cht-core into a frontend for medic-conf has been discussed. If this is a possibility, then potentially cht-cli is not a great name for that repo.

Taking this into account, a safe option would be `cht-conf`, and having `cht` as the app name in command line. 

Going with `cht-conf` or `cht-cli` seems to depend on whether the primary purpose of the tool is to manage CHT instances, or if it is to mange/use the CHT via command line. Right now it is being considered for both, since you can upload/download config, but you can also add messages.

From my perspective either is more appropriate than `medic-conf`, and if `cht-conf` is less disruptive or confusing, let's go with that.

**Comment by garethbowen** [comment]
@dianabarsan Any update on this? I thought it'd be better to do it early in the release cycle rather than late, but maybe it doesn't make any difference. What do you think?

**Comment by dianabarsan** [comment]
I was actually looking into what to work on next, guess this wins then :)

**Comment by dianabarsan** [comment]
I was looking into how to "deprecate" old npm packages once we rename everything. It appears that [npm deprecate](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) is the way to go. 

The intention is to rename all `medic-(.*)` npm packages to `cht-$1` packages, correct? `medic-nootils` -> `cht-nootils` and so on, correct?

**Comment by dianabarsan** [comment]
This covers so many repos that it'd be hard to attribute it to a repo specific milestone. Maybe that's just why it's in the workstream.

**Comment by mrjones-plip** [comment]
Ah - super fair point, thanks Diana! My concern is working on this now means developers aren't working 3.12.  PO/PM should have a way to unambiguously assign this then, yeah? Or maybe I'm overthinking it?  I'm easy - I'll wait to hear what other folks think.

**Comment by mrjones-plip** [comment]
To clarify a point, this:

>  PO/PM should have a way to unambiguously assign this then, yeah?

Should really have been a little more clear and read:

>  PO/PM should have a way to unambiguously assign ticket priority, yeah?

Basically, once a ticket leaves the "Ready for dev" column there's no way to know what the former priority was. It's on PO/PM to make this extra clear - sorry for any confusion I caused on this! Something to work on in the mid term, but not short term given how many changes we've made in the past ~week.

CC @abbyad & @michaelkohn

**Comment by garethbowen** [comment]
> I was looking into how to "deprecate" old npm packages once we rename everything. It appears that npm deprecate is the way to go. The intention is to rename all medic-(.*) npm packages to cht-$1 packages, correct? medic-nootils -> cht-nootils and etc.

Yes that's right, and I think `npm deprecate` is the right approach. I was worried it might be a bit aggressive especially seeing as the `cht-*` version will be literally identical initially. What do you think about waiting some time after the new packages are published to deprecate the old packages?

**Comment by dianabarsan** [comment]
Small question, for the Android apps (medic-android and medic-gateway), do we also update the project to have changed APK names?

**Comment by abbyad** [comment]
I wouldn't update the app id, as that would be seen as different apps by Android and Google Play store, but updating the labels in the app makes sense. We'll want to make sure that is announced clearly as well in the release notes and to the community.

**Comment by garethbowen** [comment]
We definitely want to keep the app id the same, but I think the original question is about the name of the apk file. IMO this is fairly unimportant as it's just an arbitrary string, however it should be safe enough to change it, and it'd be good to clean that up at the same time, so unless it causes a bunch of downstream updates I'd go for it.

**Comment by dianabarsan** [comment]
I have one more question, about the `cht-android` exported JS interface: 
https://github.com/medic/medic-android/blob/53b9646bb69c678b85de304e0a4d684d48e866e1/src/xwalk/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L408

I was thinking whether to "duplicate" it and export `cht-android` as well. We obviously can't remove the other one, since it's going to be used by CHT pre 3.12.

**Comment by garethbowen** [comment]
Ideally we would change the interface name but I don't think it's worth it. Nobody except developers should ever see that, and we'd basically have to maintain backwards and forwards compatibility for a long time.

If we end up versioning this API one day because we want to change something else anyway, that would be the time to change the name too.

**Comment by eljhkrr** [comment]
As a final step, we should add deprecation notices to the medic-* npm package READMEs pointing users to cht-* packages. I realized this the other day when trying to use a newer harness feature but couldn't get it on medic-harness so I checked the latest published version on npm. Nothing on the page communicates this change and newer users may not easily realize there are alternative more recent versions.

**Comment by garethbowen** [comment]
@eljhkrr Good call! I've deprecated medic-conf and medic-couch2pg. Other than medic-conf-test-harness are there any other packages we should deprecate?

@kennsippell It looks like we should deprecate medic-conf-test-harness because cht-conf-test-harness is more up to date - what do you think?

**Comment by kennsippell** [comment]
Totally.  @garethbowen Would you mind deprecating medic-conf-test-harness while you're at it?  If you don't have permissions or whatever, I'm also happy to do it.

**Comment by garethbowen** [comment]
Done!

@dianabarsan Is there anything outstanding on this or can we close it off now?

**Comment by dianabarsan** [comment]
I think deprecation was the last step, unless we've forgotten some references somewhere (but no need to keep this open for those). 
Thanks for taking up deprecating packages, last we discussed [we were postponing deprecation for an indeterminate amount of time](https://github.com/medic/cht-core/issues/6586#issuecomment-846598543) and I just forgot to check back on that. I apologize.
