### ISSUE TITLE
Detect and report when users are unable to connect to the server

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6607]
**Is your feature request related to a problem? Please describe.**
We recently had an outage where users on an old version of Android were unable to connect due to being incompatible with a modern certificate installed on the server. Our current uptime reporting was compatible so it didn't report the outage, and it wasn't reported to our support channels for a few weeks. There are other problems that may cause users to be unable to connect.

**Describe the solution you'd like**
We want to be alerted as soon as possible when there is a significant drop in users connecting to the server. Provide or update an API or integration to existing services so the number of users who have managed to connect to the server can be tracked. Consider carefully how to express this data to reduce the noise, for example, reporting the percentage of users who have managed to connect in the last 7 days would account for lower usage on the weekend.

Configuring the monitoring and alerting is a separate task.

**Describe alternatives you've considered**
- Client side reporting, but if the user cannot connect then they may not be able to report that fact either.
- Monitoring reports created or other existing metric, but there are other reasons why reporting may drop off so this isn't as accurate.

**Comment by kennsippell** [comment]
**Describe alternatives you've considered**

* Currently, our client-side telemetry system bundles data into a single monthly aggregate document. If it were updated to send real-time (or daily) data capturing end-user actions (https://github.com/medic/cht-core/issues/6295), then a bespoke API endpoint (as suggested above) would not be required to configure these alerts. The alerts could be configured to trigger when there is a drop in syncronised end-user actions. This would measure the same signal and achieve the same end-goal, but would leverage a generic system capturing end-user actions which is broadly useful for other monitoring initiatives.

**Comment by MaxDiz** [comment]
Similar requests from team members related to connecting/syncing to the server:
- Attempted syncs
- Successful syncs
- Duration of sync
- Data used by sync

**Comment by michaelkohn** [comment]
Please allocate any time spent on this to `Project | 214 Research` in Clicktime.

**Comment by njogz** [comment]
Ready for AT on `6607-detect-when-users-unable-to-connect`

**Comment by ngaruko** [comment]
Tested on local

1. `connected_users` added to `monitoring` endpoint - admin not counted, was that intentional @njogz ?
![image](https://user-images.githubusercontent.com/6979995/121839117-8136b280-cd2d-11eb-841e-51eb33b51629.png)

2. `connected-user-<username>` saved in `medic-logs` db 
![image](https://user-images.githubusercontent.com/6979995/121839170-ac210680-cd2d-11eb-9fef-51b6d1707893.png)

3.

**Comment by njogz** [comment]
@ngaruko that's not intentional. It should count all users. Looking into it.

**Comment by njogz** [comment]
@ngaruko I am currently unable to replicate this with a similar setup as shown below. Please provide steps to reproduce if possible.
![image](https://user-images.githubusercontent.com/1227336/121846637-fedbcd80-ccef-11eb-88bc-ed0bf7d70e46.png)
![image](https://user-images.githubusercontent.com/1227336/121846701-1a46d880-ccf0-11eb-9b16-1df0cddda7e9.png)

**Comment by ngaruko** [comment]
@njogz I think it has to do with proxies. In this instance, I am using gold ol' `ngrok`, but after a little while, things get in sync. Even if that happens with `ngnix` and/or AWS, it is a matter of seconds, so I wouldn't think of it as an issue.

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by latin-panda** [comment]
@njogz do we need to add this `connected_users` to the [documentation](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv1monitoring) ? 🤔

**Comment by njogz** [comment]
> @njogz do we need to add this `connected_users` to the [documentation](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv1monitoring) ? 🤔

Yes. I will add it.
