### ISSUE TITLE
Find a better way to patch the webdriver version to build against

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6614]
**Describe the issue**
Every few months Chrome releases a new version and all our builds start failing. We apply [a patch](https://github.com/medic/cht-core/blob/master/tests/patches/webdriver-manager-config.patch) to use the latest version but this needs to be manually updated and then backported to every branch we want to build to get the build to pass again.

**Describe the improvement you'd like**
Either use a travis environment variable to define the version number in one place so it gets fixed for all branches at in one go.

**Describe alternatives you've considered**
Querying some page so it dynamically updates, but this may be difficult or flaky in its own way.

**Comment by dianabarsan** [comment]
Merged to `master`. No AT required.
