### ISSUE TITLE
Bug causing feedback "Duplicates in a repeater are not allowed"

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6627]
**Describe the bug**
Routine monitoring of BRAC feedback documents is surfacing a pattern with about 15 feedback docs/week over 1200 users.
I've confirmed that the configuration has only one version of the add family and add/edit chp area forms (both uploaded on live intance and in the codebase).

Feedback doc stacks are all similar to:
```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: form in actionBarCtrl.actionBar.right.relevantForms | orderBy: 'title' track by form.code, Duplicate key: family, Duplicate value: {\"code\":\"family\",\"title\":\"Add Family\",\"showUnmuteModal\":false}
https://errors.angularjs.org/1.7.8/ngRepeat/dupes?p0=form%20in%20actionBarCtrl.actionBar.right.relevantForms%20%7C%20orderBy%3A%20'title'%20track%20by%20form.code&p1=family&p2=%7B%22code%22%3A%22family%22%2C%22title%22%3A%22Add%20Family%22%2C%22showUnmuteModal%22%3Afalse%7D
    at https://brac-ug.app.medicmobile.org/js/inbox.js:3:1158914
    at https://brac-ug.app.medicmobile.org/js/inbox.js:3:1327629
    at https://brac-ug.app.medicmobile.org/js/inbox.js:3:1258267
    at c.$digest (https://brac-ug.app.medicmobile.org/js/inbox.js:3:1258942)
    at https://brac-ug.app.medicmobile.org/js/inbox.js:3:1260603
    at completeTask (https://brac-ug.app.medicmobile.org/js/inbox.js:3:1281175)
    at https://brac-ug.app.medicmobile.org/js/inbox.js:3:1192489", "message": "[ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: form in actionBarCtrl.actionBar.right.relevantForms | orderBy: 'title' track by form.code, Duplicate key: family, Duplicate value: {\"code\":\"family\",\"title\":\"Add Family\",\"showUnmuteModal\":false}

https://errors.angularjs.org/1.7.8/ngRepeat/dupes?p0=form%20in%20actionBarCtrl.actionBar.right.relevantForms%20%7C%20orderBy%3A%20'title'%20track%20by%20form.code&p1=family&p2=%7B%22code%22%3A%22family%22%2C%22title%22%3A%22Add%20Family%22%2C%22showUnmuteModal%22%3Afalse%7D"
```

This pattern is happening for the following duplicate keys:
* Duplicate key: family, Duplicate value: {\"code\":\"family\",\"title\":\"Add Family\",\"showUnmuteModal\":false}
* Duplicate key: chp_area, Duplicate value: {\"code\":\"chp_area\",\"title\":\"Add CHP Area\"}
* Duplicate key: chp_area, Duplicate value: {\"code\":\"chp_area\",\"title\":\"Edit CHP Area\",\"showUnmuteModal\":false}

**To Reproduce**
Unknown steps to reproduce this. Unable to reproduce in production as admin user.

**Logs**
feedback-2020-08-23T10:38:09.511Z-ee41ed68-daa0-4481-94bd-1d745b9942c3
feedback-2020-08-23T03:05:29.925Z-f58e3bf1-6447-4bc5-94d9-a58680c189f0
feedback-2020-08-23T17:52:38.797Z-08801a2b-971d-4739-9546-0a1986f92ce5

**Environment**
- Instance: https://brac-ug.app.medicmobile.org
- App: webapp
- Version: 3.9.1

**Comment by MaxDiz** [comment]
bumping to 3.12 to speed up 3.11 progress

**Comment by dianabarsan** [comment]
Ready for AT on `6627-track-by-db-id`

**Comment by newtewt** [comment]
I tested the forms detailed in the original description, also created a person, assessed a patient, and processed a family survey. Using both chrome and firefox.  I did not see the errors logged in console or after syncing in the meta DBs

I did see a `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).` in firefox. I'll log this separately. 

Moving this to Ready for merging @garethbowen

**Comment by dianabarsan** [comment]
> I did see a Content Security Policy: The page

Are you not getting the same on `master` ? I remember seeing these errors on Firefox alone all the time.

**Comment by newtewt** [comment]
@dianabarsan  yeah this seems to be FF only and occurs on master as well.

**Comment by dianabarsan** [comment]
Thanks for confirming.
