### ISSUE TITLE
Feedback documents are not created when contact-summary crashes

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6629]
**Describe the bug**
If there is an error which prevents a contact summary from loading, this error should be logged as a feedback document. These errors can sometimes be data-specific and hard to pin down.

**To Reproduce**
1. Create a contact-summary.templated.js which just contains `throw 'blah';`
1. `npx medic-conf compile-app-settings upload-app-settings --local`
1. Navigate to a contact profile
1. Look in the console logs, there are errors in the logs
1. Sync
1. Look for a document in the user's meta database with the error 'blah' that was thrown that can help an app builder debug the issue

**Expected behavior**
This should create a feedback document

**Environment**
- Instance: pih is having trouble right now, but all
- App: webapp
- Version: 3.9.1

**Additional context**
Here is 4 months of back-and-forth trying to pin down a problem which seems to be due to contact summaries.
https://github.com/medic/config-pih/issues/130

**Comment by garethbowen** [comment]
The same goes for errors in Task configuration. I reproduced this by hacking the raw task configuration in Settings doc, `tasks.rules`, so the rule looked like: `rule GenerateEvents {  when { c: Contact } then { throw 'blah'; } }`

The error is shown in the UI:

![Screenshot from 2020-12-22 14-22-26](https://user-images.githubusercontent.com/2064938/102837685-2ea4c980-4461-11eb-8d0b-b3a041182561.png)

And in the console...

![Screenshot from 2020-12-22 14-23-06](https://user-images.githubusercontent.com/2064938/102837708-3cf2e580-4461-11eb-901f-049bcbb89e31.png)

But no feedback doc is created.

**Comment by garethbowen** [comment]
Ready for AT in `6629-generate-feedback-docs`

Be sure to test broken configurations for both rules and contact summary.

**Comment by garethbowen** [comment]
This has been merged into the Angular branch, so AT should be done there (or in `master` if that is merged).

**Comment by newtewt** [comment]
In the case of just throwing an error the feedback doc includes notes about the contact-summary config.  Working on the rules errors now.
```
{
  "_id": "feedback-2021-03-02T14:25:23.672Z-a5327a68-9e73-4ee6-b3a3-37d1f1d45e14",
  "_rev": "1-a2628411ff540745b4908866dcefabfb",
  "meta": {
    "time": "2021-03-02T14:25:23.672Z",
    "user": {
      "name": "brinda",
      "roles": [
        "chw"
      ]
    },
    "url": "https://d5ae04acf4e8.ngrok.io/#/contacts/0b465c41-ef04-51a0-89fe-b61b5cf76e4b",
    "version": "master",
    "source": "automatic"
  },
  "info": "Configuration error in contact-summary function: undefined",
  "log": [
    {
      "level": "error",
      "arguments": "[\"Error selecting contact\",{}]"
    },
    {
      "level": "error",
      "arguments": "[\"Configuration error in contact-summary function: blah\"]"
    },
    {
      "level": "error",
      "arguments": "[\"Error fetching read status\",{\"status\":404,\"name\":\"not_found\",\"message\":\"missing\",\"error\":true,\"reason\":\"missing\",\"docId\":\"_design/medic-user\"}]"
    },
    {
      "level": "error",
      "arguments": "[\"Error selecting contact\",{\"code\":404}]"
    },
    {
      "level": "log",
      "arguments": "[\"Not found\"]"
    },
    {
      "level": "info",
      "arguments": "[\"RulesEngine Status: Enabled\"]"
    },
    {
      "level": "info",
      "arguments": "[\"Persistent storage denied: storage may be cleared by the UA under storage pressure.\"]"
    },
    {
      "level": "info",
      "arguments": "[\"Initiating changes watch (meta=true)\"]"
    },
    {
      "level": "info",
      "arguments": "[\"Initiating changes watch (meta=false)\"]"
    }
  ],
  "type": "feedback"
}
```

**Comment by newtewt** [comment]
@garethbowen  I believe there is some work to do. I am triggering an error in the task code by calling to a function that doesn't exist. The webapp fails and console shows the error `main.js:1 Unhandled Promise rejection: fakeFunction is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: fakeFunction is not defined` Looking through the feedback docs locally and on the synced server. I don't see any docs about that error. 

```
  {
    name: 'anc.pregnancy_home_visit.unknown_lmp',
    icon: 'icon-pregnancy',
    title: 'task.anc.pregnancy_home_visit.title',
    appliesTo: 'reports',
    appliesToType: ['pregnancy'],
    appliesIf: function (contact, report) {// If LMP date is unknown
      const recentLMP = getMostRecentLMPDateForPregnancy(contact, report);
      //We only want to show until 42 weeks + 7 days
      return !recentLMP && addDays(report.reported_date, MAX_DAYS_IN_PREGNANCY + 7) >= today;
    },

    resolvedIf: checkTaskResolvedForHomeVisit,

    actions: [
      {
        type: 'report',
        form: 'pregnancy_home_visit',
        label: 'Pregnancy home visit'
      }
    ],
    //every two weeks from reported date until 42nd week, show before due date: 6 days, show after due date: 7 days
    events: [...Array(21).keys()].map(i => generateEventForHomeVisit((i + 1) * 2, 6, 7))
  },
  ```
