### ISSUE TITLE
Nginx 404 Error

### ISSUE THREAD

**Issue by andrineM** [medic/cht-core#6631]
Platform
Linux 18.04
docker Version 19.04
docker-compose 1.25.4

We are having a issue when running Medic-os Docker Image on some linux machines. 

All services start successfully but accessing the application on the browser gives nginx 404 error as shown below:

![image](https://user-images.githubusercontent.com/53934661/91983569-8b566a00-ed34-11ea-8026-df4423ed5ec7.png)

As anyone ever had such an experience?

**Comment by nomulex** [comment]
@andrineM  please share the medic api logs.

**Comment by andrineM** [comment]
Hey Alex

Am noticing this from the logs

haproxy     | backend couch-backend2
haproxy     |   balance roundrobin
haproxy     |   server couchdb1 medic-os:5987
medic-os    | mesg: ttyname failed: Inappropriate ioctl for device
haproxy     | [alert] 245/134416 (1) : parseBasic loaded
haproxy     | [alert] 245/134416 (1) : parseCookie loaded
medic-os    | [2020/09/02 13:44:18] Info: Setting up software...
haproxy     | [ALERT] 245/134416 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:47] : 'server couchdb1' : could not resolve address 'medic-os'.
haproxy     | [ALERT] 245/134416 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:51] : 'server couchdb1' : could not resolve address 'medic-os'.
haproxy     | [ALERT] 245/134416 (1) : Failed to initialize server(s) addr.
haproxy exited with code 1



medic-os    | [2020/09/02 13:44:41] Info: Service 'system-services/cron' started successfully
medic-os    | [2020/09/02 13:44:41] Info: Service 'system-services/syslog' started successfully
medic-os    | [2020/09/02 13:44:42] Info: Setting up software (100% complete)...
medic-os    | [2020/09/02 13:44:42] Info: Starting services...
medic-os    | [2020/09/02 13:44:42] Info: Synchronizing disks...
medic-os    | Fatal: CouchDB failed to start properly
medic-os    | [2020/09/02 13:44:53] Info: System started successfully
medic-os    | [2020/09/02 13:44:53] Info: Starting log streaming

**Comment by nomulex** [comment]
I notice two things from this log

1. The Ha-proxy container can  not resolve the medic-os container address by name  
2.  The couch db process failed to start.  
Can't tell why the networking is not working (are you missing some  drivers ? ) but for the db we need to look at the couchdb logs to see what is inside.
Get into the container like this `docker exec -it medic-os /bin/bash`  then share the couchdb log at `/srv/storage/medic-core/couchdb/logs`. 
Lastly out of curiosity what is the OS of this machine ?

**Comment by derickl** [comment]
Also, how was docker set up?

From the default ubuntu repository or from docker's own custom repository? 
The latter would ensure that you always get the latest docker tools. I'm sharing this link for reference on [guidelines for CHT docker setup](https://docs.communityhealthtoolkit.org/core/guides/docker-setup/)

**Comment by andrineM** [comment]
The Docker installation is from docker's own custom repository.
The Medic0os setup is as provide on https://docs.communityhealthtoolkit.org/core/guides/docker-setup/
It important to note the installation works perfectly ok on some host but is failing on others with the error shared on logs

**Comment by nomulex** [comment]
The fact that it works on some and fails on others means the problem is unique to the failing machines. Is host networking an option on the failing machines ?  I share below a docker-compose snippet for using host networking. 
`version: '3.7'

services:
  medic-os:
    container_name: medic-os
    image: medicmobile/medic-os:cht-3.9.0-rc.2
    volumes:
      - type: bind
        source: ./srv
        target: /srv
    depends_on:
      - haproxy
    network_mode: host
    environment:
      - DOCKER_NETWORK_NAME=localhost
      - DOCKER_COUCHDB_ADMIN_PASSWORD=yourpassword

  haproxy:
    container_name: haproxy
    image: medicmobile/haproxy:rc-1.16
    volumes:
      - ./srv:/srv
    environment:
      - COUCHDB_HOST=localhost
      - HA_PASSWORD=yourpassword
    network_mode: host
`

**Comment by andrineM** [comment]
Hey Alex
This has worked okay on one of the hosts that was failing. I shall test the rest and get back.
Does this translate to us having to use ports 80 and 443 or are we able to map to other ports?
Reason I ask is because at the facilities we already have the EMR running on port 80.

**Comment by nomulex** [comment]
Okay host networking means all container generated ports are immediately available to the host.  So you can actually access medic-api on port 5988. You can then disable the medic-os nginx like this  `docker exec -it medic-os /bin/bash  -c "/boot/svc-disable medic-core nginx "`  You then access the app like this at http://localhost:5988. 

on a side note, it's intresting to see that you are doing installs at every facility. Is the client server-architecture  not an option? Because currently you don't have a central point for your data.
