### ISSUE TITLE
Be able to run unit tests from different apps in the CHT

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-core#6632]
**What feature do you want to improve?**
Running `grunt test` run all the tests in the repo, and there are a few tasks defined in `Gruntfile.js` to run some test suites separately but there is no easy way to run just the tests from Sentinel, and there is a way to run just the tests from the API but not working.

**Describe the improvement you'd like**
Define a few tasks in Grunt to be able to run tests just for the app the developer is working on, saving time when waiting the execution to complete.

**Describe alternatives you've considered**
Although is not impossible to run these tests separately, it's tricky and not documented. Adding tasks in Grunt will make it easier and "auto" documented, because Grunt allows to list all the tasks available executing `grunt --help`, so no need to read the long `Gruntfile.js` script to figure out that there are other ways to run the tests.

Currently you can run just the Sentinel tests from an IDE like IntelliJ / Webstorm but you need to create a configuration manually, and the configuration differ depending of the IDE you are using. You can also run the tests from the root of the project within the command line:

    $ node_modules/mocha/bin/mocha sentinel/tests/**/*.js  sentinel/tests/**/**/*.js

Same for the API replacing the paths, but not ideal and not documented.

**Additional context**
Supposedly you can run tests just from API with `grunt mochaTest:unit`, but many unit tests fail as follow:

```
...
...
    at Context.it (api/tests/mocha/services/purged-docs.js:34:53)                                      
                                                                                                       

  55) Purged Docs service
       listen
         should restart listener on error:

      AssertionError: expected 2 to equal 1
      + expected - actual

      -2
      +1

    at Context.it (api/tests/mocha/services/purged-docs.js:90:53)




Warning: Task "mochaTest:unit" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2020-09-02 12:42:55 UTC-0)
loading tasks   328ms  ▇▇▇ 3%
mochaTest:unit  10.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
Total 10.5s
```

In the PR I'll propose I solve the problem creating a new task that execute the same task above but prepending the `env:unit-test` task:

```js
  grunt.registerTask('unit-api', 'API unit tests', [
    'env:unit-test',
    'mochaTest:api',
  ]);
```

So executing `grunt unit-api` tests work and the execution time is the same.

Also not sure if I should propose a PR before the ticket was triaged and accepted, but the reality is that struggling to run the tests I made changes in the Gruntfile.js first with the plan to add the improvements in another ticket/PR I was working on, but then realized that the proposal needs a separated thread, so feel free to reject the whole idea/PR if there is better way to resolve this.

**Comment by dianabarsan** [comment]
The failures you're listing are probably caused by not setting the required environment variable `UNIT_TEST_ENV=1` (which is what 'env:unit-test' is doing).

**Comment by mrsarm** [comment]
@dianabarsan yes I know, but that is the point of create tasks in Grunt, to simplify the execution, it is shorter and intuitive do this:

    $ grunt unit-api

than this that is not even documented:

    $ UNIT_TEST_ENV=1 grunt mochaTest:unit

The `unit-api` alternative is shorter and auto-documented (listed in `grunt --help` with the patch provided).
