### ISSUE TITLE
Test Data and Config Updates

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6638]
- Reproducible / automated 
  - Create the data associtated to a config. Using csvs
  - Figure out where to store so it makes sense(config names, feature names, bug details, etc…) 
    - First thought was to use our [release-test-repo](https://github.com/medic/medic-release-testing) to store the data for a specific config. Possible add a readme or json file that details the data and config it is for. 
    - Add folders for features if need be with configs setup. 
    - Document this in whatever repo decided.  
            EX: data/feature/issue_id   contains configs for the feature, and mock data.
            EX: data/config_name/   contains any special configuration and data
  - Maintain this with versions - If we keep all data in 1 repo we can tag and version our configs so they stay up to date with the released versions
- Can we get real data with configs associated
  - Understand real life data and how it’s being used.  Potentially looking at postgres where data is synced.

**Comment by garethbowen** [comment]
I think this is obsolete now that we have the data generation script. Please reopen if I've missed something.
