### ISSUE TITLE
Telemetry to support proposed UX updates

### ISSUE THREAD

**Issue by n-orlowski** [medic/cht-core#6651]
Some questions that would be helpful to understand in order to inform the [proposed UX updates](https://docs.google.com/presentation/d/1SYai7f5OD2Xqqxwx7S5pF2m9T2lxAO_AIRn-8WrCHgM/edit#slide=id.p) to the CHT

- How much time do users spend in each tab? How often do they switch between tabs?
- How often do users open the guided tour? Which sections are reviewed most, if any? Where do they drop off?
- How often do users report bugs?
- Which action buttons (from FAB) are most used per tab?
- Which actions (from FAB) are most abandoned (ex. clicked “edit” then went back) per tab? 
- Usage rates of search
- Usage rates of filters
- Usage rates of bulk delete

**Comment by MaxDiz** [comment]
Adding to 3.13 based on roadmap discussion. Before implementing we should review the outcomes of the https://github.com/medic/cht-core/issues/6679 investigation to see if/how much of this data would be available through a telemetry platform implementation.

**Comment by n-orlowski** [comment]
We are able to do a usability session with PIH in February so we can drop this from 3.13 if needed

**Comment by MaxDiz** [comment]
removing this issue from v3.13. We can pick up again once the initial telemetry improvements are complete and we have a clearer idea of what is needed

**Comment by latin-panda** [comment]
@n-orlowski @michaelkohn is the Apdex resolving this?

**Comment by michaelkohn** [comment]
We've already done all the UX updates, so I'm not sure if it's still relevant. Below are some reflections. @n-orlowski please close this if you've got everything you want.

> How much time do users spend in each tab?
Not knowable from existing telemetry.

> How often do they switch between tabs?
We've seen how often they visit each tab.

> How often do users open the guided tour? Which sections are reviewed most, if any? Where do they drop off?
We've removed this.

> How often do users report bugs?
Not sure, but it's knowable.

> Which action buttons (from FAB) are most used per tab?
Really the only actions are creating contacts or forms, and we know how often they "render" and "save" all of those.

> Which actions (from FAB) are most abandoned (ex. clicked “edit” then went back) per tab?
We know this too, it's the difference between "save" and "render".

> Usage rates of search
We've done some research on this and it is not frequent. 

> Usage rates of filters
We've got telemetry for this too.

> Usage rates of bulk delete
Not sure.

**Comment by n-orlowski** [comment]
going to close since we have already addressed everything in the deck 👼
