### ISSUE TITLE
Add telemetry data on GPS

### ISSUE THREAD

**Issue by ecsalomon** [medic/cht-core#6653]
**Is your feature request related to a problem? Please describe.**
As a researcher, I want to know how GPS data collection and accuracy varies across users, configurations, versions, and time. This can help diagnose issues in GPS collection and answer questions about how changes to configuration and app affect the quality and completeness of the data we collect. It can also help implementers identify users who have turned GPS services off or denied access to GPS data collection in the app (in case this is considered critical for the deployment).

**Describe the solution you'd like**
I would like see something like the following collection of metrics, aggregated to user + month (+ version + configuration):

- Number and percentage of reports with an error / specific errors
- Number of reports with / missing GPS data
- Min, max, median, total, std dev of GPS accuracy

**Describe alternatives you've considered**
For some projects/personas, it may be valuable to add this information at the form-specific level. It might help to collect user stories to see if that is required. 

**Additional context**

**Comment by garethbowen** [comment]
I think this information can already be derived from the reports synced to postgres. Is there something missing? If not, what is the advantage of duplicating the data into user telemetry?

**Comment by ecsalomon** [comment]
Definitely true. The major motivation is that no projects are currently monitoring these things (at either a project or user level) and it's intensive and low priority for projects to set up since most known deployments aren't using GPS data for anything. Having it ready made in the app would make analysis of GPS data by data scientists much easier. But there are other paths (we certainly _know_ how to write the views).
