### ISSUE TITLE
isSensitive doesn't stop replication of reports when the patient_id is the subject of a report..

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6660]
**Describe the bug**
Reports that apply to the [sensitive documents](https://docs.communityhealthtoolkit.org/apps/guides/performance/replication/#sensitive-documents) logic should not replicate to a users app. In this case the report is using the `patient_id` to mark the subject. Which allows the user to see the document.  When we do the check in code to see if it should replicate we are referring to the UUID. 

**To Reproduce**
1. Have a hierarchy of facility A > B
2. Have a user1(supervisor) with facility of A for place associated to their contact
3. Have a user2(subordinate) with facility of B for place associated to their contact 
4. Using a report that assigns a `patient_id` and sets `doc.fields.private` to 'yes'.  I modified the `on` report in standard. 
5. Submit the report as User1 from User2 contact page. 
6. The report will display on User2's contact page. 
7. Log in as User2 and ensure to replicate. 
8. User2 sees the report that should not be replicated.  If you modify the doc and remove `patient_id` and then clear User2s cache and re-replicate. The user will not see that report. 

**Expected behavior**
We should be checking all ways that a report could possibly be about a person and filtering if the private field is set. 

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Windows
- App: webapp
- Version: 3.10

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
This appears to be a bug as old as the feature itself. As far as I can tell, we've never compared the user's contact's `patient_id` field to the reports' subjects, and always only compared the user's contact's uuid. 

This is the line that did this comparison in 2.13: https://github.com/medic/medic-api/blob/26093a244a16c39c97a94a8b19767141415a6c58/handlers/changes.js#L105
```
if (subject !== feed.contactId && subject !== feed.facilityId) {
```
where `feed.contactId` is `medic.org.couchdb.user:<user>.contact_id`.

**Comment by dianabarsan** [comment]
This is ready for AT on `6660-is-sensitive-for-shortcode`. Any valid subject (uuid, patient_id, place_id) from the facility or contact should matter towards determining whether a report is sensitive.

**Comment by newtewt** [comment]
I've tested these workflows and the report does not get replicated down to the subordinate user.  While reports without the private flag are still being replicated as expected. 

A report submitted that has both `patient_id` and `patient_uuid`
A report submitted that has `patient_id`
A report submitted that has `patient_uuid`
A report submitted on the users area with `patient_uuid`

Any other scenarios you can think of @dianabarsan ? Otherwise I'd say this is ready to merge.

**Comment by dianabarsan** [comment]
We should also include reports submitted for the homeplace, which are also sensitive. 
A report with `place_id` as its subject, with `place_id` being either the homeplace's shortcode or the uuid.

**Comment by newtewt** [comment]
That works as expected as well. I think we can merge.

**Comment by dianabarsan** [comment]
Merged to `master`.
