### ISSUE TITLE
Telemetry gathering for QA Release Test. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6661]
**What feature do you want to improve?**
We have telemtery that collects different things around the app the user interacts with. As part of our release testing, we collect some of these interactions manually with a stop watch. [Here ](https://github.com/medic/medic-release-testing/issues/2) is the release test issue for possible further clarity.   

**Describe the improvement you'd like**
It would be great if we could collect these workflows through the app using telemetry that we can just harvest at the end of a run. These are the interactions we would need. 

Time from logging on to finishing replication for first time log in with offline user. 

Time from click the Reload button on the about page until the app is present. It goes to a refreshing page screen. 

Time it takes to load the contacts tab from first navigation to the page.

Time it takes to load the reports tab from first navigation to the page. 

Time it takes from clicking report on left hand side to it loading on the right hand side. Or in mobile view becomes the present page.

Time it takes from clicking submit on a form to returning to the app. 

**Describe alternatives you've considered**
Alternatives currently are to time it manually with a stop watch. 

**Additional context**

**Comment by garethbowen** [comment]
Some of this data is collected already in user telemetry. There may be functions we can add to the testing page to make this easier to access. @newtewt Can you have a look and see if we're collecting the right data, and if it's easy enough to access currently?

**Comment by newtewt** [comment]
Unless something is broken. I ran through these workflows locally and there are no telemetry items collected.  I had 5 rows in the meta database. 3 were for read reports, 1 for the `_design/medic-user` and a feedback report.

**Comment by garethbowen** [comment]
Were you checking on the server? User telemetry is aggregated and replicated at the end of the month. Can you wind your clock forward and reload the app and then sync and check again?

We could add a button to the testing page to make this easier in future.

**Comment by newtewt** [comment]
I was looking at the indexed db for the `_pouch_medic-user-ac2-meta` database in the browser.  Would they be saved somewhere else?

**Comment by garethbowen** [comment]
Before aggregation the telemetry records are stored in 'medic-user-ac2-telemetry-<uuid>`.

**Comment by newtewt** [comment]
👍  I'll re-review what's collected and see what can be changed on this list.

**Comment by newtewt** [comment]
Reviewing the telemetry and the flows in the app I believe this is the correct flow to data mapping.  @garethbowen  can you review this for accuracy? I think after this review we might only need 1 new entry. Which I can then update this request. 

Time from logging on to finishing replication for first time log in with offline user.

```
rules-engine:initialize
boot_time
boot_time:3:to_angular_bootstrap
boot_time:2:to_bootstrap
boot_time:1:to_first_code_execution
```


Time from click the Reload button on the about page until the app is present. It goes to a refreshing page screen.

Second iteration of 
```
rules-engine:initialize
boot_time
boot_time:3:to_angular_bootstrap
boot_time:2:to_bootstrap
boot_time:1:to_first_code_execution
```

Time it takes to load the contacts tab from first navigation to the page.

``` search:contacts:types ```

Time it takes to load the reports tab from first navigation to the page.

```
search:reports - reports page
search:reports:subjectIds
```

Time it takes from clicking report on left hand side to it loading on the right hand side. Or in mobile view becomes the present page.

I didn't find any telemetry for this one. 

Time it takes from clicking submit on a form to returning to the app.

``` enketo:contacts:pregnancy:add:save ``` caveat being the name of the report here.

**Comment by newtewt** [comment]
Also a side note. I think this would probably be easily automatable.

**Comment by garethbowen** [comment]
I think the tab loading times won't be accurate - `search:contacts:types` is only a small part of the overall loading time.

**Comment by newtewt** [comment]
Can we then add to the click and then page render or are you thinking about alternatives?

**Comment by newtewt** [comment]
That sounds good to me @garethbowen.  I'm not sure I understand where the point starts and ends well enough to be able to define it in a this ticket so that a developer could add it. I also have some time now that I could possibly add it if we had it defined well. Would you want to take a few minutes to chat about it?

**Comment by garethbowen** [comment]
I think we should add telemetry in the angular router so we record the rendering phase for all pages, but this will change significantly with Angular v10 so we may need to hold off until that is done.

**Comment by dianabarsan** [comment]
I believe telemetry has greatly improved in the last 4 years. 
Closing as ancient, pending future QA needs.
