### ISSUE TITLE
update remove_non_admin_users.js script to work at all, also work with http

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6663]
**Describe the issue**
The `remove_non_admin_users.js` script doesn't seem to work as it is using an object from `url.parse()` as a string.  Further, it only worked with https, thus was hard to test against local dev instances.  Here's the error output when I run it:

```
node remove_non_admin_users.js                                                       
starting with URL:"http:"                                           
https.js:291                                                                             
        throw err;                                                                                       
        ^                                                           
                                                                                         
TypeError [ERR_INVALID_URL]: Invalid URL: [object Object]/_users/_all_docs
    at onParseError (internal/url.js:256:9)                                        
    at new URL (internal/url.js:332:5)                                                                          
    at request (https.js:287:30)                                                      
    at Object.get (https.js:318:15)                                                                      
    at Object.<anonymous> (/home/mrjones/Documents/MedicMobile/cht-core/scripts/remove_non_admin_users.js:18:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)                  
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)                                                     
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {                       
  input: '[object Object]/_users/_all_docs',                                                                   
  code: 'ERR_INVALID_URL'                                                    
}  
```

This will solve [CMoHM#103](https://github.com/medic/config-moh-mali/issues/103)

**Describe the improvement you'd like**
We should write a script update the script to work and be compatible with https.  

**Describe alternatives you've considered**
Manually deleting 600+ CHW passwords via the web GUI.

**WARNING WHILE TESTING** - this script will no joke delete all the users that are not literally `admin` or `_design/_auth`. Please test with care.

Otherwise, to test:
1. set up cht-core with at least one user not named `admin` or `_design/_auth`
1. log in the web GUI with a user who will get deleted
1. assuming your instance is accessed with `http://admin:pass@localhost:5988` you would run:
   ```
   COUCH_URL=http://admin:pass@localhost:5984/medic node remove_non_admin_users.js
   ```
1. ensure:
   1.  `admin` or `_design/_auth` users are not deleted and each gets a `Skipping {{user}}` debug otuput
   1. any other are deleted and debug is show: `Response from Deleting org.couchdb.user:deleteme4 {{JSON RESPONSE HERE}}`
1. in the web GUI the user that was deleted should no longer be logged in (session expired) and you should no longer be able to log in.
1. to be extra thorough, set up ngrok or pagekit in front of your dev instance and retest, ensuring the `https` URL works as well.

**Comment by garethbowen** [comment]
Instead of changing the password why not delete the users? If that would work, then the script for removing non-admin users would suffice?

**Comment by mrjones-plip** [comment]
Ah - for the most part that would work!  We also want to keep some users per [CMoHM#104](https://github.com/medic/config-moh-mali/issues/104), but it looks like we could just do a one off and add [a few more exceptions](https://github.com/medic/cht-core/blob/a9ef90bb3edd2958ca913ba20e2e82c364696e2e/scripts/remove_non_admin_users.js#L31) for those users in the delete users script.  Thanks @garethbowen! (Though now I won't get to write a new script to practice my nascent JS skilz on ;)

**Comment by mrjones-plip** [comment]
@garethbowen  - going for the delete approach!  Re-aligned this ticket to be that - sorry if that's not our normal MO - let me know if not.
