### ISSUE TITLE
End time stamp records same value as start time stamp 

### ISSUE THREAD

**Issue by iesmail-znz** [medic/cht-core#6670]
I am running CHT **version 3.9.1** and I have added the `start` and `end` timestamps under the meta tag in my` clinic-create` and `person-create` XLSForms. 

When I look at the values in couch, I see that the `end time = start time. `  I also want to point out that these timestamps work fine in the app forms. 

[clinic-create.xlsx](https://github.com/medic/cht-core/files/5356486/clinic-create.xlsx)

**Comment by abbyad** [comment]
Thanks for reporting the issue. It is reminiscent of https://github.com/medic/cht-core/issues/5768, where `start` and `end` were fixed for `app` forms, but `contact` forms were perhaps not considered and tested at the time.

**Comment by latin-panda** [comment]
This is ready for AT in [this PR](https://github.com/medic/cht-core/pull/7404#pullrequestreview-799077109)

The [meta fields](http://xlsform.org/en/#metadata) should have now the right values when saving in the DB. These fields should be inside a group, for example the place (clinic, etc) group.
Top level elements on contact forms [have very specific functionality and constraints](https://docs.communityhealthtoolkit.org/apps/guides/forms/contact-forms/) when it comes to storing data back to the database. Only the top-level elements that are groups will be saved.

**Comment by ngaruko** [comment]
Tested using the [form in the ticket description.](https://github.com/medic/cht-core/files/5356486/clinic-create.xlsx)..
1 - created a clinic (using the form above)
2 - noted the UUI
3 - checked the doc in the db: `http://localhost:5988/_utils/#database/medic/<clinic-uuid>`

on **_master_**, end and start times are the same:
```
 "meta": {
    "start": "2021-11-16T17:03:16.450+13:00",
    "created_by": "tali",
    "created_by_person_uuid": "2b0989621bde7e9777d147978800103d",
    "created_by_place_uuid": "2b0989621bde7e9777d1479788000aa9",
    "end": "2021-11-16T17:03:16.450+13:00"
  },
  "type": "clinic",
  "reported_date": 1637035413377,
  "place_id": "57484"
}
```
_**BUT on the branch, they are different:**_
```
"meta": {
    "start": "2021-11-16T16:56:56.760+13:00",
    "created_by": "tali",
    "created_by_person_uuid": "2b0989621bde7e9777d147978800103d",
    "created_by_place_uuid": "2b0989621bde7e9777d1479788000aa9",
    "end": "2021-11-16T16:57:14.400+13:00"
  },
  "type": "clinic",
  "reported_date": 1637035034420,
  "place_id": "13122"
}
```
Ready to merge @latin-panda .

**Comment by latin-panda** [comment]
Work is merged into the main branch
