### ISSUE TITLE
Allow more granular synchronizing/purging of hierarchical documents 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6686]
## This is a draft!! We'll remove this top text when it's done
---

**What feature do you want to improve?**
Currently when a supervisor wants to get reports of just CHWs, but not patients, too many documents are synchronized.  This is because in a high density deployment (many documents (patients) per CHW) it means that a supervisor may have thousands of documents to synchronize.  This can become slow and approach the 10k document/device cht-core limitation. 

**Describe the improvement you'd like**
Based of the requirements of the CMoHM supervisor's role, allow more granular control of what documents get synchronized. 

**Describe alternatives you've considered**
We've had to introduce aggressive client side purging to ensure enough documents are removed from supervisor to ensure the app remains usable.

**Additional context**
Ticket is lacking details, but was original documented in [CMoHM#115](https://github.com/medic/config-moh-mali/issues/115)

**Comment by garethbowen** [comment]
Would this be solved by https://github.com/medic/cht-core/issues/6543 ?

**Comment by mrjones-plip** [comment]
@garethbowen  - Oh!! It might!  Thanks so much for reviewing this ticket even though it's still a draft.  @Marina-Kenf (and possibly @Fatoufall ), could you review #6543 and let us know that suites your needs?

**Comment by Marina-Kenf** [comment]
Hey @mrjones-plip thanks.
#6543 could be very useful for CMohM as they intend not to have a static assignment of areas to CHWs.
But, our need was mostly to be able to use the replication_depth and select what we want to keep under a supervisor that is having just one level under him (which includes the CHW and their patients - both at the same level). It seems that it could be possible when we upgrade to 3.10 as you can see option 2 in [#115](https://github.com/medic/config-moh-mali/issues/115) and [supervisor-signoff](https://github.com/medic/config-moh-mali/issues/115).

**Comment by mrjones-plip** [comment]
@Marina-Kenf - Gotcha - thanks for the update.  If this ticket is no needed then because 3.10 has what we need, let's close this ticket.  If this ticket is still needed, please update it to be accurate (i'm sure I got it wrong ;).  Let me know if you don't have edit perms!

**Comment by mrjones-plip** [comment]
Chatted with Marina and she confirmed the upgrade to 3.10 will suffice for this. closing!
