### ISSUE TITLE
Expose task ID to Enketo

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6690]
**Is your feature request related to a problem? Please describe.**
When integrating with OppiaMobile we have configured a task which loads a form with a link which loads the Oppia Android app if installed. When the user has finished the course, Oppia renders a link to return to the CHT. The same task should then be loaded so the user can continue through the form. We can configure the link to pass a URL to Oppia, but there's currently no way to find the ID of the task to load.

**Describe the solution you'd like**
Add the task ID to the context so it's available when rendering the form.

**Describe alternatives you've considered**
We could add the current URL to the context.

**Comment by garethbowen** [comment]
This bug will also have to be fixed to get this to work: https://github.com/medic/cht-core/issues/6139

**Comment by njogz** [comment]
Ready for AT on `6690-expose-task-id-to-enketo`

**Comment by meghna-khemka** [comment]
`task_id` is now being populated when rendering the form. Tested by displaying it as a `note` field:

<img width="1229" alt="Screen Shot 2021-06-16 at 9 57 03 PM" src="https://user-images.githubusercontent.com/84743933/122334207-33b57380-ceee-11eb-880a-68d0642bc350.png">

Issue working fine.

**Comment by njogz** [comment]
Merged to master.
