### ISSUE TITLE
Improve 3.10 release notes with compatibility matrix between android 0.5 and cht-core 3.10

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6693]
**What feature do you want to improve?**
Release notes for 3.10

**Describe the improvement you'd like**
There seem to be some nuanced details about the compatibility of android wrapper v0.5 and cht-core >3.10.

In particular:

> If your instance < v.3.10 and your user newly installs medic-android 0.5.0 on an Android >= 6(?) device, medic-android will never request location permissions and no GPS data will be recorded for that

**Comment by garethbowen** [comment]
@kennsippell I've added a [release notes section](https://github.com/medic/medic-android#release-notes) to the medic-android README. Let me know if this isn't sufficient!
