### ISSUE TITLE
Clicking on the Android back button while creating a new report minifies the app and generates feedback doc

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6698]
This has been reported several times and is a long standing bug:
see: https://github.com/medic/cht-core/issues/5298
or more recent: https://github.com/medic/config-covid-moh-ke/issues/117

**To Reproduce**
1. Login using the android-app (using an admin account will make syncing instant, but any account will work)
2. From the reports tab, open a new form.
3. Touch the Android back button
4. Observe that your app gets minified instead of redirecting you to "some page".
5. If you are logged in as an offline user, reload the app to trigger a metaDB sync. If online, skip to 6.
6. On your server, check the feedback docs generated by your user. You should find a recent feedback doc that has this info:
```
 "info": "Attempt to back to an undefined state [AndroidApi.back()]",
```

**Expected behavior**
Firstly, no feedback docs should be generated from this action!
Secondly, the app shouldn't "minimize", I think the idea was to redirect the user to the "previous" page, although the specific redirects for each page were never established. See this issue: https://github.com/medic/cht-core/issues/1565

**Environment**
- Instance: any? I think this bug goes back to 2.x
- Client platform: Android app
- App: webapp
- Version: any 3.x

**Additional context**
This is the relevant piece of code:
https://github.com/medic/cht-core/blob/master/webapp/src/js/services/android-api.js#L145
```
// If we're viewing a tab, but not the primary tab, go to primary tab
const primaryTab = $('.header .tabs').find('> a:visible:first');
if (!primaryTab.is('.selected')) {
  const uiSref = primaryTab.attr('ui-sref');
  if (uiSref) {
    $state.go(uiSref);
    return true;
  } else {
    const message = 'Attempt to back to an undefined state [AndroidApi.back()]';
    Feedback.submit(message).catch(err => {
      $log.error('Error saving feedback', err);
    });
  }
}
```
The problem is that **no tabs are visible when we view a "content page"**, such as a new report page.

I happened upon this bug while creating the new "integration api" that would replace `angular.element(document.body).injector().get(<serviceName>);`. 

I think we should definitely fix the feedback doc generation and maybe have the app not lose focus? 
I think everything else requires some design decisions.

**Comment by garethbowen** [comment]
This block should be reworked to not rely on jquery selectors - they're too brittle. There's code in the Home controller to work out which tab is the "primary" tab, and we can check the router to see if it's the currently selected route. That should be much more reliable than this code...

**Comment by dianabarsan** [comment]
I was thinking we could even call "cancelCallback" (that will display the "are you sure modal", if it's relevant) before redirecting.

**Comment by latin-panda** [comment]
1. What we need to do is removing this block:
```
} else {
    const message = 'Attempt to back to an undefined state [AndroidApi.back()]';
    Feedback.submit(message).catch(err => {
      $log.error('Error saving feedback', err);
    });
}
```
Because we don't want to log a `Attempt to back...` feedback, right?

2. Do we want to go back to the currentTab (it is in the store) or we want to go back to the primary tab (first tab)?

**Comment by dianabarsan** [comment]
> Do we want to go back to the currentTab (it is in the store) or we want to go back to the primary tab (first tab)?

I think we should primarily call `cancelCallback` as there are even redirects baked in.

**Comment by dianabarsan** [comment]
> What we need to do is removing this block:

We need to stop using tabs (like html selector tabs) to get which tab is primary or which tab is selected. We should never be in an "undefined state".

**Comment by latin-panda** [comment]
> We need to stop using tabs (like html selector tabs) to get which tab is primary or which tab is selected. We should never be in an "undefined state".

Okay, my understanding is that we leave the error and make a better determination of the "primary tab", because if it fails it's because we _really_ don't have tabs configured. 👍

**Comment by dianabarsan** [comment]
I _think_ we could just use the HomeComponent (https://github.com/medic/cht-core/blob/master/webapp/src/ts/modules/home/home.component.ts) to do this "primary tab" selection and: 
1. Keep all logic in one place
2. Use the logic we already have.

**Comment by latin-panda** [comment]
I found a similar logic in the header component for defining `permittedTabs`. I think the headerTabsService can handle this in one place 👍 Thanks!

**Comment by latin-panda** [comment]
This is ready for AT in this [PR](https://github.com/medic/cht-core/pull/7192).
The work done also fixes this [ticket](https://github.com/medic/cht-core/issues/7203).

**Comment by ngaruko** [comment]
LGTM.
Also checked #7203 on device
**before**

https://user-images.githubusercontent.com/6979995/128449940-9854ae8d-eba6-487c-9cd7-48de9ea268f4.mov


**after**

https://user-images.githubusercontent.com/6979995/128449952-ba354919-5beb-4bf5-a99e-86f44b0f51e4.mov

**Comment by latin-panda** [comment]
Merged to main branch.
