### ISSUE TITLE
Flaky test: sms-gateway api - api returns list of pending WO messages - returns list and updates state

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6702]
**Describe the issue**
I've seen a few builds (https://travis-ci.org/github/medic/cht-core/jobs/739931444) fail with this error:

```
1) sms-gateway api - api returns list of pending WO messages - returns list and updates state
  - Failed: stale element reference: element is not attached to the page document
    (Session info: headless chrome=86.0.4240.111)
    (Driver info: chromedriver=85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}),platform=Linux 4.15.0-1077-gcp x86_64)
```

**Why Now?**
Partner(s): Internal
Reason(s): Internally needs this ticket to facilitate the release, or reduce technical debt

**Comment by garethbowen** [comment]
Not a blocker for 3.15.0

**Comment by garethbowen** [comment]
Current success rate: 83%

**Comment by garethbowen** [comment]
Related: #8414

**Comment by dianabarsan** [comment]
I believe this was fixed via https://github.com/medic/cht-core/issues/8414
