### ISSUE TITLE
add patch template

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6724]
**Describe the issue**
TBD, but add a sibling to https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_major.md which is that same form paired way down for just patch level so we capture needed info for patch release

also rename existing  `z_release_major.md` -> `z_release_major_minor.md` to acknowledge the existing one is for those two ;)

**Describe the improvement you'd like**
A clear and concise description of what you want to change.

**Describe alternatives you've considered**

**Comment by garethbowen** [comment]
Is [this](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_patch.md) what you mean?

**Comment by mrjones-plip** [comment]
Hahah!  Yes, that's **_exactly_** it ;) Thanks @garethbowen !  I'll close this ticket then. I'd filed this while on the call and clearly hadn't done any research.

FYI @abbyad @michaelkohn  & @MaxDiz - Gareth pointed out the thing I asked for already exists. These two pop up on the bottom of the ["new issue" form](https://github.com/medic/cht-core/issues/new/choose):

*  Major/minor release - Schedule a major or minor release
*  Patch release - Schedule a patch release
