### ISSUE TITLE
Design and configure a reference app for MNCH workflow

### ISSUE THREAD

**Issue by maremegaye** [medic/cht-core#6727]
Design and configure a Maternal, Newborn and Child Health (MNCH) reference app for the CHT including these below workflows:

- Growth monitoring 
- Immunization 
- Child assessment

This results in the follow forms and follow up forms:
- Immunization and growth
   - Immunization and growth follow up
   - Child development follow up
- Child assessment
   - Child treatment follow up
   - Child referral follow up
   - Malnutrition follow up

Hierarchy of Forms:

![mnch](https://user-images.githubusercontent.com/8253488/101387816-d91ec900-3873-11eb-974d-b7cc138bb9d0.png)

Related resources:
* [Google Slides Presentation](https://docs.google.com/presentation/d/1RhgeFlhP0hPW9KfN80X-pHql-U8aOMk9qjuno2wW32Q/edit#slide=id.ga8dec5a146_0_0) with overview of workflows designed for different partners. 
* [Immunization and growth Google Drawing](https://docs.google.com/drawings/d/1uTIi8gcHHEOF4zw946Mn3LlbSOlUpFcuHLRgHMQwwe0/edit) 3 columns: Condition -> Task -> Resolution
* [Child assessment Google Drawing](https://docs.google.com/drawings/d/1rg5Ygq-_-GV4ZMREW81kLO_FoaMdEg7rikcHx2xyxg0/edit) 3 columns: Condition -> Task -> Resolution
* [xforms in xlsx for 7 forms](https://drive.google.com/drive/folders/14rxza8AaC6m7Y0JHZDUBfy4nhneMtctj?usp=sharing) 
* [CHT core pull request](https://github.com/medic/cht-core/pull/6768)
* [CHT docs pull request](https://github.com/medic/cht-docs/pull/422)
* [Google Drawing of form hierarchy](https://docs.google.com/drawings/d/1M3eat_G3tLFBZZELfL5PEEGdZXdrLHqNN2XuWMg1dmw/edit)  (based of ANC presentation below)
* [Main Google Sheets design doc](https://docs.google.com/spreadsheets/d/1_V7tQsH5fO08PAOdfOUPElsSZVfMQO0vx7XLQqYizZ0/edit#gid=234762789)
* [PO Team testing results doc](https://docs.google.com/spreadsheets/d/1f1Xql96Q7KKaIY7L4mbNWKBO1jC1ZSKf2H8F_hbWuGk/edit#gid=0)
* [ANC presentation - Editable design](https://docs.google.com/presentation/d/162Ey98J59ztkm-lF-ywezyVv1mldgc4xSVDkqkSUX04/edit#slide=id.g5eb1bb5ba9_0_323)
* [Public Demo Instance cht-mnch.dev.medicmobile.org](https://cht-mnch.dev.medicmobile.org)

**Comment by maremegaye** [comment]
Updates of design documentations

[XLS](https://docs.google.com/spreadsheets/d/1_V7tQsH5fO08PAOdfOUPElsSZVfMQO0vx7XLQqYizZ0/edit#gid=0)
[Immunization and growth workflow](https://docs.google.com/drawings/d/1uTIi8gcHHEOF4zw946Mn3LlbSOlUpFcuHLRgHMQwwe0/edit)
[Child assessment workflow](https://docs.google.com/drawings/d/1rg5Ygq-_-GV4ZMREW81kLO_FoaMdEg7rikcHx2xyxg0/edit)
[Form hierarchy](https://docs.google.com/drawings/d/1M3eat_G3tLFBZZELfL5PEEGdZXdrLHqNN2XuWMg1dmw/edit)

cc @mrjones-plip @abbyad

**Comment by mrjones-plip** [comment]
@michaelkohn  or @abbyad - I think we can all agree that my "secret" [party form icon](https://user-images.githubusercontent.com/8253488/101107968-5b637080-3588-11eb-804f-5311bb53b10c.png) @n-orlowski may or may not have designed is totally awesome, but I actually do wonder at what point we get real icons for these forms?  Is now the time? Should I spin up a separate ticket to track this request?

**Comment by abbyad** [comment]
You'll find some icons that should be suitable in the [icon library](https://docs.communityhealthtoolkit.org/design/icons/). If additional ones are needed we can create requests for that, but I think you'll be good to start with the [growth](https://docs.communityhealthtoolkit.org/design/icons/forms_tasks_targets/SVGs/icon-child-growth.svg), [immunization](https://docs.communityhealthtoolkit.org/design/icons/forms_tasks_targets/SVGs/icon-healthcare-immunization.svg), and [assessment](https://docs.communityhealthtoolkit.org/design/icons/forms_tasks_targets/SVGs/icon-healthcare-assessment.svg) icons in the [Icons for Forms, Tasks, Targets](https://docs.communityhealthtoolkit.org/design/icons/forms_tasks_targets/) page. And you'll be happy to see that they are SVGs! 😄

**Comment by mrjones-plip** [comment]
Awesome, thanks for the icon guidance @abbyad.

**Comment by mrjones-plip** [comment]
@n-orlowski  - can you assist w/ FA selection or approval? per [our slack chat](https://medic.slack.com/archives/CUXB9SVT5/p1607643798039400), I'm kinda guessing at what I should use here and having trouble finding existing examples.

If there's a more holistic approach we can do to  update the docs - I'm happy to transfer the info over to [the docs](https://docs.communityhealthtoolkit.org/design/best-practices/#summary-page) after we fix up this issue.

thanks thanks!

Our options are limited to [FA v4.7](https://fontawesome.com/v4.7.0/cheatsheet/) and given our rules are that every summary header needs an icon, I need ones for:
* Summary - currently  `fa-user` (commonly used already)
* Immunization and Growth monitoring - currently  `fa-check`
* Baby's Details - currently `fa-vcard` 
* Visit Findings - currently `fa-child`
* Vaccines -  currently `fa-child` (re-use not allowed!)
* Growth monitoring - currently `fa-list`
* Referral (aka danger signs) - currently `fa-exclamation-triangle`
* Follow Up Tasks - currently `fa-flag`

Here's a screenshot of all that:

![mnch summary](https://user-images.githubusercontent.com/8253488/101948565-1d2d0900-3ba7-11eb-9a89-0f0cc9e3e895.png)

FYI @abbyad

**Comment by n-orlowski** [comment]
@mrjones-plip  Here are a few suggestions that might work (I kept the ones the same that are commonly used as you mentioned):

Summary - `fa-user` 
Immunization and Growth monitoring - `fa-calendar-check-o`
Baby's Details - `fa-vcard` 
Visit Findings - `fa-child` or `fa-info-circle` or `fa-medkit`
Vaccines -  `fa-child` 
Growth monitoring - `fa-line-chart`
Referral (aka danger signs) - `fa-exclamation-triangle`
Follow Up Tasks - `fa-flag`

**Comment by mrjones-plip** [comment]
@n-orlowski - awesome, much thanks!

**Comment by mrjones-plip** [comment]
@michaelkohn - should we move this to the "in progress" column now that I'm actively working on this?

**Comment by michaelkohn** [comment]
Sure! Done :-)

**Comment by mrjones-plip** [comment]
While I do live the @n-orlowski 's party icon we have, it's really great to see the final icons @maremegaye  selected in place :tada: :taco: :

![icons in place 2](https://user-images.githubusercontent.com/8253488/104072774-f0c5d600-51c0-11eb-8f4b-4c1e70f61226.jpg)

**Comment by mrjones-plip** [comment]
The larger rollout of the MNCH app has been stalled for over 8 months. I'm going to close all the tickets and PRs. If we want to re-open them to work on this again, all good!
