### ISSUE TITLE
Add readme.md in demo-forms dir: how to load forms into CHT

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6728]
**Describe the issue**
There's a whole collection of forms that QA et al. uses to test the product in [`demo-forms`](https://github.com/medic/cht-core/tree/master/demo-forms).  It'd be good to document how these work - mainly how to load them up into an existing CHT instance both via `medic-conf` as well as via the admin web GUI.

**Describe the improvement you'd like**
Add a `readme.md` to  [`demo-forms`](https://github.com/medic/cht-core/tree/master/demo-forms)

**Describe alternatives you've considered**
Bother my co-workers, read the [docs.](docs.communityhealthtoolkit.org/)

**Comment by garethbowen** [comment]
Merged.
