### ISSUE TITLE
CouchDB Failed To Start properly error

### ISSUE THREAD

**Issue by andrineM** [medic/cht-core#6736]
I get this error when deploying medic-os on selective machine. Has anyone ever experience the same and how did you resolve?
![image_2020_11_18T14_41_26_295Z](https://user-images.githubusercontent.com/53934661/99545223-38509280-29c6-11eb-8d6a-b310a101f812.png)

**Comment by Hareet** [comment]
Hi @andrineM ! Thanks for opening the issue.

Please take a peak into your CouchDB logs, following: https://docs.communityhealthtoolkit.org/core/guides/docker-setup/#once-inside-container

Can you list your operating system and describe your `selective machine` ?

**Comment by andrineM** [comment]
The machine is running Ubuntu Server 18.04 version

**Comment by nomulex** [comment]
Hi @andrineM ,  Could you share the couchdb logs as well as hinted on by @Hareet above?

**Comment by nomulex** [comment]
Hi @andrineM any updates on this?

**Comment by garethbowen** [comment]
Closing as there has been no update for 6 months.
