### ISSUE TITLE
Add version of android app in app and in telemetry

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6741]
## Original In App request:

**Describe the issue**
This might be better in the android repo but I figure it requires cht-core work too. 

We have a lot of flavours of android app now. It would be good if we could provide details around the version of the android app, which flavor(crosswalk or webiew) and the build number in the webapp. This would help to identify if there are problems with a specific version or flavor etc...

**Describe the improvement you'd like**
Add details to the about page to get more info about the android eco system. 

**Describe alternatives you've considered**
None. 

## Additional in telemetry request

Right now we have some [user telemetry](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/#metadata), including `userAgent`, however we do not appear to capture the flavor (crosswalk or webiew) or build number.  Ideally these could be captured in discrete fields instead of concatenated into a super  `userAgent`, but that's a detail left to the implementer.  See @garethbowen's [notes below](https://github.com/medic/cht-core/issues/6741#issuecomment-799807547) too.

**Comment by garethbowen** [comment]
The current code just returns the `versionName` from the PackageInfo ([docs](https://developer.android.com/reference/android/content/pm/PackageInfo#versionName)). We should include more information, particularly the [packageName](https://developer.android.com/reference/android/content/pm/PackageInfo#packageName) and [versionCode](https://developer.android.com/reference/android/content/pm/PackageInfo#getLongVersionCode()) which is a little cryptic but will uniquely identify exactly which apk is running.

**Comment by garethbowen** [comment]
This should also be included in telemetry and feedback docs.

**Comment by MaxDiz** [comment]
I've added this to 3.12 to align with our other planned telemetry improvements

**Comment by mrjones-plip** [comment]
@garethbowen  and @newtewt - I'm warming this up in prep for it to be actionable in 3.12 and had some questions (so no real rush, but when you get a sec ;)
* Is this meant to be visible on the mobile device from with in the android app?  So it'd be something any end user could see, yeah? 
* Additionally, are we looking to add to [existing metadata we already](https://docs.communityhealthtoolkit.org/apps/guides/performance/telemetry/#metadata) aggregate, yeah?  This would then be ferried back to couch and ultimately to couch2pg, right?

**Comment by garethbowen** [comment]
> Is this meant to be visible on the mobile device from with in the android app? So it'd be something any end user could see, yeah?

There is already a field in the About page which shows the version of the medic-android app but it's light on detail (that's what my comment was trying to get it). My proposed fix is to modify the medic-android app slightly to include more information in the string that's currently returned and then it'll magically work with existing cht-core webapps.

> Additionally, are we looking to add to existing metadata we already aggregate, yeah? This would then be ferried back to couch and ultimately to couch2pg, right?

Right! That metadata is for Telemetry docs and adding this will allow us to do analysis on what apks are installed. I also proposed it be included in the Feedback docs so if we're debugging issues reported from users we can easily see if it's related to a specific apk (eg: crosswalk apk keeps crashing).

The downside of my proposed solution is by concatenating the info together in medic-android it makes it harder to do any analysis of the Feedback and Telemetry docs, for example, it would be easier to write a sql query if all the version data was stored in separate fields.

One improved solution would be to make the change as suggested above which keeps backwards compatibility, but then also provide 3 (or more) other methods to provide each piece separately. Then we can make a change to cht-core to call the three fields separately, which means we can easily query the data once cht-core has been upgraded.

**Comment by mrjones-plip** [comment]
OK - awesome thanks @garethbowen  - all makes sense.

@marialma  and @helizabetholsen - if your ears weren't burning already, they should be now ;)  Again, no rush, but we're getting close to moving on these.

I suspect as we get closer [3.12](https://github.com/orgs/medic/projects/55), we should have a holistic look at all the telemetry tickets to ensure they all line up, compliment each other (as opposed to being in a disarray and conflicting ; )

**Comment by michaelkohn** [comment]
Please allocate any time spent on this to `Project | 214 Research` in Clicktime.

**Comment by helizabetholsen** [comment]
It would be useful for us to be able to aggregate these data on cht-core across projects to ensure we understand which version of the app each partner is running currently [currently have version of cht-core included], as well as the original version [@yrimal notes that this is technically possible and he will link the ticket here], and how many times a given project has updated their version of cht-core [@mrjones-plip this would be the additional ask, I believe]

Does this make sense?

**Comment by mrjones-plip** [comment]
@helizabetholsen - thanks for the input!  this ticket will be scoped to just showing the version and related information in the app itself per Nick's original comment.  

If R&L would like to gather/aggregate this information, or other related info, we should open another with a specific feature request along with the user story as what is the intent for gathering the info.

**Comment by abbyad** [comment]
I think having the info in telemetry data goes beyond the needs of R&L, as this is going to be extremely useful when we are debugging live incidents, eg to know if the issue is limited to particular variants. From that perspective, having this info in telemetry should be part of this issue, and not prioritized as a separate feature/issue.

**Comment by mrjones-plip** [comment]
@abbyad  - awesome! Thanks for the input and for reaching out for the ad hoc call just now.  Per our chat, I can see the value of adding the data to telemetry, especially given we may not work on this any time too soon after this ticket and the sooner we get it deployed, the sooner we can run reports that R&L mentioned above.

I'll update the title of this ticket and extend the body (but not overwrite so the conversation above stays relevant)!

**Comment by latin-panda** [comment]
@garethbowen There's a method that already gathers [detailed information](https://github.com/medic/cht-android/blob/4a306a982c60cbc01f341373bfe31114724bd97a/src/webview/java/org/medicmobile/webapp/mobile/MedicAndroidJavascript.java#L230) about the app and it's [recorded in telemetry](https://github.com/medic/cht-core/blob/28f2afb6bf5870ba73aabf8f8f20b237a05648ab/webapp/src/ts/services/telemetry.service.ts#L161)
I've added the `packageName` and `versionCode` in that method, so the telemetry part is already covered (right?) and I'll use the method to get and display the info in the about page, is that okay? I think it's better to keep this in the json.

**Comment by garethbowen** [comment]
Sounds good to me.

**Comment by latin-panda** [comment]
This is ready for AT, PRs:

CHT-Android: https://github.com/medic/cht-android/pull/182
CHT-Docs: https://github.com/medic/cht-docs/pull/514
CHT-Core: https://github.com/medic/cht-core/pull/7131

This should work fine in xwalk and webview. Please see usage in the documentation PR.
<img src="https://user-images.githubusercontent.com/66472237/121284618-5d2b3980-c907-11eb-971c-3453a2c16857.jpg" width="300">

**Comment by mrjones-plip** [comment]
@garethbowen  - I was just thinking of this ticket and our chats about the forum post we've been talking about. This ticket is done and ready fort AT, but do we want to add the WebView version to this screen too?

**Comment by garethbowen** [comment]
I _thought_ that would be included in the "android app version code", but `211` doesn't make sense to me. Specifically, when building webview version, we [add `1` to the version code](https://github.com/medic/cht-android/blob/master/build.gradle#L177). But this usually generates a number that's almost 10 digits long, not 3.

@latin-panda Do you know what the number `211` represents here? Can we get the version code generated in the build.gradle instead?

**Comment by latin-panda** [comment]
@garethbowen this is the [internal version code](https://developer.android.com/reference/android/R.styleable#AndroidManifest_versionCode) coming from the [package info](https://developer.android.com/reference/android/content/pm/PackageInfo#getLongVersionCode()). If I take it directly from the Build Config class I get similar number in the 200+.

<img width="795" alt="Screen Shot 2021-06-10 at 12 37 47 pm" src="https://user-images.githubusercontent.com/66472237/121470662-bfa83680-c9e8-11eb-98a9-058bd4804eb2.png">

**Comment by garethbowen** [comment]
Ok. It might be fine. I think it's 200 and 210 because it's a snapshot and the number will come out much longer with a tagged release.

The number isn't very user friendly but it will uniquely identify the release in a way that developers can use for debugging.

**Comment by latin-panda** [comment]
@garethbowen @mrjones-plip I've verified that this versionCode is okay by hardcoding a return value in [getVersionCode()](https://github.com/medic/cht-android/blob/1195ca282c7a657886fd3042b5bcfbb53f5c917e/build.gradle#L37) I actually got displayed the expected one. I think we'll get a better number on release mode. :)

**Comment by mrjones-plip** [comment]
Awesome - thanks @latin-panda  and @garethbowen  for looking into this!

I'd love to see some additions to our documentation on how to decipher the different numbers - I'm happy to take this on if it's not already under way!

**Comment by meghna-khemka** [comment]
Tested mentioned issue and issue seems to be working fine.Waiting for peer review

Supporting documents:
Webview:
![image](https://user-images.githubusercontent.com/84743933/121616544-f184c180-ca17-11eb-9685-26370244076b.png)

Xwalk:
![image](https://user-images.githubusercontent.com/84743933/121616605-095c4580-ca18-11eb-85d1-1bb974ceab74.png)

Telemetry:

![image](https://user-images.githubusercontent.com/84743933/121616682-314ba900-ca18-11eb-9e8a-b9fb41b62119.png)

@ngaruko ,
@craig-landry

**Comment by ngaruko** [comment]
LGTM.
Ready to merge @latin-panda .
