### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by andrineM** [medic/cht-core#6745]
Any idea why i would be getting error code 304 upon login with the right set credentials.Am running Medic-os on Docker.Below error
![image](https://user-images.githubusercontent.com/53934661/99789373-83d47f00-2b33-11eb-9eb4-1b1d7131ced6.png)

**Comment by andrineM** [comment]
![image](https://user-images.githubusercontent.com/53934661/99790279-ed08c200-2b34-11eb-826a-79ae22093d51.png)

Logs

**Comment by garethbowen** [comment]
Hi @andrineM .

The 304 code you're getting isn't an error, it means "Not Modified" ([reference](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_redirection)), in other words, the cache is working correctly and you don't need to download the style.css again.

In the logs i see a 302 for the `POST /medic-login/` step which indicates you've successfully logged in and the browser should redirect to the app URL.

When you press submit do you see an error on the screen? Can you share more information about the `POST` request in the browser's "Network" tab?

**Comment by andrineM** [comment]
![image_2020_11_20T10_21_23_465Z](https://user-images.githubusercontent.com/53934661/99935066-d8b10900-2d70-11eb-9199-d818cd55f99f.png)
Please see as requested.

**Comment by garethbowen** [comment]
That seems to be the same screenshot again. There are no errors in that screenshot and everything appears to be working perfectly. Can you try and type in the credentials and click the login button? Then you should see a POST request, and also an error message in the page in red.

**Comment by dianabarsan** [comment]
Looking at the log you linked (here https://github.com/medic/cht-core/issues/6745#issuecomment-731087855)
it seems like you were successfully logged in and then you were redirected back to the login page. 

Can you, please, share your cookies? Also, what type of account are you using?

**Comment by andrineM** [comment]
That is exactly what is happening.Its attempts a login then redirects back to the login page with no error on interface. Since its in a remote facility, I am working on getting the information requested then will share.

**Comment by dianabarsan** [comment]
From your screenshot here, I can see you're trying to login against `http://localhost:5988`
In our instructions, the URL that is indicated (and you should use) is `https://localhost` (read https://github.com/medic/cht-core/blob/master/INSTALL.md#local-installation) 

The reason for the redirect is that your cookies aren't being saved. 
Because you're running a `production` env, the cookie are set to be secure (https://github.com/medic/cht-core/blob/master/api/src/services/cookie.js#L8), and you're non-secure (`http`) login. 

Can you, please, try to login against `https://localhost` ?

**Comment by andrineM** [comment]
The endpoint https://localhost returns:
![medic](https://user-images.githubusercontent.com/53934661/100099083-fc0ead80-2e6f-11eb-943c-d8bdd6754b0b.PNG)
Here is the information on the POST (Network tab)

**Comment by andrineM** [comment]
Please see below 
![image](https://user-images.githubusercontent.com/53934661/100104347-1b5d0900-2e77-11eb-9ed1-87a909b4d0b7.png)

**Comment by nomulex** [comment]
@andrineM ,   Our docker set up has an nginx proxy which  enables you to access the traffic through local host. It tries to apply ssl albeit invalid given that the header will be localhost.  Like @dianabarsan said,  You are accessing medic api directly through port 5988 and that delivers raw http traffic.

**Comment by nomulex** [comment]
@andrineM any updates on this ?

**Comment by andrineM** [comment]
Its still not clear what my action point is.Accessing the application on https gives an error as well as i had indicated.

**Comment by nomulex** [comment]
Can you access the application through the nginx proxy in the container and not directly through the api ?  Basically no port 5988 at the end of your url ?

**Comment by garethbowen** [comment]
@andrineM I'm closing this as it's had no comments for 6 months. If this problem persists please raise a question on the CHT Forum.
