### ISSUE TITLE
Backwards compatibility for location gathering

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6756]
In 3.10.0 we improved the way we gather location data (https://github.com/medic/cht-core/issues/5917) combined with an associated change in medic-android 0.5.0 (https://github.com/medic/medic-android/issues/111). Unfortunately this caused a regression for anyone using CHT 3.9.x with medic-android 0.5.0 which meant that location data was no longer being collected.

Investigate if there's a way to make these two supported versions compatible.

**Comment by ngaruko** [comment]
LGTM
Will do more thorough testing during the upcoming RT

**Comment by garethbowen** [comment]
Closing as it's already merged.
