### ISSUE TITLE
Re-usable GitHub action for deploying configurations via medic-conf

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6758]
Members of the CHT community have integrated the CHT app deployment into CI/CD pipelines or other more automated/integrated deployment systems. For those wishing to deploy code through automated GitHub workflows, it is useful to have a parameterised re-usable Github Action that deploys a cht-app application from git directory.

**Comment by MaxDiz** [comment]
Related [proposal for transitioning away from Travis](https://docs.google.com/document/d/1UsMUk8qELddsyapA_hK8r_QYaxuEKbKEhcmcEkiIxwE/edit?ts=5fae8414#)

**Comment by garethbowen** [comment]
Merged. Thanks for the contribution @kennsippell !
