### ISSUE TITLE
Default config flaky travis test

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6761]
**Describe the issue**
I've seen this happen on/off for the last couple of weeks. Travis builds fail with this error:
![image](https://user-images.githubusercontent.com/35681649/100460454-d97acf80-30cf-11eb-84fd-1369cd013cb5.png)

**Why Now?**
Partner(s): Internal
Reason(s): Internally needs this ticket to facilitate the release, or reduce technical debt

**Comment by andy5995** [comment]
I was getting some weird issues with Travis a while back. After I migrated from the .org to .com, no problems.

The migration process was pretty simple and quick. One other reason to migrate might be:

https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions
```
Q. When will the migration from travis-ci.org to travis-ci.com be completed? #

A. In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.
```

**Comment by garethbowen** [comment]
@andy5995 Thanks. We will need to switch to .com when they shut down .org, but the free account is more limited on .com so we're putting it off. Hopefully we can get at least some of our builds to GH Actions before then...

**Comment by mrjones-plip** [comment]
@dianabarsan  - is this still an issue now that we're on GH Actions instead of travis?

**Comment by dianabarsan** [comment]
I don't think the issue was dependent on the CI platform that tests ran on. 
There are some occasional failures on GHA as well: https://github.com/medic/cht-core/issues/7471 and I'm sure people won't add an issue every time CI fails.

**Comment by garethbowen** [comment]
Not a blocker for 3.15.0

**Comment by dianabarsan** [comment]
Closing as ancient.
