### ISSUE TITLE
Clicking the targets tab twice puts infinite spiner up. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6767]
**Describe the bug**
Clicking to the targets tab. Then clicking the tab again will display a spinner that never seems to go away on its own. Clicking to a different tab then back displays the targets 

**To Reproduce**
1. Log in as restricted user that has targets
1. Click the target tab. The targets are shown. 
1. Click the target tab again. The spinner displays.

**Expected behavior**
The targets should be displayed. 

**Logs**
No logs in browser console. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10531066/100913531-e74d9d80-349f-11eb-8628-95b6eb2eba1a.png)

**Environment**
- Instance:gamma-b
- Browser: chrome
- Client platform: windows
- App: webapp
- Version: 3.9.2-beta

**Comment by MaxDiz** [comment]
Adding to v3.9.2 since that's the environment you tested in. Do you know if it's consistent in > versions as well?

**Comment by newtewt** [comment]
@MaxDiz  happens in 3.8.0 and 3.10.0 as well.

**Comment by newtewt** [comment]
My vote would be to chuck this in to 3.11 or .12 as it isn't blocking in any way and has a very simple workaround.

**Comment by MaxDiz** [comment]
makes sense. Reassigned to 3.12

**Comment by garethbowen** [comment]
It's quite possible that the migration to Angular 10 will make this go away.

**Comment by dianabarsan** [comment]
The upgrade to Angular 10 fixes this issue, partially. 
Partially because now, when the user can't see target aggregates, they will be shown the analytics module selection page on 2nd click: 

1st click: 
![image](https://user-images.githubusercontent.com/35681649/109273544-02b81280-781b-11eb-8bfb-dae40af45988.png)

2nd click: 
![image](https://user-images.githubusercontent.com/35681649/109273577-0e0b3e00-781b-11eb-8af0-1f2eec91f3dc.png)

Ideally, we should always skip the selection page when there is just one module enabled.

**Comment by latin-panda** [comment]
This is ready for AT:
[CHT-Core PR](https://github.com/medic/cht-core/pull/7182)

**Comment by meghna-khemka** [comment]
Tested above issue and issue seems to be working fine

Click Target- On clicking page doesnt' re-load,Target page is still displayed.

![image](https://user-images.githubusercontent.com/84743933/126822952-1b1fdb55-c0ff-4bb5-a9a3-218c756e1285.png)


Target and target Aggregates
![image](https://user-images.githubusercontent.com/84743933/126822768-699adcf1-130e-412c-a77e-ebf58b434193.png)

Click Target tab
![image](https://user-images.githubusercontent.com/84743933/126822785-fe3ddad5-5f37-42e5-af45-421595c7c817.png)

Click Target
![image](https://user-images.githubusercontent.com/84743933/126822870-4264c039-bd60-48cf-9378-c6d74b37d61c.png)

**Comment by latin-panda** [comment]
Thanks @meghna-khemka!
This is merged into the main branch.
