### ISSUE TITLE
The wording on Target Tab not accurate

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6775]
**What feature do you want to improve?**
On the target tab, we have a `Disable` button and text above stating that _**"If disabled the targets tab will be hidden for all users".**_  
![image](https://user-images.githubusercontent.com/6979995/101438579-90503880-3977-11eb-8c86-10bc9920b5eb.png)

In reality, the target tab will still show for anyone with the right permissions , with a message that `No analytics modules are configured`

**Describe the improvement you'd like**
Edit that sentence .

**Comment by garethbowen** [comment]
Made obsolete by #8498
