### ISSUE TITLE
Support official CHT icons in form headers

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6790]
**Is your feature request related to a problem? Please describe.**
Currently our docs specify that you should use [cht icons](https://github.com/medic/icon-library) in your form header icons (see [this docs](https://docs.communityhealthtoolkit.org/design/best-practices/#page-sections) -> "header icons").  However, when you look at our forms, we always use Font Awesome(FA) (specifically [FA 4.7](https://fontawesome.com/v4.7.0/icons/)). For examples, see any of the `.xlsx` files in our [default app](https://github.com/medic/cht-core/tree/master/config/default). In these, you will see only instances of `TITLE HERE <I class="fa fa-ICON-TITLE"></i>`.   There is no way to easily include our native icons.

**Describe the solution you'd like**
We should allow the easy including of our CHT icons in these headers.  This will allow us to not only stop using FA, but to also for us to stay on design and brand.

**Describe alternatives you've considered**
Putting the entire SVG XML or a BASE64 encoding of the PNG inline.

**Additional context**
We should be sure to include icons in the CHT core itself in a web accessible directly similar to how [we deploy FA currently](https://github.com/medic/cht-core/blob/2c74a6e25428f18c7f41bd80880cbe789953f6a9/webapp/src/css/inbox.less#L3). This will allows to have self contained use of our icons with no external web site dependencies and also easy offline use.

Further, allowing for easy including of icons which adhere to our style guides would be great: float right , solid white color, transparent background.

**Comment by MaxDiz** [comment]
Related: https://github.com/medic/cht-core/issues/5535

**Comment by mrjones-plip** [comment]
@MaxDiz  - I would argue that #5535 is a superset and a more holistic ticket.  I'd be happy to close this as a dupe, and optionally update that ticket with any specifics from this ticket.  Seems like that reduce a smidge of ticket tech debt - up to you @MaxDiz !

**Comment by MaxDiz** [comment]
That'd be great, thanks @mrjones-plip

**Comment by mrjones-plip** [comment]
@MaxDiz  - upon further review this tickets use case is explicitly [covered here already](https://github.com/medic/cht-core/issues/5535#issuecomment-495395491). I get the easy way out - just close this as a dupe!
