### ISSUE TITLE
Some Enketo radio buttons don't get checked styling on first click

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6803]
**Describe the bug**
When changing the value of a radio by clicking on an unselected option for the first time, the newly selected option does produce its effect on form data/relevancy/etc, but doesn't get the "checked" styling. 
So far, I've only seen this happen in contact forms.

**To Reproduce**
1. Load default config.
2. Create a health center with a primary contact. When asked, say you want to name the health center yourself and assign a random name. 
3. Open the form to edit this health center. Don't click anywhere on the page.
4. Under the question "Would you like to name the place after the primary contact: "< primary contact name > Health Facility"?*", click on "YES"
5. Observe that the radio button gets focused, but doesn't get the "checked" style, while the other radio button keeps its checked style, but the next field's, Name of this Health Facility*, value **does** change to "< primary contact name > Health Facility".

On subsequent changes, the radios get correct checked styling. 

**Expected behavior**
Radios checked styling should be correctly applied, even on 1st click.

**Logs**
No errors in the console or any logs of note. 

**Video**

https://user-images.githubusercontent.com/35681649/102680692-43fcc800-41c3-11eb-95da-77c49feb4e2e.mp4

**Environment**
- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.10

**Comment by MaxDiz** [comment]
may be solved by the enketo upgrades scheduled in 3.12 and 3.13

**Comment by m5r** [comment]
I found a way to consistently reproduce this bug:
 - open the edit form for any place (health facility, area, household)
 - make the place's name different
 - click "Yes" to "Would you like to name the place after the primary contact: (...)?"


https://user-images.githubusercontent.com/13026820/128999033-2754bdfe-4495-4524-9656-9d6a156d3ebe.mp4

**Comment by m5r** [comment]
Marking this issue as blocked for now as we are waiting for the ongoing `enketo-core` upgrade #6345 as we're expecting it to resolve this bug.

What we know so far:
 - enketo correctly catches the `click` event and updates its internal state to reflect it
 - however, the `<input>` does not get the `:checked` attribute
 - enketo is certainly resetting event handlers or the `<input>` state at some point in the stack trace below. this stack trace gets logged when the bug is triggered

```
(anonymous)	@	Form-model.js:1399
updateCalc	@	calculation.js:128
(anonymous)	@	calculation.js:70
each	@	jquery.js:362
each	@	jquery.js:157
update	@	calculation.js:33
(anonymous)	@	Form.js:617
(anonymous)	@	Form.js:616
dispatch	@	jquery.js:5206
(anonymous)	@	jquery.js:5014
trigger	@	jquery.js:8201
(anonymous)	@	jquery.js:8269
each	@	jquery.js:362
each	@	jquery.js:157
trigger	@	jquery.js:8268
(anonymous)	@	Form-model.js:1411
updateCalc	@	calculation.js:128
(anonymous)	@	calculation.js:70
each	@	jquery.js:362
each	@	jquery.js:157
update	@	calculation.js:33
(anonymous)	@	Form.js:617
(anonymous)	@	Form.js:616
dispatch	@	jquery.js:5206
(anonymous)	@	jquery.js:5014
trigger	@	jquery.js:8201
(anonymous)	@	jquery.js:8269
each	@	jquery.js:362
each	@	jquery.js:157
trigger	@	jquery.js:8268
(anonymous)	@	Form-model.js:1411
(anonymous)	@	Form.js:597
dispatch	@	jquery.js:5206
(anonymous)	@	jquery.js:5014
ZoneDelegate.invokeTask	@	zone.js:434
onInvokeTask	@	core.js:27459
ZoneDelegate.invokeTask	@	zone.js:433
Zone.runTask	@	zone.js:205
ZoneTask.invokeTask	@	zone.js:516
invokeTask	@	zone.js:1656
globalZoneAwareCallback	@	zone.js:1686
```

**Comment by jkuester** [comment]
Good news! I checked this just now and was able to recreate the described issue in `master`, but  not in `6345-enketo-uplift`, so this should be resolved by https://github.com/medic/cht-core/pull/7256
