### ISSUE TITLE
Targets with property "passesIfGroupCount.gte" count intances with "pass: false" when aggregating

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6811]
**Describe the bug**
The `passesIfGroupCount.gte` was written to support Muso's target for "% of families with 2 household visits/month" https://github.com/medic/cht-core/issues/5493. The result is a [muso target](https://github.com/medic/config-muso/blob/master/targets.js#L73) which emits instances with `pass: true` for instances that should be counted (home visits) and `pass: false` for instances which should not be counted (families). The `pass: false` instances are essential for ensuring a correctly counted denominator - counting families with no reports and no home visits.

**To Reproduce**
1. Deploy Muso configuration
2. Create three new families A, B, C
3. For Family A - complete one household visit in current month
4. For Family B - complete no household visits in current month
5. For Family C - complete two household visits on different days in current month

**Expected behavior**
1 of 3 families have recieved 2 household visits this month

**Observed behaviour**
1 of 2 families (incorrect denominator, task does not count families with zero reports)

or (if you remove the comments)
2 of 3 families (task counts denominator correctly, but requires only 1 family visit in the month to be counted)

**Context**
You can work around this for Muso's case using `gte: 3` - assuming there is one and exactly one additional instance per family.

**Environment**
- Instance: muso-mali.app
- App: webapp
- Version: 3.8 - 3.10

**Comment by kennsippell** [comment]
See [here](https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/target-state.js#L123) the emission's pass information is observed when `!passingThreshold` but is not observed in codepath when `passingThreshold` is truthy.

**Comment by njogz** [comment]
Hi @kennsippell, I have been unable to replicate this issue locally after following the steps above. I set `gte: 2` and re-uploaded the config and the denominator is getting calculated correctly. I have tested with `3.10.2` and `3.9.0` with the same result. Maybe I am missing something?

In the screenshot below I have 4 families with two of them receiving 2 visits.

![image](https://user-images.githubusercontent.com/1227336/110767254-188bf580-8267-11eb-83cd-9e88560fadb0.png)

**Comment by dianabarsan** [comment]
@njogz 
I was able to replicate this error. 

- I created 5 families
- used the same target as linked in the original issue, but reduced gte to `2`
- I submitted a single home_visit for one family 

and the family is being counted as having 2 visits: 

![image](https://user-images.githubusercontent.com/35681649/110774442-79ff9480-8266-11eb-8a1c-76a87ca1c259.png)

and I have a single home visit: 

![image](https://user-images.githubusercontent.com/35681649/110774545-956a9f80-8266-11eb-8b7d-9b23b3eaa8dd.png)

So the error is evident when you have a family with *a single* home visit being counted as having 2.

**Comment by njogz** [comment]
Thanks @dianabarsan. I get the same when I have a family with a single home visit. I was testing for `incorrect denominator, task does not count families with zero reports`.

**Comment by kennsippell** [comment]
I think [this block](https://github.com/medic/config-muso/blob/master/targets.js#L75) has been added to ensure that families with 0 reports are counted in the denominator.

The target emits 1 `pass: true` instance for each home visit + 1 `pass: false` instance for each family to ensure it is counted properly in the denominator.

**Comment by dianabarsan** [comment]
Ready for AT on `6811-passesIfGroupCount.gte-targets-fix`

**Comment by newtewt** [comment]
@njogz  I'm struggling with the fix. I can recreate the issue described above using the config with `3.10.3`. When I apply the fix branch it seems the target never gets counted. I have a bunch of console.log statements so I see the target emitting for the 3 house visits I have. 

My target config is below. I have a clinic with 4 house_hold visits.  

```
  {
    id: '2-home-visits-per-fam',
    icon: 'home-visit',
    type: 'percent',
    translation_key: 'targets.muso',
    subtitle_translation_key: 'targets.this_month.subtitle',
    goal: 100,
    appliesTo: 'contacts', // can't be reports to track families without any reports
    appliesToType: ['clinic', 'person'],
    appliesIf: contact => (
      contact.contact &&
      !contact.contact.muted &&
      (contact.contact.type === 'clinic' || isPatient(contact.contact))
    ),
    groupBy: contact => { 
      console.log('contact is ');
      console.log(getFamilyIdForContact(contact));
      return getFamilyIdForContact(contact);
    },

    // This target requires "3" instances to pass because of https://github.com/medic/cht-core/issues/6811
    passesIfGroupCount: { gte: 2 },
    emitCustom: (emit, original, contact) => {
      console.log('here 1');
      const familyId = getFamilyIdForContact(contact);
      console.log('here 2');
      const homeVisitReports = contact.reports.filter(report => getField(report, 'visited_contact_uuid'));
      console.log('here 3');
      for (const report of homeVisitReports) {
        console.log('here 4');
        const visitDate = getReportVisitDate(report);
        console.log('here 5');
        const instance = Object.assign({}, original, {
          _id: `${familyId}-${visitDate}`,
          pass: true,
          date: toDate(visitDate).getTime(),
        });
        console.log('emitting');
        emit(instance);
      }

      // Emit one failing instance so the family is counted even if it has no reports
      if (contact.contact && contact.contact.type === 'clinic') {
        emit(Object.assign({}, original, {
          _id: familyId,
          date: Date.now(),
          pass: false,
        }));
      }
    },
    idType: 'contact',
  },
  
  ```
  
  
  
![image](https://user-images.githubusercontent.com/10531066/112340721-3447c080-8c97-11eb-83fd-cded8c4ea13f.png)

**Comment by dianabarsan** [comment]
@newtewt can you try adding home visits in different days? I think there's this rule where only one report per day is considered a home visit :)

**Comment by newtewt** [comment]
That was it. Setting a couple dates on reports different they are now counted appropriately.

Checked changing the gte value.
Checked that the default config tasks all work as expected.  Mix of count with and without goals, percent based with -1 and positive goals. 

I think we can merge this @njogz

**Comment by dianabarsan** [comment]
Merged to `master`.
