### ISSUE TITLE
Document update conflicts deleting reviewed report

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6814]
**To Reproduce**
1. Go to 'reports'
2. Click on any existing report
3. Scroll down to 'Review '- Click - then click 'correct'
4. Now try to delete the report
5. Report cannot be deleted

**Expected behavior**
Report should be deleted or a message displayed explaining why it can't be deleted

**Logs**
 browser logs.
```
inbox.js?_sw-precach…d6c6be6a6603193bc:3 Error submitting modal 
n {status: 409, name: "conflict", message: "Document update conflict", error: true, id: "037c9b13-4f55-41c8-9359-8e8c3370dfb3", …}
docId: "037c9b13-4f55-41c8-9359-8e8c3370dfb3"
error: true
id: "037c9b13-4f55-41c8-9359-8e8c3370dfb3"
message: "Document update conflict"
name: "conflict"
status: 409
__proto__: Error
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/103040850-93832f80-45d9-11eb-9619-12ecd5b0dc04.png)

**Environment**
- Instance: gamma-cht.medicmobile.org
- Browser: Chrome
- Client platform: MacOS, Android
- App: webapp
- Version: 3.10.1-beta.3

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment]
Delayed to 3.12.0 to speed up 3.11.0 release.

**Comment by dianabarsan** [comment]
This should already be fixed with the Angular 10 upgrade.

**Comment by newtewt** [comment]
Tested using online and offline user that has the verify options role. After selecting either option and then delete. The report is deleted.  I'm closing as this is in the master branch.
