### ISSUE TITLE
Android app version and Server URL not showing in About page

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6835]
**Describe the bug**
We used to show the android app version and server url when running in the android wrapper, but we don't any more.

**To Reproduce**
1. Load the android app
2. Click on the hamburger menu
3. Click "? About"
4. See that the version of the android app is not listed, and the URL is blank

**Expected behavior**
- The android app version should be shown right underneath the "Version" information
- The server URL should be shown

**Logs**
None

**Screenshots**
![Screenshot from 2021-01-12 10-49-54](https://user-images.githubusercontent.com/2064938/104242366-f1fa4a00-54c3-11eb-95c3-2a4245e457b1.png)

**Environment**
- Instance: localhost
- Browser: Android app
- Client platform: Linux
- App: webapp
- Version: master (3.10.0)

**Additional context**
This is similar to #6741 but because this part is a regression I've split it off. That issue should focus on adding more complete information like which flavour (brand, architecture, and webview/xwalk) is being used.

**Comment by garethbowen** [comment]
Ready for AT in `6835-android-version-in-about-page-a10`. Be sure to test in Android and a browser.

**Comment by newtewt** [comment]
@garethbowen  looks good. On android 10 and 6  I see the version of the webapp, version of android, and the URL all populated. On web it is only the webapp version and url.

I assume this wasn't your change but want to verify it isn't an issue.  DDOC Versions are no longer listed but have been replaced with
Server webapp revision
Client webapp revision

**Comment by garethbowen** [comment]
Yes that was part of this PR to make the labeling more consistent and more clear. @newtewt Does that change your opinion on this PR?

**Comment by newtewt** [comment]
@garethbowen no I think it's fine. I just wanted to make sure it was intentional change.

**Comment by garethbowen** [comment]
Thanks.

Merged!
