### ISSUE TITLE
Race condition in rules engine / task list interaction can result in a stale tasks list

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6839]
**Describe the bug**
Because of a race condition that can exist between rules engine and the task controller, the user could end up seeing a stale and incorrect task list.
The reproduction steps I'm about to provide (when a completed task does not disappear from the list) may not be the only situation when this race condition can be triggered. 

**To Reproduce**
1. Push default config (form and tasks). 
2. Login as an offline user with a considerable amount of docs on a slow device. I had 2000 docs (out of which 50 were "current tasks" - that I saw in my task list) and was using a Tecno Y4 (device performance is essential to reproduce the behavior). 
3. Submit a "pregnancy danger sign" form for a contact. This will create a task that will be visible immediately at the bottom of your task list. 
4. Complete this task, by selecting that the patient is not showing danger signs any more. Submit.
5. Observe that the task still exists in the task list, and is not disappearing even after many seconds. 

**Expected behavior**
The completed task should disappear from the task list after a few seconds (though we have no indication that we're actually "reloading" or expecting the task list to be updated). 

**Logs**
There are no relevant logs. 

**Environment**
- App: Webapp
- Browser: Chrome
- Version: reproduced on 3.10, but I suspect 3.9 and 3.8 are also affected.

**Additional context**
The race condition is caused by two distinct events that are in a race, both affecting what the user sees on the screen:
1. RulesEngineService listens to changes and, when it receives a contact/report change, it calls the shared library endpoint that updates the emissions for the affected contacts:
https://github.com/medic/cht-core/blob/master/webapp/src/js/services/rules-engine.js#L146
This is an *async* operation, as the `subject_ids` that we have access to when we receive the change could be shortcodes, that we need to translate to contact uuids. This requires querying the DB before marking the affected contacts as dirty and, consequently, refreshing their emissions during the next calculation cycle. 

2. TasksController also listens to changes and, like the RulesEngineService, reacts to contact/report and task changes: 
https://github.com/medic/cht-core/blob/master/webapp/src/js/controllers/tasks.js#L104
After waiting for an arbitrary second (the existence of debounce here is not to serve this purpose, but it's what makes this error less obvious by only being triggered in the lowest performing devices), the controller refreshes the tasks list. 

If both entities (the rules engine and the tasks controller) receive the change in the same "tick", but the "marking contacts as dirty" in (1) takes longer than the task controller (2) waits before requesting tasks, the result will be that the reloaded tasks will be stale, because the contact was not dirty at the moment of refreshing.

**Comment by dianabarsan** [comment]
Ready for AT on `6839-fix-tasklist-race-condition`

**Comment by ngaruko** [comment]
LGTM - Tested on the branch using a Tecno phone, with over 10000 docs. Was able to replicate on the phone, but not  in the browser (which was expected as @dianabarsan noted above that it depends on device performance.

**Comment by dianabarsan** [comment]
Thanks @ngaruko . Is this ready to be merged?

**Comment by ngaruko** [comment]
Yes @dianabarsan
