### ISSUE TITLE
Remove custom translations from Bamanankan

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6846]
**Describe the issue**
PR https://github.com/uxsolutions/bootstrap-datepicker/pull/2431 was created to add Bamanankan to the bootstrap datepicker library. Until it was released, we added custom translations at https://github.com/medic/cht-core/blob/master/webapp/src/js/enketo/bootstrap-datepicker.bm.js. 

**Describe the improvement you'd like**
Bump bootstrap-datepicker to latest and remove custom translations.

**Comment by garethbowen** [comment]
We bump dependencies (almost) every minor release, so I'll add this to 3.12.0 to be done at the same time.

**Comment by njogz** [comment]
This will be sorted out with the [enketo-core uplift](https://github.com/medic/cht-core/pull/7256)

**Comment by njogz** [comment]
@dianabarsan yes it is.

**Comment by ngaruko** [comment]
Removing from the 3.14 milestone as the enketo uplift has been postponed. Keeping it in AT.
