### ISSUE TITLE
Add bootstrap-datepicker translations for Tagalog (tl) Illonggo (hil) and Bisaya (ceb) languages

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6849]
**Is your feature request related to a problem? Please describe.**
A new app in the Philippines is requriing language support for  Tagalog, Illonggo, and Bisaya. In addition to https://github.com/medic/cht-core/issues/6848 (blocking), the project will also require translations for the bootstrap datepicker.

**Describe the solution you'd like**
Create translations and add them for these languages.

**Comment by binokaryg** [comment]
Thanks Kenn. I have asked the local partner for the required translations.

**Comment by MaxDiz** [comment]
@binokaryg do you know the timing required for this project deployment?

**Comment by binokaryg** [comment]
The project has been already deployed and the CHWs have started collecting data from yesterday. They are currently being guided by their trainers who know English or Tagalog (it is working). Starting mid-Feb, the CHWs will start working solo. We need to get the translations working at least a few weeks before that so that the training can continue in a language they know.
So I would say, it would be great if we can get it done by early next week (Jan 25).

**Comment by MaxDiz** [comment]
@ngaruko please pick this up for QA as soon as @binokaryg has completed the PR to align with project timing

**Comment by binokaryg** [comment]
@joymkimmel do we have the translations finalized yet?

**Comment by joymkimmel** [comment]
Completed the pull request for this. 

https://github.com/medic/cht-core/pull/6865

**Comment by dianabarsan** [comment]
Ready for AT on `6849-adds-bootstrap-datepicker-locales`

**Comment by ngaruko** [comment]
LGTM
- Tested on branch `6849-adds-bootstrap-datepicker-locales`. (date picker, death report.... and dob for new person) - datepicker shows months and short months as in `webapp/src/js/enketo/bootstrap-datepicker.ceb.js` and `webapp/src/js/enketo/bootstrap-datepicker.hil.js` respectively.
![image](https://user-images.githubusercontent.com/6979995/105417014-d5b69400-5c9f-11eb-97db-18d99fa82ad4.png)
Wondering though if the report filter by date use the same logic/date picker. It does not seem to be translated @dianabarsan ?

**Comment by dianabarsan** [comment]
The report date filter uses moment dates! it should have proper month names in @binokaryg 's PR!

**Comment by ngaruko** [comment]
Thanks @dianabarsan . Then this looks good. Feel free to merge. I will move onto the other PR.

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.10.x`.
