### ISSUE TITLE
Updating the ANC reference app in the CHT website

### ISSUE THREAD

**Issue by maremegaye** [medic/cht-core#6892]
Hi Francesca! As discussed we would like to update any material related to the ANC reference app by MNCH reference app. We have a list of documents to update but you can start with this below one that is already finalized.

https://communityhealthtoolkit.org/tools

Current wording in the doc | Modification | Where?
-- | -- | --
Antenatal Care (ANC) Reference App by Medic Mobile | Maternal, Newborn and Child Health (MNCH) Reference App by Medic Mobile | Section ANC reference App
Our ANC Reference App provides | Our MNCH Reference App provides | Section ANC reference App
related to pregnancy and delivery, | related to pregnancy, delivery, newborn and child assessment | Section ANC reference App
ANC APP OVERVIEW (PDF) | MNCH APP OVERVIEW (PDF) | change the Link name

I will share the rest of the docs next week.

Thank you for your support!

@cescagarrett cc @mrjones-plip

**Comment by mrjones-plip** [comment]
The larger rollout of the MNCH app has been stalled for over 8 months. I'm going to close all the tickets and PRs. If we want to re-open them to work on this again, all good!
