### ISSUE TITLE
Add an e2e test that simulates an upgrade for an offline user

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6922]
**Describe the issue**
We currently rely on manual testing to check that upgrades go smoothly between releases and have no e2e test that is designed to monitor that upgrades work. 

I realized, while working on a [separate issue](https://github.com/medic/cht-core/pull/6921), that an e2e test that does an upgrade is needed to check that the replication ids don't change when upgrading. 

**Describe the improvement you'd like**
Add an e2e test to that upgrades from the previous release to the test build. 
This can either be a new flow, or be the 1st test from the current flow - i.e. don't have horti install the test build, rather install the previous release build, login as an offline user, and then upgrade to the test build. 
The rest of the suite should continue like before. 

**Describe alternatives you've considered**
Keep manually testing upgrade compatibility.

**Comment by latin-panda** [comment]
@dianabarsan would [this test](https://github.com/medic/cht-core/blob/master/tests/e2e/upgrade/upgrade.wdio-spec.js) resolve this issue?

**Comment by dianabarsan** [comment]
No, unfortunately. This test requires an offline user being logged in while the upgrade on the server is happening.

**Comment by dianabarsan** [comment]
Done via https://github.com/medic/cht-core/commit/fbaa6f8816e6dbaf80bd7e754253a7e8b807a69e
