### ISSUE TITLE
Code changes not appearing on client's device even after reloading the app 

### ISSUE THREAD

**Issue by iesmail-znz** [medic/cht-core#6936]
We rolled out a bug fix related to `nools-extras.js` which was causing the task list to error out.  After rolling out the change, the CHVs affected by this issue were asked to Reload the app to get the changes. The task list was still erroring out despite reloading the app. 

I logged into the browser view and app view using one of the affected CHVs login credentials and I was able to see the task list. What could be the issue here?

**Comment by derickl** [comment]
It would be really useful to learn what errors they are facing.

A tip on how you could start troubleshooting: replicate the data to your local env. Upload the broken config, upload the new config and see if you get the error.

**Comment by garethbowen** [comment]
Make sure the users have replicated the settings changes before reloading.

If there's still an error it may be an issue with an already generated task. Can you check for any feedback docs from those users with error messages that may help to debug the issue?

**Comment by garethbowen** [comment]
@iesmail-znz For future reference support requests like this one are probably better to be posted to the [CHT Forum](https://forum.communityhealthtoolkit.org/). More people are looking there so you'll have a better chance of getting a quick answer!
