### ISSUE TITLE
Use more github action runners for e2e. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6957]
**Describe the performance issue**
Our build process takes around 35 minutes to execute. Majority of which is running e2e tests. 

**Describe the improvement you'd like**
A quick win would be to split the tests files up and run them across more runners. This could be done by using the matrix and the `fromJSON()`  option within github actions.  I think this would also be a good opportunity to clean up the e2e and group them based on functionality. There are a few that just sit in the root of e2e. 

**Describe alternatives you've considered**
Protractor allows you to shard and run multiple instances on one runner. I believe this effort to make our tests run against the same CHT instance would be higher because of the number of settings changes, resetting databases. 

**To Reproduce**
Steps to record the performance metrics:

**Measurements**
Looking at the Successful runs the quick average is around 35 minutes. 

**Environment**
- Instance: (eg: alpha.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, medic-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**

**Comment by dianabarsan** [comment]
This is quite old and the build process and e2e tests have changed and improved over time. 
Closing as stale.
