### ISSUE TITLE
Remove ability to set user language in database

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6972]
**Describe the bug**

In the admin app we allow administrators to pick a language when creating or editing users. This updates the user settings document in the database. When we added the login page locale selector this value is now completely ignored so it just leads to confusion.

**To Reproduce**
1. Go to App Management > Users
2. Click on "Add User"
3. Set the language as well as the other fields and create the user
4. Log in as the new user and notice that the language setting you chose in step 4 is ignored.

**Expected behavior**
The Language field shouldn't exist in the Add User modal.

**Logs**
None

**Screenshots**
![Screenshot from 2021-02-25 13-56-41](https://user-images.githubusercontent.com/2064938/109086916-52420400-7771-11eb-8898-44e0dd4c9424.png)

**Environment**
- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: admin
- Version: 3.11.0

**Comment by dacar1988** [comment]
Hi @garethbowen! I just created this PR to fix this issue: https://github.com/medic/cht-core/pull/7049 where I removed the language field from the Add User modal. This means that it is not possible to choose a language not only when a user is added but also when is updated. I hope it is fine for you.

**Comment by garethbowen** [comment]
Ready for AT in `dacar1988:6972-remove-ability-to-set-user-language-in-database`

**Comment by ngaruko** [comment]
Tested on local 

1. Add user modal in admin  >> language field removed
Before 1 |after
--- | ---
![image](https://user-images.githubusercontent.com/6979995/117588005-e74f7900-b174-11eb-9305-ef4785d99605.png) | 
![image](https://user-images.githubusercontent.com/6979995/117588023-fcc4a300-b174-11eb-8bff-e2ef4ed88dc0.png)


2. API : [POST api/v1/users](https://docs.communityhealthtoolkit.org/apps/reference/api/#post-apiv1users)
