### ISSUE TITLE
Prototype integration with CloudWorks' Rapid Diagnostic Toolkit app

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#6980]
As part of our work with CloudWorks we need to build a prototype integration to the [Rapid Diagnostic Toolkit](https://github.com/dimagi/rd-toolkit) Android application.  

The workflow for the prototype will be an assessment form that provisions a test, and then a follow up task which would have a button to check for the status of the test. If the test is still pending, the user could wait in the form to press the button again until the return status is that the test is complete. 

This [integration](https://github.com/dimagi/rd-toolkit/blob/master/docs/usage.md) requires an Enketo widget to provision a test in the RDToolkit app, and another Enketo widget to collect the test result:

> Since tests take a significant amount of time to resolve, the default execution mode is a two phase interaction. The first phase is an activity callout to provision a diagnostic test, and the second phase is request to capture the result of the test.

The result widget would store the return value as a JSON blob for now, with the status being queryable from within the form itself. That way the field could be required, and preventing advancing in the form until a completed/success status is returned.

**Comment by abbyad** [comment]
Replaced by #6981, which is in sync with roadmap.
