### ISSUE TITLE
Schrödinger's user, both online and offline 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6984]
**Describe the bug**
Because of different ways of determining whether a user has an online or an offline role, api and webapp can sometimes disagree. 

**To Reproduce**
1. Create an offline role. 
2. Create a user for this offline role. Login and check how many docs the user should download.  Log out.
3. Update the config (you can't do this through the UI) and change the role to be online - by simply removing the `"offline": true` flag. 
4. Login with the user again (in a fresh browser).
5. Notice that you're getting the replication screen, no estimate about how many docs you have and and you just download lots of docs very quickly. 

OR:

1. Create an online role. 
2. Create a user for this online role. Login and make sure the user doesn't get the replication screen. Log out. 
3. Update the config (you can't do this through the UI) and change the role to be offline- by simply adding the `"offline": true` flag. 
4. Login with the user again (in a fresh browser). 
5. Notice that you're not getting the replication screen and then none of your lists load (offline users can't request CouchDB views). 

**Expected behavior**
API and Webapp should reach a consensus on whether this user is an online user or an offline user. 

**Logs**
The only suspicious log is that the initial request to `users-info` returns a 403 (because the user doesn't have permission to update users). 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/110068248-f5040f00-7d7d-11eb-93fb-7df4f3ebebc5.png)

**Environment**
- Instance: Live instance
- App: Webapp and API
- Version: 3.10

**Additional context**

In webapp, we determine whether a user is online or offline by checking if they have a role called `mm-online`. We don't manage this role when the other user's roles are changed:
https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/session.service.ts#L112

In API, we actually check the roles' config, checking if the user has at least one role that has the `offline` flag, and completely ignore `mm-online` (the only mention to `mm-online` in API is in user creation). 
https://github.com/medic/cht-core/blob/8e139e976ff785598bcdaf3edcfb8716766adfe4/api/src/auth.js#L65

The workaround, when a user gets into this situation, is to manually update them and add (or remove) the `mm-online` role.

**Comment by latin-panda** [comment]
Once it's determined a common way to check if the user is online, we can probably add this in the [CHT Script API](https://github.com/medic/cht-core/tree/master/shared-libs/cht-script-api) 🤔

**Comment by dianabarsan** [comment]
This is ready for AT on `6984-api-mm-online`.

**Comment by ngaruko** [comment]
LGTM. Tested using local dev env. (NOTE: using horti to launch the app and upgrading to branch does not seem to do the job).
**On main branch**
![image](https://user-images.githubusercontent.com/6979995/133010371-87d3b2b8-5333-4b09-afec-f2446cbd5c9b.png)

**on this PR**

https://user-images.githubusercontent.com/6979995/133010377-da183e4e-de04-4f3a-872e-6c0f64ac2345.mov

Feel free to merge @dianabarsan

**Comment by dianabarsan** [comment]
> NOTE: using horti to launch the app and upgrading to branch does not seem to do the job

What do you mean? These changes were completely contained to API, so it means that your API code was not updated by the horti upgrade? This might be a separate issue.

**Comment by dianabarsan** [comment]
Merged to `master`.
