### ISSUE TITLE
Change Medic Mobile -> Medic, medicmobile.org -> medic.org

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6985]
**Describe the issue**
Medic has[ changed names and URLs ](https://medic.org/stories/meet-medic-a-refreshed-brand-evolving-leadership-and-a-strategic-path-forward/)

**Describe the improvement you'd like**
Change Medic Mobile -> Medic, medicmobile.org -> medic.org

**Describe alternatives you've considered**
NA

Related: [Docs issue where we did the same](https://github.com/medic/cht-docs/issues/443)

NB - This is for the repo, not the code.  Per our branding guide, no changes are being made to CHT right now as the CHT branding [is staying the same for now](https://www.notion.so/medicmobile/Our-Evolved-Brand-df7be28dae1e48e482761d075248ab00) (private notion link).

**Comment by abbyad** [comment]
Instance urls are not automatically redirected, so references to *.app.medicmobile.org and *.dev.medicmobile.org should remain until we redirect those too.

**Comment by garethbowen** [comment]
Closing. If there are specific instances where this should be done, please call those out in new issues.
