### ISSUE TITLE
Changing admin password via webapp doesn't work

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6986]
**Describe the bug**

After updating the user password while logged in using the default credentials, the update seems successful but subsequent logins using the new password fail.

Initially [raised on the forum](https://forum.communityhealthtoolkit.org/t/updating-default-login-credentials/1178).

**To Reproduce**

1. Log in using the admin credentials (medic/password)
2. Go to the app menu and select User settings
3. Click on ‘Update password’
4. Set a new password

**Expected behavior**
I expect to log in using the newly set password on my next login.

If it's not possible to update the admin password via API then we should detect this and link to the CouchDB docs rather than masquerading as success.

**Logs**

```
REQ 0af761c9-336f-4eb6-ae5b-fe7e4fe3e5ce ::ffff:127.0.0.1 admin POST /api/v1/users/admin HTTP/1.1
2021-03-08 11:37:57 INFO: REQ 0af761c9-336f-4eb6-ae5b-fe7e4fe3e5ce - Updated user 'admin'. Setting field(s) 'password'. Requested by 'admin'. 
RES 0af761c9-336f-4eb6-ae5b-fe7e4fe3e5ce ::ffff:127.0.0.1 admin POST /api/v1/users/admin HTTP/1.1 200 176 107.495 ms
```

**Screenshots**

![Screenshot from 2021-03-08 11-36-17](https://user-images.githubusercontent.com/2064938/110257391-90a5b180-8002-11eb-8d87-a558cc755e53.png)

**Environment**

- Instance: self hosted installation
- Browser: Google Chrome
- Client platform: Linux - Ubuntu 18.04
- Docker version 20.10.3, docker-compose version 1.28.2
- App:webapp
- Version: 3.9.0

**Additional context**

Workaround: Update the password directly in CouchDB as per [the documentation](https://docs.couchdb.org/en/2.3.1/config/auth.html#server-administrators).

**Comment by latin-panda** [comment]
CouchDB's admin password is saved in a diff place, the way to set the password is by making this request: 

`curl -s -X PUT http://[user]:[password]@localhost:5984/_node/$COUCH_NODE_NAME/_config/admins/[admin-user] -d '"[new-password]"'`

If this user is the same user defined in the environment variable `COUCH_URL=http://[user]:[password]@localhost:5984/medic` then the variable needs to be updated, sentinel and api restarted so the url in the [db](https://github.com/medic/cht-core/blob/master/api/src/db.js#L65) is updated as well. Perhaps couch2pg needs a restart too but I haven't test this one yet. 

It's a bit of a process. Our practice with projects supported by us is to have 2-3 admin users, for couch2pg and couchDB and I think another one for managing things inside the CHT instance, so the SRE has a process for the password rotation. 

What if we hide the option for changing password for admin users in webapp and in admin apps, then add an info text indicating to go check the CHT-Docs for a step by step guide on how to reset admin password? 

==
I'll fix the error handling for when password set failed in both webapp and admin apps. 
CC: @garethbowen

**Comment by garethbowen** [comment]
I think that makes sense. Ideally there would be two (or more) types of admin - (a) admins that are for inter-process communication where nobody knows the password and they can't be edited, and (b) admins that are for real people to log in and manage the instance. If we could figure out a way to detect which user is which then we could allow setting the password for the second type. I _think_ it would be difficult to detect for all existing instances, so unless you can think of a way, let's go with your proposed solution.

**Comment by latin-panda** [comment]
Other options considered are:

1. Have a new role to identify the admins used for internal processes (couchdb, couch2pg, etc). This will require to add some documentation in CHT, about how and why to use the role.
2. Pattern check environment variables to see if the logged in admin is also used for internal processes. This could be fragile if we forget to check a new environment variable or if the value format changes (not often to happen).

Then hide the option for changing the password for those admins that are used for internal processes.

However, hiding the option for all admin users, is the simplest solution, as probably there's 1 or 2 people managing the instance only and doesn't add more complexity in the setup of instances and users, thinking of projects that are non-supported by us primarily.

**Comment by dianabarsan** [comment]
Just a small FYI: 
As part of ArchV3 and the in-construction docker entrypoint, services [will create their own users](https://github.com/medic/cht-core/blob/deconstruct-3.10.0/api/docker-entrypoint.sh#L81) and store the passwords in a local file for reuse. I think that if we go in this direction, the entrypoint script will have a fallback to overwrite the password if it's not the same one as in the file (i.e. if it was changed manually).

**Comment by latin-panda** [comment]
Thanks Diana! 🤩 if services creates their own users automatically, then perhaps the services can add a flag or role or something in the user document to differentiate from admins that are for real people (instance managers) 🤩

**Comment by latin-panda** [comment]
Well, in theory no-one will login using those users. So it should be fine even if we can't tell them apart easy.

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7410)
Scenario 1
1. Create a new admin user that is not used for `COUCH_URL` environment variable.
2. Login as that admin user 
3. Change the password in webapp

Scenario 2
1. Create 2 new admin users that is not used for `COUCH_URL` environment variable.
2. Login as one of them 
3. Change the password of the other admin user by using the Admin app.

Scenario 3
Should be able to update other details from admin like the email when the password didn't change. 

Scenario 4
Should be able to update the password and other details of non-admin users.

**Comment by ngaruko** [comment]
Tested on local using newly created admin user (`curl -s -X PUT http://admin:pass@localhost:5984/_node/nonode@nohost/_config/admins/robby -d '"Ngaruko01"'
`) as in [comment](https://github.com/medic/cht-core/issues/6986#issuecomment-977959342) above.

1. admin user able to login with new password
2. other details
3. able to change settings for non-admin users
Ready to merge @latin-panda .

**Comment by latin-panda** [comment]
Thanks Bede
Work is merged into main branch.
