### ISSUE TITLE
Firefox is generating a Content Security Policy error when submitting a form. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6988]
**Describe the bug**
When submitting a form the following error is shown in console. 

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).` This happens for contact, person, or forms. 

**To Reproduce**
1. Log in as offline user in firefox
2. Navigate to a person
3. Open the browser console
3. Click New Action and select a form. 
4. The error is shown in the console. 

**Expected behavior**
The error should not display. 

**Logs**
The error log is shown above. 

**Screenshots**

**Environment**
- Instance: localhsot
- Browser: Firefox
- Client platform: windows
- App: webapp
- Version: master but happens on prior versions as well. 

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
I tracked this down to : https://github.com/enketo/enketo-core/blob/4.41.6/src/js/Form.js#L553

```
    //first prevent default submission, e.g. when text field is filled in and Enter key is pressed
    this.view.$.attr( 'onsubmit', 'return false;' );
```

This code also exists in Enketo latest: https://github.com/enketo/enketo-core/blob/master/src/js/form.js#L756

It looks like the bug has been reported 8 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=918724 , and now labeled P3. 

Most relevant comment: https://bugzilla.mozilla.org/show_bug.cgi?id=918724#c22 that describes differences between FF and Chrome behavior, where FF reports the CSP error when the attribute is SET (what we are seeing) versus Chrome that would only report when the event handler is triggered (I haven't managed to trigger it so I see the Chrome error, I think propagation is stopped before we reach that attribute).

**Comment by jkuester** [comment]
Pardon my web-standards ignorance, but is this the kind of thing that it would make sense to fix in `enketo-core`?  Once we get back on the latest version of enketo it probably makes sense to upstream fixes where feasible instead of having to handle them with special cases in our code.  (But in this case I am not sure if there is a feasible alternative implementation that enketo could be using or if these belongs in our CSP config no matter what...)

**Comment by dianabarsan** [comment]
I think it makes sense to "fix" in `enketo-core`. But because websites are in complete control of their CSP, and there are workarounds, maybe it won't be considered a bug ? 

I was very tempted to mark this as blocked, but then thought I'd just scratch this off our backlog.

**Comment by dianabarsan** [comment]
Ready for AT on `6988-FF-csp-enketo-onsubmit` . 

Just as a small caveat, to process the new CSP, I had to clear all data/history in FF.

**Comment by meghna-khemka** [comment]
Above issue seems to be working fine now

person
![image](https://user-images.githubusercontent.com/84743933/130526645-745a86c5-a4ee-4a5b-b73c-45f841767432.png)

Forms
![image](https://user-images.githubusercontent.com/84743933/130526815-40f542b0-0509-492b-8177-eba2c7f6a556.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
