### ISSUE TITLE
Research ability to report on releases/features based off github ticket labels

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#6990]
**Describe the issue**
Is it feasible to deduce when a feature or upgrade or initial launch went live based off the GH ticket and related labels alone?

**Describe the improvement you'd like**
After a chat in PO and R&L meetings and [slack discussions](https://medic.slack.com/archives/C024ZK678/p1614380372007900), based off @n-orlowski 's attempt to figure when #5776 went live for BRAC, let's try and see if we can add labels to GH tickets so that we can know when something went live. 

This likely looks something like:
* coming up with a label nomenclature we could use that would be tenable: detailed enough but not so overbearing that they're too verbose.  
* get sign off from relevant teams (eg Product & App Services) that adding a bunch of tags won't be too much of an imposition
* retroactively add a bunch of labels to some tickets to see if we can tell by close date when something went live and as well to vet the nomenclature has actually usefull

Lot's more scoping to do on these before this is actionable, but this _is_ a research ticket ;)

**Describe alternatives you've considered**
Lots and looooooots of guessing, asking around, trawling over old GH tickets.

**Comment by mrjones-plip** [comment]
FYI @michaelkohn  @helizabetholsen @marialma @n-orlowski

**Comment by garethbowen** [comment]
@mrjones-plip I'm not sure exactly what you mean here. Can you provide an illustrative example of what the label would look like?

**Comment by mrjones-plip** [comment]
I'm going to close this because of the effort actively being done over in [app monitoring with the data ingest tool](https://github.com/medic/app-services-team/tree/master/app-monitoring-data-ingest).  This, running over time, will be able to tell which instances where upgraded at what time.  We can map the versions back to specific features as needed.

The original request was to be able to have a ticket like "make it all green" and then be able to add labels to the feature per partner:

```
--------------------------------------------------------------------------------------
| **make it all green**                                                              |
-------------------------------------------------------------------------------------
| all of cht gui should be greeeen            | **Labels** live-partner-1         |
|                                             |  live-partner-2                   |
---------------------------------------------------------------------------------

We could then maybe (?!) run some sort of GH report/project that you could easily map which feature went live on which instance over time.
