### ISSUE TITLE
Muting transition and update clinics don't handle contacts that use a hardcoded type and also have a `contact_type` property correctly

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6996]
**Describe the bug**

**To Reproduce**
For `muting`: 

1. Configure muting transition and set a muting form.
2. Create a place. 
3. Mute this place. Make sure Sentinel processes the report before proceeding. 
4. Create a contact under this place, making sure to add a type = `person` and some string in a `contact_type` property. (it's important you do this when you first create the contact, otherwise the code will work correctly!). 
5. Wait till sentinel processes the contact. 
6. Check the contact in the DB and observe it's not muted. The UI will show them as muted, because they are muted in lineage and they will count as muted if attaching schedules to them, but it's not 100% correct, and could prove problematic in some configurations. 

**Expected behavior**
A contact created under a muted place should be muted (in its json). 

**To Reproduce**
For `update_clinics`: 

1. Enable `update_clinics`. 
2. Create a place that has a hardcoded type and add a `refid` property, save some string in the field, also add a `contact_type` field with some string. 
3. Create a doc that looks like an SMS report with a `refid` property that has the same value as the `refid` on your place. Make sure it doesn't have a `contact` property, so update clinics runs. 
4. Wait until sentinel processes the doc.
5. Observe that your doc is not connected to your clinic. 

**Expected behavior**
The connection through the refid should have been processed. 

**Environment**
- App: api, sentinel
- Version: 3.10

**Additional context**
Muting not being saved on new contacts is mostly important for analytics, but the app should look and function as if these contacts were muted. It's possible some configurations that don't check for muting in a contact's lineage could also be affected. 
I'm not sure how the `refid` for update_clinics interaction works in production or if it even is used in production.

**Comment by dianabarsan** [comment]
Ready for AT on `310-consistent-contact-types-shared-libs`.

**Comment by newtewt** [comment]
The muting portion of this issue is working on the new branch.  The person is getting tagged with the "muted" key if they fall into the odd situation of having contact_type and type of person. 

I tried to recreate the second situation but I must be messing something up with the sms step. I tried copying a N sms form from the standard config. Then add the refid to the place and form but it didnt' show up.

**Comment by dianabarsan** [comment]
Oh, on the refid thing, I remembered during an e2e test update this morning that the refid field on the report needs to be uppercase, like this one: https://github.com/medic/cht-core/blob/master/tests/e2e/sentinel/transitions/update_clinics.spec.js#L215

Sorry for not mentioning that.

**Comment by dianabarsan** [comment]
Also the field on the contact is called `rc_code`, not refid :( 
Like here: https://github.com/medic/cht-core/blob/master/tests/e2e/sentinel/transitions/update_clinics.spec.js#L194

**Comment by dianabarsan** [comment]
Ready for AT for `3.11` on `6993-consistent-contact-types`

**Comment by newtewt** [comment]
I see the report now linking to the refid/rc_code association in the branch above. I think that portion of testing for the 3.10.3 version is ready to merge.

**Comment by dianabarsan** [comment]
Thanks @newtewt . Merged into `3.10.x`.

**Comment by newtewt** [comment]
Seeing the fix in 3.11 branch as well.  

Created contacts under muted place with random contact_type and they're getting the muted property.
Created with the rccode and it gets associated to the clinic approriately.

**Comment by dianabarsan** [comment]
Merged to `master`
