### ISSUE TITLE
Remove references to "Travis" from code and readmes

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7001]
**Describe the issue**
We have a bunch of references to Travis throughout the code, like: 
- readme references
- an entire script folder called Travis: https://github.com/medic/cht-core/tree/master/scripts/travis
- the extensive use of the `TRAVIS_BUILD_NUMBER` environment variable
- e2e tests conditional `IS_TRAVIS`
- [etc](https://github.com/medic/cht-core/search?q=travis)

**Describe the improvement you'd like**
Change references to Travis to a provider neutral name, like CI, `CI_BUILD_NUMBER`, `IS_CI` etc. 

**Describe alternatives you've considered**
Leave them as is, but it's triggering me all the time :D

**Comment by garethbowen** [comment]
Done.
