### ISSUE TITLE
Recompile default and standard config after medic-conf patch release

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7003]
Shadow issue for https://github.com/medic/medic-conf/issues/382 to recompile both reference apps once medic-conf is released.

**Comment by dianabarsan** [comment]
@abbyad do you think we should recompile the default config for 3.10 as well?

**Comment by abbyad** [comment]
I don't think it is required, but if it's just recompiling and pushing a commit in the 3.10.x branch I don't see any harm in that and it could be useful to avoid issues.

**Comment by garethbowen** [comment]
Removed from 3.11.0 - we only need to track this in one place. Forward port still required.

**Comment by dianabarsan** [comment]
I haven't forward ported this yet. Because of [this bug](https://github.com/medic/medic-conf/issues/387), I'm inclined to wait until we release next patch of `medic-conf` (since it's a dependency in both configs and needs to be updated). 
Since it was removed from 3.11, I have to keep a mental reminder of having to do this sometime in the future.

**Comment by ngaruko** [comment]
LGTM. Tested most `cht` supported actions.
