### ISSUE TITLE
Pushing standard config with latest medic-conf fails with translation errors

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7009]
**Describe the bug**
A new feature to [validate custom translations](https://github.com/medic/medic-conf/issues/254) was released in [medic-conf 3.4.1](https://github.com/medic/medic-conf/blob/v3.4.1/release-notes.md#340). However, `standard` config was not updated to pass this new validation, and fails the `upload-custom-translations` job. 

**To Reproduce**
1. Install latest medic-conf. 
2. Deploy an instance. 
3. Checkout latest `master` or `3.10.x`. Try to install `standard` config by running `medic-conf --local` or `medic-conf --url=<your url>`. Alternatively, just run the `upload-custom-translations` job. 
4. See a bunch of errors. 

**Expected behavior**
The config should be updated to run with latest version of medic-conf. 

**Logs**
```
ERROR Cannot compile 'hi' translation with key 'messages.d.validation.days_since_birth' has placeholders that do not match any in the base translation provided
ERROR Cannot compile 'id' translation with key 'messages.schedule.child.month_01' has placeholders that do not match any in the base translation provided 
ERROR Cannot compile 'id' translation with key 'messages.schedule.child.month_02' has placeholders that do not match any in the base translation provided 
ERROR Cannot compile 'id' translation with key 'messages.schedule.child.month_03' has placeholders that do not match any in the base translation provided 
ERROR Cannot compile 'id' translation with key 'messages.schedule.child.month_04' has placeholders that do not match any in the base translation provided 
ERROR Cannot compile 'id' translation with key 'messages.schedule.child.month_05' has placeholders that do not match any in the base translation provided 
```
and much more. 

**Environment**
- Instance: local instance
- Version: 3.10

**Additional context**
The workaround is to run the command using the new parameter `--skip-translation-check` to skip the validations.

**Comment by dianabarsan** [comment]
This appears to have been fixed by https://github.com/medic/cht-core/commit/7ac27b3ddb54466e752df8696c4c51f0c3f341e0#diff-70e6eaa1a95f9051ae26bc13e966ced0be6ddf3e9d43caa06bbfee4c3cabd445 in `3.11.0`.

**Comment by m5r** [comment]
I confirm no error is thrown when running the `upload-custom-translations` job with the standard config.

Only these warnings are being logged but these are not blocking in any way. I believe the Indonesian translations are no longer being maintained as we don't have any project needing them anymore.
```
INFO Processing config in standard.
INFO Actions:
     - upload-custom-translations
INFO Starting action: upload-custom-translations…
WARN Empty message found for key 'targets.active_pnc.title' in 'id' translation
WARN Empty message found for key 'targets.pnc_registrations.title' in 'id' translation
WARN Empty message found for key 'targets.pnc_visits.title' in 'id' translation
WARN Empty message found for key 'targets.homebirth_no_visits.title' in 'id' translation
WARN Empty message found for key 'targets.homebirth_1_visit.title' in 'id' translation
WARN Empty message found for key 'targets.birth_3_visits.title' in 'id' translation
WARN Empty message found for key 'targets.children_u5.title' in 'id' translation
WARN Empty message found for key 'targets.children_registered.title' in 'id' translation
WARN Empty message found for key 'targets.vaccines_given.title' in 'id' translation
WARN Empty message found for key 'targets.children_vaccinated.title' in 'id' translation
WARN Empty message found for key 'targets.past_3mos.subtitle' in 'id' translation
WARN Empty message found for key 'targets.children_not_vaccinated.title' in 'id' translation
WARN Empty message found for key 'targets.bcg_reported.title' in 'id' translation
WARN Found 13 empty messages trying to compile translations
WARN 'ex' is not a recognized ISO 639 language code, please ask admin to set the name
```
