### ISSUE TITLE
Use the Node eslint plugin to lint api and sentinel

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7017]
**Describe the issue**

It's easy to break backwards compatibility with old versions of Node and if we don't have a unit test for that specific line of code it won't fail the build.

**Describe the improvement you'd like**
Add the [Node eslint plugin](https://www.npmjs.com/package/eslint-plugin-node) using `"plugin:node/recommended"` and setting the `engines` property in `package.json` to ensure we don't break compatibility and we abide by best practice.

There is an equivalent [PR for medic-conf](https://github.com/medic/medic-conf/pull/388/) you can use for inspiration.

**Describe alternatives you've considered**
More unit test coverage or running old Node versions in development. Linting is easier.

**Why Now?**
Partner(s): Internal
Reason(s): Internally needs this ticket to facilitate the release, or reduce technical debt

**Comment by garethbowen** [comment]
Not a blocker for 3.15.0

**Comment by dianabarsan** [comment]
Merged to `master`.
