### ISSUE TITLE
In the form context.expression summary is undefined. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7022]
**Describe the bug**
Forms have a context.expression that gets evaluated to determine whether the form shows or not. The  contact, user, and summary are passed in. Placing a breakpoint on that function. The summary is always undefined. This breaks a lot of the form expressions in default config. 

**To Reproduce**
1. Upload the default config.
2. Log in as an offline user.
3.  Navigate to the people tab but do not open a person just yet.
4. Open chrome devtools and breakpoint on the line that defines the `evaluateExpression = function(` in main.js
5.  Try to open a person. 
6. When the breakpoint hits you can see the param that should include contact  summary is always undefined. 
7.  This causes all forms that have an expression trying to eval the contact summary to return false. 

**Expected behavior**
The contact  summary should be passed in and the forms should show. 

**Logs**
No logs in console

**Screenshots**

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: windows
- App: webapp
- Version: current master

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Ready for AT on `7022-fix-form-context`.

**Comment by newtewt** [comment]
Verified the complex default config expressions when true show the pregnancy form.
Used each variable(contact,user,summary) individually  and ensured they would go true.
Used all three together. 
Tried properties that didn't exist on each object and it false the check. 

@dianabarsan  this is ready to merge.

**Comment by dianabarsan** [comment]
Merged to `master`.
