### ISSUE TITLE
PR Builds are failing for external contributors

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7025]
**Describe the issue**
The cleanup scrips runs for PR builds for external contributors and always fails, because some environment variables are not set. 
Example build: 
https://github.com/medic/cht-core/pull/7019/checks?check_run_id=2145959595

**Describe the improvement you'd like**
The cleanup step should not run for external contributors. 

**Describe alternatives you've considered**
Alternative is to not fail the build when a step fails - if that's even possible.

**Comment by garethbowen** [comment]
This was supposed to be solved by [this line](https://github.com/medic/cht-core/blob/master/.github/workflows/build.yml#L186). My original idea was to check the secret environment variables, but if they're not set then we default them so it wouldn't work anyway. Another option is to set a new environment variable at the same time as we're defaulting the servers and check that.

In retrospect now that we're on GHA we have the option to create a cron job to do this cleanup in a separate Action, which is much nicer than slowing down the build and having to worry about external builds all the time. So yeah, do that!

**Comment by garethbowen** [comment]
Merged.
