### ISSUE TITLE
Tasks not displayed in Area person belongs to

### ISSUE THREAD

**Issue by brad1905** [medic/cht-core#7026]
**Describe the bug**
No tasks are displayed on the Area that includes a user with tasks. 

**To Reproduce**
1. create a person with tasks, i.e. pregnant woman with risk factors
2. go to person card, verify tasks are shown
3. click on Area person Belongs to
4. check Tasks section, tasks shown for pregnant woman are not displayed

**Expected behavior**
The tasks section should include tasks for the person 

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome
- Client platform:  MacOS
- App: webapp
- Version: 3.11

**Comment by dianabarsan** [comment]
@brad1905 
I'm not able to replicate this: 
![image](https://user-images.githubusercontent.com/35681649/112061056-9a80f600-8b66-11eb-801d-5289cefd59a2.png)

Can you please share more detail into what types of places are you using? 
Tasks should only be displayed when the viewed place is a leaf place type, means that it doesn't have any other child place types.

**Comment by dianabarsan** [comment]
@brad1905 
Please confirm if this is the place where you were expecting to see tasks: https://gamma.dev.medicmobile.org/#/contacts/4396b0b9-fb65-41ab-8bc2-ccd99a94c654

If yes, this area is not of a leaf type place. 
Also, if yes, can you please try adding the same reports for this person: https://gamma.dev.medicmobile.org/#/contacts/bf67096f-8d84-467c-8b31-322e708f2230 and check that tasks appear on this place: https://gamma.dev.medicmobile.org/#/contacts/f06e618e-c397-42b3-96ba-29cb8fd86c04

Thanks!

**Comment by brad1905** [comment]
Working as expected:
Tasks are only displayed when the viewed place is a leaf place type, means that it doesn't have any other child place types.

**Comment by dianabarsan** [comment]
Thanks a lot for the update @brad1905 !
