### ISSUE TITLE
SMS recipients might not be mapped correctly when using places as subjects

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7037]
**Describe the bug**
When a report is about a place, configured messages to be sent when transitions run over the report could get incorrect recipients. 

**To Reproduce**
1. Update your config to something like this:
```
        transitions: {
          generate_shortcode_on_contacts: true,
          accept_patient_reports: true,
          update_clinics: true
        },
        patient_reports: [
          {
            form: 'FORM',
            messages: [
              {
                event_type: 'report_accepted',
                recipient: 'link:clinic',
                message: [{ content: 'to clinic' }],
              },
              {
                event_type: 'report_accepted',
                recipient: 'link:health_center',
                message: [{ content: 'to health_center' }],
              },
              {
                event_type: 'report_accepted',
                recipient: 'link:district_hospital',
                message: [{ content: 'to district' }],
              },
            ]
          }
        ],
        forms: { FORM: { } }
```
2. Create a district_hospital, a health_center and a clinic, each of them with primary contacts with valid phone numbers.
3. Submit a `FORM` report as an SMS message from the district_hospital level contact, and have this report be about the clinic (have a `fields.place_id` property with the shortcode of your clinic). 
4. Wait until sentinel processes your doc and check the tasks on the message. All of them appear to have the sender as the recipient.

**Expected behavior**
The `link:<contact_type>` should connect to the correct contact from the subject's lineage (in this case, the clinic). 

**Environment**
- App: api, sentinel
- Version: 3.11

**Additional context**
I had forgotten to change this in the never ending list of changes to support places in SMS workflows.

**Comment by dianabarsan** [comment]
Ready for AT on `7037-fix-place-sms-recipient`

**Comment by ngaruko** [comment]
Tested as in the description above, on local machine. 
Ready to merge @dianabarsan - and oh! Thanks for adding an e2e test for this.

**Comment by dianabarsan** [comment]
Thanks @ngaruko ! Merged to `master`.
