### ISSUE TITLE
SMS message that isn't a report generates extra invalid messages

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7040]
**Describe the bug**
Sending a message the doesn't match an SMS form will generate a response message shown below. However, this seems to generate 5 responses of the same message. When only 1 was recieved. 

> SMS message received; it will be reviewed shortly. If you were trying to submit a text form, please enter a correct form code and try again.

**To Reproduce**
1. Setup medic-gateway and standard config to your instance. 
2. Configure a contact with a phone number. In my case I used my personal number. 
3. Send yourself a message that doesn't match an existing sms form(R Banana 2). I sent from my phone number to my phone number. 
4. Let gateway forward the message. 
5. The message should show in the messages tab since it isn't recognized as a form. 
6. Sentinel processes and attempts to send multiple invalid form codes. 

**Expected behavior**
We should only send one response for one invalid message. The duplicate catcher eventually sees it but not after sending a few messages.

**Logs**
If applicable, include the server or browser logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/10531066/112856972-5c139b80-907e-11eb-95f5-0c6234e2a01a.png)

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Windows/Linux
- App: medic-sentinel
- Version: master

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
>  The duplicate catcher eventually sees it but not after sending a few messages.

The default "duplicate catcher" permits 5 duplicate messages to be sent before marking them as duplicate, so this is expected. The number is configurable: https://github.com/medic/cht-core/issues/6094

**Comment by dianabarsan** [comment]
@newtewt 
From the screenshot, it seems like webapp *received* the autoreply message. Are you running Gateway on the same phone that is supposed to receive the message? 
Because this would explain the vicious cycle (and it would be expected).

**Comment by newtewt** [comment]
Yes that makes sense now. Sending and receiving the message and gateway sending it back. So it's not the same message it's the auto response triggering a new message and eventually getting caught being a duplicate. I'm closing this.

**Comment by dianabarsan** [comment]
On the plus side, we've just proved that the duplicate mechanism works as expected! 🚀
