### ISSUE TITLE
Loading places fails when using an offline user and the place has a primary contact that is not a child

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#7041]
**Describe the bug**
Once the contact is clicked, this and all other contacts are not accessible, clicking them returns back to contact list.

**To Reproduce**
Not easy to reproduce. It is happening to one contact!
1. Go to 'contacts'
2. Click on one contact

3. See error: The app goes back to contact list and clicking on other contacts from then on behaves the same (see attached video)

**Expected behavior**
Expecting contact summary
**Logs**
```
main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1 Error selecting contact DOMException: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:98578
    at Array.forEach (<anonymous>)
    at https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:98553
    at https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:98700
    at te._allDocs (https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:99029)
    at te.<anonymous> (https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:68334)
    at te.<anonymous> (https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:44402)
    at te.<anonymous> (https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:157275)
    at https://3291c9f839ce.ngrok.io/main.js?_sw-precache=ec225805f8b50fe7e7355b5aeab78ff2:1:43747
    at new e (https://3291c9f839ce.ngrok.io/polyfills.js?_sw-precache=76abd25b3b164a682f388e7a347960ef:1:20836)
```
**Screenshots**

https://user-images.githubusercontent.com/6979995/112930252-703ac400-9176-11eb-9fe7-d0d148f5b6f1.mov

**Environment**
- Instance: local
- Browser:  Firefox, Chrome, mobile
- Client platform: MacOS
- App: webapp
- Version:  3.10.X (`master`)

**Additional context**
The contact's doc:
```{
  "_id": "487f30e5-5279-4af6-8e0f-cf1f8e5a922b",
  "_rev": "2-523c0c72a27c038898f431a4b7819db4",
  "parent": {
    "_id": "8935e9d8-0b2a-5eb0-ae54-ad1377a60097",
    "parent": {
      "_id": "2112ab72-448a-50bb-a15d-0b19d2927ab7"
    }
  },
  "type": "clinic",
  "is_name_generated": "false",
  "name": "James",
  "external_id": "",
  "notes": "",
  "contact": {
    "_id": "745b50c4-9ebe-5515-b0cd-eec1d5438004",
    "parent": {
      "_id": "3a9cecea-8414-5768-9846-474d21b51e91",
      "parent": {
        "_id": "8935e9d8-0b2a-5eb0-ae54-ad1377a60097",
        "parent": {
          "_id": "2112ab72-448a-50bb-a15d-0b19d2927ab7"
        }
      }
    }
  },
  "geolocation": "",
  "meta": {
    "created_by": "andra",
    "created_by_person_uuid": "2e0ceb06-ced2-5a63-bca0-0283a5aab0e8",
    "created_by_place_uuid": "8935e9d8-0b2a-5eb0-ae54-ad1377a60097"
  },
  "reported_date": 1616112072875,
  "place_id": "51512"
}```

**Comment by dianabarsan** [comment]
The error is being thrown - identically - on `3.10.3`:
![image](https://user-images.githubusercontent.com/35681649/112936393-69885e80-912e-11eb-9481-7554103ee9b9.png)

Except it doesn't stop the contact from loading, so it may be unrelated. 
The error appears to be triggered by an `allDocs` request, when loading reports. and one of the keys we pass is undefined.

**Comment by dianabarsan** [comment]
Ok, found it! 

The error is triggered when getting tasks for a contact, when this contact has a primary contact that is NOT a child. 
This is how we add the primary contact to the children array: 
```
        children.push({
          doc: doc,
          isPrimaryContact: true
        });
```
https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/contact-view-model-generator.service.ts#L165
https://github.com/medic/cht-core/blob/3.10.x/webapp/src/js/services/contact-view-model-generator.js#L148

Then, in `tasksForContact` service, we expect every child to have an `id` property:
```
        model.children.forEach(child => {
          if (child.type.person && child.contacts && child.contacts.length) {
            contactIds.push(...child.contacts.map(contact => contact.id));
          }
        });
```
https://github.com/medic/cht-core/blob/3.10.x/webapp/src/js/services/tasks-for-contact.js#L20

We're never null-checking this list, as it makes it to the rules-engine lib: 
https://github.com/medic/cht-core/blob/3.10.x/shared-libs/rules-engine/src/provider-wireup.js#L210
which does an `allDocs` using the provided keys (including an undefined value) and triggers this error. 

The only difference between 3.10 and 3.11 is that in 3.11 we actually catch this error and "unload" the selected contact. 
The "unload" mechanism hasn't changed between 3.10 and 3.11 (3.10 also redirected to the list) - but this should be a separate improvement.

**Comment by dianabarsan** [comment]
Ready for AT on `7041-catch-contact-loading-errors`

**Comment by ngaruko** [comment]
The error does not show on the branch, using the same contact. Not 100% confident on this one since it was showing differently on `master` (contact not loading) and on `3.10.3` (error in console but contact loads). Please go ahead and merge @dianabarsan and we will keep an eye on in after merge and during RT.
![image](https://user-images.githubusercontent.com/6979995/113085420-3d5b0380-923c-11eb-8e83-2309d0c20803.png)

**Comment by dianabarsan** [comment]
> Not 100% confident on this one

Please elaborate. What would make you be confident of my fix?

**Comment by dianabarsan** [comment]
In `3.10.3` the error still happened, the only difference is that it didn't stop the contact from loading. 
It did, however, stop tasks from being calculated, from that point on - this is why you would see the same error when trying to open other contacts. 

Task recalculation effectively never worked after opening such a contact, on 3.10.3 and `master`, and this is why I marked the error as high prio and rushed to fix it. 

Maybe you could do a proper test on 3.10.3 to confirm this (I've already tested)
1. Open James
2. Navigate to the tasks tab. 
3. Tasks are not loading. (Error fetching tasks). 

To recalculate tasks, a person would need to refresh the page after opening such a contact - though I fear of a way where the rules engine state would be saved to disk and the user would be in this state permanently, but with my limited testing I haven't triggered that yet. 

cc @garethbowen

**Comment by garethbowen** [comment]
It's quite serious, but it's probably been around for a while and we haven't found it in the wild, so I think fixing in 3.11.0 is fine.

**Comment by ngaruko** [comment]
We can merge this @dianabarsan .

**Comment by dianabarsan** [comment]
Merged to `master`.
