### ISSUE TITLE
Improve how we handle contact loading errors in webapp 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7045]
**What feature do you want to improve?**
When any of the steps of loading a contact in webapp fails, loading the contact is stopped and the selected contact is unset. 
To replicate: 
1. Update default config and break the contact summary function, for example add:
```
console.log(thisContact.field.field.field);
```
somewhere in the `contact-summary.template.js` file. This will generate a TypeError: `TypeError: Cannot read property 'field' of undefined`. 
2. Login as any user, go to contacts and try to load any contact. 
3. Observe that the contact begins loading, children and reports appear, but when loading contact-summary, the contact detail page unloads and displays "No person selected". If in mobile view, you're also shown the list instead of the contact page. 

**Describe the improvement you'd like**
We should display an error page, and inform the user that there were errors while loading the contact. 
Our template even has a check for this and can display this error, so this functionality existed at some point. 

**Describe alternatives you've considered**
Keep it as it is. 

**Additional context**
I'm unsure when this came to be. The likely culprits are:
1. When we added redux in ~3.5.x
2. When we added lazy loading of contacts in ~3.4.x

**Comment by garethbowen** [comment]
Possible duplicate of https://github.com/medic/cht-core/issues/6388

**Comment by dianabarsan** [comment]
Yes, sorry. Closing!
