### ISSUE TITLE
Obtain estimated performance data of architecture v3

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-core#7054]
Run performance tests on a simulated architecture v3 setup and architecture v2 setup and gather metrics from each in order to determine the degree of performance improvements to be expected from a move from v2 to v3.

We have enough of the required pieces available now to be able to manually set up (aka "cobble together") such a test without needing to write all the code/config to make everything production-ready.

For the purpose of the test, the 2 setups should match as closely as possible, only differing in the specific parts that make v2 and v3 different. This is meant to be a test, so keep it as low-effort as possible and throwaway code/config is fine.

The output of this ticket is to be performance metrics around architecture v2 and architecture v3. 

API dev work: https://github.com/medic/cht-core/issues/7076
Scalability test work: https://github.com/medic/cht-core/issues/7077
SRE work: https://github.com/medic/medic-infrastructure/issues/301

[more details to follow in the interest of running this as an official experiment]

**Comment by garethbowen** [comment]
@craig-landry I think this was designed to cover the exploratory work which was completed late last year. If so, I think this can be closed as complete?

**Comment by henokgetachew** [comment]
That's correct @garethbowen. Closing as taken care of. Results have been shared publicly [here](https://forum.communityhealthtoolkit.org/t/how-we-tested-scalability-of-cht-infrastructure/1532)
