### ISSUE TITLE
CHT hosting improvements for App Developers

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7061]
### Describe the issue
CHT app developers, primarily App Services, currently use [CHT-Core Starter](https://github.com/medic/app-services-team/tree/master/cht-core-starter) (private repo) to do development for specific CHT deployments.  Starter's goal is to enable easy "one liner" deployments of CHT instances in a local dev environment.  

It, along with the complimenting [docker compose](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/) and [development](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md) approaches, faces some challenges:
* Current docker-compose option doesn't start reliably - 403 errors, 404 errors, 
* Docker or bare-metal installs have large internet requirements to use ngrok to get around serviceworker limitations. This is slow b/c routes local traffic via internet
* Multiple projects at the same time are hard (either literally concurrent to compare configs side by side, or working on 3 different deployment serially through out a day)
* Starter can be overly aggressive in deleting ~/.horticulturalist/deployments every time :(
* Starter downloads specific version every time (eg downloading 3.10 w/i horti) 

As well, there's a number of problem tickets related to this (some are dupes of above):
* [One-line app developer experience](https://github.com/medic/app-services-team/issues/72) 
* [Local config: Docker failed to create couchDB account - 404 Not Found](https://github.com/medic/cht-core/issues/6456)
* [medic-os docker: Research nginx not starting causing 404s ](https://github.com/medic/medic-infrastructure/issues/293)
* [Cannot login on localhost as restricted user ](https://github.com/medic/cht-core/issues/6168)
* [Publish a dev version of the docker-compose.yml](https://github.com/medic/cht-core/issues/6455)

### Describe the improvement you'd like
We should offer a public facing, docker based solution for App Developers that:
* caches as much as possible to avoid re-downloading CHT versions & docker images.  This will help greatly for developers who might be bandwidth constrained. 
* supporting the trifecta of macOS* / Windows WSL 2 / Linux development environments (_* - watch out for M1_)
* Offer dockerized version of couchdb to avoid having to run in couchdb in bare-metal (in WSL2 for example)
* support CHT back to version 3.5 and up to any posted version in GH (releases, betas & alphas)
* **Added Apr 22 '21** - Work in Architecture V2 so App Developers are developing on near identical configuration as to what is running in product
*  **Added Apr 22 '21** - Permit access to Fauxton (see [here](https://github.com/medic/cht-core/issues/6455#issuecomment-637047221))
*  **Added Apr 22 '21** - Work on which ever ports are open to avoid port collision (see [here](https://github.com/medic/cht-core/pull/6962#issuecomment-785606008) and [here](https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/#port-conflicts))
*  **Added Apr 22 '21** - Offer Valid SSL support out of the box to support android development (see [here](https://github.com/medic/cht-core/issues/6168))

### Describe alternatives you've considered
Continue using starter, docker-compose and bare-metal installs as we do today.

**Comment by mrjones-plip** [comment]
I propose an iterative approach, possibly resulting in a v1 and v2 release. So this is maybe a super ticket and we need to file sub-tickets (epic?!)?
* v1 - docker based feature replacement for [CHT-Core starter](https://github.com/medic/app-services-team/tree/master/cht-core-starter)
   * support service workers via [nginx-local-ip's](https://github.com/medic/nginx-local-ip) approach.
   * tested and documented on the 3 OSes
   * offer ability to specify CHT version back to 3.5
   * caching per above
* v2 - add on all the features that [One-line app developer experience](https://github.com/medic/app-services-team/issues/72) requests.  Possibly leverage this as the actionable ticket.

**Comment by Hareet** [comment]
@mrjones-plip Great timing!

@craig-landry Some fuel for arch v3 to be scheduled relating to value:
> caches as much as possible to avoid re-downloading CHT versions & docker images. This will help greatly for developers who might be bandwidth constrained.
>support CHT back to version 3.5 and up to any posted version in GH
- Related to : https://github.com/medic/cht-core/pull/6833 . This adds better use of docker layers
 All entrypoints to how services load across OS's is work that we need tested from the above ticket.
 
 > Offer dockerized version of couchdb to avoid having to run in couchdb in bare-metal (in WSL2 for example)
 - Resolved in arch v3: https://github.com/medic/medic-infrastructure/pull/256 
 (and we can move that to cht-core, but that deserves a separate discussion)
 
 > support CHT back to version 3.5 and up to any posted version in GH
 - Certainly a great idea. @craig-landry SRE wants to begin work on the peripheral tools that would make the transition one-line from 3.5 to 4.0. 
 
 
 > medic-os docker: Research nginx not starting causing 404s
 
 Resolved in arch v3 work: https://github.com/medic/medic-infrastructure/issues/254
 
 > Local config: Docker failed to create couchDB account - 404 Not Found
 
 Resolved in  arch v3 entrypoints: https://github.com/medic/medic-infrastructure/issues/118

**Comment by kennsippell** [comment]
cht-core-starter also allows devs to seamlesslly move between applications without 10-15 minutes of transitional setup. this is very useful for app services because one dev might work on 3-4 different cht applications.

cht-core-starter creates one unique couchdb database per app. this means that developers working on multiple apps have to seed data once and then it persists. 

starts the correct cht-core version for whatever application is in development. this means the correct version of cht-core is always running. which is particularly important since you can't downgrade when moving between projects on different versions. the only option is to delete your database and start fresh.

**Comment by mrjones-plip** [comment]
@Hareet  - awesome - thanks for all the input!  I really appreciate all the links to tickets and initiatives as I haven't been following them closely. 

@binokaryg and I had some concerns that maybe v3 was too far away time wise.  His quote on this was great:

> having two medium options is worse that one great one

I know v3 is tied to CHT 4.0 release, yeah? Given this, does a v3 based app developer solution feel like "weeks not months", "months not quarters" or "quarters not years" away?  Maybe a question for @abbyad, @garethbowen  or @michaelkohn ?

To possibly bypass larger CHT 4.0 planning/timing, from a purely technical perspective, could we release a v3 based solution for this ticket before 4.0? 

@kennsippell  - appreciate the extra details!

**Comment by Hareet** [comment]
@mrjones-plip 
We need this horti issue scheduled from devs: https://github.com/medic/horticulturalist/issues/47

And SRE to schedule: https://github.com/medic/medic-infrastructure/issues/127

It can be a matter of weeks, but since the horti issue will result in a breaking change, it needs to be a major release (4.0) and we need the willpower to release that. I'm hoping the requests here add more direct value to getting this piece scheduled. @garethbowen @craig-landry 

>To possibly bypass larger CHT 4.0 planning/timing, from a purely technical perspective, could we release a v3 based solution for this ticket before 4.0?

We need to cut the release at some point. I'd rather this be fuel to push that across the line, since that's what we are having trouble finding.

We would like to release the couchdb container with the other services in isolated containers. Otherwise SRE is in a point of diverting infrastructure and still handling requests on medic-os. The reason we haven't released isolated containers for other services is the upgrade service needs to be fixed to handle that scenario. That issue is having trouble getting scheduled. 

Anyways, I think most of your v1 plans can be released ahead, with the note that medic-os issues are fixed. And this whole thing will need to be re-architected as soon as 4.0 is scheduled. And you see how resolving this earlier would mean there's more reason to further delay 4.0 as it will cause more friction for already established environments. It's a tough position for SRE, and I'm trying to use anything to get that across the Product line.

**Comment by mrjones-plip** [comment]
@Hareet  - cool, thanks very much for all the updates on timing, impetus and fuel ;)  As soon as this project was assigned to me I could tell that the answer would a challenge: If it we we're doing this 12mo ago, we'd say, "do it with v2", if we were doing it 6mo from now, we'd say "do it with v3", so I very much appreciate that there's some tricky parts in trying to fit this in to the schedule sooner vs later.

I'm looking forward to making a great app developer experience and very much want @binokaryg  and @kennsippell  to keep us honest on quality and timing!

**Comment by Hareet** [comment]
@mrjones-plip 

@kennsippell dropped some knowledge that this particular hosting scenario doesn't need the ability to upgrade between versions, just launching particular versions.

That's huge!! Apologies, I missed that, and so there won't be a need for app developers to wait for CHT-Core 4.0 but gain the benefits of our current arch v3 work. We are working on having our current work merged related to services running in isolated containers. App Developers will be able to launch those for the 3.10+ releases without us having a formal release for partners to use. 

This will also help merge our goals of resolving any remaining issues with startup across environments!! No more medic-os requests! 🎈

**Comment by mrjones-plip** [comment]
Ah cool cool - thanks to both @kennsippell  and @Hareet for the updates!

So I understand the most recent development, is it accurate to say that  for this ticket App Services doesn't need the ability to deploy a local dev environment on v2 and then upgrade to v3 architecture. Instead, they need to be able to deploy CHT 3.x and upgrade to a later version, regardless of the architecture?  And that removing this dependency means we can deliver sooner than later?  

Yay! \o/

**Comment by Hareet** [comment]
@mrjones-plip I think its more along the lines of they will receive benefits of arch v3 early (beta?), and at some point will be requested to update their local environment again to match what we formally release.

They will be able to deploy isolated service containers per CHT version (3.10+ and branches), and upgrading between the versions would require changing images. For a dev environment, this is okay as view warming can occur on startup and but for large production datasets (BRAC) it would cause significant downtime. That's what the rewrite of horti ("upgrade service") needs to handle.

> And that removing this dependency means we can deliver sooner than later?
Yes, with the huge caveat of further diverging architecture between testing and production. Along with some great fuel to push arch v3 across the board.

**Comment by kennsippell** [comment]
So until Arch v3 is ready: to upgrade locally between versions, app devs can stop the docker containers running cht-core vCurrent and restart new docker containers running cht-core vNext.  To test upgrades, app devs need to use test instances (which we do anyway).

**Comment by mrjones-plip** [comment]
> app devs can stop the docker containers running cht-core vCurrent and restart new docker containers running cht-core vNext. This will skip view-warming, but that's not usually on a problem on dev machines (little data). 

Arch v3 beta (henceforth ;) will effectively swap the CHT API container out for the upgrade API container and keep the couch container static, yeah? And following the in CHT flow of "App Management -> Upgrades -> Install" won't work? I can see my lack of CHT knowledge is being exposed here, so apologies and thanks for helping me out.

> To test upgrades, we'll use test instances (which we do anyway).

This is great to know - thanks @kennsippell!

> They will be able to deploy isolated service containers per CHT version (3.10+ and branches)

@Hareet  - currently Starter supports back to CHT 3.5 but, to confirm, for the v3 beta only supports CHT 3.10+ - is that correct?

@kennsippell  and @binokaryg - is that acceptable if so?

**Comment by mrjones-plip** [comment]
Hey all! I'd like to keep this ticket moving, slow and steady wins the race as we say over here!

@Hareet  - The larger effort for this ticket feels like entirely an SRE task.  I'll assume this is the case unless I hear different (and wasn't entirely sure what @garethbowen had in mind when tapping me and @binokaryg to lead the charge on this beyond requirements gathering and testing).

@binokaryg and @kennsippell - Can you confirm 3.10 is an acceptable lowest version?  Maybe just for an MVP release and then we can overlay the 3.5 support on a later version?

CC @craig-landry  & @michaelkohn

**Comment by binokaryg** [comment]
Support for only 3.10 and above looks to be pretty limited at the moment but as 3.9 has been in EOL for a while, we should be upgrading the older versions anyway. So in the long term, it might not matter much as the majority of the projects get to 3.10 or above.

**Comment by mrjones-plip** [comment]
Thanks @binokaryg! I'm gonna keep the requirements at 3.5 and see where we end up.

@Hareet  - thanks very much for the helpful discussion around both v3 and the timing of things in this ticket.  I'd like to walk back my side of that conversation (at the gentle nudging of @garethbowen  ; ) such that:
 * This effort should support Arch v2 to enable App Services to have feature parity in dev environments to prod environments
 * Prioritization is up to SRE based on App Services request that this is critical to their success and respecting some tickets, like #6168, were open for 16+ months.

To clarify where we're focusing our efforts I have:
* Appended a few items to [the parent body](https://github.com/medic/cht-core/issues/7061#issue-858115790) of this ticket 
* Closed all related ticket and ensured this ticket captured those requirements

CC @craig-landry & @michaelkohn

**Comment by mrjones-plip** [comment]
Hareet and I chatted last week and agreed upon a plan: Instead of going back and fixing `medic-os` re 404s and such, we'll add two additional layers (literal docker layers) on top of it.  The first is to support TLS, we'll add the local-ip.co certs.  Then we'll do N more layers, one for each CHT version.  The net result will be an image per CHT version to allow easily spinning up a container with which ever version you need. Further, these images can be cached locally and changes will be captured in discrete docker image layers, so there's only a one time pain in downloading. We'll Finally, additionally health checks and documentation will be added to account for bootstrap errors (eg 404s) as well as how to run the environment on different OSes. 

I'll meet with @binokaryg this week to confirm it's good, but assuming it is, here's the check list and sub-tickets (will be updating this comment, stay with me!)
* [ ] [Add local-ip.co certs & CHT 3.5-3.11 then `docker commit` and publish](https://github.com/medic/medic-os/issues/53)
* [ ] [Add a `medic-os` helper script](https://github.com/medic/medic-os/issues/54) to check health of the containers (`medic-os` vs `haproxy`) as well as all the services with in `medic-os` (API, CouchDB, nginx). Along with helper scripts, we should document common errors and how to fix them for `medic-os` with `docker-compose`
* [ ] [Extend docker-compose.yml to allow for ports to be overridden to support developing for concurrent deployments](https://github.com/medic/medic-os/issues/55)
* [ ] [Document using `docker-compose` on Windows and macOS](https://github.com/medic/medic-os/issues/52)

**Comment by mrjones-plip** [comment]
While there is still work to do, I think the efforts in [the latest PR](https://github.com/medic/cht-core/pull/7374) which will be merged to `master` in the coming weeks, cover the day to day uses and resolve issues well enough.  I'm going to reach out to app services about what they think of this issue being closed to ensure we're being helpful!
