### ISSUE TITLE
Sort form filter and translation timing

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7066]
**Describe the bug**
Form filter items aren't sorted and when loading the app without cache some items aren't translated. 

Not ordered:
![image](https://user-images.githubusercontent.com/66472237/114986211-ec930e00-9ebd-11eb-9295-f07a052d41e7.png)

Translation:
<img width="1773" alt="Screen Shot 2021-04-16 at 11 58 37 am" src="https://user-images.githubusercontent.com/66472237/114986233-f61c7600-9ebd-11eb-827b-7172a9ce7298.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Clean browser cache.
2. Login. I used admin user.
3. Go to Reports.
4. Open the form filter dropdown.

**Expected behavior**
Form filter options should be ordered ascending and options translated.

**Environment**
- Instance: local
- Browser: Chrome
- App: Webapp
- Version: 3.11

**Comment by latin-panda** [comment]
Hi @newtewt This is the ticket, still not assigned to a release, waiting to see how it's going to be prioritised :) 
Let me know if any question

**Comment by latin-panda** [comment]
Ready for AT in https://github.com/medic/cht-core/pull/7065

**Comment by ngaruko** [comment]
**_Form order working:_**
![image](https://user-images.githubusercontent.com/6979995/117591042-87fa6480-b186-11eb-85b4-cb424259ea2e.png)

However the translations seem to still be missing. Am I missing something here @latin-panda ?
**_Translations:_**
![image](https://user-images.githubusercontent.com/6979995/117590981-17534800-b186-11eb-8fdc-2ec3276350f6.png)

**Comment by ngaruko** [comment]
@latin-panda - My bad. It was on muso config. The translations had not loaded with `medic-conf`. Loaded them manually and it works like charm.
![image](https://user-images.githubusercontent.com/6979995/117759639-3500da00-b278-11eb-8580-166c7a0b72d8.png)

Please feel free to merge
