### ISSUE TITLE
Admin upgrade page shows all upgrades as potentially incompatible

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7072]
**Describe the bug**
The upgrade page shows all releases as potentially incompatible regardless of what the base version is.

**To Reproduce**
1. Go to App Management > Upgrade instance

**Expected behavior**
- Final releases (version format `x.y.z`) that are less than the currently installed version are hidden.
- Final releases that are greater than the currently installed version are shown *without* a "potentially incompatible" warning.
- Other releases with unknown versions (eg: branch releases) are shown *with* a "potentially incompatible" warning.

For example, in the screenshot below, 3.11.0 should _not_ have the warning icon, because we know 3.11.0 is compatible with the currently installed 3.10.3.

**Logs**
None.

**Screenshots**
![Screenshot from 2021-04-21 14-54-29](https://user-images.githubusercontent.com/2064938/115623415-44fa5d80-a34d-11eb-983f-73e4ca8b3d4c.png)

**Environment**
- Instance: demo-cht.dev
- Browser: Firefox
- Client platform: Linux
- App: admin
- Version: 3.10.0, 3.11.0

**Additional context**

This warning is based on the `deploy_info` property in the `medic` ddoc. Before upgrading the value for this was...

```json
  "deploy_info": {
    "timestamp": "2021-03-24T15:33:58.070Z",
    "user": "medic",
    "version": "3.10.3"
  }
```

I debugged [this line](https://github.com/medic/cht-core/blob/master/admin/src/js/controllers/upgrade.js#L121) in the Upgrade controller which checks for the `base_version` which is undefined above. We should either store the `base_version` when upgrading, or use the `version` when the `base_version` is undefined.

**Why Now?**
Partner(s): Internal
Reason(s): A partner will have CHWs/Supervisors with a detrimental experience, thus providing bad care

**Comment by njogz** [comment]
This is ready for review on this [PR](https://github.com/medic/cht-core/pull/7519)

**Comment by tatilepizs** [comment]
Hi @njogz,
I was trying to test this ticket, but when I update the version to branch `7072-incompatible-upgrades` I am not able to test it properly because the lates version is 3.14, there is not a higher version yet, so I am not able to see if that _warning icon_ is not present is that specific scenario.
Is there something I could change or modify to actually see the change?
