### ISSUE TITLE
Enable archv3 scalability test in API

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-core#7076]
This is a part of the work that contributes to https://github.com/medic/cht-core/issues/7054

When clients come online and replicate it can cause a large increase in resource consumption in API and CouchDB. Other efforts are underway to make this scale better, but in order to take advantage of those efforts some changes need to be made in API.

The deliverable from this ticket is a throwaway branch of hacky bare-minimum code that will run replication in a scalable way. The purpose of this task is for API to function in archv3 well enough enough for us to run the scalability test against it.

**Comment by garethbowen** [comment]
@craig-landry I think this can be closed now that we're running a scalability test against archv3?

**Comment by garethbowen** [comment]
Closing as complete. @craig-landry Please reopen if you disagree.
