### ISSUE TITLE
Upgrade webapp to latest Angular

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7083]
**Description**

In our effort to keep CHT-Core dependencies up to date with technology:

1. Upgrade webapp's Angular version to the latest. See [guide](https://update.angular.io/).
2. Upgrade the @ angular-eslint to match Angular supported version.
3. Double check the version of ngx-cookie-service, @ ngrx/effects and @ ngrx/store matches the Angular supported version.
2. Check that it is working normally with no regressions. 

**Initial analysis with Angular 11.1.0**

I tried the `11.1.0` upgrade in local and [v12](https://angular.io/guide/roadmap) is almost out. 

The `11.1.0` version is applying 2 changes automatically:

1. Unit tests: `async` is deprecated and will be removed in v12, replace by [waitForAsync](https://angular.io/api/core/testing/waitForAsync)
<img width="550" alt="Screen Shot 2021-01-25 at 11 34 59 am" src="https://user-images.githubusercontent.com/66472237/105672416-f6d4ea00-5f16-11eb-9369-6aa0cdd8a6fc.png">

2. They fixed a bug in the routing and introduced the option: [relativeLinkResolution](https://angular.io/api/router/ExtraOptions#relativeLinkResolution). Check if we need the legacy or corrected option.
<img width="550" alt="Screen Shot 2021-01-25 at 11 44 39 am" src="https://user-images.githubusercontent.com/66472237/105672546-2f74c380-5f17-11eb-89c5-19bb2fd13fd7.png">

3. Typescript 4 is supported now, and apparently the AOT in angular compiler might work better with this version of typescript.

Remember to update dependencies in `cht-core/package.json`:
<img width="550" alt="Screen Shot 2021-01-25 at 2 14 57 pm" src="https://user-images.githubusercontent.com/66472237/105672854-b5910a00-5f17-11eb-9660-84257354136d.png">
<img width="550" alt="Screen Shot 2021-01-25 at 2 15 49 pm" src="https://user-images.githubusercontent.com/66472237/105672926-d6595f80-5f17-11eb-9d93-b63c71864158.png">
<img width="550" alt="Screen Shot 2021-01-25 at 2 16 25 pm" src="https://user-images.githubusercontent.com/66472237/105672980-ea04c600-5f17-11eb-9c25-e7013326d8de.png">

and `cht-core/webapp/package.json`, for example these:

<img width="550" alt="Screen Shot 2021-01-25 at 2 16 50 pm" src="https://user-images.githubusercontent.com/66472237/105673012-f9840f00-5f17-11eb-9137-7a21417bc748.png">
<img width="550" alt="Screen Shot 2021-01-25 at 2 17 04 pm" src="https://user-images.githubusercontent.com/66472237/105673033-01dc4a00-5f18-11eb-97ed-9ddad71f8c7d.png">

**Comment by garethbowen** [comment]
Angular have published a [Angular Update Guide](https://update.angular.io/) which may help here.
