### ISSUE TITLE
CouchDB Backup and Restore

### ISSUE THREAD

**Issue by andrineM** [medic/cht-core#7086]
Hi,
Do we have a  guide on how to go about creating the CouchDB Backup and restore?
Kindly Let me know

**Comment by garethbowen** [comment]
For Medic hosted instances we backup using AWS EBS snapshots and have brief [documentation on this](https://docs.communityhealthtoolkit.org/apps/guides/hosting/ec2-setup-guide/#backups). How are you hosting the CouchDB instance?

**Comment by andrineM** [comment]
@garethbowen We are using on-prem hosting and this information was shared with me and has been of help. 

The only way to backup CouchDB is by saving the files it uses. You can read more about it here. These are mainly found in 3 folders namely 
1. /srv/storage/medic-core/couchdb  (/data and /logs) for data and logs respectively. 
2. /srv/settings/medic-core/couchdb (for settings) 

May I kindly request your assistance on this issue earlier raised. 
https://github.com/medic/cht-docs/issues/482

**Comment by garethbowen** [comment]
The other way to back up CouchDB is by replicating to a separate CouchDB instance if you have internet access. The backup and restore process is covered in detail in [CouchDB's docs](https://docs.couchdb.org/en/2.3.1/maintenance/backups.html).

**Comment by dianabarsan** [comment]
One disadvantage of backing up using replication is that replication doesn't include local docs (https://docs.couchdb.org/en/stable/api/local.html#local-non-replicating-documents), and all PoudbDB replication checkpointers are saved as local docs. This means that, if you restore from a replicated database, your offline users will restart upwards replication.

**Comment by garethbowen** [comment]
@mrjones-plip Definitely. I think the right place for this section is part of [this doc](https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/), because the AWS hosting covers backup via EBS snapshot. What do you think?

**Comment by mrjones-plip** [comment]
@garethbowen  - perfect! I'll bang out a draft this week and we'll go from there.  Worst case, we can always promote it to it's own page later if we find we need a more stand alone resource (responding on a Sunday while I make up a bit of time lost this past Fri ; )

**Comment by mrjones-plip** [comment]
With the [new CouchDB backup docs](https://docs.communityhealthtoolkit.org/apps/guides/hosting/self-hosting/#backup) being published just now via medic/cht-docs/pull/491, I'm closing this ticket.  Thanks @andrineM  very much for pointing out how we can improve our documentation!
