### ISSUE TITLE
Store users' selected language in telemetry and feedback docs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7089]
**What feature do you want to improve?**
As a consequence of https://github.com/medic/cht-core/issues/7068, it's no longer possible to know what language users have selected, since it's no longer stored in the `user-settings` document.

**Describe the improvement you'd like**
I think the currently selected language should be stored in all feedback and telemetry documents. 

**Describe alternatives you've considered**
None. 

**Additional context**
Given that plenty of bugs have been isolated when a specific language was used, with some of these critically affecting production instances, it's extremely important that this information is available, accurate and relatively fresh. 

Data analysis might also find it useful to have this information, but maybe could cope with more stale data.

**Comment by latin-panda** [comment]
I've added the telemetry piece as part of this [PR](https://github.com/medic/cht-core/pull/7364), I'll add the feedback piece shortly in another PR that needs the latest work in language translation.

**Comment by dianabarsan** [comment]
@latin-panda The idea behind this issue is to add a property in **every** feedback doc, no matter what triggered it, that contains the user's language when the error occurred. 
A lot of errors that we see, that happen in various places in the app, only occur when a certain language is selected. The errors don't occur at the time of language selection, but after, when visiting another page.

**Comment by latin-panda** [comment]
Thanks Bede!
Waiting in https://github.com/medic/cht-core/issues/7294 to close before merging this one.

**Comment by latin-panda** [comment]
Merged into main branch.
