### ISSUE TITLE
Can't submit forms against muted contacts

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7091]
**Describe the bug**
We show a modal when before opening an action against a muted contact in webapp: 
![image](https://user-images.githubusercontent.com/35681649/117460214-f35cf000-af54-11eb-99b9-f556ad80660f.png)

The modal should close and do nothing if user clicks "No", but should redirect to the form if user clicks "Yes". 
Clicking "Yes" does nothing. 

**To Reproduce**
1. Deploy 3.11. 
2. Mute a contact (quick is to just add a `muted` property in the doc's json)
3. Open the contact in webapp and click to open a form against them (make sure this is not an unmuting form). Click yes in the popup. 
4. You're not redirected when you click yes. 

**Expected behavior**
You should be redirected when clicking yes. 

**Logs**
No logs.

**Environment**
- App: Webapp
- Version: 3.11

**Additional context**
This is a regression in 3.11 and is a one liner fix.

**Comment by dianabarsan** [comment]
Ready for AT on `7091-redirect-for-muted-contacts`

**Comment by ngaruko** [comment]
Added `muted` to the doc and submitted a form

1. Modal pops up and works as expected: 
2. _**No**_ does nothing 
3. _**Yes**_ - redirect to the actual form 

https://user-images.githubusercontent.com/6979995/117912583-dc8f1280-b333-11eb-8808-d52b80803340.mov

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by dianabarsan** [comment]
Thanks a lot for the quick AT, @ngaruko !!
