### ISSUE TITLE
Loading the About page throws an error

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7100]
**Describe the bug**
When you don't have a doc with ID `partners` then loading the About page logs an error.

**To Reproduce**
1. Make sure you don't have a doc with ID `partners` (delete it if you do)
2. Clear your local data and log in as a restricted user
3. Click on the hamburger menu
4. Click "About"
5. View error in the dev console

**Expected behavior**
No errors in the dev console.

**Logs**
```
feedback.service.ts:74 Error: Uncaught (in promise): {"status":404,"name":"not_found","message":"missing","reason":"missing"}
    at resolvePromise (zone.js:1255)
    at resolvePromise (zone.js:1209)
    at zone.js:1321
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:27425)
    at ZoneDelegate.invokeTask (zone.js:433)
    at Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.invoke (zone.js:520)
    at invokeTask (zone.js:1656)
```

**Screenshots**

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.12.0 (master)

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7102).

**Comment by ngaruko** [comment]
LGTM
Tested on local with branch `7100-missing-partners-doc`
**_on master_** 
![image](https://user-images.githubusercontent.com/6979995/119072307-5bc0cc80-ba3f-11eb-9dbb-5414194110fc.png)

**_on the branch_** 
![image](https://user-images.githubusercontent.com/6979995/119071784-8fe7bd80-ba3e-11eb-9f39-c661303563e0.png)

Not sure if the `Content Security Policy` error above is relevant @garethbowen , though not related to this PR.
