### ISSUE TITLE
Flaky e2e test "Pregnancy workflow on cht - should register a pregnancy"

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7109]
![image](https://user-images.githubusercontent.com/35681649/118938862-c4cd1500-b957-11eb-9005-2e8f9cdbb624.png)

**Comment by dianabarsan** [comment]
I believe this test has been disabled, but not yet fixed.

**Comment by tatilepizs** [comment]
This ticket is no longer valid, the test that  was failing doesn't exist anymore
