### ISSUE TITLE
Monitoring sentinel backlog values are wrong

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7113]
**Describe the bug**
The monitoring `sentinel.backlog` value is incorrect, as it counts changes depending on the value from the deprecated `_local/sentinel-meta-data` doc. 

**To Reproduce**
1. Load a 3.11 or 3.10 instance. Make sure you added some docs and Sentinel cleared the queue. The update a contact. Wait for Sentinel to clear the queue again. 
2. Request `api/v1/monitoring` and check the `sentinel.backlog`
3. Value is above 0. - the actual value can differ, if you just installed, it will be equal to the number of docs in the database, if you upgraded or you have an old `_local/sentinel-meta-data` doc, it will count changes depending on values stored in this doc. 

**Expected behavior**
The value should be correct.
Even if sentinel is "up to date", this value doesn't have to be 0. Sentinel skips from processing some docs and when a doc is skipped, the update_seq doesn't advance. 
To make sure that the value gets to 0, update a doc that will be processed, for example a contact or a report. 

**Environment**
- App: api
- Version: 3.10, 3.11, 3.12

**Additional context**
In `3.10` we [changed](https://github.com/medic/cht-core/pull/6408) the doc where Sentinel keeps its transition update_seq from  `_local/sentinel-meta-data` to `_local/transitions-seq` but the monitoring service code was not updated with this change.

**Comment by dianabarsan** [comment]
Ready for AT on `6572-sms-failure-monitoring`.

**Comment by ngaruko** [comment]
LGTM,
On 3.11, value shows 47, 
```
curl http://localhost:5988/api/v1/monitoring
{"version":{"app":"3.11.0","node":"v14.16.0","couchdb":"2.3.1"},"couchdb":{"medic":{"name":"medic","update_sequence":128,"doc_count":40,"doc_del_count":7,"fragmentation":1.0086177109165042},"sentinel":{"name":"medic-sentinel","update_sequence":2357,"doc_count":404,"doc_del_count":16,"fragmentation":2.887493382373429},"usersmeta":{"name":"medic-users-meta","update_sequence":91,"doc_count":79,"doc_del_count":0,"fragmentation":2.7933064134266323},"users":{"name":"_users","update_sequence":298,"doc_count":3,"doc_del_count":38,"fragmentation":14.213515599162164}},"date":{"current":1622416653918,"uptime":163.179494752},**"sentinel":{"backlog":47},**"messaging":{"outgoing":{"state":{"due":0,"scheduled":0,"muted":0}}},"outbound_push":{"backlog":0},"feedback":{"count":49},"conflict":{"count":0},"replication_limit":{"count":0}}
```

and branch , 0,
```
curl http://localhost:5988/api/v2/monitoring
{"version":{"app":"6572-sms-failure-monitoring","node":"v14.16.0","couchdb":"2.3.1"},"couchdb":{"medic":{"name":"medic","update_sequence":315,"doc_count":114,"doc_del_count":15,"fragmentation":1.0082911113705775},"sentinel":{"name":"medic-sentinel","update_sequence":2479,"doc_count":435,"doc_del_count":24,"fragmentation":4.362529248451196},"usersmeta":{"name":"medic-users-meta","update_sequence":91,"doc_count":79,"doc_del_count":0,"fragmentation":2.7933064134266323},"users":{"name":"_users","update_sequence":303,"doc_count":4,"doc_del_count":38,"fragmentation":13.543325355346065}},"date":{"current":1622419241984,"uptime":2127.792199684},**"sentinel":{"backlog":0}**,"messaging":{"outgoing":{"total":{"due":3,"scheduled":0,"muted":0,"failed":0,"delivered":0},"seven_days":{"due":3,"scheduled":0,"muted":0,"failed":0,"delivered":0},"last_hundred":{"pending":{"pending":3,"forwarded-to-gateway":0,"received-by-gateway":0,"forwarded-by-gateway":0},"final":{"sent":0,"delivered":0,"failed":0},"muted":{"denied":0,"cleared":0,"muted":0,"duplicate":0}}}},"outbound_push":{"backlog":0},"feedback":{"count":49},"conflict":{"count":0},"replication_limit":{"count":0}}
```

**Comment by dianabarsan** [comment]
Merged to `master`.
