### ISSUE TITLE
Nginx 404 Not Found - Fatal: Failed to create initial CouchDB administrative account

### ISSUE THREAD

**Issue by andrineM** [medic/cht-core#7115]
How was this [issue](https://github.com/medic/cht-core/issues/6456) resolved as am experiencing the same issue in a couple of instances:
Below are the couchDB and nginx logs. On startup I get the same error on original post:  

root@andrine:/srv# tail -f storage/medic-core/couchdb/logs/*.log 

[notice] 2021-05-23T15:04:14.884979Z couchdb@127.0.0.1 <0.329.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
[error] 2021-05-23T15:04:14.885813Z couchdb@127.0.0.1 emulator -------- Error in process <0.7874.0> on node 'couchdb@127.0.0.1' with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}

[notice] 2021-05-23T15:04:19.887383Z couchdb@127.0.0.1 <0.329.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
[error] 2021-05-23T15:04:19.888005Z couchdb@127.0.0.1 emulator -------- Error in process <0.7971.0> on node 'couchdb@127.0.0.1' with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,
195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}

Nginx Logs

==> storage/medic-core/nginx/logs/error-ssl.log <==
2021/05/23 15:06:37 [error] 5605#0: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5988/", host: "localhost"
2021/05/23 15:06:37 [error] 5605#0: *4 open() "/srv/storage/medic-core/nginx/data/html/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5988/", host: "localhost"

==> storage/medic-core/nginx/logs/access.log <==
127.0.0.1 - - [23/May/2021:15:06:37 +0000] "GET / HTTP/1.1" 404 198 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
![image](https://user-images.githubusercontent.com/53934661/119266352-22c95900-bbf3-11eb-8fb6-72c7d320c649.png)

![image](https://user-images.githubusercontent.com/53934661/119268451-b868e680-bbfb-11eb-9977-8192e8ddf537.png)

Please assist

**Comment by garethbowen** [comment]
Hi @andrineM - apologies for the delay in getting to this issue. Please submit this as a Technical Support post on the [CHT Forum](https://forum.communityhealthtoolkit.org/) where it'll get seen by more people.
