### ISSUE TITLE
Record device id in feedback docs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7127]
**What feature do you want to improve?**
Currently, feedback docs contain some key information which is useful for debugging purposes, like: the app version, users' roles, and the active url. However, in some cases, it's very useful to know for certain that multiple feedback docs were generated on the same device (since the same user could be logged in on multiple devices). 

**Describe the improvement you'd like**
Store the device Id in feedback docs. 

**Describe alternatives you've considered**
None. This is a very easy change, with virtually no cost. 

**Additional context**
I came across a situation where I was using a sequence of feedback docs to debug some behavior and it would have been very useful to know for certain that the feedback docs came from the same device.

**Comment by elvisdorkenoo** [comment]
ok, got it, thanks @ngaruko.

**Comment by dianabarsan** [comment]
Hi @ngaruko 

> There is a glitch though where the branch is not showing on the upgrade page

Can you please show us which branches do appear in your upgrade list? My guess is that your docker-compose file for the CHT uses the old `builds` database instead of `builds_4`. Locally, using `builds_4`, I can see this branch in the upgrade list. 

![image](https://user-images.githubusercontent.com/35681649/204267489-ddfeb4df-af17-4e0b-a619-631dbcb29e91.png)


Can you try to update your docker-compose files, and use latest master compose files, launch your local instance, and check whether you see this branch? Thanks!

**Comment by elvisdorkenoo** [comment]
thanks @ngaruko
