### ISSUE TITLE
Flaky e2e test "Adding new language should add new translations"

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7133]
**Describe the issue**
![image](https://user-images.githubusercontent.com/35681649/121337238-003e7c00-c925-11eb-8858-68a31edae503.png)

**Describe the improvement you'd like**
Fix the e2e test.

**Comment by garethbowen** [comment]
Success rate as of today: 100%

**Comment by ngaruko** [comment]
Is this still flaky @garethbowen? Looks like we haven't skipped it .

**Comment by garethbowen** [comment]
Maybe not. For some reason our build history isn't working again, so I can't tell for sure, but I have no recollection of it failing. Closing - reopen if it fails again!
