### ISSUE TITLE
Tasks fail to load when priority labels are empty

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7137]
**Describe the bug**
ngx-translate (which is the tool we use to internationalize webapp) throws an error when it gets passed an empty string as a translation key. 
When using a nools-based config (non-declarative) there are no constraints on tasks priority labels. 
For declarative config, need to be undefined or be at least one character long: https://github.com/medic/medic-conf/blob/master/src/lib/validate-declarative-schema.js#L128
Having an empty string as a task priority label will stop the tasks list from loading. 

**To Reproduce**
1. Deploy 3.11 with a nools based config
2. Update a task and set its priority label to an empty string. 
3. Login as an offline user and trigger the task to generate. 
4. See error when loading tasks

**Expected behavior**
Tasks should load correctly. 

**Logs**
```
Error: Parameter "key" required
        at TranslateService.instant (projects/ngx-translate/core/src/lib/translate.service.ts:439:13)
        at RulesEngineService.translateProperty (_karma_webpack_/src/ts/services/rules-engine.service.ts:344:4)
        at http://localhost:9876/_karma_webpack_/src/ts/services/rules-engine.service.ts:390:4
        at Array.forEach (<anonymous>)
        at RulesEngineService.translateTaskDocs (_karma_webpack_/src/ts/services/rules-engine.service.ts:369:3)
        at apply (_karma_webpack_/main.js:298517:20)
        at ZoneDelegate.invoke (_karma_webpack_/node_modules/zone.js/dist/zone.js:400:30)
        at ProxyZoneSpec.onInvoke (_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:301:43)
        at ZoneDelegate.invoke (_karma_webpack_/node_modules/zone.js/dist/zone.js:399:56)
        at Zone.run (_karma_webpack_/node_modules/zone.js/dist/zone.js:160:47)
```

**Environment**
- App: webapp
- Version: 3.11

**Additional context**
The workaround (thanks to @derickl ) is to set the task labels to be undefined. 
This bug might affect other areas of the app where we accept translation keys from configuration.

**Comment by dianabarsan** [comment]
This is ready for AT on `7137-empty-translations-fix`. Besides the specific tasks fix, translations should work fine throughout the app.

**Comment by ngaruko** [comment]
1. Tested on local modified `standard` config, set the `priority label` to an empty string for new pregnancy and delivery reports emitted tasks in `tasks.js` :
```
if (isHighRiskPregnancy(c, r)) {
        return {
          level: 'high',
          label: '',
        };
      }
```
on 3.11 => tasks are not loaded 
But loaded on the branch `7137-empty-translations-fix`, no errors in console or api logs 
![image](https://user-images.githubusercontent.com/6979995/122865229-22e78080-d37a-11eb-9885-9b16de48010c.png)

2. Checked change of locale via `edit user` 
![image](https://user-images.githubusercontent.com/6979995/122865976-58d93480-d37b-11eb-879d-2a48b81c233d.png)

3. Maybe I missed something @dianabarsan . I do remember us changing the way change of locale works. ATM, changing the app default language in the admin portal `/admin/#/display/languages` does not seem to have any impact (though the outgoing messages are translated). But it seems to happen on earlier version, so it is not necessarily related to this PR _ Will look into it a little further...
![image](https://user-images.githubusercontent.com/6979995/122867029-06991300-d37d-11eb-9a59-270af97cda08.png)

**Comment by dianabarsan** [comment]
@ngaruko 
Related to 3. The locale is now set based on the users's browser locale upon login, and then only by them changing their language locally. We only fall back to the default locale if the locale cookie is missing. 
We've had a series of issues that gradually remove the ability of setting users' locales from other places, as they were not working and just created confusion.

**Comment by dianabarsan** [comment]
Merged to `master`.
