### ISSUE TITLE
Require additional permission for accessing the upgrade page and/or upgrade api endpoint

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7139]
**What feature do you want to improve?**
At the moment, any user with "can_configure" permission can initiate an upgrade. The "can_configure" is a very broad permission with makes a user akin to an admin, and is required to enable users to make any config/app/users changes. However, more granularity would be desirable to reduce risk of accidental/unplanned upgrades. 

**Describe the improvement you'd like**
Add an additional permission for accessing the upgrade page - or still permit access, but show a message that the user doesn't have the required permission to upgrade. Additionally, the same permission should be required to access the /upgrade api endpoint. 

**Describe alternatives you've considered**
Leave everything unchanged. 

**Additional context**
We've recently had an incident where an unscheduled upgrade was initiated by a user who had "can_configure" permission to help with user management. This untested upgrade caused a significant disruption. 

**Why Now?**
Partner(s): Internal
Reason(s): Partner will have CHWs/Supervisors with a detrimental experience, thus providing bad care

**Comment by njogz** [comment]
@garethbowen I have a [PR](https://github.com/medic/cht-core/pull/7565) open and a documentation [PR](https://github.com/medic/cht-docs/pull/653) as well

**Comment by njogz** [comment]
Ready for review on this [PR](https://github.com/medic/cht-core/pull/7565) and the documentation updated on this [PR](https://github.com/medic/cht-docs/pull/653)

**Comment by ngaruko** [comment]
@njogz Should we maybe add this permissions to our default [permissions](https://github.com/medic/cht-core/blob/7139/additional-permissions-for-upgrade-page/config/default/app_settings.json#L77)?

**Comment by njogz** [comment]
@ngaruko that's a good suggestion. I have [added](https://github.com/medic/cht-core/pull/7565/commits/cade390a2fd473d29ce784018f5d9ba7bfc454aa) the new permission as suggested.

**Comment by ngaruko** [comment]
1. Permission added to admin portal:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/6979995/160970803-6629586f-cc00-47c4-8dbb-097d8ba89f6b.png">
2. `can_upgrade` permission removed from UI when disabled for the user
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/6979995/160971717-1c697cb0-8111-4cd8-a8b8-73da8e97ab60.png">
3. However if the user type in the `upgrade` url, they are able to access the `upgrade` page?  
<img width="914" alt="image" src="https://user-images.githubusercontent.com/6979995/160971913-305edc52-2341-46b4-a977-ba0f64d749bf.png">
Maybe we should display the class `access denied page` @njogz ?
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/6979995/160972994-18c41af6-32df-405b-9003-c91d61e4376c.png">

Though they cannot upgrade 
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/6979995/160972503-4c3cfca0-d161-4399-abb5-e10d025b83eb.png">
```
REQ 2ad71d04-2de3-4cd1-ae75-9fb9b8279ded ::1 - POST /api/v1/upgrade HTTP/1.1
RES 2ad71d04-2de3-4cd1-ae75-9fb9b8279ded ::1 - POST /api/v1/upgrade HTTP/1.1 403 - 102.200 ms
```
4. API endpoint secured 
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6979995/160972381-66d61bf1-fff3-4108-9e30-40324b5a4a54.png">
```
REQ 811c8507-4bb2-4f15-afc1-83e8afc4e647 ::ffff:127.0.0.1 testbede POST /api/v1/upgrade HTTP/1.1
RES 811c8507-4bb2-4f15-afc1-83e8afc4e647 ::ffff:127.0.0.1 testbede POST /api/v1/upgrade HTTP/1.1 403 - 46.181 ms

```

**Comment by njogz** [comment]
@ngaruko the error page you showed is from the webapp right? Maybe we should have a different issue for adding a similar error page to the admin app? I have u[dated the code so that the content is not displayed if the user does not have the require permission. This is similar to how the "Import and export data" page behave currently.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1227336/161629341-e2ed9165-636c-4420-b138-9e09ed1bedb7.png">

Import and export data page with permissions
![image](https://user-images.githubusercontent.com/1227336/161629500-87b1d39b-4d4e-4f6f-9da5-c64cdc188bb0.png)

Import and export data page without permissions
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/1227336/161629842-b2339fc9-d5a8-4e78-b8bd-82e7fcf0db92.png">

**Comment by ngaruko** [comment]
Thanks @njogz . I created an [issue](https://github.com/medic/cht-core/issues/7579) for this. Is this one ready to AT ?

**Comment by njogz** [comment]
> Is this one ready to AT ?

@ngaruko yes it is.
