### ISSUE TITLE
Feedback docs: "409: Document update conflict"

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-core#7148]
**Describe the bug**
In the month of  May 2021, the feedback documents for `brac-ug` (3.9.2) had this error recorded 38 times from 31 users:

`Possibly unhandled rejection: {"status":409,"name":"conflict","message":"Document update conflict","error":true}`

Most of these are from the tasks page, and others from the contacts and targets page:

Location based on URL | Count (May 2021)
-- | --
Tasks page | 26
Contacts page | 6
Targets page | 2
Specific contact | 1
Family survey form from contact | 1
Family survey task| 1
About page| 1

**Logs**

Here is the top-level argument for each of the 38 incidents (brac-ug, May 2021):

Level | Arguments | Count
-- | -- | --
warn | db.type() is deprecated and will be removed in a future version of PouchDB | 18
error | Error updating _local/rulesStateStore: {\\\"status\\\":409,\\\"name\\\":\\\"conflict\\\",\\\"message\\\":\\\"Document update conflict\\\"} | 7
warn | MaxListenersExceededWarning\",\"2\":\"Possible EventEmitter memory leak detected. 11 \\\"destroyed\\\" listeners added. Use emitter.setMaxListeners() to increase limit. | 4
warn | No active pages found. Make sure your form has at least one relevant input. | 4
info | The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists. | 4
log | Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored. | 1

**Environment**
- Instance: brac-ug.app.medicmobile.org
- Version: 3.9.2

**Additional context**
This error is being recorded every month since we started collecting the feedback docs in August 2020, the highest being 80 times in September 2020, followed by 75 times in March 2021 for `brac-ug`.

Similar error is also recorded for `pih-malawi` every month, although less frequent (1-14 times a month).

**Comment by kennsippell** [comment]
roughly 163 docs matching this pattern this month for PIH production data

**Comment by dianabarsan** [comment]
I'm hitting the `Error updating _local/rulesStateStore: {\"status\":409,\"name\":\"conflict\",\"message\":\"Document update conflict\"}` error consistently in an e2e test once I started recording feedback docs every time `console.error` is called.
