### ISSUE TITLE
Release Notes for v3.8 have link to private repository (broken link for external users)

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#7165]
**To Reproduce**
1. Navigate to [cht-core v3.8 release notes](https://github.com/medic/cht-core/blob/master/release-notes/docs/3.8.0.md#breaking-changes)
2. Click link for [schema changes](https://github.com/medic/medic-projects/commit/3bb4cd5ade155cb7eca0e0ea6791cc82796d3949)

Observed: Link is broken for external users
Expected: Link works for external users

**Comment by kennsippell** [comment]
Maybe release notes link to a [forum post similar to this explanation](https://forum.communityhealthtoolkit.org/t/v3-9-support-for-legacy-rules-nools-js/1322)

**Comment by garethbowen** [comment]
This was fixed while moving release notes from cht-core to cht-docs. The doc with the fixed link is: https://docs.communityhealthtoolkit.org/core/releases/3.8.0/
