### ISSUE TITLE
Improve handling of upgrading to a non-existing version

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#7172]
**What feature do you want to improve?**
Re: #6602 
When passing a package that does not exit to the `/api/v1/upgrade/` api request (```curl https://user:pass@localhost/api/v1/upgrade/stage -k -X POST -H "Content-Type: application/json" -d '{"build":{"namespace":"medic","application":"medic","version":"'1232-enketo-bundling'"}}'```)
 , the upgrade page hangs in the UI.

and `horti` dies.
```
Failed to download build for [medic:medic:non-existing-package]. Aborting install.
  horti:debug Delete deploy ddoc +2s
********FATAL********
{
  error: 'not_found',
  reason: 'missing',
  status: 404,
  name: 'not_found',
  message: 'missing',
  docId: 'medic%3Amedic%3Anon-existing-package'
}
+ app=medic-api
+ echo '[bin/svc-stop] Stopping medic-api...'
[bin/svc-stop] Stopping medic-api...
+ pgrep -f HORTICULTURALIST_APP=medic-api
+ xargs kill
+ app=medic-sentinel
+ echo '[bin/svc-stop] Stopping medic-sentinel...'
[bin/svc-stop] Stopping medic-sentinel...
+ pgrep -f HORTICULTURALIST_APP=medic-sentinel
+ xargs kill
2021-06-30 10:32:24 DEBUG: change event on doc horti-upgrade seq 656-g1AAAAIjeJyV0TEOwjAMAMCIIsECX4AfkCZVCQt04QmwQpK6qqqSDLDDT-An8BP4BHNJ3E4gpHaxJcs-yXZJCBnmQUpGxhqbQmJsbo-n0pV7kqhJVVVFHsjlwRUGMpQ8YuK7-c-4mrqoVo1AUdApVYJBWyHxwq4RxijwUGuWybbC3gvnRtigABBp4HFLwfRdJBeXHHL1yhqViM_DmNFOyq1W7l6ZocJ4DJJ3Ux618vTKFhWRiQXT3TZ61Qre5Y0KFYqC-Plu8QESPqoI 
RES e92913ae-a9f2-46b7-8854-ff712a4a0d3a ::ffff:127.0.0.1 - GET /medic/_changes?feed=longpoll&heartbeat=10000&since=655-g1AAAAIjeJyV0TEOwjAMAMCIIsECX4AfkCZVCQt04QmwQpK6qqqSDLDDT-An8BN4BHtJ3E4gpHaxJcs-yXZJCBnmQUpGxhqbQmJsbo-n0pV7kqhJVVVFHsjlwRUGMpQ8YuK7-c-4mrqoVo1AUdApVYJBWyHxwq4RxijwUGuWybbC3gvnRtigABBp4HFLwfRdJBeXHHL1yhqViM_DmNFOyq1W7l6ZocJ4DJJ3Ux618vTKFhWRiQXT3TZ61Qre5Y0KFYqC-Plu8QESIKoH&limit=25 HTTP/1.1 200 - 1458.172 ms
+ echo '[bin/svc-stop] medic-api stopped.'
[bin/svc-stop] medic-api stopped.
+ echo '[bin/svc-stop] medic-sentinel stopped.'
[bin/svc-stop] medic-sentinel stopped.
bin/svc-start: line 9: 84545 Terminated: 15          node server.js HORTICULTURALIST_APP="$app"
bin/svc-start: line 9: 84542 Terminated: 15          node server.js HORTICULTURALIST_APP="$app"
```
Upon restarting `horti`, the admin portal seems to suggest that the upgrade was successful

![image](https://user-images.githubusercontent.com/6979995/124212478-1fef4b80-db43-11eb-9303-422d1fbf33a8.png)

Two issues I see here, one of which might have been considered but maybe hard to implement from a tech perspective, and that is, is there a way to rather check the package and return an error message, without crashing the app/horti? That would be ideal.
The second issue as seen on the second screenshot, one would expect an aborted message rather than a successful upgrade.

**Describe the improvement you'd like**
It would better to check that the version exists and fail safe if it does not, ie error telling the user the version does not exist or a typo? but `horti` keeps alive.
Plus a message in the UI that the upgrade was aborted, or better yet, not start anything in the UI until that check has been done!
**Describe alternatives you've considered**
Not a blocker at the moment. See [comment](https://github.com/medic/cht-core/issues/6602#issuecomment-872542342) on original ticket

**Comment by garethbowen** [comment]
Upgrading is completely changing in 4.0.0 so I'm going to close this.
