### ISSUE TITLE
Admin app's select2 search fields don't have focus when clicking on it.

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7173]
**Describe the bug**
There is a UX change to forms where the user has to click twice before starting typing (specifically clicking again in the input text) because it doesn't have the focus set, before it only required one click. 

**To Reproduce**
Steps to reproduce:
1. Go to Admin app.
2. Select users tab.
3. Click on "Add User"
4. Click on "Place" field, focus isn't on the input and requires the user to click on it before typing.  

**Expected behaviour**
The input should have the focus when clicking in the search field (select2).

**Screenshots**
![image](https://user-images.githubusercontent.com/66472237/124579232-1f272400-de79-11eb-9055-20d95099ba60.png)

**Environment**
- Instance: master
- Browser: Chrome
- App: admin
- Version: 3.12

**Additional context**
Select2 has some known issues related to focus:
- Select2 issue: (# 5993) Search not auto focusing in jQuery 3.6.0 
- [Bootstrap modals](https://select2.org/troubleshooting/common-problems)

**Comment by ngaruko** [comment]
Looks good atm @latin-panda 
**_Before_**

https://user-images.githubusercontent.com/6979995/124669479-8dfe8e80-df06-11eb-9969-4daa0a0a773e.mov


**_After_**

https://user-images.githubusercontent.com/6979995/124669543-aa9ac680-df06-11eb-84cd-3ebe3eb2e654.mov
