### ISSUE TITLE
Client requests receive a 502 statuscode after 2 minutes of idle time

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7183]
**Describe the bug**
Long-running requests that idle for more than 2 minutes will receive a 502 status from the AWS load-balancer. (longpolls to _changes are excluded, these requests send a heartbeat every 10 seconds and are not considered idle). 
Such requests should not occur, but they may happen when the server is under heavy load. 
On the client, these 502s will be recorded as feedback docs. See https://github.com/medic/cht-core/issues/7147

**To Reproduce**
Three options: one is time consuming, and two are not. 

Time consuming option: 
1. Get an instance with a sizeable amount of docs and users. I worked on a production clone. 
2. Find a few users (10-20) that have most docs (including purged ones). 
3. Write a script that hits the instance, requesting `/medic/_changes` for these users concurrently and continuously. (no params added to the changes request, so it's not a longpoll). 
4. Notice that when requests exceed 2 minutes, the response is a 502. 

One caveat is that it might take either a long time to load the server to this point or you'll need misconfigured users that have tens of thousands of documents. 

Less time consuming option 1: 
1. Write a script that generates a large amount of uuids (the number necessary depends on the system you're running this against). 
2. Through API, as an admin, request changes with a doc_ids filter with these uuids. It doesn't matter the docs don't exist in the database you're requesting them from. 
3. Time the request. 
4. Catch the 502 you'll eventually get. 

Less time consuming option 2 that requires adding an endpoint: 
1. Add a new endpoint to api that responds after two minutes and 10 seconds (add it somewhere close to the top of the /api/src/routing.js file, for example here: https://github.com/medic/cht-core/blob/master/api/src/routing.js#L192) 
```
app.get('/two-minute-timeout', (req, res) => {
  const timeoutMs = 60 * 2 * 1000 + 10 * 1000;
  setTimeout(() => {
    res.send(`This request responds after ${timeoutMs / 1000} seconds`);
  }, timeoutMs);
});
```
2. curl this endoint like: 
```
time curl http(s)://<instance>/two-minute-timeout
```
3. Wait for 2 minutes to observe this result: 
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

real    2m0.247s
user    0m0.016s
sys     0m0.000s
```

If running this against a local install that doesn't sit behind an AWS load-balancer, you'll see: 
```
curl: (52) Empty reply from server

real    2m0.012s
user    0m0.006s
sys     0m0.000s
```

**Expected behavior**
We should not send 502s unless the API service is down. For example, CouchDB timeouts with a 500 error. We should also timeout with an error, and overwrite the default node http timeout: https://nodejs.org/docs/latest-v8.x/api/http.html#http_server_settimeout_msecs_callback

**Environment**
- Instance: production, clone, local
- App: api
- Version: any? 

**Additional context**
The default node http server timeout is 2 minutes in v.8 (https://nodejs.org/docs/latest-v8.x/api/http.html#http_server_settimeout_msecs_callback), v.10 (https://nodejs.org/docs/latest-v10.x/api/http.html#http_server_settimeout_msecs_callback), v.12 (https://nodejs.org/docs/latest-v12.x/api/http.html#http_server_settimeout_msecs_callback). 
The default timeout is 0 in v.14 - equivalent to setting no timeout at all.

**Comment by dianabarsan** [comment]
This is ready for AT on `7183-no-timeout-take-2`. 
API requests should have no timeout.

**Comment by dianabarsan** [comment]
I'm posting the script that I used for reference: 
```
const rpn = require('request-promise-native');
const uuid = require('uuid').v4;

const auth = {
  username: 'admin',
  password: '<your password>',
};
const url = '<API url>';
const nbrUuids = 1000000;
const ids = Array.from({ length: nbrUuids }).map(() => uuid());

const start = new Date().getTime();
rpn
  .post({
    url: `${url}/medic/_changes?filter=_doc_ids`,
    auth,
    json: true,
    body: { doc_ids: ids },
  })
  .then(response => console.log(response))
  .catch(err => console.error(err))
  .finally(() => {
    console.log('done after', (new Date().getTime() - start) / 1000, 'seconds');
  });
```

Running against a dev instance (no ngnix) yields a `socket hang up` after 120 seconds. 
Running against a prod instance (behind AWS Load Balancer) yields a 502 after 120 seconds: 

![image](https://user-images.githubusercontent.com/35681649/125732258-f2b02afa-820f-46cb-98fa-599c4ae7fc98.png)

I'm not sure what happens against medic-os in docker, as it depends on the ngnix config which I'm not familiar with, but the 502 shown above is sent by the AWS Load balancer, in response to the socket hanging up with an empty response - it interprets this timeout as if the service is not available - hence the 502.

**Comment by newtewt** [comment]
@dianabarsan 

I've confirmed the requests over two minutes in length are processing to completion.

I was able to recreate this error in 3.9 on gamma-b environment. Upgraded to the branch fix and execute the same requests and they complete after 2 minutes.  

During the request processing, I also initial replicated a user on a fresh install of the webview app. Created a bunch of docs and synced with no issues. Seeing the docs on the server fine.

Any other thoughts? Otherwise I think we can start with the point releases.

**Comment by dianabarsan** [comment]
Thanks for the extensive tests, @newtewt 

any thought from @garethbowen before we domino this?

**Comment by mrjones-plip** [comment]
No need to hold this ticket up at all, but as a quick aside about this:

> I'm not sure what happens against medic-os in docker, as it depends on the ngnix config which I'm not familiar with,

I'm not 100% sure, but my guess is that the node timeout of 120 (seconds) will fire before any of nginx's timouts which look to be 300 (seconds) or greater:

```
docker exec -it medic-os grep _timeout /srv/settings/medic-core/nginx/nginx.conf
    keepalive_timeout     300;
    proxy_read_timeout    600;
        ssl_session_timeout         10m;
```

**Comment by garethbowen** [comment]
It looks fine to me. Go ahead and backport cht-core.

I'm curious if the nginx timeouts will be hit now that we've removed the Node timeout. @newtewt Did any of your tests cover requests that last > 10 minutes (the largest of the timeouts that @mrjones-plip found)? If not, would it be easy to test?

This doesn't hold up the release because any changes to nginx config can be released separately to API.

**Comment by newtewt** [comment]
@garethbowen  @mrjones-plip  I can test that during the point releases.  However, I don't believe nginx within medic-os is actually running in our k8s environment. Atleast on gamma-b.dev it's in a failed state. I assume the serving is coming from somewhere else.

**Comment by garethbowen** [comment]
Yeah that was my recollection too... but it's complicated enough I can't tell for sure  :smile:

**Comment by dianabarsan** [comment]
Merged to `master` and backported to `3.12.x`, `3.11.x` and `3.10.x`.

**Comment by newtewt** [comment]
@garethbowen  @mrjones-plip  there doesn't seem to be a 10 minute time out. I have a request that's been running for about 40 minutes now and hasn't been terminated. I am ending that now as I think it answers the question and there is no need to keep it running.

**Comment by mrjones-plip** [comment]
Awesome sauce!! and this same request would have hit the node 2 min timeout before right? As long as it's an apples to apples test, sounds good to me!  However, I fully defer to @garethbowen  who's closer to the code than I'm on this one.

**Comment by garethbowen** [comment]
Perfect. Thanks @newtewt !
