### ISSUE TITLE
Partial load of contact add/edit forms on slow networks/devices

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7184]
**Describe the bug**
A contact add or edit form be displayed partially loaded instead of showing a spinner and then displaying loaded fully, when the device is slow or has a slow connection (for online users). 

**To Reproduce**
1. Load a 3.11.x + instance
2. Open a contact add or edit form  (which doesn't matter).
3. Throttle your network to Slow 3G. 
4. Refresh the page and see the partially loaded form, and then the fully loaded form.

**Expected behavior**
We should display a spinner until the form is fully loaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/124880738-4431a900-dfd7-11eb-8cbe-7b03f8668233.png)

**Environment**
- Browser: any
- App: webapp
- Version: 3.11 +

**Additional context**
This works as expected in 3.10.

**Comment by ngaruko** [comment]
LGTM
Tested on local but throttling network to slow -
on master:

https://user-images.githubusercontent.com/6979995/139785675-9a2a3182-0ae9-4a07-b5b1-e5646f5ac566.mov

on branch 

https://user-images.githubusercontent.com/6979995/139785725-ae61cb62-6a9f-46df-974e-31660160cb63.mov

-
Please feel free to merge @m5r
