### ISSUE TITLE
Changing an offline user's password during replication will block them in loading error loop

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7186]
**Describe the bug**
We have no recovery mechanism for non-recoverable errors in our bootstrap mechanism, we assume that all errors are recoverable and we never treat cases of users being logged out or their auth tokens getting invalidated. 

**To Reproduce**
1. Login as an offline user, on a fresh browser and start initial replication. Make sure there are some docs to download, because next step needs to happen while you are downloading docs.
2. In another browser, as an admin, change the user's password. You can even use the same password the user had before. CouchDb encription involves a random salt, so the session will be invalidated either way. 
3. Observe you get a loading error while the user is replicating. Clicking on it will just refresh the page and show the loading error again. We even have a 1 minute timer to refresh the page, hence the loop. 
4. If you manually go to the login page, it'll just bootstrap again because it doesn't actually request _session. It just checks that a cookie exists. 
Recovery requires wiping the cookies manually. 

**Expected behavior**
We should have a way to recover from a logout during bootstrap. 

**Logs**
```
GET http://127.0.0.1:6500/api/v1/users-info 401 (Unauthorized)
Error fetching users-info - ignoring {code: 401, error: "unauthorized"}
Fetch failed loading: GET "http://127.0.0.1:6500/api/v1/users-info".
GET http://127.0.0.1:6500/purging 401 (Unauthorized)
Error bootstrapping Error: Error fetching purge data: {"code":401,"error":"unauthorized"}
Fetch failed loading: GET "http://127.0.0.1:6500/purging".
```

**Video**
https://user-images.githubusercontent.com/35681649/125153742-8fc28f00-e15e-11eb-824f-e79e39ebe98b.mp4

**Environment**
- Browser: any
- App: webapp
- Version: 3.x 

**Additional context**
I think we should be checking _session more often. We should definitely be checking in the login script and also at the beginning of our bootstrapping, and handle 401s accordingly.

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7433)

**Comment by lorerod** [comment]
**Reproducible on Master:**
- Get the loading error while the user is replicating. Clicking on it will just refresh the page and show the loading error again.
- When manually going to the login page, the loading error persist.
https://user-images.githubusercontent.com/21312057/147360873-90a96197-1b42-4c82-9ca2-b3a0aad0fc9f.mov

**Fixed on branch:**
- Get the loading error while the user is replicating. Clicking on it will take me to the login page as expected.
https://user-images.githubusercontent.com/21312057/147361102-73671911-1dd5-41ad-b38b-80488b66cd15.mov

**Comment by latin-panda** [comment]
Thanks Lorena!
Fix is merged into main branch.
