### ISSUE TITLE
Can't re-select message thread after deselecting it

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7203]
**Describe the bug**
In mobile view, you can't select the same message thread twice in a row. Clicking on the previously selected item does nothing. Clicking on another thread works as expected. 
The URL also doesn't change when going back. 

**To Reproduce**
1. Switch your browser to mobile view, or use a phone - behavior should be the same.
2. Go to messages tab and select a conversation thread. 
3. Click on the "<" button in the header: 
4. When the list loads again, click to open the same thread. 
5. Observe that clicking the same thread does nothing. 

**Expected behavior**
The user should be routed to the selected thread.

**Logs**
No errors in the logs

**Environment**
- App: webapp
- Version: 3.11

**Additional context**
This appears to be a regression in 3.11 Angular migration, and is probably related to renaming the parameter for the messages route, and it not matching the navigation check for `id`.

**Comment by dianabarsan** [comment]
@latin-panda Can you please confirm if your Android back button change fixes this? 
Thanks.

**Comment by latin-panda** [comment]
Yes, this is fixed with the work done in this [PR](https://github.com/medic/cht-core/pull/7192)
I'll move this ticket to 3.13's AT.

**Comment by ngaruko** [comment]
LGTM 
- on the web (mobile version to be AT'd in #6698 )
https://user-images.githubusercontent.com/6979995/128309353-925ee45f-35b7-4eea-968c-d11208c2d964.mov

**Comment by latin-panda** [comment]
Merged to main branch.
