### ISSUE TITLE
Muting transition can conflict with itself

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7209]
**To Reproduce**
1. Enable muting and add a few muting forms. 
2. Login as an offline user and work offline. 
3. Perform multiple mute + unmute actions across multiple contacts (fe: mute a clinic, unmute a person in the clinic, mute the clinic again, unmute another person etc). 
4. Set yourself as online and sync. 
5. Watch Sentinel logs and notice conflicts on muting. 

**Expected behavior**
Muting shouldn't conflict when replaying offline muting histories. 

**Logs**
```
ERROR: transition muting errored on doc b07d9293-34fc-4306-9db4-567b91518100 seq undefined: {
  error: 'conflict',
  reason: 'Document update conflict.',
  status: 409,
  name: 'conflict',
  message: 'Document update conflict.',
  docId: 'efbdd4f6-ac41-4a08-ad00-c131feae9c49'
} 
```

**Environment**
- App: Sentinel
- Version: 3.12

**Additional context**
The actual result of muting should be correct, even with the conflicts. The conflicts are caused by cascading replays.

**Comment by dianabarsan** [comment]
Ready for AT on `7020-dont-remute`.

**Comment by ngaruko** [comment]
LGTM.
Tested on local as in description. 
No errors in sentinel 
![image](https://user-images.githubusercontent.com/6979995/129160091-276758e4-f951-421c-946e-dc9607bde55d.png)
