### ISSUE TITLE
Extend docker-compose.yml to allow for ports to be overridden to support developing for concurrent deployments

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7211]
App Services needs a way to use `docker-compose` to easily run multiple deployments with in a day.  As well, they may need to run two or three deployments simultaneously.  the current `docker-compose.yml` should be extended to:
* allow for external  ports on the host to easily be remapped on per deployment (aka per docker-compose override file)
* offer a prototype of how to override with at least two example files (eg deployment A and deployment B)
* in a private repo, we should publish docker compose documents for all of App Services deployments. This will avoid the issue of port conflicts with multiple deployments.  As well, it will standardize the ports that different folks use on the same team.

See [parent issue](https://github.com/medic/cht-core/issues/7061#issuecomment-832190318) for more info/context.

**Comment by newtewt** [comment]
This is related to the PRs we've been going back and forth on right?

**Comment by mrjones-plip** [comment]
Yup yup!  Both the [core PR](https://github.com/medic/cht-core/pull/7212) as well as the [docs PR.](https://github.com/medic/cht-docs/pull/532)  My thinking was that when the `cht-core` commit was merged to master, we'd do the same for the docs.

The part of this ticket that is "Ready for AT" is the `cht-core` part.

**Comment by newtewt** [comment]
Was able to test during the PR portion. I am able to start the normal config with `docker-compose up` and also run additional apps as described in the docs.

**Comment by mrjones-plip** [comment]
Thanks again @newtewt!
