### ISSUE TITLE
After search RHS is not getting cleared off.

### ISSUE THREAD

**Issue by meghna-khemka** [medic/cht-core#7223]
1. Login to Medic environment.
2. Click on 'People' tab
3. Search for Apollo Hospital .Select Apollo Hospital from the left and examine RHS get loaded
4. Clear the search field and populate 'ee'. Hit search again.
5. Examine Apollo Hospital is getting displayed on RHS.

**Expected behavior**
RHS should be cleared off when searching with 'ee'.

Supporting video attached

https://user-images.githubusercontent.com/84743933/127573109-c2bf61ec-dcf9-48ea-9261-2d865c2abfd4.mov

https://github.com/medic/cht-core/issues/4825 issue raised earlier.

**Comment by dianabarsan** [comment]
Ready for AT on `7223-clear-rhs-contacts-search`

**Comment by meghna-khemka** [comment]
Tested above issue and issue seems to working fine now.
Supporting doc:

https://user-images.githubusercontent.com/84743933/130104208-050a4443-7e59-4062-96e6-eeae19a531d1.mov

**Comment by dianabarsan** [comment]
Merged to `master`.
