### ISSUE TITLE
Simprints integration disabled

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-core#7241]
**Describe the bug**
Simprints integration was disabled (or I'm missing something), apparently when we did the migration to Angular 10. I tried to use it with a demo app and I cound't make it work, and after digging into the code, looks like it was disabled with the intention to enable it again once related code were also migrated to Angular 10, but we forgot to re-enable it again, or finish the migration of the widget.

**To Reproduce**
1. Install a Simprints app, eg. the [demo](https://github.com/medic/mocksimprints) app. To build the app locally, try the version in the branch from this [PR](https://github.com/medic/mocksimprints/pull/1).
2. Install the following [demo form](https://github.com/medic/cht-core/blob/master/demo-forms/simprints-demo.xml)  in a CHT instance from _App Management > App forms_.
3. Try to fill a form from the mobile app, installed in the same device where the Simprints demo app is installed. Go to _Reports > Submit report > Simprints Registration Demo_
4. See the message _"Simprints isn't available on this device. ..."_.

**Expected behavior**
The Simprints widget should be visible instead of the message above, and should allows to trigger the Simprints demo app.

**Additional context**
The widget is disabled with a hardcoded implementation of a class instead of use the simprints service.

Code that disable the widget: https://github.com/medic/cht-core/blob/6485177d7e71771165482e6dd725c7da791c6613/webapp/src/js/enketo/widgets/simprints.js#L32-L37

Code with the actual service class: [webapp/src/ts/services/simprints.service.ts](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/simprints.service.ts)

I think that just replacing the hardcoded implementation with the class in the Angular service should works.

CC @dianabarsan and @latin-panda that may know better how this work.

**Comment by dianabarsan** [comment]
It's very possible we forgot about it. There is no release test for it, and nobody actually uses the integration. 
We also have this to resolve: https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/integration-api.service.ts#L36

**Comment by garethbowen** [comment]
Closed - we've decided to remove the simprints integration until someone needs it.
