### ISSUE TITLE
WDIO node support is not inline with our requirements

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7259]
**Describe the issue**
Webdriver IO supports v12.16.1 as it is the latest LTS. We require min 8. This means that our tests are running in a version of node and may not catch an issue in the older version. 

**Describe the improvement you'd like**
Determine a way to run our app in a node version that meets our requirements. My first thought is to run horti in a docker container and install the versions of node required in that container. That way the tests will still execute in a more current node and our app runs in a node we require. 

**Describe alternatives you've considered**

**Comment by garethbowen** [comment]
Another option is to only run the tests on Node 12 and manually test Node 8 and 10. There's only one or two minor versions left before we can bump our minimum requirements so it's not worth spending a lot of time making this work well.

**Comment by garethbowen** [comment]
This is resolved now that we've bumped our Node version.
