### ISSUE TITLE
Add more granularity to startup telemetry

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7260]
**What feature do you want to improve?**
Currently, the granularity of startup telemetry is limited to: 
- `to_first_code_execution` - which tracks how long it took for the browser to parse application JS code
- `to_bootstrap` - which tracks how long it took to bootstrap
- `to_angular_bootstrap` - which tracks how long it took for Angular to load
- `boot_time` - all of the above, summed

**Describe the improvement you'd like**
I'm particularly interested into breaking down `to_bootstrap`. 
Currently, bootstrap executes the following operations: 
- initial replication, only if required
- purging, only if required
- meta db purging, every startup deletes 1000 old feedback docs (if they exist) 
However more operations could be added in the future. 

At the moment, we don't know how long these operations take and how frequent they are (purging frequency depends on configuration, but also requires the user to be online). 

**Describe alternatives you've considered**
Don't track additional telemetry metrics. 

**Additional context**
Projects report that startup times are long, and when analyzing telemetry data, there are large differences between the minimum startup time and the maximum startup time within one reporting period. However it's impossible to determine which operation is time consuming and whether it should be signaled differently for the user.

**Comment by latin-panda** [comment]
Ready for AT in: 
PR Core: https://github.com/medic/cht-core/pull/7364
PR Docs: https://github.com/medic/cht-docs/pull/560

**Comment by latin-panda** [comment]
Thanks Bede!
PRs merged to master.
