### ISSUE TITLE
Phone field invalid when editing a contact with a valid phone number

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7261]
**Describe the bug**
Phone field is highlighted as invalid when editing a contact with a valid phone number, because it already exists and can't save unless the phone field gets a new value. It should not highlight the field because the contact is the phone number owner.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new contact with a unique valid phone number.
2. Save contact.
3. Click edit contact and modify another field that is not phone number.
4. Click save and observe how the phone field is hight lighted as wrong.

**Expected behavior**
Should not high light the field as wrong if the phone is correct and the contact is the only one assigned to that phone.

**Screenshots**
<img width="1486" alt="Screen Shot 2021-08-18 at 4 32 26 pm" src="https://user-images.githubusercontent.com/66472237/129874785-6b61f7e3-c6dc-42e3-ab83-dfc74191e419.png">

**Environment**
- Instance: local (master) and https://gamma.dev.medicmobile.org/
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.11 - 3.12

**Comment by dianabarsan** [comment]
Ready for AT on `7261-edit-contacts-with-phones`.

**Comment by meghna-khemka** [comment]
Tested above mentioned issue and above issue seems to be working fine but I observed unconsistent behaviour while creating a person with a Phone Number. I do face above mentioned error while creating a new person (Not always but sometime).- Supporting doc attached- (last i.e. 4rth one )

https://user-images.githubusercontent.com/84743933/130477002-d956cb09-71ef-41d7-8d2f-9206a42ab716.mov


https://user-images.githubusercontent.com/84743933/130477016-673b3b9f-a336-4256-b6c5-ee1dca9ecbad.mov


https://user-images.githubusercontent.com/84743933/130477051-825aa906-af3c-4ed4-ad49-8214f7b1f811.mov


https://user-images.githubusercontent.com/84743933/130477070-814875ad-6da9-454b-86d5-65396206948f.mov

**Comment by dianabarsan** [comment]
@meghna-khemka 
The phone numbers are both validated, and also checked against other contacts - as two contacts should not have the same phone number. This was what caused the issue in the first place. 
In your last video, can you pls make sure you don't have another contact that already uses that phone number? 

If you don't, this seems to be another issue. Can you please share the logs from the browser console? Thanks.

**Comment by meghna-khemka** [comment]
Thanks @dianabarsan 
Yeah,It's working fine when we use different phone number's ,may be I was expecting different error message when 2 contact's have same Phone number but looks to be fine if we are displaying same error message.

Happy to pass as mentioned issue is working fine :)

**Comment by dianabarsan** [comment]
Thanks @meghna-khemka for the quick AT and feedback! 

Merged to `master`.
