### ISSUE TITLE
Investigate removing view queries from API startup code

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7297]
**Describe the performance issue**
Some of the API bootstrapping steps make view queries which means if there are a bunch of new changes then API blocks on startup waiting for view building to complete. In fact, the queries end up timing out which crashes API. While it does eventually complete the app is completely unavailable during this time which makes it difficult to work out what's going on. All requests get a 502 response because API is down.

**Describe the improvement you'd like**
Rewrite these bootstrap steps to use the magic [allDocs](https://pouchdb.com/api.html#batch_fetch) view if possible so that API startup doesn't block. As soon as requests come in the view rebuild will be triggered but API will be handling requests correctly. This is only possible if the docs needed all have a predictable ID prefix.

**Describe alternatives you've considered**
We could add view building as a separate step in the bootstrapping process so it's clear what's going on, but that would still mean all requests would get a 502 response.
We could implement something like a [status page](https://github.com/medic/cht-core/issues/2967) which could report on view warming progress so at least people would know what the issue is but it's better to remove the issue than to just notify about it.

**Environment**
- Instance: all
- Browser: N/A
- Client platform: N/A
- App: api
- Version: 3.6, but also detected on latest.

**Additional context**
This was detected in a call with LG where they split their db into two instances using replication.

Examples of the steps that need to be patched:

- https://github.com/medic/cht-core/blob/master/api/src/services/generate-xform.js where it queries existing forms
- https://github.com/medic/cht-core/blob/master/api/src/translations.js where it queries for translation docs
- https://github.com/medic/cht-core/blob/master/api/src/config.js where it queries for translation docs
- Anything else you can find...

**Comment by dianabarsan** [comment]
Related: https://github.com/medic/cht-core/issues/7964

**Comment by dianabarsan** [comment]
Closing via https://github.com/medic/cht-core/issues/7964
