### ISSUE TITLE
"field required" not shown when field is read_only,  required and has calculation

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7298]
**Describe the bug**
I have a form that has a field that is both `read_only` and `required` and **has a `calculation` value**.   When the required field is not filled out, it turns red as it's required, but it does not show the "This field is required" message.  Further, if you add a custom `required_message`, it does not use this either. The use case is, in the original discovery of the issue, when the field will be populated by a 3rd party integration (e.g. RD-Toolkit via app launcher [see docs PR](https://github.com/medic/cht-docs/pull/540)).

**To Reproduce**
1. make an app form with this contents (or use [attached sample form](https://github.com/medic/cht-core/files/7132068/test.zip)):

   type | name | label::en | required | required_message | read_only | relevant | calculation
   -- | -- | -- | -- | -- | -- | -- | --
   string | the_status | The Status | yes | None Shall Pass  | yes |   | null

1. Upload the form to a CHT instance and try and submit it, but leave the `Status` empty (which , you know, it's read only, you have no choice ; )

**Expected behavior**
The CHT turns the field background red and shows the error message: "None Shall Pass"

**Actual behavior**
The CHT turns the field background red and shows no error message. Further, it doesn't show the `required_message` if specified.

**Logs**
NA

**Screenshots**
Here's the field as `required` and `read_only`:

![required_read_only](https://user-images.githubusercontent.com/8253488/132592385-82386579-5b9c-465d-a8cc-7b043d51aa3d.png)

Here's the field `required` but NOT `read_only`. It's showing the desired behavior when the field is `read_only`:

![required](https://user-images.githubusercontent.com/8253488/132592440-d990ee12-6b55-4aba-9c0e-96e48fea6e6f.png)

**Environment**
- Instance: local dev instance
- Browser: All
- Client platform: All
- App: webapp
- Version: `3.12` master on  `6981-launching-external-apps` branch

**Additional context**
This came up working on the [COVID19 config](https://github.com/medic/cht-core/pull/7273)

Here's the field's HTML when  `required` and `read_only`:

```html
<label class="question non-select current invalid-required" role="page">
    <span class="question-label active" 
        data-itext-id="/test/the_status:label" lang="en">The Status</span>
    <input 
        type="text" name="/test/the_status" data-required="true()" data-calculate="null" data-type-xml="string" readonly="readonly">
</label>
```

Here's the field's HTML when `required` but NOT `read_only`. Note that there's an extra `<span/>` at the end with the missing required message.

```html
<label class="question non-select current invalid-required" role="page">
    <span class="question-label active" 
        data-itext-id="/test/the_status:label" lang="en">The Status</span>
    <span class="required">*</span>
    <input
        type="text" name="/test/the_status" data-required="true()" data-calculate="null" data-type-xml="string">
    <span class="or-required-msg active" lang="">None Shall Pass</span>
</label>
```

**Comment by jkuester** [comment]
@mrjones-plip I can confirm that this issue seems to have been resolved in newer versions of enketo-core.  I tried out a form on my [6345-enketo-uplift](https://github.com/medic/cht-core/tree/6345-enketo-uplift) branch with a field ("Test Field") that is a `read_only` `string` question with a `calculate` (that just pulls the value from "My String").  "The test field must be" is the custom `required_message` for Test Field and as you can see in the screenshot, if there is no value, then the expected required message is shown.  Let me know if I got something wrong in this test workflow here...

![image](https://user-images.githubusercontent.com/8441903/132710011-c7aca91c-da48-4829-abb3-6f56169deb74.png)

**Comment by jkuester** [comment]
I am going to add the `enketo` label to this issue so that we can remember to validate/close this issue when the enketo-core uplift is completed.

**Comment by mrjones-plip** [comment]
Awesome - thanks @jkuester !

**Comment by ngaruko** [comment]
Tested on local with the above form. Works: The CHT turns the field background red and shows the error message: "None Shall Pass"
![image](https://user-images.githubusercontent.com/6979995/149435202-9f0cb2fe-39ef-4d99-92e6-6354c71bf22b.png)
