### ISSUE TITLE
To keep track of all protractor to wdio migration test cases.

### ISSUE THREAD

**Issue by meghna-khemka** [medic/cht-core#7302]
Creating a master ticket for protractor to wdio migration test cases where we will push all the migrated PRs

# Protractor To Wdio Migration

|Test File	|Status	|Owner	|Pull Request Link	|Notes	|
|---	|---	|---	|---	|---	|
e2e/client-side-transitions/muting.js |   |   |   |  
e2e/contacts/add-new-district.spec.js | Done |   |   | Already covered in new-lineage-spec
e2e/contacts/add-new-health-center.spec.js | Done |   |   | Already covered in new-lineage-spec
e2e/contacts/add-new-person.spec.js | Done |   |   | Already covered in new-lineage-spec
e2e/forms/add-family-form.specs.js |   |   |   |  
e2e/forms/forms-against-muted-contacts.spec.js |   |   |   |  
e2e/forms/submit-default-delivery-form.specs.js |   |   |   |  
e2e/forms/submit-delivery-form.specs.js |   |   |   |  
e2e/forms/submit-photo-upload-form.spec.js |   |   |   |  
e2e/forms/submit-z-score-form.spec.js |   |   |   |  
e2e/login/db-sync-filter.spec.js |  Done  |   |   |  
e2e/login/privacy-policy.spec.js | In PR  | Nick   |   |  
e2e/login/purge.spec.js |   |   |   |  
e2e/login/token-login.spec.js |   |   |   |  
e2e/navigation/common.specs.js | Done |   |   |  
e2e/navigation/hamburger-menu.js | Done |   |   |  
e2e/release/cht-config/contact-create.specs.js |   |   |   |  
e2e/release/cht-config/contact-edit.specs.js |   |   |   |  
e2e/transitions/message_duplicates.spec.js | Done | Bede | https://github.com/medic/cht-core/pull/7316 | Does not need browser
e2e/transitions/public_form_transitions.spec.js | Done | Bede | https://github.com/medic/cht-core/pull/7316 | Does not need browser
e2e/transitions/sms_workflows.spec.js | Done | Bede | https://github.com/medic/cht-core/pull/7316 | Does not need browser
e2e/translations/incorrect-locale.spec.js |   |   |   |  
e2e/translations/new-language.spec.js |  in PR |   |   |  
e2e/africas-talking.js |   |   |   |  
e2e/bulk-delete.js |   |   |   |  
e2e/concatenate-xpath-strings.spec.js | Done  |   |   |  
e2e/contact-summary.js |   |   |   |  
e2e/create-meta-db.js |   |   |   |  
e2e/infodocs.js |   |   |   |  
e2e/rapidpro.spec.js |   |   |   |  
e2e/registration-by-sms.js |   |   |   |  
e2e/report-date-filter.js | in PR  |   |   |  
e2e/reports-subject.js |   |   |   |  
e2e/send-message.js |   |   |   |  
e2e/sms-gateway.js | in PR| Nick   |   |  
e2e/submit-enketo-form.js |Done  |   |   |  
e2e/target-aggregates.spec.js |   |   |   |  
e2e/cht/pregnancy.spec.js |   |   |   |  
mobile/common/common.specs.js |   |   |   |  
mobile/content-security-policy.specs.js |   |   |   |  
mobile/docs-by-replication-key-view.js |   |   |   |  
mobile/login/login.specs.js |   |   |   |  
mobile/medic-collect.specs.js |   |   |   |  
mobile/service-worker.specs.js | in progress | Diana  |  https://github.com/medic/cht-core/pull/7322 |

**Comment by dianabarsan** [comment]
I see this has not been updated in a while. @ngaruko is there another place to track progress on this? 
I ask because I was planning on migrating a protractor suite, because I wanted to add some extra tests and I wanted to make sure I "assign" that migration to myself. 

Thanks!

**Comment by ngaruko** [comment]
@dianabarsan This is not definitely up to date. I will update with at least those that I am working on. For the rest, any tests that have been migrated has been renamed to `*.wdio-spec.js`, so there shouldn't be any repeat work.

**Comment by garethbowen** [comment]
This is out of date and duplicated with #7723
