### ISSUE TITLE
Blank modal when navigating to app instance.

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7305]
**Describe the bug**
When navigating back to an instance for testing. There is a blank modal displayed. Clicking the modal then returns you to the log in page. 

**To Reproduce**
Steps to reproduce the behavior: I'm struggling to reproduce this reliably but I've seen it enough it warrants an issue. 

**Expected behavior**

**Logs**
If applicable, include the server or browser logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/10531066/132743752-c5601468-9527-4668-ac4b-892cb4707a0e.png)

**Environment**
- Instance: (eg: alpha.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, medic-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Next time someone sees this, please check the cookies and share them here. Thanks!

**Comment by dianabarsan** [comment]
Ok, this just happened to me when I opened an old browser session. I checked cookies:
- my session cookie was missing
- I had a userCtx cookie with an admin role
- language was set to "en"

**Comment by dianabarsan** [comment]
Related issue: https://github.com/medic/cht-core/issues/7187 where the empty modal is also reported.

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7433)

**Comment by ngaruko** [comment]
LGTM. Tested on local
**on master** ![image](https://user-images.githubusercontent.com/6979995/144785758-4f5fca8c-b93d-4552-93ba-0975bfcb0c66.png)
**on branch**
Straight to login page
![image](https://user-images.githubusercontent.com/6979995/144786564-c9803d70-c9ab-4ed9-86c8-264dbe3292e0.png)


**_NOTE: Needed to clear cache after updating._**

**Comment by latin-panda** [comment]
@ngaruko thanks! I'll merge this one once https://github.com/medic/cht-core/issues/7186 and https://github.com/medic/cht-core/issues/7187 are ATed :)

**Comment by latin-panda** [comment]
Fix is merged into main branch.
