### ISSUE TITLE
Config Versioning

### ISSUE THREAD

**Issue by ecsalomon** [medic/cht-core#7310]
For many analytics purposes, it is useful (or essential) to know what logic was active when a CHW took an action. For example, when forms change, the field schema may change or the correct way to calculate a metric may need to be updates. For tasks generated from predictive algorithms, it is important know what version of the rules.nools.js was used. 

It would be awesome to version components of a config  upon deployment and to record these somewhere. For example, form versions could be recorded in reports. Task logic could be versioned in task documents, perhaps?

**Comment by garethbowen** [comment]
Moved from cht-conf because the change was fixed here.
