### ISSUE TITLE
Scalable Architecture

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-core#7327]
[WA for scale](https://docs.google.com/presentation/d/1GPNtVQpHVmBqAsgMr-uHRLflp_r95K8mwCz1Sk0aWLA/edit#slide=id.p1)

[Notes with estimates](https://docs.google.com/document/d/1L_inDfj8jQyTf4o5WsLlm4cM2C4HmpuT/edit)

**Comment by garethbowen** [comment]
@craig-landry Can we close this as a dupe?
