### ISSUE TITLE
PWA on mobile logs out when browser is quit 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7343]
**Describe the bug**
When you're on Android and you're logged into a CHT instance in a browser (not the app) and the browser is quit, you get logged out of the CHT instance.

**To Reproduce**
1. Deploy a CHT 3.12.1 instance
2. Create an offline `chw` user
3. Log in with the `chw` user on Android in a browser
4. Quit the browser
5. Launch browser and go back to the CHT URL
6. Note you are prompted to log out

**Expected behavior**
You are still logged in

**Logs**
NA - but I can go back and provide them if needed!

**Screenshots**

https://user-images.githubusercontent.com/8253488/134718573-42b87bca-cfb4-4ca0-982f-556411f08fe8.mp4

**Environment**
- Instance: Local dev instance in `docker-compose` upgraded to 3.12.1
- Browser: Chrome 94.4606.50
- Client platform: Android
- App: webapp
- Version: 3.12.1

**Additional context**
Interestingly enough, trying with the online `medic` user, I still get logged out, but I get the blank modal problem, which we've documented over in #7305 - so maybe this is a dupe?  cc @dianabarsan  who was looking into this already.  I can reliably reproduce this with the steps above, but just swapping out for an online user!

![login modal error](https://user-images.githubusercontent.com/8253488/134720456-bbc1ac43-a21d-4085-b2ee-84092352d181.png)

**Comment by dianabarsan** [comment]
It looks like we are stripping all cookie params from the AuthSession cookie that CouchDB responds with, and only add `sameSite`, `secure` and `httpOnly` back, omitting an Expires or Max-Age. 
https://github.com/medic/cht-core/blob/c9712931eeffb530836abebd6da8c8870f53f635/api/src/services/cookie.js#L3
https://github.com/medic/cht-core/blob/c9712931eeffb530836abebd6da8c8870f53f635/api/src/services/cookie.js#L5-L10
https://github.com/medic/cht-core/blob/c9712931eeffb530836abebd6da8c8870f53f635/api/src/services/cookie.js#L27-L31
This makes the cookie have the `Session` expiration time in the browser, causing this behavior. 

By the looks of it, this has been the case since 2015.

**Comment by mrjones-plip** [comment]
Yikes! Nice sleuthing @dianabarsan - thank you!

@garethbowen  - FWI - per our recent  chat, seems like our PWA support is lacking and likely we don't have anyone using it on any recent versions of CHT :(

**Comment by dianabarsan** [comment]
I've been looking into how this is working in Android, where users don't get logged for 1 year, and ran some experiments. 

I checked out the `master` branch of `cht-android` and installed it on an Android 11 phone. 
I mapped the instance to `gamma.dev`. 
I logged in and checked the `AuthSession` cookie. It, indeed, has `Session` expiration time. 

Scenario 1: 
- start app and login
- immediately kill the app (Force Stop)
- open the app
 = > 
- I'm logged out

Scenario 2:
- start the app and login (if you're not already logged in)
- leave the app running for some time (1 minute???)
- kill the app (Force Stop)
- open the app
 => 
- I'm logged in 

Scenario 3: 
- start the app and login (if you're not already logged in)
- leave the app running for some time (1 minute???)
- logout from the hamburger menu
- immediately kill the app
- open the app
 => 
- I'm logged in 

Scenario 4:
- start the app and login (if you're not already logged in)
- logout from the hamburger menu
- let the app stay on login screen for a bit (1 minute?)
- login 
- immediately kill the app
- open the app
 => 
- I'm logged out


I've been able to replicate these scenarios multiple times.

I don't pretend to know how Android works, but to me it seems that some "state" is saved on a schedule, and the Activity (?) is pre-populated with this cached state, which preserves cookies with `Session` expiration time.

**Comment by dianabarsan** [comment]
I tried the above in WebView today and I'm seeing the same behavior.

**Comment by dianabarsan** [comment]
A related thread where session cookies are not removed when WebView session is terminated: https://coderedirect.com/questions/497616/lifecycle-of-a-session-cookie-in-an-android-webview-cookiesyncmanager

**Comment by mrjones-plip** [comment]
Awesome research - thanks @dianabarsan! I defer to what you and @garethbowen  thinks is best as far as fixing the the `AuthSession` cookie expiration.  

I'd lean toward a year if my understanding is correct that it would bring feature parity to the PWA and CHT Android UX. Lemme know if my understanding is wrong though!

**Comment by garethbowen** [comment]
> Do we add the 1 year expires to the AuthSession cookie and have everyone everywhere logged in for a year?

The `AuthSession` cookie expiry should match the session expiry which is configured in CouchDB.

> Do we only make the change for offline users and leave online users with a Session expiration time?

That's a neat idea - I think we should raise a separate issue for that.

**Comment by ngaruko** [comment]
Tested on local and mobile
- on master - session expires on quitting browser 

https://user-images.githubusercontent.com/6979995/139774629-364fa426-1c6d-4729-87c5-bcf659d4b80a.mov

- on branch - user still logged on after quitting browser and coming back https://user-images.githubusercontent.com/6979995/139774647-4ee683f1-2d58-4fc5-85e9-738418c46d7b.mov

- cookie in browser 
![image](https://user-images.githubusercontent.com/6979995/139774222-df395371-def1-42dc-a90d-c9b01209081c.png)

**Comment by dianabarsan** [comment]
Thanks for the AT @ngaruko . 
Is the last image taken on master or on branch? 
On branch I would expect the AuthSession cookie to **not** have an expiration time of Session.

**Comment by ngaruko** [comment]
This is what it looks like on the branch @dianabarsan . Is this not what's expected?
**Firefox**:
![image](https://user-images.githubusercontent.com/6979995/139957846-7a9a4c23-6b38-4c36-8ba0-f337ee8dd37e.png)
**Chrome:** 
![image](https://user-images.githubusercontent.com/6979995/139958016-37a16954-fce5-4834-ab94-b3ceb24f9207.png)

**Comment by dianabarsan** [comment]
Thanks a lot for clarifying @ngaruko . This is exactly what to expect. 

I was confused by by the last image you attached in the previous post: 
![image](https://user-images.githubusercontent.com/35681649/140003969-a4cebbc1-974a-428a-9c02-77b1bcc3217a.png)

which is what the behavior was before.

**Comment by dianabarsan** [comment]
Merged to `master`.
