### ISSUE TITLE
Partner logos don't show on the about page

### ISSUE THREAD

**Issue by jonathanbataire** [medic/cht-core#7353]
**Describe the bug**
Partner logos are not displayed on the "about" page

**To Reproduce**
1. Go to app management under images 
2. click on partners tab and upload a logo
3. Get back in the app under the about page on the hamburger menu 
4. The label `Supporting partners` shows but the uploaded icon doesn't

**Expected behavior**
Uploaded logos should show up on the about page

**Screenshots**
Uploaded icons
![screenshot_from_2021-09-30_15-47-44](https://user-images.githubusercontent.com/32832540/135463486-ff09aaa7-f133-4c1c-87d8-2fcf0618e247.png)

The About page
![screenshot_from_2021-09-30_15-48-04](https://user-images.githubusercontent.com/32832540/135463361-e5309739-ea27-4c6e-b284-021c5e7f58e2.png)

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: Webapp
- Version: 3.13.0

**Comment by dianabarsan** [comment]
This is ready for AT on `7353-fix-about-page-partners`

**Comment by ngaruko** [comment]
Looks good. Tested on local install by adding 2 partners on `/admin/#/images/partners` and checking the about page.
On `master`
![image](https://user-images.githubusercontent.com/6979995/135770383-6a7b2386-30f6-422a-bec5-1a6e33786bdc.png)

On the branch 
![image](https://user-images.githubusercontent.com/6979995/135770398-9c40daf8-1977-47b8-81db-3829ad3911ef.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
