### ISSUE TITLE
Problems upgrading google-libphonenumber from 3.2.22 to 3.2.23+

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7361]
**Describe the issue**
[Version 3.2.23 of google-libphonenumber](https://github.com/ruimarinho/google-libphonenumber/compare/v3.2.22...v3.2.23) introduced some change into the `isNumberMatch` logic that breaks the [describe isMessageFromGateway unit test](https://github.com/medic/cht-core/blob/0e4c653890ce020064f7f0a07fa83c89ae7d06cf/shared-libs/transitions/test/unit/messages.js#L384).  I do not know what exactly caused the behavior change.

The `['+774455558888', '77-44-5555-8888', true]` test case fails because `false` is returned from `isMessageFromGateway` and that is because the [`phone-number.same`](https://github.com/medic/cht-core/blob/2c1db1618bdafc5ec14c3a27aa4a37249fcc1b4a/shared-libs/phone-number/src/phone-number.js#L109) function does not consider the phone numbers as matching.  This is because the `PhoneNumberUtil.isNumberMatch` function returns `2` (`SHORT_NSN_MATCH`) for the given phone numbers instead of the expected `3` (`NSN_MATCH`).  

**Describe the improvement you'd like**

It seems like we need to consider if the new behavior is desired and if we should update the `phone-number.same` function to account for the functionality (or update the the test case to reflect the new output).

**Comment by garethbowen** [comment]
It's important to keep this library up to date otherwise phone numbers start failing erroneously. Scheduling for 3.14.0.

**Comment by garethbowen** [comment]
I think the library and code are fine, but the test was using an invalid number (too long) which probably shouldn't have been passing before. Possibly libphonenumber has become more strict? Regardless I think the fix is to switch the test to use a valid number.

**Comment by garethbowen** [comment]
Ready for AT on `7361-update-libphonenumber`. It's a little tricky to test but just ensure the phone number validation features still work as expected.

**Comment by ngaruko** [comment]
Tested a few combinations for phone validation and it works.
![image](https://user-images.githubusercontent.com/6979995/148706877-235d837a-6568-4461-b731-83084e004c8c.png)
![image](https://user-images.githubusercontent.com/6979995/148706902-4988d100-0824-436f-9910-97c8a18eea93.png)

**Comment by jkuester** [comment]
Merged
