### ISSUE TITLE
Webapp isn't a valid PWA

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7362]
**Describe the bug**
PWA validation fails which means users are not prompted to save the app to the desktop.

**To Reproduce**
1. Log in as an offline user in Chrome
2. Open Dev Tools > Lighthouse
3. Select "Progressive Web App" checkbox
4. Click "Generate report"

**Expected behavior**
Report should be checked. Also make sure that you can add it to desktop or home screen and it appears like a regular app.

**Logs**
Failure reason:

- Manifest does not contain a 'name' or 'short_name' field
- Manifest does not contain a suitable icon - PNG, SVG or WebP format of at least 144 px is required, the sizes attribute must be set, and the purpose attribute, if set, must include "any".
- No supplied icon is at least 144 px square in PNG, SVG or WebP format, with the purpose attribute unset or set to "any"

**Environment**
- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.13.0

**Additional context**
There are a few other things to fix at the same time...

- The login page doesn't return the manifest so you can't add to desktop until logging in
- The icon and name should come from the configured branding and not be hard coded
- Check whether it should be cached, for example, in the service worker

**Comment by m5r** [comment]
Adding to this, I was recently reading ["What does it take to be installable?"](https://web.dev/install-criteria/#criteria) from Google

**Comment by garethbowen** [comment]
Ready for AT on `7362-fix-pwa-compliance`

Steps for AT:

The idea behind a Progressive Web App is that you can "install" a website on your device and it'll look basically the same as an installed app from the Play Store. For the browser to allow installation you need to provide certain information, for example, the name and icon that should be displayed on the desktop link. This change endeavours to check all the requirements to make this installation method possible.

1. One of the requirements is to have a secure connection so to test this branch you'll need to install it using an SSL proxy or a proper AWS server.
2. This is principally designed for installation on phone. It'll work with Chrome or Firefox though the installation instructions may be slightly different - I'll use Chrome for this demo.
3. Open Chrome on Android
4. Type in the URL of the site
5. Log in
6. Wait for everything to load
7. Click the three dots icon in the top right
8. Click "add to home screen"
9. Close Chrome and make sure the icon has appeared on the home screen
10. When you click the icon the app should load and work as expected except it won't have the URL bar and other browser elements - it'll look basically like an actual installed Play Store app.
11. Try changing the branding as per [the documentation](https://github.com/medic/cht-docs/pull/645), completely wipe the app, and try it again and make sure the new title and icon are used instead of the default ones.

Let me know if you have trouble getting this to work!

**Comment by lorerod** [comment]
@garethbowen can you confirm please that the behavior mentioned in the **observation** is expected? Thanks!

**Comment by garethbowen** [comment]
@lorerod It's not expected. Unfortunately I can't reproduce it on linux or windows and I don't have access to a mac. I suspect it's a bug in the Chrome for mac implementation. If it's not too much trouble can you open up the dev console (F12?) and then try to reproduce it? You might see an error message in the console, or some failed request in the network tab which will help me track this down.

**Comment by lorerod** [comment]
@garethbowen Unfortunately, I don't see any error written to the console. Just the following message:
`[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"password" name=​"password" type=​"password">​`
But this message is written when the login page loads correctly too.
The behavior only occurs when I install the application and log out for the first time. If I close the application and open it again, it does not happen again.

https://user-images.githubusercontent.com/21312057/158377787-a2013c01-b3fe-4544-a125-230b45c47db8.mov

I also noticed from the cursor icon changes that the text and button elements of the login screen are present, but not showing. I completed the fields without seeing them and clicked on the button, and its login was successful.

https://user-images.githubusercontent.com/21312057/158377938-7bf5b776-e6ea-49fa-93a4-ef8ee41a2657.mov

Please let me know what else I can do to help you to track this down.

**Comment by lorerod** [comment]
Yes, @garethbowen, I agree. I will move this issue to Ready to merge and create the new one.
Thanks.

**Comment by garethbowen** [comment]
Merged.
