### ISSUE TITLE
Crash in Tasks/Targets system not creating feedback documents

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#7363]
**Describe the bug**
Production instance was encountering the error "Error fetch tasks" for multiple users.

I'm attempting to use feedback documents to understand when this issue occurred and how many users were impacted.
https://github.com/medic/config-moh-kenya-app/issues/75

**To Reproduce**
Query postgres for feedback documents in the range that the incident occurred

```
select * from useview_feedback
where period_start > '2021-08-27T0' and period_start < '2021-08-30T0'
```

**Expected behavior**
We have observed this crash for multiple users in this date range. But there are no feedback documents indicating the crash has occurred.

**Environment**
- Instance: https://safaridoctors-ke.app.medicmobile.org/#/about
- App: safari-doctors
- Version: 3.10.0

**Comment by kennsippell** [comment]
Ready for AT on `7363-rules-feedback`

To test upload invalid "stuff" within `app_settings.json` "tasks.rules". Upload to CHT and load page. You should see "error loading tasks" on tasks tab.  Look at feedback documents and you should see one with "Failed to initialize RulesEngineService"

**Comment by garethbowen** [comment]
@kennsippell With 4.2.x branched I think you can go ahead and merge this.

**Comment by kennsippell** [comment]
There is [this pending PR feedback](https://github.com/medic/cht-core/pull/8164#issuecomment-1503172574) which I'm struggling to find time to address. Hoping to get there in the next few weeks.

**Comment by garethbowen** [comment]
Merged!
