### ISSUE TITLE
Support for Node 16

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#7368]
**Describe the issue**
Some [dependencies](https://github.com/medic/cht-core/runs/3810444057) fail to install with Node 16, with `npm ci`
**Describe the improvement you'd like**
Fix dependencies
**Describe alternatives you've considered**
n/a - v16 Not supported yet, just a heads-up!

[2021-10-06T03_52_51_211Z-debug.log](https://github.com/medic/cht-core/files/7306826/2021-10-06T03_52_51_211Z-debug.log)

**Comment by garethbowen** [comment]
This is fixed in `master` ready for 4.0.0
