### ISSUE TITLE
Update mocha to latest

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7372]
**Describe the issue**
Upgrading from our current version of mocha (`7.2.0`) to `8.0.0` or anything higher causes the webapp unit tests to fail with an error similar to what is described here https://github.com/mochajs/mocha/issues/4660 and here https://github.com/angular/angular/issues/42834. It seems like there is some bad interaction between mocha and karma.

```
RangeError: Maximum call stack size exceeded
```

**Describe the improvement you'd like**
It will probably be worth revisiting this issue after #7083 has been addressed and we have a new version of Angular (however, the issues linked above indicate that the issue still persists with Angular 12, to this is unlikely to be the fix).

**Describe alternatives you've considered**
I tried several versions of mocha (`8.0.0`, `8.4.0`. `9.1.2`) and they all failed for the same issue.

**Comment by garethbowen** [comment]
It looks like this was updated to `^9.2.2` as part of 4.0.0. Maybe upgrading node fixed it?
