### ISSUE TITLE
Display tab's label in small screens

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7409]
**What feature do you want to improve?**
Display tab's labels in small screens. This helps users to understand better what are the tabs for. 

**Additional context**
Currently partners do a work around to change the responsive settings to display the labels:

- Settings> about phone> software information> tab on builder number 7 times to enable developers options
- After developers options have been enabled; go to settings> developers options> change smallest width/minimum width to 411
- Close the app and reopen the app

**Comment by latin-panda** [comment]
There was a job done to display the labels when there's only 3 tabs: https://github.com/medic/cht-core/issues/5804

**Comment by latin-panda** [comment]
Hi @n-orlowski is it okay to always display the tabs' label regardless of the device size? 
If it's okay, then I will remove the logic about [displaying the label only when there are 3 tabs or less](#5804)

Considering a device with width < 400px:
1. Font size = 0.8125rem (aprox 13px)
<img width="400" alt="Screen Shot 2021-11-10 at 4 32 12 pm" src="https://user-images.githubusercontent.com/66472237/141089699-c8974675-062d-4637-ba8e-1365b676d5ce.png">

2. Font size = 0.625rem (aprox 10px)
<img width="400" alt="Screen Shot 2021-11-10 at 4 33 08 pm" src="https://user-images.githubusercontent.com/66472237/141089911-efe9e454-5253-4e8d-b074-e96f5f8668f5.png">

**Comment by n-orlowski** [comment]
Hi @latin-panda , yes it's best practice to always have labels however you're right about them being too large in the first screenshot.. I think making the text smaller in the second screenshot on makes sense, but only if there are 5 tabs. For example,  if there are 4 tabs at that same screen size it should still default to 13px. We've heard CHWs often have bad eyesight and enlarge the text themselves :) Is this possible?

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7411)

**Comment by ngaruko** [comment]
LGTM.
`font-size: .625rem;` with 5 tabs
![image](https://user-images.githubusercontent.com/6979995/142963904-fb5122f3-fcb4-4735-8de0-4a697f5b3a99.png)

    `font-size: .8125rem; ` with 4 tabs
![image](https://user-images.githubusercontent.com/6979995/142964519-f4b40f91-432e-43f3-8fd2-0eedc2e48ff0.png)

**Comment by latin-panda** [comment]
Thanks Bede, work is merged into main branch.
