### ISSUE TITLE
Stopping and resuming initial replication could start local purging 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7419]
**Describe the bug**
The way that we determine whether initial replication is needed is by checking whether the `settings` document and the `_design/medic-client` document exist on the device. If both of these docs exist in the local PouchDb database, we consider initial replication as _not needed_ and we start business as usual, including purging. 

After all startup steps are completed and the Angular app boots, replication will continue in the background, and while that is happening, the user has just partial access to their docs - which could cause generating tasks unnecessarily when reports that complete those tasks are not yet replicated. Will add another issue to cover improving how we detect if we should do initial replication or not. 

**To Reproduce**
1. Setup your CHT installation. Version must be 3.7+. Configure server-side purging. 
2. Create your user and upload all of their documents (make sure you have at least a couple of thousand, also make sure some of them should be purged). DO NOT update settings AFTER pushing user documents. 
3. Run purging on the server. 
4. Log in as this user. 
5. Immediately after you see the "Fetching...." counter goes over a couple of 100, refresh the page. 
6. See "Cleaned 0" for a while. (purging is running)
7. App boots - you don't have all of your documents so you may see errors, but this is beyond the scope of this issue. 

**Expected behavior**
Purging shouldn't run if the device has not been setup completely yet. 

**Logs**
No errors. 

**Environment**
- Instance: production
- Browser: any
- Client platform: any
- App: webapp
- Version: 3.7+

**Additional context**
We create a purging checkpoint _after_ initial replication is completed. If initial replication is interrupted, we don't create this checkpoint. 
The easy fix for this would be to create the purging checkpoint _before_ initial replication, which would ensure that purging is up to date in the event of an interruption. 
This was brought forward after one partner did a hierarchy change, and when doing the resync, many of their devices started purging instead of doing initial replication (purging from 0 is very time consuming if the user has many _total_ documents and the server is under load).
One workaround would be to push a _rev for the `settings` document, insuring that it's close to the end of the changes feed and not available early on the device.

**Comment by dianabarsan** [comment]
cc @Fatoufall

**Comment by Fatoufall** [comment]
To note that this step takes at least 12h to finish and this is why for 2 days the configuration of 18 phones is not done yet. 
Would be great to implement this workaround to speed up this phase knowing that this is just the first area and the internet is not stable in Mali cc @Marina-Kenf @binokaryg 
![Muso_1711](https://user-images.githubusercontent.com/35699783/142455966-bc71f26b-3a64-416a-8ae5-67fc785af8fa.jpeg)

**Comment by dianabarsan** [comment]
This is ready for AT on `7419-early-purging-checkpointer`.

**Comment by ngaruko** [comment]
LGTM.
On refreshing the page during `fetching ...`, the app restarted `fetching` without local purging...
before refresh:
![image](https://user-images.githubusercontent.com/6979995/144536440-9e98ec3a-d8ba-4331-b34b-af1445a8a93a.png)

straight after refresh:
![image](https://user-images.githubusercontent.com/6979995/144536466-9c3a8aae-b633-4688-bf5e-3a4cb3c431ea.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
