### ISSUE TITLE
Remove simprints code

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7421]
**Describe the issue**
The simprints integration doesn't work and isn't being used or requested.

**Describe the improvement you'd like**
Remove the code which is unnecessary bloat.

**Describe alternatives you've considered**
Fixing it and supporting it, but we can add it back when someone wants it.

**Comment by njogz** [comment]
@garethbowen this was done by @latin-panda in this [PR](https://github.com/medic/cht-core/pull/7461)

**Comment by garethbowen** [comment]
@latin-panda This work was scheduled for 4.0.0 so that the breaking change could be communicated with the major version. Now that it's merged it will be released in 3.15.0. Do you think we could revert this change and then merge it once 3.15.0 has branched off main?

**Comment by latin-panda** [comment]
@garethbowen CHT-Android v1.0.0 is going to be released before 4.0.0, is that okay? The app break before core

**Comment by garethbowen** [comment]
cht-android 1.0.0 must support cht-core 3.x. It's ok if simprints doesn't work with cht-android 1.0.0 and cht-core 3.x but we should make sure it doesn't throw errors or otherwise disrupt the user. What would happen if the simprints code is still in cht-core but _not_ in cht-android?

Looking at [the code](https://github.com/medic/cht-core/pull/7461/files#diff-4a886c28eb47ecc7e78ebc1d09ab1e4b7b391b21212e1e31e8cd7b038edbb73eL38) it looks like it'll gracefully handle it. So that means if someone upgrades to cht-android 1.0.0 it'll gracefully stop working.

**Comment by garethbowen** [comment]
Merged for 4.0.0 release. AT was recorded in the [cht-android issue](https://github.com/medic/cht-android/issues/230#issuecomment-1010537797).
