### ISSUE TITLE
Schedules don't have a default value for `start_from`

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7425]
**Describe the bug**
According [to our documentation](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/schedules/#app_settingsjson-schedules), schedules should have a default value for `start_from`. This is not the case. 

**To Reproduce**
1. Update your config to create a schedule (make sure the translation key exists). 
```
"schedules": [
      {
        "name": "ANC Visit Reminders",
        "messages": [
          {
            "translation_key": "messages.schedule.registration.followup_anc",
            "group": 1,
            "offset": "1 hour",
            "recipient": "parent"
          }
        ]
      }
]
```
```
"registrations": [
    {
        "form": "pregnancy",
        "events": [
          {
            "name": "on_create",
            "trigger": "assign_schedule",
            "params": "ANC Visit Reminders"
          }
        ]
      }
]
```
```
"transitions": {
    "registration": true,
}
```
2. Submit a pregnancy report and wait for Sentinel to apply all transitions. 
3. Notice you don't see any scheduled message for the report. 

**Expected behavior**
A scheduled message should be generated for the report. 
If you update your schedule config like: 
```
"schedules": [
      {
        "name": "ANC Visit Reminders",
        "start_from": "reported_date",
        "messages": [
          {
            "translation_key": "messages.schedule.registration.followup_anc",
            "group": 1,
            "offset": "1 hour",
            "recipient": "parent"
          }
        ]
      }
]
```
and submit a new pregnancy, it should have a scheduled message. 

**Environment**
- App: api, sentinel
- Version: I went back to 2017, and afaict we never actually assigned a default value to `start_from`. 

**Additional context**
It makes sense that `start_from` should have the default value of the reported date of the triggering report, as the documentation says.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `master`

Using the steps from the description of the ticket, the _scheduled message_ was not present until the value for the property `start_from` was set.

<details>
<summary>Images: property "start_from" was not set, the scheduled message was not present in the pregnancy report.</summary>

![image](https://user-images.githubusercontent.com/94494491/210278383-b6bbc588-e59d-46a0-a987-214d30b63f9d.png)
![image](https://user-images.githubusercontent.com/94494491/210278241-b05241f5-516c-4ff7-aafa-69b3fb13fd40.png)

</details>

<details>
<summary>Images: property "start_from" was set with the value "reported_date", the scheduled message was present in the pregnancy report.</summary>

![image](https://user-images.githubusercontent.com/94494491/210278321-7ac1f8b9-f8b6-40d9-8395-86da36571a3c.png)
![image](https://user-images.githubusercontent.com/94494491/210278261-0d6f1ab7-cbdb-461f-9c6b-a6b7dd1eea18.png)

</details>


### Fixed on `7425-start-from-default-value`

Using the steps from the description of the ticket, when a schedule was created the _scheduled message_ was generated in the report, even if the property `start_from` was not set, the value was set as default in the code.

<details>
<summary>Image attached</summary>

![image](https://user-images.githubusercontent.com/94494491/210279142-307b3083-3658-45d7-b65c-b0bceec864c2.png)
![image](https://user-images.githubusercontent.com/94494491/210278962-359d8890-c6f1-4f83-955a-914c2cad1f9b.png)

</details>

---

Test passed successfully. :tada:

**Comment by latin-panda** [comment]
@dianabarsan @samuelimoisili  should this ticket have milestone 4.2.0 assigned?
