### ISSUE TITLE
Number of downloaded documents shown more than maximum documents while fetching

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#7431]
While loading an application as an offline user, when CHT fetches documents, It's showing more documents being pulled than that of maximum documents available. 
Please look at the image below: 

![image](https://user-images.githubusercontent.com/6102813/143492252-d812c0a6-26af-497d-b44d-2704961df1ad.png)

**Comment by garethbowen** [comment]
@dianabarsan Is this fixed with the new initial replication algorithm?

**Comment by dianabarsan** [comment]
I believe so.

**Comment by garethbowen** [comment]
Ok. Closing as fixed in 4.2.0 as part of #8134 

Please reopen if it happens again!
