### ISSUE TITLE
Users can view reports in contacts detail page despite lacking permissions

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7438]
**Describe the bug**
We control showing reports on contact detail pages using `can_view_reports` permission. 
As of 3.11, lacking this permission does not hide reports on contact detail pages. 

**To Reproduce**
1. Create a user with an offline role. Make sure their role has `can_view_reports` permission. 
2. Create reports and make sure they are visible on the contact detail page. 
3. Remove `can_view_reports` permission from the user's role. Sync. 
4. Load the same contact page and observe reports are still visible. 

**Expected behavior**
Permissions should be respected.

**Logs**
No logs.

**Environment**

- App: webapp
- Version: 3.11

**Comment by dianabarsan** [comment]
This is ready for AT on `7438-contact-details-permissions`.

**Comment by lorerod** [comment]
**Reproducible on Master**
Contact detail page when role has can_view_reports permission:
<img width="977" alt="can_view_reports on (master)" src="https://user-images.githubusercontent.com/21312057/147270558-b0ec7352-045b-4676-9235-5038047f5c44.png">

Contact detail page when role doesn't have can_view_reports permission:
<img width="957" alt="can_view_reports off (master)" src="https://user-images.githubusercontent.com/21312057/147270628-1657593c-2a51-48a9-8c73-969b8c4f66f9.png">

**Fixed on branch:**
Contact detail page when role has can_view_reports permission:
<img width="931" alt="can_view_reports on (branch)" src="https://user-images.githubusercontent.com/21312057/147270697-9781c648-9237-4c96-9a42-526a2b4188c9.png">

Contact detail page when role doesn't have can_view_reports permission:
<img width="976" alt="can_view_reports off (branch)" src="https://user-images.githubusercontent.com/21312057/147270766-6d298633-6aa7-4628-9f1f-020c43e9179e.png">

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by kitsao** [comment]
Hello @dianabarsan, was this ported to `3.13.x`, `3.12.x` and `3.11.x` or available in `3.14.x` only?

**Comment by dianabarsan** [comment]
Hi @kitsao 
This is just in 3.14

**Comment by kitsao** [comment]
Thanks @dianabarsan. For a partner looking forward to upgrading to fix several issues, this being one of them and given that they have thoroughly tested `3.13`, would the version be considered for porting since it is still supported and how long would it take? Or is it recommended to wait for `3.14` release, tentatively in mid February?
