### ISSUE TITLE
DHIS2 import reports a conflict 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7447]
**Describe the bug**
Integration with DHIS2 is described here: https://docs.communityhealthtoolkit.org/apps/guides/integrations/dhis2-aggregate/#user-experience and it requires exporting data from cht-core and importing this data into dhis2. 
DHIS2 import has warnings in latest versions because of the json schema. 

**To Reproduce**
1. Follow instructions and setup the integration with dhis2. 
2. Export dhis2 data from the admin app, either for all orgunits, or just for one.
3. Try to import the resulting file into dhis2, either by using the endpoint or the api.
4. Import results in a conflict: 
```
{"responseType":"ImportSummary","status":"WARNING","importOptions":{"idSchemes":{},"dryRun":false,"async":false,"importStrategy":"CREATE_AND_UPDATE","mergeMode":"REPLACE","reportMode":"FULL","skipExistingCheck":false,"sharing":false,"skipNotifications":false,"skipAudit":false,"datasetAllowsPeriods":false,"strictPeriods":false,"strictDataElements":false,"strictCategoryOptionCombos":false,"strictAttributeOptionCombos":false,"strictOrganisationUnits":false,"requireCategoryOptionCombo":false,"requireAttributeOptionCombo":false,"skipPatternValidation":false,"ignoreEmptyCollection":false,"force":false,"firstRowIsHeader":true,"skipLastUpdated":false,"mergeDataValues":false,"skipCache":false},"description":"Import process completed successfully","importCount":{"imported":0,"updated":0,"ignored":0,"deleted":0},"conflicts":[{"object":"OrganisationUnit","value":"Must be provided to complete data set"}]}
```

**Expected behavior**
Import should work without conflicts. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/146188756-1fde0d5f-ba50-4e94-9fef-7c4b68197e96.png)

**Environment**
- Instance: any
- App: api
- Version: any

**Additional context**
Our export schema looks like: 
```
{
  "dataSet":"set1",
  "completeDate":"2021-12-15",
  "period":"202111",
  "dataValues": [
    {"dataElement":"element1","orgUnit":"A","value":0},
    {"dataElement":"element1","orgUnit":"B","value":0}
  ]
}
```

removing the `completeDate` seems to fix the issue. 

Ideally, we should make sure that: 
1. We respect the supported schema as much as possible
2. Import happens without warning, which might be very confusing for users. 

**Why Now?**
Partner(s): Guava Pineapple
Reason(s): Blocked by it for major release or expansion

**Comment by jdndiaye** [comment]
Thanks a lot for that @dianabarsan 
can we prevent the export of completeDate?

**Comment by dianabarsan** [comment]
I think we should follow the indicated schema as much as possible. 

For bulk imports, instructions are to omit `dataSet` and `completeDate`. The value for `completeDate` we export is the current date when the export is executed, I'm not sure how that's used internally by DHIS2 or why it should be omitted when data is imported in bulk.

**Comment by mrjones-plip** [comment]
@dianabarsan - If this ticket doesn't make it into 3.14, should it be moved into 3.15 to ensure good DHIS2 support along with #6797? We're hoping to make 3.15 as small a release as possible, but still have key features partners are wanting (like DHIS2), so smaller bug fixes would be delayed after 3.15.

**Comment by dianabarsan** [comment]
#6797 is arguably much more consistent than this work. If DHIS is considered for 3.15, this should definitely make it too.

**Comment by mrjones-plip** [comment]
> If DHIS2 is considered for 3.15, this should definitely make it too.

Perfect - thanks!

**Comment by garethbowen** [comment]
As far as I'm aware nobody is using this feature. If it's not a quick fix then it makes sense to re-evaluate the priority here.
