### ISSUE TITLE
Release notes in GH all 404

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7458]
**Describe the issue**
When you're on the [GH based release list](https://github.com/medic/cht-core/releases), clicking any of the "Release notes" links is now 404.

This broke when we release #7413 which moved all the release notes from CHT Core repo -> docs.

**Describe the improvement you'd like**
These links need to be changed to go to the [new home on docs](https://docs.communityhealthtoolkit.org/core/releases/). For example the latest [3.13.0 release](https://github.com/medic/cht-core/releases/tag/3.13.0) goes to [this 404 page](https://github.com/medic/cht-core/blob/master/release-notes/docs/3.13.0.md).  Instead it should go to [the deep link in docs](https://docs.communityhealthtoolkit.org/core/releases/3.13.0/).

**Describe alternatives you've considered**
NA

**Comment by craig-landry** [comment]
I went and manually fixed up release back through 3.0.0. Prior to that the notes are just on the release item in GH anyway, so no updated required.
