### ISSUE TITLE
Incorrect place filter label when selecting only one place

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7463]
**Describe the bug**
When using the report facility filter and selecting a single place to filter by, the place's name should be displayed as the filter header. However `[obect Promise]` appears instead. 

**To Reproduce**
1. Go to reports tab, open the facility filter dropdown and select just one place. 
2. Notice that `[obect Promise]` appears as the filter header.
3. Selecting another place displays the correct filter header (`2 places`). 

**Expected behavior**
When using the report facility filter and selecting a single place to filter by, the place's name should be displayed as the filter header. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/148912070-6c2fcbde-4a1f-4507-87a5-d5d630d91e1d.png)

**Environment**
- App: webapp
- Version: 3.12+ (caused by https://github.com/medic/cht-core/issues/7137)

**Comment by dianabarsan** [comment]
Ready for AT on `7463-report-filter-label`.

**Comment by lorerod** [comment]
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

**Reproducible on Master**
When using the report facility filter and selecting a single place to filter by, the place's name is not displayed as the filter header. Instead `[obect Promise]` appears:
<img width="503" alt="master" src="https://user-images.githubusercontent.com/21312057/151043392-c89cb5cb-3ae2-4722-b3e8-1aef80166eb0.png">

**Fixed on branch**
When using the report facility filter and selecting a single place to filter by, the place's name is displayed as the filter header:
<img width="497" alt="branch" src="https://user-images.githubusercontent.com/21312057/151043497-0170009e-23a5-4904-aa2f-b48ff2fd4f4e.png">

**Comment by dianabarsan** [comment]
Merged to `master`.
