### ISSUE TITLE
Webapp report filters are not applied to export

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7464]
**Describe the bug**
With older versions of CHT (tested on 3.10.2), it was possible to only download the reports that are being displayed in the reports tab after applying some filter.
This is not working in the newer versions of CHT (tested: 3.11.0, 3.13.0).

**To Reproduce**
1. As an admin user, go to the Reports tab
2. Apply filters so that only a few reports are shown
3. Click on Export
4. Open the downloaded file

**Expected behavior**
Only the filtered reports are exported

**Environment**
- App: webapp
- Version: 3.11+

**Why Now?**
Partner(s): Internal
Reason(s): A partner will have CHWs/Supervisors with a detrimental experience, thus providing bad care

**Comment by dianabarsan** [comment]
This is ready for AT on `7464-export-with-filters`.

**Comment by tatilepizs** [comment]
**Config**: Default
**Environment**: Local with docker helper script
**Platform**: WebApp
**Browser**: Chrome

**Test scenario:**
There are six reportes created, the filter is _Postnatal danger sign follow-up_, there is only two reports from that type.

**Reproducible on Master**
The download file shows the six reports

![image](https://user-images.githubusercontent.com/94494491/151208026-47688445-e69e-4725-8c63-2c8fccc15f6e.png)

**Fixed on 7464-export-with-filters**
The download file shows only the two reports from the filter.

![image](https://user-images.githubusercontent.com/94494491/151208201-0b318678-2339-4f8d-8c58-3d56c0f9c6ee.png)

**Comment by dianabarsan** [comment]
Merged to `master`.
