### ISSUE TITLE
Default config flaky CI tests

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7471]
**Describe the issue**
Example run: https://github.com/medic/cht-core/runs/4789374194?check_suite_focus=true

![image](https://user-images.githubusercontent.com/35681649/149145912-9c49e86b-480a-4dd4-88c6-85dd7292cb29.png)
![image](https://user-images.githubusercontent.com/35681649/149146054-dca66a09-4155-4ecb-b9dc-5ff4946dfa67.png)

**Describe the improvement you'd like**
Look into the test and stabilize it. If it turns out that the problem is in the config, and not the test, I think a separate issue should be raised to fix the config. 

**Describe alternatives you've considered**
None.

**Comment by tatilepizs** [comment]
Closing it because it was created more than two years ago, and the example run link is no longer valid.
