### ISSUE TITLE
Correct typo in rapidpro endpoint path

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7472]
**What feature do you want to improve?**
There's a typo in the rapidpro endpoint path: "radpid" instead of "rapid" (but is consistent with documentation).
https://github.com/medic/cht-core/blob/master/api/src/routing.js#L370

**Describe the improvement you'd like**
Fix the typo. For backwards compatibility we'd still need to keep the old URL (use deprecation middleware for the old endpoint). 

**Describe alternatives you've considered**
Don't fix it. 

**Additional context**
Issue signaled on the forum.

**Comment by garethbowen** [comment]
Ready for AT in https://github.com/medic/cht-core/pull/7906

Documentation here: https://github.com/medic/cht-docs/pull/839

We now have two versions of the endpoint: `/api/v1/sms/radpidpro/incoming-messages` and `/api/v2/sms/rapidpro/incoming-messages`. Ensure both work the same as each other, and the same as the `master`.

**Comment by garethbowen** [comment]
@ngaruko My guess from the error message is that you changed the secret which has corrupted the rapid pro credentials. When you change your secret you have to reset the credentials using [this API](https://docs.communityhealthtoolkit.org/apps/reference/api/#put-apiv1credentials). Can you try that and see if that fixes the issue?

If that _does_ fix the issue, then I'll raise an issue to make that error message easier to understand!

**Comment by garethbowen** [comment]
Merged.
