### ISSUE TITLE
Update release (patch and minor) issue templates to reflect release notes location

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7475]
**Describe the issue**
One of the steps in the [patch](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_patch.md) and [major](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_major.md) release issue templates is a step for adding release notes to the CHT-core release notes directory. However, the release notes have been moved to cht-docs and removed from cht-core (via https://github.com/medic/cht-core/commit/61664b8544c1cc02ce32db7270d490f96cc89f7c). 

**Describe the improvement you'd like**
Update the releasing issue templates to provide up to date instructions about where to store release notes. 

**Describe alternatives you've considered**
None.

**Comment by garethbowen** [comment]
Done in this [PR](https://github.com/medic/cht-core/pull/7498) and merged.
