### ISSUE TITLE
Logging out of the app as an offline user while offline takes you to a "No Internet" page

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7497]
**Describe the bug**
Logging out of the CHT while you are offline takes you to a page that says "No Internet".

**To Reproduce**
1. Make sure you are online
2. Log in as an offline user
3. Disable your internet connection
4. Tap on Log Out
5. Confirm log out 

**Expected behavior**
I would expect to see the login page.

**Screenshots**
![Logout](https://user-images.githubusercontent.com/10096985/152050088-0aa163df-811f-4b6a-991f-59406e16b433.gif)

**Environment**
- Instance: https://demo-cht.dev.medicmobile.org/
- Browser: Brave
- Client platform: MacOS
- App: webapp
- Version: 3.13.0

**Additional context**
Offline users often do not have access to log out anyway so many projects probably wouldn't encounter this.

**Comment by dianabarsan** [comment]
Very interesting. 
I'm trying to replicate locally, and on [gamma](http://gamma.dev.medicmobile.org/) and I'm not seeing this behavior. 
I *can* replicate on https://demo-cht.dev.medicmobile.org/ however. 

When checking the chrome devtools, I can see an error that I've never seen before: 
![image](https://user-images.githubusercontent.com/35681649/152128646-da3d75f2-06d4-4d98-970f-6702d4304d43.png)
I'm referring to the "Navigated to chrome-error://chromewebdata/" bit, which I don't see when trying to replicate this on any other instance. 

Additionally, all of my "data" is not available: 
![image](https://user-images.githubusercontent.com/35681649/152128907-6971f43f-c194-45c6-b357-aad6b2786107.png)

Versus: 
![image](https://user-images.githubusercontent.com/35681649/152129143-82e49954-5c0d-453b-9d6d-75fc73129317.png)

With demo-cht, it looks like Chrome (and Brave) somehow lose access to the website data.

**Comment by dianabarsan** [comment]
There's a StackOverflow response that says that navigation to chrome-error://chromewebdata/ might be caused by an invalid URL in location.href: https://stackoverflow.com/a/55716793
However, the URL seems valid and is open successfully if I am online: https://demo-cht.dev.medicmobile.org/medic/login?redirect=https%3A%2F%2Fdemo-cht.dev.medicmobile.org%2F%23%2Fmessages&username=diana

**Comment by dianabarsan** [comment]
Oh ... this was a known issue: https://github.com/medic/cht-core/issues/7307 and fixed in 3.14. 
Michael, can we safely close this?

**Comment by michaelkohn** [comment]
Thanks @dianabarsan ! Yep i'll close it.
