### ISSUE TITLE
All places filter in Reports tab is distored when hierarchy is long

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#7502]
**Describe the issue**
When hierarchy includes multiple levels than regular 3/4 hierarchies, the All places filter option in Reports tab is distorted and indention of the places is confusing and unhelpful. 

**Describe the improvement you'd like**
Display places without confusing indentation. 

This is for the isntance where there are following hierarchies: 
Center -> Provinces -> District -> Municipalities -> Wards -> CHN Areas -> FCHV Areas -> Households -> Person

![image](https://user-images.githubusercontent.com/6102813/152836034-463a1c94-164c-439e-af35-2a87bfd25290.png)

If you look at the image above, ***Mathillo Gau (CHN Area)*** , ***Maili didi ko Area (FCHV Area)*** ,and **Ram Thapa को घर धुरी (house hold)**, all appear at the same level as MoH Nepal, which is Center (or top level hierarchy).

**Comment by michaelkohn** [comment]
Can you tell us a bit more about the user you are logged in as? I assume it's an online user... is it as an admin or as a contact at a certain level? (PS we can chat about this on our call tomorrow)

**Comment by michaelkohn** [comment]
@yrimal can you test this on 3.17 or higher and see if it's still an issue?  The UX for filters changed in 3.17 and I'm curious if it has solved your concern. 

<img width="643" alt="Screenshot 2023-05-25 at 4 14 03 PM" src="https://github.com/medic/cht-core/assets/10096985/e33c946a-80af-4cb7-826a-d54d02c4bdeb">

**Comment by yrimal** [comment]
Hi @michaelkohn , I can confirm that this has been fixed and we don't see this problem in 3.17.1.
