### ISSUE TITLE
Translations not working when using repeat groups with dynamic repeat count

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7515]
**Describe the bug**
When using a repeat group with the repeat count set to a dynamic field, the text inside the repeat group appears in English even though the language is set to Nepali.

**To Reproduce**
1. Deploy 3.14
2. Upload this form: https://gist.github.com/dianabarsan/144fd2a781dd989648d21c2f8ad5954c
3. Switch your language to Nepali
4. Open the form and increase the number of repeats. 
5. See that subsequently added repeats are not translated

**Expected behavior**
Repeats should pick correct translations for fields. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/153863642-995ffca2-4b55-4c5d-b2c6-c68817bbb238.png)

**Environment**
- App: webapp
- Version: 3.14 (introduced in 3.14, working in 3.13)

**Additional context**
Originally reported on the forum: https://forum.communityhealthtoolkit.org/t/translations-not-working-when-using-repeat-groups-with-dynamic-repeat-count/1713

This appears to be cause by [this change](https://github.com/medic/cht-core/commit/d6c83f92168a80b5ebdb7409f8ac61909a54928c#diff-35f326c2c6a97b7394203d191a6128becef8e55244826f4126d53ebcc4494267R295) where we only apply the language to new fields when a certain button is clicked. In the case of this form, repeats are added by increasing the number in an input field.

**Comment by m5r** [comment]
This is ready for AT on branch `7515-fix-translations-in-repeat-groups-enketo-form`

[PR link](https://github.com/medic/cht-core/pull/7520)
