### ISSUE TITLE
Register feedback doc when forms fail to load. 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7525]
**What feature do you want to improve?**
We catch all errors that happen when forms fail to load ([an example](https://github.com/medic/cht-core/blob/e8406d3e384cdbc48faa87e7134162b94a0bca33/webapp/src/ts/modules/contacts/contacts-edit.component.ts#L172)). However we don't register feedback docs when these crashes happen. 

**Describe the improvement you'd like**
Create a feedback doc when a form fails to load. 

**Describe alternatives you've considered**
Find some way to trickle down the error further so it gets in the automatic feedback doc capturing mechanism. 

**Additional context**
https://forum.communityhealthtoolkit.org/t/help-understand-and-fix-error-loading-form-please-try-again-or-check-with-an-administrator/1681/9

**Comment by latin-panda** [comment]
@elvisdorkenoo looks like this was merged but the ticket is open, if nothing is left to be done, please close the ticket and add the milestone so it's included in the release notes :)

**Comment by elvisdorkenoo** [comment]
Yeah it's done !
