### ISSUE TITLE
Can't edit forms that have empty "binary" fields

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7530]
**Describe the bug**
Trying to edit a report that has a non-required upload fails. 

**To Reproduce**
1. Upload a form with an image selector, for example: https://github.com/medic/support-scripts/blob/master/forms/photos-on-android.xml
3. Open the form, don't add an image and save. 
4. Open the report. Hit edit.
5. `Error loading form. Please try again or check with an administrator.`

**Expected behavior**
Make sure any form that can be submitted can be also edited. 

**Logs**
![image](https://user-images.githubusercontent.com/35681649/154911441-6cdf1813-294f-4a26-990c-e5358090882f.png)

**Environment**
- App: webapp
- Version: 2.15+? The code looks like has not changed since it was added in this commit: https://github.com/medic/cht-core/commit/4457404d43e66f5f98b8ae497338e14f8de33f84

**Additional context**
Came across it when reviewing a PR that fixes file uploaders in Android.

**Comment by dianabarsan** [comment]
Forum post reporting this issue as well: https://forum.communityhealthtoolkit.org/t/error-loading-form/2438

**Comment by garethbowen** [comment]
This was fixed in 4.9.0 along with the refactoring done on the Draw widget.
