### ISSUE TITLE
Missing subtitle translation for Children under 5 Target in demo-cht.dev

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7545]
**Describe the bug**
The subtitle for this target is showing the translation key, not the translated text.

**To Reproduce**
1. Go to https://demo-cht.dev.medicmobile.org/#/analytics/targets
2. Scroll down to 'Children under 5'

**Expected behavior**
Subtitle has a translation

**Screenshots**
See below

**Environment**
- Instance: https://demo-cht.dev.medicmobile.org
- Browser: Brave
- Client platform: MacOS
- App: webapp
- Version: 3.14

![Screen Shot 2022-03-02 at 9 11 11 AM](https://user-images.githubusercontent.com/10096985/156378805-0f9a59ca-0bb3-49c3-9630-af9d5cc95636.png)

**Comment by garethbowen** [comment]
@michaelkohn I can see the issue, but I can't find the source configuration to fix it. The `standard` config is similar but slightly different. It's also similar to `medic-projects/demo-cht` but that one's missing even more translations. It's possible it's been configured through the admin app so it's not in sync with its original source, but we should make sure the configuration is upgraded regularly so the demo is up to date.

Do you know what configuration this should be?

cc @abbyad

**Comment by michaelkohn** [comment]
I don't know what config it should be... maybe @smbuthia knows?

**Comment by michaelkohn** [comment]
The updated demo environment does not include this target so this is not irrelevant.
