### ISSUE TITLE
choice_filter in xlsforms is broken on 3.14.1

### ISSUE THREAD

**Issue by jonathanbataire** [medic/cht-core#7550]
**Describe the bug**
When you add choice filter to a question the choices lose their labels i.e it a blank space

**To Reproduce**
On CHT v 3.14.1
1. Add the following sample form with choice filters. ie Every subsequent question answer choices are filtered based on the previous question answer
[cascading_select.xlsx](https://github.com/medic/cht-core/files/8222830/cascading_select.xlsx)

2. As you select answers for the different questions you can see the filter filtering the subsequent choices but the labels are missing 

**Expected behavior**
I have tested this on version 3.11 and the labels to filtered choices are available.

**Environment**
- Instance: localhost 
- Browser: chrome
- Client platform: Linux ubuntu
- App: webapp  3.14.1, cht-conf v3.8.0

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
I've also just tested on 3.14.0 and am not seeing this behavior. This seems to have been introduced in 3.14.1.

**Comment by m5r** [comment]
This is ready for AT on branch `7550-fix-choice-filter-xlsforms`

[PR link](https://github.com/medic/cht-core/pull/7555)

**Comment by tatilepizs** [comment]
**Config:** Default 
**Environment:** Local with docker helper script 
**Platform:** WebApp 
**Browser:** Chrome

**Test scenario**
The provided [cascading_select.xlsx](https://github.com/medic/cht-core/files/8222830/cascading_select.xlsx) was used to test in both branches 

**Reproducible on** `3.14.1`
Labels shown as blank after selected an option in a choice_filter question

![image](https://user-images.githubusercontent.com/94494491/158474814-56ad5828-5bfd-4388-aba0-03b8b91e842d.png)

**Fixed on** `7550-fix-choice-filter-xlsforms`
Labels are shown correctly.

![image](https://user-images.githubusercontent.com/94494491/158476477-0182a234-45b4-4f23-87eb-d81e34be57f8.png)

**Comment by yrimal** [comment]
Are we planning to release this in 3.14.x version immediately after fix and verification? We are upgrading one of our instance to 3.14.1, and would wait if that's the case. We need the feature/bug fixed on 3.14.1, so we'd want this to be backported or released.

**Comment by latin-panda** [comment]
Hi, yes @yrimal it is available in [3.14.2 milestone](https://github.com/medic/cht-core/milestone/100), the team is working hard to [get it out soon](https://github.com/medic/cht-core/issues/7551), we will notify in the respective channels and forum.

**Comment by m5r** [comment]
@yrimal @jonathanbataire [3.14.2 is now released](https://forum.communityhealthtoolkit.org/t/announcing-the-release-of-the-cht-core-framework-v3-14-2/1782) and contains the fix for this regression.
