### ISSUE TITLE
Quick code fixes: import alias, service interface data type, remove unused parameters. 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7557]
**Describe the issue**
Creating this issue to track AT and sending these quick fixes for fast merging into the main branch, because I'm working on a feature release that might take long to merge into main.

Improvements are:
- Fix data types in the Enketo Service's interface.
- Remove unused parameters in the Enketo Service's `replaceJavarosaMediaWithLoaders` function.
- Fix alias in imports.

Suggested test: 
- Enketo is working as usual.

**Comment by latin-panda** [comment]
The relevant change is in the media loader where I removed an unused param, see [here](https://github.com/medic/cht-core/pull/7546/files#diff-35f326c2c6a97b7394203d191a6128becef8e55244826f4126d53ebcc4494267R87).

This function adds a loading spinner wrapper in the media element, the spinner wrapper [will be removed](https://github.com/medic/cht-core/blob/77d1dcc95aef0229abf70aa43e50f3fd5f0893fa/webapp/src/ts/services/enketo.service.ts#L111) when we get the media from the DB or it'll be hidden if[ something when wrong.](https://github.com/medic/cht-core/blob/77d1dcc95aef0229abf70aa43e50f3fd5f0893fa/webapp/src/ts/services/enketo.service.ts#L115)

_Loading spinner wrapper_
![Screen Shot 2022-03-16 at 12 13 52 pm](https://user-images.githubusercontent.com/66472237/158522012-fc3593b5-01b9-4233-a346-773ddb9a7d7b.png)

_Loading spinner wrappers are being removed as we get the media_
![Screen Shot 2022-03-16 at 12 14 15 pm](https://user-images.githubusercontent.com/66472237/158522034-c5933fc1-9d06-4368-a141-aa2d78f0dc7d.png)

_Loading spinner wrapper is removed and media is displayed_
![Screen Shot 2022-03-16 at 12 14 28 pm](https://user-images.githubusercontent.com/66472237/158522081-bf4dc07e-ac61-4c1e-b174-8d395de836e9.png)

CC: @tatilepizs

**Comment by tatilepizs** [comment]
Thanks @latin-panda for the details.

I used an enketo_widgets form that has different options to test.
Here are the tests:

<details>
<summary>Text widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158897546-a20b7cdb-9b65-45da-99a1-b00b35913d4b.png)

</details>

<details>
<summary>Number widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158898069-77fa6b2b-a320-4519-a7b3-b20f47d6a020.png)
![image](https://user-images.githubusercontent.com/94494491/158898111-0445444c-5665-4f62-b973-f5b0e03d8586.png)

</details>

<details>
<summary>Date and time widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158898199-dbf92a2c-82d8-484b-b962-ac302330ecbd.png)

</details>

<details>
<summary>Select widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158898268-9852568e-23ee-4c6e-881c-8a514e124c23.png)

</details>

<details>
<summary>Cascading select widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158898493-21a321f4-81a9-45cb-b3e2-164869953bcb.png)

</details>

<details>
<summary>Media Widgets</summary>

![image](https://user-images.githubusercontent.com/94494491/158896831-09c64416-50b9-4d02-b3a0-fb7477270899.png)
![image](https://user-images.githubusercontent.com/94494491/158898704-658802e7-5a0b-411e-b679-3192186b4e8e.png)

</details>
