### ISSUE TITLE
Re-enable the ability to get user's language in Enketo forms

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-core#7559]
**Is your feature request related to a problem? Please describe.**
Before #7068, we used to collect the user's language in the app forms inputs such as bellow 
![image](https://user-images.githubusercontent.com/63068738/158336872-88a4497b-40ff-47a9-8257-6e12f3d04dac.png)
to ease calculations and displaying of calculated filed such as this: `if(${s_acc_danger_sign_hemoptysis} = 'yes', if (${language} = ‘en’,'Hemoptysis (blood-stained sputum)', if (${language} = ‘fr’,'Hémoptysie (crachats teintés de sang)', 'Da ji joliman')),'')` 
This ability being removed from 3.12, all calcultations based on this are broken for all users created after an upgrade to the latest cht.

**Describe the solution you'd like**
We'd like to be able to get the user's language from the app forms again, via the user-settings.

**Describe alternatives you've considered**
One of the alternatives we are using right now is to create 1 variable per language for each of those concerned by this.

**Additional context**
We are about to go live with the new project `muso-cdi`, with `cht v3.13.0`, and just noticed during internal QA[ that the default language picked for displaying some concerning fields is Bambara](https://github.com/medic/config-muso/issues/736#issuecomment-1066926162). Investigations demonstrated that this is happening because we don't have the user's language in the form.

**Comment by dianabarsan** [comment]
The language doesn't necessarily need to come from user-settings, we just need to find a way to make the selected language available in Enketo forms.

**Comment by Marina-Kenf** [comment]
As long as we're able to get it in the form, that's fine :)

**Comment by mrjones-plip** [comment]
@Marina-Kenf  - is this blocking any of the projects you're working on?

@dianabarsan  - are we considering this a regression such that it could be a candidate for 3.14.2 or 3.14.3 depending on the timing? I didn't see the "regression" label on it, but the "re-enable" in the title had me wondering.

**Comment by Marina-Kenf** [comment]
is this blocking any of the projects you're working on?

**Comment by garethbowen** [comment]
I've called it a regression because we unintentionally broke backwards compatibility.

**Comment by njogz** [comment]
This is ready for AT [here](https://github.com/medic/cht-core/pull/7574).

**Comment by ngaruko** [comment]
Tested on local by modifying the `edit-person` form to include `user > language`. 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/6979995/161003008-60cad8c5-ba15-48c9-bcbd-8609f93f0bc5.png">
