### ISSUE TITLE
Record the form's version when saving a report

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7561]
**What feature do you want to improve?**
Currently when you view a report in couchdb or postgres you can tell which form type was used to generate it, but not which version of the form was used.

**Describe the improvement you'd like**
Copy the form version that was [added to cht-conf recently](https://github.com/medic/cht-conf/issues/395) and save it on the report generated when the enketo form is submitted.

**Describe alternatives you've considered**
You can't use the reported_date or initial_replication_date because you don't know for sure when the user replicated the new version of the form to their device.
For some changes it's possible to check whether the expected fields are there or not but this doesn't cover all cases, for example, if an additional value was added to a select.

**Comment by garethbowen** [comment]
This is ready for AT on `395-xml-form-version`.

To test this
1. You'll need the latest version of cht-conf.
2. When you upload the forms with cht-conf it now records an xml_version on them with the date they were compiled and a hash of the contents.
3. With this change when you submit a report it copies the xml_version from the form into the report doc so for each report you know which version of the form generated it.

It should be completely backwards compatible so it works even if the form was generated with an older version of cht-conf.

**Comment by ngaruko** [comment]
Form contains ```
"xmlVersion": {
    "time": 1649362670263,
    "sha256": "8d9b3a215ae7fd54e8f7e09921562812afd3ec3860a8d5a51afb239e17858197"
  },
```
<img width="827" alt="image" src="https://user-images.githubusercontent.com/6979995/162307976-0dc284bc-dc9c-41a5-bbb5-5d5f2e632974.png">

**Comment by ngaruko** [comment]
^Ready to merge @garethbowen

**Comment by aodhan-domhnaill** [comment]
Merged
