### ISSUE TITLE
Expose purgelogs to users without requiring an online user role

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#7593]
**What feature do you want to improve?**
We are building an app monitoring system and want to confirm that purging has completed. In Q1 two live-site incidents were the result of purging not completing and it went undetected for many months. Ideally, our monitoring tool should not require online permission for all instances monitored.

**Describe the improvement you'd like**
* API endpoint which includes purgelog details
* Or purgelog details syncing into postgres
* A permission which allows access to medic-sentinel database without being an online user

**Comment by garethbowen** [comment]
Sounds like a perfect addition to the monitoring API. Specifically what question do you want to answer? "is purging complete: true/false"?

**Comment by kennsippell** [comment]
Probably completion date of last purge (last 3 purges?) and the full content of all `purgelog:error` documents.

**Comment by garethbowen** [comment]
The monitoring API is designed to sound the alarm when there's an issue but not designed to provide diagnosis. If we start including more information such as the error message then we risk leaking private information that's included in the error message.

I propose the monitoring response looks something like...

```json
{
  purging: {
    latest: {
      success: true,
      timestamp: '2022-02-02....'
    }
  }
}
```

There's a little complexity because each role combination has a different purge doc but I think if _any_ role combination failed, then success should be `false`.

If success is false, or the timestamp is really old, then a human gets involved to do the diagnosis, who access medic-sentinel db directly.

That makes the script really easy but ultimately someone still needs credentials to see the error. They will likely need credentials to fix the error anyway so potentially won't slow you down much?

**Comment by kennsippell** [comment]
Currently to get access to sentinel logs you need admin credentials, or you need a user with `mm-online` (access to all docs) with additional elevated permissions by manually editing `medic-sentinel/_security`.  [Example](https://forum.communityhealthtoolkit.org/t/access-to-purge-logs/1826/7)

For some projects, we have app devs outside Medic who don't have admin permisisons. Is editing the _security for the sentinel db your recommended path to access for them or should we provide another? 

For some UG projects, our Medic teammates are the app devs without admin permissions but we would like to monitor the health of the app (including purging).  In this case, we also can't have mm-online access anymore because it gives us access to all PHI for the national system. To get access, we need to go through political channels and justify it.  We need a path to access purge logs without having access to **everything**.

Sounds like it is maybe not a perfect fit for the monitoring API?

**Comment by garethbowen** [comment]
I think monitoring, plus some other way to access the error is the way to go.

What about if the error was logged in the sentinel logs? I assume app devs have access to the logs, and if you have the error timestamp it should be reasonably easy to find the stack trace. It's not the _most_ user friendly option but is easy, secure, and feels like a logical place to put it. It also means anyone looking at the logs may sound the alarm too even if they haven't hooked up the monitoring framework yet.

**Comment by kennsippell** [comment]
As of 3.14, I believe purgelog:error happens even when purging completes successfully. So we might need to clarify the idea of how/when we "sound the alarm". The Monitoring API might need info about purging success + additional details about error rates. If that is true, I believe logging alone would be insufficient.

Additionally - Sentinel logs are okay for Medic-hosted projects, but I think self-hosted instances lack a convenient way to go through log events. I'm not totally sure about that, but they definitely don't all have a system as easy as logtrail.

**Comment by garethbowen** [comment]
> As of 3.14, I believe purgelog:error happens even when purging completes successfully.

Looking at [the code](https://github.com/medic/cht-core/blob/master/sentinel/src/lib/purging.js#L579) I wouldn't expect it to behave that way... What _should_ be happening is a doc is created with the _id `purgelog:<date>` or `purgelog:error:<date>`, and a sentinel info log written with either `Purging failed after ... minutes` or `Purging completed in ... minutes`.

There is some complexity to do with different combinations of roles, for example, purging of CHWs may pass, but purging of Supervisors may fail. I think it'd be appropriate to say purging has only succeeded if _all_ combinations of roles succeeded.

> I think self-hosted instances lack a convenient way to go through log events

We should definitely solve this, too. Should be easier in 4.0.0 with 1 log stream per container.

> Why not /api/v1/purgelog which serves up the purgelog docs from the db?

Could do, but there will be heaps of docs. I suspect you want something more sophisticated so you can just get the most recent errors?

**Comment by kennsippell** [comment]
Sorry, I'm just starting to use 3.14 now. I thought there was a `purgelog:error` for each contact that failed to purge. But it is a new attribute `skipped_contacts` inside the purgelog document.  Do we want to "raise the alarm" based on the number of skipped contacts?

**Comment by garethbowen** [comment]
I'd say, yes, that should also be exposed in the monitoring API, from which app devs can decide whether or not to raise the alarm.

**Comment by kennsippell** [comment]
I've never actually seen a purgelog:error - maybe we don't need them.  So maybe something like:

```
{
  "purging": {
    "latest": {
      "success": "2022-02-02....",
      "failure": "2022-01-01....",
      "skipped_contacts": ["mr_a", "mrs_b"],
    }
  }
}
```

**Comment by kennsippell** [comment]
A workaround is to pull purgelogs from Postgres and expose them to users through dashboards. This allows users to view purgelogs without an online user role.

```
SELECT
  (doc ->> ''date'')::timestamptz as completion_date,
  ((doc ->> ''duration'')::double precision / 1000 / 60)::integer as duration_minutes,
  (doc ->> ''skipped_contacts'')::text as skipped_contacts,
  doc ->> ''error'' as error
FROM couchdb
WHERE
  doc #>> ''{_id}'' like ''purgelog:%''
;
```

See https://github.com/medic/cht-app-monitoring-data-ingest/pull/55

**Comment by kennsippell** [comment]
Between https://github.com/medic/cht-core/issues/7593 and https://github.com/medic/cht-app-monitoring-data-ingest/pull/55 I believe this is solved.

**Comment by garethbowen** [comment]
@kennsippell In the comment above you linked this issue to itself - is there another duplicate cht-core issue you meant to link to?

**Comment by kennsippell** [comment]
Oops. https://github.com/medic/cht-core/issues/7355
