### ISSUE TITLE
Fix `breatfeeding` typo in default config

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7595]
**What feature do you want to improve?**

There's a typo in the default config delivery form:
https://github.com/medic/cht-core/blob/6f3551a1b7b6d9efc5c9a507083f18960c70b9ed/config/default/forms/app/delivery.xml#L943
breatfeeding -> breastfeeding

**Describe the improvement you'd like**
Fix the typo. 

**Describe alternatives you've considered**
Don't fix the typo.

**Comment by garethbowen** [comment]
@elvisdorkenoo Given the PR got merged, does that mean we can close this issue?

**Comment by elvisdorkenoo** [comment]
Yes, we can. I just did, thanks for the notice.
