### ISSUE TITLE
Add additional tests for Enketo Form functionality

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7600]
**Describe the issue**
During AT for #6345, there were a number of behavior issues that were found that were not covered by any sort of automated tests. It would be very beneficial to have automated tests for these cases before the next Enketo uplift in #7599.  

- [x] Submit a form with a non-relevant `inputs` group. Verify the data in the `inputs` group is still saved.
    - [x] It would also be good to have at least one of the fields in the `inputs` group to have a constraint that is violated when saving the form.  Verify that the form still saves properly since the `inputs` group is not relevant.
- [x] Submit a form that uses data loaded from the patient's `contact-summary` (e.g. the default `delivery` form loads in the pregnancy UUID).  Verify the contact summary data is properly loaded (e.g. that the pregnancy UUID is saved for the `delivery` report).
- [x] Submit a form using the `instance::db-doc` and `instance::db-doc-ref` functionality and verify the new reports are properly created along with the expected doc-refs. (e.g. new contacts are created for the babies entered into the default `delivery` form.)
- [x] Submit a form with a `required` `tel` field and verify this is properly handled by the `phone-widget` proper and the report is saved.
- [x] Create a completely new test using the enketo widgets we don't have in our forms -> [Example forms](https://github.com/medic/support-scripts/tree/master/forms)

**Comment by jkuester** [comment]
@ngaruko yes it is still valid!  (And would be really good to address before https://github.com/medic/cht-core/issues/7599.)  I am not sure about the difference between `to-do` and `backlog`, though.... :confused:

**Comment by michaelkohn** [comment]
Looks like this issue is in Allies Code Health, please work with @mrjones-plip to organize.

**Comment by tatilepizs** [comment]
Merged into `master`.
PR #8480

**Comment by tatilepizs** [comment]
Merged into `master`.
PR #8480
