### ISSUE TITLE
API wants to build form xmls when forms are deleted 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7608]
**Describe the bug**
When watching for config changes, we filter out form document changes with a very simple id match: 
https://github.com/medic/cht-core/blob/52605ac752bb40ab61ee1198fd7fe1bc0fbef982/api/src/services/config-watcher.js#L163

This also matches form deletions and later, tombstones of those form deletions, and spams the logs with:
```
ERROR Failed to update xform: {
  error: 'not_found',
  reason: 'deleted',
  status: 404,
  name: 'not_found',
  message: 'deleted',
  docId: 'form%3Aundo_death_report'
} 
```

And later: 
```
INFO: Form with ID "form:pnc_danger_sign_follow_up_mother____3-336f91959e14966f9baec1c3dd1c7fa2____tombstone" does not need to be updated. 
```

**To Reproduce**
1. Start CHT (api and sentinel)
2. Upload default config.
3. Delete a form document.

**Expected behavior**
We should update the form matching code, so it doesn't capture deletions and tombstones. 

**Logs**
As above. 

**Environment**
- App: api
- Version: 3.14

**Additional context**
Labeling this as low priority. These errors are successfully caught, but they pollute the logs.

**Comment by garethbowen** [comment]
Ready for AT in `7608-handle-deleted-forms`.

Reproduction steps above should be sufficient to test this.

**Comment by ngaruko** [comment]
on main branch 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/6979995/169748903-98d37d48-ff95-4e59-9a20-8cb98c870282.png">

**Comment by garethbowen** [comment]
Merged.
