### ISSUE TITLE
Admin app is not localizable

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7617]
**Describe the bug**
The Admin App is [supposed to be localizable ](https://forum.communityhealthtoolkit.org/t/admin-app-localization/1860/2?u=michael)but is [hard-coded to always use `en`](https://forum.communityhealthtoolkit.org/t/admin-app-localization/1860/3?u=michael). 

**To Reproduce**
1. Provide a French translation for the `instance.upgrade` key
3. From the login screen, select French as your language
4. Log in as a user who can access the admin app
5. Notice on the list of tabs on the left hand side that "Upgrade instance" is still in English 

**Expected behavior**
The admin app can be viewed in French

**Environment**
- Instance: https://demo-cht.dev.medicmobile.org/admin/#/upgrade
- Browser: Brave
- Client platform: MacOS
- App: Admin
- Version: 3.14.0

**Comment by garethbowen** [comment]
I think what's missing is a call to the [SetLanguage service](https://github.com/medic/cht-core/blob/master/admin/src/js/services/language.js#L21). I think if this were called somewhere in the `main.js` it would just work.

**Comment by garethbowen** [comment]
Ready for AT in `7617-translate-admin-app`.

AT steps in the issue description.

**Comment by ngaruko** [comment]
Admin app translated
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/6979995/169768037-b90ebea5-7155-4980-9519-f5da73941ad6.png">

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/6979995/169768247-7602b610-3c62-4076-b2df-0b357626b366.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6979995/169768389-c2924e6d-6b00-4306-aa60-f380cd908d46.png">

**Comment by garethbowen** [comment]
Merged.
