### ISSUE TITLE
Update google-libphonenumber to support new Nepali numbers

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7621]
**Describe the issue**
Some deployments in Nepal need to accept newer numbers:

> Nepal telecom has started to convert the CDMA SIM into GSM SIM, the range of the newly changed SIM starts from the `+977976XXXXXXX` but the web app has not accepted this range of the mobile numbers

**Describe the improvement you'd like**
Update the `ruimarinho/google-libphonenumber` dependency once it has pulled in [the upstream change](https://github.com/google/libphonenumber/releases/tag/v8.12.48) (`v8.12.48`) from `google/libphonenumber` which has the support we need.

**Describe alternatives you've considered**
Manually pushing in the numbers with `cht-conf`

**Comment by mrjones-plip** [comment]
Note - we bump dependencies every release, so this maybe super easy and done by default, but adding a ticket to track google/libphonenumber.  If this lib gets bumped in `4.0.0`, but it doesn't include the upstream fix from `google/libphonenumber`, please push this out to `4.1.0`

**Comment by mrjones-plip** [comment]
Ah - great news! [There's already a PR to bring in the change from upstream](https://github.com/ruimarinho/google-libphonenumber/pull/332)!  Once this closes and they cut a relase, we can in turn bump our dependencies to pull in the change.

**Comment by binokaryg** [comment]
The previous [PR](https://github.com/ruimarinho/google-libphonenumber/pull/332) has been superseded by ruimarinho/google-libphonenumber#334 which has already been merged.

**Comment by mrjones-plip** [comment]
Thanks Binod! Now we just need to do the dependency update on our side.

**Comment by mrjones-plip** [comment]
@dianabarsan  - I see [package.json](https://github.com/medic/cht-core/blob/master/package.json) hasn't been updated for 4.0.0. Do you know if we could expect this ticket's dependency (google-libphonenumber) would get updated in 4.0.0 or if would be for 4.1.0's dependency update?

**Comment by dianabarsan** [comment]
It will be updated for 4.0.

**Comment by mrjones-plip** [comment]
Wonderful - thanks for the update!

**Comment by ngaruko** [comment]
@mrjones-plip @binokaryg . If I have understood, this issue has been fixed and the ticket could be closed?

**Comment by mrjones-plip** [comment]
I don't think so? I was very much hoping to get this fixed in 3.16, but I don't see a PR attached to this ticket.  

 I'll defer to @njogz , release manager for 3.16: we should either fix and release in 3.16 or move to 4.0

**Comment by njogz** [comment]
@mrjones-plip @ngaruko this never got picked up and I had filed it under nice to have in 3.16 and since we are not updating other packges I think it's best if we move this to 4.0.

**Comment by binokaryg** [comment]
We are using a workaround (only checking phone number length) so that we can add the new phone numbers. It can take a long time to take the multiple instances to 4.0. It would be great if we could support it earlier.

**Comment by mrjones-plip** [comment]
@binokaryg  - @njogz  confirmed:

> reviewing if the update google-libphonenumber [ticket](https://github.com/medic/cht-core/issues/7621) should be in 3.16

And I see a draft PR was just opened.  Thanks @njogz !

**Comment by binokaryg** [comment]
AT passed:
![image](https://user-images.githubusercontent.com/20041732/181424758-5ed0baf6-84e9-485e-b436-f75ddf696883.png)

**Comment by mrjones-plip** [comment]
Thanks so much @binokaryg! Really great to see it working with in a dev deployment with the specific config and a Nepali mHealth validated number :heart_eyes:

**Comment by tatilepizs** [comment]
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp 
**Browser:** Chrome

**Test scenario:**
Same test that @binokaryg did but using `Default config`. Everything looks good.

**Reproducible on** `Master`
![image](https://user-images.githubusercontent.com/94494491/181625367-7f749e5b-2cff-4103-aace-518d06cef18a.png)


**Fixed on** `7621-update-google-libphonenumber`

![image](https://user-images.githubusercontent.com/94494491/181625434-37f0658a-543d-496e-bbc8-111ed5828040.png)

**Comment by mrjones-plip** [comment]
Closing this assuming the PR being merged and 3.16 just passed RT. Please re-open if this isn't correct!
