### ISSUE TITLE
Replace developer docs with link to docs site docs

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7633]
**Describe the issue**
When we release the [new developer docs](https://github.com/medic/cht-docs/issues/700) on the docs site, we should replace the contents of the [Development.md](https://github.com/medic/cht-core/blob/575bc95a8ccf82b211a13fec9d3228f71169405f/DEVELOPMENT.md) with a "see docs site" link

**Comment by garethbowen** [comment]
@mrjones-plip We can implement this change now, right?

**Comment by mrjones-plip** [comment]
yes! I'll grab it later this week.  Thanks for the reminder to circle back.

**Comment by mrjones-plip** [comment]
oop! this was already done in 1f0f990150bf2e7df0242185f87365e96dbbecf9 - closing!
