### ISSUE TITLE
Report's filter redesign 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7653]
**Description**

[Taken from the forum:](https://forum.communityhealthtoolkit.org/t/feature-testing-filters/1917)
As we are working on incremental updates to the UI/UX of the CHT to be more scalable, intuitive, mobile-first and consistent with other Android experiences, we are looking to test a new design of filters.

![image](https://user-images.githubusercontent.com/66472237/174545990-39d95647-5aa9-46fe-9357-fee14277602f.png)

The current design allows users to select the type of filter from a row of drop downs with icons. Each filter type expands and users are able to filter content by selecting the appropriate checkboxes. The search icon expands to show a search bar.

![image](https://user-images.githubusercontent.com/66472237/174546374-e0677694-fdf2-4ce7-9c71-26a4c82ebc6b.png)

The proposed design decouples the search and filter functionalities. In this proposal, the user is able to view filters by tapping on the filter icon. This opens a drawer with a list of filter types. By tapping on the dropdown arrows, the user is able to view detailed filter options and tap on the appropriate checkboxes.

Our intention is to simplify the filtering experience by providing a cleaner interface and clearer labels that allows for better scalability.

**Additional context**
This work relates with this item from the [Road Map](https://github.com/medic/cht-roadmap/issues/61)
[Figma](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/Filter?node-id=0%3A1)

**Comment by latin-panda** [comment]
[Taken from forum](https://forum.communityhealthtoolkit.org/t/feature-testing-filters/1917/2)
Open questions from @michaelkohn  are:

**Active Filter**
It’s nice to know if a filter is currently applied (5th screenshot on the new design). There is a visual cue for this in the current app (though you can’t see it in mobile view). Is there a design pattern for doing that with the new filter icon (ie the funnel)?
![image](https://user-images.githubusercontent.com/66472237/174546846-3a89e720-3d99-43ff-8f8d-7320b8ec94a8.png)

**Place filter**
“Place” filters are tricky because there is a hierarchy element. It’s currently conveyed with indentation and can be confusing if you have many levels in your hierarch. I’m curious how it might look in the new design?
![image](https://user-images.githubusercontent.com/66472237/174546937-1bf532a5-8dd8-47ed-9033-24403125b1b8.png)

cc: @n-orlowski

**Comment by latin-panda** [comment]
@n-orlowski how does it look in desktop?

**Comment by n-orlowski** [comment]
@latin-panda @michaelkohn considerations are in the [Figma doc](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/Filter?node-id=0%3A1) under V2, please take a look!

**Comment by latin-panda** [comment]
Latest design: 

<details>
<summary> Desktop </summary>
<img src="https://user-images.githubusercontent.com/66472237/180967177-79e179cb-edc8-4f17-be94-d50925de0f7c.png" width="700">

<img src="https://user-images.githubusercontent.com/66472237/180967199-377d8c16-3fd1-4e94-8960-4054c29a20fb.png" width="700">

<img src="https://user-images.githubusercontent.com/66472237/180967203-c8857a67-2f24-43e6-a2a5-d5d13e07e3a9.png" width="700">

<img src="https://user-images.githubusercontent.com/66472237/180967207-2ee5f066-bfc1-4c97-a137-20daa940dfd3.png" width="700">

<img src="https://user-images.githubusercontent.com/66472237/180967209-78e87beb-07b6-4d8c-b1aa-62d376cd2fcd.png" width="700">
</details>

<details>
<summary> Mobile </summary>
<img src="https://user-images.githubusercontent.com/66472237/180967210-0ea96cf8-3617-4173-9f33-84a49b3b2117.png" width="300">

<img src="https://user-images.githubusercontent.com/66472237/180967212-5a503e4e-590e-4af4-9897-188f1278f097.png" width="300">

<img src="https://user-images.githubusercontent.com/66472237/180967218-3d23d810-4ea7-48b3-ad79-4bb55bb6e2ff.png" width="300">

<img src="https://user-images.githubusercontent.com/66472237/180967219-c7bc2638-72d8-4bf3-87dd-c3a8a22a82aa.png" width="300">

<img src="https://user-images.githubusercontent.com/66472237/180967225-f1efada4-c2c9-4e5c-86e6-b72b7ffad3cd.png" width="300">
</details>

**Comment by latin-panda** [comment]
Cool thanks @michaelkohn! What is the phone's resolution in pixels? 

> 1: Slide out panel sizing

That's very small resolution! I tested in Samsung S3 (360 x 640 very old) and the filter was fully visible. Anyhow that's fixed, but I think these users experience won't be nice when using the places filter and there's deep hierarchy.

> 2: Cannot see full calendar and cannot scroll to see it

This dropdown calendar component is a floating element outside the scroll scope of the container (it won't scroll with the rest of things), its position is calculated with javascript. Other good libraries automatically recalculate and re-position the calendar when it can't fit, but the library that we're using is limited and doesn't do that. 

I've added a workaround but it's not perfect. Very small devices like probably your Tecno phone, won't fit when opening on top or below the date input. 

I recommend to move the "date filter" section on top of the "form filter" that way we ensure the calendar will fit in the screen, even if it's not the most used filter by the user. 

The date component has been a challenge while working on this assignment, it has limited features for what we need in the new design, [not supported anymore](https://github.com/dangrossman/daterangepicker/discussions/2266#discussioncomment-2594296), not interest of merging contributions ([55 PR](https://github.com/dangrossman/daterangepicker/pulls)), last release was 2 years ago but we can't upgrade ([bootstrap-daterangepicker](https://docs.communityhealthtoolkit.org/core/guides/update-dependencies/#problems)) anyways. We need to change it for a smarter modern option that supports Nepali and all other languages (I'll open a ticket for this)

 > 3: Tap zone size

I think we'll need to update all similar bars, but I'd like to see first if @n-orlowski would like to improve other elements was well and work them all at once. I'll leave this bullet open. On the UI topic, Josh observed that places's chevron icon, the one that you click to see the parent's child place, looked like disabled because of the grey color, perhaps changing the shade to darker would improve that perception.

**Comment by michaelkohn** [comment]
>Josh observed that places's chevron icon, the one that you click to see the parent's child place, looked like disabled because of the grey color, perhaps changing the shade to darker would improve that perception.

Are you talking about this one?  If so, it's not clickable for me (on any device). 

<details>
<summary> Place chevron </summary>

<img width="501" alt="Screen Shot 2022-07-29 at 9 56 18 AM" src="https://user-images.githubusercontent.com/10096985/181775892-dfffd46a-39d0-4878-9ddf-e71f0370de55.png">

</details>

**Comment by latin-panda** [comment]
@michaelkohn yes that one! The icon helps to indicate whether the section is collapsed/expanded, but in this case the concern is that it can indicate the feature of collapsing/expanding is disabled. The users can always explore and find out.

The click event is attached to the title area, the icon as added as a pseudo element (not explicit html element) as indicator of current state (collapsed/expanded) a bit outside the title area to avoid text overlapping the icon.

**Comment by latin-panda** [comment]
@tatilepizs @ngaruko 

This is ready for AT in [this PR](https://github.com/medic/cht-core/pull/7696). You can refer to the PR's description and reach out to me if you need a walkthrough.

Besides your test plan, I recommend to also cover the following:
- The [filter design](https://github.com/medic/cht-core/issues/7653#issuecomment-1195244290) looks good in mobile and desktop.
- Everything else displays as expected (messages, contacts, targets, etc) because in order to insert the filter as sidebar I had to change the general layout and styles in: reports, reports detail, edit reports, contact, actions-bar component. There could be side effects in other tabs because we reuse some code. Make combinations like when filter is open, when filter is close and try other things around. 
- The search is working fine for reports and contacts in these combinations: mobile device, desktop, old filter and new filter.
- Check that a current issue affecting place filter is fixed in both, new and old filter: 
  - If one child place was already selected and the user selects the parent place, it was unselecting the child. The expected behaviour is to select the parent and all its children. 
  - This isn't easy to see in master because the UI shows everything is selected but it's actually not selecting. The filter isn't sending all selected places to filter reports.
  - Filter works based on CouchDB views, in this case the view is reports_by_place (`[your instance]/_utils/#/database/medic/_design/medic-client/_view/reports_by_place`), there you can see the place associated to the report.
- Check that a current issue when logging telemetry is fixed in both, new and old filter:
  - When a filter is applied, then cleared individually by clicking "clear", telemetry will keep logging the filter as if it was still in use. The expected behaviour is to not log filters with no selected criteria. 
- Check that a current issue is fixed both, new and old filter:
  - When select mode is on and some reports are selected, [it shouldn’t let the user filter or search](https://github.com/medic/cht-core/issues/1000#issuecomment-170813237)
- New permission (`can_view_old_reports_filter `) is enabling the old filter design for all users that has it, except DB admin user that can always see the new filter.
- Old filter works and looks fine <-- It was refactored
- Tour works as always with old filter. However it should skip the steps explaining filters when the new filter is enabled.
- Test with long list of places and with hierarchy.

**Comment by latin-panda** [comment]
[CHT Docs PR](https://github.com/medic/cht-docs/pull/746)

**Comment by tatilepizs** [comment]
@latin-panda I have a couple of questions:

1. I had the same impression that @jkuester and @michaelkohn had in [this comment](https://github.com/medic/cht-core/issues/7653#issuecomment-1199325399).
I also thought that the icon for the health center was disabled due to the gray color, I think that is a good idea to make the color a little darker. And then when I was trying to display the areas and households I was a little confused because when I clicked on the icon nothing was happening, my first instinct was to click on that icon to display the hierarchy, I thought that it was an error, but after clicking almost everything I realized that if I click on the name, for example, it will work. 
Would it be possible to make that icon clickable? I think that it will be easier.

3. I am not able to see the housholds in the `Place` filter. I was testing if it was something related to the user that create it, but I am not able to see them. I tried with the `admin` user and with an offline user.
Were they removed? or is there something extra that I need to do? because in the images that you attached to [this comment](https://github.com/medic/cht-core/issues/7653#issuecomment-1195244290) the HHs are displayed in the filter.

This is what I have: 
![image](https://user-images.githubusercontent.com/94494491/183715066-e41441b0-2059-49b5-825c-854650df89e4.png)
![image](https://user-images.githubusercontent.com/94494491/183715130-692051e0-704c-4e81-9b06-55c26a402247.png)

**Comment by michaelkohn** [comment]
>I am not able to see the housholds in the Place filter. I was testing if it was something related to the user that create it, but I am not able to see them. I tried with the admin user and with an offline user.

@tatilepizs re: ^ I wonder if it has something to do with the configuration (depth) of your [hierarchy](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/hierarchy/) and where your user sits in that hierarchy. What does your testing hierarchy look like?   FWIW... https://demo-cht.dev.medicmobile.org/ , which I believe is just configured with the  `clinic`, `health_center`, `district_hospital` hierarchy, also _does not show households_ as an option in the place filter.

**Comment by tatilepizs** [comment]
Thanks @michaelkohn 

I think that I made my comment a little confusing due to the names that I use. Those names are from the default config, but let me try to explain it with the correct name/id.

I am using three levels, `district_hospital`, `health_center`, and `clinic`

<details>
<summary>Mufasa's Health Facility (f63d44db-40f6-490b-aa94-9af221afaa72) -> type:  district_hospital </summary>

![image](https://user-images.githubusercontent.com/94494491/183752097-ad239722-2cb5-47be-b5e6-9dd324e02103.png)

</details>

<details>
<summary>Sarabi's Area (c9bc781e-fd53-47bd-8b61-9993ed49ab36) -> type: health_center </summary>

![image](https://user-images.githubusercontent.com/94494491/183752213-b93dbb31-4df9-4e1c-9b76-2b95e21cb830.png)

</details>

<details>
<summary>Zazu's Household (b5abc50b-934c-4314-9c06-f90800574e4a) -> type: clinic</summary>

![image](https://user-images.githubusercontent.com/94494491/183752362-6ac31442-a914-4883-8c6e-7fe862d79f59.png)

</details>

**Comment by tatilepizs** [comment]
I am a little confused, now I am not sure if I am using the correct branch, this is the one that I am using right now:

![image](https://user-images.githubusercontent.com/94494491/183766982-99d92868-305a-474c-9b83-7bd15300b344.png)

But If I go to the `permission` section I am not able to find the `can_view_old_reports_filter` one. I even search for just the word `filter` and `reports` but was not able to find it.

<details>
<summary>Images attached </summary>

![image](https://user-images.githubusercontent.com/94494491/183767445-4d70e789-4a47-4f6b-85a3-47ba7ebecb06.png)
![image](https://user-images.githubusercontent.com/94494491/183767512-291aa7bc-cef6-485a-9000-6e3730380484.png)
![image](https://user-images.githubusercontent.com/94494491/183767729-076d9ef8-a209-467e-9528-d9404519eeec.png)
![image](https://user-images.githubusercontent.com/94494491/183767771-1847aaec-198e-4e62-8e9a-5ef1c7441208.png)
![image](https://user-images.githubusercontent.com/94494491/183767816-5e9b0c33-92a6-49f6-941f-895a8f1d9c14.png)
![image](https://user-images.githubusercontent.com/94494491/183767869-ad76948b-ed52-4462-aa90-4d4bd942c965.png)
![image](https://user-images.githubusercontent.com/94494491/183767908-12216f7b-47f1-4b54-896c-b2fb3f064547.png)

</details>

Am I doing something wrong?

**Comment by latin-panda** [comment]
Hi @tatilepizs 

> Would it be possible to make that icon clickable? I think that it will be easier.

I'll get back to you on this one by tomorrow morning or before, I have to change the css and html structure. 

> I am not able to see the households in the Place filter

The options in places filter is controlled by `place_hierarchy_types` setting, if you're using default config, then you can add `clinic` in [that setting](https://github.com/medic/cht-core/blob/9dc444affbbfadbfe16c13831472f09a14a79981/config/default/app_settings.json#L29). Compile and upload the app-settings into your instance. 

> But if I check in the DB in the reports_by_place it is only associated with two places (Mufasa's Health Facility and Sarabi's Area). I would think that it should be associated with the three places too

I can see that `reports_by_place` view takes the place from the [db doc's contact](https://github.com/medic/cht-core/blob/9dc444affbbfadbfe16c13831472f09a14a79981/ddocs/medic-db/medic-client/views/reports_by_place/map.js#L3). That contact is injected by Enketo Service, [it gets the contact](https://github.com/medic/cht-core/blob/9dc444affbbfadbfe16c13831472f09a14a79981/webapp/src/ts/services/enketo.service.ts#L675) from the user and [save the report's document with it](https://github.com/medic/cht-core/blob/9dc444affbbfadbfe16c13831472f09a14a79981/webapp/src/ts/services/enketo.service.ts#L695). 
Consider a hierarchy of `level 1 > level 2 > level 3`. If the user's contact is associated to level 2 and the user creates a report for a patient in level 3, because the report is associated **to the user** and not to the patient, the `reports_by_place` view creates entries for this report in level 1 and level 2. Going back to the places filter, this report will appear in the results when selecting either level 1 or level 2.

If we want to see results when selecting level 3, then a user with associated contact in level 3 should create a report.


> But If I go to the permission section I am not able to find the can_view_old_reports_filter one

That's the correct branch! You will need to add the permission in the app_settings of your config:
```
 "permissions": {
   "can_view_old_reports_filter": [ "chw" ],
   ....
   ....
}
```
The list of available permissions is in [the docs](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/user-permissions/). We have [a PR](https://github.com/medic/cht-docs/pull/746) to added this new permission to that list.

**Comment by tatilepizs** [comment]
Thank you @latin-panda for all the details and the clear explanation. It is really helpful to see instruction/suggestions and to know what could be affected with the changes, thanks again 🎉 

This is the summary of my test, please let me know if there is anything else that I missed.

---

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome
**cht-core version:** `6028-title-test-too-long`
**Platform - mobiles:** Mobile App. Downloaded from play store **version 1.0.1**

### Mobiles

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 103.0.5060.129
**Android Version:** 10

**Phone:** Alcatel Onetouch 50560
**Android System WebView Version:** 95.0.4638.74
**Android Version:** 5.1.1

---


<details>
<summary>Filter design - desktop / mobile</summary>

#### Desktop
![image](https://user-images.githubusercontent.com/94494491/183974104-d5f445ae-2733-4508-85be-2bfe62df11d5.png)
![image](https://user-images.githubusercontent.com/94494491/183974444-e5a0edb8-db85-4447-a4c8-5fbcf33f9c7e.png)

#### Mobile - Android 10
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183975901-0023c91e-8107-4bbf-b97c-9fe81a739852.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183975939-0a6dbb2b-88d5-4443-85f0-90e585322061.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183975968-ac5d6f71-a968-4f77-926f-57e0da7753ce.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183976018-76660b64-c9e5-46f0-b6ce-a75fd04d0f8d.png">

#### Mobile - Android 5
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183977788-2d9b1231-76a7-4dec-bfb2-cedfac361a3e.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183977829-8fcc2940-b005-438a-8431-7956447df779.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183977869-cb01452d-18cb-4011-b243-a4587040553c.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94494491/183977913-605ed876-5588-4d7a-9059-de0c7cb24ef3.png">

</details>

<details>
<summary>Search is working as expected.</summary>

#### Desktop - New filter
![image](https://user-images.githubusercontent.com/94494491/183978364-3e8c3233-56a4-4647-b247-31f2d82a1d0b.png)
![image](https://user-images.githubusercontent.com/94494491/183978413-80764d77-a284-4dc0-adba-b8907b66c03d.png)

#### Mobile - Android 10 - New filter
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183978945-1417c00c-be05-4db8-b773-cdfa35766222.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183979015-a0aab239-1a21-429d-8ea8-ae65a1bfadea.png">

#### Mobile - Android 5 - New filter
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183979226-6f75a668-dc92-48a1-b414-238b1c902538.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183979272-afc61100-87e9-4928-9088-da45d1bcc941.png">

#### Desktop - Old filter
![image](https://user-images.githubusercontent.com/94494491/183980483-ae6919e1-4e1c-440d-87fc-4466d83fba65.png)

#### Mobile - Android 10 - Old filter

<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183981322-fb185079-3757-4ea1-b0f5-987e3c81f3e6.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183981347-57c283b8-9ac0-4209-97b5-823f84c98fcd.png">

#### Mobile - Android 5 - Old filter
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183981522-8b19ed95-4278-4f2c-b0e8-c2a649a46322.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/183981561-27845b8e-987a-408e-ad7f-7ebddd721994.png">

</details>

<details>
<summary>Place filter issue (parent place / child place) - Fixed</summary>


[video](https://user-images.githubusercontent.com/94494491/184002447-a8c14550-78f2-4143-821c-b6ca0de2bf66.mov)

![image](https://user-images.githubusercontent.com/94494491/184004520-27269fc6-e285-4cd2-8ed8-65b92395f789.png)
![image](https://user-images.githubusercontent.com/94494491/184004706-6818617e-34d6-477b-8d6c-8c9d7ac4d0f9.png)

</details>

<details>
<summary>Telemetry fix</summary>

This was a little difficult to test, I received Jenny's help to understand what should be the correct behavior. I finally test it and it was working fine. 
This is the file obtained after the test: [telemetry-2022-8-24-scar-e3a6563a-301e-4509-8e56-5cf0e7ed2cd9.txt](https://github.com/medic/cht-core/files/9303552/telemetry-2022-8-24-scar-e3a6563a-301e-4509-8e56-5cf0e7ed2cd9.txt)


</details>

<details>
<summary>Issue when select mode is on - Fixed.</summary>

[video](https://user-images.githubusercontent.com/94494491/184006040-71b3fbd1-5112-4dd5-9752-967b922302f6.mov)

</details>

<details>
<summary>Old filter enabled</summary>

#### Admin user
![image](https://user-images.githubusercontent.com/94494491/184006531-c92f429f-eecb-4097-955a-7742b4e141fe.png)

#### CHW user with the "permission" added in the `app_setting.json` file
![image](https://user-images.githubusercontent.com/94494491/184006889-7476652a-ad8e-450d-9a51-b3a7cdd6f652.png)
![image](https://user-images.githubusercontent.com/94494491/184006633-c8a30e29-e66a-4a10-9d2d-bd804dd00879.png)

</details>

<details>
<summary>Places with long names.</summary>

#### Desktop
![image](https://user-images.githubusercontent.com/94494491/184007511-c36d795b-7577-4207-9ff6-6935aa34c209.png)

#### Android 10
![image](https://user-images.githubusercontent.com/94494491/184009412-a3129263-9fbe-451e-964a-928e5332a0b8.png)

#### Android 5
![image](https://user-images.githubusercontent.com/94494491/184009361-9d58ecf4-4d88-4dfc-995a-bc0adafc17ec.png)

</details>

---

Everything is working perfectly, great work! 🎉 
Now I am just going to wait to see if you could do some magic with the icon for the hierarchy of the places (make it clickable)

> I'll get back to you on this one by tomorrow morning or before, I have to change the css and html structure.

**Comment by latin-panda** [comment]
Hi @tatilepizs,

About the chevron click:
I found a way to make it happen without affecting the title's wrap of 2 lines with ellipsis and that still works fine for the old filter.
Please pull the latest from the branch, this is the [commit](https://github.com/medic/cht-core/pull/7696/commits/1f2ba8be314c865442175c246fd275a869db9a8a) with the changes. 

About the chevron colour:
I've asked @n-orlowski, we agreed to leave it as it is for now, after user feedback if they have any problem using it then we can make it darker or find other option.

**Comment by tatilepizs** [comment]
Great @latin-panda, thank you for putting this together, it works perfectly 🎉 

<details>
<summary>Testing video - Desktop.</summary>

[video](https://user-images.githubusercontent.com/94494491/184177105-7b7c113f-d164-4394-9c30-d6a9a100920b.mov)

</details>

<details>
<summary>Testing video - Mobile.</summary>

[video](https://user-images.githubusercontent.com/94494491/184177159-e2319f84-f201-4a2b-9fc2-e3f51c33ca36.mov)

</details>

**Comment by latin-panda** [comment]
Thanks everyone!!! 🎉

Ticket to remove the old filter: https://github.com/medic/cht-core/issues/7726
Ticket to add visual indication to parent item when child is selected in Place filter: https://github.com/medic/cht-core/issues/7727

**Comment by michaelkohn** [comment]
I think we can ship it now, no need to wait for #7727.

**Comment by mrjones-plip** [comment]
Perfect.
