### ISSUE TITLE
The reports raw content has the label in the wrong place

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7657]
**Describe the bug**
The report content pane is essentially a list of properties with label above value... except for the raw report property which has the value above the label.

**To Reproduce**
1. Submit a JSON report using the test SMS page: /admin/#/sms/test
2. Go to the Reports tab
3. Check the "Raw report content" field

**Expected behavior**
The label and value should be in the same order as the other properties.

**Screenshots**

![Screenshot from 2022-06-28 14-16-20](https://user-images.githubusercontent.com/2064938/176077484-6aac54ed-00c0-4358-98c1-6a49f8abc43e.png)

**Environment**
- Instance: localhost
- Browser: any
- Client platform: linux
- App: webapp
- Version: 3.15.x (master)

**Comment by garethbowen** [comment]
Ready for AT on `7657-raw-label-order`

**Comment by ngaruko** [comment]
Tested on local install following the [steps above](https://github.com/medic/cht-core/issues/7657#issue-1286673922).
On `master`, the value is on top:
![image](https://user-images.githubusercontent.com/6979995/176641115-423c2657-2aa8-4567-8370-dd9838c54521.png)

on branch, the label comes first:
![image](https://user-images.githubusercontent.com/6979995/176640998-3ff1b659-327b-423d-8476-8a4116f1b6cc.png)

**Comment by garethbowen** [comment]
Merged.
