### ISSUE TITLE
Expose privacy policy at a public URL

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7662]
**What feature do you want to improve?**
Android app submission now requires a URL to the apps privacy policy.

**Describe the improvement you'd like**
Add a simple page which shows the privacy policy (if configured) without requiring login. Add a link to the login page to this new page so users can check the policy before logging in.

**Describe alternatives you've considered**
Having a stock privacy policy, but without context we can't answer questions like "what this data will be used for" or even "what data is being collected".

**Comment by mrjones-plip** [comment]
@njogz  - if this is a quick, it'd be a great win for 3.16.0, given how important it is!

**Comment by garethbowen** [comment]
@mrjones-plip I think you put this comment on the wrong issue... this one is still very much in development!

**Comment by mrjones-plip** [comment]
@garethbowen  - It is on the correct issue, I just think extremely highly of our core-devs!

I'll slow my roll though and be more patient ;)

**Comment by garethbowen** [comment]
Ok. It won't be ready in time for 3.16.0...

**Comment by mrjones-plip** [comment]
I'm still a believer!!

**Comment by garethbowen** [comment]
Ready for AT in `7662-public-privacy-policy`

**Comment by ngaruko** [comment]
1. No privacy policy configured 
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/6979995/181198312-c23b1599-5319-4388-bca5-1117c7d13410.png">

2. `medic/privacy-policy/
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/6979995/181198242-ffe1353f-b29c-46de-8fe0-5143acc2e626.png">

3. Privacy policy configured 
![image](https://user-images.githubusercontent.com/6979995/181198956-4ad774e7-5bce-4cdc-8700-f76adf705000.png)

**Comment by garethbowen** [comment]
@ngaruko Can you clarify whether this has passed or failed AT or whether it's still in progress?

**Comment by ngaruko** [comment]
@garethbowen - Passed

**Comment by garethbowen** [comment]
Merged.

**Comment by mrjones-plip** [comment]
> Merged.

While not technically _in_ 3.16, this is merged to `master` _before_ 3.16 is released - I'm still a believer!! 

thanks all

**Comment by garethbowen** [comment]
What you'll never know is if I purposefully held back on development to prove myself correct  ;)

**Comment by mrjones-plip** [comment]
well played sir!!

**Comment by latin-panda** [comment]
Does it make sense to add this work to the [cht-doc](https://docs.communityhealthtoolkit.org/apps/guides/privacy/privacy-policy/)?

**Comment by mrjones-plip** [comment]
@latin-panda  - yes please! I read over the AT steps above and couldn't figure how to implement it - docs are needed!

**Comment by mrjones-plip** [comment]
Opened [docs PR to capture this](https://github.com/medic/cht-docs/pull/770) - thanks again @latin-panda !

**Comment by tatilepizs** [comment]
Thank you @latin-panda and @mrjones-plip for updating the documentation.
I was trying to test this ticket for 3.17 and didn't understand what kind of `html` I need to upload, didn't know if it needed to have something specific or not.
I asked @latin-panda and she told me that just a valid `html` will be good, nothing specific.

Just adding this note to remember about this and maybe to add that little detail in the documentation.

This is an example of an `html` test file that worked:

``` .html
<html> <body> <h1>Test</h1> </body> </html>
```

**Comment by mrjones-plip** [comment]
ah - thanks for the note @tatilepizs ! 

do you think [the docs](https://docs.communityhealthtoolkit.org/apps/guides/privacy/privacy-policy/) could be improved per your comment?

**Comment by tatilepizs** [comment]
Yes, maybe just adding a note saying that the `html` it is just any valid `html` file.

If you check in the doc, in this part:

> Add these HTML files to the privacy-policies folder in your configuration, and associate them to the correct language in the privacy-policies.json file.

It is not saying anything about the `html` file, it was not obvious to me what file do I need to create and upload
