### ISSUE TITLE
Add lasers to the batsuit

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-core#7664]

**Comment by mrjones-plip** [comment]
![batman3](https://user-images.githubusercontent.com/8253488/176760262-509181a9-2cc3-48a1-abd7-c3730fa951b2.png)
![batman2](https://user-images.githubusercontent.com/8253488/176760267-1a7adbfe-8258-4ca2-a396-ab06b7dfff8c.png)
![batman1](https://user-images.githubusercontent.com/8253488/176760270-483d1a58-259e-4902-a105-79570d1f7b1f.png)
