### ISSUE TITLE
Answers to non-relevant questions in forms are not immediately cleared with new Enekto

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7674]
**Describe the bug**
This is a known issue that _will be_ introduced by the [Enketo uplift](https://github.com/medic/cht-core/pull/7256). Logging this here ([as requested](https://github.com/medic/cht-core/issues/6345#issuecomment-1167946463) by @garethbowen) as a point of reference and discussion.

Basically, the issue (reported by @tatilepizs [here](https://github.com/medic/cht-core/issues/6345#issuecomment-1164635324)) is that on old versions of enketo-core, if a question that has already been answered becomes non-relevant (such as if the user goes back and changes a previous answer) the answer value for the non-relevant question would be immediately cleared out and its value would be no longer be available to any XPath expressions throughout the form. If the question became relevant again, the user would need to re-enter their answer.

Now, with the new version of enketo-core that we are uplifting to (`5.18.1`), the `clearIrrelevantImmediately` option [has been removed](https://github.com/enketo/enketo-core/commit/26fb7d47921a71a1af75e95e4e75f1556a6d7c6d) and this makes the behavior a little more complex.  When an answered question becomes non-relevant, it retains its answer value and if it becomes relevant again, the user will not have to re-enter the same answer. If the form is submitted while the question is still non-relevant, the value will be cleared out before the form data is saved.  Unfortunately, due to [this Enketo issue](https://github.com/enketo/enketo/issues/82) the answer value for a non-relevant question will still be available to XPath expressions throughout the form _while the form is being filled out_. When the form is submitted, these expressions will be re-evaluated without the answer value from the non-relevant question, but until then, the expressions will still see the non-relevant answer value.  This, of course, can cause inconsistencies between what is displayed in the form and what is actually saved in the report.

The good news is this inconsistency has [been fixed](https://github.com/enketo/enketo-core/pull/870) in version `6.1.0` of enketo-core which introduces a new `excludeNonRelevant` option (which is still off by default).  

The `excludeNonRelevant` option is not going to have identical behavior to the `clearIrrelevantImmediately` option, but I think the new behavior (where the form remembers what the user had answered before) is actually desirable and does not seem likely to cause issues with existing form config (as long as `excludeNonRelevant` is set to `true`).  

---

One important thing to keep in mind is that we also noticed issues with this behavior as it pertains to our [custom logic for the `inputs` group](https://github.com/medic/cht-core/issues/6345#issuecomment-1021342562).  However, the new logic with `excludeNonRelevant` is likely to break this `inputs` functionality again and this will need to be accounted for when upgrading enekto-core.

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by latin-panda** [comment]
@jkuester if we [upgrade eketo](https://github.com/medic/cht-core/issues/7599), will it fix this bug?

**Comment by jkuester** [comment]
I think the short answer is yes, the Enketo upgrade should "fix" this issue via the `excludeNonRelevant` functionality.  As noted up in the description: 

> The excludeNonRelevant option is not going to have identical behavior to the clearIrrelevantImmediately option, but I think the new behavior (where the form remembers what the user had answered before) is actually desirable and does not seem likely to cause issues with existing form config (as long as excludeNonRelevant is set to true).

As part of https://github.com/medic/cht-core/issues/7599, we should be enabling `excludeNonRelevant` (and getting everything sorted out with the `inputs` functionality...)

**Comment by latin-panda** [comment]
@garethbowen @jkuester Can we move this to 4.6? Since maybe we can get it fixed by #7599 work?

**Comment by garethbowen** [comment]
I'm leaving it here hoping that by some miracle the enketo uplift makes it in to 4.5.0.
