### ISSUE TITLE
Zero-width unicode characters removed from SMS messages too often

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7676]
**Describe the bug**
The fix introduced in https://github.com/medic/cht-core/issues/7654 is too aggressive and strips unicode characters from the entire message rather than just the parts needed for matching.

From @binokaryg 

> One minor caveat of this change is that if some text deliberately has zero-width characters, they would also be stripped out. These characters are very rarely used in general Nepali texting and the meaning and pronunciation remain the same, with or without them. For our use case, it might only be the name field that is potentially altered.

**To Reproduce**

1. Register a new patient via SMS with the name `र्‍याले`
2. See the name is changed to `र्याले` in the database

Also make sure we don't regress on the fix to #7654

**Expected behavior**
The name is a freetext field so should remain unchanged.

**Environment**
- Instance: localhost
- Browser: any
- Client platform: any
- App: api
- Version: 3.16.0

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment]
This is ready for AT on `7676-more-selective-stripping`

**Comment by tatilepizs** [comment]
**Config:** Standard
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`
After adding a new person via SMS (N form) with the name `र्‍याले`, the person is created successfully but its name is changed to `र्याले `in the database

<details>
<summary>Test images</summary>

![image](https://user-images.githubusercontent.com/94494491/184391794-d3661bd2-cef2-4e7b-b43c-6fea5654edf7.png)
![image](https://user-images.githubusercontent.com/94494491/184394312-4fbcea04-f12a-4fc9-8cb8-4c86313b9abc.png)
![image](https://user-images.githubusercontent.com/94494491/184394455-0a7b58ec-b77a-421d-aafc-adf9d73c33f8.png)
![image](https://user-images.githubusercontent.com/94494491/184394682-57fdc51c-8c05-4771-830b-e845040c8b75.png)

</details>


### Fixed on `7676-more-selective-stripping`
After adding a new person via SMS (N form) with the name `र्‍याले`, the person is created successfully and its name was saved correctly.

<details>
<summary>Test images</summary>

![image](https://user-images.githubusercontent.com/94494491/184395213-b75a1001-e005-4044-8ab3-952afecd9304.png)
![image](https://user-images.githubusercontent.com/94494491/184395315-f97465c7-0026-4d49-9138-496cad5e684c.png)
![image](https://user-images.githubusercontent.com/94494491/184395354-2f50e218-c929-49c2-bc03-a188eaf7e295.png)
![image](https://user-images.githubusercontent.com/94494491/184395560-efa6b3f4-c1b6-4685-b325-abe0a0914c75.png)

</details>

<details>
<summary>Test #7654</summary>
Not sure about this test, I had some problems uploading the Sunsari config and creating the place. @garethbowen please confirm if the test is correct.

![image](https://user-images.githubusercontent.com/94494491/184407241-edb6d033-e041-482b-8fed-96a74e967ab5.png)
![image](https://user-images.githubusercontent.com/94494491/184407394-93c51b74-863a-426e-b0a7-686a78b826d4.png)
![image](https://user-images.githubusercontent.com/94494491/184407516-13b34803-b081-47e9-b4fb-e05a0d3c596c.png)
![image](https://user-images.githubusercontent.com/94494491/184407574-bc1d3edf-6f9a-4fb0-9b7f-75e9f2147d14.png)

</details>

**Comment by garethbowen** [comment]
Merged!
