### ISSUE TITLE
Set form version when creating contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7689]
**What feature do you want to improve?**
When a report is submitted the version of the form that created it is stored to make it easy to write logic that branches depending on the form version. It would be useful if contacts created through the app also stored the form version.

**Describe the improvement you'd like**
When creating a contact (person or place) store the version of the form that was filled in on the doc.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
[Forum post](https://forum.communityhealthtoolkit.org/t/questions-about-form-versioning-introduced-in-cht-core-3-15-cht-conf-3-10/2032)

**Comment by garethbowen** [comment]
Ready for AT in `7689-record-form-version-when-saving-contacts`. You may like to test at the same time as #7690

AT instructions:

1. Make sure your person creation form has an `xmlVersion` property with `time` and `sha256` properties. If it doesn't, use a new cht-conf to upload it again.
2. Log in
3. Sync to make sure you have the latest version of the form
4. Create a person using the create person form set in 1
5. Check in CouchDB and make sure the person created has a `form_version` property that matches the `xmlVersion` of the form.

**Comment by ngaruko** [comment]
1. Contact doc has `form-version` 
![image](https://user-images.githubusercontent.com/6979995/182104847-41ba6d5a-d727-427b-9904-5f26b95a3d24.png)
2. form_version property that matches the xmlVersion of the form
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/6979995/182105403-ea51df5f-2148-4305-8611-a0d78236017c.png">

**Comment by garethbowen** [comment]
Merged.
