### ISSUE TITLE
Uploading a form through the app management GUI does not set the xml version

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7690]
**Describe the bug**
When uploading a form in the admin app the xml version should be set so that app builders can perform logic on a report based on which form created it.

**To Reproduce**
1. Go to App Management app
2. Select App Forms from the navigation menu
3. Upload a new form
4. Submit a report using the new form
5. Look up the report in CouchDB and notice it has no `form_version` property

**Expected behavior**
The report has a `form_version` property with the time that the form was uploaded and a hash of the form xml.

**Logs**
None.

**Screenshots**
None.

**Environment**
- Instance: localhost
- Browser: Firefox, Chrome
- Client platform: Linux
- App: admin
- Version: 3.15.0

**Additional context**
[Forum post](https://forum.communityhealthtoolkit.org/t/questions-about-form-versioning-introduced-in-cht-core-3-15-cht-conf-3-10/2032)

**Comment by garethbowen** [comment]
Ready for AT in `7690-admin-app-xml-version`. Reproduction steps above. You may like to test #7689 at the same time...

**Comment by ngaruko** [comment]
Looks good> Form uploaded using the app management GUI has `Xmlversion`
**_Master_**
![image](https://user-images.githubusercontent.com/6979995/182098617-6d434fd2-e41f-44a8-8a5e-6dd1837fd2cf.png)

_**Branch**_
![image](https://user-images.githubusercontent.com/6979995/182099138-d99f72ac-45d5-45eb-a885-995027e799a4.png)

**Comment by garethbowen** [comment]
Merged.
