### ISSUE TITLE
Add moment and datepicker translations for Luganda

### ISSUE THREAD

**Issue by brian256** [medic/cht-core#7712]
- [ ] Create a messages.lg.properties file for the Luganda translation modeled off of this [English language](https://github.com/medic/cht-core/blob/master/ddocs/medic/_attachments/translations/messages-en.properties) file. 
- [ ] Share with Miriam Achieng at MoH Uganda (as MOH App Services Lead)
- [ ] Share file with Uganda based partners ready to support translation work 
- [ ] Upload translated file back to CHT core
- [ ] Prepare translation with next app release for VHT App

**Comment by garethbowen** [comment]
@brian256 I'm wondering if the translations should be maintained in CHT Core or the project's configuration repo. Is the goal here to create a new supported language which is useful to other partners, or is this solely for a single project?

**Comment by garethbowen** [comment]
Ready for AT on `7712-luganda-translation`

To test it add a language for `lg` (LG in lower case) short for Luganda. The only real change in cht-core was to make `moment` and `bootstrap-datepicker` include lg translations.

Test `moment` using the dates shown in the app. Test `bootstrap-datepicker` by going to Reports, filtering and selecting the date filter.

**Comment by garethbowen** [comment]
Due to the urgent nature of this fix @jonathanbataire did the AT and I've released a feature branch here: `medic:medic:3.11.x-7712-luganda-translation`

After this has been ATed and merged to `master` we'll want to backport it to `4.1.x` so Uganda can upgrade and keep this fix.

**Comment by garethbowen** [comment]
@ngaruko Did you also test this bit:

> Test moment using the dates shown in the app.

Something like checking relative dates on the reports LHS with the hover showing the full date would be great.

**Comment by garethbowen** [comment]
Yes, perfect. Thanks @ngaruko !

**Comment by garethbowen** [comment]
Merged to `master` and backported to `4.1.x`

**Comment by andrablaj** [comment]
This was [released via 4.1.1](https://forum.communityhealthtoolkit.org/t/announcing-the-release-of-v4-1-1-of-the-cht-core-framework/2588).
