### ISSUE TITLE
Changing application and outgoing message languages does not seem to work properly

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#7717]
**To Reproduce**
1. Go to '/admin/#/display/languages'
2. Change application language to French and submit
3. Change outgoing language to French and submit 
<img width="902" alt="image" src="https://user-images.githubusercontent.com/6979995/183316157-4295c0bd-a989-44a4-b0d3-38d39f22e3d4.png">

4. Change application language to Spanish and submit
5. Change outgoing language to Spanish and submit 
6. See that application language is still in French 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/6979995/183316131-b86de87f-964b-49e8-9d19-edde9de740ac.png">

7. Go to `outgoing messages`: `/admin/#/message-queue/scheduled?page=1`
8. see errors 
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/6979995/183316105-2dd8d66e-003a-4805-9ea3-ffd99917cbae.png">

**Expected behavior**
User should be able to switch languages and changes should apply immediately
**Logs**
None

**Screenshots**
https://www.loom.com/share/80cc0f03fc1048158a8b4234e41e755e 
**Environment**
- Instance: (eg: alpha-cht.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, cht-conf, etc)
- Version: (eg: 3.16.0-beta.2.)

**Additional context**

**Comment by dianabarsan** [comment]
For the outgoing messages errors, do you have the message keys translated in the language that you switched to?

**Comment by dianabarsan** [comment]
Scheduled messages texts are generated on the fly, by the admin app, depending on the selected outgoing language.

**Comment by mrjones-plip** [comment]
> User should be able to switch languages and changes should apply immediately

In my testing, a users language takes precedence over the default settings in the admin UI.  So when I set my user's language in cht core via hamburger -> user settings -> Edit user profile:

![image](https://user-images.githubusercontent.com/8253488/183477487-e2d43db9-c38d-4c50-8c25-7b57b8b4a1a5.png)

This overrules what the App Admin -> Display -> Languages -> default app language.

I believe messages are always sent in default message language, regardless of the user preference that you're sending it to. 

Maybe this has changed such that before 3.16 it worked differently?

**Comment by ngaruko** [comment]
Thanks @mrjones-plip . It seems to behave the same on master, so I won't be an issue for this release in any case. I will look deeper into this.

**Comment by garethbowen** [comment]
@ngaruko Can you please try and reproduce this, or close it if you're happy with the responses above?

**Comment by ngaruko** [comment]
@garethbowen Seems to work as expected. Closing this . 👍
