### ISSUE TITLE
Icon labels on action buttons are not showing at the default dp for commonly used mobile devices

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7721]
Labels for icons on action buttons do not render their text if your device's horizontal resolution is 400px or less.  

A number of commonly used phones have a horizontal resolution of 720 with a default dp of 360.  With this default setting, the icon labels are not showing. If you change the dp to something higher, the labels become visible; however, changing this on every phone is onerous and it also makes the rest of the app text much smaller.  At a minimum, we should show the icon labels for the default resolution on these phones. 

https://github.com/medic/cht-core/issues/6394 addressed the same issue with **_action labels_** but [intentionally did not address](https://github.com/medic/cht-core/issues/6394) _**action button icon labels**_.  

Additional context in https://github.com/medic/config-ug-vht/issues/568 (private repo).

![screenrez](https://user-images.githubusercontent.com/10096985/183792267-45775e27-d5b1-42cc-b38e-9759eca3ec59.gif)

cc: @n-orlowski

**Comment by latin-panda** [comment]
The change: 
![Screen Shot 2022-08-10 at 9 50 01 am](https://user-images.githubusercontent.com/66472237/183799526-91b787b0-4f1f-4607-a24a-831800560ae7.png)

**Comment by tatilepizs** [comment]
**Config:** Default
**Environment:** Local with docker helper script
**cht-core version:** `7721-action-buttons-label`
**Platform:** Mobile App. Downloaded from play store **version 1.0.1**

## Android 10

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 103.0.5060.129

<details>
<summary>Reproducible on "master"</summary>

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184020986-07eb8a5a-476f-4d96-9965-9c580048d31f.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021156-c7536048-c7f4-43de-9ca0-6839df9361d9.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026160-b39a2c56-c639-4050-8b35-0183ff54329f.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021205-ee5aed15-ac55-4508-9030-cec72d485ed2.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021250-74fa5bea-5e3f-415e-a2f3-0a5a960a7ee3.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021280-fcd02c1a-0ffd-4f97-872f-572de8018a73.png">

</details>

<details>
<summary>Fixed on "7721-action-buttons-label"</summary>

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021596-21b04723-cde1-43c5-9731-275657b207ae.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026224-28180e66-8522-4391-a544-3b148c61cd91.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026253-fcab6377-38bb-42c7-b562-8b1430e22e3a.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021685-8042d26d-0ea8-4bcc-ae29-290dd14988e1.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021731-b3666961-214a-4c1d-b403-db8ced02c9c1.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184021789-0184582e-359d-4961-bfcf-9ffe0681d572.png">

</details>

## Android 5.1.1

**Phone:** Alcatel Onetouch 50560
**Android System WebView Version:** 95.0.4638.74

<details>
<summary>Reproducible on "master"</summary>

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024455-c36a2e94-3609-4bd5-b67c-d31665196d8f.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026603-9510cb03-0c36-4f1c-8ba7-37d420efb02e.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026632-8a1e07d4-d76f-491e-b950-8226dce3396d.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024543-d9ac96f8-b826-4d11-add1-b30dcfb762f0.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184025201-a57c6811-6129-48be-95fe-a4c4208d8ff9.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024631-799d01b2-aae2-43a2-8222-2fe7a81c8e51.png">

</details>

<details>
<summary>Fixed on "7721-action-buttons-label"</summary>

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024676-8169087f-2635-4991-81eb-4ada235200e5.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026646-89b25528-58b7-4555-aef0-94cc9a8fe05c.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184026665-fcc1d69a-244a-404d-8257-e3d875a11e9d.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024776-d4752f47-713a-4f2a-b920-1ede7138177c.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024807-6f9ad18f-9942-4063-a9a9-1d095c1352b1.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/184024853-93de432c-9cd3-463c-8636-e9996b765438.png">

</details>

**Comment by latin-panda** [comment]
@michaelkohn I wanted to add this ticket to the 3.17 milestone but I couldn't find it. I can create it if that's okay. Let me know :)

**Comment by mrjones-plip** [comment]
I created [the milestone](https://github.com/medic/cht-core/milestone/104) \o/
