### ISSUE TITLE
Places created with bulk upload don't have a primary contact

### ISSUE THREAD

**Issue by m5r** [medic/cht-core#7724]
**What feature do you want to improve?**
This is an improvement on the bulk user upload feature [that didn't make the cut](https://github.com/medic/cht-core/pull/7678#pullrequestreview-1049496847)

**Describe the improvement you'd like**
Have the newly created contact be the primary contact of the newly created place

**Additional context**
See this [slack thread](https://medic.slack.com/archives/C033W2BP7B9/p1656663380341799?thread_ts=1656539828.344089&cid=C033W2BP7B9) for more context as to why we're adding the feature.

For testing steps, please see https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/#spreadsheet-instructions, including the google sheets template in those docs.

**Comment by m5r** [comment]
@medic/quality-assurance This is ready for AT on branch `bulk-user-upload-primary-contact`, thanks a lot :rocket:

**Comment by tatilepizs** [comment]
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`

Using [this `.csv` file](https://github.com/medic/cht-core/files/9311610/Contact.Place.Templates.-.master.-.contact.chw.csv) the user and place were created successfully, but the contact created was not assigned as the "Primary contact" of the place. 

<details>
<summary>Created user</summary>

![image](https://user-images.githubusercontent.com/94494491/184226953-602a2909-0579-456b-820b-f36a257195bf.png)

</details>

<details>
<summary>Created place</summary>

![image](https://user-images.githubusercontent.com/94494491/184227295-7ad16f40-66e7-4526-b525-1084531517eb.png)


</details>



### Fixed on `bulk-user-upload-primary-contact`

Using [this `.csv` file](https://github.com/medic/cht-core/files/9311648/Contact.Place.Templates.-.branch.-.contact.chw.csv) the user and place were created successfully, and the contact created **was assigned as the "Primary contact"** of the place. 

<details>
<summary>Created user</summary>

![image](https://user-images.githubusercontent.com/94494491/184227776-3b9d09a1-5421-4ee9-9220-fef213f7f2d1.png)


</details>

<details>
<summary>Created place</summary>

![image](https://user-images.githubusercontent.com/94494491/184227852-eb03320a-7947-497c-a6d0-f4b46db8946a.png)

</details>

**Comment by mrjones-plip** [comment]
@m5r - I think you just need to merge this and close out the ticket?  If yes, please do so!

**Comment by latin-panda** [comment]
is this 3.17?

**Comment by mrjones-plip** [comment]
Yes - I've just added it to [3.17 milestone](https://github.com/medic/cht-core/milestone/104). Thanks!

**Comment by latin-panda** [comment]
Does it makes sense to add a [note in the docs](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/) about how the primary contact is defaulted with newly created places by bulk upload?

**Comment by mrjones-plip** [comment]
@latin-panda  - [good thinking](https://github.com/medic/cht-docs/pull/769)!
