### ISSUE TITLE
Remove support for old reports filter

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7726]
**What feature do you want to improve?**
[Reports filter was redesign](https://github.com/medic/cht-core/issues/7653) however the support for the old design is still there by enabling a permission to the user's role.

Approximately 3 months (1 quarter) after release, we need to evaluate and remove the support for the old design in the next CHT release. 

CC: @michaelkohn @n-orlowski

**Comment by garethbowen** [comment]
It's now 3 months later so this can be scheduled for removal. cc @michaelkohn

**Comment by latin-panda** [comment]
Hi @garethbowen, 
We discussed the topic during this week's CT meeting where @craig-landry, @n-orlowski and I considered to retire all feature flags related to UX Evolution in one go, when the main path of the UX Evolution is complete.
Part of this to avoid partners confusion and have a clear reference point when the old is retired. We'll align with @michaelkohn when he's back next week :)

**Comment by michaelkohn** [comment]
I've added a final step on the [roadmap ticket ](https://github.com/medic/cht-roadmap/issues/61) to keep track of this and will close this ticket.
