### ISSUE TITLE
Update `today` XPath function to not return current time

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7731]
**What feature do you want to improve?**
Currently we have a [custom implementation](https://github.com/medic/cht-core/blob/3d00f5ffc34510ce43dae26190ef41f57ea01154/webapp/src/js/enketo/medic-xpath-extensions.js#L86) of the `today` functionality that is identical to what is returned by the `now` function (the current date and time in the current timezone).  

**Describe the improvement you'd like**
As noted in this OpenRosa issue (https://github.com/enketo/openrosa-xpath-evaluator/issues/27), this behavior does not seem to follow the [ODK Spec](https://getodk.github.io/xforms-spec/#fn:today).  Unfortunately, the wording in the spec is a little confusing (to me at least) with regards to how it is actually supposed to behave.  However, both [openrosa](https://github.com/enketo/openrosa-xpath-evaluator/blob/01648be20c638f773467e299a9b65a050a409a97/src/openrosa-extensions.js#L302) and [javarosa](https://github.com/getodk/javarosa/blob/b72e0d48947c7f2b5c2d05ab9783ea9b8a259b04/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java#L333) have coalesced on a single interpretation of the spec where `now` returns the current date and time while `today` returns the current date with the time set to midnight of the current timezone.  I think we should remove our custom implementation of `today` and just use the one provided by OpenRosa.

As things stand today, we have a bunch of forms that are doing things like `date(floor(decimal-date-time(today())))` to get the start of today.  All this extra logic could be eliminated with the new implementation of `today`.  Any logic that relies on the current time being included in `today` can just update to the spec-compliant `now` function.  

As discussed in places like [here](https://github.com/medic/cht-core/issues/6345#issuecomment-1152800834), [here](https://github.com/medic/cht-core/issues/6345#issuecomment-1155647161), and [here](https://github.com/medic/cht-core/issues/6345#issuecomment-1201489355) the [Enketo uplift](https://github.com/medic/cht-core/pull/7256) is already going to cause subtle behavior changes in the behavior of `format-date` and `decimal-date` (both frequently used along with `today`). Changing `today` at the same time as these other changes would allow projects to implement proper fixes to their date handling once and for all instead of breaking some things now with the Enketo uplift and again later if we decide to switch to a spec-compliant version of `today`.  

**Describe alternatives you've considered**
One alternative would be to leave `today` alone and add a new custom function (e.g. `today-date`) that would return today's date without a time value.  This would be more passive and backwards compatible, but less spec-compliant.

**Additional context**
This has been an ongoing saga in CHT code for years:

- https://github.com/medic/cht-core/issues/1340
- https://github.com/medic/cht-core/issues/1878
- https://github.com/medic/cht-core/issues/5768

https://github.com/medic/cht-core/pull/5831 was the PR that added the current custom functionality for `today` to cht-core.

The big difference now is that both openrosa and javarosa seem to have agreed on an implementation (that is different from what we have).

**Comment by garethbowen** [comment]
@abbyad I think what @jkuester has proposed is the right solution, but given this is such a long standing issue and that you were involved in the [OG issue](https://github.com/medic/cht-core/issues/1878) would you mind chiming in?

**Comment by abbyad** [comment]
I agree that we should align to the [ODK XForm spec](https://getodk.github.io/xforms-spec/#fn:today), and that this is likely the best time to do so. That said, this will need revision of nearly all forms that use dates, so we should do everything possible to help app builders convert and verify their forms.

**Comment by garethbowen** [comment]
@jkuester Thinking about 4.0.0 scheduling, are you planning to work on this? If so, when do you think you'll have time to get it ready?

**Comment by jkuester** [comment]
@garethbowen sorry for the late response here!  My goal is to address this issue next week.  Let me know if you think that will be too late on the `4.0.0` timeline.

**Comment by garethbowen** [comment]
@jkuester I think that'll be ok. archv3 AT will take some time. Please let me know if there's anything I can do to help make progress on this.

**Comment by jkuester** [comment]
@garethbowen as I go though our default/standard config and evaluate if anything needs changed, I just wanted to run my criteria by you and see if it sounds correct.  Mostly it is pretty simple. For each place we are currently using `today`:

- If we do not actually care about the time value, keep using `today`
- If we do care about time, switch to use `now`

Where things become a bit complicated is when we have places where we are _currently_ using `today` along with `floor`.  (e.g. `date-time(floor(decimal-date-time(today())) + 3)` for setting a due date in 3 days.)  With the _new changes to the `today` function_ that remove the time data and only return today's date at midnight in the _current timezone,_ I initially thought I could just replace the previous statement with `date-time(decimal-date-time(today()) + 3)` and the `floor` call would no longer be necessary.  However, I realized that there is a subtle difference in behavior.  (I will use `now` in the following example as a stand-in for the old behavior of `today` just to avoid confusion between the old `today` and the new one.)  Since `decimal-date-time` returns the days since the Unix epoch (starting at midnight _UTC_) `floor(decimal-date-time(now()))` will actually return the days since the Unix epoch until today's date _at midnight UTC_.  `decimal-date-time(today())`, on the other hand, will return the days since the Unix epoch until today's date _at midnight in the current timezone_.

It seems like the new behavior of `decimal-date-time(today())` is what we would actually want in most cases.  The above due date example would become `date-time(decimal-date-time(today()) + 3)` (or even better, with the new `add-date` function it would be `add-date(today(), 0, 0, 3)`) which would return the date, 3 days from now, at midnight in the _current timezone_.  Let me know if this all sounds correct to you, or if you think we need to handle these combinations of `floor` and `today` in a different way!

**Comment by jkuester** [comment]
Edited forms:

### Default config
* app:
    * death_report
    * delivery
    * pnc_danger_sign_follow_up_baby
    * pnc_danger_sign_follow_up_mother
    * pregnancy
    * pregnancy_danger_sign
    * pregnancy_danger_sign_follow_up
    * pregnancy_home_visit
* contact:
    * clinic-create
    * distric_hospital-create
    * health_center-create
    * person-create
    * person-edit
 
### Standard config

* app:
    * death_confirmation
    * delivery
    * pregnancy
* collect:
	* child
* contact:
	* person-create
	* person-edit

**Comment by tatilepizs** [comment]
Thank you very much @jkuester for all the details about the changes, this is really helpful because that way I know where to focus the testing.

Using cht core version `7731_refactor_today` all the forms with changes worked as expected.

Tested forms for `default` config:

- district_hospital-create
- district_hospital-edit
- health_center-create
- health_center-edit
- clinic-create
- clinic-edit
- person-create
- person-edit
- pregnancy
  - with previous visits
  - with future visits
- pregnancy_home_visit
  - with miscarriage
  - with abortion
  - with still pregnant
- pregnancy_danger_sign
- delivery 
  - with mother alive and well
  - with mother dead
  - with child alive and well
  - with child dead
- pnc_danger_sign_follow_up_mother
- t_danger_signs_referral_follow_up_date
- death_report

Tested forms for `standard` config:

- district_hospital-create
- district_hospital-edit
- health_center-create
- health_center-edit
- clinic-create
- clinic-edit
- person-create
- person-edit
- pregnancy
- delivery
- death_confirmation

**Comment by garethbowen** [comment]
@jkuester I know I'm late to the party but I agree with your solution WRT timezones. Thanks!
