### ISSUE TITLE
Refactor tests for standard config tasks/targets to use cht-conf-test-harness

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7744]
**Describe the issue**
The current tests for tasks/targets in the standard config are written with an out-of-date version of `medic-conf-test-harness`.  These should be uplifted to use the latest version of `cht-conf-test-harness`.

**Describe the improvement you'd like**
There does not seem to be a super clean upgrade path here (it will take more than just updating some function names, etc).  These tests will need to be refactored to follow the latest patterns for testing tasks/targets.  (Can probably reference the default tests for examples.)

**Describe alternatives you've considered**
We could do nothing, but any additional tests that get added in here will just make it that much harder to uplift in the future. Also, none of the tests will have access to the latest cht-conf-test-harness features.

**Comment by latin-panda** [comment]
Also please upgrade to the latest cht-conf, it will require some fixes in the config's tests.

**Comment by garethbowen** [comment]
NB these tests are timezone dependant (fail in NZT, pass in UTC).

**Comment by jkuester** [comment]
FTR, this can be closed if we move forward with https://github.com/medic/cht-core/issues/8757

**Comment by jkuester** [comment]
https://github.com/medic/cht-core/issues/8757
