### ISSUE TITLE
If you're on a FR `beta.1` via `horti`, admin UI doesn't show `beta.2` 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7750]
The bug is that the feature we added in #7629 isn't working correctly.  

steps to reproduce:
1. use `horti` to [install a feature release beta](https://docs.communityhealthtoolkit.org/core/releases/feature_releases/#initial-fr-installation) that has  a later beta available.  Eg `3.16.0-FR-offline-user-replace-beta.2` has `3.16.0-FR-offline-user-replace-beta.3` avail after it.
2. go to admin GUI to ugprade
3. try to upgrade in admin GUI to Beta 3

Expected: I can upgrade in admin GUI
Actual: No Beta 3 is show for my current FR

Screenshot:

![image](https://user-images.githubusercontent.com/8253488/187285823-f8d2f842-00b5-4887-9e27-838cab514271.png)

**Comment by mrjones-plip** [comment]
@m5r - let's try and get the fix for this into 3.17. I think it's just a matter of getting the 3819974 commit as a PR against this issue toward `master` and push it through the PR/AT process!

**Comment by mrjones-plip** [comment]
cc @latin-panda

**Comment by m5r** [comment]
@medic/quality-assurance This is ready for AT on branch `7750-fix-FR-betas-in-admin`

To test this without having to be on an actual FR beta, you can spoof your CHT version by having a file named `version` in the `ddocs/medic/deploy_info` directory. The content of the file should be the version number you want to test with.  
Here is how I did it:
```sh
# cd into cht-core
touch ./ddocs/medic/deploy_info/version
echo "3.16.0-FR-offline-user-replace-beta.1\n" > ./ddocs/medic/deploy_info/version
# run the cht
```

**Comment by mrjones-plip** [comment]
Given the fix is in an existing FR AND that we've tried to fix at least once before, I think it'd be better to actually test this in situ.  @m5r - they just need to run this horty command (using their local docker based CHT's IP instead of `192-168-68-26`) and then it should show up in the admin UI because we fixed in in `beta.3`, correct?

```
COUCH_URL=https://medic:password@192-168-68-26.my.local-ip.co:8443/medic horti --local --install=3.16.0-FR-offline-user-replace-beta.3
```

**Comment by m5r** [comment]
Yes that is correct, the version `3.16.0-FR-offline-user-replace-beta.3` contains the fix and you should be able to upgrade to `beta.4` from the upgrade page

**Comment by m5r** [comment]
This issue is no longer needed, the bug has been fixed with the recent archv3 changes merged to master. See [commit b31ee370a9f055433dd26eb7229da8ceb3743d9e](https://github.com/medic/cht-core/commit/b31ee370a9f055433dd26eb7229da8ceb3743d9e#diff-dd6632d3132a5c703c567d9fd5c5d8dca9974b5b6d3103d33bc9dd8922758d49)
