### ISSUE TITLE
`enketo-transformer` is not compatible with npm 8

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7771]
**Describe the issue**
`enketo-transformer` fails to be installed when using npm 8. This is caused by the `libxslt` dependency not supporting npm 8. 
More details in this issue: https://github.com/albanm/node-libxslt/issues/87

**Describe the improvement you'd like**
With 4.0, we are changing the target node version to 16 and target npm version to 8. 
Since we only need a few resources from `enketo-transformer` (2 xslts and one js file), most convenient solution is to commit these directly in `cht-core`. 

**Describe alternatives you've considered**
- downgrade to npm 6 and node 14
- fix this upstream

**Comment by dianabarsan** [comment]
This is ready for AT on `7771-no-tranformer`. 

This is just a server-side change, where API generates the from HTML and form model based off of the form XML. 
I think a quick smoke test that forms work correctly would be ok, picking forms that needed changes from 3.x -> 4.x would be best. Maybe @jkuester has a good form to recommend.

**Comment by latin-panda** [comment]
@ngaruko and @tatilepizs that branch contains a fix for the e2e and it will unblock @elvisdorkenoo's PRs about breadcrumbs (to be released in 3.17). Thanks

**Comment by tatilepizs** [comment]
Using the branch `7771-no-tranformer` I tested the following forms and everything worked as expected.

- district_hospital-create
- district_hospital-edit
- health_center-create
- health_center-edit
- clinic-create
- clinic-edit
- person-create
- person-edit
- pregnancy
- pregnancy_facility_visit_reminder
- pregnancy_home_visit
- pregnancy_danger_sign_follow_up
- delivery
- pnc_danger_sign_follow_up_baby
- pnc_danger_sign_follow_up_mother
- death_report
- undo_death_report
- [cascading_select.xml](https://github.com/medic/cht-core/files/9552005/cascading_select.xml.zip)
- [enketo_widgets.xml](https://github.com/medic/cht-core/files/9552008/enketo_widgets.xml.zip)

**Comment by dianabarsan** [comment]
Merged to `master`.
