### ISSUE TITLE
Wdio E2E test suite broken on master

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7775]
**Describe the issue**
There are 5 e2e tests with are consistently failing: 
- `Submit Default Delivery Report open, submit and edit (no changes) default delivery form` (https://github.com/medic/cht-core/runs/8264779617?check_suite_focus=true#step:14:417)
- `Submit Default Delivery Report open, submit and edit default delivery form` (https://github.com/medic/cht-core/runs/8264779617?check_suite_focus=true#step:14:422)
- `Submit Photo Upload form submit and edit (no changes)` (https://github.com/medic/cht-core/runs/8264779617?check_suite_focus=true#step:14:447)
- `Submit Photo Upload form submit and edit (with changes)` (https://github.com/medic/cht-core/runs/8264779617?check_suite_focus=true#step:14:452)
- `Submit Z-Score form saves z-score values` (https://github.com/medic/cht-core/runs/8264779617?check_suite_focus=true#step:14:468)

All are failing with the same error: 
```
Can't call click on element with selector "reset-filters" because element wasn't found
[Chrome Headless 103.0.5060.134 linux #0-17] Error: Can't call click on element with selector "reset-filters" because element wasn't found
[Chrome Headless 103.0.5060.134 linux #0-17]     at implicitWait (/home/runner/work/cht-core/cht-core/node_modules/webdriverio/build/utils/implicitWait.js:34:19)
```

My hunch is that the reports filter redesign conflicted with another change that was using that selector. 

**Describe the improvement you'd like**
Fix the e2e tests. 

**Describe alternatives you've considered**
None.

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by m5r** [comment]
I have seen `Submit Default Delivery Report open, submit and edit default delivery form` failing quite a few times recently, should I reopen this issue or open a new one specifically for this failing test?

**Comment by dianabarsan** [comment]
This issue was strictly referring to one error: 

```
Can't call click on element with selector "reset-filters" because element wasn't found
[Chrome Headless 103.0.5060.134 linux #0-17] Error: Can't call click on element with selector "reset-filters" because element wasn't found
```

While your runs displays another: 

```
[Chrome Headless 107.0.5304.121 linux #0-21] element ("li[data-record-id="25baef77-f5a1-409f-a230-7d13ee291de9"]") still not displayed after 15000ms
```

Please open a different issue with the error that you are seeing now.

**Comment by m5r** [comment]
Thanks, I opened https://github.com/medic/cht-core/issues/7966
