### ISSUE TITLE
Bulk delete of reports redesign

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7778]
**Description**
[Related forum post.](https://forum.communityhealthtoolkit.org/t/experience-with-bulk-deleting-reports/2142)

The bulk delete of Reports tab is redesigned to improve the user experience. 

Extra considerations: 
- No actions (create, verify reports, etc) are allowed when there's at least 1 item selected. Just bulk delete. 
- The checkboxes are always visible as long as `can_bulk_delete_reports` permission is enabled. 
- The Search and filter are hidden when there is at least 1 item selected.
- All unselected checkboxes have gray border, including the "Select all" checkbox.
- One telemetry entry is added to count every time a user bulk delete reports.
- We decided that we would NOT use a feature flag for the bulk delete redesign:
    1. It's not a feature that CHWs use frequently (they rarely even have the reports tab)
    2. The purpose of Feature Flagging these UI changes is to give projects a way to roll out significant changes to large numbers of users over time rather than all at once. This is not likely a feature that falls into this category (see # 1).
    3. While the way we do bulk delete may change over time, we are definitely moving forward with our material design changes so we would not consider reverting back to the old (well, current) way of doing bulk delete. 
    4. It adds complexity to the codebase
    5. It gets even trickier since there are other UI feature flags
 - While in mobile view: if a user clicks outside the checkbox, then the reports open. If the user clicks "back", then the selection from before appears.
 - While in desktop view: if a user already has one item selected and then clicks outside the checkbox on a second item, this one will select (it won't open the report). If the user wants to see more details about the report, the user still have the option to expand the selected reports located on the right side.
 - We won't fully support responsive ui when user logins in a browser using the phone (no medic android app). See [this comment](https://github.com/medic/cht-core/issues/7778#issuecomment-1292995038) for more details.

Some additional clarification about this feature behaviour are:
- When the select all checkbox has a minus, and the user clicks on it
  - it should select all (up to 500 reports). 
- When that checkbox is blue and checked, and the user clicks on it 
  - it should deselect all. 
- If the user has too many reports (+500) then select all 
  -  it will only select up to 500 same as in master, 
  - and the select all checkbox is blue and checked, and the "clear selection" is available. 
- If the user scrolls more than +500 in the LHS, and "selects all" and then selects some more (for example 505 selected) then that's okay _for now_, same as master. (https://github.com/medic/cht-core/issues/7883)
 
<details>
<summary>The new version can be seen here</summary>
<img width="906" alt="Screen Shot 2022-09-22 at 10 05 14 am" src="https://user-images.githubusercontent.com/66472237/191649470-bfbac5b9-a5ed-45d1-be57-59fd63de52a2.png">
<img width="1777" alt="Screen Shot 2022-09-22 at 10 04 59 am" src="https://user-images.githubusercontent.com/66472237/191649481-4ae3414b-05b4-40b2-bea2-6e58dbcce056.png">
<img width="1766" alt="Screen Shot 2022-09-22 at 10 00 30 am" src="https://user-images.githubusercontent.com/66472237/191649490-7290aa74-9549-4ac5-ae10-fcdf75da8bc2.png">

</details>

<details>
<summary> The old version can be seen here </summary>

![Screen Shot 2022-09-12 at 4 34 02 pm](https://user-images.githubusercontent.com/66472237/189621264-2cfdef6e-7f60-4bc8-baf7-646aeccb5683.png)

![Screen Shot 2022-09-12 at 4 34 24 pm](https://user-images.githubusercontent.com/66472237/189621356-1ee1006c-7335-460c-afb8-38f3e875a0f9.png)

</details>

**Comment by latin-panda** [comment]
@n-orlowski @michaelkohn @tatilepizs I have updated the ticket's description with some more information. Please feel free to add or edit.

Next is:
- What are we documenting in cht-docs? 
    - For sure the new Telemetry entry. 
- What is the e2e test we want to cover?
    - I found [this one](https://github.com/medic/cht-core/blob/master/tests/e2e/default/reports/bulk-delete.wdio-spec.js) that we'll need to fix after the changes are complete. I'm wondering if this is enough or take the opportunity to add another escenario.

**Comment by latin-panda** [comment]
I've added 1 clarification item in the description of this ticket, based on our last conversation:

> No actions (create, edit, verify reports, etc) allowed when there is at least 1 item selected. User can just bulk delete.

**Comment by latin-panda** [comment]
We decided to not fully support responsive UI right now. 

<details>
<summary>Feature behaviour conflict details</summary>

[Conversation](https://medic.slack.com/archives/C02GME3BQE6/p1666799812670479).

If the user is in mobile view, selects some reports, then click on one to view. The user is redirected to the report and it opens the content.
Then the user rotate the phone to landscape, the phone might display desktop view if it’s big enough.
At this point the behaviour conflicts because the user is still in select mode and in desktop the user shouldn’t navigate to a report to see its content.
Because the user was looking at 1 report content, it can be confusing to suddenly not see the report content anymore but a list of selected report’s summary.

In the video, you can observe that after rotating the phone, only 1 report is visible (that one that was open), it’s not showing the summary of the other selected reports. At this point the url is about 1 report that the user was looking at ([https://……./reports/fef3a94b-c47f-4005-ba5a-524500bbd0f0](https://reports/fef3a94b-c47f-4005-ba5a-524500bbd0f0))… in desktop the url should be the root ([https://…….](https://reports/fef3a94b-c47f-4005-ba5a-524500bbd0f0)/reports/)

**Video:** 
https://user-images.githubusercontent.com/66472237/198192265-c31c2f78-2f5e-46b4-a330-885eceedc67d.mov

We’re okay in android app because the rotation is blocked, the user will always see portrait.
If the user is always in mobile or always in desktop, we’re okay…

The problem is when transitioning from mobile to desktop in this scenario

</details>

It's considered an edge case and we think it's OK to leave it as is, here's why:

- We don't think we've ever seen a CHW use their phone in landscape mode (at least while using the CHT... probably they do for YouTube)
- Even in landscape mode, it will probably show the mobile view (1 pane) anyway, depending on how big the phone is...right? (on my phone, it still just shows 1 pane in landscape)
- If the user is confused by this behavior, I imagine they would just rotate their phone upright again

Alternatively... we could disable viewing an individual report once you've selected at least one report (in iOS, you can't view an individual row once you've started selecting stuff)... but we're fine leaving the behavior as is based on the points above and observe user behaviour.

cc: @michaelkohn @n-orlowski @tatilepizs

**Comment by latin-panda** [comment]
Hey **Release Manager** from the future, and anyone else looking for screenshots of this feature. You can use these for documentation or release notes: 

<details>
<summary>Screenshots mobile view!!!!</summary>

![Screen Shot 2022-10-27 at 11 24 15 am](https://user-images.githubusercontent.com/66472237/198194653-22723f89-5ae5-41bb-9e54-e7a72f7ad94e.png)
![Screen Shot 2022-10-27 at 11 24 53 am](https://user-images.githubusercontent.com/66472237/198194659-429c0178-8d23-4281-834a-483aec59c08a.png)
![Screen Shot 2022-10-27 at 11 25 28 am](https://user-images.githubusercontent.com/66472237/198194661-20399c62-91fd-4ac6-90dd-498a11c2e322.png)
![Screen Shot 2022-10-27 at 11 28 27 am](https://user-images.githubusercontent.com/66472237/198194672-b544ef1c-4d2a-4139-a62d-50c856a3dd98.png)
![Screen Shot 2022-10-27 at 11 28 37 am](https://user-images.githubusercontent.com/66472237/198194677-dffefc1e-cda4-4086-bad3-58f523b15aae.png)

</details>


<details>
<summary>Screenshots desktop view!!!!</summary>

![Screen Shot 2022-10-27 at 11 26 25 am](https://user-images.githubusercontent.com/66472237/198194664-1cfbc640-da1a-4688-93e6-c2caf2c4bee8.png)
![Screen Shot 2022-10-27 at 11 26 46 am](https://user-images.githubusercontent.com/66472237/198194665-89318289-0955-46d8-9cc3-2b478c4db6e6.png)
![Screen Shot 2022-10-27 at 11 27 06 am](https://user-images.githubusercontent.com/66472237/198194668-d48a3a14-f54f-4827-b083-ffc97d4f79f6.png)
![Screen Shot 2022-10-27 at 11 27 33 am](https://user-images.githubusercontent.com/66472237/198194669-db7cf2a2-4901-455a-a179-8da59a8d26a0.png)
![Screen Shot 2022-10-27 at 11 27 46 am](https://user-images.githubusercontent.com/66472237/198194670-ed8aaa98-ff3b-4de2-ace6-f377f07143d6.png)
</details>

**Comment by latin-panda** [comment]
Some additional clarification about this feature behaviour are:
- When the select all checkbox has a minus, and the user clicks on it
  - it should select all (up to 500 reports). 
- When that checkbox is blue and checked, and the user clicks on it 
  - it should deselect all. 
- If the user has too many reports (+500) then select all 
  -  it will only select up to 500 same as in master, 
  - and the select all checkbox is blue and checked, and the "clear selection" is available. 
- If the user scrolls more than +500 in the LHS, and "selects all" and then selects some more (for example 505 selected) then that's okay _for now_, same as master.

**Comment by latin-panda** [comment]
Related tickets:
- [Selected reports not loading summary properly](https://github.com/medic/cht-core/issues/7868)
- [Improve experience of "select all" when there are +500 reports](https://github.com/medic/cht-core/issues/7883)

**Comment by latin-panda** [comment]
This is ready for AT [here](https://github.com/medic/cht-core/pull/7846). My recommendation is to do an exploratory test, during development I fixed a number of issues that you can see in the PR and in the recordings that I'm going to send in the CT channel.

**Comment by tatilepizs** [comment]
### Testing Details

- **Config:** Default
- **Environment:** Local with docker helper script 4.0
- **Platform:** WebApp
- **Browser:** Chrome
- **CHT version:** 7778-bulk-delete-redesign 

### Android 10

- **Phone:** Samsung Galaxy A01
- **Android System WebView Version:** 107.0.5304.105
- **CHT Android version: ** 1.0.1

### Android 5.1

- **Phone:** Ulefone Note 6
- **Android System WebView Version:** 100.0.4896.127

---

### Tests scenarios

<details>
<summary>Select and unselect reports - webapp</summary>

[video](https://user-images.githubusercontent.com/94494491/203156314-7a0415b0-8810-45cd-96a3-19bbb4d8e9ad.mov)

</details>

<details>
<summary>Select and unselect reports - Android 10</summary>

[video](https://user-images.githubusercontent.com/94494491/203161510-b6da0788-3633-4ef0-bce7-4328dfa86c68.mov)

</details>

<details>
<summary>Select and unselect reports - Android 5</summary>
</details>

<details>
<summary>Bulk delete reports - webapp </summary>

[video](https://user-images.githubusercontent.com/94494491/203163595-c567dd40-0e04-453c-bcab-6754a72e3aeb.mov)

</details>

<details>
<summary>Bulk delete reports - Android 10</summary>
</details>

<details>
<summary>Bulk delete reports - Android 5</summary>
</details>

<details>
<summary>Bulk delete reports with a filter selected- webapp</summary>

[video](https://user-images.githubusercontent.com/94494491/203165039-a3c4c44b-2905-45c2-afcd-e53a6c15e262.mov)

</details>

<details>
<summary>Bulk delete reports with a filter selected- Android 10</summary>
</details>

<details>
<summary>Bulk delete reports with a filter selected- Android 5</summary>
</details>

_...Testing in progress..._

**Comment by tatilepizs** [comment]
Hey @latin-panda, 
Something really weird is happening, the redesign is looking really good, but in the testing process, I saw that something was happening with the report that was deleted, if I logged in using another device and synced, I still was able to see the report that I deleted using the browser in my laptop.

Steps to reproduce:

- Using an offline user, login into two or more different devices (laptop and phone for example).
- Create a report.
- Sync in both devices to make sure you can see the report.
- Delete the report using the browser on the laptop.
- Sync again on the phone. You will still be able to see the deleted report.

<details>
<summary>Video attached, using branch 7778-bulk-delete-redesign</summary>

[video](https://user-images.githubusercontent.com/94494491/203590914-f21e188c-b779-44cf-b421-0597642e26da.mov)

</details>

I tried the exact same steps using master, and I don't see that behavior, the report was deleted in all the devices. 

<details>
<summary>Video attached, using master</summary>

[video](https://user-images.githubusercontent.com/94494491/203591693-0eba13f2-a1ba-41e3-aa2f-234d99ac7bc2.mov)


</details>

Could you check?

**Comment by latin-panda** [comment]
@tatilepizs very good finding and thanks for catching that. I was passing the wrong document that couch needs, I've fixed it in this [commit](https://github.com/medic/cht-core/pull/7846/commits/010fe63afd818d83707fb9328babcd6faea76ee4). When you have time, can you please have a look? 
Pura vida!

**Comment by tatilepizs** [comment]
It looks good Jenny, the sync between devices is working perfectly, thank you!
🚢 🚢

**Comment by latin-panda** [comment]
Thanks @tatilepizs, this has been merged in to our main branch
