### ISSUE TITLE
Feedback Documents - "Error when purging on device startup: Failed to fetch"

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#7782]
**Describe the bug**
This is a failure pattern in feedback documents in production instances.

For PiH, there are about 120 of these per month. 
```Error when purging on device startup: Failed to fetch```

Related, but much less common  (2/month) - there is also this pattern:
```Error when purging on device startup: Unexpected token < in JSON at position 0```

**Expected behavior**
Purging should be successful

**Environment**
- Instance: https://pih-malawi.app.medicmobile.org
- Browser: NA
- Client platform: NA
- App: webapp
- Version: 3.14.2

**Additional context**
https://github.com/medic/config-pih/issues/676

**Comment by garethbowen** [comment]
This error will go away or at least change significantly with upgrade to 3.15.0 as the [purging request no longer happens on startup](https://github.com/medic/cht-core/issues/7492). Looking at the code it appears as though purge errors will now not cause a feedback doc to get created.

**Comment by kennsippell** [comment]
Awesome.
