### ISSUE TITLE
Fix openrosa-xpath-evaluator issue with numbers using scientific notation

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7792]
**Describe the issue**
The current version of `openrosa-xpath-evaluator` (`2.0.11`) has [a bug](https://github.com/enketo/openrosa-xpath-evaluator/issues/159) where some numbers can cause an error because JS will represent them using scientific notation.

This issue should be fixed by https://github.com/enketo/openrosa-xpath-evaluator/pull/160.

**Describe the improvement you'd like**
We need to either upgrade our version of `openrosa-xpath-evaluator` to a new version with the fix (once one is released) or we need to add a patch into `webapp` to pull in the fix manually.

**Comment by garethbowen** [comment]
Ready for AT on `7792-fix-scientific-notation-bug`

Replication steps:

1. Configure the form below
2. In the app/browser, sync to get the new form
3. Try to fill in the form

Expected: The form loads, and can be submitted.
Actual: An error message is shown and a stack trace in the console (included below)

Test form:
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms">
  <h:head>
    <h:title>Enketo Widgets</h:title>
    <model>
      <itext>
        <translation lang="en">
          <text id="/enketo_widgets/intro:label">
            <value>My Lucky Number: <output value=" /enketo_widgets/my_calc "/></value>
          </text>
        </translation>
      </itext>
      <instance>
        <enketo_widgets id="enketo_widgets" prefix="J1!enketo_widgets!" delimiter="#" version="2022-09-19 00:00:00">
          <intro/>
          <my_calc/>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </enketo_widgets>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/enketo_widgets/intro" readonly="true()" type="string"/>
      <bind nodeset="/enketo_widgets/my_calc" type="string" calculate="floor(0.0000001)"/>
      <bind nodeset="/enketo_widgets/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
    </model>
  </h:head>
  <h:body class="pages">
    <input ref="/enketo_widgets/intro">
      <label ref="jr:itext('/enketo_widgets/intro:label')"/>
    </input>
  </h:body>
</h:html>
```

Stacktrace:

```
Error loading form. Error: ["FormLogicError: Could not evaluate: floor(0.0000001), message: Failed to execute 'evaluate' on 'XPathEvaluator': The string 'floor(1e-7)' is not a valid XPath expression."]
    at enketo.service.ts:288:33
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1648:18)
    at globalCallback (zone.js:1679:29)
```

Screenshot:

![Screenshot from 2022-09-20 08-06-03](https://user-images.githubusercontent.com/2064938/191107063-ad6100ee-28b2-4793-a7ac-c864383e482c.png)

**Comment by tatilepizs** [comment]
**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`
Using the test form provided in the [previous comment](https://github.com/medic/cht-core/issues/7792#issuecomment-1251493621) the error was shown when I tried to open it.

<details>
<summary>Screenshot attached</summary>

![image](https://user-images.githubusercontent.com/94494491/191316024-cd9a0af0-92ef-41d8-9eda-3580f74dca9d.png)

</details>

### Fixed on `7792-fix-scientific-notation-bug`
Using the test form provided in the [previous comment](https://github.com/medic/cht-core/issues/7792#issuecomment-1251493621) the form was opened and submitted successfully.

<details>
<summary>Screenshot attached</summary>

![image](https://user-images.githubusercontent.com/94494491/191318787-db45b9ba-28a4-43c3-8805-c06ada2c81d6.png)
![image](https://user-images.githubusercontent.com/94494491/191319011-e42d8b9b-2ad1-47bb-8b53-fa0ae179a31d.png)


</details>

**Comment by garethbowen** [comment]
Merged.
