### ISSUE TITLE
Arch v3 Docker Compose Logging: `local` instead of `json-file` and all containers have it

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7801]
**Describe the issue**
When reviewing the new [cht-core](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Aarchv3/docker-compose%2Fcht-core.yml) and [cht-couchdb](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Aarchv3/docker-compose%2Fcht-couchdb.yml) docker-compose files for archv3 currently published to staging.dev.medicmobile.org, I suggest we use `local` instead of `json-file` for `logging:driver:`.  the JSON one is [deprecated and does not have compression](https://docs.docker.com/config/containers/logging/configure/).  As is, this means the in the worst case we could have 50MB x 20 files x 6 containers = 6GB of uncompressed logs.  local uses compression by default.

As well, `cht-nginx` and `couchdb` containers don't have a `logging:` stanza. They should have one added to them, presumably mirroring what is on the other 4 containers.

**Describe the improvement you'd like**
oops - kinda spoiled it above - use `local` instead  and uniformly declare the `logging:` section for all containers ;)

**Describe alternatives you've considered**
There may have been intentional design decisions that I don't appreciate that mandate sticking with uncompressed  `json-file` driver.

**Comment by garethbowen** [comment]
I can't find any documentation about json-file being deprecated, in fact, it looks like it's the default driver. Can you link to the deprecation notice?

**Comment by mrjones-plip** [comment]
Yikes - thanks so much for checking my work @garethbowen! The link I originally cited was wrong, but I've since updated it above to be [this one](https://docs.docker.com/config/containers/logging/configure/) (this was [the wrong one](https://docs.docker.com/config/containers/logging/json-file/)). The correct one states:

> **Tip: use the “local” logging driver to prevent disk-exhaustion**
>
>    By default, no log-rotation is performed. As a result, log-files stored by the default [json-file logging driver](https://docs.docker.com/config/containers/logging/json-file/) logging driver can cause a significant amount of disk space to be used for containers that generate much output, which can lead to disk space exhaustion.
>
>    Docker keeps the json-file logging driver (without log-rotation) as a default to remain backward compatibility with older versions of Docker, and for situations where Docker is used as runtime for Kubernetes.
>
>    For other situations, the “local” logging driver is recommended as it performs log-rotation by default, and uses a more efficient file format. Refer to the [Configure the default logging driver](https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver) section below to learn how to configure the “local” logging driver as a default, and the [local file logging driver](https://docs.docker.com/config/containers/logging/local/) page for more details about the “local” logging driver.

Further down it lists `local` as follows (emphasis mine):

> `local` - Logs are stored in a custom format **designed for minimal overhead**.

So - re-reading this, I think it's fair to say that my original statement of "JSON one is deprecated" is a bit strong.  Thanks again!

All in all, it still seems if we don't have a reason to use JSON, seems like we should go to `local` instead. 

If do have a strong reason to go with JSON, we should be sure to enable compression in  [`json-file` logging driver](https://docs.docker.com/config/containers/logging/json-file/) with something like:

```yaml
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-50m}"
        max-file: "${LOG_MAX_FILES:-20}"
        compress: "true"
```

**Comment by garethbowen** [comment]
@Hareet I'd love your opinion here. Why did we pick `json-file` for logging? Were we just going with the default?

**Comment by Hareet** [comment]
Great catches @mrjones-plip !

We definitely want compress and added logging statements to the services mentioned.

@garethbowen I picked json thinking it would be the easiest for the community to ingest it into existing tools they may be familiar with. I'm cool with the change to default, and we could make it into an environment variable to have some flexibility

**Comment by mrjones-plip** [comment]
works for me! `compress` will default to `true` for `local`, but otherwise I believe all the arguments in the YAML apply directly to both `local` and `json-file`

**Comment by garethbowen** [comment]
Merged. AT will be done as part of the larger archv3 AT.
