### ISSUE TITLE
Call 'db.close' for ephemeral PouchDB objects to avoid memory leaks

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7813]
**Describe the performance issue**
Continuing from https://github.com/medic/cht-core/issues/6106, I observed a similar behavior using Node 16 when opening databases that don't exist - this will happen when sync-ing users on a server with no purging enabled. 

**Describe the improvement you'd like**
Close all dbs we open, even if they don't exist. 

**To Reproduce**
Steps to record the performance metrics:
1. Install CHT 4.0.0. Setup config so there is no purging and there are no purging databases (this is important). 
2. Start API and open inspector. 
3. Login as an offline user. 
4. Record API memory profile. 
5. Hit the sync button 10 times. 
6. Record API memory profile. 
7. Compare with previous profile and notice additional PouchDb objects: 
![image](https://user-images.githubusercontent.com/35681649/191674757-0de543e0-b567-4f52-a915-3242615311ec.png)

**Environment**
- App: api
- Version: 4.0.0

**Comment by dianabarsan** [comment]
This is ready for AT on `7813-close-non-existent-db`.

**Comment by tatilepizs** [comment]
Hi @dianabarsan,

I am trying to test this ticket but I am not sure if what I am seeing is the correct behavior, can you please confirm?

This is what I am seeing using `master` branch

![image](https://user-images.githubusercontent.com/94494491/192834073-8fb82b90-f2cd-4207-9e36-def24f8713fb.png)

This is what I am seeing using `7813-close-non-existent-db` branch

![image](https://user-images.githubusercontent.com/94494491/192833873-0fe3dae7-cbb9-4fee-b9a0-616fb03fc1ac.png)

**Comment by dianabarsan** [comment]
Hi @tatilepizs 

That's correct. 

If you look at the columns for PouchDB, in the first image you have:
- new 16
- deleted 13
- delta +3

In the second image: 
- new 15
- deleted 15
- delta 0

Delta = 0 = no lingering PouchDb objects = no memory leak.

**Comment by dianabarsan** [comment]
Merged to `master`.
