### ISSUE TITLE
CouchDb `/_utils` faulty redirect

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7815]
**Describe the issue**
Using self hosted 4.0 docker setup, accessing Fauxton through `https://localhost/_utils` will redirect to `https://_/_utils/`. 
Using `https://localhost/_utils/` works as expected.
This looks like it's a CouchDb internal redirect that doesn't match the host name correctly. 

**Describe the improvement you'd like**
Fix the redirect, so Fauxton is accessible with or without the trailing slash. 

**Describe alternatives you've considered**
Worse case scenario, we implement a redirect directly in the API router.

**Comment by dianabarsan** [comment]
I think this is the same as https://github.com/medic/cht-core/issues/7504 but happening on the new architecture.

**Comment by dianabarsan** [comment]
This is ready for AT on `7815-no-server-name`.

**Comment by tatilepizs** [comment]
**Environment:** Local with docker
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`

<details>
<summary>Video attached:</summary>

[video](https://user-images.githubusercontent.com/94494491/192567668-c8c8c40b-b1f8-4685-961f-d7a76b4c43cc.mov)

</details>

### Fixed on `7815-no-server-name`
<details>
<summary>Video attached:</summary>

[video](https://user-images.githubusercontent.com/94494491/192566447-dab38756-fe29-439e-a5ea-22064fa3f90e.mov)

</details>

**Comment by dianabarsan** [comment]
Merged into `master`.
