### ISSUE TITLE
CERTIFICATE_MODE=OWN_CERT fails with "cannot load certificate"

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7832]
**Describe the bug**
In Arch v3 you can specify you're bringing your own TLS cert by setting `CERTIFICATE_MODE` to `OWN_CERT`.  This will pass our test for [files being present](https://github.com/medic/cht-core/blob/69b478371091c0fa3cac00003e04af052050346d/nginx/ssl-install.sh#L97), but because we [hard code the path to the certs](https://github.com/medic/cht-core/blob/69b478371091c0fa3cac00003e04af052050346d/nginx/nginx.conf#L42), nginx fails to start.

**To Reproduce**
Steps to reproduce the behavior assuming no existing docker containers, volumes or networks:
1. Download the current `master` [docker compose file for core](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-core.yml): `curl -o docker-compose_cht-core.yml https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-core.yml`
2. Download the current `master` [docker compose file for couch](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-couchdb.yml): `curl -o docker-compose_cht-couchdb.yml https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-couchdb.yml`
3. Create an empty `cht-ssl` volume `docker volume create cht-ssl`
4. Populate the volume with valid local-host.ip certs:
   	```
	docker run --rm -d -v cht-ssl:/root --name deleteme alpine sleep 3600
	docker exec -it deleteme sh -c "wget -P /root/  http://local-ip.co/cert/server.pem"
	docker exec -it deleteme sh -c "wget -P /root/ http://local-ip.co/cert/chain.pem"
	docker exec -it deleteme sh -c "cat  /root/server.pem /root/chain.pem > /root/cert.pem"
	docker exec -it deleteme sh -c "wget -P /root/ http://local-ip.co/cert/server.key"
	docker exec -it deleteme sh -c "mv /root/server.key /root/key.pem"
	docker stop deleteme
   	```
5. Run `up` for compose, specifying your cert paths and `OWN_CERT` like so: `SSL_CERT_FILE_PATH=/etc/nginx/private/server.pem SSL_KEY_FILE_PATH=/etc/nginx/private/key.pem CERTIFICATE_MODE=OWN_CERT  COUCHDB_PASSWORD=password COUCHDB_USER=medic docker-compose -f docker-compose_cht-core.yml -f docker-compose_cht-couchdb.yml up`

**Expected behavior**
`cht-nginx` container start with a valid TLS cert

**Logs**
here's the output of `docker logs --follow cht-nginx`. Note that we see the script validation passes with `SSL certificate exists.` but then `nginx` internal checks faile with `cannot load certificate`

```   
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/ssl-install.sh
Running SSL certificate checks
CERTIFICATE MODE = OWN_CERT
SSL certificate exists.
Launching Nginx
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/10/04 23:13:08 [emerg] 1#1: cannot load certificate "/etc/nginx/private/cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/private/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/nginx/private/cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/private/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Screenshots**
NA

**Environment**
[This compose](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-core.yml) file from `master`

**Additional context**
I was able to get this to work by changing the mount point of `cht-ssl` for the `cht-nginx` service to point to where `nginx` is looking in the config.

```yaml
    volumes:
      - cht-ssl:/etc/nginx/private/
```

This yields a succsfull boot of `cht-nginx` service when we run the same compose command in step 4 and then run `docker logs --follow cht-nginx`:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                                   /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/ssl-install.sh
Running SSL certificate checks
CERTIFICATE MODE = OWN_CERT
SSL certificate exists.
Launching Nginx
/docker-entrypoint.sh: Configuration complete; ready for start up
192.168.68.26 - - [04/Oct/2022:23:43:13 +0000] "GET / HTTP/1.1" 200 420 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"  
```

**Comment by dianabarsan** [comment]
Thanks for reporting! This was an item on our discussion topics that never made it to the board, thanks for reporting!

**Comment by mrjones-plip** [comment]
This has been merged to master already, but I've moved this ticket to AT to follow up on at some point. 

quote from [this slack](https://medic.slack.com/archives/C02F2TAME90/p1665667713743029) thread:

> I think testing with `OWN_CERT` is already part of the 4.0 AT instructions, so I think it will be covered by the holistic AT/RT procedure. We could, eventually, not close the issue and set it to be AT-ed anyway, just to have the reference.

**Comment by tatilepizs** [comment]
Using [these](https://github.com/medic/cht-core/pull/7834#issuecomment-1268710481) steps to test everything worked as expected.
Thanks @mrjones-plip for all the details.

![image](https://user-images.githubusercontent.com/94494491/196553475-123c14b1-cc67-4a5b-9cb1-9bfa55af8527.png)
