### ISSUE TITLE
Permenently archive a 3.x version with Enketo uplift

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7836]
**Describe the issue**
In ~60 days the one version that users can easily test their forms with the enketo uplift (`7786-fix-report-label`) will disappear because branches are culled from `staging.dev.medicmobile.org` every 90 days and it was published ~30 days ago.  

As documented [by this forum post](https://forum.communityhealthtoolkit.org/t/september-2022-update-on-cht-core-4-0-0/2171/2?u=mrjones), this branch makes it trivial to use docker to set up and test your forms in preparation for `4.0`, but it will go away soon.

**Describe the improvement you'd like**
We should figure  permanent way to archive this so users can continue to use `medic-os` to easily test their forms in docker under CHT 3.x. While Arch v3/CHT 4 will have the enketo uplift (and supports docker) this is currently not stable and presents a larger effort for app devs to continue doing what they're doing today.

**Describe alternatives you've considered**
Can't think of any...

Related, new enketo_upgrade_3.x[ branch](https://github.com/medic/cht-core/tree/enketo_upgrade_3.x) is being worked on.

**Comment by dianabarsan** [comment]
How hard would it be to build a medic-os image with this branch pre-installed?

**Comment by mrjones-plip** [comment]
> How hard would it be to build a medic-os image with this branch pre-installed? 

Let the records show that I didn't suggest this!! (though I totally _thought_ this). :sweat_smile: 

I know @Hareet  was opposed to new `medic-os` builds, but maybe we can sneak one very last one in!?!?  I'll stay out of the way and defer to the experts.

**Comment by jkuester** [comment]
Just leaving a reminder that we should include documentation for whatever we decide to do in the upgrade guide: https://github.com/medic/cht-docs/pull/806

**Comment by jkuester** [comment]
https://github.com/medic/cht-core/tree/enketo_upgrade_3.x now contains what I believe to be the best Enketo code on `3.x`.

It includes the following cherrypicked on top of the `3.17.x` branch:

- 6345 - Uplift to enketo-core version 5.18.1 (#7256)
- 7694 - Add `add-date` XPath function (#7729)
- Update default/standard config forms to pass validation (#7739)
- Update openrosa-xpath-evaluator to fix scientific notation bug
- Remove custom today XPath function (#7821)
- Remove Simprints support

**Comment by mrjones-plip** [comment]
awesome!

**Comment by garethbowen** [comment]
@jkuester Can we close this issue off now or is there more to be done?

**Comment by jkuester** [comment]
:sob:  @garethbowen we have almost started!  

https://github.com/medic/cht-core/tree/enketo_upgrade_3.x is in good shape, but its build artifacts will be deleted after 90 days.  I am looking into possibly cutting a feature release from this branch to keep it around permanently.  That was my plan for this afternoon, but have kinda gotten bogged down in PRs...  Should be able to close this soon, though!

**Comment by jkuester** [comment]
This is ready for AT!  

I have created a new [feature release](https://docs.communityhealthtoolkit.org/core/releases/feature_releases/): https://github.com/medic/cht-core/releases/tag/3.17.0-FR-enketo-upgrade-beta.1

This should be a permanently accessible build of the code from https://github.com/medic/cht-core/tree/enketo_upgrade_3.x that anyone on `3.x` can upgrade their instance to use.

To install the feature release using horti run:

```sh
COUCH_URL=https://medic:password@192-168-1-13.my.local-ip.co:8443/medic horti --local --install=3.17.0-FR-enketo-upgrade-beta.1
```

The big things to test on this FR is just that the basic form functionality is still intact as well as new Enketo features also work:
- The latest default config from `master` has forms that use the `add-date` function. These should work on this FR.
- The [`enketo_widgets` form](https://github.com/medic/support-scripts/tree/master/forms/enketo_widgets) should work on this FR.

**Comment by jkuester** [comment]
To be clear, no changes have been made to the `main`/`master` branches on any of our repos for this issue.  After investigating various options, I concluded that a simple feature release following [this basic process](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_feature.md) was going to be sufficient to achieve what we wanted here!

**Comment by mrjones-plip** [comment]
> I concluded that a simple feature release following [this basic process](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_feature.md) was going to be sufficient to achieve what we wanted here!

simplicity FTW - love it!

**Comment by jkuester** [comment]
Closing as the updated version of Enekto will now remain available for testing on the feature release: https://github.com/medic/cht-core/releases/tag/3.17.0-FR-enketo-upgrade-beta.1
