### ISSUE TITLE
API credentials endpoint fails CouchDb secret is too short

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7840]
**Important**: This is a public repository. Anyone in the world can see what's posted here. If you are posting screenshots or log files, please **carefully examine them for** the presence of any kind of **protected health information** (PHI). Images or logs containing PHI _must_ be posted in fully-redacted form, with no visible PHI.

**Describe the bug**
The `/api/v1/credentials` fails with 500 when trying to set any credentials, when CouchDb secret is too short. 

**To Reproduce**
1. Set your CouchDb secret to be very short (mine was "monkey")
2. Try to PUT some credentials through API (/api/v1/credentials)
3. Response is 500

**Expected behavior**
Credentials should be stored even if the "secret" is short. 
We had the same issue before, when CouchDb secret was too long, but that was fixed before merging the PR. (https://github.com/medic/cht-core/pull/7577#discussion_r894495591)

**Logs**
```
2022-10-10 10:06:53 [33mWARN[39m: Non-numeric error code: ERR_CRYPTO_INVALID_KEYLEN 
2022-10-10 10:06:53 [31mERROR[39m: Server error: RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at /shared-libs/settings/src/index.js:51:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1) {
  [stack]: 'RangeError: Invalid key length\n' +
    '    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)\n' +
    '    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)\n' +
    '    at new Cipheriv (node:internal/crypto/cipher:243:3)\n' +
    '    at Object.createCipheriv (node:crypto:138:10)\n' +
    '    at /shared-libs/settings/src/index.js:51:29\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Promise.all (index 1)',
  [message]: 'Invalid key length',
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
} 
```

**Environment**
- App: api
- Version: 4.0.0

**Additional context**
Discovered while testing https://github.com/medic/cht-core/issues/7800

**Comment by dianabarsan** [comment]
This is ready for AT on `7840-allow-short-couch-secret`. 

Compose files:
- [Single-node Couch](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-couchdb.yml)
- [CHT](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-core.yml)

For AT, please experiment with various lengths `COUCHDB_SECRET` env variables and make sure that the new `/api/v1/credentials` doesn't throw errors when getting / putting credentials.

**Comment by lorerod** [comment]
@dianabarsan I'm trying to reproduce this issue on master:

- I'm using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml)
- I set my CouchDb secret running this command: `COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=a docker-compose -f cht-couchdb.yml -f cht-core.yml up`
- I put some credentials through the API: `curl -X PUT -H "Content-Type: text/plain" https://medic:****@my.local-ip.co/api/v1/credentials/user -d 'my pass'`
The response is 200
```
{
    "ok": true
}
```
I'm wondering if I'm trying to reproduce on the wrong branch.

**Comment by dianabarsan** [comment]
I just checked current master and I am getting the error, using exactly your curl command. 
My guess is that you're using an existent docker volume. Can you please do a `docker-compose down -v` and then an up, and try again? Thanks :)

**Comment by lorerod** [comment]
@dianabarsan thank you so much for your help, but I am missing something because I am not able to set the secret correctly. 

I put down the containers with `docker-compose down -v` and then up again with `COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=a docker-compose -f cht-couchdb.yml -f cht-core.yml up`

When querying my Couchdb with `curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret,` I'm getting a long secret (not` 'a'` as stated in the up command).

But when I do a `docker container inspect couchdb`, I get the environment values I put on the up command:
```
...
"Env": [
                "COUCHDB_USER=medic",
                "COUCHDB_PASSWORD=****",
                "COUCHDB_SECRET=a",
                "COUCHDB_UUID=",
                "SVC_NAME=couchdb",
                "COUCHDB_LOG_LEVEL=error",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GPG_COUCH_KEY=390EF70BB1EA12B2773962950EE62FB37A00258D",
                "COUCHDB_VERSION=2.3.1-1"
            ],
 ...
 ```
`COUCHDB_SECRET` is not the same as `couch_httpd_auth/secret`? If not, how do I set `couch_httpd_auth/secret` to the value I want?

**Comment by dianabarsan** [comment]
Hi @lorerod 

Can you please try removing the containers entirely and starting over: `docker-compose down -v --remove-orphans`?

**Comment by lorerod** [comment]
Ok, this is what I got.
Putting everything down:
![Captura de Pantalla 2022-10-19 a la(s) 08 53 11](https://user-images.githubusercontent.com/21312057/196684367-3deb2bc1-e9ac-42c4-a0ae-c12984ada5f4.png)

Up again:
![Captura de Pantalla 2022-10-19 a la(s) 08 55 04](https://user-images.githubusercontent.com/21312057/196684271-c50dee8c-60cd-4458-ab36-b61d0e76a24d.png)

Getting the secret with `curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret` I get `{"error":"not_found","reason":"unknown_config_value"}`

I log in with online user, and then output of `curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret` is a long secret, not `'a'`

**Comment by dianabarsan** [comment]
Oh, I see what is happening. The secret doesn't get set when using single-node, only when using clustered. 
Could you please change your test to use [clustered CouchDb](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb-clustered.yml) (also change the `COUCHDB_SERVERS` property to be `couchdb.1,couchdb.2,couchdb.3`) and try again?
I'll raise an issue to fix the secred not being set in single-node.

**Comment by lorerod** [comment]
Thank you @dianabarsan

**Reproduced on master**
**Environment**
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb-clustered.yml)
Browser: Firefox
Client platform: MacOS
App: api
Version: 4.0.0-alpha

**Steps to reproduce:**

- Set my CouchDb secret: 
Command:
`COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3 COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=a docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up`

- Obtain the secret:
Command:
`curl -k https://medic:****@my.local-ip.co/_node/_local/_config/couch_httpd_auth/secret`
Response:
`"a"`

-  Try to put some credentials through the API: 
Command:
`curl -X PUT -H "Content-Type: text/plain" https://medic:****@my.local-ip.co/api/v1/credentials/user -d 'my pass'`
Response:
`Server error`
<details>
<summary>The CHT-API log:</summary>

```REQ 46a2d2b8-4452-4ebb-9180-7ac757738811 172.22.0.1 medic PUT /api/v1/credentials/user HTTP/1.0
2022-10-19 15:19:09 WARN: Non-numeric error code: ERR_CRYPTO_INVALID_KEYLEN 
2022-10-19 15:19:09 ERROR: Server error: RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at /shared-libs/settings/src/index.js:51:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1) {
  [stack]: 'RangeError: Invalid key length\n' +
    '    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)\n' +
    '    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)\n' +
    '    at new Cipheriv (node:internal/crypto/cipher:243:3)\n' +
    '    at Object.createCipheriv (node:crypto:138:10)\n' +
    '    at /shared-libs/settings/src/index.js:51:29\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Promise.all (index 1)',
  [message]: 'Invalid key length',
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
} 
RES 46a2d2b8-4452-4ebb-9180-7ac757738811 172.22.0.1 medic PUT /api/v1/credentials/user HTTP/1.0 500 - 36.494 ms
```


</details>
<details>
<summary>The credentials are not stored:</summary>
<img width="905" alt="Captura de Pantalla 2022-10-19 a la(s) 12 31 52" src="https://user-images.githubusercontent.com/21312057/196737020-d9aab6d1-0697-4406-a052-a03dfda8933a.png">

</details>

**Comment by lorerod** [comment]
@dianabarsan to test the fix can you please also provide the `7840-allow-short-couch-secret` couchdb clustered compose file?

**Comment by lorerod** [comment]
**Fixed on branch (clustered couchdb)**
**Environment**
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-core.yml) and [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-couchdb-clustered.yml)
Browser: Firefox
Client platform: MacOS
App: api
Version: 4.0.0-7840-allow-short-couch-secret

**Steps to reproduce:**

- Set my CouchDb secret: 
Command:
`COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3 COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=a docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up`

- Obtain the secret:
Command:
`curl -k https://medic:****@my.local-ip.co/_node/_local/_config/couch_httpd_auth/secret`
Response:
`"a"`

-  Try to put some credentials through the API: 
Command:
`curl -X PUT -H "Content-Type: text/plain" https://medic:****@my.local-ip.co/api/v1/credentials/mykey -d 'my pass'`
Response:
`{"ok":true}`
<details>
<summary>The CHT-API log:</summary>

```
REQ a2a62387-14e7-4678-ae3a-eaea343b4608 172.23.0.1 medic PUT /api/v1/credentials/mykey HTTP/1.0
RES a2a62387-14e7-4678-ae3a-eaea343b4608 172.23.0.1 medic PUT /api/v1/credentials/mykey HTTP/1.0 200 11 68.941 ms
```

</details>
<details>
<summary>The credentials are stored:</summary>
<img width="1121" alt="Captura de Pantalla 2022-10-19 a la(s) 13 50 37" src="https://user-images.githubusercontent.com/21312057/196756084-f7424aae-e777-496f-834b-e6554909cffe.png">

</details>

**Observations:** Tested with different sizes for the value of `COUCHDB_SECRET` and for all I got the same result. Also tested with an empty string and a secret was generated for the instance.

**Comment by dianabarsan** [comment]
@lorerod , if you still have the setup running, could you also try to get the credential you set and check that you get `my pass`?

**Comment by dianabarsan** [comment]
Oh! I suppose there isn't a direct API. So sorry about that! 
I think the only way to actually use stored credentials is to use them in a workflow. Right now, only three workflows use stored credentials: `rapidpro`, `africas-talking` and `outbound`. 

I'm leaving it up to you whether to check if these still work. We have e2e tests that cover rapidpro and africas-talking.

**Comment by lorerod** [comment]
Yes, I would love to learn about the workflows. I'm going to check if `outbound` still works. Is [this](https://github.com/medic/support-scripts/tree/master/outbound-express) documentation going to help me get started? Thanks!

**Comment by dianabarsan** [comment]
Yup, that should work. You'll to need to change the network in the docker-compose file to match the network of CHT.

**Comment by lorerod** [comment]
Also, this branch would have pending tests with single-node compose files. Please let me know how you would like to manage that. Thanks

**Comment by dianabarsan** [comment]
The fix in this branch affects API, not in CouchDb. 
But I suppose that for 100% coverage, we'd want to test single node as well. I have a change pending for CouchDb, but it's still in review. We'd have to wait for that to be reviewed, tested, merged and then come back to this one.

**Comment by dianabarsan** [comment]
The fix for single node secret is ready for AT: https://github.com/medic/cht-core/issues/7850

**Comment by lorerod** [comment]
**Outbound push**
**Environment**
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-core.yml) and [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-couchdb-clustered.yml)
Browser: Firefox
Client platform: MacOS
App: api
Version: 4.0.0-7840-allow-short-couch-secret

**Steps:**
- Clone the [support-scripts](https://github.com/medic/support-scripts) repo
- cd into outbound-express
- npm ci
- run node server.js
- Configure Outbound: 
Add in `app-settings` transitions `"mark_for_outbound": true`
Add the `outbound` field to `app-settings`:
```
"outbound": {
    "express_config": {
      "relevant_to": "doc.type === 'data_record'",
      "destination": {
        "base_url": "http://192.168.100.62:3000",
        "path": "/",
        "auth": {
          "type": "basic",
          "username": "admin",
          "password_key": "Outbound"
        }
      },
      "mapping": {
        "patient_name": "doc.fields.patient_name"
      }
    }
  }
```

- Save the settings and upload the settings:
`cht --url=https://medic:****@my.local-ip.co compile-app-settings backup-app-settings upload-app-settings `

-  Put the credentials through the API: 
Command:
`curl -X PUT -H "Content-Type: text/plain" https://medic****@my.local-ip.co/api/v1/credentials/Outbound -d 'Outbound'`
Response:
`{"ok":true}`

<details>
<summary>The credentials are stored:</summary>

<img width="1064" alt="Captura de Pantalla 2022-10-19 a la(s) 16 59 07" src="https://user-images.githubusercontent.com/21312057/196799617-b84fa1f3-5ad9-47fc-b841-09da7dea4f9f.png">


</details>

- Create a death report.
- Confirm with logs:
Sentinel Log:
```
2022-10-19 20:27:17 DEBUG: About to send outbound request 
2022-10-19 20:27:17 DEBUG: {
  "url": "http://192.168.100.62:3000/",
  "body": {
    "patient_name": "Lorena"
  },
  "json": true,
  "timeout": 10000,
  "auth": {
    "username": "admin",
    "password": "*****",
    "sendImmediately": true
  }
} 
```

Express server log:
`{ patient_name: 'Lorena' }`

- Delete the Outbound credentials from medic-vault
- Create an undo death report
- Confirm with logs:
Sentinel log:
`2022-10-19 20:29:43 ERROR: Failed to push af16fdd1-8900-40ee-ad65-c6f45799c76f to express_config: Credentials for 'Outbound' have not been configured. See the Outbound documentation`

**Comment by lorerod** [comment]
> The fix in this branch affects API, not in CouchDb. But I suppose that for 100% coverage, we'd want to test single node as well. I have a change pending for CouchDb, but it's still in review. We'd have to wait for that to be reviewed, tested, merged and then come back to this one.

@dianabarsan We can come back to this issue now and test a single node. Please let me know which compose documents I should use. Thanks

**Comment by dianabarsan** [comment]
I've merged `master` into the branch and new images have been uploaded. To re-test, you can use the same docker-compose files, but you will have to clean your image cache before, because the image tags will be the same. 

Thanks!

**Comment by lorerod** [comment]
**Fixed on branch (single couchdb)**
**Environment**
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7840-allow-short-couch-secret/docker-compose%2Fcht-couchdb.yml)
Browser: Firefox
Client platform: MacOS
App: api
Version: 4.0.0-7840-allow-short-couch-secret

**Steps to reproduce:**

- Set my CouchDb secret: 
Command:
`COUCHDB_PASSWORD=**** COUCHDB_USER=admin COUCHDB_SECRET=4 docker-compose -f cht-couchdb.yml -f cht-core.yml up`

- Obtain the secret:
Command:
`curl -k https://admin:****@my.local-ip.co/_node/_local/_config/couch_httpd_auth/secret`
Response:
`"4"`

-  Try to put some credentials through the API: 
Command:
`curl -X PUT -H "Content-Type: text/plain" https://admin:password@192-168-100-62.my.local-ip.co/api/v1/credentials/singlecouch -d "singlecouch"`
Response:
`{"ok":true}`

<details>
<summary>The CHT-API log:</summary>

```
REQ 777129d4-d7d1-4902-a422-65f37efcbfd2 172.22.0.1 admin PUT /api/v1/credentials/singlecouch HTTP/1.0
RES 777129d4-d7d1-4902-a422-65f37efcbfd2 172.22.0.1 admin PUT /api/v1/credentials/singlecouch HTTP/1.0 200 11 31.663 ms
```

</details>
<details>
<summary>The credentials are stored:</summary>

<img width="1143" alt="Captura de Pantalla 2022-10-20 a la(s) 15 17 32" src="https://user-images.githubusercontent.com/21312057/197027513-e777e7b9-9f01-4bdb-8c8c-7f6ec7c51b18.png">

</details>

**Comment by dianabarsan** [comment]
Merged to `master`.
