### ISSUE TITLE
Refactor privacy policy controller to use template service

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7841]
**Describe the issue**
The privacy policy controller has a bunch of code that is duplicated in the recently added template service.

**Describe the improvement you'd like**
Refactor the controller to use the template service.

**Comment by garethbowen** [comment]
AT instructions: Ready for AT in https://github.com/medic/cht-core/pull/7908

This was a purely technical change so just make sure the Privacy Policies feature still works as expected, eg: upload a custom privacy policy, log in as a new user, accept the privacy policy, make sure it doesn't show again.

**Comment by lorerod** [comment]
**Environment:**  Local using branch `7841-refactor-privacy-controller`
**Phone:** Galaxy A01 Core
**Android Version:** 10
**Android System WebView Version:** 107.0.304.105
**WebApp:** Chrome

1. Add privacy policies in the `Admin Console`, under `Display` >` Privacy Policies`:
![Captura de Pantalla 2022-11-25 a la(s) 09 17 37](https://user-images.githubusercontent.com/21312057/203987169-ce357762-4c2a-4376-ac2c-13a6004dd997.png)

<details>
<summary>In log in page, privacy policy link shows:</summary>
- Mobile:

![Screenshot_20221125-092711](https://user-images.githubusercontent.com/21312057/203987481-ea301500-9e82-46ef-b153-9b3cab5e882a.jpg)

![Screenshot_20221125-092717](https://user-images.githubusercontent.com/21312057/203987694-d9555a47-65eb-43b9-adc7-0d6e39d44fa3.jpg)

- Webapp

![Captura de Pantalla 2022-11-25 a la(s) 09 24 50](https://user-images.githubusercontent.com/21312057/203987553-14783196-7cff-40fa-9c5a-a3ef7c665eb6.png)

![Captura de Pantalla 2022-11-25 a la(s) 09 25 49](https://user-images.githubusercontent.com/21312057/203987730-267ae840-e689-475d-9a51-0eb530cd11bb.png)

</details>

<details>
<summary>When logged in as offline user, privacy policy shows:</summary>
- Mobile

![Screenshot_20221125-093308](https://user-images.githubusercontent.com/21312057/203987651-f87124d5-b806-4dac-b83d-17df3768325c.jpg)

![Screenshot_20221125-091917](https://user-images.githubusercontent.com/21312057/203987774-50afc996-9d3f-421d-baa1-fb86a17626ed.jpg)

- Webapp

![Captura de Pantalla 2022-11-25 a la(s) 09 41 31](https://user-images.githubusercontent.com/21312057/203988238-625d5aaa-3b00-4147-9236-e824f4cf57ac.png)

![Captura de Pantalla 2022-11-25 a la(s) 09 41 39](https://user-images.githubusercontent.com/21312057/203988257-131afa73-4607-436f-bf53-feb5ed10eedd.png)
</details>

- When logged off and in again as offline user, privacy policy doesn't show again

**Comment by garethbowen** [comment]
Merged.
