### ISSUE TITLE
Add deep links to compose files for PRs

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7848]
**Describe the issue**
Right now for any given PR, it's not easy to find the docker compose file that CI builds and published to the `staging.dev.medicmobile.org` server

**Describe the improvement you'd like**
1. update the PR template to have place holder values for core, couch and couch cluster compose URLs. Something like:
   ```
   Compose files:
   * CORE_COMPOSE_URL_HERE
   * COUCH_SINGLE_COMPOSE_URL_HERE
   * COUCH_CLUSTER_COMPOSE_URL_HERE
   ```
1. Publish a GH Action that allows a user configurable search and replace of PRs. should support N key value search and replace terms. ~~[This action](https://github.com/juztcode/pr-updater) looks to be close to what we need already.~~ That repo is unlicensed (thus [all rights reserved](https://softwareengineering.stackexchange.com/a/276147)) - we should use [this how to](https://www.freecodecamp.org/news/build-your-first-javascript-github-action/) as a boilerplate. 
2. Update the [build CI](https://github.com/medic/cht-core/blob/master/.github/workflows/build.yml) to use the new action to replace the placeholder values with real URLs.

**Describe alternatives you've considered**
Manually do the same

**Comment by mrjones-plip** [comment]
working on [an action over here](https://github.com/medic/PR-search-replace) - currently very much a WIP!

**Comment by lorerod** [comment]
Testing details in [PR comment](https://github.com/medic/cht-core/pull/7860/#issuecomment-1305880947)
