### ISSUE TITLE
CouchDb Secret does not get set in single node

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7850]
**Describe the bug**
CouchDb Secret (`_config/couch_httpd_auth/secret`) does not get set when using single node CouchDb. 

**To Reproduce**
1. Download [cht-core yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [single node couch yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml)
2. Run `COUCHDB_PASSWORD=pass COUCHDB_SECRET=a docker-compose -f cht-couchdb.yml -f cht-core.yml up`
3. Run `curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret`
4. Get `{"error":"not_found","reason":"unknown_config_value"}`
5. Login as admin, and request the config again. Get a value.

**Expected behavior**
The CouchDb secret should be set to the value provided through the environment variable. 

**Environment**
- Instance: (eg: alpha.dev.medicmobile.org, etc)
- Browser: (eg: Firefox, Chrome, incognito mode, etc, which worked, which didn't)
- Client platform: (eg: Windows, MacOS, Linux)
- App: (eg: webapp, admin, sentinel, api, couch2pg, cht-conf, etc)
- Version: (eg: 2.15.0, 3.0.0, etc)

**Additional context**
This only affects single node couchdb. Discovered during AT of another issue (https://github.com/medic/cht-core/issues/7840#issuecomment-1283831754)

Thank you @lorerod !

**Comment by dianabarsan** [comment]
This is ready for review on `7850-single-node-secret`

- [clustered](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-couchdb-clustered.yml)
- [single](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-couchdb.yml)
- [core](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-core.yml)

**Comment by lorerod** [comment]
**Fixed on branch**
**Environment**
Client platform: MacOS
App: api
Version: 4.0.0-7850-single-node-secret

Steps:
1. Single node
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-couchdb.yml)
- Set my CouchDb secret running this command: `COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=a docker-compose -f cht-couchdb.yml -f cht-core.yml up`
- Get the secret with 
command:
`curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret` 
response
"a"
2. Cluster node
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-core.yml) and [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7850-single-node-secret/docker-compose%2Fcht-couchdb-clustered.yml)
- Set my CouchDb secret running this command: `COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3 COUCHDB_PASSWORD=**** COUCHDB_USER=medic COUCHDB_SECRET=b docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up`
- Get the secret with 
command:
`curl -k https://admin:pass@localhost/_node/_local/_config/couch_httpd_auth/secret` 
response
"b"

**Comment by dianabarsan** [comment]
Merged to `master`.
