### ISSUE TITLE
Add support for app developers easily starting local CHT 4 instances 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7852]
**What feature do you want to improve?**
Right now, it's easy for app developers to start one or more local instances of the CHT with [CHT Docker Helper](https://docs.communityhealthtoolkit.org/apps/guides/hosting/app-developer/#cht-docker-helper). There is no way for them to do this with CHT 4

**Describe the improvement you'd like**
An easy way for app developers to start one or more CHT 4.0 instance.  Ideally it would include the same feature set of the current helper:
* be based off env files to store key values for each local instance 
* install (and possibly renew!) [local-ip.co](http://local-ip.co/) certs 
* show the URL of the local instance, including Fauxton URL
* given it will be the normal way to do things, leverage the new [CHT upgrader](https://github.com/medic/cht-upgrade-service/)
* _optional:_ consider moving to node instead of bash and allowing folks to install it with `npm` like we do with `cht-conf` 

**NB -** All of the above is up to the engineer to decide how to implement. Ideally as simple as possible, with as little code from the old helper to KISS, be it bash or node. 

**Describe alternatives you've considered**
Manually launch developer instances via something like:
1. fetch the two compose files: `curl -s -o docker-compose_cht-core.yml https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-core.yml && curl -s -o docker-compose_cht-couchdb.yml https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3Amaster/docker-compose%2Fcht-couchdb.yml`
1. Run this docker-compose command to start everything up: `COUCHDB_PASSWORD=password COUCHDB_USER=medic docker-compose -f docker-compose_cht-core.yml -f docker-compose_cht-couchdb.yml up`

**Additional context**
There's a [forum post](https://forum.communityhealthtoolkit.org/t/cht-4-0-0-preperation-for-partners-alpha-docker-demo/2233) that talks about, and has a video demo, how to start the CHT without using env files or the CHT upgrade service.

A lot of the problems for how to do this are already solved:
* **Adding Local IP Co certs:** A prototype script was written to do this already.  It overwrites the self signed certs. Private slack thread [here](https://medic.slack.com/archives/C024KTGRW/p1665694500957199?thread_ts=1665435520.618599&cid=C024KTGRW), raw script [here](https://github.com/medic/cht-core/blob/mrjones-hack-local-ip-easy-add-script/scripts/add-local-ip-certs-to-docker-4.x.sh). We could set `CERTIFICATE_MODE=OWN_CERT` and the populate the certs [like this](https://github.com/medic/cht-core/pull/7834#issuecomment-1268710481).
* **detecting IP/URL for CHT:** We already do this in the current CHT Docker Helper by first [getting the host IP](https://github.com/medic/cht-core/blob/master/scripts/docker-helper/cht-docker-compose.sh#L24),  then [building up](https://github.com/medic/cht-core/blob/master/scripts/docker-helper/cht-docker-compose.sh#L45) the `*.my.local-ip.co` URL.
* **Env files:** Docker supports this natively, so if we have an env file like this:
   ```bash
   NGINX_HTTP_PORT=8080
   NGINX_HTTPS_PORT=8443
   CHT_COMPOSE_PROJECT_NAME=test-4.0.0
   DOCKER_CONFIG_PATH=/home/mrjones/Documents/MedicMobile/test-400
   COUCHDB_SECRET=foo-bar-bash-smang
   COUCHDB_DATA=/home/mrjones/Documents/MedicMobile/test-400/couch-test-400
   CHT_COMPOSE_PATH=/home/mrjones/Documents/MedicMobile/test-400
   COUCHDB_USER=medic
   COUCHDB_PASSWORD=password
   ```
   Assuming we have core and couch compose files in `/home/mrjones/Documents/MedicMobile/test-400` and we're in the the root directory of the [cht upgrader project](https://github.com/medic/cht-upgrade-service/) with the `docker-compose.yml` [file](https://github.com/medic/cht-upgrade-service/blob/main/docker-compose.yml) , we can just call: `docker-compose --env-file ~/Documents/MedicMobile/test-400 up`  and this just works.  We can make as many projects as we want that are peers to `test-400` directory to scale out running multiple instances locally.

**Comment by mrjones-plip** [comment]
@binokaryg  and I had a chat to bring him up to speed on this.  He's an avid user of the current CHT Docker Helper and Allies wanted to validate our approach with a highly technical domain expert.

His feedback was, first and foremost:

> "To be at least as easy as it's now"

Well said!  

Otherwise, his input was:

* wsl2 support? Possibly the `npm` native windows support would allow docker containers to work on LAN? Not a requirement, but possibility for improvement. Currently you need to do some firewall config to expose your docker container to the LAN and forward the ports.
* should support offline like it does today (DNS lookups aside)
* Be sure to denote that no upgrade path for 3.x -> 4.x (for now) 
* Apple M1 support?! Hopefully we get this for free with Arch v3 :pray:

**Comment by dianabarsan** [comment]
I want to mention is that the CHT upgrade service will only update the compose files names that match the attachment names from the staging ddoc (so `cht-core.yml` and `cht-couchdb.yml` or `cht-couchdb-clustered.yml`). 
We made this design decision to support partial upgrades, partial editing of docker-compose files and custom deployments for CouchDb.
