### ISSUE TITLE
Move non-additive actions from Action Bar to "More Options" menu "⋮"

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7872]
# Overview
As a part of our[ longer term goal ](https://github.com/medic/cht-roadmap/issues/61)to align with material design standards, the "Action Bar" at the bottom of the app (left hand side AND right hand side) will be removed. 

<img width="500" alt="Screenshot 2022-10-28 at 5 13 39 PM" src="https://user-images.githubusercontent.com/10096985/198734008-69f97efb-b075-44e3-9008-717b46bfbf97.png">

The actions currently in the Action Bar will move to other locations in the app:
- **Primary actions** (submitting a report, creating a new person, etc...) will move to a "[Floating Action Button](https://m3.material.io/components/floating-action-button/overview)"
- **Supplemental actions** (Edit, Delete, Export, etc...) will move to a "[More Options](https://m3.material.io/components/menus/guidelines#f7434719-f2f5-47e0-a5fe-61309ee37985)" style menu "`⋮`"

**This step of the evolution addresses moving some of the supplemental actions to a "More Options" menu.** 

**NOTE:** 
1. [#7778](https://github.com/medic/cht-core/issues/7778) updated the way Bulk Delete works, which included moving Bulk Delete related actions out of the Action Bar. That work was included in [4.1.0](https://github.com/medic/cht-core/milestone/105?closed=1).
2. The Action Bar will be temporarily available as [feature flag](https://docs.communityhealthtoolkit.org/apps/guides/updates/feature-flags/) by enabling the `can_view_old_action_bar` permission, and it should work the same as before this work.
3. When "More Options" is displayed and the user is looking at a record (report or contact) using a mobile device, the title should still display an ellipsis when the text is too long. 
4. No new capabilities are being _added_ as a part of this issue, but one existing capability is being _removed_. We are removing the capability to "Export" from the mobile (single pane) view of the Messages, Reports, and Contacts tabs.

# Reports Tab

**Summary:** Export, Edit, and Delete will be moved from their current location (LHS and RHS action bars in desktop) to the more options menu. If the user has the right permissions and user type (online vs. offline), the action will be shown in the menu. The action may show up in a disabled state if it is not applicable in the current view. "Export" will no longer be available in mobile view.

### Desktop view

<img width="700" alt="Screenshot 2022-10-28 at 7 56 36 PM" src="https://user-images.githubusercontent.com/10096985/198753011-5b8f87ba-f4df-4526-aab0-841fb3ab04df.png">

<details>
<summary>Scenarios and expected behaviors</summary>

Num | Scenario | Expected behavior
-- | -- | --
1 | - 1 or more reports are selected  | The "`⋮`" icon is not shown
2 | - No reports selected  <br>- At least one action is displayed | The "`⋮`" icon is shown to the right of the search bar
3 | - No reports selected <br>- No actions displayed (based on permissions/user type) | The "`⋮`" icon is not shown
4 | - User does not have the permission for exporting (`can_export_all` or `can_export_messages` permission) | Export option is not shown in the menu
5 | - User is an offline user <br>- User does not have the permission for exporting | Export option is not shown in the menu
6 | - User is an offline user <br>- User does have the permission for exporting | Export option is not shown in the menu
7 | - User has the permission for exporting <br>- User is an online user <br>- There are reports on the LHS   | Export is an option in the menu and is enabled
8 | - User has the permission for exporting <br>- User is an online user <br>- There are no reports on the LHS | Export is an option in the menu and is disabled
9 | - User does not have the permission for editing (`can_edit` and `can_update_reports` permissions) | Edit option is not shown in the menu
10 | - User has the permission for editing <br>- User has opened a report from the LHS <br>- The report's `content_type` is `xml` | Edit is an option in the menu and is enabled
11 | - User has the permission for editing <br>- No report is opened | Edit option is not shown in the menu
12 | - User does not have the permission for deleting (`can_edit` and `can_delete_reports` permissions) | Delete option is not shown in the menu
13 | - User has the permission for deleting <br>- User has opened a report | Delete is an option in the menu and is enabled
14 | - User has the permission for deleting <br>- No report opened | Delete option is not shown in the menu.
15 | - User is in "Edit" mode for a report | <br>- The "`⋮`" icon is shown <br>- Export option is shown <br>- Delete and Edit options are not shown.

</details>

### Mobile View - Reports list (LHS)

Action bar and More options when viewing the list of reports on the left hand side in mobile.

**Summary:** We are removing the "Export" capability from Mobile View. Since Edit and Delete are not relevant for LHS in Mobile View, the only change we are doing here is removing "Export" from the Action Bar. 

See design in Nicole's [comment](https://github.com/medic/cht-core/issues/7872#issuecomment-1302775162).

<details>
<summary>Scenarios and expected behaviors</summary>

Num | Scenario | Expected behavior
-- | -- | --
1 | - 1 or more reports are selected | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
2 | - No reports are selected <br>- At least one action will be displayed | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
3 | - No reports are selected <br>- No actions will be displayed (based on permissions/user type) | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
4 | - User does not have the permission for exporting | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
5 | - User is an offline user <br>- User does not have the permission for exporting | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
6 | - User is an offline user <br>- User does have the permission for exporting | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
7 | - User has the permission for exporting <br>- User is an online user <br>- There are reports | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
8 | - User has the permission for exporting <br>- User is an online user <br>- There are no reports | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
9 | - User does not have the permission for editing | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
10 | - User has the permission for editing <br> | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
11 | - User does not have the permission for deleting | The "`⋮`" icon is not shown and "Export" is not in the Action Bar
12 | - User has the permission for deleting <br> | The "`⋮`" icon is not shown and "Export" is not in the Action Bar

**Additional questions and answers**
- Do we show Export option in mobile even if they are an online user?
  - A/ We can hide it in mobile 
- Do we even show the Edit and Delete options in a disabled state on the reports list screen (since they are only valid once you have selected a report)?
  - A/ If no report is opened, then we hide the options of Edit and Delete.

</details>

### Mobile View - Selected report (RHS)

See design in Nicole's [comment](https://github.com/medic/cht-core/issues/7872#issuecomment-1302775162).

<details>
<summary>Scenarios and expected behaviors</summary>

Num | Scenario | Expected behavior
-- | -- | --
1 | - No actions will be displayed (based on permissions/user type) | The "`⋮`" icon is not shown
2 | - User does not have the permission for exporting | Export option is not shown in the menu
3 | - User is an offline user <br>- User does not have the permission for exporting | Export option is not shown in the menu
4 | - User is an offline user <br>- User does have the permission for exporting | Export option is not shown in the menu
5 | - User has the permission for exporting <br>- User is an online user <br> | Export option is not shown in the menu
6 | - User does not have the permission for editing | Edit option is not shown in the menu
7 | - User has the permission for editing <br> | Edit is an option in the menu and is enabled
8 | - User does not have the permission for deleting | Delete option is not shown in the menu
9 | - User has the permission for deleting <br> | Delete is an option in the menu and is enabled
10 | - User is in "Edit" mode | The "`⋮`" icon is not shown

</details>

# Contacts Tab

**Summary:** 
See design in Nicole's [comment](https://github.com/medic/cht-core/issues/7872#issuecomment-1302775162). "Export" will no longer be available in mobile view.
<details>
<summary>Scenarios and expected behaviors</summary>

Num | Scenario | Expected behavior
-- | -- | --
1 | - At least one action displayed | The "`⋮`" icon is shown to the right of the search bar
2 | - No actions displayed (based on permissions/user type) | The "`⋮`" icon is not shown
3 | - User does not have the permission for exporting (`can_export_all` or `can_export_contacts`) | Export option is not shown in the menu
4 | - User is an offline user <br>- User does not have the permission for exporting | Export option is not shown in the menu
5 | - User is an offline user <br>- User does have the permission for exporting | Export option is not shown in the menu
6 | - User has the permission for exporting <br>- User is an online user <br>- There are contacts on the LHS | Export is an option in the menu and is enabled
7 | - User has the permission for exporting <br>- User is an online user <br>- There are no contacts on the LHS | Export is an option in the menu and is disabled
8 | - User does not have the permission for editing (`can_edit` permision) | Edit option is not shown in the menu
9 | - User has the permission for editing <br>- User has opened a contact from the LHS | Edit is an option in the menu and is enabled
10 | - User has the permission for editing <br>- No contact is opened | Edit option is not shown in the menu
11 | - User does not have the permission for deleting | Delete option is not shown in the menu
12 | - User has the permission for deleting <br>- User has opened a contact from the LHS | Delete is an option in the menu and is enabled
13 | - User has the permission for deleting (`can_delete_contacts` permission) <br>- No contact is opened | Delete option is not shown in the menu
14 | - User is in "Edit" mode for a contact | - The "`⋮`" icon is shown <br>- Export option is shown <br>- Delete and Edit options are not shown.
15 | - User is online only OR user's facility_id is different from the selected contact's doc's _id | Edit is display
16 | - Selected contact have children contacts inside (nested contacts) | Delete is disabled

</details>

# Messages Tab

**Summary:** 
See design in Nicole's [comment](https://github.com/medic/cht-core/issues/7872#issuecomment-1302775162).

<details>
<summary>Scenarios and expected behaviors</summary>

Num | Scenario | Expected behavior
-- | -- | --
1 | - No actions will be displayed (based on permissions/user type) | The "`⋮`" icon is not shown
2 | - User does not have the permission for exporting | Export option is not shown in the menu
3 | - User is an offline user <br>- User does not have the permission for exporting | Export option is not shown in the menu
4 | - User is an offline user <br>- User does have the permission for exporting | Export option is not shown in the menu
5 | - User has the permission for exporting <br>- User is an online user but no messages available <br> | Export is an option in the menu and is disabled

</details>

# Tasks Tab

**Summary:** No changes

# Targets Tab

**Summary:** No changes

**Comment by n-orlowski** [comment]
## Reports tab:
### Mobile View - Reports list (LHS)
Stays the same; "Select" will be removed and only "Submit" will be left. No more actions.

### Mobile View - Selected report (RHS)
<img width="662" alt="Screen Shot 2022-11-03 at 4 03 41 PM" src="https://user-images.githubusercontent.com/59581790/199851445-ea157efd-3ee5-4578-b8ac-5c01ea1422ed.png">

## Contacts Tab
### Desktop View
<img width="763" alt="Screen Shot 2022-11-03 at 4 06 23 PM" src="https://user-images.githubusercontent.com/59581790/199851737-84fa7e54-59b9-407e-b674-2968b2f11746.png">

### Mobile View - Contact List
Stays the same, only action item is Add Household

### Mobile View - Selected place
<img width="588" alt="Screen Shot 2022-11-03 at 4 07 31 PM" src="https://user-images.githubusercontent.com/59581790/199851855-950f3b36-6c04-4ca8-987e-8ee7f3c9ea04.png">

### Mobile View - Selected contact
<img width="591" alt="Screen Shot 2022-11-03 at 4 07 44 PM" src="https://user-images.githubusercontent.com/59581790/199851886-4751f98f-625d-4e52-b783-ae4a508c8ae2.png">

**Comment by latin-panda** [comment]
Just pasting here to not loose the reference an [assessment](https://docs.google.com/spreadsheets/d/1l9noqxsrl0vAk1mmpbAKdVHIGBIwsujaqFGqX1SPqGk/edit?usp=sharing) I did about these actions.

**Comment by latin-panda** [comment]
I've added more info to this ticket description

**Comment by latin-panda** [comment]
Thanks @ngaruko, the # 1 is helpful and time-saving :) I think I can fix those by tomorrow.

About # 3 in your list (there's no # 2)

> - export reports
> - export contacts
> - export messages

I'm researching how to test the download, and I'll tag you for help.

> - review report

Do you mean this action? This one isn't part of this ticket, we're not moving it from the original place. 
![Screen Shot 2022-12-08 at 11 28 15 am](https://user-images.githubusercontent.com/66472237/206356649-b94b8dca-c4de-421b-92a1-860d3f89b0dc.png)

> - delete single report - selected

Yes, this one is planned for mobile, and not sure if it already exists in desktop (?) but shouldn't be difficult to add.

> `can_view_old_action_bar` permission and associated flag

This flag is to show the old action bar temporarily, we're going to remove the old designs in 2023 and no later I think. So, my advice is to not spend effort automating tests for the old design and fully focus on the new one. We can do `manual` testing for the old stuff. 

> state (visible/invisible/disabled) of : "⋮" icon, Export, Edit, Delete, depending on context/view and/or user (offline, permissions) as per specifications (both Desktop and mobile)

This one is okay, it's plenty of work and I'll reach out to you for help on achieving this one :)

**Comment by latin-panda** [comment]
The following images can be used for documentation or release notes.

<details>
<summary>Mobile device display</summary>

![Screenshot_20221208_154912_CHT Android](https://user-images.githubusercontent.com/66472237/206403990-d075cbbe-3a10-4b2a-a4bf-56b09b061687.jpg)
![Screenshot_20221208_155019_CHT Android](https://user-images.githubusercontent.com/66472237/206403999-2db73b7c-0ae1-4636-81a5-d4a8434749a1.jpg)
</details>

<details>
<summary>Desktop display</summary>

![Screen Shot 2022-12-08 at 3 59 03 pm](https://user-images.githubusercontent.com/66472237/206404029-28683688-c747-4365-b861-b15cf4c2ce71.png)
![Screen Shot 2022-12-08 at 3 58 51 pm](https://user-images.githubusercontent.com/66472237/206404037-8f7e1e11-d9ef-4dfc-86be-91d13252492b.png)
![Screen Shot 2022-12-08 at 3 58 39 pm](https://user-images.githubusercontent.com/66472237/206404038-2353f8f4-455a-492d-a8d0-e6480a2ff233.png)
![Screen Shot 2022-12-08 at 3 58 12 pm](https://user-images.githubusercontent.com/66472237/206404041-47c0a713-f22d-47c8-afed-27712b55c978.png)
</details>

**Comment by latin-panda** [comment]
Hi @ngaruko, that's correct. The Message tab only has Export, if the Export isn't displayed then the menu icon won't be displayed as well. That would correspond to this scenario:
![Screen Shot 2022-12-13 at 6 29 12 pm](https://user-images.githubusercontent.com/66472237/207306558-23bba387-e57a-4762-a3b7-ed3387b5f7e4.png)

Please feel free to edit the scenario in the ticket description, if it requires more detail :) Thanks!

**Comment by latin-panda** [comment]
This is ready for AT:

- [Main feature PR](https://github.com/medic/cht-core/pull/7965)
- [Export action e2e coverage](https://github.com/medic/cht-core/pull/7982)
- [Delete action e2e coverage](https://github.com/medic/cht-core/pull/7984)
- [Documentation of feature flag (permission)](https://github.com/medic/cht-docs/pull/914)

Recommendation:
- We added the [Angular Material library](https://material.angular.io/), it's like a bootstrap but with a different design concept. It shouldn't conflict with the existing UI, but please keep an eye. 
- The old action bar should work the same as before. There's [a known issue](https://github.com/medic/cht-core/issues/7973) that only affects the old action bar.

**Comment by michaelkohn** [comment]
>4. No new capabilities are being added as a part of this issue, but one existing capability is being removed. We are removing the capability to "Export" from the mobile (single pane) view of the Messages, Reports, and Contacts tabs.

@ngaruko it should actually be removed from _all_ tabs in mobile (single pane) view.

**Comment by latin-panda** [comment]
Thanks @ngaruko!! Great news 🎉  I'll leave the ticket open and we can close it once your PR is merged. This feature is ready for v4.2.0 🎉

**Comment by latin-panda** [comment]
[Remaining e2e tests were merged](https://github.com/medic/cht-core/pull/8056)
