### ISSUE TITLE
Switch staging server to a different URL due to breaking change

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7879]
**What feature do you want to improve?**
Right now we're using the same staging server for 3.x and 4.x which means the 4.0.0 upgrade is shown to everyone on 3.x, but clicking on the upgrade button will probably brick your server.

**Describe the improvement you'd like**
If we instead publish builds of 4.0.0 and later to a completely separate staging database, then they won't be shown to anyone currently running 3.x so users can't upgrade without doing manual steps.

**Describe alternatives you've considered**
Modifying the 3.x admin app to show some warning, but that requires everyone to upgrade to the latest 3.x release, which is unlikely.
Leaving it as is and communicating directly, but there are cases where people upgrade by accident without reading docs first.

**Comment by garethbowen** [comment]
@dianabarsan Please also review the medic-builds-repo PR. Then I _think_ all I need to do is...

1. manually create the `builds_4` db
2. merge the `medic-builds-repo` PR so CI uploads the DDOC
3. re-run the `cht-core` CI to publish to the new db
4. create a tag/branch off this branch so there's a second release to the new DB and set for AT

Have I missed anything?

**Comment by garethbowen** [comment]
AT instructions...

1. Do a fresh install of `7879-change-staging-server`
2. Go to the upgrade page
3. You should only see one possible upgrade because the market is now 4.x only
4. Upgrade to `7879-change-staging-server-test-upgrade` - this is an identical build just for ATing this change
5. Ensure the upgrade completes and you're now on the "new" branch

**Comment by mrjones-plip** [comment]
For step 1 for AT instructions, we're expecting QA to use the correct compose file which, in turn, will use the correct docker image from the `7879-change-staging-server` branch, right?  I don't think the build is passing so the compose files haven't been published - is that right?  I'm expecting them [here](https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A7879-change-staging-server/docker-compose%2Fcht-core.yml) for example (though I often fat finger that URL!)

**Comment by garethbowen** [comment]
@mrjones-plip The whole point of this issue is that they're on a different market, therefore a different URL. I've updated the instructions with a link to the yml to use. Thanks for the prompt.

**Comment by mrjones-plip** [comment]
aha - Thank you! (and uh, d'oh - obviously!) 

Note to self about two PRs that have the old URL hard coded will need to be updated:
* #7871
* #7860

**Comment by lorerod** [comment]
@garethbowen I'm getting `Error Fetching available versions` on the upgrade page. Do you know what might have gone wrong? Thanks!

![Captura de Pantalla 2022-11-04 a la(s) 10 50 12](https://user-images.githubusercontent.com/21312057/199989298-48d38520-28c9-4d97-ba45-e7b887b418fb.png)

**Comment by mrjones-plip** [comment]
Ok - I _think_ I've figured this out.  If we look at the XHR request on master for available builds, we see it's to the staging server here: `https://staging.dev.medicmobile.org/_couch/builds/`.  If we look at the XHR URL for this branch it's to `https://staging.dev.medicmobile.org/_couch/builds_4/`. These match up.

What does NOT match up is the CSPs for both.  On `master`, looking at the `connect-src` we have:

```
connect-src 'self' https://staging.dev.medicmobile.org/_couch/builds/ maps.googleapis.com; 
```

But then looking at this branch's value for  `connect-src` there is, are you ready?!  ONE character different.  The trailing slash!

```
connect-src 'self' https://staging.dev.medicmobile.org/_couch/builds_4 maps.googleapis.com; 
```

The tip for me was that the XHR request is blocked on the branch:

![image](https://user-images.githubusercontent.com/8253488/200084404-b2b98a86-6f44-462b-a5c1-f95c99e425d4.png)

Digging into the commit a bit, I THINK the issue is we changed the URL on [line 60](https://github.com/medic/cht-core/pull/7880/files#diff-ca6928872d8d920a49027473c56cc03e5da0d2d94519bb7a69ccf32d51436087L60) (note trailing slash):

```js
const BUILDS_DB = 'https://staging.dev.medicmobile.org/_couch/builds/'; // jshint ignore:line
``

to now being [based off the](https://github.com/medic/cht-core/pull/7880/files#diff-ca6928872d8d920a49027473c56cc03e5da0d2d94519bb7a69ccf32d51436087R159) `environment` object, which must be declared upstream with out the trailing slash based off what we're seeing in the XHR request:

```js
         environment.buildsUrl,
```

I'll wait to see what Gareth things next week!

**Comment by garethbowen** [comment]
@lorerod @mrjones-plip Reproduced this locally and it is indeed the trailing slash. I've fixed this now, so this is ready to AT again.

**Comment by mrjones-plip** [comment]
New build is good! retest steps below.

> You should only see **one** possible upgrade because the market is now 4.x only

Note: I saw **two** possible upgrades (see screenshots)


1. stopped all my containers: `docker kill $(docker ps -q)`
1. deleted the API image to ensure it downloads the latest one anew: `docker image rm 50ed41cc5c7d`
1. download this branch's core file,  master's couch and upgrade service's master: `wget https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml&&wget https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3A7879-change-staging-server/docker-compose%2Fcht-core.yml&&wget https://raw.githubusercontent.com/medic/cht-upgrade-service/main/docker-compose.yml`
1. run an instance: `CHT_COMPOSE_PROJECT_NAME=test5 COUCHDB_SECRET=test5 DOCKER_CONFIG_PATH=./ COUCHDB_DATA=./couchdb CHT_COMPOSE_PATH=./ COUCHDB_USER=medic COUCHDB_PASSWORD=password docker-compose up -d`
2. login and check that we see no 3.x version or branches and that we have to 4.x branches on the new market ( [screenshot](https://user-images.githubusercontent.com/8253488/200198794-6931792e-e0cd-4b09-8eab-49dea1938fe0.png))
3. initiate an upgrade to the test target branch ([screenshot](https://user-images.githubusercontent.com/8253488/200200008-c2e06498-4f7a-4d8c-a6e9-35e6bcaf6cbd.png))
4. upgrade completes ([screenshot](https://user-images.githubusercontent.com/8253488/200200055-5019e764-c0f9-4c59-bb95-ebcf668f16a4.png))
