### ISSUE TITLE
API and Sentinel crash in CHT 4 when HAProxy returns HTML

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7886]
**Describe the bug**

When Sentinel and API services query HAProxy for data and HAProxy returns HTML instead of JSON, they both crash.  

**To Reproduce**
1. get your two docker compose files:
   ```
   wget https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml
   wget https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb-clustered.yml
   ```
3. Start a cluster

   ```
   COUCHDB_SERVERS="couchdb.1,couchdb.2,couchdb.3" CHT_COMPOSE_PROJECT_NAME=test5 COUCHDB_SECRET=test5 DOCKER_CONFIG_PATH=./ COUCHDB_DATA=./couchdb CHT_COMPOSE_PATH=./ COUCHDB_USER=medic COUCHDB_PASSWORD=password docker-compose -f cht-core.yml -f cht-couchdb-clustered.yml up
   ```
1. ensure CHT is up in browser and with `curl`
   1.  browse to https://localhost/
   2. find IP of haproxy with `docker inspect -f '{{.Name}} - {{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q)` and run the command and see JSON of healthy medic DB: `curl -s http://medic:password@172.27.0.3:5984/medic | jq` 
1. check for a container names with `docker ps --format '{{.Names}}'|grep couchdb` and then stop a couch node: `docker stop deleteme_couchdb.2_1`
1. ensure CHT is DOWN in browser and with `curl`
   1.  browse to https://localhost/
   2. find IP of haproxy (`172.27.0.3` in this case) and run the command and see JSON of SAD medic DB: `curl -s http://medic:password@172.27.0.3:5984/medic | jq` 
1. start couch node again: `docker start deleteme_couchdb.2_1`
1. note that API and Sentinel have not restarted and will not restart. Online users see a full page spinner

**Expected behavior**
API and Sentinel stay do not crash when given HTML

**Logs**
[See AT ticket with extensive logs](https://github.com/medic/cht-release-testing/issues/208#issuecomment-1301449855).

**Screenshots**
NA

**Environment**
- Instance: local
- Browser: NA
- Client platform: NA
- App: sentinel, api, haproxy
- Version: 4.0.0 as of da1e1d8581392b8e9755019e3a814c85bc20a9df

**Additional context**
Solutions might be to be more defensive and not crash when getting HTML or [have HAProxy never return HTML](https://github.com/medic/cht-release-testing/issues/208#issuecomment-1301490674). 

Also related is this earlier [bug about the full page spinner](https://github.com/medic/cht-core/issues/7356).

**Comment by garethbowen** [comment]
@mrjones-plip Is this a duplicate now?

**Comment by mrjones-plip** [comment]
@garethbowen  - ah  - sure!  With the closing of #8179, agreed.

I still do like the idea of "be more defensive and not crash when getting HTML", but given we control both ends - fair enough!
