### ISSUE TITLE
3.x -> 4.x data migration container

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7891]
Create a container that contains all the necessary scripts, exposed as commands, that edit Couchdb node and database metadata, to facilitate data migration from a 3.x instance to a 4.x instance. 

The scripts should cover: 
- relocating a shard from one node to another (excluding actually moving data physically on disk?)
- relocating all shards from one node to another
- deleting a node

**Comment by dianabarsan** [comment]
This is ready for AT. The code is available in the repo linked above. 

We have put together documentation for users to follow to achieve this migration. This can be found in this PR: https://github.com/medic/cht-docs/pull/866
Since we want both the documentation and the software to be correct and easy to use, please follow the steps in the documentation to AT this migration container. 

There are a couple of test cases that should be covered: 
- migrating from medic-os to single node 4.x
- migrating from medic-os to multi node 4.x
Once the migration is successful:
- offline users should not need to resync data
- users should not get logged out
- all data should be available in the new instance

Additionally, it would be helpful if we could assess the quality of the instructions for users that might be hosting on AWS without using medic-os (if there are such cases), who might have CouchDb data saved in some type of AWS storage volumes. 

Ideally, we will improve the documentation to such quality that migrating is easy. Feedback is very welcome! 

Thanks!

**Comment by lorerod** [comment]
Hi @dianabarsan, this is still a work in progress, but I would like to write my findings when testing this.

1. For the scenario of "migrating from medi-os to single node 4.x" I was successful only with an online user using the chrome web app. With the two offline users I was connected using the phone to in the previous 3.x instance, I couldn't sync. It is because of the URL to connect to the instance. The ports differ from 3.x medic-os instance with port 8443 to 4.x instance with port 443. I tried changing the port to 8443 on 4.x cht-core.yml but could not make this work. For this it would be helpful to be prepare in advance.

1. I couldn't complete the scenario of "migrating from medic-os to multi-node 4.x" successfully. I will keep working on this. 

Other documentations suggestions we can discuss:
- The title doesn't send the message that after this set of instructions, your 3.x instance will be down, and you will end up with a 4.x instance. It is not only a "data migration" set of instructions. Maybe change the title or put a clear message about what to expect at the end of the instructions.
- Also, it would be helpful to have the two related documents so we can have everything in one place. https://github.com/medic/couchdb-migration/blob/main/README.md and https://github.com/medic/cht-docs/pull/866
- It would be interesting to have some rollback instructions in case the happy path doesn't work. To go back to your 3.x instance. It would give me more confidence. Do you think this could work? 
- In cht-docs also specifying where 3.x instances can be stopped would be helpful. 
- Env variables `COUCH_URL` and `CHT_NETWORK` must be set in two places. Before `2. Prepare CHT-Core 3.x installation for upgrading `and again before `5. Launch 4.x CouchDB installation`. Can we add this information to the documentation? Or to explain where you better use a clean env variables environment., not mix the two. 

I now @ngaruko is also working on this. He may have more suggestions.

**Comment by dianabarsan** [comment]
Thanks a lot for the feedback @lorerod . 

> It is not only a "data migration" set of instructions.

It's supposed to only cover data migration, though. The data migration does indeed require that no further changes are made in the data. What title would you suggest? 

> It would be interesting to have some rollback instructions in case the happy path doesn't work. To go back to your 3.x instance. It would give me more confidence. Do you think this could work?

I think the backup of data that we instruct to save should be enough of a "rollback". Do you think that would suffice? 

> Env variables COUCH_URL and CHT_NETWORK must be set in two places

Are you referring to the environment variables that you need to pass to CouchDb and to the migration tool?

**Comment by dianabarsan** [comment]
Thanks for the feedback @ngaruko 

For both 1 and 2:
- when making requests in docker containers, `localhost` is scoped to the docker container. not the host machine. 
- the easiest way to refer a URL to another docker container is to have them exist in the same docker network and use the service name in lieu of the IP, since docker knows how to resolve these internally
- when accessing a container through the docker network, the default exposed port will be used, instead of the one mapped to the host. For CouchDb, the default ports are 5984 and 5986. 
- 4.x CouchDb, the published docker-compose files do not map the clustering port (5986) to a host port, which is required for some of the clustering calls that are made by this code. 

For 1, your suggestion of checking `docker network ls` is good, how do you suggest we instruct further if there are multiple networks? 
For 2, do you think changing the example of the URL that needs to be passed would help?

**Comment by lorerod** [comment]
@dianabarsan 
> it's supposed to only cover data migration, though. The data migration does indeed require that no further changes are made in the data. What title would you suggest?

I will suggest maybe something like this:
**Main title:** Migration from CHT 3.x to CHT 4.x
**Subtitle:** Guide to migrate existent data from CHT 3.x to CHT 4.x
**Some observations before point 1:**  "This guide will present the required steps while using a migration helping tool, called `couchdb-migration`" and add "by the end of this guide you will end up with you CHT-Core 3.x instance down and CHT-Core 4.x ready to be used. 



> I think the backup of data that we instruct to save should be enough of a "rollback". Do you think that would suffice?

I think we can add some basics instructions of how to get your CHT 3.x up again with the backup data, or if there is some related documentations to link. 
Maybe in the same **Some observations before point 1:** we can add: "If you encounter any problems executing the instructions of this guide, you can always get your CHT 3X instance up again with the backup data. See link for further instructions."  Or put the instructions in the same guide at the end.
Please let me know if you think this is too much.



> Are you referring to the environment variables that you need to pass to CouchDb and to the migration tool?

I´m referring to the environment variables that I need you pass to the migration tool.

**Comment by dianabarsan** [comment]
Thanks a lot for the feedback @lorerod . I'll include it in the docs PR.

**Comment by lorerod** [comment]
@dianabarsan I saw that we have a new version for [couchdb-migration](https://github.com/medic/couchdb-migration). Can we continue testing this? 
cc: @ngaruko

**Comment by dianabarsan** [comment]
@lorerod correct, there is a new version that fixes some interactions between the migration software and self-hosted medic-os. If you continue testing, please use the new version. 
@mrjones-plip volunteered to help with testing as well.,

**Comment by lorerod** [comment]
**Environment:** MacOS 13.1 (22C65); Docker desktop 4.15.0 (93002)l; Docker engine: 20.10.21
**CHT 3.17:** Local using docker helper script from `master` branch
**config:** standard
**data**: upload data from [scalability test ](https://github.com/medic/cht-core/tree/master/tests/scalability)
**CHT 4.1.0:**  Local using docker compose files [cht-core.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb.yml)
**couchdb-migration branch:** `main`
**cht-docs branch:** `828-4.x-upgrade`
**Phones:** 
- Samsung Galaxy A01 with Android 10 and cht-android v1.0.4  
- Sony Xperia Z1 - Android 5.1.1 - cht-android v1.0.1

<details>
<summary>Migrating from medic-os to single node 4.x ✅ </summary>

-  I logged in 3.17 instance with users ac1 and ac2 on two different phones.
- Installed CHT data migration tool. Provided Couchdb data:
    - `export CHT_NETWORK=migration_project_medic-net`
    - `export COUCH_URL=http://medic:password@migration_project_haproxy_1:8443/`

- I got a count of the total number of documents in CHT:
    - Fauxton database information:
    
     ![3 17 database](https://user-images.githubusercontent.com/21312057/223754456-4dc2eae4-ab47-4422-bae1-050ff942956a.png)


    - Database info JSON:
    
    ```
    {
   "db_name":"medic",
   "purge_seq":"0-g1AAAAFTeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMeC5BkeACk_gNBViIDQbUNELXz8atNSgCSSfUEzUxSAKmzJ9LuBRC79xMw0wFkZjyRZh6AmHkfv9pEhiR5iIFZAB3kXo4",
   "update_seq":"12908-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYGNi24lGXpAAkk-xhSlPxKXUAKY2HKXXDpzQBpLQeplQZj9I8FiDJ0ACkgKrng5XbElS-AKJ8P1i5DUHlByDK74OVSxNU_gCiHOL20CwAQq5hMg",
   "sizes":{
      "file":139605696,
      "external":124984426,
      "active":120177061
   },
   "other":{
      "data_size":124984426
   },
   "doc_del_count":15,
   "doc_count":10545,
   "disk_size":139605696,
   "disk_format_version":7,
   "data_size":120177061,
   "compact_running":false,
   "cluster":{
      "q":8,
      "n":1,
      "w":1,
      "r":1
   },
   "instance_start_time":"0"
    }
    ```
- I prepare CHT-Core 3.x installation for upgrading:
    - Backup /srv/storage/medic-core/couchdb/data in the medic-os container (⚠️ This instruction is in two places in the doc: In 2. and 4. Please make clear in the doc when it is the right moment to do the backup.)
    - Stop the API by getting shell on your Medic OS container and calling /boot/svc-stop medic-api:
    ```
    Debug: Service 'medic-api/medic-api' exited with status 143
    Info: Service 'medic-api/medic-api' was stopped successfully
    Success: Finished stopping services in package 'medic-api`
    ```

    - Initiated view indexing by running `docker-compose run couch-migration pre-index-views 4.1.0`
    
- Save existent CouchDb configuration running `docker-compose run couch-migration get-env` obtained 

```
COUCHDB_USER=medic
COUCHDB_PASSWORD=password
COUCHDB_SECRET=70c9debff9c41e5a67d5fb189eef6575
COUCHDB_UUID=339a0dfa73ee09c85e08661b7923c0e9
```

- At this point, I stopped my 3.17 medic os container (⚠️ This may be only relevant for a local setup. If not, then please clarify this in the documentation)
- Launch 4.x CouchDb installation - Single node:
    - I downloaded 4.x single-node CouchDb docker-compose in a directory: 
    `curl -s -o ./docker-compose.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb.yml`
    - Copied the content of the 3.17 backup data in the new directory
    - Set the env variables:
    ```
    export COUCHDB_USER=medic
    export COUCHDB_PASSWORD=password
    export COUCHDB_SECRET=70c9debff9c41e5a67d5fb189eef6575
    export COUCHDB_UUID=339a0dfa73ee09c85e08661b7923c0e9
    export COUCHDB_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-single/data 
    ```
    - Updated couchdb-migration environment variables with the 4.x information:
    ```
    export COUCH_URL=http://medic:password@couchdb-single_couchdb_1:5984
    export CHT_NETWORK=cht-net
    ```
    - Started 4.1 couchdb with `docker-compose up -d` inside the new project directory
    - Checked couchdb up with `docker-compose run couch-migration check-couchdb-up` inside couchdb-migration directory:
     ```
    Creating couchdb-migration_couch-migration_run ... done
    Waiting for CouchDb to be ready...
    CouchDb is Ready
    ```
    -Executed `docker-compose run couch-migration move-node`:
    ```
    Creating couchdb-migration_couch-migration_run ... done
    Node moved successfully
    ```
   - Executed `docker-compose run couch-migration verify`:
    ```
    Creating couchdb-migration_couch-migration_run ... done
    Verifying _global_changes
    Database _global_changes has passed migration checks.
    Verifying _replicator
    Database _replicator has passed migration checks.
    Verifying _users
    Database _users has passed migration checks.
    Verifying medic
    Database medic has passed migration checks.
    Verifying medic-audit
    Database medic-audit has passed migration checks.
    Verifying medic-logs

      Views of database medic-logs are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Verifying medic-sentinel

      Views of database medic-sentinel are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Verifying medic-user-ac1-meta

      Views of database medic-user-ac1-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Verifying medic-user-ac2-meta

      Views of database medic-user-ac2-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Verifying medic-user-medic-meta

      Views of database medic-user-medic-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Verifying medic-users-meta

      Views of database medic-users-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
    Migration verification passed.
    ```
    - Started CHT-Core 4.1 using the same environment variables already set and setting also NGINX_HTTPS_PORT to match the port to the local  3.17 instance. (⚠️ This may be only relevant for a local setup. If not, then it should be an observation in the documentation.)
 
- Once the migration is successful:

✅ offline users should not need to resync data
✅ users should not get logged out
![Screenshot_20230308-112043](https://user-images.githubusercontent.com/21312057/223739778-2490816d-b6a9-4489-8136-b9c4d29d0039.jpg)


✅ offline users should be able to resync

![Screenshot_20230308-094359](https://user-images.githubusercontent.com/21312057/223739835-19bc1aae-dbad-4fa2-8ed5-1527840b06bd.jpg)


⚠️ All data should be available in the new instance. For this I compare the database information json and the fauxton database info. I found some differences in the json, but `doc_count` is the same in both instances.

- Fauxton database information:

![Captura de pantalla 2023-03-08 a la(s) 09 42 02](https://user-images.githubusercontent.com/21312057/223738013-3afb0d73-fcfe-4d5f-bf15-45dcc3bd67db.png)


- Database info JSON:
    ```
    {
    "db_name":"medic",
   "purge_seq":"0-g1AAAAFTeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMeC5BkWACk_v__vz8rkQGP2iQHIJkUD1SIXx3EzAaImfMJmJkAMrOeoJlJCiB19kTafQBi931i1D6AqCVgbiJDkjxEURYAyQVejg",
   "update_seq":"12968-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYGNj24VGXpAAkk-xhSjPwKXUAKY2HKfXApzQBpLQeptQAj9I8FiDJ0ACkgKrng5W7E1S-AKJ8P1i5C0HlByDK74OVqxJU_gCiHOL2qCwAZyNhbg",
   "sizes":{
      "file":10999512,
      "external":15122310,
      "active":10475588
   },
   "other":{
      "data_size":15122310
   },
   "doc_del_count":15,
   "doc_count":10545,
   "disk_size":10999512,
   "disk_format_version":7,
   "data_size":10475588,
   "compact_running":false,
   "cluster":{
      "q":8,
      "n":1,
      "w":1,
      "r":1
   },
   "instance_start_time":"0"
    }
    ```

</details>

**Comment by lorerod** [comment]
**Environment:** Same as in [previous](https://github.com/medic/cht-core/issues/7891#issuecomment-1460329935) comment with the difference in the couchdb compose file: [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb-clustered.yml)

<details>
<summary>Migrating from medic-os to clustered node 4.1.0 :x: </summary>

-  I logged in 3.17 instance with users ac1 and ac2 on two different phones.
- Installed CHT data migration tool. Provided Couchdb data:
    - `export CHT_NETWORK=migration_project_medic-net`
    - `export COUCH_URL=http://medic:password@migration_project_haproxy_1:8443/`
- I prepare CHT-Core 3.x installation for upgrading:
    - Stop the API by getting shell on your Medic OS container and calling /boot/svc-stop medic-api:
    ```
    Debug: Service 'medic-api/medic-api' exited with status 143
    Info: Service 'medic-api/medic-api' was stopped successfully
    Success: Finished stopping services in package 'medic-api`
    ```

    - Initiated view indexing by running `docker-compose run couch-migration pre-index-views 4.1.0`

    - Save existent CouchDb configuration running `docker-compose run couch-migration get-env` obtained 
    ```
    COUCHDB_USER=medic
    COUCHDB_PASSWORD=password
    COUCHDB_SECRET=56fd72c4c6a793516ee789624d667af1
    COUCHDB_UUID=bfeec72652b854f958ee52258d6a0e0b
    ```
    - Backup /srv/storage/medic-core/couchdb/data in the medic-os container (⚠️ This instruction is in two places in the doc: In 2. and 4. Please make clear in the doc when it is the right moment to do the backup.)
    
- At this point, I stopped my 3.17 medic os container (⚠️ This may be only relevant for a local setup. If not, then please clarify this in the documentation)
- Launch 4.x CouchDb installation - multi node:
    - I downloaded 4.x clustered CouchDb docker-compose in a directory: 
    `curl -s -o ./docker-compose.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb-clustered.yml`
    - Create the data folders:
    ```
     /couchdb/data/main
     /couchdb/data/secondary1
     /couchdb/data/secondary2
    ```
    - Copy the 3.17 backup data into the /couchdb/data/main directory
    - Set the env variables:
    ```
     export COUCHDB_USER=medic
     export COUCHDB_PASSWORD=password
     export COUCHDB_SECRET=56fd72c4c6a793516ee789624d667af1
     export COUCHDB_UUID=bfeec72652b854f958ee52258d6a0e0b
     export DB1_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/main
     export DB2_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/secondary1
     export DB3_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/secondary2
    ```
    - Updated couchdb-migration environment variables with the 4.x information ⚠️:
    ```
    export COUCH_URL=http://medic:password@couchdb-cluster-couchdb.1-1:5984
    export CHT_NETWORK=cht-net
    ```
    - Started 4.1 couchdb with `docker-compose up -d` inside the new project directory
    ```
    cd ~/couchdb-cluster/ 
    docker-compose up -d
    Creating couchdb-cluster_couchdb.2_1 ... done
    Creating couchdb-cluster_couchdb.1_1 ... done
    Creating couchdb-cluster_couchdb.3_1 ... done
    ```
    - Checked couchdb up with `docker-compose run couch-migration check-couchdb-up` inside couchdb-migration directory:
     ```
    Creating couchdb-migration_couch-migration_run ... done
    Waiting for CouchDb to be ready...
    CouchDb is Ready
    ```
    - ⚠️ I tried using `<docker-service-name>` (in my case `couchdb.1`) in COUCH_URL as in the doc, but checking couchdb is up. I got:
    ```
    Waiting for CouchDb to be ready...
    ports:
      - "${COUCH_PORT}:5984"
      - "${COUCH_CLUSTER_PORT}:5986" An unexpected error occurred Error: CouchDb is not up after 100 seconds.
    at checkCouchUp (/app/src/check-couch-up.js:36:11)
    at async /app/bin/check-couchdb-up.js:10:5
    ```
    - Generate the shard distribution matrix and get instructions for final shard locations.
    ```
    shard_matrix=$(docker-compose run couch-migration generate-shard-distribution-matrix)
    docker-compose run couch-migration shard-move-instructions $shard_matrix

    Move <mainNode-Path>/shards/00000000-1fffffff to <couchdb@couchdb.1-path>/shards/00000000-1fffffff
    Move <mainNode-Path>/.shards/00000000-1fffffff to <couchdb@couchdb.1-path>/.shards/00000000-1fffffff
    Move <mainNode-Path>/shards/20000000-3fffffff to <couchdb@couchdb.2-path>/shards/20000000-3fffffff
    Move <mainNode-Path>/.shards/20000000-3fffffff to <couchdb@couchdb.2-path>/.shards/20000000-3fffffff
    Move <mainNode-Path>/shards/40000000-5fffffff to <couchdb@couchdb.3-path>/shards/40000000-5fffffff
    Move <mainNode-Path>/.shards/40000000-5fffffff to <couchdb@couchdb.3-path>/.shards/40000000-5fffffff
    Move <mainNode-Path>/shards/60000000-7fffffff to <couchdb@couchdb.1-path>/shards/60000000-7fffffff
    Move <mainNode-Path>/.shards/60000000-7fffffff to <couchdb@couchdb.1-path>/.shards/60000000-7fffffff
    Move <mainNode-Path>/shards/80000000-9fffffff to <couchdb@couchdb.2-path>/shards/80000000-9fffffff
    Move <mainNode-Path>/.shards/80000000-9fffffff to <couchdb@couchdb.2-path>/.shards/80000000-9fffffff
    Move <mainNode-Path>/shards/a0000000-bfffffff to <couchdb@couchdb.3-path>/shards/a0000000-bfffffff
    Move <mainNode-Path>/.shards/a0000000-bfffffff to <couchdb@couchdb.3-path>/.shards/a0000000-bfffffff
    Move <mainNode-Path>/shards/c0000000-dfffffff to <couchdb@couchdb.1-path>/shards/c0000000-dfffffff
    Move <mainNode-Path>/.shards/c0000000-dfffffff to <couchdb@couchdb.1-path>/.shards/c0000000-dfffffff
    Move <mainNode-Path>/shards/e0000000-ffffffff to <couchdb@couchdb.2-path>/shards/e0000000-ffffffff
    Move <mainNode-Path>/.shards/e0000000-ffffffff to <couchdb@couchdb.2-path>/.shards/e0000000-ffffffff
    ```
   - Manually move the shard files to the correct location
   - Change metadata to match the new shard distribution
    ```
    docker-compose run couch-migration move-shards $shard_matrix
    Shards moved successfully
    ```
    - docker-compose run couch-migration verify
    ```
    ... Migration verification passed.
    ```
    - Started CHT-Core 4.1 using `curl -s -o ./docker-compose.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml` and `COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3 docker-compose up` and I got this errors on the log:
    ```
    api_1          | Error: Cluster not ready
    api_1          |     at checkCluster (/shared-libs/server-checks/src/checks.js:94:11)
    api_1          |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
    api_1          |     at async couchDbCheck (/shared-libs/server-checks/src/checks.js:135:7)
    api_1          |     at async /api/server.js:23:5
    haproxy_1      | <150>Mar  9 18:12:11 haproxy[25]: 172.20.0.8,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',222,-1,-,'-'
    sentinel_1     | StatusCodeError: 503 - "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to 
    handle this request.\n</body></html>\n"
    sentinel_1     |     at new StatusCodeError (/sentinel/node_modules/request-promise-core/lib/errors.js:32:15)
    sentinel_1     |     at Request.plumbing.callback (/sentinel/node_modules/request-promise-core/lib/plumbing.js:104:33)
    sentinel_1     |     at Request.RP$callback [as _callback] (/sentinel/node_modules/request-promise- 
   core/lib/plumbing.js:46:31)
    sentinel_1     |     at Request.self.callback (/sentinel/node_modules/request/request.js:185:22)
    sentinel_1     |     at Request.emit (node:events:513:28)
    sentinel_1     |     at Request.<anonymous> (/sentinel/node_modules/request/request.js:1154:10)
    sentinel_1     |     at Request.emit (node:events:513:28)
    sentinel_1     |     at IncomingMessage.<anonymous> (/sentinel/node_modules/request/request.js:1076:12)
    sentinel_1     |     at Object.onceWrapper (node:events:627:28)
    sentinel_1     |     at IncomingMessage.emit (node:events:525:35) {
    sentinel_1     |   statusCode: 503,
    sentinel_1     |   error: '<html><body><h1>503 Service Unavailable</h1>\n' +
    sentinel_1     |     'No server is available to handle this request.\n' +
    sentinel_1     |     '</body></html>\n'
    sentinel_1     | }
    haproxy_1      | <150>Mar  9 18:12:12 haproxy[25]: 172.20.0.7,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',222,-1,-,'-'
    api_1          | StatusCodeError: 503 - "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle 
    this request.\n</body></html>\n"
    ```
    - The instance is not working.
</details>

@dianabarsan I wasn't able to migrate successfully. Am I missing something? 
@ngaruko Did you try this also? Can you share your experience?

**Comment by dianabarsan** [comment]
Hi @lorerod 

Thanks a lot for the extensive detail that you've provided! This is of great value! 

>  I tried using <docker-service-name> (in my case couchdb.1) in COUCH_URL as in the doc, but checking couchdb is up. I got:

It seems you have unlocked yourself, what URL did you end up using?

> Started CHT-Core 4.1 using curl -s -o ./docker-compose.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml and COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3 docker-compose up and I got this errors on the log:

Can you please try: 
- stopping the previous CouchDb build, that you used for the migration
- start CHT 4.1 using both docker-compose files

My guess is that there is some docker network mismatch and haproxy can't reach the pre-existent CouchDb. 
Please make sure that you're using the same environment variables when you start 4.1 CouchDb along with the other services.

**Comment by lorerod** [comment]
> It seems you have unlocked yourself, what URL did you end up using?
> 
> >
@dianabarsan I end up using COUCH_URL=http://medic:password@couchdb-cluster-couchdb.1-1:5984

**Comment by dianabarsan** [comment]
Hi @lorerod 

I'll try to replicate this locally.

**Comment by dianabarsan** [comment]
Hi @lorerod 

I've made an update to the documentation to add an additional step to the migration for clustered. 
It involves running an additional command after the `move-shards` command. 

For some reason, my haproxy process had trouble starting up every time, but it restarted itself automatically after 1 minute. 
```
rsyslog startup failure, child did not respond within startup timeout (60 seconds)
```
This doesn't have anything to do with the migration, but it can be a nuisance. 

Could you please try to integrate the node deletion step and wait for 1 minute after starting the 4.1 instance to check if it works? 

Thanks a lot!

**Comment by lorerod** [comment]
Hi @dianabarsan 
It worked! I will leave the details tomorrow but I wanted to let you know.

**Comment by lorerod** [comment]
**Environment:** Same as in [previous](https://github.com/medic/cht-core/issues/7891#issuecomment-1460329935) comment with the difference in the couchdb compose file: [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb-clustered.yml)

<details>
<summary>Migrating from medic-os to clustered node 4.1.0 ✅ </summary>

-  I logged in 3.17 instance with users ac1 and ac2 on two different phones.
- Installed CHT data migration tool. Provided Couchdb data:
    - `export CHT_NETWORK=migration_project_medic-net`
    - `export COUCH_URL=http://medic:password@migration_project_haproxy_1:443/`
- I prepare CHT-Core 3.x installation for upgrading:
    - Stop the API by getting shell on your Medic OS container and calling /boot/svc-stop medic-api:
    ```
    Debug: Service 'medic-api/medic-api' exited with status 143
    Info: Service 'medic-api/medic-api' was stopped successfully
    Success: Finished stopping services in package 'medic-api`
    ```

    - Initiated view indexing by running `docker-compose run couch-migration pre-index-views 4.1.0`

    - Save existent CouchDb configuration running `docker-compose run couch-migration get-env` obtained 
    ```
    COUCHDB_USER=medic
    COUCHDB_PASSWORD=password
   COUCHDB_SECRET=bb45d28ca97bdf024bbff179e0a165f7
   COUCHDB_UUID=459be07c858612f49a796f8af462ea0d
    ```
    - Backup /srv/storage/medic-core/couchdb/data in the medic-os container
    
- At this point, I stopped my 3.17 medic os container.

- Launch 4.x CouchDb installation - multi node:
    - I downloaded 4.x clustered CouchDb docker-compose in a directory: 
    `curl -s -o ./cht-couchdb-clustered.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb-clustered.yml`
    - Create the data folders:
    ```
     /couchdb/data/main
     /couchdb/data/secondary1
     /couchdb/data/secondary2
    ```
    - Create a shards and a .shards directory in every secondary node folder
    - Copy the 3.17 backup data into the /couchdb/data/main directory
    - Set the env variables for couchdb cluster:
    ```
     export COUCHDB_USER=medic
     export COUCHDB_PASSWORD=password
     export COUCHDB_SECRET=bb45d28ca97bdf024bbff179e0a165f7
     export COUCHDB_UUID=459be07c858612f49a796f8af462ea0d
     export DB1_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/main
     export DB2_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/secondary1
     export DB3_DATA=/Users/marialorenarodriguezviruel/medic-workspace/couchdb-cluster/couchdb-data/secondary2
    ```
    - Updated couchdb-migration environment variables with the 4.x information:
    ```
    export COUCH_URL=http://medic:password@couchdb-cluster_couchdb.1_1:5984
    export CHT_NETWORK=cht-net
    ```
    - Started 4.1 couchdb with ` docker-compose -f cht-couchdb-clustered.yml up -d` inside the new project directory

    - Checked couchdb up with `docker-compose run couch-migration check-couchdb-up 3` inside couchdb-migration directory:
     ```
    Creating couchdb-migration_couch-migration_run ... done
    Waiting for CouchDb to be ready...
    Waiting for CouchDb Cluster to be ready....
    CouchDb Cluster is Ready
    ```
    - Generate the shard distribution matrix and get instructions for final shard locations.
    ```
    shard_matrix=$(docker-compose run couch-migration generate-shard-distribution-matrix)
    docker-compose run couch-migration shard-move-instructions $shard_matrix
    ```
   - Manually move the shard files to the correct location
   - Change metadata to match the new shard distribution
    ```
    docker-compose run couch-migration move-shards $shard_matrix
    Shards moved successfully
    ```
    - Remove old node from the cluster:
    ```
    Creating couchdb-migration_couch-migration_run ... done
    Node couchdb@127.0.0.1 was removed successfully
    ```
    - docker-compose run couch-migration verify
    ```
    ... Migration verification passed.
    ```
    - Started CHT-Core 4.1 using `curl -s -o ./cht-core.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml` and `COUCHDB_SERVERS=couchdb.1,couchdb.2,couchdb.3` 
    
   - Once the migration is successful:

    ✅ offline users should not need to resync data
    ✅ users should not get logged out
 ![Screenshot_20230328-160652](https://user-images.githubusercontent.com/21312057/228591370-51b18e21-9a21-47bf-9e38-0df8998cfa1c.jpg)

    ✅ offline users should be able to resync
![Screenshot_20230328-160628](https://user-images.githubusercontent.com/21312057/228591324-94b59cdf-7397-422f-a8eb-2c05e8bc60ea.jpg)


⚠️ All data should be available in the new instance. For this I compare the database information json and the fauxton database info. I found some differences in the json, but `doc_count` is the same in both instances.

- Fauxton database information 3.17:
![317](https://user-images.githubusercontent.com/21312057/228592123-f6f8e957-396e-4ed9-827c-e1e41f50ee6d.png)

- Database info JSON 3.17:
    ```
    {
   "db_name":"medic",
   "purge_seq":"0-g1AAAAFTeJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFOSApBMsv___39WIgMedYkMSfIEFeWxAEmGBiAFVDofv9okB5DF8USauQBi5n4CZiaAzKwn0swHEDOJUnsAovY-UG0WAApQXo4",
   "update_seq":"12213-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYGNh68ahLUgCSSfYwpWr4lDqAlMbDlEbjU5oAUloPVco6EY_SPBYgydAApICq54NNFiSofAFE-X6w6QcJKj8AUX4frLyfoPIHEOUQt2_NAgBglmJ3",
   "sizes":{
      "file":133301952,
      "external":124029761,
      "active":119027566
   },
   "other":{
      "data_size":124029761
   },
   "doc_del_count":15,
   "doc_count":10543,
   "disk_size":133301952,
   "disk_format_version":7,
   "data_size":119027566,
   "compact_running":false,
   "cluster":{
      "q":8,
      "n":1,
      "w":1,
      "r":1
   },
   "instance_start_time":"0"
   }
    ```

- Fauxton database information 4.1.0:
![410](https://user-images.githubusercontent.com/21312057/228592417-2e76c5b7-cc6b-4eee-b96c-9e705f083d1d.png)

- Database info JSON 4.1.0:
    ```
    {
   "db_name":"medic",
   "purge_seq":"0-g1AAAAFTeJzLYWBg4MhgTmEQTM4vTc5ISXKA0npGOUAppjwWIMnQAKT-__8_PyuRAY_aJAUgmWQPVIhfHcTMBxAzcao1RFJ7AKL2Pn61SQkg--sJmpnIkCSPR5ExxDAHkGHxBNVBHLgA4sD9QLVZABSLaqU",
   "update_seq":"12886-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXKA0nqGOUAppkSGJPn___9nJTEwsM3Eqs4IrC5JAUgm2cOUGmJVagxR6gBSGg9TWoPH9qQEkNJ6qFLWO3gckMcCJBkagBRQ9Xywyc14HAFRvgCifD9YeQgeh0CUH4Aovw9WrkrQMQ8gyiHetMgCANqsbjI",
   "sizes":{
      "file":11798448,
      "external":15129047,
      "active":10595509
   },
   "other":{
      "data_size":15129047
   },
   "doc_del_count":15,
   "doc_count":10544,
   "disk_size":11798448,
   "disk_format_version":7,
   "data_size":10595509,
   "compact_running":false,
   "cluster":{
      "q":8,
      "n":1,
      "w":1,
      "r":1
   },
   "instance_start_time":"0"
    }
    ```
</details>

@dianabarsan I was able to migrate successfully!

**Comment by dianabarsan** [comment]
I have merged the documentation PR. Closing this as completed.
