### ISSUE TITLE
Enketo selected option highlight color changes incorrectly on drag

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7892]
**Describe the bug**

When filling in an Enketo form on mobile the CHT shows a bright orange background behind selected options. This should always highlight the selected option, but it's quite easy to get the selected and highlighted option to be different options.

This was observed multiple times in a recent CMMB site visit. Users appeared to be coping with this by increased scrolling and re-selecting options.

**To Reproduce**

1. Using a mobile phone go to a form which has radio button options
2. Select an option - notice the radio icon shows selected, and the background is bright orange
3. On a different option, press and hold for around 1 second before dragging down
4. Note how the second option has been highlighted, but not selected

**Expected behavior**
The highlight should always indicate the selected option.

**Logs**
N/A

**Screenshots**
![Screenshot from 2022-11-07 11-49-49](https://user-images.githubusercontent.com/2064938/200199614-728c2798-42dc-419c-aef5-8191aaaee29b.png)

**Environment**
- Instance: local
- Browser: Chrome, but _not_ Firefox.
- Client platform: Android and Linux
- App: webapp
- Version: 3.10.0 and 4.0.0

**Additional context**

- The highlight was added in [1630](https://github.com/medic/cht-core/issues/1630)
- The colour is also ["quite horrible"](https://github.com/medic/cht-core/issues/1630#issuecomment-159145207), and the text colour is difficult to read because white on orange is low contrast. Work with @n-orlowski to figure out how this should look, or if the highlighting is even still needed.

**Comment by n-orlowski** [comment]
@garethbowen Highlighting the selection is still helpful to make it more easily recognizable; my reco would be to keep the current blue for the radio button and update the orange to the our secondary blue (#EEF5F9) and not changing the text color

<img width="481" alt="Screen Shot 2022-11-08 at 10 59 21 AM" src="https://user-images.githubusercontent.com/59581790/200651981-03b1aaa6-da1d-4f5f-9ad0-59c205e92976.png">

**Comment by garethbowen** [comment]
@n-orlowski Perfect, thanks! That blue is used for the hover colour on desktop, so it might be confusing to have the hover and selected colour the same. How would you feel about...
- desktop: secondary blue hover colour and no selected colour
- mobile: no hover colour and secondary blue selected colour

**Comment by n-orlowski** [comment]
@garethbowen sorry for the late reply! Suggested desktop and mobile behavior sounds good, and extra padding between the items would be clearer thanks

**Comment by garethbowen** [comment]
Ready for AT in https://github.com/medic/cht-core/pull/7951

AT instructions:
- Follow the reproduction steps above
- This will need to be tested on desktop, on phone, and in the Android app to make sure it works cross browser
- Make sure you check a range of input types, in particular radio and checkboxes

**Comment by garethbowen** [comment]
That was just the version where it was initially seen in the field. In reality it goes back way further. Do you think it makes sense to set a limit on how far back we set the labels?

**Comment by mrjones-plip** [comment]
Given labels are cheap...I'd say we just go for it and add it to them all.  That said, I [recently added](https://github.com/medic/cht-docs/pull/824) the "Known Issues" retroactively only back to [3.10.0](https://docs.communityhealthtoolkit.org/core/releases/3.10.0/) - so I could see an argument to not add them further back than 3.10.

your call!

**Comment by garethbowen** [comment]
Initially introduced in 2.6.0 :laughing:

**Comment by mrjones-plip** [comment]
> Initially introduced in 2.6.0 laughing

:hourglass_flowing_sand:

**Comment by garethbowen** [comment]
@ngaruko Is the orange border a new behaviour or does it happen on `master` too? I can't think of how it could be new on this branch but can have another look... It looks like some "selected" style so you might need to focus on it somehow?

**Comment by garethbowen** [comment]
Merged.
