### ISSUE TITLE
delete compose files on master branch on staging.dev.medicmobile.org

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7898]
**Describe the issue**
With the recent switch to a [new a staging database](https://github.com/medic/cht-core/issues/7879) to house releases only for 4.x, there's some concerns that the old 4.x compose files on  the 3.x will be used. As the 4.x compose files will drift further and further away from the now orphaned 3.x compose files, this could be a problem that is hard to detect by end users and Medic support.

**Describe the improvement you'd like**
We should delete the composes files for the master branch:
* `https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml`
* `https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml`
* `https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb-clustered.yml`

We may optionally delete the branch's 4.x compose files in the 3.x database, but this feels less risky as folks would really have to go looking for them.

**Describe alternatives you've considered**
Mainly Let these files sit there and hope no one uses them.

**Comment by mrjones-plip** [comment]
works for me!

**Comment by dianabarsan** [comment]
I've moved all 4.x builds from the `builds` database to `builds_4` database. 
As a result, 3.x installations will no longer list `~4.0.0` branches as possible upgrades, and old builds are still available for upgrades / installs for 4.x installations.

**Comment by mrjones-plip** [comment]
This keeps things so tidy and logical  - thanks so much @dianabarsan !
