### ISSUE TITLE
Upgrade test fails release

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7901]
**Describe the issue**
The upgrade test fails on release, eg: https://github.com/medic/cht-core/actions/runs/3423568916
In the log it looks like it's installed the wrong version:

```
4.0.0-alpha: Pulling from s5s3h4s7/cht-nginx

Digest: sha256:31fd524f86e61e1344d951822518e138384ef76b3d24c349246500083d0225e6

Status: Downloaded newer image for public.ecr.aws/s5s3h4s7/cht-nginx:4.0.0-alpha
```

This should be `4.0.0` not `4.0.0-alpha`.

I think the problem lies with the [branch-name](https://github.com/nelonoel/branch-name) action.

**Describe the improvement you'd like**
The test should pass.

**Comment by dianabarsan** [comment]
Fix was merged. We will observe changes when we publish the next release.
