### ISSUE TITLE
Incorrect image tag on release

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7902]
**What feature do you want to improve?**
Image tagging for release tags is lists the release name twice:
For example, the `api` tag is `public.ecr.aws/s5s3h4s7/cht-api:4.0.0-4.0.0` instead of `public.ecr.aws/s5s3h4s7/cht-api:4.0.0`

**Describe the improvement you'd like**
Fix release tagging.

**Comment by dianabarsan** [comment]
Fix was merged. We will observe changes when we publish the next release.

**Comment by dianabarsan** [comment]
I don't think we should republish the images with different tags, thought it's definitely possible. 
Theoretically, everyone should get the image tags directly from the docker-compose files or our staging documents.

**Comment by mrjones-plip** [comment]
As well, we can can update these references cited above to use the new `4.2.0` tag when it's released - fix it that way!
