### ISSUE TITLE
GH Actions deprecation warning

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#7905]
**Describe the issue**
Our builds ([example](https://github.com/medic/cht-core/actions/runs/3444691524)) are showing a bunch of warnings about usage of deprecated features. At some point the build will just start failing. While there are a load of warnings, it looks like it's just three distinct issues being hit multiple times each. Some of these will go away by updating the dependencies in the build script.

**Describe the improvement you'd like**
Update our build to remove all deprecated code.

**Comment by dianabarsan** [comment]
I've updated:

- docker/login-action@v1 -> docker/login-action@v2
- actions/checkout@v2 -> actions/checkout@v3
- actions/setup-node@v1 -> actions/setup-node@v3\
- aws-actions/configure-aws-credentials@v1 -> aws-actions/configure-aws-credentials@v1-node16
- actions/upload-artifact@v2 -> actions/upload-artifact@v3

Removed nelonoel/branch-name, which has not received updates in 3 years, for pulling the branch name directly from github params. 

No deprecation warnings are displayed.
