### ISSUE TITLE
Calling `/api/v1/settings/deprecated-transitions` prevents any future transitions to run over new records in API

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7912]
**Describe the bug**
The call to `/api/v1/settings/deprecated-transitions` will cause the settings object in the transitions lib to be unset, preventing all calls that pass documents to transitions to resolve. 

**To Reproduce**
1. Enable `death_reporting`. This doesn't just affect this transition, but this transition's code will be effective in triggering the error. Also make sure that you have no other transitions config errors, transitions must be working in order to trigger the bug. 
2. Create an SMS form. Any form will do, I just copied the ["DR" form from standard config](https://github.com/medic/cht-core/blob/master/config/standard/app_settings.json#L3916). 
3. Submit a DR form through `api/v2/records` to check that the call works. 
4. Call `/api/v1/settings/deprecated-transitions` . You can even do it from your browser. 
5. Submit a DR form through `api/v2/records`. Notice that the request hangs. Also if you check api logs you'll see something like 
```
2022-11-17 09:31:19 ERROR: UNHANDLED REJECTION! 
2022-11-17 09:31:19 ERROR:   Reason: TypeError: Cannot read properties of undefined (reading 'death_reporting')
    at Object.get (/home/diana/projects/medic/shared-libs/transitions/src/config.js:10:21)
    at getConfig (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:13:32)
    at getConfirmFormCodes (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:14:35)
    at isConfirmForm (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:17:31)
    at Object.filter (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:52:8)
    at canRun (/home/diana/projects/medic/shared-libs/transitions/src/transitions/index.js:220:16)
    at applyTransition (/home/diana/projects/medic/shared-libs/transitions/src/transitions/index.js:270:18)
    at wrapper (/home/diana/projects/medic/shared-libs/transitions/node_modules/lodash/lodash.js:5213:19)
    at /home/diana/projects/medic/shared-libs/transitions/node_modules/async/dist/async.js:3674:28
    at replenish (/home/diana/projects/medic/shared-libs/transitions/node_modules/async/dist/async.js:446:21) {
  [stack]: "TypeError: Cannot read properties of undefined (reading 'death_reporting')\n" +
    '    at Object.get (/home/diana/projects/medic/shared-libs/transitions/src/config.js:10:21)\n' +
    '    at getConfig (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:13:32)\n' +
    '    at getConfirmFormCodes (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:14:35)\n' +
    '    at isConfirmForm (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:17:31)\n' +
    '    at Object.filter (/home/diana/projects/medic/shared-libs/transitions/src/transitions/death_reporting.js:52:8)\n' +
    '    at canRun (/home/diana/projects/medic/shared-libs/transitions/src/transitions/index.js:220:16)\n' +
    '    at applyTransition (/home/diana/projects/medic/shared-libs/transitions/src/transitions/index.js:270:18)\n' +
    '    at wrapper (/home/diana/projects/medic/shared-libs/transitions/node_modules/lodash/lodash.js:5213:19)\n' +
    '    at /home/diana/projects/medic/shared-libs/transitions/node_modules/async/dist/async.js:3674:28\n' +
    '    at replenish (/home/diana/projects/medic/shared-libs/transitions/node_modules/async/dist/async.js:446:21)',
  [message]: "Cannot read properties of undefined (reading 'death_reporting')"
} 
```

**Expected behavior**
API should be able to process transitions. 

**Logs**
Included above. 

**Environment**
- Instance: Production instance
- App: api
- Version: 3.11+

**Additional context**
I randomly noticed the error logs in a production instance, reporting that their integration calls are failing. 
This bug was introduced a long time ago, but we got away with it. Currently only `cht-conf` calls that endpoint. If there are no deprecated transitions in the config, the `settings` endpoint is called immediately afterwards, which resolves the issue by resetting the transitions lib (it gets reset when settings are updated).
However, if the config contains deprecated transitions, and the `settings` call is made, API is stuck in an invalid transitions state. 

**For projects that are affected by this**
- updating settings will fix the problem
- updating translations will fix the problem

The change can be insignificant, it only serves the purpose to trigger the code that runs in API when settings and translations are changed.

**Comment by jkuester** [comment]
This _may_ be resolved in https://github.com/medic/cht-core/pull/7709.  I have not had time to check yet, but I know we saw a very similar issue in that branch and fixed it.  (At the time I thought the issue in our branch was caused by refactoring we had done, but maybe it was endemic...)

**Comment by dianabarsan** [comment]
I think this has value to be tracked separately, since it might require backporting to older supported versions.

**Comment by dianabarsan** [comment]
This is ready for AT: https://github.com/medic/cht-core/pull/7914

**Comment by lorerod** [comment]
**Reproduced on 4.0**
**Environment**
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3A4.0.0/docker-compose%2Fcht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic%3Amedic%3A4.0.0/docker-compose%2Fcht-couchdb.yml)
Browser: Chrome
Client platform: MacOS
Version: 4.0.0-alpha
App: api

**Steps to reproduce:**
- Get the instance up
- Upload `standard` config 
    - This config have `death_reporting` enabled
    - This config have "DR" SMS form
- Login as online user. Create places, chw and offline user
- Login as offline user create a family and two patients
- Call `POST https://192-168-100-62.my.local-ip.co/api/v2/records`
    - Request:
    ```
    {
      "patient_id": "88080",
      "_meta": {
        "form": "DR"
        }
    } 
    ```
    - Response:
    ```
    {
        "success": true,
        "id": "0d44db83-42b1-4b9e-bfe8-0e84d90493ac"
    }
    ```
- Call `/api/v1/settings/deprecated-transitions` from your chrome browser. 
   - Response:
```
[{"name":"generate_patient_id_on_people","deprecated":true,"deprecatedIn":"3.8.x","deprecationMessage":"generate_patient_id_on_people transition is deprecated since 3.8.x. Please use \"generate_shortcode_on_contacts\" transition instead."},{"name":"update_notifications","deprecated":true,"deprecatedIn":"3.2.x","deprecationMessage":"update_notifications transition is deprecated since 3.2.x. Please use \"muting\" transition instead."}]
```
- Call `POST https://192-168-100-62.my.local-ip.co/api/v2/records`
    - Request:
    ```
    {
      "patient_id": "15301",
      "_meta": {
       "form": "DR"
        }
    }
    ```
    - Didn't get a response. The request hangs:
  
![Captura de Pantalla 2022-11-23 a la(s) 17 00 40](https://user-images.githubusercontent.com/21312057/203636587-c2cd4235-deed-4d04-9e9d-47a2d8e8d356.png)
- Api log:
```
2022-11-23 20:00:30 ERROR: UNHANDLED REJECTION! 

2022-11-23 20:00:30 ERROR:   Reason: TypeError: Cannot read properties of undefined (reading 'registrations')

    at Object.get (/shared-libs/transitions/src/config.js:10:21)

    at getConfig (/shared-libs/transitions/src/transitions/registration.js:188:32)

    at Object.filter (/shared-libs/transitions/src/transitions/registration.js:671:29)

    at canRun (/shared-libs/transitions/src/transitions/index.js:220:16)

    at applyTransition (/shared-libs/transitions/src/transitions/index.js:270:18)

    at wrapper (/shared-libs/transitions/node_modules/lodash/lodash.js:5213:19)

    at /shared-libs/transitions/node_modules/async/dist/async.js:3674:28

    at replenish (/shared-libs/transitions/node_modules/async/dist/async.js:446:21)

    at iterateeCallback (/shared-libs/transitions/node_modules/async/dist/async.js:430:21)

    at /shared-libs/transitions/node_modules/async/dist/async.js:327:20 {

  [stack]: "TypeError: Cannot read properties of undefined (reading 'registrations')\n" +

    '    at Object.get (/shared-libs/transitions/src/config.js:10:21)\n' +

    '    at getConfig (/shared-libs/transitions/src/transitions/registration.js:188:32)\n' +

    '    at Object.filter (/shared-libs/transitions/src/transitions/registration.js:671:29)\n' +

    '    at canRun (/shared-libs/transitions/src/transitions/index.js:220:16)\n' +

    '    at applyTransition (/shared-libs/transitions/src/transitions/index.js:270:18)\n' +

    '    at wrapper (/shared-libs/transitions/node_modules/lodash/lodash.js:5213:19)\n' +

    '    at /shared-libs/transitions/node_modules/async/dist/async.js:3674:28\n' +

    '    at replenish (/shared-libs/transitions/node_modules/async/dist/async.js:446:21)\n' +

    '    at iterateeCallback (/shared-libs/transitions/node_modules/async/dist/async.js:430:21)\n' +

    '    at /shared-libs/transitions/node_modules/async/dist/async.js:327:20',

  [message]: "Cannot read properties of undefined (reading 'registrations')"

} 
```

**Comment by lorerod** [comment]
**Fixed on branch**
**Environment**
Instance: Local using branch `7912-fix-deprecated-transitions-api`
Browser: Chrome
Client platform: MacOS
Version: `7912-fix-deprecated-transitions-api`
App: api

**Steps to reproduce:**
- Get the instance up
- Upload `standard` config 
    - This config have `death_reporting` enabled
    - This config have "DR" SMS form
- Login as online user. Create places, chw and offline user
- Login as offline user create a family and two patients
- Call `POST http://localhost:5988/api/v2/records`
    - Request:
    ```
  {
  "patient_id": "17322",
  "_meta": {
    "form": "DR"
    }
    }
    ```
    - Response:
    ```
   {
    "success": true,
    "id": "ac625519-1362-4227-8f31-04e275a6d757"
    }
    ```
- Call `/api/v1/settings/deprecated-transitions` from your chrome browser. 
   - Response:
```
[{"name":"generate_patient_id_on_people","deprecated":true,"deprecatedIn":"3.8.x","deprecationMessage":"generate_patient_id_on_people transition is deprecated since 3.8.x. Please use \"generate_shortcode_on_contacts\" transition instead."},{"name":"update_notifications","deprecated":true,"deprecatedIn":"3.2.x","deprecationMessage":"update_notifications transition is deprecated since 3.2.x. Please use \"muting\" transition instead."}]
```
- Call `POST http://localhost:5988/api/v2/records`
    - Request:
    ```
    {
  "patient_id": "89126",
  "_meta": {
    "form": "DR"
    }
    }
    ```
    - Response:
    ```
   {
    "success": true,
    "id": "15a1fbff-94bf-422d-bd6a-29d731e50782"
    }
    ```
- No errors on api log
- Both Death Reports were generated:
![Captura de Pantalla 2022-11-24 a la(s) 14 11 45](https://user-images.githubusercontent.com/21312057/203838122-fd10fa97-8f27-42f5-8c23-60e4b8fd30d9.png)

**Comment by lorerod** [comment]
Thanks @dianabarsan! This look good!

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by dianabarsan** [comment]
Will need to be backported to `4.0.1`, `3.17.1` and `3.16.1`.

**Comment by dianabarsan** [comment]
Backported to `4.0.x`

**Comment by dianabarsan** [comment]
Backported to `3.16.x` and `3.17.x`.
