### ISSUE TITLE
Issue in Bikram Sambat Date Picker

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#7925]
**Describe the bug**
There is an issue in Bikram Sambat date picker when I am put the valid value first and invalid value later on. 

**To Reproduce**
1. Create any form with date input and open it in CHT in Nepali locale. 
2. When you are in date field, enter valid Nepali Date. For e.g: (30, Kartik (or any month), 2079) and try validating form (going to next page or submitting).
4. If you've gone to next page, come back to date field. 
5. If you submitted the report, click on edit report and come back to date field. 
6. Try putting in any invalid dates (99 Kartik, 2079) 
7. Then submit form, it gets submitted without error. 

**Expected behavior**
Date should be validated if users are editing report and enter invalid date. 

**Screenshot**
Please watch this recording where I am editing a report with valid date and putting in invalid date later on. 

https://user-images.githubusercontent.com/6102813/203792958-56628198-d296-487f-bea8-f6866448b02a.mov

**Environment**
- Instance: Any
- Browser: Chrome
- App: webapp
- Version: 3.14.2

**Comment by dianabarsan** [comment]
@yrimal 
To make sure I understand this, editing the date doesn't trigger validation? But adding the date initially does? 
Thanks

**Comment by yrimal** [comment]
That's correct @dianabarsan. Additionally, If invalid date is submitted, the field keeps the original date which was in correct format.

**Comment by dianabarsan** [comment]
Cool, thanks for clarifying @yrimal . 
I am trying this in 4.x and I'm seeing some inconsistent behavior where: 

- If I edit the year, then I get a constraint error
![image](https://user-images.githubusercontent.com/35681649/203813118-61cca695-2b2f-4708-a226-2dee8572d753.png)

- if I edit the day, I don't
![image](https://user-images.githubusercontent.com/35681649/203813254-af1267de-e53a-4aaf-9339-92900a312d61.png)

**Comment by dianabarsan** [comment]
Just an update:
- I can add the "invalid" date even on add 
- I can't find any "validation" in the widget code.

@yrimal 
Can you please try to create a report with an invalid date?

**Comment by yrimal** [comment]
Hi @dianabarsan , I've updated the form to replicate this issue. 

[deliver.xlsx](https://github.com/medic/cht-core/files/10089027/deliver.xlsx)

**Comment by yrimal** [comment]
This issue is mainly caused by how bikram sambat bootstrap library handles new inputs. When we get new BS date input and convert it, the [updateBackingDateInput](https://github.com/medic/bikram-sambat/blob/master/bootstrap/src/bikram-sambat-bootstrap.js#L55-L58) function sets the gregorian date only if converted date is valid. 

If user inputs an invalid Bikram Sambat date, the bikramsambat library converts it to gregDate which will be null because it's not a valid date. Then updateBackingDateInput() checks if it needs to trigger the change. Since new greg date is not valid, current condition on this function won't trigger the change and a date based on [previous input which was valid will be stored](https://github.com/medic/cht-core/issues/7925#issuecomment-1326539557).

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

--

### Test scenario: 
The report attached to [this comment](https://github.com/medic/cht-core/issues/7925#issuecomment-1327052208) was uploaded to each environment to test the issue.

### Reproducible on `master`
The Bikram Sambat date picker was validated only the first time, if I continue to the next page or try to edit the report the validation is not present.

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/213543321-74154831-5192-49d0-9c54-00d736ecb1fa.mov)

</details>

### Fixed on `yrimal:master`
The Bikram Sambat date picker was validated every time that the value was modifided.

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/213543491-979989b0-f269-425c-acae-93df2a92b957.mov)

</details>

---

Test passed successfully. :tada:

**Comment by yrimal** [comment]
Thanks @tatilepizs . 
@dianabarsan , Please let me know once you release [bikram-sambat](https://github.com/medic/bikram-sambat) to npmjs. Then I'll update my branch to use bikram-sambat from npmjs and we can merge this.

**Comment by dianabarsan** [comment]
I've published `bikram-sambat-bootstrap@1.6.0` on npm.

**Comment by dianabarsan** [comment]
Merged to `master`.
