### ISSUE TITLE
Staging URL placeholder replacement uses old `builds` database

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7944]
**Describe the issue**
Even for new PRs and new branches, the docker-compose placeholders are updated with links pointing to the old `builds` database, instead of `builds_4`. 
Example: https://github.com/medic/cht-core/pull/7935 . This PR was created yesterday.

**Describe the improvement you'd like**
Have the action use the correct links.

**Comment by garethbowen** [comment]
The source for this was fixed in [this commit](https://github.com/medic/cht-core/commit/f9bbb4f74d5061e9a4db7599484ad94b89f9e8a4) but it looks like the action was never compiled so the change never made it.

**Comment by garethbowen** [comment]
Merged
