### ISSUE TITLE
Improve wording of the warning when upgrading. 

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#7947]
**What feature do you want to improve?**
During the upgrade process there is error message showing (`error fetching upgrade progress`)

**Describe the improvement you'd like**
Would be better to show a message to the user to wait, that 'something is happening' instead of an error
**Describe alternatives you've considered**
ATM, if one knows what's happening, one just has to wait and the error message will go away.
**Additional context**
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6979995/204742997-0d6a7569-5531-457d-946a-a5ca948ab17e.png">

**Comment by dianabarsan** [comment]
The're one small issue that I'm not sure how to fix here. 
We *expect* that message during the container swap (required by the upgrade). We *expect* that message to go away once everything is up and running again (the page also gets automatically refreshed).
However, if there is a problem, where the upgrade failed and some of the containers failed to start, that message will persist. 

I'm not sure how explicit this message should be.

**Comment by garethbowen** [comment]
Let's just not show the warning if it's expected - it's unnecessarily alarming.

Instead of "completing upgrade" it should say, "restarting CHT" or something so people know that an outage at this point is expected. Then maybe show the error if the server isn't back within 1 hour or something? Ideally it'd be a shorter time, but this step may take a while if the server is downloading Docker images, right?

**Comment by dianabarsan** [comment]
> Let's just not show the warning if it's expected - it's unnecessarily alarming.

If something happens during container swapping, we have to show something. All admin knows is that API isn't responding. What do you suggest for that case?

**Comment by garethbowen** [comment]
But even the admin app can't know there's an issue during container swapping, can it?

**Comment by dianabarsan** [comment]
That's correct. it can't know.

**Comment by dianabarsan** [comment]
It only knows it can't reach API.

**Comment by dianabarsan** [comment]
Sure. 
I think solving the halting problem is a bit unreasonable at the moment, as it would require 100% blue-green deployment.

What would you say "reasonable time" would be?

**Comment by garethbowen** [comment]
I think we should aim for <1% false positives (ie: very unlikely that we show the warning when the startup is working just slow). Reading through the code, it's not clear when API gets shut down. Does the docker pull work in the background or does it take down the containers? If we can do the pull first then API should come up fast, right?

**Comment by dianabarsan** [comment]
It's not just API that needs to be up, it's also CouchDb and nginx and haproxy. many points of failure. in my experience, couch is the slowest to start up.

**Comment by dianabarsan** [comment]
>  docker pull work in the background
yes, it works in the background. containers are taken down after images are already available

**Comment by garethbowen** [comment]
Ok. What about 10 minutes? 20?

**Comment by dianabarsan** [comment]
I would say that's a lot, but then I don't know every computer spec that will upgrade CHT. 
@ngaruko Any idea for how long you saw the warning message on screen?

**Comment by dianabarsan** [comment]
Huh interesting it takes so long for your containers to come back up, and that some take so much longer to come up or don't go down at all until later. 
I think setting the timer to a minute should be good. What do you think @garethbowen ?

**Comment by garethbowen** [comment]
1 minute is fine. If it shows up spuriously too often we can increase it later.

**Comment by dianabarsan** [comment]
This is ready for AT on https://github.com/medic/cht-core/pull/7974 . 
The warning message is now displayed with a 1 minute delay.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `master`
The warning message was shown a couple of times before the deployment completes.

<details>
<summary>Video attached.</summary>

[video](https://user-images.githubusercontent.com/94494491/212771982-c393265e-40ed-4b08-962c-0fb6ab9c04b6.mov)

</details>

### Fixed on `7947-delayed-admin-upgrade-warning`
The warning message was not shown during the deployment.

<details>
<summary>Video attached.</summary>

[video](https://user-images.githubusercontent.com/94494491/212772032-551fb548-a4b7-4172-bc36-d380a3cab658.mov)

</details>

---

Test passed successfully. :tada:

**Comment by dianabarsan** [comment]
Merged to `master`.
