### ISSUE TITLE
Nginx Environment Variables not passed along

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#7949]
**Describe the bug**
When using own cert, Nginx configuration fails unless the cert is named `cert.pem` and the key is named `key.pem`.
Environment variables `SSL_CERT_FILE_PATH` and `SSL_KEY_FILE_PATH` are not honored.

**To Reproduce**
1. Set the above two variables with a `certificate.pem` and `privkey.pem`
2. Launch it and see the error.

**Comment by henokgetachew** [comment]
FYI: Bug is here: https://github.com/medic/cht-core/blob/master/nginx/ssl-install.sh#L5-L6

**Comment by mrjones-plip** [comment]
@henokgetachew  - given we're going to deprecate `CERTIFICATE_MODE` and `SSL_VOLUME_MOUNT_PATH` in #8098 and that the prototyping being done in #8099 has shown than  `SSL_CERT_FILE_PATH` and `SSL_KEY_FILE_PATH` don't need to be updating - is this ticket still needed?  

If not, I think we should remove the `Affects: 4.x.x` labels and close it.

**Comment by henokgetachew** [comment]
@garethbowen what do you think?

**Comment by garethbowen** [comment]
I agree with deprecating the MODE but didn't think we agreed with deprecating PATH which is still useful I think. @mrjones-plip Why deprecate the PATH? Is it because it's easy enough to rename your files in the volume?

**Comment by mrjones-plip** [comment]
> Why deprecate the PATH? Is it because it's easy enough to rename your files in the volume?

correct!   That said, I should have been more explicit as I'm effectively requesting to deprecate them.  I'm sorry!

I don't think it gets us that much to have the paths configurable:
* The certs are already stored in a durable volume to survive container reboots 
*  this volume name is [already an env variable](https://github.com/medic/cht-core/blob/master/scripts/build/cht-core.yml.template#L109)
* You can already trivially update the certs by either copying them directly into the running container and HUP `nginx` like we do [for local-ip certs](https://github.com/medic/cht-core/blob/master/scripts/add-local-ip-certs-to-docker-4.x.sh) or externally as we direct [all production installs](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/adding-tls-certificates/) to do.  
* the [large amount of env vars](https://github.com/medic/cht-upgrade-service/#environment-variables) seems like overkill.  a lot of them are undocumented (and some are unusable as we've seen with #8098)

The main reason I can see to keep  `SSL_CERT_FILE_PATH` and `SSL_KEY_FILE_PATH`  is if SRE needs them for Medic hosted deployments under k8s.

**Comment by henokgetachew** [comment]
The container doesn't handle SSL for Medic hosted.

**Comment by garethbowen** [comment]
Discussed on the call today and decided to deprecate the path variables and require people to rename certs to match our convention.

**Comment by mrjones-plip** [comment]
Thanks @garethbowen ! I've updated #8098 accordingly!
