### ISSUE TITLE
Nginx OWN_CERT mode broken

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#7950]
**Describe the bug**
When using `OWN_CERT`, the volume mounting is broken. Even if the variable `SSL_VOLUME_MOUNT_PATH` is passed, the app crashes stating certs not provided.

**To Reproduce**
1. Set the `SSL_VOLUME_MOUNT_PATH` to the path of your cert.
2. Launch it. 
3. It fails startup.

**Expected behavior**
It should pull the cert and mount it to `/etc/nginx/private`

**Comment by mrjones-plip** [comment]
@henokgetachew  - there was a fix for this in #7832 and checking now I can get `OWN_CERT` to work by [following these steps](https://github.com/medic/cht-core/pull/7834#issuecomment-1268710481):

```
nginx_1        | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/server.conf.template to /etc/nginx/conf.d/server.conf
nginx_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/ssl-install.sh
nginx_1        | CERTIFICATE MODE = OWN_CERT
nginx_1        | Running SSL certificate checks
nginx_1        | SSL certificate exists.
nginx_1        | Launching Nginx
nginx_1        | /docker-entrypoint.sh: Configuration complete; ready for start up
```

Is this ticket still needed?

**Comment by mrjones-plip** [comment]
Cool - sounds good! Thanks for checking my suggestion.

Feel free to revert any my changes if they make it more complex or conflict.  What ever makes it easiest for the self hoster!

**Comment by mrjones-plip** [comment]
Closing this in favor of our new effort to deprecate `CERTIFICATE_MODE` and friends in #8098
