### ISSUE TITLE
Update patch and release issue templates to add step to create `Affects x.y.z` labels. 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7954]

**Comment by garethbowen** [comment]
@dianabarsan To be clear, you mean creating the labels for the release you're in the process of releasing?

**Comment by dianabarsan** [comment]
I think so. I created an issue, and had to create the labels after the fact. Do you think it's too much to preemptively create the `affects` label on release?

**Comment by garethbowen** [comment]
I think it's fine. Bonus points if it can be automated with GH actions so when we tag the label is created without any human intervention.

**Comment by garethbowen** [comment]
@dianabarsan I think [this commit](https://github.com/medic/cht-core/commit/a25e17b19da2b8771f1674d686b30878cfa80d91) resolves this request... It's more about adding the label to existing issues, but to do that you're going to have to create the new label. Can we close this issue?

**Comment by dianabarsan** [comment]
Thanks!
