### ISSUE TITLE
Change CouchDb service names to match all hostname specs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7962]
**Describe the issue**
Starting with NodeJs v18, parsing urls like `http://admin:pass@couchdb.1:5984` will throw a `ERR_INVALID_URL`. 
This already happens in Chrome:

Type this in Chrome Console: 
```
new URL('http://admin:pass@couchdb.1:25984');
````

**Describe the improvement you'd like**
Change the docker service names for couchdb (and any other container) to be compliant with the URL spec, and make sure internal docker network URLs can be parsed when we'll upgrade Node to 18. 

**Describe alternatives you've considered**
Leave them as they are.

**Comment by dianabarsan** [comment]
We will have to take into account that the service names are passed as env variables to other couchdbs, so they identify each other over the docker network. 
If partners have changed those environment variables, upgrading to this version will need manual stopping and starting to update the environment.

**Comment by garethbowen** [comment]
Could try `couchdb-1.local`?

**Comment by dianabarsan** [comment]
> Could try `couchdb-1.local`?

This works, I like this suggestion.

**Comment by dianabarsan** [comment]
This changes the service names for CouchDb to `couchdb-x.local` and is available here: https://github.com/medic/cht-core/pull/7981
I think a sanity check and verifying that the service names are correct would suffice.

**Comment by lorerod** [comment]
**Environment:** 
MacOS 13.1
Docker desktop 4.15.0
Docker engine: 20.10.21. 
Chrome Versión 109.0.5414.119 (Build oficial) (x86_64)

- Using Chrome console I executed `new URL('http://medic:password@couchdb-1.local:25984');` and got 
![Captura de pantalla 2023-02-16 a la(s) 18 06 35](https://user-images.githubusercontent.com/21312057/219487072-879893dc-7289-4695-880a-bf420eab6c67.png)

**CHT:**  Local using docker compose files provided in [PR](https://github.com/medic/cht-core/pull/7981)
- I got the instance up and running executing `COUCHDB_SERVERS=couchdb-1.local,couchdb-2.local,couchdb-3.local COUCHDB_PASSWORD=password COUCHDB_USER=medic docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up`

**Comment by dianabarsan** [comment]
Merged to `master`.
