### ISSUE TITLE
Discuss whether or not to resume view indexing if installation was interrupted

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7964]
**What feature do you want to improve?**
If installation is interrupted before view indexing is finished, API will start up immediately, without waiting for indexes to be up to date. 

**Describe the improvement you'd like**
I think this warrants a discussion. 

Some context: 
- this case can present when: 
  - CHT 4.x is being installed on an existing data-set - for example when upgrading from 3.x without pre-indexing views
  - an upgrade is staged, but finalized at a later date (and after a significant number of changes have been pushed to the database) 
- in this scenario, API has already started on the correct version, so we are passed the point of upgrade. where the old version of API would still be running
- we are facing potential downtime while views are not up to date, regardless of choice

The options are to:
1. Wait for all views to be indexed before starting API
- this means that the API startup page will be displayed for the duration of this process
- API will not respond to any requests 

2. Start API anyway
- depending on which views require indexing, API could be working partially, responding to some requests that don't require querying  these views, and timing out for others
- startup could be blocked because some views are required in startup steps: for example `medic-client/doc_by_type` is queried when getting forms: https://github.com/medic/cht-core/blob/master/api/src/services/forms.js#L23

One thing to note is that most projects will not actively use all views. For example, some webapp projects might never use SMS views and vice versa. When installing or upgrading, **all views** will be indexed.

**Comment by garethbowen** [comment]
Quick thoughts...

- As much as possible API startup should not block on view indexing. This is important because if something is going wrong we want admins to have access to diagnose and fix it. Can your example be modified to use doc by id?
- If we can get down to zero view requests in API startup, then we should not warm views before starting API.
- If we can't get down to zero view requests in API startup, then we should show the API startup page until the required views are responding.

**Comment by dianabarsan** [comment]
I agree. Indeed, if we eliminate all view queries from startup, API can bootstrap successfully. 
Luckily, we can target form documents because of their prefix, so this particular example can be updated so it does not require a view query. 
I'll go over the code again and flag any other view queries that might occur at startup.

**Comment by dianabarsan** [comment]
I've updated the way we get forms when  starting up on this PR: https://github.com/medic/cht-core/pull/8080
As far as I can tell, this was the only query that was left for API startup. 

To AT the change in particular: 
- make sure form attachments get generated on server start
- form attachments get generated on form updates

To AT the stale view startup: 
- launch CHT
- make edits to some views (pick one view from `medic` and one view from `medic-client` for example)
- make a post call to view  cleanup `curl -X POST <url_with_authentication>/medic/_view_cleanup`
- restart API

You should see API starting up immediately, and be able to load the uncached login page successfully, and any endpoint that doesn't hit views should also load immediately (`/setup/poll`, `/api/deploy-info`, `/api/v1/settings`, `/api/v1/settings/deprecated-transitions`, ). Hitting any URL that requires querying a view will trigger view indexing (which you should be able to see in the activetasks UI: `<url_with_authentication>/_utils/#/activetasks`)

**Comment by dianabarsan** [comment]
Merged to `master`.
