### ISSUE TITLE
Upgrades don't work on self hosted multi-node CouchDB CHT 4 deployments

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7970]
**Describe the bug**
When a self hosted deployment has set up Docker Swarm to have an overlay network with a multi-node CouchDB cluster, the upgrade service fails to upgrade all the nodes when using the CHT admin interface to upgrade the instance

**To Reproduce**
1. set up a self hosted multi-node CouchDB instance 
2. go to "upgrades" in admin interface 
3. Select version to upgrade to and choose "stage" or "upgrade"

**Expected behavior**
The instance should successfully upgrade

**Logs**

**Screenshots**

**Environment**
- Instance: NA
- Browser: NA
- Client platform: NA
- App: NA
- Version: 4.0.0+
 
**Additional context**
SRE knows best, but the reason this doesn't work I believe is that the upgrade service can't see across the overlay network to upgrade the nodes as well as edit the compose files

**Comment by dianabarsan** [comment]
We're shifting away from advising to hosting clustered deployments using docker-compose and docker swarm, and instead using k3d for clustered deployments, which allows upgrading clustered CouchDb out of the box. 

This [PR](https://github.com/medic/cht-core/pull/8263) will add all K8s configuration necessary.

**Comment by garethbowen** [comment]
Deprioritising this as Diana mentioned this is no longer the recommended setup.

**Comment by dianabarsan** [comment]
Closing as distributed deployments are not deployed using Kubernetes, which supports upgrades.

**Comment by latin-panda** [comment]
@mrjones-plip is this part of 4.6?

**Comment by latin-panda** [comment]
@dianabarsan will this affect 4.5.2?

**Comment by garethbowen** [comment]
@latin-panda No it's not relevant any more.
