### ISSUE TITLE
Export action isn't displayed when there is a child place and user doesn't have 'can_create_places' permission

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7973]
**Describe the bug**
There is currently a rule that if there are child places and the user doesn’t have 'can_create_places' permission, then the Export action is not displayed. The bug is in [this code.](https://github.com/medic/cht-core/blob/aab4b89b2fb354c442f6fca0f6c795d929ca3ba8/webapp/src/ts/components/actionbar/actionbar.component.html#L41)

**To Reproduce**
1. Make a hierarchy 
2. Deactivate 'can_create_places', and activate 'can_export_all' or 'can_export_contacts' permission.
3. Go to contact tab
4. See how export doesn't display. 

**Expected behavior**
The export action should display if there are records to export and if the user has 'can_export_all' or 'can_export_contacts' permission. The 'can_create_places' isn't related to this action. 

**Environment**
- Instance: all
- Browser: chrome
- Client platform: MacOs
- App: webapp
- Version: [3.9.x](https://github.com/medic/cht-core/blob/3.9.x/webapp/src/templates/directives/actionbar.html#L52) maybe even since before.

**Additional context**
I discover this while working on [More Options Menu](https://github.com/medic/cht-core/pull/7965#:~:text=room%20for%20it.-,%237872,-Code%20review%20checklist). The issue is fixed in the More Options Menu but not in the action-bar component

**Comment by garethbowen** [comment]
@latin-panda In the additional context for this issue you wrote...

> The issue is fixed in the More Options Menu but not in the action-bar component

I agree that it looks like it's fixed in the More Options menu. Given that the old action bar is deprecated and soon to be removed can we close this as won't fix? 

It seems like it'd be a waste of time to fix it just before removing the code altogether... The workaround is to use the new design.

**Comment by latin-panda** [comment]
Won't fix. The action bar is deprecated.
