### ISSUE TITLE
Container names issue for clustered couchdb setup when running across different nodes

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#7986]
**Describe the bug**
`container_name` needs to be specified for couchdb docker-compose files when using clustered setup across different nodes. The other option is to make CLUSTER_PEER_IP variable configurable and not hardcoded.

**Description**
When running couchdb nodes across different instances, you want to be able to address the container names using their exact names. Given the CLUSTER_PEER_IPs are hardcoded to couchdb.2 and couchdb.3, to way to get it working right now is by setting `container_name` property for the containers.

**Comment by garethbowen** [comment]
This came up in a recent PR review: https://github.com/medic/cht-core/pull/7981/files#r1047808516

**Comment by mrjones-plip** [comment]
Note that we're [likely going to](https://github.com/medic/cht-core/issues/7962#issuecomment-1340576122) `couchdb1.local` nomenclature

**Comment by dianabarsan** [comment]
This is getting updated by https://github.com/medic/cht-core/pull/7981/files#r1047808516

**Comment by henokgetachew** [comment]
Just took a look. Looks good!

**Comment by lorerod** [comment]
I don't know how to test this. @henokgetachew @dianabarsan Can you explain the situation where CLUSTER_PEER_IP would need to change? 

**I successfully got the instance up**
**Environment:** MacOS 13.1 (22C65); Docker desktop 4.15.0 (93002)l; Docker engine: 20.10.21
**CHT:**  Local using docker compose files provided in [PR](https://github.com/medic/cht-core/pull/7981)

- I got cht-core up executing `COUCHDB_SERVERS=couchdb-1.local,couchdb-2.local,couchdb-3.local COUCHDB_PASSWORD=password COUCHDB_USER=medic docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up`

- Successful created the containers:
```
CONTAINER ID   IMAGE                                                                                   NAMES                    PORTS
c6b95e669b92   public.ecr.aws/s5s3h4s7/cht-nginx:4.1.0-7962-valid-couchdb-service-name                 7962_nginx_1             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp
55674513766d   public.ecr.aws/s5s3h4s7/cht-api:4.1.0-7962-valid-couchdb-service-name                   7962_api_1               5988/tcp
98f572b92f64   public.ecr.aws/s5s3h4s7/cht-sentinel:4.1.0-7962-valid-couchdb-service-name              7962_sentinel_1          
6270d4808ec7   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_couchdb-2.local_1   4369/tcp, 5984/tcp, 9100/tcp
2446555f1893   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_couchdb-1.local_1   4369/tcp, 5984/tcp, 9100/tcp
6f265e08accd   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_couchdb-3.local_1   4369/tcp, 5984/tcp, 9100/tcp
7e3053cd027d   public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.1.0-7962-valid-couchdb-service-name   7962_healthcheck_1       
8ed09a60b411   public.ecr.aws/s5s3h4s7/cht-haproxy:4.1.0-7962-valid-couchdb-service-name               7962_haproxy_1           5984/tcp
```

**Comment by lorerod** [comment]
To change the name of the servers, I have to change the `services` names, `SVCX_NAME,` `CLUSTER_PEER_IPS,` and `COUCHDB_SYNC_ADMINS_NODE` is that correct?

**Comment by dianabarsan** [comment]
That's correct. You should be able to change all of those through environment variables. 

I've just noticed we don't add all of those to the upgrade-service docker-compose file, I have a PR that adds them (https://github.com/medic/cht-upgrade-service/blob/ddafd1f34ed7a33c70de71243098436a5d51cbef/docker-compose.yml). You can also add them manually to your existent file if you wish.

**Comment by lorerod** [comment]
**I successfully got the instance up using the provided yml, changing the servers names and env variables**
**Environment:** MacOS 13.1 (22C65); Docker desktop 4.15.0 (93002)l; Docker engine: 20.10.21
**CHT:**  Local using docker compose files provided in [PR](https://github.com/medic/cht-core/pull/7981)

- I change `services` names in `cht-couchdb-clustered.yml` from `couchdb-x.local` to `database-x.local`
- I got cht-core up executing `COUCHDB_SERVERS=database-1.local,database-2.local,database-3.local CLUSTER_PEER_IPS=database-2.local,database-3.local COUCHDB_SYNC_ADMINS_NODE=database-1.local SVC1_NAME=database-1.local SVC2_NAME=database-2.local SVC3_NAME=database-3.local COUCHDB_PASSWORD=password COUCHDB_USER=medic docker-compose -f cht-couchdb-clustered.yml -f cht-core.yml up `

- Successful created the containers:
```
CONTAINER ID   IMAGE                                                                                   NAMES                     PORTS
87b34a486388   public.ecr.aws/s5s3h4s7/cht-nginx:4.1.0-7962-valid-couchdb-service-name                 7962_nginx_1              0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp
c330cca43f6c   public.ecr.aws/s5s3h4s7/cht-api:4.1.0-7962-valid-couchdb-service-name                   7962_api_1                5988/tcp
1a0e3a7745dd   public.ecr.aws/s5s3h4s7/cht-sentinel:4.1.0-7962-valid-couchdb-service-name              7962_sentinel_1           
4fd4411da017   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_database-2.local_1   4369/tcp, 5984/tcp, 9100/tcp
9b11dfb9536e   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_database-1.local_1   4369/tcp, 5984/tcp, 9100/tcp
e3f3cf0f5ebc   public.ecr.aws/s5s3h4s7/cht-couchdb:4.1.0-7962-valid-couchdb-service-name               7962_database-3.local_1   4369/tcp, 5984/tcp, 9100/tcp
4e39c15c8820   public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.1.0-7962-valid-couchdb-service-name   7962_healthcheck_1        
fb94e65cdc9f   public.ecr.aws/s5s3h4s7/cht-haproxy:4.1.0-7962-valid-couchdb-service-name               7962_haproxy_1            5984/tcp
```
