### ISSUE TITLE
Upgrade webapp's angular to v15.x.x

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7992]
**Describe the issue**
The current version is v12.x.x, we need to keep it updated. Latest version is v15

**Comment by latin-panda** [comment]
- Running time of unit tests
  - Angular 12:  
    - `grunt unit-webapp` total time: 3m 31.3s 
    - `grunt unit-webapp-no-dependencies` total time: 1m 35.5s
  - Angular 15: 
    - `grunt unit-webapp` total time: **2m 47.6s**  
    - `grunt unit-webapp-no-dependencies` total time: **56.8s**
- Build time
  - Angular 12: 
    - `grunt dev-webapp` total time: 1m 80s 
    - `grunt dev-webapp-no-dependencies` total time: 49.46s
  - Angular 15: 
    - `grunt dev-webapp` total time: **40.46s**  
    - `grunt dev-webapp-no-dependencies` total time: **26.82s**
- Size
  - Angular 12: 
    - Initial total: 5.53 MB
    - `main.js` 13.97 MB
  - Angular 15: 
    - Initial total: **14.00 MB**
    - `main.js` **12.24 MB**


**Common error while upgrading Angular**
Whenever we have the error below, it's likely that `@angular/compiler`, `@angular-devkit/build-angular`  or `@angular-builders/custom-webpack` aren't resolved properly in the `package-lock.json`. So, uninstall these 3, then install them again in that order.

![Screen Shot 2022-12-22 at 12 36 21 pm](https://user-images.githubusercontent.com/66472237/209088049-aaf33272-dd0c-4640-9917-a309c5782eea.png)

**Comment by jkuester** [comment]
> Common error while upgrading Angular

Should we add this note to the [Updating Dependencies docs](https://docs.communityhealthtoolkit.org/contribute/code/core/update-dependencies/)?

**Comment by latin-panda** [comment]
Good idea, I'm going to do that tomorrow.

This is ready for AT in [this PR](https://github.com/medic/cht-core/pull/7999), besides testing general functionality, please also:
- test on mobile
- and also performance 
- 
More details in the PR's description.

**Comment by latin-panda** [comment]
Following up on @jkuester suggestion, I've [opened a PR](https://github.com/medic/cht-docs/pull/942) to include details about angular's exception when upgrading and a tip to fix it.

**Comment by tatilepizs** [comment]
### Test details

Everything is working as usual, nothing different 🎉 

- Default config (webapp and phone, android 10)
  - Create/edit district, health center, clinics
  - Pregnancy workflow
  - Death report

- Standard config  (webapp and phone, android 10)
  - Create/edit district, health center, clinics
  - Pregnancy workflow
  - Immunization workflow
  - Send reports using sms
  - Death report

**Comment by latin-panda** [comment]
This work has been merged into the main branch. 
Thanks @tatilepizs ✨
