### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7993]
**Describe the issue**
After the CHT Core's  v4.x.x has been released, we now support the latest LTS NodeJS.
Upgrade and make sure all is working fine.

**Comment by garethbowen** [comment]
While doing this, also update this code: https://github.com/medic/cht-core/blob/e94df0961fe33f53936cee799e7d8ed196428b0a/tests/cht-conf-utils.js#L20-L39

As well as the TODO in the code, this should `fs.rm` not `fs.rmDir` which is deprecated.

**Comment by garethbowen** [comment]
Blocked on https://github.com/medic/cht-conf/issues/538

**Comment by garethbowen** [comment]
Now, we just need to update cht-conf in cht-core... blocked on https://github.com/medic/cht-core/issues/7167 and https://github.com/medic/cht-core/issues/7744

**Comment by garethbowen** [comment]
Merged!
