### ISSUE TITLE
Broken link in How To Manage Translations documentation.

### ISSUE THREAD

**Issue by nsitaula** [medic/cht-core#7997]
There is broken link in [How To Manage Translations documentation](https://docs.communityhealthtoolkit.org/core/overview/translations/#adding-new-languages). In section, Adding new languages link to ddocs/medic/_attachments/translations/messages-XX.properties shows 404 error.

**Comment by abbyad** [comment]
Good catch! The translations are now under api: https://github.com/medic/cht-core/tree/master/api/resources/translations

**Comment by nsitaula** [comment]
thanks @abbyad
