### ISSUE TITLE
Move additive actions from the Action Bar to Floating Action Button

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#7998]
# Overview
As a part of our [longer term goal](https://github.com/medic/cht-roadmap/issues/61) to align with material design standards, the "Action Bar" at the bottom of the app (left hand side AND right hand side) is being removed. This issue will **remove the Action Bar** (_see Notes below_), **introduce a [Floating Action Button (FAB)](https://m3.material.io/components/floating-action-button/overview)**, and **move additive actions** (creating reports, places, people, etc...) from the Action Bar to the FAB. This will affect single pane (mobile) and dual pane views (desktop) on the [Messages](https://docs.communityhealthtoolkit.org/apps/features/messaging/), [Reports](https://docs.communityhealthtoolkit.org/apps/features/reports/), and [People](https://docs.communityhealthtoolkit.org/apps/features/contacts/) tabs. 

<img width="789" alt="Screenshot 2022-12-21 at 4 39 24 PM" src="https://user-images.githubusercontent.com/10096985/209007698-fe6dc6d8-cbac-41f2-872a-a2ddcf05d892.png">

The Figma mockups can be found [here](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?node-id=230%3A9424&t=BsHuimIOqnExyorI-0).

#### NOTES

1. The Action Bar will be temporarily available through a [feature flag](https://docs.communityhealthtoolkit.org/apps/guides/updates/feature-flags/) by enabling the `can_view_old_action_bar` [permission](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/user-permissions/). Be aware that [#7778](https://github.com/medic/cht-core/issues/7778) **_uses the same permission_**.
2. Issue [#5962](https://github.com/medic/cht-core/issues/5962) will be worked on separately, _after_  the FAB update is released. This FAB issue will define a default order when multiple actions are in the FAB.

# FAB Contents

This table illustrates which actions are **currently** available based on what is selected and which device is being used. This is not changing.  There are [permissions](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/user-permissions/) to control the visibility of the Call and Message actions on the Contacts tab. 

![Screenshot 2023-01-19 at 2 47 50 PM](https://user-images.githubusercontent.com/10096985/213544955-8e0ee7f1-08f9-419a-8f5e-f31bd4fca2e3.png)

_In all cases, only show relevant actions based on `context`._

## Mobile View

The FAB options will show up as a drawer from the bottom with rows of actions, much like it looks today for Forms, but with the other options (Call, Message, Contact Forms) in this list as well. 

![Screenshot 2023-01-19 at 2 39 49 PM](https://user-images.githubusercontent.com/10096985/213543673-52da4e12-fe2e-4f5f-9925-78b5854bb92d.png)

## Desktop View

There are two trigger buttons, one is located in the list's footer which only has a label (no icon), and the other one is located on the top right side and only has an icon (no label).
 
![Screenshot 2023-03-07 at 6 02 22 pm](https://user-images.githubusercontent.com/66472237/224626072-1881959a-2c4d-4b56-9e36-2afd343b8db7.png)

The FAB options will show up as a modal window in the middle of the screen. The options will be in a list just like the mobile drawer mentioned above. If the option name is too long, then display it in two lines and use the ellipsis to trim the text. 

If the user clicks outside the modal or presses "Esc" from the keyboard, also if the user navigates to another page, then the modal should close.

## Trigger button

The old action bar will be removed and tapping on the list footer's button (desktop) or in the FAB (mobile) will bring up the action list. 

FAB button:
- No label
- If there is more than one action: plus sign icon
- If there is only one action, but the action's icon isn't Font Awesome: plus sign icon.
- If there is only one action, and the action is a Font Awesome: action's icon.  

List footer's button:
- No icon
- Show label

## Order of items in the list

Issue https://github.com/medic/cht-core/issues/5962 will allow a custom order by for actions in the list, but the default will be as below. Reference the colorful table above to understand what is shown when. For example, you'll notice that there are never more than 3 "types" of things shown at once. 

1. Call
2. Message
3. "Place" Contact Forms, in alphabetical
4. "Person" Contact Forms, alphabetical
5. App Forms, alphabetical

# Messages Tab

The only action available on this tab is `Send message`. The old action bar will be removed and tapping on the list footer's button (desktop) or in the FAB (mobile) will bring up the `Send Message` modal. 

# Contacts Tab

The Contacts Tab has five possible actions: `Call`, `Send message`, `New place`, `New person`, and `New action` (report).

#### Left Hand Side (Top Level)

- The only option available is `New place`. Move it to the FAB. When the search input has the focus and the soft-keyboard appears, then hide the FAB.

#### Right Hand Side (Place)

- There are three options: `New place`, 'New person', and `New action`. Move all these to the FAB.
- Never skip the drawer if the one thing is a Form.  

#### Right Hand Side (Person)

- There are three* options: `Call`, `Send message`, and `New action`. Move all these to the FAB.
- Never skip the drawer if the one thing is a Form. 

_* `Call` only shows up if you are on a mobile device._

#### Left Hand Side

The action will be moved to the list footer's bottom. 

#### Right Hand Side

Same as in mobile

# Reports Tab

The Reports tab has four main Actions: `Submit report`, `Send message`, `Update facility` and `Review`.

## Review action
- This action is moved to the More Options menu. 
- When a user taps on it, shows a modal (desktop) or a bottom drawer (mobile) with two options: "Has errors" and "Correct".  Show in one row, with "Has errors" on the left and "Correct"  on the right.
- The review badge is moved next to the form's name.
![Screenshot 2023-03-13 at 4 00 43 pm](https://user-images.githubusercontent.com/66472237/224654728-9bd83add-5aa0-408f-b6fc-c4fa0e774bae.png)

#### Left Hand Side

The only option available is `Submit report`. Move it to the FAB.

- Icon should always be a `+` 
- Always show the drawer, even if there is only one thing on the list
- The FAB is hidden behind the Filter panel when it's open. 
- When the search input has the focus and the soft-keyboard appears, then hide the FAB if possible.
- While in multiselect (bulk delete), hide the FAB 

#### Right Hand Side

- There are two options: `Send message` and `Update facility`. Move it to the FAB
- While in multiselect (bulk delete), hide the FAB 

#### Left Hand Side

- The only option is `Submit report`. Move it to the list footer's button.
- While in multiselect (bulk delete), hide the FAB 

#### Right Hand Side

- There are two options: `Send message` and  `Update facility`. Move it to the FAB 
- While in multiselect (bulk delete), hide the FAB

**Comment by latin-panda** [comment]
Working on this now

**Comment by latin-panda** [comment]
About this [issue](https://github.com/medic/cht-core/issues/7998#issuecomment-1478433217).
@tatilepizs and I kept testing, but we can't reproduce it and, therefore, can't provide a fix. The Angular Material component manages the background.
This is what we did to try to reproduce it:
- firefox
- chrome
- real android phone on versions: 12, 10, 5
- docker helper deploy and regular deploy (grunt command)
- different screen sizes and mobile emulation in the browser

**Comment by tatilepizs** [comment]
### Desktop

<details>
<summary>Flat button - People's tab. ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/231294754-317ce484-2cc0-489b-aed6-d80d481236c8.png)

</details>

<details>
<summary>FAB - Health Facility. ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/231296303-deea5fbe-c446-4b7a-8016-7db584373e1b.png)

</details>

<details>
<summary>FAB - Area. ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/231299599-c17fe957-f20b-4c81-94ea-c56d2ef28fd8.png)


</details>

<details>
<summary>FAB - Household. ✅ </summary>

##### Opens directly the `New Person` form

![image](https://user-images.githubusercontent.com/94494491/231300325-3257b137-0d01-410a-811e-bc5ddcccb5a1.png)

</details>

<details>
<summary>FAB - Person with a phone number assigned. ✅ </summary>

![image](https://user-images.githubusercontent.com/94494491/231302148-e9f7d110-d628-4ac9-8f2a-f1f5b630c9b3.png)


</details>

<details>
<summary>FAB - Person without a phone number assigned. ✅ </summary>

<img width="539" alt="image" src="https://user-images.githubusercontent.com/94494491/231304743-042c5f12-89b1-45d9-a3bf-eecfda5026b3.png">


</details>

<details>
<summary>FAB - Person with just the alternate phone number assigned. ✅ </summary>

<img width="539" alt="image" src="https://user-images.githubusercontent.com/94494491/231305070-8efd79eb-0567-4890-b9c7-2a305110756f.png">

</details>

<details>
<summary>Flat button - Send a message. ✅ </summary>

<img width="537" alt="image" src="https://user-images.githubusercontent.com/94494491/231305848-19672c89-73be-41ea-b05b-a200445643b9.png">

</details>

<details>
<summary>Flat button - New Report ✅ </summary>

<img width="537" alt="image" src="https://user-images.githubusercontent.com/94494491/231306214-2ec6dbc2-caaf-4669-8e2a-227d30e77b08.png">

</details>

<details>
<summary>Flat button - A lot of reports (scroll). 🚧 </summary>

</details>

<details>
<summary>FAB - A lot of reports (scroll). 🚧 </summary>

</details>

<details>
<summary>FAB - Custom icon 🚧 </summary>

</details>

---

### Mobile 

<details>
<summary>Flat button - People's tab. 🚧 </summary>

</details>

<details>
<summary>FAB - Health Facility. 🚧 </summary>

</details>

<details>
<summary>FAB - Area. 🚧 </summary>

</details>

<details>
<summary>FAB - Household. 🚧  </summary>

</details>

<details>
<summary>FAB - Person with a phone number assigned. 🚧  </summary>

</details>

<details>
<summary>FAB - Person without a phone number assigned. 🚧 </summary>

</details>

<details>
<summary>FAB - Person with just the alternate phone number assigned. 🚧  </summary>

</details>

<details>
<summary>Flat button - Send a message. 🚧 </summary>

</details>

<details>
<summary>Flat button - New Report 🚧 </summary>

</details>

<details>
<summary>Flat button - A lot of reports (scroll). 🚧 </summary>

</details>

<details>
<summary>FAB - A lot of reports (scroll). 🚧 </summary>

</details>

<details>
<summary>FAB - Custom icon 🚧 </summary>

</details>

---

🚧 Work in progress 🚧
