### ISSUE TITLE
Bullets not displaying properly in form labels

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8002]
**Describe the bug**
In `3.x` versions of the CHT you could _simulate_ a bulleted list in a form label (e.g. a `note`) by using `-` or `*`.  Now, in `4.x`, after https://github.com/medic/cht-core/issues/6345, the bullets are no longer properly displayed in the label.

**To Reproduce**
1. Create a form with a note that has this label:
```
Do these bullets work:
- Hello 
- World

Or do these work:
– Hello 
– World

How about these:
* Hello 
* World
```
2. Open the form and view the note

**Expected behavior**
On `3.x`, the note looks like this:

![image](https://user-images.githubusercontent.com/8441903/209364499-65c8f4cd-a0af-427f-986c-bd4b397d1539.png)

**Actual behavior**
On `4.x`, though, it looks like this:

![image](https://user-images.githubusercontent.com/8441903/209364595-8b73b480-e939-4a87-a08f-25ef3e0c6894.png)

_(Note that the middle block "works" because the `–` character is not valid markdown syntax for a bullet point....)_

**Additional context**

The problem is that in `3.x` the [markdown processing](https://github.com/medic/cht-core/blob/3.17.x/webapp/src/ts/services/markdown.service.ts) was basic and did not support bullet points.  So, these notes were evaluated as simple text and the bullet characters are preserved in the text.  

On `4.x`, the [markdown processing](https://github.com/medic/cht-core/blob/69a0207d8c67e92ba625f9545e01c4c781779246/api/src/enketo-transformer/markdown.js#L65) is more advanced and can detect the bullet points in the question labels.  It then converts the bullets to unordered lists (`<ul>`).  The problem is that the CSS style that ends up getting computed for those unordered lists is `list-style: none`.  So, the end result is that the unordered lists are displayed in the labels without any bullet points.

I think we probably just need to tweak the CSS for these unordered lists to be `list-style: inside;`

_(This change was first noted by @binokaryg (and team) when upgrading a project's config to work with CHT `4.x`.)_

**Comment by latin-panda** [comment]
As mentioned in this ticket description, the dash and asterisk characters were replaced with a `ul li` elements. 
<img width="300" src="https://github.com/medic/cht-core/assets/66472237/bcad3a39-9e12-45b0-a107-0d8b8b2957b9">

The best I can do is style the `ul li` to look like bullet points:

<img width="400" src="https://github.com/medic/cht-core/assets/66472237/0426aa4d-4bcb-4db7-9763-b8113ce18c3e">
