### ISSUE TITLE
CHT 4.x Setup Installation issue

### ISSUE THREAD

**Issue by manishjaingit** [medic/cht-core#8007]
I tried to install it with Medic V4.0 but https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.0.1/docker-compose/cht-core.yml && curl -s -o ./core-couch/cht-couchdb.yml https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.0.1/docker-compose/cht-couchdb.yml && curl -s -o ./upgrade/docker-compose.yml https://raw.githubusercontent.com/medic/cht-upgrade-service/main/docker-compose.yml
Is giving 
error: "not_found",
reason: "Document is missing attachment"
and the same library installs the 3.9 version by-default. 

Can somebody help me to get the v4.0 working?

**Comment by dianabarsan** [comment]
Hi @manishjaingit 

There are three commands there, and I'm not sure which one of them is returning this error. Would you mind running each individually and sharing which one fails? Thanks.

**Comment by manishjaingit** [comment]
Thanks, @dianabarsan for your quick response, 
both are loading version 3.9
https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.0.1/docker-compose/cht-core.yml
https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.0.1/docker-compose/cht-couchdb.yml

And also After installation, it shows 3.9 even after not being upgraded by the system as well.

![image](https://user-images.githubusercontent.com/6293004/211502576-3448785d-2498-49f9-89a4-41440454c524.png)

**Comment by dianabarsan** [comment]
Oh! So you have an existing installation? 
Unfortunately, you can't just use the UI to upgrade to 4.x, installation is completely separate and manual. 
You're going to have to stop the 3.9 installation entirely and start anew with 4.x.

**Comment by manishjaingit** [comment]
Sorry for the confusion, Actually this is not the existing installation,
I have created a fresh installation with the expectation that I am going to have V4.0 Medic CHT but after installation, it shows V3.9 on the about page.
So I tried to upgrade it via the above page as well but the process moves in a deadlock and nothing happen.

Is there any separate doc to install 4.x version of CHT core?

**Comment by dianabarsan** [comment]
These are the steps to follow to install 4.x : https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/

**Comment by manishjaingit** [comment]
Yeah, I followed the same and this process is installing the V3.9 version and unable to upgrade it on V4.x too.

**Comment by dianabarsan** [comment]
Are you running these commands on the host machine?

**Comment by manishjaingit** [comment]
Yeah, I have created one EC2 instance and run these commands over there.
also, I have uploaded dummy data inside it, but the major thing I want is to have an updated version of CHT.
[https://13.213.238.50/#/reports/](https://13.213.238.50/#/reports/)

**Comment by dianabarsan** [comment]
> I have uploaded dummy data inside it
How did you add dummy data? You should start with a fresh database for 4.x, any data would be added after installation.

**Comment by manishjaingit** [comment]
> How did you add dummy data?

https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/#3-upload-test-data

I mean test data.

Actually, The issue is as I am following this doc with the expectation to have V4.0 on my EC2 machine, but unfortunately not working.

**Comment by manishjaingit** [comment]
![image](https://user-images.githubusercontent.com/6293004/211631688-e4e9ff1c-4633-4526-89fb-a197bc0c8afc.png)

**Comment by dianabarsan** [comment]
Thanks for sharing. 
From what I can see, you have installed the `medic-os` container, which only support cht-core 3.x. It indeed install 3.9 by default, and there is no way to upgrade from that to 4.x. 
Do you happen to remember the exact steps you followed until this point? 

To install 4.x, please remove these two containers first. (stop and remove), and then follow the instructions in this tutorial to install 4.x: https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/ 
Please let me know how this goes!

**Comment by dianabarsan** [comment]
Closing as Stale. @manishjaingit Please re-open if you are still facing issues.
