### ISSUE TITLE
Display version and build number separately in the admin upgrade page

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8009]
**What feature do you want to improve?**
Right now the version that is displayed in the admin upgrade page is the full version, which includes the build number. 
This is useful for branches, where there might be multiple builds for the same branch. It's not useful for releases, where there should only be one build for each release. 

![image](https://user-images.githubusercontent.com/35681649/211512168-feb007b6-3530-46ed-8e94-3f2b6d4dd75f.png)

**Describe the improvement you'd like**
Display full build version separately, while also displaying clean semver only version. 

**Describe alternatives you've considered**
- Don't display build at all (then there is no way of knowing if you're on the latest version of a branch)
- No changes

**Additional context**
This came up on the forum: https://forum.communityhealthtoolkit.org/t/docker-helper-cht-version/2356

**Comment by dianabarsan** [comment]
This is ready for AT on https://github.com/medic/cht-core/pull/8013 . 

I've added an extra field for `build`, and left the version be just the base_version. 
![image](https://user-images.githubusercontent.com/35681649/212609947-9b3c69ec-8c28-4471-afdc-f44072766c6c.png)

This change affects both admin and api, so after you upgrade to the branch, please refresh the admin upgrade page to see the changes.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `master`
Both, version and build number are shown in the same field.

<details>
<summary>Image attached</summary>

![image](https://user-images.githubusercontent.com/94494491/212773620-ea606bea-ee2c-4d57-84b5-8775461618ea.png)

</details>

### Fixed on `8009-separate-admin-build-and-version`
Version and build details are shown in different fields.

<details>
<summary>Image attached</summary>

![image](https://user-images.githubusercontent.com/94494491/212773514-1a4c92c4-f11f-45f2-ae2c-815180d2d2ef.png)

</details>

---

Test passed successfully. :tada:

**Comment by dianabarsan** [comment]
Merged to `master`.
