### ISSUE TITLE
Feature Release upgrades don't work on CHT 4.x

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8019]
**Describe the issue**
In 3.x you would upgrade using `horti` and then when you published a new FR (eg beta 2) it would show up in the admin UI.  This is no longer true in 4.x

**Describe the improvement you'd like**
We should make it an easy way to upgrade after you have [installed the FR](https://github.com/medic/cht-docs/pull/934).  

As well, we may consider making the latest version of every available FR for your current version visible in the admin GUI. For example if you were on `4.2.0`, we might show you all the FRs that were based on this version or later versions.  We would only show the latest (eg `beta3`) and not all prior versions (eg `beta1` and `beta2`)

**Describe alternatives you've considered**
NA

**Comment by mrjones-plip** [comment]
Related, there will soon be a work around on [how to install them](https://github.com/medic/cht-docs/pull/934) that doesn't use `horti`

**Comment by dianabarsan** [comment]
@mrjones-plip 
FR-s should appear in the upgrade UI exactly as they did before. Horitculturalist was replaced partially by the upgrade service and partially by API.

**Comment by mrjones-plip** [comment]
@dianabarsan - you're correct!

i tested this by using docker helper to deploy `4.4.1-FR-enketo-7-with-async-compute-beta.1`.  I then went to the admin upgrade section and saw the next beta (`2`) was available:

![image](https://github.com/medic/cht-core/assets/8253488/0959f87e-8c06-4a68-a179-f3f41065b722)

thanks for the follow up on this.
