### ISSUE TITLE
Angular's `ExpressionChangedAfterItHasBeenCheckedError` exception in Reports and Contacts tabs

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8022]
**Describe the bug**
When in developer mode and after interacting with Reports and Contacts, Angular throws the  `expressionChangedAfterItWasChecked` exception.

**To Reproduce**
Contacts tab - Steps:
1. Go to the Contacts tab
2. Edit a contact
3. While the contact form is open, reload the page
4. See exception in the browser's developer tools.

Reports tab - Steps:
1. Go to the Reports tab
2. User the search to filter reports
3. Select one report (click on the checkbox)
4. Unselect the same report (click again on the checkbox)
5. See exception in the browser's developer tools.

To get another exception from Reports tab (same as contact tab):
1. Go to the Reports tab
2. Edit a report
3. While the report form is open, reload the page
4. See exception in the browser's developer tools.

**Expected behavior**
No exception is thrown.

**Logs**
Reports tab:

![image](https://user-images.githubusercontent.com/35681649/212070600-0f0a6f81-85da-44a8-b6d8-aee520ba0370.png)

![Screen Shot 2023-01-13 at 3 27 17 pm](https://user-images.githubusercontent.com/66472237/212273489-2be757ad-824e-44f1-9eda-9e60ef872de4.png)

Reports & Contacts tab:
![image](https://user-images.githubusercontent.com/35681649/212070806-ef0bc4c7-3b9f-46d6-be6e-a80d58fabe14.png)

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 4.1.0

**Comment by garethbowen** [comment]
Related to #7651

**Comment by latin-panda** [comment]
Merged [6ed0af2](https://github.com/medic/cht-core/commit/6ed0af2aa10d59babb627d4fdc074e1a5e43be5f)
