### ISSUE TITLE
Form submission e2e test fails with "Error saving report"

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8033]
**Describe the bug**
Report fails to be saved in e2e test. 
Example run: https://github.com/medic/cht-core/actions/runs/3940194827/jobs/6741276076

**To Reproduce**
This is probably caused by a race condition, somewhere in webapp code, since this test succeeds most of the time. 

1. Deploy `default` config.
2. Open a "Pregnancy danger sign follow-up" form from the reports page. 
3. Quickly fill the fields. 
4. Submit. 
5. See "Error saving report. 

**Expected behavior**
The report should be saved. 

**Logs**
Browser logs from e2e test: 
```
[error] Console Api Event: [{"type":"string","value":"Error submitting form data: "},

{"type":"object","subtype":"error","className":"Error","description":"Error: Error in XMLFormService : getByView : No form found for internalId : \"undefined\"\n    at https://localhost/main.js:1:3353964\n    at I.value (https://localhost/polyfills.js:1:24935)\n    at I.value (https://localhost/polyfills.js:1:18995)\n    at https://localhost/polyfills.js:1:35874\n    at I.value (https://localhost/polyfills.js:1:25626)\n    at I.value (https://localhost/polyfills.js:1:19802)\n    at _e 

(https://localhost/polyfills.js:1:27970)","objectId":"-6685610337139740902.10.2","preview":{"type":"object","subtype":"error","description":"Error: Error in XMLFormService : getByView : No form found for internalId : \"undefined\"\n    at https://localhost/main.js:1:3353964\n    at I.value (https://localhost/polyfills.js:1:24935)\n    at I.value 

(https://localhost/polyfills.js:1:18995)\n    at https://localhost/polyfills.js:1:35874\n    at I.value (https://localhost/polyfills.js:1:25626)\n    at I.value (https://localhost/polyfills.js:1:19802)\n    at _e (https://localhost/polyfills.js:1:27970)","overflow":false,"properties":

[{"name":"stack","type":"string","value":"Error: Error in XMLFormService : getByView : No fo…   at _e (https://localhost/polyfills.js:1:27970)"},{"name":"message","type":"string","value":"Error in XMLFormService : getByView : No form found for internalId : \"undefined\""}]}}]
```

The essential part of the error is in the last line: 
`Error in XMLFormService : getByView : No form found for internalId : \"undefined\""}`

This is coming from https://github.com/medic/cht-core/blob/7e28a83a1164b8dfa04eae26fdc9f4af356fe448/webapp/src/ts/services/xml-forms.service.ts#L78
In turn this is triggered by: https://github.com/medic/cht-core/blob/6042a8e298c0251b8b6141a0d6652bb9fb200dbe/webapp/src/ts/modules/reports/reports-add.component.ts#L299

So it looks like our state becomes incorrect or incomplete at some point. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/212938672-fac2cb9e-5f7f-4506-9509-846bd4a4e27c.png)

**Environment**
- Instance: Github Action
- App: webapp
- Version: 4.1.0

**Comment by garethbowen** [comment]
Inlining the test failure before the test run logs are purged...

```
 ------------------------------------------------------------------
[Chrome Headless 108.0.5359.124 linux #0-18] Running: Chrome Headless (v108.0.5359.124) on linux
[Chrome Headless 108.0.5359.124 linux #0-18] Session ID: 9f44a25c-e46e-41c2-a904-84f2cf518f95
[Chrome Headless 108.0.5359.124 linux #0-18]
[Chrome Headless 108.0.5359.124 linux #0-18] » /tests/e2e/default/enketo/pregnancy-danger-sign.wdio-spec.js
[Chrome Headless 108.0.5359.124 linux #0-18] Pregnancy danger sign follow-up form
[Chrome Headless 108.0.5359.124 linux #0-18]    ✓ Submit and validate Pregnancy danger sign follow-up form and keeps the report minified
[Chrome Headless 108.0.5359.124 linux #0-18]    ✖ should submit and edit Pregnancy danger sign follow-up form (no changes)
[Chrome Headless 108.0.5359.124 linux #0-18]    ✖ should submit and edit Pregnancy danger sign follow-up form with changes
[Chrome Headless 108.0.5359.124 linux #0-18]
[Chrome Headless 108.0.5359.124 linux #0-18] 1 passing (40.5s)
[Chrome Headless 108.0.5359.124 linux #0-18] 2 failing
[Chrome Headless 108.0.5359.124 linux #0-18]
[Chrome Headless 108.0.5359.124 linux #0-18] 1) Pregnancy danger sign follow-up form should submit and edit Pregnancy danger sign follow-up form (no changes)
[Chrome Headless 108.0.5359.124 linux #0-18] element ("#reports-content .report-body .details") still not displayed after 15000ms
[Chrome Headless 108.0.5359.124 linux #0-18] Error: element ("#reports-content .report-body .details") still not displayed after 15000ms
[Chrome Headless 108.0.5359.124 linux #0-18]     at async Object.submitForm (/home/runner/work/cht-core/cht-core/tests/page-objects/default/reports/reports.wdio.page.js:127:3)
[Chrome Headless 108.0.5359.124 linux #0-18]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/pregnancy-danger-sign.wdio-spec.js:37:5)
[Chrome Headless 108.0.5359.124 linux #0-18]
[Chrome Headless 108.0.5359.124 linux #0-18] 2) Pregnancy danger sign follow-up form should submit and edit Pregnancy danger sign follow-up form with changes
[Chrome Headless 108.0.5359.124 linux #0-18] element (".action-container .general-actions:not(.ng-hide) .fa-plus") still not clickable after 15000ms
[Chrome Headless 108.0.5359.124 linux #0-18] Error: element (".action-container .general-actions:not(.ng-hide) .fa-plus") still not clickable after 15000ms
[Chrome Headless 108.0.5359.124 linux #0-18]     at async Object.openForm (/home/runner/work/cht-core/cht-core/tests/page-objects/default/reports/reports.wdio.page.js:79:3)
[Chrome Headless 108.0.5359.124 linux #0-18]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/pregnancy-danger-sign.wdio-spec.js:56:5)
------------------------------------------------------------------
```

**Comment by garethbowen** [comment]
Success rate as of today: 75%

**Comment by ngaruko** [comment]
Is this still flaky @dianabarsan ?I have run it multiple time on local and it is passes all the time. 🤔

**Comment by ngaruko** [comment]
Ah! Got it after n runs. Will still be hard to know how to fix it and when it is fixed. 🤔
<img width="1036" alt="image" src="https://github.com/medic/cht-core/assets/6979995/71079a1b-a541-469e-a91a-09fd51db9d29">

**Comment by ngaruko** [comment]
Ah! Got it after n runs. Will still be hard to know how to fix it and when it is fixed. 🤔
<img width="1036" alt="image" src="https://github.com/medic/cht-core/assets/6979995/71079a1b-a541-469e-a91a-09fd51db9d29">

**Comment by ngaruko** [comment]
Apparently, [it is not a flaky test](https://github.com/medic/cht-core/pull/8503#issuecomment-1700337405). Removing flaky tag. What's the priority on this @michaelkohn ? Just so it could be assigned to a dev and not sit idle in a backlog.

**Comment by michaelkohn** [comment]
It's unclear to me if this is something that users can/are actually experiencing. Is this something we'd see in feedback docs? Any other indication of frequency? Is it a quick/easy fix?

**Comment by garethbowen** [comment]
> It's unclear to me if this is something that users can/are actually experiencing. Is this something we'd see in feedback docs?

I don't think feedback docs are generated when this happens.

> Any other indication of frequency?

It's reasonably frequent in testing but no idea how common for actual users. It's probably not that common given we haven't seen it reported and it's been around a while.

> Is it a quick/easy fix?

It's hard to tell. I've spent a couple of hours trying to track it down or reproduce it without any luck. It's one of those things that once you find it it'll be a 1 minute fix, but it might take a long time to find.

**Comment by latin-panda** [comment]
@michaelkohn I had a similar experience as Gareth; after debugging and trying different combinations, I couldn't reproduce it. I tried to fill out the form as fast as possible and move around quickly, sync as I filled the form, and other combinations, but I had no luck yet. This will require more time

**Comment by dianabarsan** [comment]
It seems that this is not reproducible anymore.
