### ISSUE TITLE
Admin app fails to get releases when a different staging server is passed through ENV to API

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8038]
**Describe the bug**
We hardcode the staging server url in the admin app here: https://github.com/medic/cht-core/blob/master/admin/src/js/controllers/upgrade.js#L1 
However API accepts an environment variable to define the staging server: https://github.com/medic/cht-core/blob/master/api/src/environment.js#L26 , we even change our content-security-policy to include the "configured" build server as an allowed source: https://github.com/medic/cht-core/blob/master/api/src/routing.js#L160

When passing a different builds server to API, Admin app will report it fails to get builds because: 
1. it's trying to get them from the hardcoded staging server
2. the hardcoded staging server is blocked by the content security policy

**To Reproduce**
1. Launch API with a different `BUILDS_URL`
3. Go to admin upgrade page
4. See error: "Error fetching available versions"

**Expected behavior**
Admin app should query selected builds server, instead of trying to query the default and fail because of CSP. 

**Logs**
```
Refused to connect to 'https://staging.dev.medicmobile.org/_couch/builds_4/' because it violates the following Content Security Policy directive: "connect-src 'self' http://admin:pass@127.0.0.1:6984/builds_4/ maps.googleapis.com"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/213491237-b9d07a24-8569-4ef6-b538-b77d7af9e405.png)

**Environment**
- App: admin
- Version: 4.0.0

**Comment by garethbowen** [comment]
Merged
