### ISSUE TITLE
API Crashes on malformed translation docs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8040]
**Describe the bug**
API fails to start when any of the translation docs `messages-xx` is missing some properties that are expected. 
This can happen for a number of reasons, and has been the case for many releases. 
Since 4.0, this can be triggered very easily when deleting languages. 

**To Reproduce**
1. Make sure Sentinel is up and up to date with the queue.
2. Create a new language (can do from admin app)
3. Delete this new language. (can do from admin app)
4. Wait for Sentinel to process this deletion. 
5. Restart API. 
6. See error. 

**Expected behavior**
API should not crash when languages are deleted. 

**Logs**
```
2023-01-23 15:31:19 ERROR: Fatal error initialising medic-api 
2023-01-23 15:31:19 ERROR: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.loadTranslations (/home/diana/projects/medic/shared-libs/translation-utils/src/translation-utils.js:5:12)
    at /home/diana/projects/medic/api/src/services/config-watcher.js:32:55
    at Array.forEach (<anonymous>)
    at /home/diana/projects/medic/api/src/services/config-watcher.js:27:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/diana/projects/medic/api/server.js:38:5 {
  [stack]: 'TypeError: Cannot convert undefined or null to object\n' +
    '    at Function.keys (<anonymous>)\n' +
    '    at Object.loadTranslations (/home/diana/projects/medic/shared-libs/translation-utils/src/translation-utils.js:5:12)\n' +
    '    at /home/diana/projects/medic/api/src/services/config-watcher.js:32:55\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at /home/diana/projects/medic/api/src/services/config-watcher.js:27:23\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async /home/diana/projects/medic/api/server.js:38:5',
  [message]: 'Cannot convert undefined or null to object'
} 
```

**Environment**
- Instance: local
- App: api
- Version: 3.4.0+ would crash on malformed translation docs, but after 4.0 api will crash when languages are deleted because that will produce the "malformed" docs (tombstones of deleted translation docs) and serve them to translations utils. 

The workaround for 4.x projects encountering this is to delete all `messages-xx` tombstones and restart API.

**Comment by dianabarsan** [comment]
This is ready for AT on https://github.com/medic/cht-core/pull/8043

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `master`
Following the instructions in [the description](https://github.com/medic/cht-core/issues/8040#issue-1553309725) of the ticket, the API failed as reported.

<details>
<summary>Image attached.</summary>

![image](https://user-images.githubusercontent.com/94494491/220157672-098f220f-e65b-4cde-93a7-e34f8bba89c2.png)

</details> 

### Fixed on `8040-fix-messages-tombstones`
Re-creating the same scenario the API restarted with no issues.

<details>
<summary>Image attached.</summary>

![image](https://user-images.githubusercontent.com/94494491/220166082-14968a4d-9410-4343-b110-e1b98fd106ae.png)

</details> 

---

Test passed successfully. :tada:

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by NYARAS** [comment]
Is there a way to natively do this via a command line since it currently we are facing this and we cannot access the server? @dianabarsan

**Comment by dianabarsan** [comment]
Hi @NYARAS 
Is upgrading not an option? Simply replacing the docker-compose files with the ones from the newer version and just getting the fix for free? 

Deletion _can_ be done via command line, however it requires either:
- manually editing the docker-compose file to expose Haproxy or CouchDb directly to the host 
- writing a script that will read all tombstones: you would call `_all_docs?start_key="messages-"&end_key="messages-\ufff8"`, filter out all tombstones and `_bulk_docs` the deletions

OR 
- putting the above script in a container that you add to the same docker network as the pre-existing containers so it gains access to CouchDb directly. the script would be the same. 

Using command line exclusively is possible, but in my opinion is much more cumbersome to handle json to generate correct delete payloads, you are welcome to try though.

**Comment by NYARAS** [comment]
Hi @dianabarsan you mean v4.1.1?

I have update the images to that version but the issue is still there

**Comment by NYARAS** [comment]
Thank you @dianabarsan 

I was able to get this running with `v4.0.1` by deleting the tombstones command line using a custom Python script. Now the API is running successfully.

**Comment by kitsao** [comment]
Here's a rough script to help with tombstones deletion.
```
const axios = require(`axios`);
const COUCHDB_URL = `http://<user>:<password>@localhost`;
const DATABASE = `<database>`;

const deleteTombstoneTranslations = async() => {
  try {
    // Fetch all documents from the _changes feed
    const changesUrl = `${COUCHDB_URL}/${DATABASE}/_all_docs?start_key="messages-"&end_key="messages-\ufff8"`;
    const response = await axios.get(changesUrl);
    const changes = response.data.rows;

    // Filter and delete tombstones
    const tombstones = changes.filter(tombstone => tombstone.id.includes(`tombstone`));
    for (const tombstone of tombstones) {
      const docUrl = `${COUCHDB_URL}/${DATABASE}/${tombstone.id}?rev=${tombstone.value.rev}`;
      await axios.delete(docUrl);
      console.log(`Deleted tombstone: ${tombstone.id}`);
    }
    console.log(`Tombstones deleted successfully.`);
  } catch (error) {
    console.error(`An error occurred while deleting tombstones: ${error.message}`);
  }
};

deleteTombstoneTranslations();
```
cc @jonathanbataire
