### ISSUE TITLE
CouchDB entry point always saves `couch_httpd_auth` and `couchdb` to cluster-credentials.ini 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8067]
**Describe the issue**
The `docker-entrypoint.sh` does a check to ensure that `couch_httpd_auth` and `couchdb` are in `/opt/couchdb/etc/local.d/cluster-credentials.ini`. However, the check always fails, even when it shouldn't, so the credentials are always written to the file causing `cluster-credentials.ini` to endlessly grow.

**Describe the improvement you'd like**
fix [the entrypoint](https://github.com/medic/cht-core/blob/bbc99f92dbd936511281c718b163aaba65d5704e/couchdb/docker-entrypoint.sh) so the checks work as expected and only write the values to the ini file once

**Describe alternatives you've considered**
none

**Comment by latin-panda** [comment]
@mrjones-plip Is this still a work in progress? Should it be in 4.2.0?

**Comment by mrjones-plip** [comment]
yikes! i've left a mess of my tickets :disappointed: 

yups - should be added - closing!
