### ISSUE TITLE
Add a dropdown that gets populated with family members

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8074]
**Is your feature request related to a problem? Please describe.**
In a discussion about interoperability, this question came up: "How do I establish a relationship between two contacts?". For example, selecting the mother/father of a child in a contact create form. 

Right now, we only support db-object searches by doc type, not by parent. So users are left in searching the whole list of contacts of a certain type to find the correct selection. This can prove cumbersome with duplicate names - which is a common occurrence in our deployments. 

**Describe the solution you'd like**
Add support for db-object searches by parent. This can be a compound search by type and parent as well. 

**Describe alternatives you've considered**
Another idea is to inject the children of a place directly in the form (via contact summary for example). 

**Additional context**
Question came up in a session about interoperability with a partner, concerning an existing deployment.

**Comment by nKataraia** [comment]
I believe that solving this issue will enable us to create an accurate report for one of our important indicators. Currently, we are relying on estimates based on various heuristics. Therefore, we are eagerly looking forward to utilise this feature as soon as possible.

**Comment by iesmail-znz** [comment]
@dianabarsan, currently we also have use case where a supervisor chooses a list of CHVs from a drop down menu. The drop down shows a list of chvs + clients. A workaround is to set a replication depth of 2, but that prevents the supervisors from viewing clients.

**Comment by ChinHairSaintClair** [comment]
Related to [this](https://forum.communityhealthtoolkit.org/t/restrict-contact-select-to-a-specific-top-level-place/2803) CHT Forum thread.

In our case a CHW can be assigned work on multiple `households` and their `members`, the latter totaling in about 500 - many of which can have very similar names. 
It would be advantageous to 'restrict' the list of `members` returned by `select-contact` to a specific `household`.
Not only will that reduce the size of the list, it will also mitigate the issue where similarly named `member` from an entirely different `household` may be selected.

**Comment by michaelkohn** [comment]
@latin-panda can you please summarize the solution in the first comment of this issue?

**Comment by latin-panda** [comment]
Commonly, I add it in the PR's description for discussion with the reviewers, with test evidence and/or instructions, and so. 
To keep it practical, I am going to copy that and paste it here. Also, I prefer to not change Diana's text (the original author). 

## Solution

- This feature is applied when using the appearance:`descendant-of-current-contact`
- The scope remains for forms that are opened in the contact tab; it takes the contact ID from the URL. 
- It uses the CouchDB view `contact_by_parent` in combination with the contact type.

**Usage**
| type | name | label:en | appearance |
|------|-------|------|------|
| string | a-person | select a person | select-contact type-person descendant-of-current-contact |

[CHT Docs PR](https://github.com/medic/cht-docs/pull/1254)
