### ISSUE TITLE
Update default branding to CHT logo

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8075]
**What feature do you want to improve?**
The default branding for the CHT is the Medic flying phone.

**Describe the improvement you'd like**
Now that we have an official CHT brand we should update this to the new branding. This includes the login page, the header in desktop mode, and the favicon, and anywhere else you can find it.

**Describe alternatives you've considered**
We could stick with what we have but it'll help make it clear that the CHT is separate to Medic if we update the branding.

**Additional context**
The images are available here: https://drive.google.com/drive/u/0/folders/1VVLm9WbuNNFwpg0bf7qLa3uEcE3uDbRd
Work with @n-orlowski to confirm usage is consistent with our branding.

**Comment by garethbowen** [comment]
@n-orlowski If you have time would you mind reviewing this change? The idea is to completely remove the "medic" branding and use "cht" instead. If someone has already configured their own branding (most projects) then the logo and favicon won't update, but there is a change to the "about page footer".

# Desktop

## Login

![Screenshot from 2023-11-23 13-53-37](https://github.com/medic/cht-core/assets/2064938/9504db27-6f8e-45aa-99f4-5224d79f9662)

## Favicon

![Screenshot from 2023-11-23 13-52-10](https://github.com/medic/cht-core/assets/2064938/9596e068-64e8-4248-96eb-c3e71aaff6a5)

## Main page

![Screenshot from 2023-11-23 13-51-55](https://github.com/medic/cht-core/assets/2064938/914d40b3-d5fb-4ca4-849b-70a63c759eb4)

## About page footer

I'm not happy about the design here, but I was somewhat limited. It would be nicer to use the light background variant of the logo without the dark coloured card, but that would force users to download both versions. We should revisit this when we make the nav updates which remove the logo from the header.

NB: This footer **is not configurable**, meaning even if you change the branding of your app, this part will always say "CHT".

![Screenshot from 2023-11-23 13-52-40](https://github.com/medic/cht-core/assets/2064938/8f4a51b4-e2fe-444a-8c7c-f88f8f333f9c)

# Mobile

## Login

![Screenshot from 2023-11-23 13-53-23](https://github.com/medic/cht-core/assets/2064938/43cbfcb6-7072-450d-9da0-ee9a26387627)

## About page footer

![Screenshot from 2023-11-23 13-53-02](https://github.com/medic/cht-core/assets/2064938/7a8b83e1-eab2-4127-8a92-327d0f504715)

**Comment by n-orlowski** [comment]
Exciting!! Can we use the [stacked version](https://drive.google.com/file/d/1B9uveH4XB3hsmZym2bKeySQmjmBw7LXy/view?usp=sharing) for the login screen? Not at 100% width but maybe 70 or whatever feels appropriate. Might look a bit more balanced 🙂 

It's also looking a little large on the main page, could we align the logo to the top of the tab icons and bottom of the tab text?

**Comment by garethbowen** [comment]
> Can we use the stacked version for the login screen?

Both the login page and the header use the same logo set up in the branding configuration. This means you only need to configure and download one copy, but the downside is the login logo has to be the same ratio as the header logo (landscape). In a future where we remove the header logo this gives us a lot more flexibility for the login logo. Are you ok waiting until that redesign lands?

> It's also looking a little large on the main page, could we align the logo to the top of the tab icons and bottom of the tab text?

Yes I think you're right. It's also noticeably wider than the medic logo which isn't ideal. I'll look at scaling it down today.

Also I think I've figured out it's ok to use the light bg logo in the About page which will look much nicer IMO so I'll give that a try and get back to you.

**Comment by n-orlowski** [comment]
Cool, all sounds good to me!

**Comment by garethbowen** [comment]
Latest screenshots

# Desktop

## Header

![Screenshot from 2023-11-24 11-06-43](https://github.com/medic/cht-core/assets/2064938/8d4c250b-cf00-436a-bf82-266e04f6e296)

## About page footer

![Screenshot from 2023-11-24 11-06-56](https://github.com/medic/cht-core/assets/2064938/e600485f-00d8-4ad2-b7ed-bb7d5f0490af)

## Login

![Screenshot from 2023-11-24 11-07-38](https://github.com/medic/cht-core/assets/2064938/a473bed5-c656-4a89-8ffe-f057f3f73817)

# Mobile

## Login

![Screenshot from 2023-11-24 11-07-26](https://github.com/medic/cht-core/assets/2064938/e0081be1-20ee-4251-912a-9012f38437a5)

**Comment by garethbowen** [comment]
@n-orlowski I've added a little padding to the logo in the header so it lines up better. Also changed the about page footer to the alternate logo so it doesn't need to grey background color.

**Comment by n-orlowski** [comment]
LGTM ✨

**Comment by garethbowen** [comment]
Merged
