### ISSUE TITLE
`/api/v2/export/contacts` does not return useful contact type data for custom hierarchy

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8081]
**Describe the bug**
The [`/api/v2/export/contacts` endpoint](https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv2exportcontacts) returns a CSV file containing the following:

- id
- rev
- name
- patient_id
- type

Unfortunately, if a project is using custom hierarchy and the type information on the contact docs looks like `{ type: 'contact'
, contact_type: 'my_custom_type' }` then the `export` data will just contain `'contact'`  as the "type" value for all of the rows instead of returning the expected custom type data from `contact_type`....

**Environment**
- Version: 4.1.x+

**Comment by dianabarsan** [comment]
Merged to `master`.
