### ISSUE TITLE
Race condition: Tasks list briefly shows "No more tasks" before displaying available tasks. 

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8085]
**Describe the bug**
When loading the tasks list, even if there are tasks to display, the LHS will display "No more tasks" momentarily, before actually rendering the list. 
This would point to a race condition somewhere in the tasks controller. 
The race condition becomes more evident on a slow device. 

**To Reproduce**
1. Login as an offline user with a large number of active tasks (mine had 440 tasks). 
2. If in a browser, Throttle your CPU in the performance tab:
![image](https://user-images.githubusercontent.com/35681649/219869927-0aa3a12e-88f7-4826-bdce-9e151fa7d48e.png)
3. Load the tasks page.
4. See "No more tasks" before actually seeing the tasks list. This behavior is visible with every subsequent task list render, not only when there are tasks to be calculated.

**Expected behavior**
Keep showing the spinner until the task list can be rendered.

**Video (desktop browser with mobile resolution)**

https://user-images.githubusercontent.com/35681649/219870147-7148c7a8-1531-4868-a153-22461a56a9b0.mp4

**Environment**
- Instance: local
- Browser: Chrome
- App: webapp
- Version: 4.2.0

**Comment by michaelkohn** [comment]
Seen on People page as well


https://github.com/medic/cht-core/assets/10096985/b977e806-2576-4917-a461-2a5edf652e57

**Comment by mrjones-plip** [comment]
Happy to see this is captured as a bug already!  I had a 4s spinner followed by almost 7 seconds of  "No more tasks" - here's a video.  y'all know this already but just capturing it as a data point:

https://github.com/medic/cht-core/assets/8253488/42640c2a-234a-4e3a-91b6-77a46d9db0ce

**Comment by latin-panda** [comment]
This one still has feedback to resolve. 
Moving to the next week.
