### ISSUE TITLE
Implement a way of restricting which users are allowed to replicate

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8086]
**Is your feature request related to a problem? Please describe.**
Be it for performance reasons (for example: needing to prioritize certain users for replicating quickly) or for data integrity reasons (for example users that have orphaned contacts after a move contacts or a rollback), restricting replication to only some users has been a go-to solution for CHT projects a few times in cht history. 

A few of the ways this has been implemented:
- socially, by instructing some users to stop using their devices
- hot-patching the instance to add custom code which will produce the same result
- IP blocking at load balancer level 

None of the solutions above are easy or guarantee results: the social solution becomes inefficient very quickly for large projects, hot-patching with custom code is very risky, ip blocking requires that the target users have "stable" IPs and technical knowledge and accessibility to change the config of the load balancer. 

**Describe the solution you'd like**
Find way to:
- stop specific users from replicating (have an exclusions "list")
- allow only specific users from replicating (have an inclusions "list")

The user selection should be flexible, some example of criteria for selecting users can be: role, permission, username, facility_id (or facility ancestor). 
When a user is denied replication, their replication endpoint calls should respond with a status and error message that will stop the client from progressing replication (no "denied" errors for example, which do not stop replication progression). 
Changing the list of users should be easy, but be restricted to certain users (maybe only admins?). 

**Additional context**
Restricting replication, implemented socially, was the solution chosen by a partner when mitigating effects of moving most of the contacts in a large deployment.

**Comment by dianabarsan** [comment]
Closed as a duplicate of https://github.com/medic/cht-core/issues/8086

**Comment by garethbowen** [comment]
@dianabarsan You've linked this issue to itself - which issue is this a duplicate of?

**Comment by dianabarsan** [comment]
Sorry, I edited the comment to link to the correct issue.
