### ISSUE TITLE
Flaky test: Submit Default Delivery Report open, submit and edit default delivery form

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8087]
**Describe the issue**
This test is failing very frequently across multiple builds (10 out of the last 14 builds). It looks like selecting convulsions doesn't work and when the next page is clicked the validation fails stopped test execution.

```
[chrome 109.0.5414.119 linux #0-23] 6) Submit Default Delivery Report open, submit and edit default delivery form
[chrome 109.0.5414.119 linux #0-23] element (".action-container .general-actions:not(.ng-hide) .fa-plus") still not clickable after 15000ms
[chrome 109.0.5414.119 linux #0-23] Error: element (".action-container .general-actions:not(.ng-hide) .fa-plus") still not clickable after 15000ms
[chrome 109.0.5414.119 linux #0-23]     at async Object.openForm (/home/runner/work/cht-core/cht-core/tests/page-objects/default/reports/reports.wdio.page.js:79:3)
[chrome 109.0.5414.119 linux #0-23]     at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/enketo/submit-default-delivery-form.wdio-spec.js:216:5)
```

![image](https://user-images.githubusercontent.com/2064938/219972870-5ca0ff7b-262d-467b-b0c5-cd15d8490285.png)

**Comment by garethbowen** [comment]
I've made a go at this but it's not 100%. Leaving the attempt here for the record, but skipping the test for build stability for now.

**Comment by garethbowen** [comment]
No, the test is still disabled.

**Comment by andrablaj** [comment]
@lorerod can we close this issue? I see you marked it as `Done`.

**Comment by lorerod** [comment]
Yes @andrablaj it was close by [chore(#8701): Clean and organize e2e tests: folder /enketo](https://github.com/medic/cht-core/pull/8812#top)
