### ISSUE TITLE
Caught errors do not generate feedback documents.

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8089]
**Describe the bug**
Feedback docs get generated automatically on unhandled exceptions. Webapp has been getting better and better at catching errors and displaying useful/actionable data to the user, and also missing the trigger to create a feedback doc. 
Other examples of issues where we added feedback docs deliberately for specific errors: 
- https://github.com/medic/cht-core/issues/7363 - errors in task targets
- https://github.com/medic/cht-core/issues/6629 - errors in contact-summary
- https://github.com/medic/cht-core/issues/7525 - errors in loading forms

Feedback docs are essential for assessing app health, and are the easiest way to discover most common problems in deployments. 

This bug is about errors when saving reports (submitted through reports, contacts, tasks, training forms). 

**To Reproduce**
Steps to reproduce the behavior on saving a report:
1. Upload a form that should throw an error when saving. I picked one that I was already using in another issue: https://github.com/medic/cht-core/issues/8072 . If that gets fixed first, another bugged form is required. 
2. Submit this form. 
3. After submission fails, check generated feedback docs. 
4. See that no feedback doc was generated. 

**Expected behavior**
A feedback doc should be generated when a report cannot be saved. 

**Logs**
The error gets logged correctly. 

**Environment**
- App: webapp
- Version: 4.2.0 (has been the case for a long time, version TBD)

**Additional context**
There are probably more cases where we avoid feedback doc creation on potentially critical errors. 
**We should reconsider when automatic feedback doc generation is triggered.**

**Comment by kennsippell** [comment]
Example of another scenario not caught from @m5r 
https://github.com/medic/cht-core/pull/8164#pullrequestreview-1377421173

**Comment by dianabarsan** [comment]
Merged to `master`
