### ISSUE TITLE
Flaky test: Reports tab - Edit/export invisible when NON XML report selected

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8091]
**Describe the issue**

```
Error: element (".more-options-menu-container>.mat-mdc-menu-trigger") still not clickable after 15000ms
                    at async Object.openMoreOptionsMenu (/home/runner/work/cht-core/cht-core/tests/page-objects/default/common/common.wdio.page.js:33:3)
                    at async Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/more-options-menu/online-user/permissions-enabled.wdio-spec.js:109:7)
```

![image](https://user-images.githubusercontent.com/2064938/220213741-0480b529-34e4-4dac-b55b-6767579a3cf9.png)

**Comment by dianabarsan** [comment]
This test is failing repeatedly on master: https://github.com/medic/cht-core/actions/runs/4260638941/jobs/7414226353#step:16:979

**Comment by dianabarsan** [comment]
It looks like this test is initially failing another assertion: 

```
      actual expected
      
      truefalse
      
[chrome 110.0.5481.100 linux #0-35] AssertionError: expected true to be false
[chrome 110.0.5481.100 linux #0-35]     at Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/more-options-menu/online-user/permissions-enabled.wdio-spec.js:110:78)
```

https://github.com/medic/cht-core/actions/runs/4262996197/jobs/7419406672#step:16:944

And then the retry attempts are failing differently.

**Comment by dianabarsan** [comment]
It looks like this test is initially failing another assertion: 

```
      actual expected
      
      truefalse
      
[chrome 110.0.5481.100 linux #0-35] AssertionError: expected true to be false
[chrome 110.0.5481.100 linux #0-35]     at Context.<anonymous> (/home/runner/work/cht-core/cht-core/tests/e2e/default/more-options-menu/online-user/permissions-enabled.wdio-spec.js:110:78)
```

https://github.com/medic/cht-core/actions/runs/4262996197/jobs/7419406672#step:16:944

And then the retry attempts are failing differently.

**Comment by garethbowen** [comment]
Success rate as of today: 100%

**Comment by ngaruko** [comment]
This one seems to be passing consistently. Should we close this @garethbowen @dianabarsan ? Or have anyone observed failures in the last couple of months?

**Comment by dianabarsan** [comment]
I haven't seen this fail in a while. Closing.
