### ISSUE TITLE
Prevent data loss through re-sync when restoring data from backup

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8093]
**What feature do you want to improve?**
Data loss when restoring from backups is most likely unavoidable. 
However there is one mitigation we can deploy, with relatively little cost. 

First, follow these steps to reproduce how data loss happens now: 
1. Launch CHT (4.x is easiest, but this applies to every release since 2017) and create an offline user
2. Login as the offline user. 
3. Create a data backup. 
4. As the offline user, create some documents and sync. 
5. As the admin, check that the documents created on step 4 exist on the server. 
6. Overwrite live data with the backup (simulate a restoration from backup). 
7. Check that the documents created on step 4 don't exist on the server (this is expected, those docs were created AFTER the backup). 
8. Sync as the offline user. 
9. Check that the documents created on step 4 don't exist on the server. 

What happens on step 9 is caused by the way we save the replication checkpointer in Pouchdb: [at replication source](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/db-sync.service.ts#L88). This means that the document that holds the replication sequence for client uploads exists only on the client. The client doesn't know the server was restored from a backup, so it will keep uploading docs based on the locally stored sequence. This sequence is _after_ the docs created on step 4. 

**Describe the improvement you'd like**
PouchDb supports multiple settings for the `checkpoint`, and by default will save the checkpointer on both `source` and `target`. 
If the checkpointer is also saved on the target, when reaching step 9, PouchDb will check replication history on both checkpointers and choose the latest common seq. Because the server will have an older seq, the documents created on 4 will be re-uploaded. No data loss. 

With this approach, in case the server checkpointer becomes corrupted, is deleted, etc, the client will start replication from 0. This means that the local database is iterated over in batches and, for each batch, it will query a server endpoint (_revs_diff) to check whether the docs already exist. This endpoint is unfiltered, and requests are forwarded directly to CouchDb.  Only missing docs will be uploaded.
We should assess the performance impact of a client resetting replication, both for the client and for the server. 

When implementing this, we should also make sure that we somehow "start" by writing the server-side checkpointer, if possible, so we avoid all clients going through the process described above. 

**Describe alternatives you've considered**
Don't change anything. 

**Additional context**
We recently restored a production  deployment from a backup due to server-side data corruption.

**Comment by dianabarsan** [comment]
This is ready for AT on https://github.com/medic/cht-core/pull/8108

**Comment by lorerod** [comment]
> Do you think this is worth adding documentation for?
No, thank you. It is pretty straightforward.

**Comment by lorerod** [comment]
### Test details

**Config:** Standard
**Environment for reproduce:** Local using docker files [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml) and [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb.yml)
**Environment for testing branch:** Local using docker files [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8093-store-serverside-checkpointer/docker-compose/cht-core.yml), [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8093-store-serverside-checkpointer/docker-compose/cht-couchdb.yml) and [cht-couchdb-clustered.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8093-store-serverside-checkpointer/docker-compose/cht-couchdb-clustered.yml)
**Data**: upload data from [scalability test ](https://github.com/medic/cht-core/tree/master/tests/scalability)
**Phone:** Samsung Galaxy A01 with Android 10
**cht-android**: v1.0.0

---

### Test scenario:
I follow the steps mentioned in the  description of the issue.

### Reproducible using 4.1.0
<details>
<summary>Steps:</summary>

1. Login as the offline user ac1 on the phone.
2. Create a data backup. 
3. As the offline user, create a pregnancy and a delivery for Person2 at Clinic_1. And sync.
![Screenshot_20230420-111527](https://user-images.githubusercontent.com/21312057/233442251-77473952-c377-422a-93d8-6de767156987.jpg)

5. As the admin, check that the documents created on step 4 exist on the server.
![Captura de pantalla 2023-04-20 a la(s) 11 19 03](https://user-images.githubusercontent.com/21312057/233442363-0c9adccb-b080-48b5-a691-c3a9522a42d8.png)
![Captura de pantalla 2023-04-20 a la(s) 11 20 50](https://user-images.githubusercontent.com/21312057/233442400-c9d00467-23f2-449b-8aa7-5f37b03e318b.png)
![Captura de pantalla 2023-04-20 a la(s) 11 21 13](https://user-images.githubusercontent.com/21312057/233442408-ff8b2440-2ede-4cd0-97aa-5a2a6f9e51fc.png)


7. Overwrite live data with the backup. 
8. Check that the documents created on step 4 don't exist on the server. Also checked using Fauxton with the documents Ids.
![Captura de pantalla 2023-04-20 a la(s) 11 37 36](https://user-images.githubusercontent.com/21312057/233443365-a5a4cb69-f3e5-4ead-808b-6711a6243346.png)
![Captura de pantalla 2023-04-20 a la(s) 11 39 40](https://user-images.githubusercontent.com/21312057/233443374-0d650a62-3bdc-41e6-93cf-f4de86550f6b.png)

10. Sync with the offline user ac1 on the phone.
11. Check that the documents created on step 4 don't exist on the server. Also checked using Fauxton with the documents Ids.
![Captura de pantalla 2023-04-20 a la(s) 11 41 04](https://user-images.githubusercontent.com/21312057/233443484-82befb41-08d3-4e20-82b4-5662b7a15b18.png)
![Captura de pantalla 2023-04-20 a la(s) 11 41 31](https://user-images.githubusercontent.com/21312057/233443490-d65104ff-03d4-41f6-9d6f-59c135fa3713.png)

</details>

### Fixed on branch `8093-store-serverside-checkpointer` 
I follow the steps mentioned in the  description of the issue.
I repeated the steps also for clustered couchdb. Everything worked as expected.
I'm only documenting here for single couchdb not to repeat information.

<details>
<summary>Steps:</summary>

1. Login as the offline user ac1 on the phone.
2. Create a data backup. 
3. As the offline user, create a delivery for Person10 at Clinic_2. And sync.
![Screenshot_20230420-154125](https://user-images.githubusercontent.com/21312057/233484568-5838b029-9e9d-4234-9a23-564de8d7f8c6.jpg)

5. As the admin, check that the documents created on step 4 exist on the server.
![Captura de pantalla 2023-04-20 a la(s) 15 41 38](https://user-images.githubusercontent.com/21312057/233484728-29996fcb-4bda-4743-af40-ed7049a9e050.png)
![Captura de pantalla 2023-04-20 a la(s) 15 47 06](https://user-images.githubusercontent.com/21312057/233484733-ce36e94f-3c13-4fa2-9bf5-5efc90fb7f35.png)

7. Overwrite live data with the backup. 
8. Check that the documents created on step 4 don't exist on the server. Also checked using Fauxton with the documents Ids.
![Captura de pantalla 2023-04-20 a la(s) 15 55 46](https://user-images.githubusercontent.com/21312057/233484778-31a93f54-c2be-4de5-8ba1-23d6ac872ba8.png)

10. Sync with the offline user ac1 on the phone.
11. Check that the documents created on step 4 exist on the server. 
![Captura de pantalla 2023-04-20 a la(s) 16 05 06](https://user-images.githubusercontent.com/21312057/233484818-d047ab8a-9c9b-469e-92f4-8e7ece8e4caf.png)
![Captura de pantalla 2023-04-20 a la(s) 16 05 44](https://user-images.githubusercontent.com/21312057/233484823-93cdbfb7-449a-4ff6-b6ae-4378345f37aa.png)

</details>

---

Test passed successfully. :white_check_mark:
@dianabarsan I want also to compare the time that takes an initial load and a resync after resetting the checkpointer. Is there an easy way to reset it? Thanks!

**Comment by dianabarsan** [comment]
> I want also to compare the time that takes an initial load and a resync after resetting the checkpointer. Is there an easy way to reset it? Thanks!

You'd have to delete the document. You can see the uuid of it when you sync, because it gets written to the server, it's going to look like `/_local/<some_random_characters>`. You should either delete that from the client or from the server.

**Comment by lorerod** [comment]
### Test details

Same as [previous](https://github.com/medic/cht-core/issues/8093#issuecomment-1517173900) comment

---

### Test scenario:
Delete server checkpointer document. Time when sync.

###On branch `8093-store-serverside-checkpointer` 

<details>
<summary>Steps:</summary>

1. Log in in two different phones with offline users ac1 and ac2
2. With ac2 create a document and sync.
3. Found in the api log:
`api_1          | REQ c585153c-39f2-464d-b90e-9931d94a65bb 172.23.0.1 - GET /medic/_local/SlCQ7ZTo958uR5Qk9vRfmg== HTTP/1.0`
4. With admin user open `https://localhost/_utils/#database/medic/_local/SlCQ7ZTo958uR5Qk9vRfmg==`
5. Delete the document.
6. Sync with ac2. It took 1 minute 45 seconds. Similar to an initial sync as stated in [this](https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw) doc.
7. With ac1 create a document and sync. It took 9 seconds.
</details>

---

Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`

**Comment by dianabarsan** [comment]
Merged to `master`
