### ISSUE TITLE
Admin pass change in CHT 4.x breaks CHT, shows wrong error message

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8096]
**Describe the bug**

**To Reproduce**
1. Spin up a CHT 4.1.0 instance using [CHT Docker Helper](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/app-developer/#cht-docker-helper-for-4x)
2. login as user `medic` , password `password`
3. go to hamburger menu -> user settings -> update password
4. change password
5. Password change is accepted, but an error is shown stating it wasn't accepted "Password is not correct."
6. CHT instance stops working because the `COUCHDB_PASSWORD` value in the environment variable file is now wrong

**Expected behavior**
Either password change is not allowed because it will break CHT or password change works and all services use new password

**Logs**
```
<150>Feb 22 00:02:23 haproxy[25]: 172.19.0.7,couchdb,201,12,0,0,PUT,/_users/org.couchdb.user%3Amedic,api,medic,'{"_id":"org.couchdb.user:medic","_rev":"1-5b7bf3319f91c46105aa45fbef077b6c","name":"medic","type":"
user","roles":["admin"],"password":"***"}',414,10,85,'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)'                                                                                                      <150>Feb 22 00:02:23 haproxy[25]: 172.19.0.7,couchdb,200,3,0,0,GET,/_node/_local/_config/admins,-,medic,'-',324,2,97,'-'                                                                                           <150>Feb 22 00:02:23 haproxy[25]: 172.19.0.7,couchdb,200,3,0,0,GET,/_membership,-,medic,'-',253,1,74,'-'                                                                                                 
<150>Feb 22 00:02:23 haproxy[25]: 172.19.0.7,couchdb,200,7,0,0,PUT,/_node/couchdb@127.0.0.1/_config/admins/medic?raw=true,-,medic,'"-pbkdf2-21c4d152c87449a1cf60fd0989ca25f1307b1dc2,5b5034cec58639daf2022ab6e890c1358b604b9d,10"',314,5,87,'-'
<150>Feb 22 00:02:23 haproxy[25]: 172.19.0.7,couchdb,401,1,0,0,PUT,/medic/org.couchdb.user%3Amedic,api,medic,'{"_id":"org.couchdb.user:medic","_rev":"2-7035a74129b2bf8ff30347b2e51c4e59","name":"medic","type":"user-settings","roles":["admin"],"known":true}',359,0,67,'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)'
<145>Feb 22 00:02:27 haproxy[25]: Server couchdb-servers/couchdb is DOWN, reason: Layer7 wrong status, code: 0, info: "via agent : down", check duration: 208ms. 0 active and 0 backup servers left. 6 sessions active, 0 requeued, 0 remaining in queue.
<144>Feb 22 00:02:27 haproxy[25]: backend couchdb-servers has no server available!                                                                                                                                 [WARNING] 052/000227 (25) : Server couchdb-servers/couchdb is DOWN, reason: Layer7 wrong status, code: 0, info: "via agent : down", check duration: 208ms. 0 active and 0 backup servers left. 6 sessions active, 0 requeued, 0 remaining in queue.                                                                                                                                                                                   [ALERT] 052/000227 (25) : backend 'couchdb-servers' has no server available! 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8253488/220491302-6ae96812-42be-4c91-9b07-03e1b2baa558.png)

**Video**

https://user-images.githubusercontent.com/8253488/220491551-2609e50b-3827-4fc8-beed-59c6e6b1071b.mp4

**Environment**
- Instance: local dev
- Browser:  latest FF
- Client platform: ubuntu 
- App: webapp
- Version: 4.1.0

**Additional context**

The fix is to edit the `COUCHDB_PASSWORD` value in the environment variable file (`cht-core/scripts/docker-helper-4.x/*` in the case of Docker Helper) so that the env file password matches the new one you just changed it to.  Restart containers and everything works again.

Related tickets:
* #8076 - discovered here
* #6986  - possibly the last time this behavior was changed?

**Comment by dianabarsan** [comment]
I think the only safe way of fixing this is to **not** allow UI password changes for db admins, because the UI has no way to know which account is used in the docker environment.

**Comment by garethbowen** [comment]
@mrjones-plip Can I please get your blessing before I merge the PR? I've taken the most basic approach to deny admins from updating passwords to protect them from bricking their instance. Alternatives would be...

1. Having different kinds of admins - one type for services, and one for humans. Then the one for services cannot be changed, but the one for humans can be. I suspect this feature wouldn't get used much unless we forced it somehow, eg: changing the login page to block the service user from logging in.
2. Finding a way to update the environment so the password can be changed without requiring manual steps.

Overall I'm comfortable with the current PR and if we want could raise a feature request for a more advanced option if we think there's value. What do you think?

**Comment by mrjones-plip** [comment]
Yeah - while we could be more advanced about it per your alternatives, this is good:

![image](https://github.com/medic/cht-core/assets/8253488/dc575610-a44d-46c1-bdb1-09ea01728efe)

I also did a spot of regression testing and confirmed the feature still works for non-db admins.

nice job!

**Comment by garethbowen** [comment]
Merged!
