### ISSUE TITLE
Monitoring and Alerting for CHT 4 Self Hosting

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8114]
**What feature do you want to improve?**
Right now there's no easy way to monitor and alert on your CHT instance for folks who are [self hosting](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-single-node/).

**Describe the improvement you'd like**
Provide an out of the box solution that provides monitoring and alerting for [common monitoring metrics](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/).

**Describe alternatives you've considered**
Using the [App Monitoring data ingest](https://github.com/medic/cht-app-monitoring-data-ingest/) coupled with [superset](https://superset.apache.org/docs/intro/) might work, but feel that an off the shelf time series database (TSDB) plus off the shelf dashboard that already works well together would be a better fit for this.  As well, SRE has indicated they could bring more metrics to this as they use a TSDB + dashboard already internally.

**Additional context**
The goal of this is that the alerts need to be both relevant and actionable.  To that end, this solution should:
* try to get as many P0's from "App Health Metrics" from [App Serv project](https://docs.google.com/document/d/1Slr0Bs2oXg6uqX4XKma5c5jzQ1fMJYkwlIO_bRlJmvc/edit#heading=h.1u4z3n85mbaf) (private google doc) 
* hopefully get all of the monitoring API metrics for "free" with a cheap "get all the JSON" recipe from the which ever solution is chosen. 
* Cover key metrics from the [published monitoring doc](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/)

**Comment by jkuester** [comment]
Status update (mostly for @mrjones-plip's benefit since he will be back on Monday and I will be off on Monday):

Currently have working configuration for deploying the stack needed to scrape CHT `/monitoring` stats, recording them in Prometheus, and view them in Grafana.  We even have a prototype Grafana dashboard: 

![image](https://user-images.githubusercontent.com/8441903/226021514-959a72b0-0f21-4caa-83d3-7517b73b865e.png)

- Code is currently in: https://github.com/jkuester/cht-monitoring/tree/8114_metrics_mvp
    - Basic instructions for using config are in the README
- Test instance has been deployed at https://cht-monitoring.kuester7.com/
    - Credentials are [in 1Password](https://start.1password.com/open/i?a=FS6VLBPCXJGBTFO3LV4R74OA6E&v=3xw7qcbg2snbgpt3j25bljlmlm&i=qqg33r5xtk6h4eyahy6u2tia3q&h=medic.1password.com)
    - Test instance is currently "scraping" fake data from a fake endpoint.  (This way because the low traffic on instance like Gamma is not very useful when trying to craft dashboard panels. Code for that is in [this branch](https://github.com/jkuester/cht-monitoring/tree/8114_metrics_mvp_test)

TODO:
- [ ] Figure out how to sideload test data into Prometheus
    - This will be really important for testing the dashboard (particularly the parts of the dashboard that require specific data generated over periods of time...)
- [ ] ALERTING - I have started looking at this. The good news is that Grafana has built-in support for sending at least email alerts (if you give it connection info for an SMTP server).  
    - Need to do some thinking on the best way to test this.
- [ ] Finalize the dashboard(s) configuration. I demoed what I currently have with Tatiana and Nicole.
- [ ] Think through "upgrade paths" for the various components
    - The applications (Prometheus/Grafana) versions can be controlled by the `.env` config
    - The config for mapping from `/monitoring` to Prometheus metrics is a little more tricky
        - As I pointed out [in this issue](https://github.com/medic/cht-core/issues/8124) adding anything to `/monitoring` is going to require _everyone_ using this monitoring config to update their mapping in order to see the new metrics in Grafana.
        - Gareth mentioned that at one time the CHT had undocumented support for directly returning Prometheus-style metrics, and he is not opposed to re-including that support now that we actually have a use for it.
        - We will need to decide if this needs to be a part of the MVP or if we have an update path from our current approach to one where Prometheus can just scrape the CHT directly....
    - For the Dashboards, we can always update the default config we ship with dashboards, but we need to figure out the experience for existing instances when the data in `grafana/provisioning/dashboards` changes

**Comment by jkuester** [comment]
FTR, here is the commit that removed the original OpenMetrics support from CHT api.

[`788b603` (#6240)](https://github.com/medic/cht-core/pull/6240/commits/788b603588a20ce8f1f1f9986ec79b1f7da2cae1)

(Not sure this ever actually made it into `master` at all...)

**Comment by jkuester** [comment]
Whoops, got carried away and merged this without QA!  :sweat_smile: 

@tatilepizs the PR review for this is complete and ready for your final review!  (Can just use the `main` branch over in https://github.com/medic/cht-monitoring),

**Comment by tatilepizs** [comment]
I didn't test again because we all worked together during the development process so at this point I feel like it is ready 😄 

Moved it to `Done` because it was already merged. Thanks @jkuester 🎉
