### ISSUE TITLE
Update contribution link on the cht-core 

### ISSUE THREAD

**Issue by esthermmoturi** [medic/cht-core#8115]
**What feature do you want to improve?**

Change the link on this [cht-core issues page](https://github.com/medic/cht-core/issues)

**Suggested improvement**

Change the link to point to the [contributor handbook](https://docs.communityhealthtoolkit.org/contribute/) rather than loop to a [contributing.md file](https://github.com/medic/cht-core/blob/2e978aa7ffd960f9250d4cd214fd52e3cce611bc/CONTRIBUTING.md) that points them to the docsite.

![image](https://user-images.githubusercontent.com/2064938/223177471-6249ae0a-039e-42ae-aecb-b054b308380f.png)

**Comment by garethbowen** [comment]
Unfortunately this link is not configurable. If you have a `CONTRIBUTING.md` then it is used. If you don't have it, then the link is not shown. With those two options I think what we have is the best option.

If anyone knows of a better way, please reopen!
