### ISSUE TITLE
Feedback Document - Could not evaluate: format-date-time(..), message: globalThis is not defined

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#8143]
I'm seeing feedback documents with these correlated messages about `globalThis`:

`Could not evaluate: format-date-time(../dob_raw,"%Y-%m-%d"), message: globalThis is not defined`
`Uncaught (in promise): FormLogicError: Could not evaluate: format-date-time(../dob_raw,"%Y-%m-%d"), message: globalThis is not defined`
`Failed during the form "communication" rendering : ["FormLogicError: Could not evaluate: if( /model/instance[1]/communication/g_evaluation/done_today ='yes',format-date-time(now(), \"%d/%m/%Y\"),format-date-time( /model/instance[1]/communication/g_evaluation/done_date , \"%d/%m/%Y\")), message: globalThis is not defined"]`

Overall there are about 21 documents affecting 1 user. 

**Environment**
- Instance: moh-mali-chw
- App: cht-core
- Wrapper: cht-android 1
- Version: 4.1

**User Details**
```
  "device": {
    "screen": {
      "width": 320,
      "height": 570
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 8.1.0; TECNO F1 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36 org.medicmobile.webapp.mobile.moh_mali_chw/v1.0.4-1",
    "deviceInfo": {
      "app": {
        "version": "v1.0.4-1",
        "packageName": "org.medicmobile.webapp.mobile.moh_mali_chw",
        "versionCode": 100040100
      },
      "ram": {
        "free": 380968960,
        "total": 994189312,
        "threshold": 150994944
      },
      "network": {
        "upSpeed": 59,
        "downSpeed": 236
      },
      "storage": {
        "free": 297451520,
        "total": 5642911744
      },
      "hardware": {
        "model": "TECNO F1",
        "device": "TECNO-F1-PRO",
        "cpuInfo": {
          "arch": "armv7l",
          "cores": 4,
          "model name": "ARMv7 Processor rev 3 (v7l)"
        },
        "hardware": "mt6580",
        "manufacturer": "TECNO"
      },
      "software": {
        "osVersion": "3.18.79(EFG-190619V11)",
        "osApiLevel": 27,
        "androidVersion": "8.1.0"
      }
    },
    "hardwareConcurrency": 4
  },
```

**Comment by kennsippell** [comment]
Related: https://github.com/medic/cht-core/issues/8113

**Comment by kennsippell** [comment]
In release notes for 4.0 there is "Browser users have the most recent version of Chrome or Firefox". This users is running Chrome 70.  Do we know approximately what version is actually required? Is there a recommended procedure for users to update Chrome - would it just be through PlayStore?

https://docs.communityhealthtoolkit.org/core/releases/4.0.0/#updated-browser-and-android-requirements"

**Comment by garethbowen** [comment]
> Is there a recommended procedure for users to update Chrome - would it just be through PlayStore?

Yes Play Store is the easiest if you have it, or you should be able to side load. Either the browser itself or the webview app if using an apk. There are some very brief instructions in the [4.0.0 release notes](https://docs.communityhealthtoolkit.org/core/releases/4.0.0/#updated-browser-and-android-requirements) - if you have suggestions to make these more useful please let me know!

@jkuester Given this is now affecting an actual user, how do you feel about patching `globalThis` out before we release 4.2.0? While we don't support Chrome 70 we don't need to break it if there's an easy alternative.

**Comment by garethbowen** [comment]
@jkuester Ok you've convinced me. Also our [supported version check in the code](https://github.com/medic/cht-core/blob/master/api/src/public/login/script.js#L192-L198) checks for Chrome >= 80 so hopefully users are at least notified that something is wrong before they hit this, although they may need this change to actually be notified: #7770

**Comment by kennsippell** [comment]
Can we clarify in release notes that Chrome 80 is required for cht-core 4.x?

**Comment by garethbowen** [comment]
I think the support matrix is clear as per [your comment](https://github.com/medic/cht-core/issues/8143#issuecomment-1481477842). But I think what you're saying is you'd like to change the minimum browser requirement, is that right?

**Comment by derickl** [comment]
We should fail loudly if the minimum browser requirement is not met. In the same way we are clear on the minimum android os version, we should be clear on the minimum chrome version (and other requirements).

**Comment by garethbowen** [comment]
@derickl Would you mind raising an issue saying just that?
