### ISSUE TITLE
Secondary risk factors are not returned if primary risk factors are present in getRiskFactorsFromPregnancy()

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#8144]
In a default config, contact-summary's [getRiskFactorsFromPregnancy(report)](https://github.com/medic/cht-core/blob/master/config/default/contact-summary-extras.js#L132) method doesn't return secondary risk factors if there are primary risk factors present. This method is supposed to return all risk factors regardles of one's existence. Below is the code that's causing this issue in Line 147.

https://github.com/medic/cht-core/blob/990104cb82d7666668973346f4be8d9dcb3de7c7/config/default/contact-summary-extras.js#L144-L149

Many CHT projects use the helper mehtods provided in contact-summary-extras to start the config with and might have carried this issue along. We've similar issue in [CHIS](https://github.com/medic/config-nssd/blob/master/contact-summary-extras.js#L147-L161).

**Comment by garethbowen** [comment]
Closing as complete. Please reopen if there's something I've missed.
