### ISSUE TITLE
E2E builds fail for external contributors because of allure history jobs

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8151]
**Describe the issue**
When running a build as an external contributor, they always fail because the script tries to upload allure history to main, but fails because of lacking secret credentials. 
```
Started: bash /home/runner/work/_actions/actions-js/push/master/start.sh
Push to branch main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
```

example run: https://github.com/medic/cht-core/actions/runs/4514911375/jobs/7951825941?pr=8145

**Describe the improvement you'd like**
Skip all allure-history building for external contributor builds.

**Comment by garethbowen** [comment]
The building is still useful because it gets attached as an artefact, but we should definitely skip the uploading step!

**Comment by garethbowen** [comment]
Merged.
