### ISSUE TITLE
API Changes watcher skips changes - or becomes blocked

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8173]
**Describe the bug**
I believe this is a race condition, as it has been only reported twice, as far as we know. 
Once was [on the forum](https://forum.communityhealthtoolkit.org/t/404-error-on-model-xml/2455/11) and once on [slack](https://medic.slack.com/archives/C024KTGRW/p1680869810577819). 
On slack, I was able to log into the instance and personally checked this was happening. I updated a form document and saw nothing appear in the api logs about receiving a change. 
Restarting API fixed the issue. 

I believe this is a race condition. I'll examine the instance logs for clues and update with findings. 

**To Reproduce**
1. Load CHT 4.1.0
1. Wait 10 seconds. 
1. `docker restart <your haproxy container>` or `docker restart <your couchdb container>`
1. Upload a new form
1. Load the new form in webapp and see error. When checking the console, you'll see a request to get `model.xml` and `form.html`, and both would fail with a 404. 

**Expected behavior**
Form attachments should be generated by changes watcher on the fly. 

**Logs**
No logs. no errors.

**Environment**
- Instance: test instance
- App: api
- Version: 4.1.0

**Comment by garethbowen** [comment]
If this is common it'll be quite serious, so I've scheduled it to 4.3.0 for investigation and possible fix.

**Comment by dianabarsan** [comment]
I've tried to replicate it, and have not been successful so far. 
My initial guess was that there is some de-sync where the changes watcher request became cancelled on by the server (either haproxy or couchdb), but remained pending for the client (either haproxy or api), because in the instance where this happened, there was an interval of two days with no writes. 
I'll resume checking logs for anything suspicious.

**Comment by dianabarsan** [comment]
I've replicated this by killing CouchDb or HAproxy after the first 10 seconds of the live changes request was started. I don't think this is a 4.x isolated issue, because I replicated this while running api / couchdb without haproxy layer, but will confirm.

**Comment by dianabarsan** [comment]
Confirming this did not happen in `3.x`. I restarted CouchDb in medic-os with /boot/svc-restart and API crashed when that happened.

**Comment by dianabarsan** [comment]
I've narrowed this down to an interaction in the PouchDb changes request when running in Node 14 and higher. 

I'm running this code snippet: 
https://gist.github.com/dianabarsan/57ece72ad9548fb14c14b0a55fa3a622

And this is the output I get for various node version: 

```
// node 8
10s passed
Error watching changes { FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input
    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input',
  type: 'invalid-json',
  [stack]: 'FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input\n    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)' }
```

```
// node 10
10s passed
Error watching changes { FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input
    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input',
  type: 'invalid-json',
  [stack]:
   'FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input\n    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

```
// node 12
10s passed
Error watching changes FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input
    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input',
  type: 'invalid-json',
  [stack]: 'FetchError: invalid json response body at http://127.0.0.1:6984/medic/_changes?feed=longpoll&heartbeat=10000&since=1380893-g1AAAAFreJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____s5IYmJan41GXpAAkk-yhSuefwKfUAaQ0Hqp0jhs-pQkgpfVQpQs68CjNYwGSDA1ACqh6Pkj56k0ElS-AKN8PUj7XiqDyAxDl98Gm6xBU_gCiHOz2WRxZAAfQZtI&limit=25 reason: Unexpected end of JSON input\n' +
    '    at /home/diana/projects/medic-utils/node_modules/node-fetch/lib/index.js:273:32\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  name: 'FetchError'
}
```

However, this is what is logged when running with Node 14+: 

```
// node 14
10s passed
```

```
// node 16
10s passed
```

**Comment by dianabarsan** [comment]
It looks like someone reported something similar: https://github.com/pouchdb/pouchdb/issues/8608

**Comment by dianabarsan** [comment]
It looks like this gets fixed in the latest version of node-fetch@2. 
https://github.com/node-fetch/node-fetch/releases/tag/v2.6.8 https://github.com/node-fetch/node-fetch/pull/1064

**Comment by garethbowen** [comment]
Moved to "in progress" as we've decided to remove the "AT" statuses. @dianabarsan Please work with teammates until you're confident to merge this.

**Comment by dianabarsan** [comment]
Thanks a lot @ngaruko 

I think the entrypoint warnings (first quote) are things that we should fix separately, I already have fixes for those in my couchdb 3 upgrade branch. 
The `unknown_error : normal` couchdb warnings are just noise, which was fixed upstream in a later version - which we will also get with the CouchDb 3 upgrade: https://github.com/apache/couchdb/issues/1600

Besides these, do you have any other concerns?

**Comment by dianabarsan** [comment]
Merged to `master`.
