### ISSUE TITLE
More Options Menu visible in LHS when resizing from desktop to mobile

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8177]
**Describe the bug**
More Options Menu is visible in LHS when resizing from desktop to mobile

**To Reproduce**

https://user-images.githubusercontent.com/66472237/231794129-35365678-9b82-4a36-b104-5ef265ee79fa.mp4

**Expected behavior**
No More Options Menu in LHS when resizing from desktop to mobile

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 4.2.0 (to be released)

**Comment by latin-panda** [comment]
@lorerod and @tatilepizs  
This is ready for AT in this [PR](https://github.com/medic/cht-core/pull/8178), it was a quick fix.

**Comment by tatilepizs** [comment]
### Test details

**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

#### Reproducible on `7998-fast-action-button`

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/232091922-efbebfe1-ae1c-45e9-86b4-5641b0664bb4.mov)

</details>

#### Fixed on `8177-more-options-screen-resize`

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/232092170-285d403b-dff3-40d6-bd5b-ede59198361b.mov)

</details>

---

Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`
@latin-panda

**Comment by latin-panda** [comment]
@tatilepizs Thank you 🙏
