### ISSUE TITLE
nginx and haproxy should respect `Accept` headers when responding with error templates

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8179]
**What feature do you want to improve?**
Both nginx and haproxy use the default error templates for 4xx and 5xx responses. These templates are html. 
Respecting the `Accept` header would standardize the behavior of the CHT, and this is important since we expect third party software to call CHT APIs. 

To reproduce: 
- start CHT 4.x 
- stop your api container `docker stop <api container name>`
- request a JSON response from API: 
```shell
curl -k https://localhost -H 'Accept: application/json'
```
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.6</center>
</body>
</html>
```

If you are logged into webapp, you will see a JSON parse error spammed in the console: 
![image](https://user-images.githubusercontent.com/35681649/232050203-f0b152b0-fe75-4156-bece-2765155dc3b0.png)

**Describe the improvement you'd like**
We should change nginx and haproxy configs to respond with JSON when the `Accept: application/json` header is passed. 

**Describe alternatives you've considered**
Leave it as it is. 

**Additional context**
I had a script that passed the result of an API call to `jq`. Because the response was html, my `jq` call failed. 
Similarly, we've seen reports of feedback docs being generated that feedback docs get generated in webapp when with `Unexpected token < in JSON at position 0`:

https://github.com/medic/cht-core/issues/6412
https://github.com/medic/cht-core/issues/7782

**Comment by garethbowen** [comment]
> Similarly, we've seen

The suspense is killing me!

**Comment by dianabarsan** [comment]
> The suspense is killing me!

Apologies. Resuscitation in progress.

**Comment by mrjones-plip** [comment]
Also noting that the lack of a proper JSON and sending HTML instead affects [more tickets than the two above](https://github.com/search?q=repo%3Amedic%2Fcht-core+%22Unexpected+token+%3C+in+JSON%22&type=issues). Spot checking one, I found:  "This indicates that CouhchDb is down and Haproxy responds with html instead of JSON" [#7759](https://github.com/medic/cht-core/issues/7759#issuecomment-1260451501).

A fix to this will be a welcome addition!

**Comment by nydr** [comment]
We have suggested that HAProxy error pages to be JSON only since HAProxy is not externally available
