### ISSUE TITLE
Remove old design that was replaced by Material design 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8181]
**Describe the issue**
We have been replacing some UI features in webapp as part of the UI/UX Evolution to adopt Material design. Now that we are going to build the last stage, navigation, it is a good time to deprecate and remove the old design.

**Describe the improvement you'd like**
Remove old design:

- [x] Seach: Report & Contact
- [x] All filters: Reports 
- [x] Botton action bar
- [x] Update e2e

**Comment by witash** [comment]
@latin-panda should we move this to 4.12?

**Comment by latin-panda** [comment]
@witash done! Thanks

**Comment by latin-panda** [comment]
Code merged ([PR](https://github.com/medic/cht-core/pull/9361))
