### ISSUE TITLE
Remove Guided Tour and Welcome message

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8185]
**Is your feature request related to a problem? Please describe.**
It's a good time to remove the Guided Tour, since we now have the [Training Cards](https://docs.communityhealthtoolkit.org/apps/guides/training/training-cards/) ([ticket](https://github.com/medic/cht-core/issues/6598)), which projects can customize and deliver remote short trainings to their CHWs. 

The CHT now has a place where projects can get templates of trainings cards that explains features from the CHT Framework, these can be adapted to specific scenarios. 

Also, most projects do their initial trainings with CHWs on-site, and users might not get to see the Guided Tour popping up on their first login. 

**Describe the solution you'd like**
Remove the Guided Tour from webapp, since Training Cards can cover the same training this tool offers.  

We are also removing the welcome message and displaying the user the Guided Wizard Configuration right away, if `setup_complete` config property is `false` to avoid extra steps/clicks when using the app for the first time.

![Screenshot 2023-04-17 at 6 04 16 PM](https://user-images.githubusercontent.com/66472237/232638420-0ed08318-75c7-4804-96c0-e0e8818a809a.png)

**Describe alternatives you've considered**
- Leave it there. 

**Additional context**
The Guided Tour sometimes displays dialogs explaining missing elements on the screens.

**Comment by latin-panda** [comment]
We need to update the docs: 
- https://docs.communityhealthtoolkit.org/apps/concepts/navigation/
- https://docs.communityhealthtoolkit.org/apps/tutorials/application-settings/ - Frequently Asked Questions section
- https://docs.communityhealthtoolkit.org/core/overview/db-schema/
- https://docs.communityhealthtoolkit.org/apps/reference/api/

**Comment by garethbowen** [comment]
This also closes...

- https://github.com/medic/cht-core/issues/6739
- https://github.com/medic/cht-core/issues/6738
- https://github.com/medic/cht-core/issues/6105
- https://github.com/medic/cht-core/issues/5682
- https://github.com/medic/cht-core/issues/5681
- https://github.com/medic/cht-core/issues/5680
- https://github.com/medic/cht-core/issues/5679
- https://github.com/medic/cht-core/issues/5597
- and probably some I didn't find...

**Comment by garethbowen** [comment]
@latin-panda Now that 4.2.x has been branched off, feel free to merge this!

**Comment by latin-panda** [comment]
Merged
