### ISSUE TITLE
Remove configuration wizard

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8190]
**Describe the issue**
Related [forum post](https://forum.communityhealthtoolkit.org/t/configuration-wizard/2670).

The configuration wizard will be displayed the first time a user logs in if the user has the `can_configure` permission and the `setup_complete` property in `app_settings` is `false`. Closing this screen (even without setting anything) updates `setup_complete` to `true` and the screen does not show up again (but is still accessible from the hamburger menu). 

**Step 1** The modem setup, is only needed if you’ll be sending SMS which isn’t the first concern for most projects anymore.

<img width="600" alt="Screenshot 2023-04-19 at 9 22 59 am" src="https://user-images.githubusercontent.com/66472237/233123482-65831354-41e8-4a99-ac31-113f459f91c2.png">

 **Step 3** The language preference, is mostly useful for translating SMS messages, now users on smartphones pick their own language when they log in.

<img width="600" alt="Screenshot 2023-04-19 at 9 23 44 am" src="https://user-images.githubusercontent.com/66472237/233123675-e15f3c4e-ddaa-4099-85f7-f2e9e2ddc51e.png">

**Step 2** ( Identify Care Coordinators) and **Step 4** (Registration form) aren't being used anywhere. it was probably useful in the DIY days, but less so today. 

<img width="600" alt="Screenshot 2023-04-19 at 9 23 28 am" src="https://user-images.githubusercontent.com/66472237/233123581-5a47ce97-6721-4e22-80a7-047b7255fef6.png">

<img width="600" alt="Screenshot 2023-04-19 at 9 24 33 am" src="https://user-images.githubusercontent.com/66472237/233123887-a117230b-2476-4fb2-8c39-43dcaaf0fdf6.png">

**Describe the improvement you'd like**
Remove the configuration wizard from webapp

**Describe alternatives you've considered**
Leave it there and fix the UI to explain better the steps and make it more friendly.

**Comment by garethbowen** [comment]
@latin-panda Now that 4.2.x has been branched off, feel free to merge this!

**Comment by latin-panda** [comment]
Merged
