### ISSUE TITLE
Nginx can't connect to API after container restarts because of dynamic IP allocation

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8205]
**Describe the bug**
Docker allocates dynamic IPs within a network. When a container restarts, there's a chance the IP changes. However nginx caches DNS queries to backend servers and never tries them again. 
As a result, after an API restart and IP change, nginx fails to connect. 

This is a known issue: 
https://github.com/docker/compose/issues/3314
https://stackoverflow.com/questions/27912917/how-to-configure-docker-port-mapping-to-use-nginx-as-an-upstream-proxy
https://serverfault.com/questions/722438/nginx-refresh-upstream-server-ip
https://stackoverflow.com/questions/63154521/connect-failed-113-host-is-unreachable-while-connecting-to-upstream-nginx-f

**To Reproduce**
1. Start CHT 4.
1. Run `docker network inspect <your network name>` and check API's IP
1. Restart some containers to get IPs to swap. I used: 
```docker stop <haproxy> -t 0 && docker stop <api> -t 0 && docker start <haproxy> && docker start <api>```. 
For some reason, when restarting a single container, I never got an IP change, but did get it quite consistently when restarting two. 
1. Wait for one minute - or make sure everything is up and running by checking container logs. Make a request to the server. 
1. Get 502. 

**Expected behavior**
nginx should be able to remap backends ips. 

**Logs**
```
2023/04/27 21:19:33 [error] 41#41: *8603 connect() failed (111: Connection refused) while connecting to upstream, 
client: 172.30.0.1, server: , request: "GET /api/info HTTP/1.1", upstream: "http://172.30.0.7:5988/api/info", 
host: "localhost"
172.30.0.1 - admin [27/Apr/2023:21:19:33 +0000] "GET /api/info HTTP/1.1" 502 157 "-" "-"
```

The IP of api was `172.30.0.6` at this point. 

**Environment**
- App: nginx
- Version: 4+

**Additional context**
I discovered this when working on https://github.com/medic/cht-core/issues/8173, after adding an e2e test that restarted haproxy, which resulted in an expected API restart as well. Once API was up, nginx could not connect. 
Restarting nginx fixes this issue.

**Comment by dianabarsan** [comment]
This is ready for AT on https://github.com/medic/cht-core/pull/8206. 
The solution is to force nginx to re-resolve all DNS entries every 10 seconds. What you should see is that 10s after API is up again, with a new IP, nginx should successfully connect and proxy requests.

**Comment by mrjones-plip** [comment]
Initial steps to reproduce fail:

* Docker version 23.0.5, build bc4487a
* Docker Compose version v2.11.2
* CHT 4.0.1 on CHT Docker Helper

Here's a video showing IPs don't change and `502`s only happen briefly while services restart.  I'll dig into this more!

https://user-images.githubusercontent.com/8253488/235746881-9a29bd9d-a6dd-4f0a-bc87-4de6aab189e8.mp4

**Comment by mrjones-plip** [comment]
After testing some more, I still can not reproduce the issue.  I tried on a [production style](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-single-node/) CHT 4.1.0 install and on Ubuntu 22.04 (vs my daily driver 20.04 desktop) with a clean install of docker.  The main problem is that I never had the docker IPs for API and HAProxy change after the initial `docker compose up -d`.  

Here's how I tested:
1. Run this `watch -n .1 ./show.ips.sh` with `show.ips.sh` being:
   ```
   #!/bin/bash
   docker inspect -f '{{ .Name }} {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps --quiet) | egrep 'api|hapro'
   ```
2. Run this, waiting for the IPs to change in above script:
   ```
   watch -n 4 "docker stop cht_haproxy_1 -t 0 ;docker stop cht_api_1 -t 0 ;docker start cht_haproxy_1 ; docker start cht_api_1"
   ```

Noteworthy, I was unable to reproduce the issue in using images from `4.0.1`, `4.1.0` and `4.2.0-8205-add-nginx-resolver` - so there no regressions, just not the bug cited in the issue :disappointed: 

@garethbowen  - were you able to reproduce?

I'll try and grab @dianabarsan soon so we can figure what's next!

**Comment by garethbowen** [comment]
I haven't tired to reproduce this, sorry. Can you force the IP change by forcing an IP collision or something?

**Comment by dianabarsan** [comment]
@mrjones-plip 
What version of docker are you running?

**Comment by mrjones-plip** [comment]
I tested on two setups.  Setup 1:

* `docker -v`: Docker version 23.0.5, build bc4487a
* `docker-compose -v`: Docker Compose version v2.11.2  <--- using separate binary)

Setup 2:
* `docker -v`: Docker version 23.0.5, build bc4487a
*  `docker compose version`:  Docker Compose version v2.17.3

**Comment by dianabarsan** [comment]
Ok. I have `docker -v`: Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
And got the IP swap consistently.

**Comment by mrjones-plip** [comment]
aha! lemme get VM or something w/ the old version and see if I can reproduce.

**Comment by mrjones-plip** [comment]
Hrm - I still can't get the IPs to switch.  I'm using the [two commands from above](https://github.com/medic/cht-core/issues/8205#issuecomment-1531907769), and you can see in this video they always come back the same:

* Ubuntu 18.04
* Docker version 20.10.21, build baeda1f

https://user-images.githubusercontent.com/8253488/235826760-f4135648-37cb-4f62-8122-e23d985ef30b.mp4

I'll try @garethbowen's approach of starting a service on the last IP of one of the services while it's down, but now that I'm on my 3rd system, maybe this was endemic to Diana's environment?

**Comment by dianabarsan** [comment]
> maybe this was endemic to Diana's environment?

This would be very weird. 
I think I have an explanation, tho! I've been experimenting a little locally and I've observed that docker-compose kinda "reserves" those IPs in a network. So you have 2 containers with IPs X and Y, and you restart them, they will end up using IPs X and Y, and will get assigned these IPs in ascending order. 

In your case, API had *.7 and haproxy has *.5, if you start haproxy first, it will get *.5. 
When you see this, can you switch the restart sequence so that you start the container with the higher old IP first? In your particular example: 
```
watch -n 4 "docker stop cht_haproxy_1 -t 0 ;docker stop cht_api_1 -t 0 ; docker start cht_api_1 ; docker start cht_haproxy_1 "
```

**Comment by mrjones-plip** [comment]
wow!  This is brilliant work here.  I got the `502` right away when I switched the order.  Crazy times.

now lemme try the new image and see if it fixes it :crossed_fingers:

**Comment by mrjones-plip** [comment]
Sweet - that worked!  Whew - glad you figured that out - extra nice!

AT passes

**Comment by dianabarsan** [comment]
Merged to `master`.
