### ISSUE TITLE
Change extension libs API so libs are modules not functions

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8210]
**What feature do you want to improve?**
Extensions libs (introduced in #7824) are provided as functions/objects as an attachment. This works but it's not consistent with contact summary, tasks, targets, and purging interfaces, and it makes it harder to unit test.

**Describe the improvement you'd like**
Change the API so the extension libs files use `module.exports` rather than returning a function/object.

**Describe alternatives you've considered**
Support both somehow, but let's be opionated about it before changing means breaking backwards compatibility.

cc @kennsippell

**Comment by garethbowen** [comment]
Scheduled in 4.2.0 because if we fix it before release we don't break production usage.

**Comment by tatilepizs** [comment]
### Test details

Using the [lib example](https://github.com/medic/cht-core/issues/7824#issuecomment-1470598390) provided in the original ticket (#7824) the test using `module.exports` works as expected.

#### Steps to test:

<details>
<summary>Create the lib inside "/extension-libs" folder in the default config:</summary>

#### average.js

``` .js
const getValue = function(obj) {
  let val;
  if (obj.t === 'arr') {
    val = obj.v && obj.v.length && obj.v[0];
  } else {
    val = obj.v;
  }
  if (!val) {
    return 0;
  }
  const parsed = parseInt(val.textContent);
  return isNaN(parsed) ? 0 : parsed;
};

module.exports = function(first, second) {
  const average = (getValue(first) + getValue(second)) / 2;
  return {
    t: 'num',
    v: average
  };
};

```

</details>

<details>
<summary>Create the form that will use the created lib.</summary>

#### test-average.xml

``` .xml
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
    <h:head>
        <h:title>Test - Average</h:title>

        <model>
            <instance>
                <data id="test:sum">
                    <first>0</first>
                    <second>0</second>
                    <avg/>
                    <meta>
                        <instanceID/>
                    </meta>
                </data>
            </instance>

            <bind nodeset="/data/avg" type="string" calculate="cht:extension-lib('average.js', /data/first , /data/second )" readonly="true()"/>
        </model>
    </h:head>

    <h:body>
        <group appearance="field-list" ref="/data">
            <input ref="/data/first">
                <label>first</label>
            </input>
            <input ref="/data/second">
                <label>second</label>
            </input>
            <input ref="/data/avg">
                <label>avg</label>
            </input>
        </group>
    </h:body>
</h:html>
```

</details>

<details>
<summary>Upload the config</summary>

```
cht --url=https://medic:password@192-168-86-245.local-ip.medicmobile.org:10446
```

![image](https://user-images.githubusercontent.com/94494491/236566047-6b471602-e9e2-450f-8323-d65eb78d57b2.png)

</details>

<details>
<summary>Test the form</summary>

![image](https://user-images.githubusercontent.com/94494491/236567209-3f90c0de-b7bf-4a3e-836e-fb236d91d86e.png)

</details>

---
Test passed successfully. :white_check_mark:
Moving the ticket to `Ready to Merge`
@garethbowen 

---

**Note:** 
I also tested the functionality using `return` just to see what happened. This is the error that it throws:

<details>
<summary>Error log</summary>

```
Error loading form Error: Failed during the form "test:sum" rendering : ["FormLogicError: Could not evaluate: cht:extension-lib('sum.js', /model/instance[1]/data/first , /model/instance[1]/data/second ), message: Form configuration error: no extension-lib with ID \"sum.js\" found"]
```

![image](https://user-images.githubusercontent.com/94494491/236567860-bf881fb7-868c-4471-91af-12fffe7e0532.png)

 </details>

--- 

@garethbowen, this ticket was in the `No Status` column, I moved it to `AT in progress` and then to `Ready to Merge`. If there was a reason why it was in the `No Status` column or if there is something else that you needed to do before moving it to a different column please move it back where you think is correct.

**Comment by garethbowen** [comment]
Merged. Thanks @tatilepizs !
