### ISSUE TITLE
Contact and Messages Tab:  footer button scrolls with content, not staying pinned

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#8213]
## Describe the bug

_Originally reported on the forum [here](https://forum.communityhealthtoolkit.org/t/change-of-button-position-after-a-given-number-of-entries/2708)._

https://github.com/medic/cht-core/issues/7998 Introduced a Floating Action Button and a list footer button (on desktop). The list footer button on desktop is supposed to stay pinned to the bottom of the list at all times. On the Contacts tab, when there are many rows in the list (basically once a scrollbar shows up), it becomes "unpinned" and scrolls with the content. It seems to work fine on the Reports tab, I didn't test the Messages tab, and it's not applicable to the Tasks tab (there is no button on the LHS on Tasks tab).

## To Reproduce
1. Go to the Contacts tab on desktop
2. Make sure you have more places than can fit on the screen by creating a bunch of test places. 
3. Scroll down
4. Notice that the list footer button scrolls with the content

**NB** - the same thing happens on messages tab too

## Expected behavior
List footer button should stay pinned in all circumstances.

## Screenshots

Animated GIF (say "Jiff!!!") showing reports tab working, but people tab not working
![bottom button](https://user-images.githubusercontent.com/10096985/236032562-872f0b43-2ffa-4195-a361-26a2f181ccfe.gif)

Video showing people tab fixed #8219, but messages tab is broken: 

https://user-images.githubusercontent.com/8253488/236578298-48eede77-7cf0-4f01-b3af-02c5e7efaa02.mov

## Environment

- Instance: Local docker
- Browser: Chrome
- Client platform: MacOS
- App: WebApp
- Version: `master`

**Comment by dianabarsan** [comment]
I've added this to 4.2.0, since this is disruptive - the button ends up completely obscuring one entry in the list, which means that the user will not be able to access that contact at all.

**Comment by garethbowen** [comment]
@michaelkohn Can you please find someone who can work on this so as not to block the 4.2.0 release?

**Comment by mrjones-plip** [comment]
OK, the issue is, purely from a CSS/DOM perspective is that:
* the `<ul>` elements (places)
* the `<p/>` tag with `No more people` 
*  the `<div class="padding"></div>` 
 
all need to be wrapped in a `<div class="items-container"></div>` right before the `<mm-fast-action-button></mm-fast-action-button>`.  This specifically gives it these 3 styling:

```css
  padding: 15px;
  overflow-y: auto;
  height: 100%;
}
```

Here's the client side hacked DOM working with the fixes:


https://user-images.githubusercontent.com/8253488/236505078-444249e2-08b7-41ac-bee1-a53de1a6d9d3.mp4

Now that I know the fix, I'll see if can't trace this back to the code.

**Comment by mrjones-plip** [comment]
Steps to test - follow the "to reproduce" steps and ensure the "New Health Facility" doesn't scroll.
