### ISSUE TITLE
E2e structure - Part III - Shared files

### ISSUE THREAD

**Issue by tatilepizs** [medic/cht-core#8224]
The last part of this re-structure will be to organize all the files that are shared globally. 
For example, we have an `utils` folder and also a `utils.js`. Should we move the file inside the `utils` folder? Should we create a new folder? Should we change the name to the `utils` folder to be more accurate?

We need to evaluate all the shared files that are in `/e2e/` and locate them in the correct place. 

Previous tickets: 
- #7720 
- #7793

**Comment by garethbowen** [comment]
@elidakirigo Absolutely! Check out the documentation for how to contribute: https://docs.communityhealthtoolkit.org/contribute/code/

If you want to write new tests it would be a good idea to get in touch with what you plan to do to make sure it's not already covered by testing. Perhaps the best way would be to look for existing open issues, or by raising an issue outlining what you propose to do.

**Comment by tatilepizs** [comment]
This ticket was more related to organize files and folders. And with all the other tickets related to clean-up the e2e test folder, this ticket was already addressed.
