### ISSUE TITLE
Cannot use db-object-widget to load contact data in non-relevant `inputs` group

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8225]
**Describe the bug**
If the `inputs` group in a form is never relevant, then the `select-contact` feature from the db-object-widget cannot be used to load contact data into a sub-group of the `inputs` group.

Take the following form:

type | name | label::en | relevant | appearance | calculation
-- | -- | -- | -- | -- | --
begin group | inputs | NO_LABEL | ./source = 'user' | field-list |  
begin group | contact | NO_LABEL |   | field-list |  
begin group | parent | NO_LABEL |   |   |  
hidden | _id | Parent ID |   |   |  
end group | parent |   |   |   |  
end group | contact |   |   |   |  
begin group | my_parent_data |   |   |   |  
string | _id |   |   | select-contact | ../../contact/parent/_id
string | name |   |   |   |  
end group | my_parent_data |   |   |   |  
end group | inputs |   |   |   |  

This does not work in situations where `./source = 'user'` is false (does not work when opening the form from the "People" tab with a contact in context.  

I think this behavior is the result of some incomplete [patching](https://github.com/medic/cht-core/tree/master/webapp/patches) of the `enketo-inputs-always-relevant` situation where Enketo is still not actually evaluating the calculations in the non-relevant `inputs` group.  [Other `inputs` data](https://docs.communityhealthtoolkit.org/apps/guides/forms/form-inputs/) (such as `inputs/contact`) will show up just fine since it is pre-loaded into the form.  All of this kind of makes sense from the Enketo logic perspective, but is _really confusing_ for any consumer trying to get their form to work!
�
The whole `inputs` functionality probably needs to be re-thought in `5.0`, but for now, it might be enough to just add an additional patch(es) in enketo-core for places [like this](https://github.com/enketo/enketo-core/blob/b83271e8cc88fb79ddeb4f79fb1194d2aac9f421/src/js/calculate.js#L199) that would allow for calculations to run inside the non-relevant `inputs` group. 

**Environment**
- Version: `master` (`4.1.x`)

**Additional context**

The work-around here is to not try to use the `select-contact` in the `inputs` group unless you know that it is going to be relevant when you need it.

[forum thread](https://forum.communityhealthtoolkit.org/t/query-parent-contact-place-data-in-child-form/2711/4)

**Comment by garethbowen** [comment]
@jkuester Please check the Affects labels I've added here - I assume this is related to the enketo-core upgrade in 4.x?

Also if there's a breaking change you'd recommend here, please raise a new issue and assign it to the 5.0.0 milestone so we don't lose it.

**Comment by jkuester** [comment]
@garethbowen as far as I can tell this did not work prior to the `4.0` Enketo upgrade either.  I have reproduced the behavior described above on `3.13`, but it probably does not work on earlier version.

**Comment by jkuester** [comment]
@garethbowen, should we actually remove the `Regression` label here (and the associated `Affects *` since this did not work in the `3.x` line either?  

The functionality is still a bug, but I guess it is not a regression if it never worked...

**Comment by garethbowen** [comment]
True! Thanks for pointing that out.

**Comment by jkuester** [comment]
Okay, so, based on [this forum post](https://forum.communityhealthtoolkit.org/t/current-user-data-hydration-with-db-object-issue-using-cht4/3880/4), I have identified a new wrinkle to this issue.  :sweat:   If you look at my original sample form above, you can see that I am trying to load the parent data _in a separate `my_parent_data` group_ contained in the `inputs` group.  This behavior has not been observed to work in any CHT version (as previously noted).  

_However,_ using the contact selector to load contact data for an id value _in its current group_ within the `inputs` did actually work prior to `4.6.0`, but now does not work in `4.6.0+`.  Take the following form for example:

type | name | label::en | appearance | relevant
-- | -- | -- | -- | --
begin_group | inputs |   |   | false()
begin_group | user | NO_LABEL |   |  
db:person | contact_id | User’s Contact | db-object |  
string | role | User’s Role |   |  
end_group | user |   |   |  
end_group |   |   |   |  
note | my_note | User’s Role: ${role} |   |  

I have confirmed that this form will display the `role` value from the user's contact document on `3.17` and on `4.5`, but it will not display the value on `4.6+`.  

The important factors here are the `inputs` group which has special logic around it, and the fact that `inputs` is non-relevant.  Based on my debugging, this issue is actually not technically specific to the contact selector functionality.  The root problem seems to be that updates to form model data in a non-relevant `inputs` group are not actually persisted.  The db-object widget is getting triggered as expected and it is "setting" the proper value onto the `role` field in the form model, but that value is not actually getting stored into the model.  I expect this is because we missed patching something in the setVal logic around `inputs` when it is non-relevant.  :disappointed: 

---

To workaround this issue, you can just move your contact selector group out of the `inputs` group.  You can still reference `inputs` fields, but just do not use the contact selector, itself, inside of `inputs`.

Unfortunately, because of https://github.com/medic/cht-core/issues/8226 you cannot just create a hidden top-level group for loading the contact data since that will result in a blank page being shown in the form.  But, you can nest the hidden group into the group for an existing page.  This should work on any 3.x-4.x version of the CHT.

type | name | label::en | appearance | relevant | calculation
-- | -- | -- | -- | -- | --
begin_group | inputs |   |   | false() |  
begin_group | user | NO_LABEL |   |   |  
string | contact_id | User’s Contact |   |   |  
end_group | user |   |   |   |  
end_group |   |   |   |   |  
begin_group | my_page | NO_LABEL | field-list |   |  
begin_group | user_contact | NO_LABEL | hidden  |   |  
db:person | _id | User contact Id | db-object |   | ${contact_id}
string | role | User Role | |   |  
end_group |   |   |   |   |  
note | my_note | User’s Role: ${role} |   |   |  
end_group | my_page |   |   |   |
