### ISSUE TITLE
Upgrade webapp to Angular 16

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8237]
**Describe the issue**
Angular 16 is ready and with great features, including performance improvements; see [blog post](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d).

We need to find out if any breaking change affects us and do a before and after performance comparison. 

Reference of previous upgrade: https://github.com/medic/cht-core/issues/7992#issuecomment-1378422496

**Comment by latin-panda** [comment]
[Typescript 5 blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0)

**Comment by latin-panda** [comment]
Blocked until this lib releases a version compatible with Angular 16

https://www.npmjs.com/package/@angular-builders/custom-webpack

**Comment by latin-panda** [comment]
Router guard interfaces [are deprecated](https://angular.io/guide/deprecations#angularrouter) and we need to migrate to functions

**Comment by latin-panda** [comment]
Won't be worked in Q3. Prob in Q4
cc: @michaelkohn I've moved this issue back to ToDo for now.

**Comment by latin-panda** [comment]
#### Performance   
**Build time**
- Angular 15:
  - `npm run build-dev` Best: 3m 01s — Average: 3m 07s — Worst: 4m 02s
- Angular 16:
  - `npm run build-dev` Best: 1m 19s —  Average: 2m 5s — Worst: 2m 37s
  
**Size**
- Angular 15:

Initial Chunk Files       |  Raw Size
--------|--------
main.js                     |  11.93 MB | 
polyfills.js          |   1.04 MB | 
styles.css            | 572.33 kB | 
scripts.js                | 152.52 kB | 
runtime.js          |   6.99 kB | 
  | **Initial Total** |  **13.68 MB**

- Angular 16:

Initial Chunk Files        |  Raw Size
--------|--------
main.js            |  12.30 MB | 
styles.css       | 537.11 kB | 
polyfills.js       | 230.55 kB | 
scripts.js          | 152.52 kB | 
runtime.js        |   6.99 kB | 
 | **Initial Total** |  **13.20 MB**

**Unit tests time**
- Angular 15:
  - `npm run unit-webapp` total: 2m 23s
- Angular 16:
  - `npm run unit-webapp` total: 1m 40s

See [here](https://github.com/medic/cht-core/issues/7992#issuecomment-1378422496) performance of previous angular migrations when we had `grunt`.

**Comment by ngaruko** [comment]
Tested a few functionalities with chrome, android 13, 12, and 10 - and it all looks great and same as master.

<details><summary>Message tab</summary>
<img width="370" alt="image" src="https://github.com/medic/cht-core/assets/6979995/95efab67-806f-49c4-a7b2-e441672908b8">

</details>

<details><summary>Contact tab > </summary>
creating/editing contacts
<img width="398" alt="image" src="https://github.com/medic/cht-core/assets/6979995/68575f79-552c-4ad0-ae77-99ad8a87f6a9">

</details>

<details><summary>report tabs > </summary>
 creating editing reports 
<img width="328" alt="image" src="https://github.com/medic/cht-core/assets/6979995/208f40de-5107-46d1-bd8f-2368c40f763b">

</details>

<details><summary>Tasks tabs > </summary>
 tasks are created and can be completed
<img width="332" alt="image" src="https://github.com/medic/cht-core/assets/6979995/6e632244-b144-413a-911e-7176fc7a2a96">

</details>

<details><summary>Targets tab </summary>
<img width="330" alt="image" src="https://github.com/medic/cht-core/assets/6979995/ce4a35ba-9c1b-4317-bc10-d15c3a75e1cd">

</details>
<details><summary>Warnings when existing form before completion </summary>
<img width="307" alt="image" src="https://github.com/medic/cht-core/assets/6979995/e20ce770-143f-464c-bb37-7c72ecd0da30">

</details>
