### ISSUE TITLE
Figure out a different way to use purged docs cache

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8238]
**What feature do you want to improve?**
Right now, purged docs are cached for a very short interval (5 minutes) - for considerations of memory management. 
Recent research has shown that: 
- users end up having a very large number of documents before purging - with 40k being common, growing up to 100k docs
- cache is used in 40% of requests

**Describe the improvement you'd like**
Experiment with increasing TTL, and only bust cache when purging has run again. 

**Describe alternatives you've considered**
If experiments show that the memory footprint of the cache for a large project (suppose 4000 users each with 60k pre-purge docs, cached), investigate whether cache can be saved on disk.

**Additional context**
@kennsippell has been analyzing production logs and observing request behavior. Querying for purged docs in this project, which has  very aggressive purging and high number of pre-purge docs, the purging requests take up to 40% of server time.

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by dianabarsan** [comment]
Merged to `master`
