### ISSUE TITLE
Can't turn off permissions for `national_admin` role in admin app

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8243]
**Describe the bug**
A user with the `role` of national admin will always have all permissions enabled in webapp. 
[This was reserved solely for db admins](https://github.com/medic/cht-core/blame/1edc93a9555737e2734fb37f4d7883a2fe3c400d/webapp/src/ts/services/auth.service.ts#L33) (user with the reserved couchdb role `_admin`) but was changed when adding the [CHT script API](https://github.com/medic/cht-core/commit/869fd7103723730f9f7a7a990c058687c8c3cbf5).

**To Reproduce**
1. Disable UHC (delete the `uhc` property in `settings` and uncheck the permission `can_view_last_visited_date` for all roles)
2. Create an online user. Give them the `national_admin` role. You can either configure this role or just leave it unconfigured and just add it manually to the `user` doc in `_users` db. Assign this user to a contact that would see places that have [`count_visits` enabled](https://github.com/medic/cht-core/blob/master/config/default/app_settings.json#L335).
3. Login with this user and load the contacts tab.
4. See that the contacts list shows UHC last visited dates. 

**Expected behavior**
It should be possible to not display `last_visited` for `national_admin` role, but currently we only exclude that for `_admin`. 

**Logs**
Not applicable. 

**Screenshots**
![image](https://github.com/medic/cht-core/assets/35681649/851e1bef-8a41-4156-bd83-2f4ed5d5e415)

**Environment**
- App: webapp
- Version: 3.12+

**Additional context**
Reported [on the forum](https://forum.communityhealthtoolkit.org/t/seeking-clarity-on-the-national-admin-role-and-mm-online-role/2746/3?u=diana) after logs for a live instance were analyzed and observing very long view queries made by `national_admin`s loading the contact page, even though they did not have permissions to view last visited dates.

**Comment by garethbowen** [comment]
Bumping to 4.4.0 as we're almost ready to release 4.3.0 and this has more work needed yet.

**Comment by kennsippell** [comment]
Would it be an okay time to remove this role instead of fixing this?  It's nearly an unexpected change to fix this after being broken for so long...

**Comment by garethbowen** [comment]
That's my thinking too, but we need to verify backwards compatibility, so anyone with this role isn't given more permissions than they should.

**Comment by dianabarsan** [comment]
I'm also proposing to remove all hardcoded interactions for this role, and _not_ add `_admin` for these users, and reduce `national_admin` to be a standard online role.

**Comment by dianabarsan** [comment]
Merged to `master`. All hardcoded perks for `national_admin` have been removed.
