### ISSUE TITLE
Flaky e2e test Enabling/disabling languages - should disable a language and enable another

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8249]
**Describe the issue**
This test is failing frequently on branches and on `master`: 
https://github.com/medic/cht-core/actions/runs/4999357597/jobs/8955822854#step:16:1380

Failure is: 
```
[chrome 113.0.5672.63 linux #0-66] 1) Enabling/disabling languages should disable a language and enable another
[chrome 113.0.5672.63 linux #0-66] expected [ { code: 'bm', …(1) }, …(7) ] to deeply equal [ …(3) ]      
      actual expected
      
      [ { code: 'bm', name: 'Bamanankan (Bambara)' }, { code: 'en', name: 'English' }, { code: 'es', name: 'Español (Spanish)' }, { code: 'fr', name: 'Français (French)' }, { code: 'hi', name: 'हिन्दी (Hindi)' }, { code: 'id', name: 'Bahasa Indonesia (Indonesian)' }, { code: 'ne', name: 'नेपाली (Nepali)' }, { code: 'sw', name: 'Kiswahili (Swahili)' } ]   
```

**Describe the improvement you'd like**
Fix the test.

**Comment by garethbowen** [comment]
Thanks @dianabarsan . I hit this the other day but didn't have time to work out if it was an issue in my branch or not.

I'm not sure what's going on but when I run just that test it passes so it's possible some other test is updating/reverting the settings.

**Comment by dianabarsan** [comment]
I've made an attempt to stabilize this. If the issue persists, please feel free to reopen.
