### ISSUE TITLE
Upgrade demo-cht.dev to 4.x.x

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8270]
**Describe the issue**
As part of the [release steps](https://github.com/medic/cht-core/blob/master/.github/ISSUE_TEMPLATE/z_release_major.md), we update the [demo site](https://demo-cht.dev.medicmobile.org/) so people can experience the latest version of CHT. 

Right now it's on version 3.17, as we work with partners on migrating to 4.x.x, It'd be good to upgrade this instance in case they want to see it.

**Comment by latin-panda** [comment]
@jonathanvq @garethbowen I'm not sure if I created this in the right place, and in case, it needs to be prioritized with the team accordingly.

**Comment by garethbowen** [comment]
We have two options here - either upgrade with the same database which is more work but keeps the config as users as is, or wipe it and start again. [We're not sure](https://github.com/medic/cht-core/issues/7545#issuecomment-1057189946) what config is loaded on there so a fresh start would change the config slightly (for better or worse).

I propose we start with a fresh install and use the `default` configuration. This is because...
- it's easier to do
- it cleans up the config to a known state
- it removes all the old users who may have self registered
- it removes all the old data (which is a pro and a con)

@michaelkohn @abbyad Does this sound ok to you?

**Comment by michaelkohn** [comment]
Yep, I agree with starting afresh from `default` config. I'd like to then make some tweaks to that config (enabling household tasks, deploying some example training cards, etc....) and make sure we can store that somewhere.

I don't really know how the demo account creation scripts work (they create a bunch data for users too) and the integration with Slack, but we should make sure they work after the upgrade too.  https://medic.slack.com/archives/CE59MTM3K

**Comment by garethbowen** [comment]
@henokgetachew You mentioned starting a fresh instance would be a 1 minute job - can you do this (or tell me how to), redirect the domain, share the credentials in 1pass, and then shut down the old demo instance?

@michaelkohn For the config, could you set this up? Either replace the config in the `medic-projects/demo-cht`, or probably better would be do make a new config in `cht-core` which can be public. Once the baseline is set I want to make a script that automatically deploys the latest release and pushes the latest config at the same time.

Once that's done I'll make sure the demo account generation works as expected.

**Comment by michaelkohn** [comment]
Cool. Ya, I can decide what it should include but I'll need some help with actually updating and publishing app_settings. I'll work with @mrjones-plip when he get's back. I imagine we'll just start from the default config and configure a few additional features, then publish to https://github.com/medic/cht-core/tree/master/config/demo

**Comment by henokgetachew** [comment]
@garethbowen @michaelkohn I just setup a new instance for demo-cht. https://demo-cht-latest.dev.medicmobile.org - password on 1password. 

I haven't yet redirected the old url (Just in case there is some issue with this one - as this is hosted on eks and everything including the helm charts used to set it up are new.)

@michaelkohn can you do your magic and can we see if everything works as intended?

**Comment by michaelkohn** [comment]
Thanks @henokgetachew 

- I logged in as `medic` and created a health facility, chw area, and chw
- I created a new user and associated to the chw/area that i just created
- I logged in as that chw
- I created a new HH and family member
- I submitted a pregnancy registration for that person
- Tasks/Targets/etc... all looked good

The only thing that was kind of funky is that I noticed there was a user `role` that I would not have expected to be in the `default` config. Was something copied over from the old instance or is this a completely fresh instance with `default` config? 

<img width="1160" alt="Screenshot 2023-06-20 at 3 43 28 PM" src="https://github.com/medic/cht-core/assets/10096985/897b3673-9c3f-40f0-8876-6a3c5de53e1e">

**Comment by henokgetachew** [comment]
It's a fresh instance @michaelkohn.

**Comment by michaelkohn** [comment]
@garethbowen do you want to go ahead and test the creation scripts before I update any configuration? The new instance has the default config on it and there's a new folder ([PR](https://github.com/medic/cht-core/pull/8344)) in cht-core/config/demo where we can make changes in the future. Right now it's just a direct copy of the default config.

**Comment by garethbowen** [comment]
@michaelkohn Go ahead making config changes. I'll hold of testing the user creation scripts until the URL is finalised because that's going to break them for sure.

**Comment by henokgetachew** [comment]
FYI, upgrade/migration automation scripts are completed and being tested for k8s hosted instances. This can now be taken care of using the actual upgrades script and we can forgo the new instance.

**Comment by Hareet** [comment]
Oops, I moved the url over after [this slack conversation](https://medic.slack.com/archives/C024KTGRW/p1692361955803629). The other, old 3.x setup is still there, I won't delete it and let me know if you want me to switch demo-cht back.

**Comment by michaelkohn** [comment]
Cool thanks @Hareet !  I just checked it out and can see it's on 4.2.1 (and I can see the new UI elements ⚡ )

@garethbowen you mentioned you wanted to: 

> ...make a script that automatically deploys the latest release and pushes the latest config at the same time

and...

> ...make sure the demo account generation works as expected.

The latest demo config is [here](https://github.com/medic/cht-core/tree/master/config/demo), just FYI. What will trigger the script to push the latest config? Will committing config automatically deploy it?

**Comment by mrjones-plip** [comment]
OMG!  We should totally do this! It would be the only Continuous Delivery CHT instance in the world! :world_map: :rocket:

**Comment by henokgetachew** [comment]
I think we might have to redeploy this new fresh instance if it was deployed with the version of helm charts before the race-condition fix. Let me know if the instance goes unavailable once someone tries to upgrade it through the UI. I'll re-deploy it using the latest helm charts.

> Oops, I moved the url over after [this slack conversation](https://medic.slack.com/archives/C024KTGRW/p1692361955803629). The other, old 3.x setup is still there, I won't delete it and let me know if you want me to switch demo-cht back.

I'm okay with us proceeding either way. My personal preference would be to do an actual upgrade of the old instance with all it's data - even if for testing purposes but I think @garethbowen might prefer the removing of all old users and old accounts which may no longer be relevant as per [this](https://github.com/medic/cht-core/issues/8270#issuecomment-1593554205) comment.

**Comment by garethbowen** [comment]
> The latest demo config is [here](https://github.com/medic/cht-core/tree/master/config/demo), just FYI. What will trigger the script to push the latest config? Will committing config automatically deploy it?

I think it should be tied to the release tag, for example, when `4.4.0` is tagged in GitHub...

1. The release is compiled and published to the market
2. The demo instance is updated to 4.4.0
3. The demo config is pushed just in case something changed since 4.3.0

We could also deploy config after updating the config, but the new config might be dependant on the new code so I'd prefer to only do it at release time.

> I think we might have to redeploy this new fresh instance if it was deployed with the version of helm charts before the race-condition fix. Let me know if the instance goes unavailable once someone tries to upgrade it through the UI. I'll re-deploy it using the latest helm charts.

@henokgetachew It looks like it's down - when I try to log in I get a 503. Is this because of the helm charts?

> My personal preference would be to do an actual upgrade of the old instance with all it's data...

Deleting data is fine here. I think the ideal demo site would actually be wiped regularly (every night?) and reset with some seed data because anybody can create an account and do anything in there.

**Comment by henokgetachew** [comment]
>@henokgetachew It looks like it's down - when I try to log in I get a 503. Is this because of the helm charts?

If an upgrade proceeded it going down, it was likely because it uses the old charts with the race condition. I'll push the new ones today when I get some downtime.

**Comment by Hareet** [comment]
@henokgetachew Seeing the same issue that was commented about [here](https://github.com/medic/upgrade-service-kubernetes/issues/13#issuecomment-1547900837). API container is unable to bind/listen to its port, seemingly due the api k8s service resource using that space. I've seen it happen with the upgrade-service-kubernetes a while back, and now we are seeing it occur with API. I have not witnessed it with CouchDB. It looks like we are misconfiguring our service resource, container specification, or how our app interacts that these bindings should not interfere.

API error:
```
  [stack]: 'Error: listen EACCES: permission denied tcp://172.20.84.184:5988\n' +
    '    at Server.setupListenHandle [as _listen2] (node:net:1446:21)\n' +
    '    at listenInCluster (node:net:1511:12)\n' +
    '    at Server.listen (node:net:1610:5)\n' +
    '    at Function.listen (/service/api/node_modules/express/lib/application.js:635:24)\n' +
    '    at /service/api/server.js:54:22\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
  [message]: 'listen EACCES: permission denied tcp://172.20.84.184:5988',
```
Notice that will be the same ClusterIP that the api k8s service resource is using:
```
kubectl -n demo-cht get services
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
api               ClusterIP   172.20.84.184    <none>        5988/TCP
```

The workaround is to delete the service resource, let the container bind, and then re-deploy the service. If you test this with the upgrade-service-kubernetes and roll over a local k3d node, you see the same thing. Or keep restarting the upgrade-service and eventually you run into this.

cc: @nydr This is the binding issue I was referring to during our call

**Comment by Hareet** [comment]
I've implemented the workaround (re-deploy the service resource). @henokgetachew I edited the ingress from demo-cht-latest to demo-cht since the ALB ingress controller was deleting manual entries on its managed resource.

**Comment by Hareet** [comment]
@henokgetachew @nydr Saw this binding issue again when I re-deployed demo-cht. Is this part of the race condition that's fixed? Or I'm thinking we didn't test our templates/charts with failovers in k3s/eks?

**Comment by henokgetachew** [comment]
This is the race condition that i have already fixed. I'll deploy the new charts to this deployment this week.

**Comment by garethbowen** [comment]
@henokgetachew It looks like the upgrade is complete. Is there anything left to do?

**Comment by antonykhaemba** [comment]
I have tested the upgraded demo app which is running on CHT v4.2.2 and I have noticed these changes:
- [ ] when I access a person profile (for example an U5, I am not able to access the assessment form).
- [ ] I am not able to access the add new person form, when I open the profile of a household and click on floating button, the add new person automatically open without giving me an option of selecting the add new person form.

@michaelkohn is this the expected behaviour after changing the configuration. cc @garethbowen.

**Comment by henokgetachew** [comment]
> @henokgetachew It looks like the upgrade is complete. Is there anything left to do?

Thanks for the reminder @garethbowen. Yes we can now push the latest charts to the deployment. I will take it on tomorrow.

**Comment by antonykhaemba** [comment]
This is well noted. Thanks @michaelkohn for the clarifications.

**Comment by garethbowen** [comment]
Calling this done.
