### ISSUE TITLE
Add more debug information to CHT4 Docker Helper

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8293]
**Describe the issue**
When the [CHT4 docker helper](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/app-developer/#cht-docker-helper-for-4x) fails, there's often not a lot of information for the user to go on on how to fix the problem.  

**Describe the improvement you'd like**
Add docker status information when the script exits

Related, there's a number of [forum posts like this](https://forum.communityhealthtoolkit.org/t/docker-compose-error-while-setting-up-the-first-project/2674/14)

**Describe alternatives you've considered**
na

**Comment by garethbowen** [comment]
@mrjones-plip When closing, remember to add issues to the current release.

I would also argue since docker helper is something that people outside Product use it's an "Improvement" not a "technical issue" - it'd be a shame if our app developer friends didn't see this in the release notes!

**Comment by mrjones-plip** [comment]
Right right - thanks for the reminder!
