### ISSUE TITLE
Don't show action button when there's no action for user.

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#8313]
**What feature do you want to improve?**
If a user doesn't have an action to perform, don't show action button on the page for them. 

<img width="760" alt="image" src="https://github.com/medic/cht-core/assets/6102813/aa0648c0-3052-4c68-9bd9-cf193abc02e8">

**Describe the improvement you'd like**
Don't show empty blackbox, it'd be appropriate to not this at all. 

I haven't checkd if this is not the case in 4.x, but this is seen in 3.17.1. 

**Additional Context**:
This behavior seen in both Contacts tab and Reports tab.

<img width="1073" alt="image" src="https://github.com/medic/cht-core/assets/6102813/607ee28e-a20b-4fd9-8409-55c54a8135d4">

**Comment by dianabarsan** [comment]
Hi @yrimal 

Can you please include which version you're seeing this for? Is this post FAB update?

**Comment by dianabarsan** [comment]
@latin-panda Could you please check how this behaves in 4.2.x, post FAB update?

**Comment by latin-panda** [comment]
@dianabarsan @yrimal it's quite hard to hide the grey banners, and we decided to leave it like that [see the original ticket and related comment](https://github.com/medic/cht-core/issues/6215#issuecomment-1240176736). This action bar is considered deprecated and will be removed in the following months. This won't be a problem if the project uses [FAB](https://docs.communityhealthtoolkit.org/core/releases/4.2.0/#floating-action-button).

**Comment by dianabarsan** [comment]
My question is: does the FAB disappear if there are no actions to perform?

**Comment by latin-panda** [comment]
| Does the FAB disappear if there are no actions to perform?
@dianabarsan yes, it disappears

**Comment by yrimal** [comment]
Thanks @dianabarsan ,  @latin-panda . I also checked this with 4.2.0 instance using FAB and there's no problem like this in 4.2.0. We can close this request as already implemented in 4.2.0 onwards and the issue exists in version prior to that.
