### ISSUE TITLE
Fix reports's review title in modal

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8355]
**Describe the bug**
This is a quick fix. 
Rename the review's header's custom title property.
<img width="339" alt="Screenshot 2023-07-03 at 8 58 24 pm" src="https://github.com/medic/cht-core/assets/66472237/77370b61-bcf8-4304-963a-a0cf8806cb62">

**To Reproduce**
1. Open the app with developer tools and choose a phone device (It has to be a touch device setup) 
2. Open a report 
3. Click on the Review from More Options

**Expected behavior**
The review's title should be fully extended horizontally. 

**Environment**
- Instance: local
- Browser: Firefox and Chrome mobile
- Client platform: MacOS
- App: webapp
- Version: 4.3.x

**Comment by dianabarsan** [comment]
@latin-panda I've noticed the PR is merged. Can we close this issue?

**Comment by latin-panda** [comment]
Thanks for the reminder!
