### ISSUE TITLE
Webapp watch not publishing changes

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8367]
**Describe the issue**
After making changes in webapp, it's not publishing changes. 
This is not a blocker for work or production environments.

**Steps:**
1. checkout `master`
2. `npm ci` in the root folder
3. `grunt dev-webapp`
4. make a change in webapp
5. see how it starts to rebuild but doesn't finish and stays hanging. Go to webapp, sync & reload, and see that changes aren't deployed.

**Logs**
This is after a change in webapp's code, and hangs at that point

<img width="693" alt="Screenshot 2023-07-06 at 11 13 40 am" src="https://github.com/medic/cht-core/assets/66472237/19e377b5-4f85-48bc-b3a8-50b50b5d14ea">
<br>

**More details**
Trying this in:
npm --version
8.3.1
node --version
v16.14.0
macOS
13.4.1

**Comment by dianabarsan** [comment]
I'm not getting this error: 
![image](https://github.com/medic/cht-core/assets/35681649/6c05bfe4-878a-4c3f-9cb6-42b90ba4e9e1)

**Comment by latin-panda** [comment]
I resolved the issue in my laptop by removing the `.angular` folder used for caching. This Angular caching allows faster builds. 

We can add a command (grunt or npm run) to clean this (`ng cache clean`) and have a fresh start when we need it. For example, something like: `npm ci && ng cache clean && grunt dev-webapp`.
