### ISSUE TITLE
Nginx in crash loop in certificate check

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8383]
**Describe the bug**
Nginx is in crash loop if using `CERTIFICATE MODE = OWN_CERT`

**To Reproduce**
_repro steps likely to change_
1. Start `cht-nginx` with  `CERTIFICATE MODE = OWN_CERT` and all `SSL_*` environment variables.
2. Observe that the container is in a crash loop

**Expected behavior**
Unsure. 

**Logs**
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/server.conf.template to /etc/nginx/conf.d/server.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/ssl-install.sh
Running SSL certificate checks
CERTIFICATE MODE = OWN_CERT
Please provide add your certificate (/etc/nginx/private/cert.pem) and key (/etc/nginx/private/key.pem) in the /etc/nginx/private/ directory
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/server.conf.template to /etc/nginx/conf.d/server.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/ssl-install.sh
Running SSL certificate checks
CERTIFICATE MODE = OWN_CERT
Please provide add your certificate (/etc/nginx/private/cert.pem) and key (/etc/nginx/private/key.pem) in the /etc/nginx/private/ directory
```

**Environment**
- Instance: any
- App: nginx
- Version: 4.2.0

**Additional context**
This came up when a test instance was upgraded to 4.2.0

**Comment by henokgetachew** [comment]
I don't think this was because of the expiry. I think this was actually caused by [this](https://github.com/medic/cht-core/issues/7949) issue that happens when the cert and the key are differently named other than `cert.pem` and `key.pem`.

**Comment by dianabarsan** [comment]
I agree, I was in the process of updating the contents.

**Comment by dianabarsan** [comment]
But in this case, the certs did have the correct names.

**Comment by dianabarsan** [comment]
I've asked @nydr to look into this. Thanks @nydr !

**Comment by dianabarsan** [comment]
Did you try upgrading from 4.1.0, with an `OWN_CERT` that worked in `4.1.0` and then upgrade to `4.2.0`? This is where this failed and the purpose of this issue, to identify if we've not broken this.

**Comment by dianabarsan** [comment]
Cool, I think it's safe to close this. My last suspicion is that changes were made to the docker-compose files on the instance, and those changes were overwritten by the upgrade. We can reopen if this is reported again.
