### ISSUE TITLE
Improve Nepali translation

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-core#8389]
This Nepali translation is incorrect.
https://github.com/medic/cht-core/blob/1d19531b2404595d17f63b631c659a717a786ee5/webapp/src/js/bootstrapper/translator.js#L61

Instead of:
`${count} मध्ये ${total}`,

It should be:
`${total} मध्ये ${count}` which gives the meaning of `${count} out of ${total}`.

**Comment by dianabarsan** [comment]
Are you able to take this on @binokaryg ?

**Comment by binokaryg** [comment]
> Are you able to take this on @binokaryg ?

Yes!

**Comment by garethbowen** [comment]
Merged!

**Comment by garethbowen** [comment]
Thanks @binokaryg
