### ISSUE TITLE
Align "dialog" components with Material design guidelines

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#8390]
Update CHT [dialogs](https://m3.material.io/components/dialogs/guidelines) to align with Material guidelines. This includes updating the visual design / placement of dialogs as well as updating the default text of dialogs as necessary.  The list of default text (and what it will be updated to) can be found [here](https://docs.google.com/document/d/1Dh7g0Eyk6x1xtzkn7gkwx84R5fS-KfppZVNgcwgOi9k/edit#heading=h.t0rco2pr43gd). 

👇🏼 Example current implementation and new implementation ([figma](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?type=design&node-id=2611-22370&mode=design&t=6y61bAUk52OKR6wj-0))

<img width="1057" alt="Screenshot 2023-07-12 at 11 23 20 AM" src="https://github.com/medic/cht-core/assets/10096985/40db074d-75f2-443c-88ca-659040c147f8">

**Comment by latin-panda** [comment]
FYI @ngaruko I'm working on this

**Comment by latin-panda** [comment]
In the release notes, we need to high light that [some modals' text have been improved](https://github.com/medic/cht-core/issues/8390#issuecomment-1698919652) to increase understanding and that some keys have been replaced 
- Bulk delete reports 
    - `bulkdelete.confirm.title` used for the modal title when deleting 1 report
    - [NEW] `bulkdelete.confirm.title.plural` used for the modal title when deleting multiple reports.
- Edit message group
    - [NEW] `edit_message_group.modal.title`: used for the modal title
- Report a bug
   - [NEW] `feedback.modal.submit`: used for the modal submit button label.   
- Confirm Navigation - like when exiting a form that hasn't been submitted 
   - [NEW] `confirm.destructive.navigation.title`: used for the modal title
   - [NEW] `confirm.destructive.navigation.submit`: used for the modal submit button label.   
- Training cards 
  - [NEW] `training_cards.confirm.title`: used for the modal title
- Confirm verifying a report
   - [NEW] `confirm.verification.title`: used for the modal title
   - [NEW] `confirm.verification.submit`: used for the modal submit button label. 

We have provided translations for all of these in the CHT Core supported languages (English, Spanish, French, Indonesian, Hindi, Nepali, Bambara, Swahili)
