### ISSUE TITLE
Bug with Upgrade/migration from 3.x to 4.x - Users page empty, accounts unable to login, some catchment areas not showing details

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#8397]
**Upgraded from**: 3.15.0
**Upgraded to**: 4.2.1

**Describe the bug**

1. User accounts unable to login after migration/upgrade.
2. Users page shows an empty list.
3. Catchment areas not showing up for contacts. On a test data - `Darasa1`, `ExampleSupervisorryArea` and `ANC/PNC Testing Area` below are not showing details. 

If required, I'll provide both volumes mounted to an instance for investigation.

Login doesn't seem to be a password issue. I've tried resetting the password from the couchdb ini file and it was still unable to login - including using the main admin user. Creating a new account in the ini file was working however.

**Logs**
Logs during verification after upgrade:

```
      Views of database medic-user-chv10-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.

Verifying medic-user-test_admin-meta

      Views of database medic-user-tchv8-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
Verifying medic-users-meta

      Views of database medic-user-test_admin-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
Verifying medic-vault

      Views of database medic-users-meta are not indexed. 
      This can be caused by a migration failure or by the the views functions not indexing any documents.
    
Database medic-vault has passed migration checks.
Migration verification passed.
```

**Screenshots**
Here's the user's page after upgrade:
<img width="1439" alt="image" src="https://github.com/medic/couchdb-migration/assets/3198821/e0925424-547e-4555-b694-67d08c1cf029">

![image](https://github.com/medic/cht-core/assets/3198821/38ff8d31-be1a-4542-9aad-6c0fc258be4e)

The area is selected in the following screenshot - as can be seen from the address bar. However, it briefly starts showing the name and reverts to `No person selected`
 
In chrome:
<img width="1599" alt="image" src="https://github.com/medic/cht-core/assets/3198821/e394aae1-456d-4408-9a2b-124b7cd987c1">

In firefox:
<img width="680" alt="image" src="https://github.com/medic/cht-core/assets/3198821/30702477-a217-43e1-8935-f734ee608cf7">

The selection works for `covid1` however:
<img width="1260" alt="image" src="https://github.com/medic/cht-core/assets/3198821/50e7761e-e69b-4ad0-a238-3285a516c71d">

I checked to see the verification results for `covid1`:
<img width="753" alt="image" src="https://github.com/medic/cht-core/assets/3198821/6f324ae0-a7b7-43b1-b30b-ad21017078e7">

**Comment by dianabarsan** [comment]
I strongly suspect some faults in moving data around. 
Was this migrated to clustered or single-node couchdb?

**Comment by henokgetachew** [comment]
I doubt that. Data was moved in a compressed tar file so a corruption there would have prevented entire thing from working. This was a single-node couchdb setup

**Comment by dianabarsan** [comment]
I'd be interested to look at the data, before and after migration and decompression, the entire list of users missing is suspicious.

**Comment by henokgetachew** [comment]
@dianabarsan I have sent you access to the test data privately.

**Comment by dianabarsan** [comment]
Hi @henokgetachew 
I'm looking into the instance you shared access to and it does seem that there indeed is some data errors. 
For example, I'm looking at the `shards` folder in 3.x CouchDb, compare to `shards` folder from 4.x CouchDb (excerpt): 
```
ubuntu@ip-instance:/cht-3x/storage/medic-core$ sudo ls -la couchdb/data/shards/00000000-1fffffff
-rw-rw-r--  1 998  1001  205013 Jul 20 06:00 medic-purged-role-4f0b7258e805c9f1c0abf4e443ab99d2.1658848800.couch
-rw-rw-r--  1 998  1001   86216 Mar  2 06:00 medic-purged-role-5111f92498eabe781c3e19990049318f.1658848800.couch
-rw-rw-r--  1 998  1001   90312 Mar  2 06:00 medic-purged-role-5644fe421c77864b9037566ebb34882d.1658848800.couch
-rw-rw-r--  1 998  1001  176334 Jul 20 06:00 medic-purged-role-9a95896f66efcd2c2f725a6230ebd0a7.1658848800.couch
-rw-rw-r--  1 998  1001  176334 Jul 20 06:00 medic-purged-role-dc6aef2f5bbad17a51df3cbf5eea105a.1658848800.couch
-rw-rw-r--  1 998  1001  225496 Jul 20 06:00 medic-purged-role-f504eddcf3620476ae085e09909a4c82.1658848800.couch
-rw-rw-r--  1 998  1001 4575451 Jul 19 11:35 medic.1568680669.couch
```
 vs:
```
ubuntu@ip-instance:/cht-4x/data$ ls -la shards/00000000-1fffffff
-rw-r--r--  1 5984 5984  4249 Jul 18 13:56 medic-purged-role-4f0b7258e805c9f1c0abf4e443ab99d2.1658848800.couch
-rw-r--r--  1 5984 5984  4249 Jul 18 13:53 medic-purged-role-5111f92498eabe781c3e19990049318f.1658848800.couch
-rw-r--r--  1 5984 5984  4249 Jul 18 13:56 medic-purged-role-5644fe421c77864b9037566ebb34882d.1658848800.couch
-rw-r--r--  1 5984 5984  4249 Jul 18 13:54 medic-purged-role-9a95896f66efcd2c2f725a6230ebd0a7.1658848800.couch
-rw-r--r--  1 5984 5984  4249 Jul 18 13:56 medic-purged-role-dc6aef2f5bbad17a51df3cbf5eea105a.1658848800.couch
-rw-r--r--  1 5984 5984  4249 Jul 18 13:54 medic-purged-role-f504eddcf3620476ae085e09909a4c82.1658848800.couch
-rw-r--r--  1 5984 5984 20681 Jul 18 13:53 medic.1568680669.couch
```

The difference in size is staggering.

I unzipped the files again, and these are the sizes that I got:
```
ubuntu@ip-instance:/cht-4x/data2$ ls -la shards/00000000-1fffffff/
-rw-rw-r--  1 998  1001  192725 Jul 13 06:00 medic-purged-role-4f0b7258e805c9f1c0abf4e443ab99d2.1658848800.couch
-rw-rw-r--  1 998  1001   86216 Mar  2 06:00 medic-purged-role-5111f92498eabe781c3e19990049318f.1658848800.couch
-rw-rw-r--  1 998  1001   90312 Mar  2 06:00 medic-purged-role-5644fe421c77864b9037566ebb34882d.1658848800.couch
-rw-rw-r--  1 998  1001  164046 Jul 13 06:00 medic-purged-role-9a95896f66efcd2c2f725a6230ebd0a7.1658848800.couch
-rw-rw-r--  1 998  1001  164046 Jul 13 06:00 medic-purged-role-dc6aef2f5bbad17a51df3cbf5eea105a.1658848800.couch
-rw-rw-r--  1 998  1001  213208 Jul 13 06:00 medic-purged-role-f504eddcf3620476ae085e09909a4c82.1658848800.couch
-rw-rw-r--  1 998  1001 4497627 Jul 18 13:13 medic.1568680669.couch
```

I suspect something went wrong when you unzipped, I don't have an explanation. Can you please retry the process?

**Comment by dianabarsan** [comment]
Any updates on this @henokgetachew ?

**Comment by henokgetachew** [comment]
Not yet. I haven't retried the migration for these two instances.

**Comment by dianabarsan** [comment]
@henokgetachew any news on this? 
I believe we found the source of this error (not manually moving shard files around) in other migration attempts.
Is it safe to close this?

**Comment by henokgetachew** [comment]
In these two specific cases, there was no case of actually moving shards because it was from a single node to a single node. However, I'm now fairly convinced that it was a data moving/copying error and so I'm closing this ticket.
