### ISSUE TITLE
Clicking on report `case_id` does not apply search filter

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8401]
**Describe the bug**
When a report has a `case_id` field, this field is highlighted as a link in the report details page, and the link is meant to apply a filter that shows all other reports that have the same `case_id`. The interaction should be described here: https://github.com/medic/cht-core/issues/6291

This interaction is broken, clicking on the `case_id` does nothing. 

**To Reproduce**
1. Add a `case_id` field to a report. 
2. Open the report detail page. 
3. Notice that the `case_id` field is a link. Click the link. 
4. Nothing happens. 

**Expected behavior**
The reports list should be filtered to only display reports that have the same case_id. 

**Logs**
No errors reported. 

**Environment**
- App: webapp
- Version: master, suspecting regressions happened when filters were reworked.

**Comment by latin-panda** [comment]
FYI @ngaruko

**Comment by dianabarsan** [comment]
@latin-panda would you mind adding the appropriate Affects-* tags? I haven't looked closely at what point in development this was introduced.
