### ISSUE TITLE
Flaky test: sms-gateway api returns list and updates state

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8414]
**Describe the issue**
Example run: https://github.com/medic/cht-core/actions/runs/5690753258/job/15425008850#step:16:1498

```
chrome 115.0.5790.102 linux #0-60] 1) - api returns list of pending WO messages - returns list and updates state
[chrome 115.0.5790.102 linux #0-60] expected 'sent' to equal 'forwarded to gateway'      
````

Subsequent retries fail differently.

**Comment by garethbowen** [comment]
I've made an attempt to resolve this and run it a few times successfully - reopen if it reoccurs.
