### ISSUE TITLE
Expose an API with endpoint performance metrics

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8426]
**Is your feature request related to a problem? Please describe.**
Currently it's difficult to work out how long it takes API to respond to requests. This is important for monitoring performance over time and accessing whether performance is acceptable.

**Describe the solution you'd like**
Expose a monitoring API which reports aggregate request durations for specific endpoints.

**Describe alternatives you've considered**
Log analytics but it's complicated.

**Additional context**
One use of this would be for medic/cht-watchdog#60

**Comment by garethbowen** [comment]
@kennsippell Please also update the API documentation here: https://docs.communityhealthtoolkit.org/apps/reference/api/

**Comment by dianabarsan** [comment]
Merged to `master`
