### ISSUE TITLE
Support Nepali digits in Medic ID and LMP Date

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#8447]
**What feature do you want to improve?**
Support Nepali digits on medic id and lmp date and other inputs

**Describe the improvement you'd like**
Accept nepali digits in SMS for medic id field or lmp date. 

**Describe alternatives you've considered**
None

**Additional context**
FCHVs in Nepal use often type in Nepali for patient name field and they need to switch back to english to pass medic id or lmp date. This is inefficient and difficult task for FCHVs as they need to switch input tools from Nepali to English. Accepting Nepali digits in sms for medic id field or lmp date would make their job easy.

**Comment by garethbowen** [comment]
@dianabarsan This is a reasonably safe change that looks like it's ready to go. What do you think about including it in 4.3.0?

**Comment by dianabarsan** [comment]
I think it's a good idea to include it!

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by lorerod** [comment]
Hi, @yrimal @dianabarsan. Do you have the config for the SMS pregnancy form that I can use to test this feature? I am using standard, and it has validations in the lmp date.

**Comment by lorerod** [comment]
### Test details

**Config:** standard
**Environment:** Local using [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:master/docker-compose/cht-couchdb.yml) and [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:master/docker-compose/cht-core.yml)
**Platform:** WebApp

### Test scenario:
Register a pregnancy for this woman using SMS (P form)- web

<details>
<summary>Edited app_settings.json sms pregnancy form definition</summary>

```JSON

{
      "form": "P",
      "events": [
        {
          "name": "on_create",
          "trigger": "add_expected_date",
          "params": "lmp_date",
          "bool_expr": "doc.fields.last_menstrual_period"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "ANC Reminders LMP",
          "bool_expr": "doc.fields.last_menstrual_period"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "Delivery Reminders LMP",
          "bool_expr": "doc.fields.last_menstrual_period"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "ANC Reminders",
          "bool_expr": "!doc.fields.last_menstrual_period"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "Delivery Reminders",
          "bool_expr": "!doc.fields.last_menstrual_period"
        },
        {
          "name": "on_create",
          "trigger": "clear_schedule",
          "params": "ANC Reminders LMP from App, ANC Reminders LMP, ANC Reminders, Delivery Reminders LMP from App, Delivery Reminders LMP, Delivery Reminders, Postnatal Care, Postnatal Care for Facility Birth, Postnatal Care from App, Registration Followup ANC, Registration Followup ANC PNC",
          "bool_expr": ""
        }
      ],
      "validations": {
        "join_responses": true,
        "list": [
          {
            "property": "patient_id",
            "rule": "regex('^[0-9]{5,13}$')",
            "translation_key": "messages.generic.validation.patient_id"
          }
        ]
      }

```
</details>

<details>
<summary>SMS send</summary>

![SMS send](https://github.com/medic/cht-core/assets/21312057/e62ef21b-d182-48ad-a297-693e1b269d36)


</details>

<details>
<summary>Report created</summary>

![Report created 1png](https://github.com/medic/cht-core/assets/21312057/97ba40ed-aa29-4c0d-9655-e4b447156645)


</details>


Test passed successfully. :white_check_mark:

Please let me know if you would like me to check with another config or another scenario.
