### ISSUE TITLE
Add support for HTTP/2 in nginx 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8451]
**Describe the issue**
In our [nginx config](https://github.com/medic/cht-core/blob/master/nginx/nginx.conf), we only support HTTP/1 

**Describe the improvement you'd like**
By adding support for HTTP/2, we can improve performance for self hosted deployments who have nginx facing CHWs

**Describe alternatives you've considered**
currently AWS hosted (including Medic hosted) CHT deployments use [ELB](https://aws.amazon.com/elasticloadbalancing/) which [already supports HTTP/2](https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#load-balancer-scheme), so we could do nothing and leverage this.  As well, other self hosted partners could use [traefik](https://traefik.io/traefik/) or [caddy](https://caddyserver.com/).

**Comment by mrjones-plip** [comment]
Turns out we can't use [the old ciphers currently in `master`](https://github.com/medic/cht-core/blob/9a2619d45e04a9d64acd95dd0c638b9d5c242e7a/nginx/nginx.conf#L50), so we need to wait until #8335 is merged before we can make this work.

**Comment by garethbowen** [comment]
Merged!
Thanks @mrjones-plip and @nydr
