### ISSUE TITLE
Loading the webapp fails on with WebView version 74

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8456]
**Describe the bug**
Starting at CHT 4.2.0, when a self hosted CHT instance uses `nginx` as it's front end, certain Android devices fail with a console error `Uncaught SyntaxError: Unexpected token ? main.js:1`

**To Reproduce**
1. Install CHT Core 4.2.0 in docker helper. Do not use AWS ELB
2. Using CHT Android 1.0.1 with webview 74 or lower, connect to CHT Core
4. See error in console `Uncaught SyntaxError: Unexpected token ? main.js:1` and see full screen spinner.  

**Expected behavior**
You should be prompted to log in to the CHT with no errors in console

**Screenshots**

<details>
<summary>Console tab</summary>

<img width="1319" alt="Captura de pantalla 2023-08-11 a la(s) 13 40 35" src="https://github.com/medic/cht-core/assets/21312057/86f3edbc-bd19-40ba-8f40-afc1b53fad3d">

</details>

<details>
<summary>Network tab</summary>

<img width="1326" alt="Captura de pantalla 2023-08-11 a la(s) 13 40 17" src="https://github.com/medic/cht-core/assets/21312057/9b240b7b-4fe4-4443-8f95-6ff62c91f276">

</details>

<details>
<summary>Security tab</summary>

<img width="1314" alt="Captura de pantalla 2023-08-11 a la(s) 13 40 25" src="https://github.com/medic/cht-core/assets/21312057/a9b6c124-1709-47f9-b66b-0c617a73b6bb">

</details>

**Environment**
- Instance: local dev
- Browser: CHT Android 1.0.1 WebView 74 or 68
- Client platform: See above
- App: webapp
- Version: 4.2.0 and above
  
**Additional context**
This was discovered while testing #8278.  It's assumed that this wasn't caught earlier because we test on Gamma which uses AWS ELB to terminate TLS.  Indeed, testing CHT COre 4.2.0 on Gamma  with the exact same handset as above works.  Testing on 4.1.0 and 4.0.0 on the same handset also work. 

Also, testing the same 4.2.0 instance with WebView 111 worked fine. All desktop browsers worked as well.

**Comment by garethbowen** [comment]
This may be resolved by setting a higher minimum browser version as part of https://github.com/medic/cht-core/issues/7448 but we don't currently know the upper bound on this issue so we need to look into it regardless.

@mrjones-plip It looks like this is happening after login - is that correct?

**Comment by dianabarsan** [comment]
I believe what is happening here is that Tatiana is navigating to root, which attempts to load the main code (main.js,. scripts.js). This code is responsible for checking whether the user is logged in and eventually redirect them to login.

**Comment by mrjones-plip** [comment]
Ah - thanks @dianabarsan ! 

We're using unbranded and entering the URL of the docker helper instance - so it's what ever default behavior of CHT Android unbranded in this case.

**Comment by dianabarsan** [comment]
I believe this is because of the Angular upgrade: https://github.com/medic/cht-core/issues/7992 we did in 4.2 
https://github.com/medic/cht-core/pull/7999#issuecomment-1383565270

> I've updated the .browserlistrc and the isUsingSupportedBrowser function from the browser detection services to support chrome v80 which includes the features of es2020.

**Comment by dianabarsan** [comment]
I'm not sure we can do anything about this, unfortunately, and we were already aware of this issue - we even discussed with @craig-landry, @garethbowen and @kennsippell post ZNZ meetup.

**Comment by mrjones-plip** [comment]
ah - thanks for the research into the cause being the angular bump to 15 in CHT 4.2 @dianabarsan! I think a reasonable remediation is to detect WebView <80  and alert that we're not compatible.  I know we did a bit of this work in #7448, but should complete the effort with the recently filed #8159.

Given this is "working as designed" per your comment re ZNZ meetup, do we feel this is still a bug then?  Maybe just close this in favor of  #8159?

**Comment by mrjones-plip** [comment]
@kennsippell  - curious on your thoughts as you're closer to what the field and live deployments sees things as.  Further, I know you've explored [client telemetry](https://github.com/medic/cht-app-monitoring-data-ingest/pull/71) and what folks are actually running!

**Comment by garethbowen** [comment]
@mrjones-plip Do we have any data on what versions _do_ work? Is 80 ok?

**Comment by mrjones-plip** [comment]
We know for sure 95 works on my Android 5.1 device and  QA had an Android 9 device with 79  that failed and then upgraded to latest (accidentally) and started working.  Only two data points, but coupled with [Diana's research](https://github.com/medic/cht-core/issues/8456#issuecomment-1681092467), 80 sounds correct to me.

@garethbowen  - I propose  remove the  `Affects:*` labels, remove from `4.3.0` release, closing this ticket and focusing on #8159

**Comment by garethbowen** [comment]
@mrjones-plip I agree. My only concern is that 74 is higher than the previously communicated 72. However we're starting to make good progress on testing and communicating browser support versions better...
