### ISSUE TITLE
API fails to start because of large form attachments exceed POST allowed payload

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8457]
**Describe the bug**
A [step] in our API startup sequence is to re-generate all forms attachments: https://github.com/medic/cht-core/blob/master/api/src/services/generate-xform.js#L258
The code attempts to update all forms at one, in one big `_bulk_docs` request. The payload for this request will include all form attachments and form docs. This includes images and any other media elements that the forms require. 
This request can fail with a `413 Content Too Large`.

**To Reproduce**
1. Create some forms that have very large media attachments. Upload these forms individually to the server. An alternative would be to create many forms. 
2. Restart API
3. See error

![image](https://github.com/medic/cht-core/assets/35681649/eb6e184b-e413-42a8-a836-9d8873021908)

**Expected behavior**
API should not fail to start when there are too many forms to upload. 

**Environment**
- Instance: any
- App: api
- Version: Code was not changed since 3.7.0, it's possible this only affects 4.0.0+ due to architecture changes, but I have not tested. 

**Additional context**
Originally reported on the forum.

**Comment by job-isabai** [comment]
Hello Everyone, we got this error when upgrading from 3.15 to 4.2.2 using the data migration guide on docs. Currently our installation is stuck at: "Installing forms".

**Comment by magp18** [comment]
We tried commenting the parameters "max_document_size" and "max_attachment_size" (they were commented out) in the default ini of the couchdb inside of the couchdb container and restarting the container (thanks  @delcroip ). Now we don't seem to have the 413 anymore but we have this one instead
![image](https://github.com/medic/cht-core/assets/33976946/61825140-4a90-48c4-ac43-726ff715a3e1)

**Comment by delcroip** [comment]
> We tried commenting the parameters "max_document_size" and "max_attachment_size" (they were commented out) in the default ini of the couchdb inside of the couchdb container and restarting the container (thanks  @delcroip ). Now we don't seem to have the 413 anymore but we have this one instead
> ![image](https://github.com/medic/cht-core/assets/33976946/61825140-4a90-48c4-ac43-726ff715a3e1)
> 

This was done on the couchdb container level

I had once a similar issue with cht-conf when pushing a form with lots/big images.

I worked on the image size so I never checked the root cause

Br

**Comment by dianabarsan** [comment]
Thanks for the feedback @magp18 and @delcroip 

Indeed, I believe you are seeing this issue because you have very large media attached to your forms. 
It's best practice to reduce the size of media, as offline users will also download these files every time the forms receive updates. 

I'll experiment with `max_document_size` and `max_attachment_size` to see what the default values are, indeed we don't set them in our config so we rely on CouchDb defaults. 

@delcroip 
I'm not sure the timeout is related. I need more logs to figure out where api fails in your second example.

**Comment by job-isabai** [comment]
@dianabarsan we have the following:
![image](https://github.com/medic/cht-core/assets/100341653/c862af80-b611-47a3-a937-c37857f33131)
We got Error 500, see the attached log file for cht_api_1 container.
[cht_api_1_logs.txt](https://github.com/medic/cht-core/files/12343081/cht_api_1_logs.txt)

**Comment by dianabarsan** [comment]
This is curious. It seems that the write is failing with a timeout. Could you please check haproxy logs for these timeout errors and share the logs? Thanks!

**Comment by job-isabai** [comment]
Hi @dianabarsan ,
It seem the fix worked. I stepped out for lunch only to find the system already upgraded and running. 
I will still share the logs with you.
Thank you so far for the support, much appreciated.
thanks,
Job

**Comment by job-isabai** [comment]
[cht_haproxy_1_logs.txt](https://github.com/medic/cht-core/files/12343673/cht_haproxy_1_logs.txt)

**Comment by dianabarsan** [comment]
Thanks for sharing the logs, @job-isabai 

This is the request that was timing out: 
```
<150>Aug 15 09:26:39 haproxy[12]: 172.18.0.8,couchdb,500,49137,0,0,GET,/medic/_all_docs?include_docs=true&attachments=true&startkey=%22form%3A%22&endkey=%22form%3A%EF%BF%B0%22,api,medic,'-',339,9010,98,'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)'
```

This is very strange - I've never seen an _all_docs request fail like this. Would you be willing to make this request yourself and provide the size of the payload?

**Comment by dianabarsan** [comment]
Merged to `master`.
