### ISSUE TITLE
Update nginx to latest 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8459]
**Describe the issue**
Right now we're running version `nginx:1.19.6-alpine` of the [docker image](https://github.com/medic/cht-core/blob/9a2619d45e04a9d64acd95dd0c638b9d5c242e7a/nginx/Dockerfile#L2).  We should update it.

**Describe the improvement you'd like**
Update to latest version of `nginx:1.X-alpine` image. As of this writing [it's `1.25.1-alpine`](https://hub.docker.com/layers/library/nginx/1.25.1-alpine/images/sha256-ccf066d2cfec0cfe57a63cf26f4b7cabbea80e11ab5b7f1cc11a1b5efd65ea0b?context=explore)

**Describe alternatives you've considered**
Don't upgrade

**Comment by nydr** [comment]
Sounds great! Other things to consider, which is likely out of scope for this change:
1. Automatically update on security vulnerabilities using [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker) or internal scripts
2. Adding `zlib` and other potentially vulnerable packages to the `apk add --update` command in the dockerfile and possibly a way to ensure cache is not being used on build like for example a date variable above or date comment in the run command
