### ISSUE TITLE
Invalid phone for patient still running triggers

### ISSUE THREAD

**Issue by yrimal** [medic/cht-core#8478]
**Describe the bug**
CHT-Core 4.3 recently added a feature where we can register patient by passing patient phone number.  Though phone number validation is done internally, since 

**To Reproduce**

1. Prepare a patient registration form with schedule and phone number field on patient. 

<details>
  <summary>Click for config</summary>
 
  ### Sample config
 ```json
{
      "form": "N",
      "events": [
        {
          "name": "on_create",
          "trigger": "add_patient_id",
          "params": "",
          "bool_expr": "doc.patient_name"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "Registration Reminders",
          "bool_expr": "doc.patient_name"
        }
      ],
      "validations": {
        "join_responses": false,
        "list": [
          {
            "property": "patient_phone",
            "translation_key": "messages.n_na.duplicate_phone",
            "rule": "uniquePhone('patient_phone')"
          },
          {
            "property": "patient_age",
            "rule": "(integer && min(0) && max(125))",
            "translation_key": "messages.n.invalid_format"
          },
          {
            "property": "patient_name",
            "rule": "(string && lenMin(1) && lenMax(30))",
            "translation_key": "messages.n.invalid_format"
          }
        ]
      },
      "messages": [
        {
          "translation_key": "messages.n_na.registered",
          "recipient": "",
          "event_type": "report_accepted",
          "bool_expr": "doc.errors.length===0"
        },
        {
          "translation_key": "messages.n_na.duplicate_phone",
          "recipient": "",
          "event_type": "provided_phone_not_unique"
        }
      ]
    }
```
</details>

2. Submit this form with some invalid phone number

**Expected behavior**
1. First trigger `add_patient_id` shouldn't run and patient id shouldn't be assigned. 
2. Second trigger `assign_schedule` should not be created. 

**Screenshots**

Look at Invalid message, generated medic id, and reminder schedules created. 

<img width="745" alt="image" src="https://github.com/medic/cht-core/assets/6102813/769e5e19-deeb-45fc-9629-d4f0f52350cd">

**Environment**
- Instance: (eg: jajarkot-ne dev instance)
- Browser: Any
- Client platform: Any
- App: webapp, api
- Version: (eg: 4.3)

**Proposed solution:**
Expose a method to validate phone in app_settings in [rules](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/#rules), such that we can call phone validation and give message, and stop transition.

**Comment by PrjShrestha** [comment]
@yrimal Didn't know having a phone validation failing inside add_patient trigger wouldn't stop other triggers from running. Thanks for catching this. 

I had [tried adding the valid_phone validation to the list of validations ](https://github.com/medic/cht-core/pull/8369/commits/a4b55afa5a480149825e0959616522d92c2d0cb3#diff-28eb89c6813eb2dfc98b0b30fd0e87ed7be5df013425f11dabf80442db3a430d)but it seemed trivial and that whether a phone is valid or not should be in the code itself.  

I will re-add the validation like you mentioned in the solution as well which should fix the problem.

**Comment by PrjShrestha** [comment]
PR [here](https://github.com/medic/cht-core/pull/8479).

cc: @yrimal @garethbowen

**Comment by yrimal** [comment]
@PrjShrestha , Thanks for the fix. I performed a testing on it and validPhone throws validation error and stops triggers from execution, which solves the problem described here. 

@medic/quality-assurance, seeking your testing and input on this.

**Comment by garethbowen** [comment]
@PrjShrestha Thanks for getting on to this so quickly. Is this serious enough to warrant a patch release (eg: 4.3.1) or can it wait till the next minor in a couple of months?

**Comment by garethbowen** [comment]
@tatilepizs As you helped out with #8204 would you also mind assisting with this?

**Comment by yrimal** [comment]
>Is this serious enough to warrant a patch release (eg: 4.3.1) or can it wait till the next minor in a couple of months?

Hi @garethbowen , We'd be wanting this to release on 4.3.1. This isn't a major incident, but important enough to fix sooner.

**Comment by tatilepizs** [comment]
@PrjShrestha,

Using the [app_settings.json](https://github.com/medic/cht-core/files/12422712/app_settings.json.zip) file that you provide (thanks again for that), I am still able to see the outgoing messages using the branch `PrjShrestha:valid_phone_8478`, is there something else that I need to change or update before testing on your branch?

<details>
<summary>Video - tested in master</summary>

[video](https://github.com/medic/cht-core/assets/94494491/f436c261-7dc4-4edd-849b-6f2629d952d8)

</details>

<details>
<summary>Image - Tested in PrjShrestha:valid_phone_8478</summary>

![image](https://github.com/medic/cht-core/assets/94494491/b6a18b9c-5107-4198-91fe-8b7a8084dd14)

</details>

**Comment by yrimal** [comment]
Hi @tatilepizs , 
The test should be against validPhone function. To do so, you can add following validation in your current app_settings, line 673. 
```json
  {
    "property": "patient_phone",
    "translation_key": "messages.n_na.invalid_phone",
    "rule": "validPhone('patient_phone')"
  },
```
When an invalid phone number is passed, schedules shouldn't be created. When valid phone is passed, schedules should be created. I've tested it against master with config like this and this has worked.

**Comment by tatilepizs** [comment]
Thank you @yrimal  for your help.

It worked as expected the validation of an invalid phone

Using the [app_settings.json](https://github.com/medic/cht-core/files/12430866/app_settings.json.zip) file the outgoing messages were shown when I tested in `master` but they were not shown when I tested in `PrjShrestha:valid_phone_8478`. Images attached.

<details>
<summary>Test in master</summary>

![image](https://github.com/medic/cht-core/assets/94494491/dc90d230-2cba-4260-b902-c6875665ddbd)

</details>

<details>
<summary>Test in PrjShrestha:valid_phone_8478</summary>

![image](https://github.com/medic/cht-core/assets/94494491/9257a069-8390-4b22-8fd3-724f44d25211)

</details>

⚠️ I just have one question, using the `validPhone` function works fine if an invalid phone is sent, but if a duplicated phone is sent it creates the two patients without any problem. Shouldn't that function validate the two things? check if the phone is valid and if it is not duplicated.

<details>
<summary>Images of the test for duplicated phones</summary>

![image](https://github.com/medic/cht-core/assets/94494491/341fab61-f611-4503-ae8a-eb10348bbacc)
![image](https://github.com/medic/cht-core/assets/94494491/975f17f9-074d-4c8d-a38f-127214a1534a)
![image](https://github.com/medic/cht-core/assets/94494491/14b30acd-1de5-4e47-a5cf-c6798e183c04)


</details>

**Comment by yrimal** [comment]
>Shouldn't that function validate the two things? check if the phone is valid and if it is not duplicated.

That is two separate function @tatilepizs . Sometimes, we need to allow duplicate phones and that's configurable. Duplicate phone can be tested using already implemented `uniquePhone` rule check.

**Comment by tatilepizs** [comment]
Perfect @yrimal, thank you for the clarification 
It is good to go then 🎉

**Comment by garethbowen** [comment]
Merged and backported - waiting to merge the docs PR before closing.
