### ISSUE TITLE
Remove upgrade e2e's temporary modal logic

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8501]
**Describe the issue**
Because we migrated modals to use Angular Material ([PR](https://github.com/medic/cht-core/pull/8441)), we had to add some temporary logic to the upgrade e2e  tests that are loading the old version of the app which has the bootstrap modals. 

Once 4.4 is released, remove that temporary logic.

**Comment by garethbowen** [comment]
@latin-panda Is this ready for review?

**Comment by latin-panda** [comment]
@garethbowen No yet, it fails to upgrade from [4.4.1 to the branch,](https://github.com/medic/cht-core/actions/runs/6740871292/job/18325867471?pr=8665#step:8:435) and not sure why. I need to debug it.

**Comment by latin-panda** [comment]
This is resolved in this [PR](https://github.com/medic/cht-core/pull/8696)
