### ISSUE TITLE
Align "Target" components with Material design guidelines

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#8513]
Update CHT "[Targets](https://docs.communityhealthtoolkit.org/apps/features/targets/)" to align with Material guidelines (see [Cards](https://m3.material.io/components/cards/guidelines)). This will only update the visual design, no functional changes will be made. 

#### Personal Targets
- Each "card" will be separated into two content areas
- The content areas will use shading and/or a line to delineate them
- The labels and images which used to be on the top, will be in the lower content area
- Instead of using red for unmet targets, we'll use black

#### Aggregate Targets
- The only thing we are changing is coloring, use black for unmet targets instead of red

###  Example current and new visual design 

See [figma](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?type=design&node-id=2701-3724&mode=design&t=9dub0EjaIJZo5G06-0) for full details

![Screenshot 2023-09-01 at 3 54 39 PM](https://github.com/medic/cht-core/assets/10096985/e67d6092-b30e-4014-8eb5-526aa95c568f)

### Scenarios to test

There are two types of widgets: Numeric and Percent. And for each, they can have a goal set or not, and the goal can be met or not. 

#|Widget Type|Has Goal?|Goal Met?|Color
--|--|--|--|--
1|Numeric|No||Green
2|Numeric|Yes|No|Black
3|Numeric|Yes|Yes|Green
4|Percent|No||Green
5|Percent|Yes|No|Black
6|Percent|Yes|Yes|Green

### Documentation Updates

- [ ] https://docs.communityhealthtoolkit.org/apps/features/targets/
- [ ] https://docs.communityhealthtoolkit.org/apps/tutorials/targets/
- [ ] https://docs.communityhealthtoolkit.org/apps/reference/targets/
- [ ] https://docs.communityhealthtoolkit.org/design/best-practices/#targets
- [ ] https://www.figma.com/file/Zl8TNPi7iNF0t5k0ZxSeId/Medic-Library?type=design&node-id=0-5430&mode=design&t=lUyGvvNAU3DuEgwd-0

**Comment by n-orlowski** [comment]
[Figma link here with all the instances](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?type=design&node-id=2701%3A3724&mode=design&t=emFrsbkEjCbZdWTn-1)

**Comment by latin-panda** [comment]
@ngaruko @Benmuiruri Please double check that target aggregates doesn't get side effects by this work :)

**Comment by michaelkohn** [comment]
We originally weren't planning on touching anything on aggregate targets, but Jenni's message above made me realize there are a few places in aggregate targets that we _will_ need to update to stay consistent with what we are doing for personal (CHW) targets.

For personal targets, we are changing red text and red bars to black whenever a goal is not met, we should do the same for aggregate targets. We don't need to change any other visual design for aggregate targets, but should update the text color. I'm going to update the first comment to clarify all this.

**Comment by ngaruko** [comment]
From a QA pov, we don't seem to have a test that covers these visuals for met or unmet goals/targets. So, we should introduce a test that check the color of the target (met or unmet) > maybe use [getCssProperty](https://webdriver.io/docs/api/element/getCSSProperty/) to check for this for instance:
<img width="828" alt="image" src="https://github.com/medic/cht-core/assets/6979995/cdfd4976-e649-46ff-b35e-8b30fea6540f">

I also noticed we could re-organise our test folders better: atm, we have target tests in [tests/e2e/default/analytics/analytics.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/analytics/analytics.wdio-spec.js) and target aggregates tests in [/tests/e2e/default/targets/target-aggregates.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/targets/target-aggregates.wdio-spec.js). It would be neater to move the target aggregates tests in /analytics. Your thought @latin-panda ?
@Benmuiruri Please let me know once you start working on this, and need some help with setting up the instance for target aggregates or regarding the e2e tests.

**Comment by Benmuiruri** [comment]
Thanks @ngaruko  I am starting to work on it now. I'll reach out to you when I get to the e2e tests.

**Comment by latin-panda** [comment]
> we have target tests in [tests/e2e/default/analytics/analytics.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/analytics/analytics.wdio-spec.js) and target aggregates tests in [/tests/e2e/default/targets/target-aggregates.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/targets/target-aggregates.wdio-spec.js). It would be neater to move the target aggregates tests in /analytics. Your thought @ latin-panda ?

For us, analytics and targets refer to the same thing, to avoid confusion makes sense to rename them to `analytics-aggregates.wdio-spec.js` and move them to the `analytics` folder. However, this is the last step of this work.

**Comment by garethbowen** [comment]
@Benmuiruri This looks like it's ready to merge. Is that right? NB: You may need to rebase to get the builds to pass...

**Comment by Benmuiruri** [comment]
This has been completed in #8590
