### ISSUE TITLE
Action button uses wrong font

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8520]
**Describe the bug**
The "new household" button at the bottom of the LHS is using Roboto instead of Noto font used elsewhere in the app.

**Screenshots**

Actual
![image](https://github.com/medic/cht-core/assets/2064938/e4bd701c-aaf4-4ee7-9023-acfd285f554d)

Expected
![image](https://github.com/medic/cht-core/assets/2064938/ecf39787-f1cb-4d5b-b3ab-2ff6f3842a32)

**Environment**
- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 4.3.0

**Additional info**
Also impacts other areas, like the dialog buttons.

**Comment by latin-panda** [comment]
Fix in https://github.com/medic/cht-core/pull/8515
