### ISSUE TITLE
Flaky test: More Options Menu - Offline User all permissions disabled

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8522]
**Describe the issue**
This test fails with:

```
[chrome 116.0.5845.96 linux #0-9] 1) all permissions disabled  - all tabs, kebab menu not available
[chrome 116.0.5845.96 linux #0-9] expected true to be false      
```

https://github.com/medic/cht-core/actions/runs/6092583125/job/16531117558#step:16:477

**Comment by garethbowen** [comment]
Two failures in the last week. @latin-panda Would you mind having a look?

**Comment by dianabarsan** [comment]
I'm seeing this fail repeatedly in the CouchDb 3 branch, which can imply that limiting CPU can help replicate this locally.
