### ISSUE TITLE
Flaky test: Service worker cache  adding new languages triggers login page refresh

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8538]
**Describe the issue**
This test is failing with:
```
1) Service worker cache adding new languages triggers login page refresh
[chrome 116.0.5845.140 linux #0-1] Node is either not clickable or not an HTMLElement
[chrome 116.0.5845.140 linux #0-1] Node is either not clickable or not an HTMLElement
[chrome 116.0.5845.140 linux #0-1] Error: Node is either not clickable or not an HTMLElement
[chrome 116.0.5845.140 linux #0-1]     at ElementHandle.clickablePoint (file:///home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/ElementHandle.ts:557:13)
[chrome 116.0.5845.140 linux #0-1]     at runMicrotasks (<anonymous>)
[chrome 116.0.5845.140 linux #0-1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[chrome 116.0.5845.140 linux #0-1]     at async ElementHandle.click (file:///home/runner/work/cht-core/cht-core/node_modules/puppeteer-core/src/common/ElementHandle.ts:668:20)
```

Example run:
https://github.com/medic/cht-core/actions/runs/6154832305/job/16701009464#step:16:537

![image](https://github.com/medic/cht-core/assets/35681649/e50495f4-d253-41f0-9334-edf2303ee83b)

**Comment by garethbowen** [comment]
The transparency in that image makes it look like it's a race condition. It might've been introduced with the angular modals if they have some sort of fade in animation. We should make sure the tests are waiting for is clickable, not just exists.

**Comment by dianabarsan** [comment]
A picture is worth a thousands words .... ;)

**Comment by garethbowen** [comment]
This one keeps biting me.

**Comment by garethbowen** [comment]
Had a quick look at this today. The logs are not at all helpful but I think it's trying to cancel the modal. Other tests also call this code and it's working for them.

The close modal code waits for the cancel button to be clickable and the clicks it. It's not clear from the image whether the modal is fading in or out, but my theory is it was clickable initially, and then is fading away (or a new one fading in) when the click is attempted.

**Comment by dianabarsan** [comment]
Can it be that the modal rework can trigger a dual modal? We used to have code that prevented this.

**Comment by garethbowen** [comment]
Yes quite possibly, I can't see any indication that it's there in the new implementation.

**Comment by garethbowen** [comment]
And again this week.
