### ISSUE TITLE
Sentinel stuck in infinite loop when 100 sequential deletions fail to generate tombstones

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8539]
**Describe the bug**
Sentinel only advances its `transitions-seq` sequence if a successful change is processed. 
Sentinel also only loads 100 docs at a time, to prevent an OOM error when there are millions of changes to process. 

If all of the 100 sequential changes fail to be processed by transitions, sentinel will keep requesting the same 100 docs over and over and be stuck in this loop forever. 

**To Reproduce**
This is easiest to reproduce in 4.2.2 and lower, because we can use tombstones to trigger this. Transitions alone will only error when writes fail, but tombstones can fail for a variety of reasons.

1. Launch CHT v 4.2.2. 
2. Stop sentinel. 
3. With a script, create 1000 documents. Then delete those 100 documents, making sure you only save 3 keys in your delete, `_id`, `_rev` and `_deleted`. 
4. Run compaction. 
5. Start Sentinel. 
6. Leave sentinel running for a while and observe that the number of docs to process stays the same - you can use the monitoring endpoint for this. 
If you check the logs, you will see that sections like: 
```
2023-09-12 14:43:05 ERROR: Tombstone: could not process doc id: <doc_id> seq: <SEQ> {
  error: 'not_found',
  reason: 'missing',
  status: 404,
  name: 'not_found',
  message: 'missing',
  docId: <doc_id>
} 
```
If you search the log for the same doc id, you will find multiple appearances for the same doc. 

**Expected behavior**
For tombstones specifically, we could advance the seq even if the tombstone could not be created (?). For other failures, I'm not sure.

**Environment**
- Instance: live training instance
- App: sentinel
- Version: 3.9+, tombstones no longer trigger this in 4.3+. 

**Additional context**
This was affecting a live training instance. 
As a workaround, the sentinel seq can be advanced manually to skip the problematic batches.

**Comment by dianabarsan** [comment]
Given that this mostly affects v4.2 and lower, because of the interaction with how tombstones are generated. 

The only ways I can see this occurring on non-deletes is by:
- bugs in lineage shared library (uncaught errors)
- bugs in infodoc shared library (uncaught errors)
- errors on saving transitions - CouchDb repeatedly failing to write 

For all of these, the infinite sentinel queue is just a symptom of a separare (bigger?) problem. 
We can address it, but I don't see that solution as important as handling tombstones in 4.2. 

Seeking feedback from @garethbowen . (thanks!!)

**Comment by garethbowen** [comment]
I think we need to raise a new issue for the generic case, so this one can be solely related to tombstones. It's probably worth publishing a 4.2.3 to patch this, would you agree?

For the generic case there are heaps of possible solutions but none that are easy and good...

- We could just back off the retry or squelch the logging to minimise the impact of this issue.
- We could mark certain docs as permanently failed after x tries and keep going and allow for manually resetting it somehow if the cause is fixed.
- We could make sentinel not run sequentially somehow which would mean it could scale horizontally.
- We could make sentinel transitions 100% synchronous (no writes happen on the db without first having transitions executed). I think this is where we'll eventually end up so we can scale, catch errors like this earlier, and be more responsive. It completely gets around this issue because you can't "stop sentinel" which is something that seems to occur way too often in production...

**Comment by dianabarsan** [comment]
> It's probably worth publishing a 4.2.3 to patch this, would you agree?

Yes, this was my thinking as well. 

For solutions, without removing Sentinel entirely in a patch (make sentinel transitions 100% synchronous), the solution I was leaning on was marking docs as permanently failed and skipping them. This is the least complex option and easiest to implement.

**Comment by garethbowen** [comment]
> marking docs as permanently failed and skipping them

Yeah it's certainly one of the easiest solutions. The problem is if it's a configuration bug or something then every doc will get failed and it will be difficult to undo the damage...

**Comment by dianabarsan** [comment]
> The problem is if it's a configuration bug or something then every doc will get failed and it will be difficult to undo the damage

This has been our general approach anyway: 
>// todo: how to handle a failed save? for now just
    // waiting until next change and try again.

https://github.com/medic/cht-core/blob/08ec4d72d2a0bc3c20de53b8fefbbf6d9e23168f/shared-libs/transitions/src/transitions/index.js#L259C48-L259C48

**Comment by dianabarsan** [comment]
This is also what happens currently, if within a batch at least one document advances the Sentinel seq.

**Comment by mrjones-plip** [comment]
I updated the `Affects: *` labels with all versions except `4.3.0` and  `4.3.1`. Lemme know if that isn't correct!

**Comment by dianabarsan** [comment]
It affects all versions, but 4.3.x has a different interaction.
