### ISSUE TITLE
Translations don't load after upgrade to CHT 4.4

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8572]
**Describe the bug**
When a demo instance of the CHT running 4.3.1 was upgraded to 4.4, translations weren't loaded as they should be . See here in the top image the wrong modal and the bottom image the correct modal:

![image](https://github.com/medic/cht-core/assets/8253488/5350f9b3-0289-4b2c-a758-c259b6e2ba39)

**To Reproduce**
We've been unable to reproduce :disappointed: 

**Expected behavior**
All translations are working

**Environment**
- Instance: demo-cht.dev.medicmobile.org
- Browser: NA
- Client platform: NA
- App: NA
- Version: 4.4.0

**Additional context**

There's an easy fix which is to just restart API container which reloaded the translations and everything was fixed.

**Comment by garethbowen** [comment]
We haven't been able to reproduce this one, so closing it off. Please reopen with more info if it happens again!

**Comment by 1yuv** [comment]
Just for the context: I wasn't able to see this issue when I upgraded from 4.4.1 to 4.5.0 either.
