### ISSUE TITLE
Asterisk for required field in form located on new line when in `summary` group

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8585]
**Describe the bug**
Originally reported [on the forum](https://forum.communityhealthtoolkit.org/t/alignment-of-labels-with-asterisks-in-app-forms/3057/1).  If you have a `required` field in your form, you will see an asterisk (`*`) at the end of the label to indicate the question is required.  However, if that field happens to be in a group with the `summary` appearance, then the asterisk will be shown on a new line below the label (instead of just being appended to the same line as the label).  

**Expected behavior**
![image](https://github.com/medic/cht-core/assets/8441903/20867cc2-ffa2-4c7f-b2b6-e94adcd70bb8)

**Actual behavior**
![image](https://github.com/medic/cht-core/assets/8441903/b000b735-822a-482a-94e7-cb3b4e5cc428)

**Additional Information**
I have confirmed this behavior from `master` back to `3.17.1`, but I image it goes back much further than that.

**Comment by latin-panda** [comment]
The issue happens with the fields type `string`
