### ISSUE TITLE
CouchDB single-node set-up script fails at creating system db's if admin pw contains special characters

### ISSUE THREAD

**Issue by Hareet** [medic/cht-core#8599]
### Issue

We have a partner who deployed single-node cht-core and used many special characters in their admin password.

Our set-up-cluster.sh script fails silently [here ](https://github.com/medic/cht-core/blob/4.3.x/couchdb/set-up-cluster.sh#L104)

### Expected
We should escape characters properly, document password restrictions and not fail silently on this command.

**Comment by mrjones-plip** [comment]
So this was a 4.3.1 instance and they manually crafted a password in the `.env` file on [the "prepare env file" step](https://docs.communityhealthtoolkit.org/apps/guides/hosting/4.x/self-hosting-single-node/#prepare-environment-variables-file) and then  we failed to parse on the [line you cited](https://github.com/medic/cht-core/blob/4.3.x/couchdb/set-up-cluster.sh#L104)?  

I believe the password had `*` and `!` in it which cause the problem, correct?

**Comment by nydr** [comment]
Resolved by https://github.com/medic/cht-core/pull/8908
