### ISSUE TITLE
Automated test: pregnancy_visit, default config

### ISSUE THREAD

**Issue by tatilepizs** [medic/cht-core#8603]
**What feature do you want to improve?**
The e2e automated test that we have in the [default folder](https://github.com/medic/cht-core/tree/master/tests/e2e/default) is not testing the form from the `default` config, it is using the form from the `standard` config. 

**Describe the improvement you'd like**
Update the [pregnancy-visit.wdio-spec.js](https://github.com/medic/cht-core/blob/master/tests/e2e/default/enketo/pregnancy-visit.wdio-spec.js) file to test the correct form. In the [page-objects/default/enketo/pregnancy-visit.wdio.page.js file](https://github.com/medic/cht-core/blob/master/tests/page-objects/default/enketo/pregnancy-visit.wdio.page.js) file, it is importing the form from the `standard` config and not the one from the `default` config. We should not create any document, we should create a pregnancy and then create a pregnancy visit as the manual process. 

**Describe alternatives you've considered**

**Additional context**

**Comment by lorerod** [comment]
@andrablaj this was closed by [chore(#8701): Clean and organize e2e tests: folder /enketo](https://github.com/medic/cht-core/pull/8812#top)
