### ISSUE TITLE
Show URL when done running k3d script

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8605]
**Describe the issue**
when you're done using the soon to be [merged k3d `cht-deploy` script](https://github.com/medic/cht-core/pull/8263), you don't know what the URL of your instance is

**Describe the improvement you'd like**
we should output the URL of your instance:

```
  ➜  deploy git:(cht-k8s-configuration) ✗ ./cht-deploy -f values.yml


   --------------    SUCCESS      -------------- 
   https://mrjones.dev.medicmobile.org is live!
   ------------------------------------------------- 
 
 Namespace mrjones already exists.
 Release does not exist. Performing install.
 NAME: mrjones
 LAST DEPLOYED: Fri Sep 15 16:36:31 2023
 NAMESPACE: mrjones
 STATUS: deployed
 REVISION: 1
 TEST SUITE: None
```

**Describe alternatives you've considered**

**Comment by henokgetachew** [comment]
Completed. PR in review.
