### ISSUE TITLE
add a "get all logs" script for k3d deployments

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8608]
**Describe the issue**
when you're using the [soon merged k3d `troubleshooting/view-logs` script](https://github.com/medic/cht-core/pull/8263), there's no easy way to get all logs and node/cluster/what ever state for k3d deployments 

**Describe the improvement you'd like**
It'd be rad to have a "debug" script [like this one](https://docs.communityhealthtoolkit.org/apps/guides/debugging/sharing-4x-logs/). I could run it now and answer all like 49 bazzilion questions you wanna ask me in one go!

**Describe alternatives you've considered**

**Comment by henokgetachew** [comment]
Completed. PR in review.
