### ISSUE TITLE
Allow schedule to start with multiple fields

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#8633]
**Is your feature request related to a problem? Please describe.**
We need to create one schedule based on multiple forms and SMS. And sadly, not all forms and reports create a field at the same level or name. [`start_from` in schedules.json](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/schedules/) currently accepts only one field. Problem ius explained here in the [forum](https://forum.communityhealthtoolkit.org/t/adding-form-field-outside-of-fields-section/2998). This means we need to repeat the same schedule for different forms for which a field name is different. 

**Describe the solution you'd like**
Allow `start_from` to accept multiple date fields and create schedule best on first non-undefined value.

**Comment by 1yuv** [comment]
As a solution to this, I am thinking about CHT to allow array inputs on `start_from` in schedules, then extract the first non-undefined value from the array and create schedule from there.

**Comment by garethbowen** [comment]
Another option we discussed in Slack was having a simple transition that can be configured to copy arbitrary fields from one place to another. This would mean the edd (or whatever) could be copied from `fields.edd` to `edd` and then the same property can be used by `start_from` for both SMS and xform submissions.

**Comment by jkuester** [comment]
I am interested in the idea of a simple transition for making arbitrary changes to docs, but I think I would want to see more clear use-cases where this would be valuable before adding this logic to the CHT.  

Supporting an array for `start_from` seems to be a much more limited feature (and so easier to maintain). Without any further context, this is the direction I would lean.

That being said, I feel like I am still missing something here.  @1yuv, I understand that the app forms can only set `fields.lmp_date` and not just `lmp_date` in the report doc.  Is there a reason why the SMS forms cannot set `fields.lmp_date`?  (I have very little experience with SMS forms, so maybe this is a dumb question....)  I am just hesitant to add more logic to the CHT to address something that could be handled by updating a form config!

**Comment by 1yuv** [comment]
>Is there a reason why the SMS forms cannot set fields.lmp_date

Hi @jkuester , this definitely can not be handled by form config. SMS forms can't set fields themselves as easily as app forms can. For sms forms, most of the fields are set by transition. In case of lmp_date, when user send sms with `lmp_week`, [add_expected_date](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/#add_expected_date) transition is called. This transition [sets lmp_date](https://github.com/medic/cht-core/blob/a0a80a3b2671bba37dd10d9231197b6c03ed1aa3/shared-libs/transitions/src/transitions/registration.js#L186-L187) at the root level. So, an alternative option for sms to set this field inside would be possible only by updating the transition. 

Schedules are very critical in sms workflows and now app forms also coming in to play, supporting this field is important. Also, this is not the first field that CHT allows multiple type of inputs for.

**Comment by garethbowen** [comment]
Merged PRs to cht-core, cht-conf, and cht-docs. Thanks @1yuv !
