### ISSUE TITLE
Link to Contact's Profile from Messages tab

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#8660]
_This originally came from the [forum](https://forum.communityhealthtoolkit.org/t/having-a-link-to-the-client-profile-page-on-the-message-tab/3088)._

When viewing messages on the Messages tab, users will often want to navigate to the message recipient's profile on the Contacts tab. They should be able to do this just by tapping on the message recipient. Currently, users would have to tap on the parent place (in the breadcrumbs) and then scan the list of contacts for that place. If the message recipient has many "peers" (ie contacts at the same level), this becomes very inconvenient and there is no ability to search.  

We should hyperlink from the message recipient to the specific contact's profile on the Contacts tab, just like we do on the Reports tab.

### No hyperlink from the Messages tab
![Screenshot 2023-10-23 at 3 08 43 PM](https://github.com/medic/cht-core/assets/10096985/aece231f-610c-41dc-b791-58c651156af8)

### Already have a hyperlink from the Reports tab
![Screenshot 2023-10-23 at 2 53 27 PM](https://github.com/medic/cht-core/assets/10096985/8508c20f-5491-4605-ba81-6f65d6afdfbc)

**Comment by Nyu10** [comment]
Hi I would like to be assigned this issue

**Comment by latin-panda** [comment]
Hi @Nyu10. Thanks a lot for this!

You can have a look [here](https://github.com/medic/cht-core/blob/71e98ea80ee8424a8b265ded26cbc3b4f806a2f7/webapp/src/ts/modules/reports/reports-content.component.html#L28) how we did it for other pages, where we have added an anchor with `[routerLink]="['/contacts', <<add contact's id>>]"` for navigation.

If you have questions or need help, please let me know.

**Comment by latin-panda** [comment]
Hi @Nyu10, I hope your coding is going well. Is there anything you need support with or any specific topic we can collaborate on for this ticket? Your efforts are valuable, and we're here to help make progress together 🙂

**Comment by Nyu10** [comment]
Hi, I'm currently working on it now, sorry if I didn't reply earlier
