### ISSUE TITLE
Cannot create user for contacts created via Place Api

### ISSUE THREAD

**Issue by freddieptf** [medic/cht-core#8674]
**Describe the bug**
I used the [places api](https://docs.communityhealthtoolkit.org/apps/reference/api/#post-apiv1places) to create a place and contact as shown in the docs. 

```json
{
  "name": "County",
  "type": "contact",
  "contact_type": "a_county",
  "contact": {
    "name": "Paul",
    "phone": "+254883720611",
    "type": "contact",
    "contact_type": "person"
  }
} 
```

That worked but i cannot create a user for the created contact

![Screenshot from 2023-11-01 04-41-02](https://github.com/medic/cht-core/assets/10602047/3ad8959e-4c73-49b9-804d-b1d735532c53)

From the raw contact doc, it seems we don't assign the parent place

```json
{
  "_id": "57abc794c92360562914ff12690118ff",
  "_rev": "1-e40cb19c63fa3b2e161a0aec8ce01fb5",
  "name": "Paul",
  "phone": "+254883720611",
  "type": "contact",
  "contact_type": "person",
  "reported_date": 1698801965100
}
```
The pattern used in the API explains the behavior but it'd be cool if we could assign the place as the person's parent and also include the person id in the response
https://github.com/medic/cht-core/blob/cede018b19239cde2aaeefb30be54db0bfe57f84/shared-libs/contacts/src/places.js#L86-L103

**Expected behavior**
Should be able to create a user for the new contact

**Environment**
- Instance: local instance with moh-ke echis config 
- Browser: Firefox
- Client platform: Linux
- App: webapp, api
- Version: 4.4.1

**Comment by dianabarsan** [comment]
@freddieptf reached out to me, asking if he can work on this. Fred, if this is currently in progress or planning to take on this soon, would you mind assigning this to you, so it doesn't get worked on by another dev. Thanks!

**Comment by freddieptf** [comment]
@dianabarsan yes I'm planning to take this on! I can't assign myself though nor add it to a project

**Comment by dianabarsan** [comment]
Merged to `master`.

**Comment by mrjones-plip** [comment]
@freddieptf - maybe I'm missing why not use the `/api/v2/users` [API](https://docs.communityhealthtoolkit.org/apps/reference/api/#post-apiv2users) which already lets you create a user, contact and place?
