### ISSUE TITLE
Chrome 118 broke e2e testing

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8685]
**Describe the issue**
Chrome 118 has been released and caused our e2e testing to fail, eg: https://github.com/medic/cht-core/actions/runs/6588139242/job/17900197896#step:16:720

**Describe the improvement you'd like**
Fix it.

**Comment by latin-panda** [comment]
😅 I was wondering for a while about the reason the CI was failing with unrelated errors. I'm working on top of 4.4.1

Future patch and feature releases will need to backport this fix.
