### ISSUE TITLE
Fix target UI to match Figma

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#8686]
**Describe:**
The design should match [Figma](https://www.figma.com/file/3wFzMcNEGxV6se1QWftckk/UX-Stages?node-id=2787%3A11166&mode=dev) (original [work](https://github.com/medic/cht-core/issues/8513)), and the documentation should be updated. 

Tasks to complete this work:
- [ ] Should keep margins in responsive design (small phones (360 x 670), regular phones, small desktops (10"), and regular desktops (15"))
- [ ] Should align icons when text next to it is long or short
- [ ] Should have a distinctive background color from the page's background
- [ ] Should have radius in corners. 
- [ ] Should align the small texts (goals)
- [ ] Verify the target page matches the Figma design when having different device sizes. Attach test evidence in the PR. 
- [ ] Update documentation's screens, link CHT Docs PR here.
- [ ] Once merged, backport commit from `master` to `4.5.x`

**Comment by latin-panda** [comment]
@n-orlowski @Benmuiruri 
- The margin around the card and other elements is 10px (top and bottom), 12px (left and right). The cards should keep that margin as they extend horizontally (width)
- The icon should be aligned top in relation to the text.
- The gray color for the card seems to be `#f8f8f8`, we need to add a new variable.
- The border-radius is 8px
- The small text is aligned to the progress-bar, and has a margin: 7px for the top and 18px for the bottom.

**Comment by Benmuiruri** [comment]
The following tasks have been completed by #8687 
- [x] Consistent margins in responsive design (small phones (360 x 670), regular phones, small desktops (10"), and regular desktops (15"))
- [x] Icons aligned when text next to it is long or short
- [x] Updated Target card background color
- [x] Updated Target card border radius to 8px
- [x] Aligned the small texts (goals)
- [x] Verified the target page matches the Figma design when having different device sizes.
- [x] Updated documentation's screens, link [CHT Docs PR](https://github.com/medic/cht-docs/pull/1221).

**Comment by Benmuiruri** [comment]
Closed with #8687
