### ISSUE TITLE
Clean up and organize e2e tests: folders /telemetry, /transitions, /translations, /users

### ISSUE THREAD

**Issue by tatilepizs** [medic/cht-core#8705]
**Describe the issue**
We need to clean and organize the e2e test, this ticket is to do it for folders [/telemetry](https://github.com/medic/cht-core/tree/master/tests/e2e/default/telemetry), [/transitions](https://github.com/medic/cht-core/tree/master/tests/e2e/default/transitions), [/translations](https://github.com/medic/cht-core/tree/master/tests/e2e/default/translations), [/users](https://github.com/medic/cht-core/tree/master/tests/e2e/default/users)

**Describe the improvement you'd like**
The plan for this first phase is just to clean and organize the e2e test that we already have, we don't plan to remove or implement any new scenarios, we just want to try to reduce the flakiness of the tests that we have.

**Describe alternatives you've considered**

**Comment by andrablaj** [comment]
@tatilepizs I changed the status of this ticket to `This Week's Commitments` to have it appear on the [Allies board](https://github.com/orgs/medic/projects/134/views/3).
