### ISSUE TITLE
Make update compose URLs action more reliable

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8707]
**Describe the issue**

The compose URLs in the PR templates have 3 stages...
1. A place holder value before the `Update compose URLs` has run.
2. A link to a URL after the `Update compose URLs` that 404s until the publish is complete.
3. The link that actually works.

The first two are not useful states.

**Describe the improvement you'd like**

Instead of having a separate action for the URLs this would be better as a job that runs after publishing has succeeded, that way step 2 never happens.

I think it would also be better to add a comment to the PR rather than find and replace content in the PR description. This is less fragile because it doesn't rely on finding a specific string, removes the step 1 above, and by using [standard GH commands](https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action) also allows for removing a lot of code.

**Describe alternatives you've considered**

Alternatively we could remove it altogether. With docker helper does anyone use docker compose files manually any more?

**Comment by garethbowen** [comment]
@mrjones-plip I'd love your input on this!

**Comment by mrjones-plip** [comment]
This is a great ticket - thanks for filing it.

I think the KISS approach is to yank as much code as possible and just add a comment that "docker image build complete!".  If it's easy, we can add some build artifact meta data, ideally the image ID so you can compare what you have locally to know if you need to update it.

and, yes, this is because we can and should double down on docker helper 4.x which allows you to easily choose any branch to install.  It's. so. easy. ;)

I'll throw a comment out on Slack in case this is a terrible idea.

**Comment by garethbowen** [comment]
Quick summary of where this is at...

1. There's a blocker with whether this runs on `pull_request` or `branch` build. If it runs on `branch` it's hard to find the pull request to update, but if it runs on `pull_request` then you can't be certain that the publish has completed, because it runs on the `branch`. So 100% reliability is not possible without complex GH requests.
2. It would be relatively easy to change the PR placeholder text to an HTML comment (eg: `<!-- links go here -->`) which means it wouldn't be shown until the build runs. This removes one of the intermediate steps where the bullets are shown without links.
3. It would also be easy to invoke the `replace-staging-urls` script from the main build thus removing a whole build. The benefit of that is it's probably slightly gentler to GH because it doesn't need to spin up a whole extra server. It also cleans up our [Actions](https://github.com/medic/cht-core/actions) page which I use frequently for working out how long the build takes, or how often it fails, etc.
4. If we did 3 then we could easily invoke the script at a later point in the workflow, either after the build step succeeds, or after the e2e tests succeed. Because of 1 this still wouldn't ensure success (if the build doing the publishing has a flaky test and fails before publishing, OR if it's just slower than the build updating the PR). However it would be more likely to work because it's run later, and if eslint fails (for example) it'll fail in both builds.

@mrjones-plip I'd appreciate your thoughts. I'm leaning towards doing 2, 3, and 4 above because while not perfect those solve _most_ of the problem.

**Comment by mrjones-plip** [comment]
Awe - yeah - I love and second pursuing 2, 3 and 4!  Nice thinking about using a comment that we can easily find, but that doesn't show to the end user via `<!-- html comment -->`.

**Comment by garethbowen** [comment]
Merged.
