### ISSUE TITLE
Enhanced Error Messaging for Phone Number Validation: Clarifying Database Duplicates

### ISSUE THREAD

**Issue by hassan254-prog** [medic/cht-core#8725]
**Is your feature request related to a problem? Please describe.**

I have identified a potential improvement concerning phone number validation. Currently, when a user enters an incorrect phone number that does not adhere to the correct format (e.g., +254), an error message is displayed, prompting them to enter the number in the correct format. However, I have observed that if a user enters a phone number already present in the database, they still receive the same error message regarding the format which might be confusing for end users.

**Describe the solution you'd like**

I propose enhancing the error messaging  for phone number validation. Specifically, in the case where a user enters a phone number already present in the database, the error message should provide more context. It would be beneficial for the error message to explicitly indicate that the entered phone number is already registered in the system.

**Describe alternatives you've considered**

No alternative solutions have been considered at this point. The primary focus is on improving the existing error message to offer a clearer and more user-friendly experience.

**Additional context**

I've attached a brief video recording that illustrates the above scenario.

![cht_phone_number_validation](https://github.com/medic/cht-core/assets/85742599/3a02fe9f-d9d3-4861-8a60-3d0b41c2e64a)

**Comment by garethbowen** [comment]
@hassan254-prog Thanks for raising this issue! Is this the same as #7514 ?

**Comment by hassan254-prog** [comment]
@garethbowen Yes, this is the same issue as #7514 . Closing mine as the other discussion has more insight. Thank you.
