### ISSUE TITLE
Upgrade to couchdb 3.3.3

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8743]
**Describe the issue**

Couch [just released 3.3.3](https://blog.couchdb.org/2023/12/05/3-3-3/) which patches a security vulnerability.

**Describe the improvement you'd like**

Update the couchdb image to use the new version. When the details of the vulnerability are disclosed decide whether to backport.

**Describe alternatives you've considered**

None.

**Comment by dianabarsan** [comment]
Merged to master
