### ISSUE TITLE
Users can't login because data loss during creation via API 

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8764]
**Describe the bug**
In the MoH KE deployment, we've seen users that were  created via `/api/v1/users` endpoint via  `cht-conf`.  They're initially created without error, but then are missing in the CouchDB `_users` database:

> At some point, it is claimed that there is a period of downtime after which users are not able to log in.  Upon investigation, app devs find that the `_user` docs are "missing" - people use words like "corrupt", "deleted", etc.  w/e... They are just "missing".
>
> Evidence from CouchDB shows these docs "never existed."  But if these docs are created and then being lost, we have a very serious cht-core bug on our hands or an issue with how eCHIS is hosted, other? 

While the issue may indeed be with "how eCHIS is hosted", I'm filing this bug with an abundance of caution, as they say, to capture details in case we verify it is indeed an issue with CHT Core.

**To Reproduce**
So far this hasn't been reproducible every time, but this is the closest I know of:
1. create a CSV file with users
2. run `cht csv-to-docs` to create the JSON file
3. run `cht upload-docs` to upload the JSON file to the CHT instance

**Expected behavior**
Users get created via `cht-conf` and can login fine.  Their login continues to work over time with out issue.

**Logs**

**Screenshots**

**Environment**
- Instance: siaya.echis.go.ke, echis.health.go.ke, migori-echis.health.go.ke
- Browser: NA
- Client platform: Linux
- App: CHT Core
- Version: 4.2.2

**Additional context**

The [users file mentioned in Slack](https://medic.slack.com/archives/CHYAGKHN2/p1702648685287979?thread_ts=1702472824.421589&cid=CHYAGKHN2) was the source CSV file which was converted to JSON with `cht-conf` and then uploaded to `siaya.echis.go.ke` also with `cht-conf`.

Related URLs/incidents:
* https://github.com/moh-kenya/config-echis-2.0/issues/1650
* https://github.com/moh-kenya/config-echis-2.0/issues/1770
* [slack thread after (unrelated) power outage](https://medic.slack.com/archives/C042D6TPC3Y/p1698130551344359)
* [another slack thread](https://medic.slack.com/archives/C042D6TPC3Y/p1702632855926239?thread_ts=1698130551.344359&cid=C042D6TPC3Y)
* [Lwala slack thread](https://medic.slack.com/archives/CHYAGKHN2/p1699355666521429?thread_ts=1698130720.826469&cid=CHYAGKHN2)

@kennsippell  reported this about the `siaya.echis.go.ke` instance:

> I just did a quick scan. There were 819 users with `user-settings` docs and without `_user` docs as-of today when I investigated this Siaya issue. Of these, 376 of them are listed in the `connected-users` log.  There are only 19 deletion entries in the `_users/_changes` feed.  This definitively confirms dataloss within the CouchDB `_users` database.

**Comment by mrjones-plip** [comment]
giving this a 'Affects: 4.2.2' label as this potentially affects `4.2.2` because the two CHT instances it was seen on were running that version.  

If verified, this will very likely include other 4.x CHT Core versions.

**Comment by jkuester** [comment]
Are the affected instances running single-node or multi-node Couch?  IDK how it would be even possible for the CHT api server to remove records from `_users` without a trace, but perhaps there is some weirdness happening when replicating the created users between nodes....

**Comment by mrjones-plip** [comment]
@jkuester - confirmed that at least one, and likely all, are single node.

That said, the "how eCHIS is hosted" part means that this is a multi-tenant deployment with dozens CHT Core instances all running in docker compose. There is one `nginx` ingress which routes traffic according to hostname. If miss-configured, this could cause issues.

**Comment by mrjones-plip** [comment]
Medic SRE has been looking into the specific deployment's config inside docker compose and currently suspects a miss-configuration there.   See [this ticket](https://github.com/moh-kenya/config-echis-2.0/issues/1650#issue-1992081379) for more details (private repo). 

If it ends up being a miss-config and not a CHT Core issue, we'll close this ticket and remove the `Affects: 4.2.2` label

**Comment by mrjones-plip** [comment]
This has been confirmed to be an issue where there two couch containers running in the docker compose setup.  Upon restart, one of the containers would win and be used, but it wasn't deterministic, so the data would appear to randomly change to the end user.

removing `Bug` and `Affects: 4.2.2` labels and closing!

**Comment by kennsippell** [comment]
After restoring this, the database `_users` database became corrupted after the first write.

```
curl "https://medic:password@siaya.echis.go.ke/_users/_all_docs?include_docs=true&startkey=\"org.\"&endkey=\"p\"" | jq .

{
  "error": "badmatch",
  "reason": "{'EXIT',\n    {bad_return_value,\n        {read_beyond_eof,\n            \"./data/shards/80000000-9fffffff/_users.xxx.couch\"}}}",
  "ref": yyy
}
```
