### ISSUE TITLE
Error in map/reduce function when aggregating telemetry

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8778]
**Describe the bug**

If for any reason a telemetry entry is created with a value that is non-numerical then the next day when the aggregation runs the map/reduce function will throw an error because it can't generate stats on non-numerical values.

**To Reproduce**

1. Go to the reports tab
2. Use the FAB to start a new report
3. Fill in the report
4. Submit the report
5. Wait until the next day
6. Load the app again to trigger telemetry aggregation

**Expected behavior**

1. Invalid values should be logged at record time, not aggregation time, so it's obvious if a dev does the wrong thing.
2. Invalid values that are already in the DB should be skipped so aggregation can complete. Without this any user with an invalid doc from an old version will get stuck and their telemetry will not get synced at all.

**Logs**

```
feedback.service.ts:179 The user's map/reduce function threw an uncaught error.
You can debug this error by doing:
myDatabase.on('error', function (err) { debugger; });
Please double-check your map/reduce function.

BuiltInError {status: 500, name: 'invalid_value', message: 'builtin _sum function requires map values to be numbers or number arrays', error: true, stack: 'invalid_value: builtin _sum function requires map …Task (http://localhost:5988/polyfills.js:824:171)'}error: truemessage: "builtin _sum function requires map values to be numbers or number arrays"name: "invalid_value"status: 500stack: "invalid_value: builtin _sum function requires map values to be numbers or number arrays\n    at createBuiltInError (http://localhost:5988/main.js:155831:10)\n    at sum (http://localhost:5988/main.js:155853:15)\n    at _stats (http://localhost:5988/main.js:156907:12)\n    at tryReduce (http://localhost:5988/main.js:156054:17)\n    at reduceView (http://localhost:5988/main.js:156558:23)\n    at onMapResultsReady (http://localhost:5988/main.js:156618:24)\n    at _ZoneDelegate.invoke (http://localhost:5988/polyfills.js:797:158)\n    at Zone.run (http://localhost:5988/polyfills.js:581:37)\n    at http://localhost:5988/polyfills.js:1673:28\n    at _ZoneDelegate.invokeTask (http://localhost:5988/polyfills.js:824:171)"[[Prototype]]: Error {keys: Array(1), values: Array(1), rereduce: false, fun: ƒ}fun: ƒ (keys, values)keys: Array(1)0: (2) ['gareth', '50b988b3-08bf-4314-9219-bfb85dd43015']length: 1[[Prototype]]: Array(0)rereduce: falsevalues: Array(1)0: nulllength: 1[[Prototype]]: Array(0)[[Prototype]]: Object
options.console.<computed> @ feedback.service.ts:179
guardedConsole @ index.es.js:548
emitError @ index.es.js:8041
tryReduce @ index.es.js:8091
reduceView @ index.es.js:8620
onMapResultsReady @ index.es.js:8685
invoke @ zone.js:372
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
invokeTask @ zone.js:491
invokeTask @ zone.js:1661
globalCallback @ zone.js:1692
globalZoneAwareCallback @ zone.js:1725
```

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp
- Version: master

**Additional context**

The telemetry service has specific code to check for `undefined` so that's safe, but other non-numeric values also need to be handled.

**Comment by dianabarsan** [comment]
I believe this is also true for any builtin map/reduce function provided by CouchDb.

**Comment by garethbowen** [comment]
I've tracked down the cause of the invalid telemetry data to [this commit](https://github.com/medic/cht-core/commit/5723cd3de99fad98450f475ced338ab22b502a2a) and updated the reproduction steps. The change is since the commit the initial telemetry isn't recorded on the reports tab if you creating a new report. This means when you come to save the report it tries to subtract the undefined initial time from the current time and gets NaN which pouchdb cannot aggregate.

**Comment by garethbowen** [comment]
Merged.
