### ISSUE TITLE
`api/v1/users-doc-count` doesn't work as expected

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#8796]
**Describe the bug**
The api endpoint `/api/v1/users-doc-count` should return the list of users with user name, id and document count. However, the api returns an empty array even if there are multiple users. 

**To Reproduce**
1. Go to API endpoint `/api/v1/users-doc-count`
2. View the output, which doesn't list users.

```json

{
  "limit": 10000,
  "users": [
    
  ]
}
```

**Expected behavior**
The output should be something like this:

```json
{
  "limit": 10000,
  "users": [
    {
      "_id": "replication-count-118",
      "_rev": "1-4e66a75a2ecafecb3b3731e3fd2f1cd6",
      "user": "118",
      "date": 1664341970077,
      "count": 190
    }
]
}
```

**Environment**
- Instance: Any
- Browser: Any
- Client platform: Any
- App: api
- Version: 4.5.0

**Additional context**
This is seen on 4.5.0, I also checked some 4.3.0 instances and saw same issue there.

**Comment by dianabarsan** [comment]
Merged to `master`
