### ISSUE TITLE
Bulk password change script causing `503` errors?

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8862]
**Describe the issue**
@billwambua reports the `bulk-password-update-export.js` [script](https://github.com/medic/cht-core/blob/master/scripts/bulk-password-update-export.js) added in #8843:

> I've tried using this script. There seems to be an issue. Every time I use the script, the instance ends up getting 503 bad gateway errors. It has happened twice now.
>
> The first time I'm not sure whether it was due to the script because I hadn't checked the instances before but the second time the instance was definitely working before I ran the script.
>
> Could it be the scripts doing or do you think coincidence?

**Describe the improvement you'd like**
Using the script doesn't cause errors

**Describe alternatives you've considered**
Not use the script

**Comment by mrjones-plip** [comment]
@billwambua - can  you add details on how to reproduce?
* how many users are you changing the password on?
* what version of CHT are you on?
* is this a local dev instance or a Medic hosted instance or other?

**Comment by mrjones-plip** [comment]
Testing on 256 changes (same 5 users many times in one file) hasn't shown the issue on either [default conf](https://github.com/medic/cht-core/tree/master/config/default/) or [echis ke conf](https://github.com/moh-kenya/config-echis-2.0/).  I'm on CHT `4.4.1` but I'll try on `4.5.2` now.

```
 ****** WARNING ******
Continuing will log 256 users out of the CHT until you provide them with their updated password.

Do you want to continue? [y/N]
```

**Comment by billwambua** [comment]
@mrjones-plip I'm using it on https://bomet.echis.go.ke. 

I can't tell which CHT version it is on right now because due to the 502 Bad Gateway errors, I can't login.

I was only trying to reset the password for 2 users as a test.  I've shared the 2 usernames via DM with @mrjones-plip 

I have not been able to recover.

**Comment by mrjones-plip** [comment]
@billwambua - thanks for the details!

I was able to reproduce the error when I accidentally changed the password for the admin user that couch was using, `medic` in my case.

Do you know if this was the case you?  You can check the contents of your `user-password-change.txt` file.

**Comment by billwambua** [comment]
@mrjones-plip those 2 usernames I've shared via Slack DM are the only usernames in `user-password-change.txt`

**Comment by mrjones-plip** [comment]
I was able to get a `503` when I accidentally changed the password for my main CHT user which API uses with CouchDB (`medic` is this user for me).  This looked like this in the script:

```
SUCCESS 123456 YBleGr-t1T633                                                                                                                                                                       
SUCCESS 123456 JbVSma-Gg8488                                                                                                                                                                       
SUCCESS azed QmsBDny-13Y01                                                                                                                                                                         
SUCCESS azed PkYCxxw-6007C                                                                                                                                                                         
SUCCESS fet c-KDDp3pa506S                                                                                                                                                                          
ERROR medic 401 - {"code":401,"error":"unauthorized"}                                                                                                                                                              
ERROR sub 401 - {"code":401,"error":"unauthorized"}                                                                                                                                                
ERROR test 401 - {"code":401,"error":"unauthorized"}        
ERROR sub 401 - {"code":401,"error":"unauthorized"}
ERROR test 500 - {"code":500,"error":"Server error"}
ERROR zed 500 - {"code":500,"error":"Server error"}
ERROR azed 500 - {"code":500,"error":"Server error"}
```

I recovered by resetting my `medic` user password. For my my couchdb container is called `test_couchdb_1`: 
1. getting shell on my couchdb container: `docker exec -it test_couchdb_1 bash`
2. changing the value of the `medic` user's hash to a string: `medic = password`
3. exiting out and then restarting couch: `docker restart test_couchdb_1`

However!  The two user names that @billwambua shared are not the admin user - so this appears to not be the problem with that instance.  

I'll continue digging! :thinking:

**Comment by mrjones-plip** [comment]
I was able to get a `503` when I accidentally changed the password for my main CHT user which API uses with CouchDB (`medic` is this user for me).  This looked like this in the script:

```
SUCCESS 123456 YBleGr-t1T633                                                                                                                                                                       
SUCCESS 123456 JbVSma-Gg8488                                                                                                                                                                       
SUCCESS azed QmsBDny-13Y01                                                                                                                                                                         
SUCCESS azed PkYCxxw-6007C                                                                                                                                                                         
SUCCESS fet c-KDDp3pa506S                                                                                                                                                                          
ERROR medic 401 - {"code":401,"error":"unauthorized"}                                                                                                                                                              
ERROR sub 401 - {"code":401,"error":"unauthorized"}                                                                                                                                                
ERROR test 401 - {"code":401,"error":"unauthorized"}        
ERROR sub 401 - {"code":401,"error":"unauthorized"}
ERROR test 500 - {"code":500,"error":"Server error"}
ERROR zed 500 - {"code":500,"error":"Server error"}
ERROR azed 500 - {"code":500,"error":"Server error"}
```

I recovered by resetting my `medic` user password. For my my couchdb container is called `test_couchdb_1`: 
1. getting shell on my couchdb container: `docker exec -it test_couchdb_1 bash`
2. changing the value of the `medic` user's hash to a string: `medic = password`
3. exiting out and then restarting couch: `docker restart test_couchdb_1`

However!  The two user names that @billwambua shared are not the admin user - so this appears to not be the problem with that instance.  

I'll continue digging! :thinking:

**Comment by mrjones-plip** [comment]
@billwambua  - Any updates on your side? I've been unable to reproduce any errors aside from changing the password for the `medic` or `admin` user that API uses to talk to couch.

@garethbowen - any thoughts based on the code?  My thinking is that  we only do one active `POST` per user [on line 116](https://github.com/medic/cht-core/blob/41d28031e0e2e77b51997964b7109a2544a19fb7/scripts/bulk-password-update-export.js#L116) - I'm struggling to see how this could bring down an entire instance short of the admin user change I mentioned above.

**Comment by garethbowen** [comment]
I couldn't figure it out from your code either.

It might be worth updating your script to block updating admin passwords. I would expect this change to protect you this: https://github.com/medic/cht-core/issues/8096 . Did your CHT instance have that code? If so we need to figure out how you managed to change an admin password.

However given @billwambua says he didn't change the admin password this isn't the issue. We need to see the logs from the server that's 503ing. My guess is it's unrelated.

**Comment by mrjones-plip** [comment]
@billwambua  - ah - gotcha ! Thanks for the update. I'll dig into the script a bit more and see if there's a race condition in there I'm not seeing at first (and second and third ;) look.

@garethbowen - yeah - makes sense to not allow password changes for `medic` and `admin` users.  I'll open a PR against this ticket!

**Comment by garethbowen** [comment]
@mrjones-plip I think the API should already block this with an error message. If you're not seeing this on `4.6.x` or `master` I'll have a bug to fix...

**Comment by mrjones-plip** [comment]
Ah - I'll let you know about `master` @ ~`4.6.x`,  I'll still do the change as this script will work against older versions.

**Comment by mrjones-plip** [comment]
@garethbowen  - excellent work!

```
 ****** WARNING ******
Continuing will log 7 users out of the CHT until you provide them with their updated password.

Do you want to continue? [y/N]
y
(node:78144) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
SUCCESS admin BUThxax-6E043
ERROR medic 400 - {"code":400,"error":"Admin passwords must be changed manually in the database"}
SUCCESS test VWr-Fc5ny412H
ERROR foobatr 404 - {"code":404,"error":"Failed to find user."}
```

**Comment by mrjones-plip** [comment]
Closing this issue as no evidence was found that the password change caused an error.  Please re-open if new evidence to contrary surfaces!
