### ISSUE TITLE
Research available alternatives to run our mobile test suite on a device farm

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#8873]

**Comment by ralfudx** [comment]
After a careful investigation of the phone options available for real devices) on the [AWS device farm](https://aws.amazon.com/device-farm/) and also [browserStack](https://www.browserstack.com/list-of-browsers-and-platforms/js_testing), we noticed that most of the devices listed in our [devices-used-by-projects](https://docs.google.com/spreadsheets/d/13JbbbqKRuGOoxpHR1dHDYfrXR-D57CEjhGRWbpJ1tGs/edit#gid=0) list were unavailable on their platform - therefore, these device farm alternatives do not provide the device capabilities for us to simulate the right measure of testing for the different configs
We finally resulted in using real physical devices for testing - Safaricom Neon Ray Ultra S

**Comment by andrablaj** [comment]
@ralfudx this issue was moved to `Done`. Can we close it?
