### ISSUE TITLE
Builds are failing because Webdriver cannot download Chromedriver

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8881]
**Describe the issue**
Example build: 
https://github.com/medic/cht-core/actions/runs/7934590909/job/21666328737

```
Checking API
API is up
API startup: User contact doc setup
Error: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip
```
It looks like google has changed the domain where they host chromedriver downloadables.
This is already tracked in the webdriverio repo: https://github.com/webdriverio/webdriverio/issues/12251
 
**Describe the improvement you'd like**
Fix the build by upgrading webdriverio after a fix is published. 

**Describe alternatives you've considered**
Find a workaround, like downloading older browser versions that are still available on the old domain.

**Comment by dianabarsan** [comment]
WDIO published a fix: https://github.com/webdriverio/webdriverio/releases/tag/v8.32.2

Upgrading to the latest version is proving non-trivial unfortunately.

**Comment by garethbowen** [comment]
@dianabarsan If it's helpful, I went down the upgrade path and solved some of the problems in this PR: https://github.com/medic/cht-core/pull/8817

The commit messages are rubbish but there's one for "upgrade wdio" and most of what's below that was fixing wdio issues.

**Comment by dianabarsan** [comment]
Thanks :)

The one error that I'm struggling with is:
```
[0-0] TypeError: browser.cdp is not a function
[0-0]     at Object.saveBrowserLogs (/home/diana/projects/cht-core-3/tests/utils/browser-logs.js:8:19)
```

`cdp` is a custom command added by the `devtools` service and we use it to get browser logs.

**Comment by garethbowen** [comment]
Yeah that's exactly where I got stuck too. Sorry I couldn't find any info for it :/

**Comment by dianabarsan** [comment]
I just made some progress. It seems that the service add the commands in the `before` hook, and we also call the commands in the `before` hook. there seems to be some race condition, where wdio doesn't wait until the service is set up before firing the custom `before` script.

**Comment by dianabarsan** [comment]
I've tracked this down and submitted a bug report in webdriverIO: https://github.com/webdriverio/webdriverio/issues/12321

**Comment by garethbowen** [comment]
Merged. Thanks @dianabarsan !
