### ISSUE TITLE
Add Swahili Translations

### ISSUE THREAD

**Issue by Benmuiruri** [medic/cht-core#8884]
**What feature do you want to improve?**
Some translations key are missing Swahili entries

**Describe the improvement you'd like**
Add Swahili entries to translation keys.

**Comment by Benmuiruri** [comment]
Swahili translations for entries 1-200 added by #8890.
Swahili translations for entries 200 - 1450  (work in progress).

**Comment by garethbowen** [comment]
Moved to 4.8.0 so as not to hold up the release.

**Comment by latin-panda** [comment]
This is complete
