### ISSUE TITLE
External contributor builds fail as unable to find docker images

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#8902]
**Describe the issue**

External contributed builds are failing ([example](https://github.com/medic/cht-core/actions/runs/7980265526/job/21808773919#step:7:23)).

```
Starting download for cht-images
Error: Unable to find any artifacts for the associated workflow
```

**Comment by garethbowen** [comment]
I've fixed most of this, but looking at the [upgrade test failure](https://github.com/medic/cht-core/actions/runs/7990756484/job/21821517627#step:8:1015) I can't understand how/if it ever worked for external contributors, because it doesn't extract the cht-images artifact the way that the e2e test suite does.

@dianabarsan Do you recall if this works? The options I've thought of are to skip the upgrade test for external contributors, or update the upgrade test to install the images from the artifact.

**Comment by dianabarsan** [comment]
I think this never worked. And given this tests the vanilla upgrade path, I think the changes required to make this work for images that are not uploaded would be extensive. It would make more sense to make an entirely different upgrade path for external contributors that doesn't use the upgrade service / admin upgrade button at all.

**Comment by garethbowen** [comment]
Merged

**Comment by garethbowen** [comment]
After merging external contributors are hitting an error further down the build pipeline: https://github.com/medic/cht-core/actions/runs/8001406685/job/21865464236?pr=8900

```
Run geekyeggo/delete-artifact@v4
Error: HttpError: Resource not accessible by integration
```

I think what's happening is with the v4 version you need certain credentials to delete artifacts. I suggest we just don't bother deleting. I feel bad because it's 500MB of artifact we no longer need but hopefully GH cleans it up aggressively. If we get told off we can investigate other options...

**Comment by garethbowen** [comment]
External build completed successfully.
