### ISSUE TITLE
Add Nepali Translations to L200

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#8938]
**What feature do you want to improve?**
Some translations key are missing Nepali entries

**Describe the improvement you'd like**
Add Nepali entries to translation keys.

**Comment by latin-panda** [comment]
@1yuv, in case it helps, @Benmuiruri, @andrablaj, and I have been basing the translation on the English text and submitting the work in chunks of 200 or 300 lines, then assigning another speaker of the same language to review them. 
Maybe @nsitaula can help you review your PRs?
