### ISSUE TITLE
Select question grid display in forms broken

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8939]
**Describe the bug**
In Enekto forms, you can create a [grid of select questions](https://docs.getodk.org/form-question-types/#grid-of-selects-on-the-same-screen) that all have the same choices so that the choice labels are only displayed once.  

Unfortunately. the CSS to hide the subsequent choice labels in the matrix seems to have been broken with these changes: https://github.com/medic/cht-core/pull/8672

**To Reproduce**

Create a form with either of the following select matrix patterns (note that Enekto supports both the `table-list` and the `list-nolabel` appearance patterns, but only the `list-nolabel` pattern is included in the ODK docs):

type | name | label::en | appearance
-- | -- | -- | --
begin_group | table_list_test | Table | field-list
select_one yes_no | table_list_test_label | Table | label
select_one yes_no | table_list_1 | Q1 | list-nolabel
select_one yes_no | table_list_2 | Question 2 | list-nolabel
end group |   |   |  
begin group | table_list_test2 | Table (alternative method) | table-list
select_one yes_no | table_list_3 | Q1 |  
select_one yes_no | table_list_4 | Question 2 |  
end_group |   |   |  

Open the form on a CHT instance `>=4.5.0` and see that the labels for the matrix choices are not hidden as expected.

**Screenshots**
This is the expected behavior:
![image](https://github.com/medic/cht-core/assets/8441903/efa68a9f-8ed1-4e66-88fa-c5ce8e083e19)

This is how it looks now:
![image](https://github.com/medic/cht-core/assets/8441903/950b9e2d-8903-43a5-951d-43f05d69a83c)

**Additional context**
Originally reported [on the forum](https://forum.communityhealthtoolkit.org/t/changes-in-table-list/3384)

**Comment by latin-panda** [comment]
I'm just waiting for @ralfudx's review. Moving this ticket to next week.
