### ISSUE TITLE
Admin app shows error after successful upgrade

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8940]
**Describe the bug**

When using the Admin app to upgrade a CHT instance to the latest tagged version (e.g. `4.6.0-beta.3`), the installation will complete successfully, but the UI will still display the installation error card.  

**To Reproduce**

Deploy a CHT instance that can be upgraded via the Admin app (I used EKS)

In the Admin app on the Upgrades tab, select "Install" for the `4.6.0-beta.3` tag.  Wait for the install to complete and see the error message (even though the installation succeeded).  

![image](https://github.com/medic/cht-core/assets/8441903/96547788-fbd9-4881-9546-bfb1989a6a03)

Alternatively, instead of selecting "Install", select "Stage".  Then, once the installation is staged, click "Install" and see the error (note that, for me, the page automatically updates after ~30sec to clear this screen and take me back to the normal Upgrades tab.  I never see the "Deployment Complete" card, but at least the error goes away....):

![image](https://github.com/medic/cht-core/assets/8441903/e4859223-25b7-43c3-82a7-96c28ca6d25c)

**Expected behavior**

Either way, when the installation succeeds, I expect to see "Deployment complete.":

![image](https://github.com/medic/cht-core/assets/8441903/969fa609-454e-4a67-8b19-d1db4883f160)

**Logs**

There are lots of errors in the console log, but I think most of them are normal while polling for the updated api server to come back online.  However, as the error card appears at the end of the upgrade, I do see: `main.js:1 Error triggering update instance.upgrade.error.deploy`

**Additional context**

This behavior only seems to be happening for the `4.6.0` beta tags.   If I start from an older CHT version,  such as `4.3.0`, and then try upgrading to `4.5.2-beta.1`, I do not see any problems.  Then if I upgrade to `4.6.0-beta.3`, I see the error card being displayed.

**Comment by jkuester** [comment]
@garethbowen now that we have resolved https://github.com/medic/cht-core/issues/8868 and there are not any session issues after upgrading, we have still been able to re-create these error display issues.  My main question at this point is if you think this should block the `4.6` release?  [Similar behavior](https://github.com/medic/cht-core/issues/8868#issuecomment-1942449890) has been seen before on older code, but I was not able to reproduce this myself.  As far as I can reproduce, this problem behavior only happens for the 4.6.0 beta tags.

**Comment by garethbowen** [comment]
@jkuester I'm sure I've seen this before 4.6.x. either way I don't think it's a blocker.

**Comment by dianabarsan** [comment]
Merged to `master`
