### ISSUE TITLE
Outbound push cron config error

### ISSUE THREAD

**Issue by njuguna-n** [medic/cht-core#8947]
Job commented on the [forum](https://forum.communityhealthtoolkit.org/t/configure-cronjob-or-batch-processing-for-cht-outbound/2641/31?u=njuguna) that outbound push tasks are failing with `Unable to push ***** for ped_benchmark_outbound because this outbound config no longer exists, clearing task`.

The steps for reproduction are:

1. Configure outbound as seen below:

![Image](https://github.com/medic/cht-core/assets/141340177/741ac868-edcc-40f7-a2bf-79b875e77e93)

2. Create records and trigger outbound at minute 11 all the way to 20. You will notice that your records will be saved and not pushed, see the above logs. An outbound task will be generated
3. Within the same timeframe you will see a message `Unable to push ***** for ped_benchmark_outbound because this outbound config no longer exists, clearing task`

**Comment by njuguna-n** [comment]
As mentioned in my [comment](https://forum.communityhealthtoolkit.org/t/configure-cronjob-or-batch-processing-for-cht-outbound/2641/28?u=njuguna) the only way I have been able to reproduce this error is by changing the configuration before the task are processed. Even with the reproduction steps above, the tasks are processed as expected. I am still experimenting with the timings and config to see if I can consistently reproduce the error.

**Comment by dianabarsan** [comment]
@njuguna-n 
Have you tried adding two configs with different cron settings - so that they would never run at the same time, and making it so one config gets its turn while the other does not, and then check that the other config jobs are still present? This is the only idea I have right now.

**Comment by njuguna-n** [comment]
Thanks for that suggestion @dianabarsan. I was able to reproduce the error and now working on fixing the bug.
<img width="1112" alt="image" src="https://github.com/medic/cht-core/assets/141340177/ddf54323-3190-4d7a-8f73-1277154b5a88">

**Comment by andrablaj** [comment]
@njuguna-n I added this issue under 4.12 milestone. Please change it to 4.11 if you think (and it's possible) this could be released earlier.
cc @witash
