### ISSUE TITLE
Support getting the difference between two dates in various time formats

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#8971]
Retroactively logging this issue for the functionality already in PR: https://github.com/medic/cht-core/pull/8949

**Is your feature request related to a problem? Please describe.**
See https://github.com/medic/cht-core/issues/5468, but basically doing logic around dates in xforms can be tricky and error prone since it is mostly manual calculations. It would be much nicer to have proper XPath functions that could do the generic heavy lifting around date calculations.

**Describe the solution you'd like**
Contained in the PR are 4 new functions that add functionality similar to the existing [`difference-in-months` function](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#difference-in-months).

- `cht:difference-in-days`
- `cht:difference-in-weeks`
- `cht:difference-in-months`
- `cht:difference-in-years`
- ~~`days-remaining-in-week`~~

Most of these are pretty self-explanatory, but @ChinHairSaintClair, I was hoping you could provide some more context here for `days-remaining-in-week`.  Looking at the code, it seems to calculate the value by `totalDiffDays % 7;`.  This seems like a pretty simple calculation that could be done in the form via just getting the modulo of the `difference-in-days` value.  Am I missing something here?  (Have not actually tried calculating modulo in an xform....)  Depending on the circumstances here and how common the use-cases would be for this functionality, we might not need this function.

The rest of these functions seem super valuable and hard to manually code within the form logic (because of all the weird date edge cases).  

**Describe alternatives you've considered**
One alternative would be to try and up-stream these functions into the ODK spec (and then into the Enketo code-base). The functionality here is genericish since it just deals with date values, but maybe is not very useful in typical data-collection contexts...  One point of context is that the `difference-in-months` function was actually [removed from the Enekto code base](https://github.com/enketo/enketo/issues/911). I imagine any functions that are actually accepted into the spec would be welcome in Enekto.  @garethbowen you probably have more context here regarding the history of trying to put this kind of thing into the xform spec.  What do you think?

My current thinking is that regardless we should move forwards with adding these functions to the CHT. It will not be hard to migrate the code to Enketo later if needed.

**Additional context**
Originally discussed in [this forum thread](https://forum.communityhealthtoolkit.org/t/mitigate-duplicate-data-capture/3313/6?u=anro).

**Comment by jkuester** [comment]
@ChinHairSaintClair, one minor design consideration (which I will also note in a PR comment) is that we have decided to start prefixing all of our custom CHT XPath functions with `cht:` to try and help make it more clear which functionality is specific to the CHT (and which is part of the generic ODK spec). E.g the [cht:extension-lib function](https://docs.communityhealthtoolkit.org/apps/reference/forms/app/#chtextension-lib).  So, all the new functions would have names like `cht:difference-in-days`.  Additionally, it also probably makes sense to be consistent and add an additional `cht:difference-in-months` function so we can deprecate `difference-in-months` .

**Comment by ChinHairSaintClair** [comment]
Hi @jkuester, 
You raise a good point regarding the `days-remaining-in-week`, and after testing, it can be removed from the PR and simply be a modulo calculation in the form. 
As noted in the [xforms-spec](https://getodk.github.io/xforms-spec/#xpath-operators), this can be done by using the `mod` operator.
In our case, and as noted above, it would simply be `${diff_in_days} mod 7` in the calculation column.

The results can be seen here:
![image](https://github.com/medic/cht-core/assets/41445931/8818e50c-8119-4736-b971-cac288558af4)

I believe this was implemented as is due to time constraints and uncertainty about usage frequency. It seems a 'damp code' approach might have been better in this circumstance, given the numerous unknowns at the time.
Thank you for highlighting this. Our forms are scheduled for some maintenance.
