### ISSUE TITLE
Run default core and enketo e2e tests on minimum browser requirements

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#8973]
**What feature do you want to improve?**
We should fail loudly if the minimum browser requirement is not met.
This issue is meant to divide the work into smaller tasks. Parent issue https://github.com/medic/cht-core/issues/8159

**Describe the improvement you'd like**
Run **default core** and **enketo** e2e test on minimum browser requirements (chrome 90) using Chromedriver

**Describe alternatives you've considered**

**Additional context**

**Comment by lorerod** [comment]
@garethbowen, we can make it required; how do I do that?

**Comment by garethbowen** [comment]
@lorerod It's an admin only change - I've just made it.
