### ISSUE TITLE
Improve Apdex score of contact_list

### ISSUE THREAD

**Issue by Benmuiruri** [medic/cht-core#9006]
**Describe the performance issue**
[Care Teams KR](https://github.com/medic/care-teams/issues/22)
[Initial research done](https://github.com/medic/care-teams/issues/91#issuecomment-2049084781)

In the first cycle of performance optimisation I did not find any glaring performance bottlenecks. In this issue I suggest two refactors that might improve performance or at least better maintainability that could lead to potentially improved performance. 

### contactsComponent
1. In [contacts-component.ts](https://github.com/medic/cht-core/blob/master/webapp/src/ts/modules/contacts/contacts.component.ts), the `ngOnInit` method mixes synchronous and asynchronous logic ([code](https://github.com/medic/cht-core/blob/c4c3114ed8e17f49a78e1f803a643792b71f2c8e/webapp/src/ts/modules/contacts/contacts.component.ts#L124)) which can be refactored to use `async - await`
2. The initialization of the contacts Component can also be wrapped in a `try - catch` block to allow for centralized error handling instead of error handling in each promise. 
3. The subscription management ([code](https://github.com/medic/cht-core/blob/c4c3114ed8e17f49a78e1f803a643792b71f2c8e/webapp/src/ts/modules/contacts/contacts.component.ts#L92)) can also be refactored into a separate method. This wont particularly lead to a performance gain but it improves the separation of concerns. 

### searchService
In looking for ways to optimize the `contact_list:query` I reviewed the search library and there could be possible optimization by avoiding redundancy of [responses.map](https://github.com/medic/cht-core/blob/c4c3114ed8e17f49a78e1f803a643792b71f2c8e/shared-libs/search/src/search.js#L46C30-L46C43)

**Comment by garethbowen** [comment]
Moved to 4.8.0 so as not to hold up the release.
