### ISSUE TITLE
Reduce loops when processing tasks and reports 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9019]
**Describe the performance issue**
[Research 1](https://github.com/medic/care-teams/issues/74#issuecomment-2039481418)
[Research 2](https://github.com/medic/care-teams/issues/99#issuecomment-2060711839)

- Add all the tasks' [emissions fields in the rule engine](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/services/rules-engine.service.ts#L293) to avoid going through the list of data twice. [Tasks list adds](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/modules/tasks/tasks.component.ts#L129): date, overdue and owner. While [contact detail adds](https://github.com/medic/cht-core/blob/679b7051aa15488b6c9f3e872145a3b0d433aba8/webapp/src/ts/services/tasks-for-contact.service.ts#L66) overdue, the calculation is the same.

- Pass the selected contact ID and the descendants' IDs to the service that loads the breakdown of tasks to avoid going through the list of data twice.

- There is a micro improvement [to avoid looping twice a list of tasks](https://github.com/medic/cht-core/blob/04491c9f93c4689c4207928a339347e863c1d52f/webapp/src/ts/reducers/contacts.ts#L119), but it is likely not noticeable by the user.

**Comment by garethbowen** [comment]
Moved to 4.8.0 so as not to hold up the release.
