### ISSUE TITLE
Remove server check for node version

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9023]
**Describe the issue**

The server checks code checks a few things to make sure the server is correctly set up so it can fail early with a clear error message if it's not. One of the things it checks is the node version, but because we publish docker images with a node dependency it should never be wrong in prod.

**Describe the improvement you'd like**

Remove the node check. Keep the code that logs the version because that's useful. Consider _adding_ a check for CouchDB version which is more likely to get out of sync because the CouchDB version is defined in a separate docker image.

**Describe alternatives you've considered**

Keep it as a sanity check, and to protect devs who are running outside of docker from silly mistakes.
Due to an oversight on my part it didn't get updated when we bumped to Node 20 so update it and move on.

**Comment by garethbowen** [comment]
@dianabarsan I'm on the fence about the right solution so would appreciate your input... do you think we should

1. Remove the node version hard fail?
2. Add a CouchDB version hard fail?

**Comment by dianabarsan** [comment]
I agree completely. I think the CouchDb version is important, and the Node version not at all.
