### ISSUE TITLE
Add pagination when loading All reports associated with a contact in contact detail page

### ISSUE THREAD

**Issue by Benmuiruri** [medic/cht-core#9025]
**What feature do you want to improve?**

We recently fixed a [bug](https://github.com/medic/cht-core/issues/8815) where only the last 50 reports for contact were provided to contact-summary calculation. The fix to use max fetched reports (500 reports) for contact-summary calculation was [merged](https://github.com/medic/cht-core/pull/8984). 

However, currently loading reports in the contact detail page does not have any pagination or lazy loading implementation. Since there is a possibility that a contact might have 500 reports, the app might freeze as it loads all 500 Reports at once. To mitigate that, we set the max number of reports you can view in the contact detail as 50.

That means when you click the `View all` tab in the Reports section you see only 50 instead of literally `All Reports` associated with that contact.
![Screenshot 2024-04-20 at 14 24 17](https://github.com/medic/cht-core/assets/2597305/e2046e4f-bbe0-4cd4-a78a-180a62586898)

**Describe the improvement you'd like**

Implement lazy loading / pagination similar to how its implemented in the Reports Tab to load reports in batches but ensure someone can view `All Reports`associated with a user.

**Comment by michaelkohn** [comment]
Closing this until we hear that this is an issue for users.
