### ISSUE TITLE
Add Nepali Translations 201 - All

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9028]
**What feature do you want to improve?**
Missing and misleading nepali translations

**Describe the improvement you'd like**
Add Nepali entries to translation keys, correct incorrect translations up to line 800.

**Comment by garethbowen** [comment]
@1yuv How are you getting on with this work? I'm really keen to get it to 100% so we can [turn on linting](https://github.com/medic/cht-core/issues/9234) to keep it at 100% for future releases.

**Comment by 1yuv** [comment]
Hi @garethbowen , I am sorry this got deprioritized, @binokaryg and I were talking about wrapping this up soon. We'll work on it.
