### ISSUE TITLE
Upgrade CI workflow fails with image rate limit

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9042]
**Describe the issue**

The Upgrade GitHub workflow gets the upgrade service to run an upgrade from a recent final version to the PR branch to ensure the upgrading process isn't broken. In the last 24 hours this has failed twice for exceeding a rate limit when pulling images, presumably from docker hub.

I'm fairly sure this only affects CI not our production instances which should use our AWS image registry, but this should be confirmed, but for now I'm treating this as a flaky test, not a bug.

Builds that have failed:
- https://github.com/medic/cht-core/actions/runs/8802148266/job/24159595878
- https://github.com/medic/cht-core/actions/runs/8802148266/job/24186345133

The two builds have failed in a slightly different place, but this is an example:

```
api Pulling 
sentinel Pulling 
couchdb Pulling 
haproxy Pulling 
healthcheck Pulling 
nginx Pulling 
haproxy Error 
api Error 
couchdb Error 
nginx Error 
sentinel Error 
healthcheck Error 
Error response from daemon: toomanyrequests: Rate exceeded

    at ChildProcess.<anonymous> (/app/src/docker-compose-cli.js:34:25)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

**Describe the improvement you'd like**

Logging in to docker hub would solve this issue, but because the error appears to be coming from inside the upgrade service I presume the credentials would need to be passed in to the service rather than just logging in in the CI worker like we do elsewhere.
Alternatively we could switch to using a different registry for CI.

**Describe alternatives you've considered**

Add retries to the test, with a sufficient timeout to give docker a break between pulls.

**Comment by dianabarsan** [comment]
Oh, interesting. 
These images aren't hosted on dockerhub, they're hosted in AWS ECR.

**Comment by garethbowen** [comment]
Oh yeah you're right. The upgrade service gets the published docker-compose file which references images hosted in AWS, NOT docker hub.

I suspect the login code you linked is not helpful because that's running in the builder, not the upgrade service.

If this is the case then this might end up as a production issue if servers are rate limited when trying to update an instance.

**Comment by garethbowen** [comment]
The default quotas _look_ ok to me, but may be I'm missing something: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service-quotas.html

**Comment by dianabarsan** [comment]
As far as I remember, we have a retry in the upgrade service for rate exceeded errors: https://github.com/medic/cht-upgrade-service/blob/main/src/docker-compose-cli.js#L7
I wonder what we're missing here.

**Comment by garethbowen** [comment]
Ahh that's it! It's not a bug in the upgrade service it's a bug in how the test installs the upgrade service. This line doesn't have a retry on rate exceeded:

https://github.com/medic/cht-core/blob/2e1a05ff17c9e15c8702790ff949c7028c36f343/tests/e2e/upgrade/wdio.conf.js#L98

I think if we add that retry in more or less the same way as we have in the upgrade service you linked then we'll stabalise the tests.

**Comment by dianabarsan** [comment]
You hit the mark! But in a different repo: 

https://github.com/medic/cht-upgrade-service/blob/main/src/docker-compose-cli.js#L52

This is how we start containers, with an `up`, and we have the retry on the `pull`, which we only run when we upgrade, and not when we install. 
I'll open an issue in the upgrade service and fix it there.

**Comment by garethbowen** [comment]
Ahh maybe. There is nothing in the log file about that, but probably because that service doesn't log what it's about to do (just the result). Let's log the command that's being run as part of your change, like the test does here:

https://github.com/medic/cht-core/blob/2e1a05ff17c9e15c8702790ff949c7028c36f343/tests/e2e/upgrade/wdio.conf.js#L73

**Comment by garethbowen** [comment]
Fixed here: https://github.com/medic/cht-upgrade-service/issues/40
