### ISSUE TITLE
Add @medic/environment shared library

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9081]
**Describe the issue**
We have some duplicate code accessing `process.env.COUCH_URL`: 
https://github.com/search?q=repo%3Amedic%2Fcht-core+COUCH_URL+language%3AJavaScript+NOT+path%3A%2F%5Escripts%5C%2F%2F&type=code&l=JavaScript

**Describe the improvement you'd like**
Add a shared-library @medic/environment that processes environment variables and exports parsed / generic data to be reused. 

**Describe alternatives you've considered**
None.

**Comment by mrjones-plip** [comment]
Moving to 4.9 to unblock 4.8 release
