### ISSUE TITLE
add tests/helm/values.yaml to .gitignore

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#9085]
**Describe the issue**
when test are run locally (eg `npm run ci-integration-sentinel-k3d`) a YAML file is created locally every time: `tests/helm/values.yaml`.  However, `.gitignore` doesn't have this file listed, so it might get accidentally added to the repository.  As it's created every time, it shouldn't be added.

**Describe the improvement you'd like**
add to .gitignore

**Describe alternatives you've considered**
manually ignore it

**Comment by dianabarsan** [comment]
Should be fixed in https://github.com/medic/cht-core/commit/85b539634ff2810f4e04b0a2513bb67ae3cee265
Thanks @mrjones-plip !
