### ISSUE TITLE
K3D suites are failing for external contributors

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9097]
**Describe the issue**
All k3d builds are failing for external contributors, because they fail to import testing images

Example:
https://github.com/medic/cht-core/actions/runs/8973920709/job/24652846777?pr=9027

**Describe the improvement you'd like**
Add mechanism to import downloaded docker images to k3d.

**Comment by garethbowen** [comment]
Example log...

```
Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-dependabot-npm-and-yarn-webapp-ngx-bootstrap-18.0.2.10381871022 not found: manifest unknown: manifest unknown
```

**Comment by garethbowen** [comment]
Trying out a fix: https://github.com/medic/cht-core/tree/9097-load-docker-images-for-external-contributors
