### ISSUE TITLE
Uploading tasks.js break everything 

### ISSUE THREAD

**Issue by SangharshaPyakurel** [medic/cht-core#9115]
I started app development from get started step by step after i goes to task field after that all the contact forms are hide and no add anything will show only access form is shown in report .

**Comment by binokaryg** [comment]
This came from [CHT forum](https://forum.communityhealthtoolkit.org/t/uploading-tasks-js-break-everything/3499/18). It probably belongs to [medic/cht-docs](https://github.com/medic/cht-docs).

**Comment by binokaryg** [comment]
The documentation issue has been created: https://github.com/medic/cht-docs/issues/1389
We can close this.
