### ISSUE TITLE
Make place field in the user form a multiselect dropdown 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9116]
**Is your feature request related to a problem? Please describe.**
This is a continuation of https://github.com/medic/cht-core/issues/6543

Now, users can be associated with more than one facility. The CHT's Admin app should provide a way to associate those facilities with the user. 

**Describe the solution you'd like**

- The admin user enables `can_have_multiple_places` to some specific roles (e.g Supervisor CHW, etc.)

Whenever a new user is added:
- The admin user clicks on  `add user`
- The dialog displays, and the place field is a multiselect dropdown. 
- The admin user fills in the information and selects roles and multiple places. 
- The admin submits the form and CHT validates:
   - At least one of the selected roles has `can_have_multiple_places`
   - Selected places are at the same hierarchy level
   - There's currently validation that says the associated contact must be a child of the selected place. In multiselect case, it should be a child of at least one of the selected places. Validate with the team. 
- CHT displays error in form when validations doesn't pass successfully.  
- Make sure to edit existing user prefills the multiselect field, and saves changes correctly 

[MK EDIT 2024-05-14] We should also update the "Place" text. 

**Describe alternatives you've considered**
- When the validation happens, the user is not created yet, then probably use the settings service to validate `can_have_multiple_places` permission. 
- The place dropdown shows the hierarchy, check if we have access to that data easily to validate all places are from the same hierarchy level
<img width="560" alt="Screenshot 2024-05-14 at 1 43 59 PM" src="https://github.com/medic/cht-core/assets/66472237/a7a58e31-c3f9-4928-83bd-3f32153eb5ee">

**Comment by latin-panda** [comment]
@michaelkohn, please check if this is correct, and feel free to edit. 

@Benmuiruri, please review and let us know if you have any questions.

**Comment by Benmuiruri** [comment]
@michaelkohn you had started writing an [edit](https://github.com/medic/cht-core/issues/9116#:~:text=%5BMK%20EDIT%202024%2D05%2D14%5D%20We) but you didn't quite finish it. What was the thought there ?

**Comment by michaelkohn** [comment]
@Benmuiruri I was thinking we'd want to update the "place" text with some guidance on what is acceptable (can only have multiple places if the permission is enabled, places have to be at the same level in the hierarchy, etc...), but I think we can just let validation take care of it.
