### ISSUE TITLE
Impossible to upgrade from 4.7.0

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9117]
**Describe the bug**
Upgrades from 4.7.0 to any branch fail due to a bug in how we index the newly added view for _users: 
https://github.com/medic/cht-core/blame/4ced6937a73b105fa2a970d729e3803afd29893a/api/src/services/setup/databases.js#L37

**To Reproduce**
1. Install 4.7.0 with the docker upgrade service
2. Attempt an upgrade to any 4.7.x branch
3. See the upgrade fails almost immediately

**Expected behavior**
The upgrade should work.

**Logs**
Inspecting api logs, you'll find: 
```
2024-05-14T06:38:36.499 INFO: Indexing staged views 
2024-05-14T06:38:36.550 ERROR: Error thrown while installing: StatusCodeError: 404 - {"error":"not_found","reason":"Database does not exist."}
.....
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - {"error":"not_found","reason":"Database does not exist."}',
  error: { error: 'not_found', reason: 'Database does not exist.' },
  [stack]: 'StatusCodeError: 404 - {"error":"not_found","reason":"Database does not exist."}\n' +
    ....
} 
```

In haproxy: 
```
<150>May 14 06:38:36 haproxy[12]: 172.19.0.6,couchdb,404,1,2,0,GET,//medic-users/_design/:staged:users/_view/users_by_field?limit=1,-,admin,'-',294,1,58,'-'
```

**Environment**
- Instance: any
- App: api
- Version: 4.7.0

**Comment by garethbowen** [comment]
Merged. Ready for release.

**Comment by garethbowen** [comment]
Oops, not yet backported, reopening...

**Comment by dianabarsan** [comment]
Merged, backported and released.

**Comment by garethbowen** [comment]
I haven't proven this works but if anyone's stuck on this, there might be a workaround which involves skipping the view warming stage by requesting the `/upgrade/complete` endpoint...

```
curl 'https://USER:PASS@demo-cht.dev.medicmobile.org/api/v2/upgrade/complete' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"build":{"author":"npm on runner","application":"medic","base_version":"4.7.1","build":"4.7.1.9094416754","namespace":"medic","time":"2024-05-15T10:57:41.885Z","schema_version":2,"version":"4.7.1"}}'
```
