### ISSUE TITLE
Use helm repository for cht-core helm-chart

### ISSUE THREAD

**Issue by nydr** [medic/cht-core#9118]
**What feature do you want to improve?**

Use helm repository for cht-core helm-chart

**Describe the improvement you'd like**

Moving the helm chart to [medic/helm-charts](https://github.com/medic/helm-charts) and publish it with the helm repository. 

Main benefits:

1. charts become versioned
    - this allows for making larger changes without fear of breaking existing deployments as the old charts will remain available
    - can reduce the amount of logic needed for a deploy over time
2. the compressed chart file that needs to be updated each time the chart is changed is no longer increasing the size of the cht-core git history

**Describe alternatives you've considered**

Removing the compressed chart file and having cht-deploy reference the chart folder instead, this would allow faster iteration but make backwards incompatible changes more difficult (resolves point 2 but not point 1)

**Additional context**

Resolved by:
1. https://github.com/medic/helm-charts/pull/2
2. https://github.com/medic/cht-core/pull/8996

**Comment by Benmuiruri** [comment]
Thank you @nydr for writing up the issue and working on the improvement in the linked PRs
