### ISSUE TITLE
Add e2e test for upgrading from build

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9123]
**Describe the issue**

We have an e2e test that ensures it's possible to upgrade to the build version, but we don't have anything that checks it's possible to upgrade _from_ the build version. This meant a recent [critical regression](https://github.com/medic/cht-core/issues/9117) got missed in CI and released to the market and only got detected when other branch builds tried to upgrade from the released version.

**Describe the improvement you'd like**

Add a CI test/suite that after upgrading to the build version it is possible to upgrade to the next version. This is a little tricky because the next version doesn't exist yet. We could use the `master` version or possibly install the build version over the top of itself.

**Describe alternatives you've considered**

**Comment by tatilepizs** [comment]
Completed in PR #9215
