### ISSUE TITLE
Investigate the reason upgrade service related tests didn't catch the bug in how we index the newly added view for _users

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#9146]
**Describe the issue**
We need to find out why our test suite didn't catch bugs like [Impossible to upgrade from 4.7.0](https://github.com/medic/cht-core/issues/9117#top)

**Describe the improvement you'd like**
Investigate and document findings. If there is a way to cover this scenario, create an issue to implement it.

**Describe alternatives you've considered**

**Comment by garethbowen** [comment]
Related to #9123

**Comment by lorerod** [comment]
This was close by https://github.com/medic/cht-core/pull/9215
