### ISSUE TITLE
Submitter name is duplicated on the Reports Page | Detail View

### ISSUE THREAD

**Issue by michaelkohn** [medic/cht-core#9156]
## **Describe the bug**
On the Reports  Page | Detail View, the submitter's name is listed twice. So instead of saying **Submitted by Jennifer Katanga**, it shows **Submitted by Jennifer Katanga Jennifer Katanga**.  

## **To Reproduce**
1. Go to the Reports Tab
2. Tap on a Report in the list
3. Direct your eyes to the "Submitted by...." text

## **Expected behavior**
It should only show the submitters name once.

## **Screenshots**
![Screenshot 2024-05-31 at 1 31 41 PM](https://github.com/medic/cht-core/assets/10096985/4cac5813-0dfd-4024-9c25-1bf32cf1bd80)

## **Environment**
- Instance: https://demo-cht.dev.medicmobile.org/ and several others
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 4.6.0, 4.7.0, 4.8.0 (I've tested and see the problem on these versions)

**Comment by Benmuiruri** [comment]
Hi @michaelkohn 

What is the expected display of that text, is it the one on the left or the one on the right of this screenshot ? 

- For the one that has a link, clicking the link takes you to the contact who submitted the Report. 

![Screenshot 2024-06-24 at 17 45 56](https://github.com/medic/cht-core/assets/2597305/857caccb-5fdc-4bdf-87ec-056f629c3701)

**Comment by michaelkohn** [comment]
This feels like a test of my CHT knowledge 🧙🏼 😄 

The "Submitted by" could be a lot of different things I suppose. 
- Most of the time I think it would just be the CHW who is currently logged in, so tapping on this wouldn't be that useful because it would just take them to their own profile on the Contacts Page. It's actually more likely to cause mistakes whereby the user wants to navigate to something in the lineage/breadcrumbs but they accidentally tap on the "submitted by"
- The report could also be from a [JSON form](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/forms/), in which case i'm not really sure what/who the "submitted by" might be 
- I can see it being useful for a Supervisor if they have replicated reports submitted by CHWs, as a quick way to get to the CHW's profile, though I'm not really sure when/if this happens frequently. I know there are verification workflows (like death confirmations) where the report would probably get replicated "up" to the supervisor. 
- I suppose reports created by [additional docs](https://docs.communityhealthtoolkit.org/apps/guides/forms/additional-docs/) just use the same submitted by as the original doc

I image there are plenty more scenarios beyond what I have highlighted above. How does it currently work/what is the logic? I don't think we necessarily need to change anything so I'd just leave it the way it the way it currently works if that part of it isn't broken.

**Comment by Benmuiruri** [comment]
Hi @michaelkohn apologies for not coming back to it. My takeaway from your comment was the following. 

> I don't think we necessarily need to change anything so I'd just leave it the way it the way it currently works.

On investigation, I found out that this PR to[ add a link in conversation to navigate to sender's contact page link](https://github.com/medic/cht-core/pull/8717) is what might have introduced the bug. 

The way it worked before is there was no link. The above PR introduced a bug that led to duplication of the name. Therefore, to return it to how it was before was to remove the duplicate name, but do not add a link.
