### ISSUE TITLE
Running `couch-start` script fails with rate limiting error

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9169]
**Describe the issue**

CI fails sometimes with a rate limit exception trying to download couch.

eg: https://github.com/medic/cht-core/actions/runs/9416969236/job/25941195785

```
Run ./scripts/ci/couch-start
Unable to find image 'public.ecr.aws/medic/cht-couchdb:4.2.2' locally
docker: Error response from daemon: toomanyrequests: Rate exceeded.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

Restarting the build works.

**Describe the improvement you'd like**

Add a retry with a cooldown either to the GH build step, or to the script itself.

**Describe alternatives you've considered**

- Investigate why we need to install Couch in this step - I think it's for integration testing, but maybe we should do that as a separate job to make the unit test job super fast.
- Consider using a tool like docker helper to install the CHT stack instead of this custom couch install script. This gets the retry for free, increases reuse, and tests our own dog food.

**Comment by dianabarsan** [comment]
I've been wanting to fix this for a LONG time.
