### ISSUE TITLE
Add Gaze cwd with path.resolve to watch.js

### ISSUE THREAD

**Issue by fardarter** [medic/cht-core#9173]
**What feature do you want to improve?**
The module resolution in the watch.js file

**Describe the improvement you'd like**
The rootdir should apply to the Gaze config as well as the tasks

**Describe alternatives you've considered**
None

**Additional context**
We're calling the script from a different context and this addition would help us avoid the need to patch this.

The proposed change to `watch.js`.

```js
const path = require('path');
const rootdir = path.resolve(__dirname, '../../');

const watchers = [];

const DEBOUNCE = 10; // 10 ms
const GAZE_OPTIONS = {
  interval: 1000, // how often the target should be polled in milliseconds
  cwd: rootdir
};
```

**Comment by garethbowen** [comment]
Changed to a "technical issue" because no end user will notice any difference.

**Comment by garethbowen** [comment]
Thank you @fardarter !
