### ISSUE TITLE
API Endpoints for getting contacts by type

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#9193]
**Is your feature request related to a problem? Please describe.**
As noted in https://github.com/medic/cht-core/issues/8889, getting the contacts of a specific type is needed for cht-user-managment.  

**Describe the solution you'd like**

```
HTTP GET api/v1/person

HTTP GET api/v1/place?type=clinic
```

Endpoints should also accept the following query parameters to allow for paging through the data: 
- `limit` - default is `100`
- `skip` - default `0`

When it comes to the cht-datasource api, things will be a bit interesting.  On one hand, _most_ consumers of the lib will not want to manually deal with paging, but instead we should return something like an `async Iterable` so the paging it completely abstracted away.  However, the api code will need to be able to make a targeted request for a specific limit/skip since that is what it will be receiving as a request and for best performance we will need to be able to pass those though directly to the Couch view query... Perhaps we just provide both functions in cht-datasource:

- One that takes `limit/skip` and returns an array of values.
- One that just returns an Iterable - Under the hood, this would probably just use the first function, but wrap it up with a generator function or something.

**Describe alternatives you've considered**
Other ways to structure the API include:
- `api/v1/clinic`
- `api/v1/place/clinic`

However, these do not seem any more clear than just using a query parameter and are definitely less flexible.

**Comment by sugat009** [comment]
After a bit of assessment, I've decided to break this task down into smaller tasks in the following way.
1. Add functionality of getting people with pagination in the `cht-datasource`.
2. Add functionality of getting people as an `async Iterable` in the `cht-datasource`.
3. Add functionality of getting places with pagination in the `cht-datasource`.
4. Add functionality of getting places as an `async Iterable` in the `cht-datasource`.
5. Add API `api/v1/person`
6. Add API `api/v1/place?type=clinic`

_TODO: Create tickets for these._

**Comment by sugat009** [comment]
I will be pushing each sub-task changes to this branch `9193-api-endpoints-for-getting-contacts-by-type`.
