### ISSUE TITLE
Upgrade e2e tests fails on minor releases 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9218]
**Describe the issue**
After creating the 4.9.0 tag, it failed consistently with the errors below, however, the upgrade is working fine. 

Please stabilize these tests before 4.10 is out: 

![Screenshot 2024-06-26 at 12 53 39 PM](https://github.com/medic/cht-core/assets/66472237/fdfa4e8c-2f63-4422-bb60-05b275d6f3bc)

![Screenshot 2024-06-26 at 12 50 33 PM](https://github.com/medic/cht-core/assets/66472237/5002cc14-3c5c-43f9-8248-6a471960eac3)

![Screenshot 2024-06-26 at 12 53 48 PM](https://github.com/medic/cht-core/assets/66472237/fe41aec9-d612-494e-92a0-e5a6006f253e)

https://github.com/medic/cht-core/actions/runs/9673244794/job/26688062252

**Comment by latin-panda** [comment]
fyi @lorerod @tatilepizs @ralfudx

**Comment by dianabarsan** [comment]
@latin-panda 

To be clear, which upgrade e2e test failed, from which version to which version? I'm seeing the upgrade e2e test pass successfully on current `master`.

**Comment by latin-panda** [comment]
@dianabarsan That was when creating the 4.9.0 tag for release. It didn't fail in master nor in beta tags.

**Comment by latin-panda** [comment]
The run still available, you can see[ it here.](https://github.com/medic/cht-core/actions/runs/9673244794)

**Comment by dianabarsan** [comment]
Ah, I see. I think this is probably expected now, because the test is trying to upgrade from 4.9.0 to 4.9.0 (from latest to latest). 

![image](https://github.com/medic/cht-core/assets/35681649/d854c41e-ca30-46f4-9054-f6ce19dd47af)
