### ISSUE TITLE
Include xpath function for validation of Luhn identifiers

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9227]
**Is your feature request related to a problem? Please describe.**

The [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) provides for checkbits to detect typos on the client side, but right now there's no way to run this validation in enketo forms.

**Describe the solution you'd like**

Include a custom xpath function to validate the given number is valid.

**Comment by garethbowen** [comment]
@ChinHairSaintClair Does that mean you need to normalize the data, and not just validate it? I'm thinking about if there are spaces included, and that passes validation, but then it's auto-filled later on with spaces intact?

**Comment by ChinHairSaintClair** [comment]
@garethbowen you have a valid point. That seems to be the case, yes.
If we only used the value downstream, it could be easily addressed, however it's still better to fix the issue at source.
I've read up a little and played around with the `translate` xpath function and it seems something like `translate(., ' ', '')` would strip spaces from a string. Contrary to my original understanding.
See the below screenshot:
![image](https://github.com/user-attachments/assets/c4e0a238-e757-4895-8453-582efdf592ae)
This should suffice. However, do you think we need to rethink what the Luhn XPath method returns?

**Comment by garethbowen** [comment]
I think the validation can only return a boolean, right? If so then you could have two xpath functions - one to validate and one to transform (more or less what you have demoed). The other option would be to have an enketo widget which does both but that's much more complex to write and maintain than xpath functions.

**Comment by ChinHairSaintClair** [comment]
@garethbowen thank you for your suggestions. 
I've added a function that strips white spaces and pushed it to the open PR for your review.

**Comment by garethbowen** [comment]
Thank you! I'll review on Monday.

**Comment by garethbowen** [comment]
Merged. Thank you!
