### ISSUE TITLE
Add Nepali translation to the lint

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9234]
**Describe the issue**
Add Nepali language to the [lint](https://github.com/medic/cht-core/pull/9209/files) once it has been [fully translated](https://github.com/medic/cht-core/pull/9219). This ensures we keep supporting the language correctly and that all translation strings are added. 

**Describe the improvement you'd like**

**Describe alternatives you've considered**

**Comment by 1yuv** [comment]
Hi @garethbowen , @latin-panda , Is it okay for me to add this on this [PR](https://github.com/medic/cht-core/pull/9219) ? As this would allow me to fix anything if needed.

**Comment by garethbowen** [comment]
@1yuv Yes I think so - makes sense to turn linting on to ensure the translations are correct before merging that PR.
