### ISSUE TITLE
Add functionality of getting people as an iterator in cht-datasource

### ISSUE THREAD

**Issue by sugat009** [medic/cht-core#9238]
**Is your feature request related to a problem? Please describe.**

This feature is part of a bigger feature of the creation of API endpoints for getting contacts by type. (#9193)
The target of this feature is to have the functionality of getting people using `cht-datasource` as an `AsyncIterator` or something similar that can fetch data in batches.

**Describe the solution you'd like**

```javascript
Person.v1.getAllAsync();
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jkuester** [comment]
As noted here: https://github.com/medic/cht-core/issues/9237#issuecomment-2221081736

I think we should go for a function signature like:

```ts
const getAll = () => AsyncGenerator<Person.v1.Person, void>
```

Also, FTR, I have found [this blog post](https://javascript.info/async-iterators-generators) to be very helpful in wrapping my mind around async interators/generators.

**Comment by garethbowen** [comment]
@sugat009 Should this be in the release milestone?

**Comment by sugat009** [comment]
@garethbowen yes.

**Comment by jkuester** [comment]
I am removing this from the 4.11 milestone since it is covered already by https://github.com/medic/cht-core/issues/9241.
