### ISSUE TITLE
Reports with subject_id set via patient_id are not exposed at skip-level contact summary

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9253]
**Describe the bug**

**To Reproduce**

The hierarchy is: CHW Area (place) > Household (place) > Client (person)

1. Create a report X which sets `fields.patient_id` to a Client’s id
2. View the contact summary for the CHW area (two levels above the client with report X). 
3. Log the value of `reports` data passed into the contact summary.  (Reports does not include report X)
5. Update report X changing the `fields.patient_id` to `fields.patient_uuid`
6. Look at the value passed to the CHW area’s contact summary again
7. The `reports` data now includes report X

**Expected behavior**
Consistent behavior across `patient_id` and `patient_uuid`

**Environment**
- Instance: eCHIS KE Digital Payment
- Browser: *
- Client platform: *
- App: webapp
- Version: 4.8.x

**Additional context**
The behavior to expose the data into the contact summary can also be achieved by adding a 2nd subject ID like setting `place_id` to the CHW Area's ID. That's maybe more concerning? I'm not sure.

https://forum.communityhealthtoolkit.org/t/reports-with-multiple-subject-ids/3737/5

**Comment by dianabarsan** [comment]
I'm trying to replicate this behavior and failing. 

According to this: https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/contact-view-model-generator.service.ts#L316 , we only ever load the reports of the current contact's person's children reports. So you would never see a report from two levels down. 

Can I see this behavior somewhere online? This might be some particularity about your config.

**Comment by eljhkrr** [comment]
The config is available on nairobi-echis-clone.health.go.ke

**Comment by dianabarsan** [comment]
Can you link to a particular report that shows up on skip level - without having a place_id field?

**Comment by eljhkrr** [comment]
No reports show in skip-level without place_id

**Comment by dianabarsan** [comment]
Ok, that's what I thought. Then I don't exactly know what to make of this issue.

**Comment by eljhkrr** [comment]
I think the argument is that they should be visible without having to rely on place_id

**Comment by dianabarsan** [comment]
We have no precedent of this, showing things 2 levels above by default. So this is not a bug. It's more like a feature request.

**Comment by dianabarsan** [comment]
Do you have a report with patient_id _and_ place_id that doesn't show up for the `place_id`? And the one with `patient_uuid` does?

**Comment by kennsippell** [comment]
Double checked this today and the behavior between `patient_id` and `patient_uuid` is consistent. So maybe this isn't a bug.

So the steps we're looking at are:
1. Create a report which sets `patient_uuid` or `patient_id` to the client's ID  AND  sets `place_id` to the CHW Area's ID
2. View the CHW Area's contact summary
3. The client's report is visible here on the place's contact summary

We want this behavior (we want to be able to see this report at the skip level's contact summary).  Is it safe to deploy an eCHIS Kenya workflow which relies on this behavior from setting multiple subject IDs?

**Comment by dianabarsan** [comment]
@kennsippell do you have any thoughts about what we should do with this issue? 
We have mostly concluded that this behavior is not a bug, and we searched for alternative solutions for your workflow (https://github.com/medic/cht-core/issues/9269). 
I still believe we should address the inconsistency for selecting replication subject id versus other subject id selection, but this issue doesn't clearly target that.

**Comment by kennsippell** [comment]
I agree we should address the inconsistencies and I'll trust you to track those appropriately.
