### ISSUE TITLE
Contact Details load facilities when user has one home place assigned

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9265]
**Describe the bug**
When the user only has 1 home place assigned, the contact details should not load the descendant facilities. For example, a CHW Area that is the user's home place should not load households. 

But if the user has more than 1 home place assigned, it should load them.  

The bug is when the user has 1 home place, it's loading the facilities on reload. 

**To Reproduce**

https://github.com/user-attachments/assets/ad0af532-cadc-423f-a02a-abf1b4f99357

**Expected behavior**

It should not load the descendant facilities when a user has 1 home place assigned, not even when reloading the page. 

**Logs**
No errors in logs.

**Environment**
- Instance: Local
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 4.9

**Comment by latin-panda** [comment]
@michaelkohn Am I remembering the rule correctly? Should we make this rule explicit somewhere in cht-docs so it's not just a rule in the code?

**Comment by michaelkohn** [comment]
> Am I remembering the rule correctly?

Yes, that is correct. 

> Should we make this rule explicit somewhere in cht-docs so it's not just a rule in the code?

We mention this in the [release notes](https://docs.communityhealthtoolkit.org/core/releases/4.9.0/#user-experience) and link to the forum screenshots in the docs [here](https://docs.communityhealthtoolkit.org/apps/features/supervision/#managing-multiple-areas). Perhaps we can address it elsewhere (like [here](https://docs.communityhealthtoolkit.org/apps/features/contacts/)) when we redo _everything_ for NAV. Was there somewhere else you were thinking too? cc: @esthermmoturi
