### ISSUE TITLE
Expose the user's target documents into the contact summary

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9269]
**Is your feature request related to a problem? Please describe.**
Automated payment workflows and stock monitoring workflows are often limited in their functionality because of the data that is available to the contact summary and data which is available to forms. A contact summary can only see data directly associated with a single place and even after 3.7.x the data is limited to 500 reports which can be insufficient when reviewing all data created by a CHP in a month. 

We are seeking a performance way to expose more data to contact summaries and to forms.

**Describe the solution you'd like**
Targets have full access to all data on a user's device. Targets are efficient because 1) the data is not exposed at once and 2) the results target computations are efficiently cached. `targetDocs` store the computed results of targets.  If we were to expose the user's current and recent target docs to the contact summary, this would be fast, powerful, and performant way to allow contact summaries and forms to effectively access the results of computations which requirei all data on the device. 

**Describe alternatives you've considered**

**Additional context**
eCHIS Kenya Digital Payments go-live is awaiting this feature

**Comment by mrjones-plip** [comment]
@garethbowen  - I'd love to merge this to `master` so we have a solid feature in `4.11`  and then do the release that @witash  is release manager for.

Can you complete the merge now/create a new PR to merge/assign an engineer to do the work?  

Thanks!

**Comment by garethbowen** [comment]
@dianabarsan is assigned already. What do you think? Is this ready for the mainline?

**Comment by dianabarsan** [comment]
This has been merged to `master` and backported to `4.11` and UAT-ed on 4.11.
