### ISSUE TITLE
Starting an upgrade that involves view indexing can cause CouchDB to crash

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9286]
**Describe the bug**
I've been consistently seeing that starting an upgrade - and starting view indexing through the upgrade API - can cause CouchDb v2 to crash without a crash log. What I was seeing was Couch stopping logging requests, haproxy reporting <NOSRV> for all incoming requests.  

**To Reproduce**
1. Install CHT Core 4.2.2 on a large database (I was on a database with 33M docs). 
2. Upgrade to 4.8.1
3. CHT is inaccessible and haproxy reports <NOSRV> (communication between haproxy and couchdb is broken, but couchdb still runs). 
 
**Expected behavior**
Starting an upgrade should not crash couchdb. 

**Logs**
```
<150>Jul 26 20:57:30 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:31 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:32 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:33 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:34 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:35 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:36 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:37 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:38 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:39 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:40 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'
<150>Jul 26 20:57:41 haproxy[12]: 172.22.0.4,<NOSRV>,503,0,0,0,GET,/,-,medic,'-',217,-1,-,'-'

```

```
[notice] 2024-07-26T20:52:45.229027Z couchdb@127.0.0.1 <0.10998.4> dca1387a05 haproxy:5984 172.22.0.4 medic GET /_active_tasks 200 ok 1
[notice] 2024-07-26T20:52:45.234397Z couchdb@127.0.0.1 <0.10986.4> 2715cd1e47 haproxy:5984 172.22.0.4 medic GET /medic-logs/_all_docs?descending=true&include_docs=true&startkey=%22upgrade_log%3A1722027165223%3A%22&limit=1 200 ok 6
[notice] 2024-07-26T20:52:45.468469Z couchdb@127.0.0.1 <0.11029.4> 3bf85c6071 haproxy:5984 172.22.0.4 medic GET /_active_tasks 200 ok 1
[notice] 2024-07-26T20:52:45.472730Z couchdb@127.0.0.1 <0.11024.4> 3f14bb6656 haproxy:5984 172.22.0.4 medic GET /medic-logs/_all_docs?descending=true&include_docs=true&startkey=%22upgrade_log%3A1722027165463%3A%22&limit=1 200 ok 5
[notice] 2024-07-26T20:52:45.967644Z couchdb@127.0.0.1 <0.11355.4> 73a558eb82 haproxy:5984 172.22.0.4 medic GET /_active_tasks 200 ok 1
[notice] 2024-07-26T20:52:45.971950Z couchdb@127.0.0.1 <0.11354.4> d2bba2e013 haproxy:5984 172.22.0.4 medic GET /medic-logs/_all_docs?descending=true&include_docs=true&startkey=%22upgrade_log%3A1722027165962%3A%22&limit=1 200 ok 5
```

**Environment**
- Instance: production instance
- App: CouchDb & Haproxy
- Version: 4.2.2 - guessing it will affect 4.3.x, since this uses the same version of couchDb 

**Additional context**
Everytime this happens, I've restarted both haproxy and couchdb - I believe this is also happening: https://github.com/medic/cht-core/issues/9284

Eventually I just abandoned using the upgrade API and started indexing process manually (by navigating to the views one by one). This seems to not trigger the same behavior. 

I'm suspecting we're ending up queuing too many requests because of the 2 minute timeout we set in API: https://github.com/medic/cht-core/blob/4.2.x/api/src/services/setup/view-indexer.js#L69
I believe this timeout doesn't end up cancelling the request at CouchDb level, so it's possible we're running out of file descriptors or something (???). Because there are no logs, it's not possible to know.

**Comment by Hareet** [comment]
> it's possible we're running out of file descriptors
No couch logs is weird. I've seen unable to open more files / file descriptors as `{error,emfile}` back when we were diagnosing ulimit parameters.

**Comment by dianabarsan** [comment]
> No couch logs is weird.

I know, right? 
I was tailing docker logs as the failures happened and nothing came through, even though the instance was down.
