### ISSUE TITLE
Float button menu form icons vertical alignment

### ISSUE THREAD

**Issue by jonathanbataire** [medic/cht-core#9291]
**What feature do you want to improve?**
The alignment looks great for large screens eg PCs but looks off for mobile devices. Screenshots for v4.9.0 vs v4.2.4
![SmartSelect_20240731_180857_CHT Android.jpg](https://github.com/user-attachments/assets/90fba7ec-1840-4635-b91b-bfd0355edbc4)

![SmartSelect_20240731_180831_eCHIS Uganda.jpg](https://github.com/user-attachments/assets/4dccddc2-d5b8-4a23-a386-6a37dc71b970)

**Additional context**
this has been tested for v4.9.0 and v4.2.4
with cht-android v1.4.0

**Comment by kapelo** [comment]
Hi @Benmuiruri, as discussed I noticed that on mobile the text seems to be properly aligned but the icon is not. Also, when the icon is bigger it tends to shift the position of the text like we see for "New area" on mobile
![icon](https://github.com/user-attachments/assets/bdb20306-108b-4842-a926-2f259a547c84)
