### ISSUE TITLE
CouchDb error on indexing telemetry documents

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9298]
**Describe the bug**
Checking logs from an instance upgrading from `4.2.2` to `4.8.1`, I'm seeing lots of errors logged about failing to index certain telemetry documents: 
```
[info] 2024-07-24T22:47:37.208456Z couchdb@127.0.0.1 <0.26440.0> -------- OS Process #Port<0.9087> Log :: function raised exception (new TypeError("number.toString().padStart is not a function", "undefined", 12)) with doc._id telemetry-2024-2-13-plucygaren-5ddd3d91-56b1-48ad-a11f-8f0e97f813fd
[info] 2024-07-24T22:47:37.208835Z couchdb@127.0.0.1 <0.26439.0> -------- OS Process #Port<0.9086> Log :: function raised exception (new TypeError("number.toString().padStart is not a function", "undefined", 12)) with doc._id telemetry-2024-2-16-bmargaretitauc-022087c6-d91c-4f8a-b3f0-14b9bf787784
[info] 2024-07-24T22:47:37.210019Z couchdb@127.0.0.1 <0.6689.1> -------- OS Process #Port<0.9887> Log :: function raised exception (new TypeError("number.toString().padStart is not a function", "undefined", 12)) with doc._id telemetry-2024-2-6-vvictorhumax-2367c8bf-1508-4eb1-bdbb-c210356d25e9
[info] 2024-07-24T22:47:37.210751Z couchdb@127.0.0.1 <0.6670.1> -------- OS Process #Port<0.9882> Log :: function raised exception (new TypeError("number.toString().padStart is not a function", "undefined", 12)) with doc._id telemetry-2024-2-10-hleahwasif-a07b0c8a-1c08-4b8c-bc90-8ce228ed86ab
```

**To Reproduce**
1. Install 4.2.2
2. Create an offline user and do some actions, change the date to generate a telemetry document. 
3. Upgrade to 4.8.1
4. Check logs. 

**Expected behavior**
Ideally no views should throw errors. 

**Logs**
As above. 

**Environment**
- Instance: production instance
- App: couchdb
- Version: 4.8.1

**Additional context**
We had fixed the view to be backwards compatible with the Javascript engine that runs on CouchDb 2, so the view can be warmed, but it appears that some documents can still throw errors when being indexed.

**Comment by garethbowen** [comment]
It's interesting that it's just a `info`! I'm guessing this means the view index will be empty when you first start. As far as I'm aware the view isn't critical, and after the upgrade to CouchDB 3 it will run just fine. Because of the way this view index is used I expect it to heal itself and start giving correct results as more docs are replicated every month.

We should definitely fix it but there may be a case for not backporting it as updating which would trigger a view rebuild which is arguably more disruptive than having some data missing.

More investigation needed.

**Comment by dianabarsan** [comment]
I think the info vs crash is something that was addressed in the new version of CouchDb. 
I agree about not backporting the fix if the view heals itself automatically after the upgrade.

**Comment by dianabarsan** [comment]
I've replicated this in 4.3.1 and then upgraded to 4.8.1. 
I'm sad to say that documents are not indexed when accessing the view in 4.8.1 so somehow couchdb does advance the seq of the view after the bugged documents, so unless someone clears the views, these docs will be missing from the view results forever.
