### ISSUE TITLE
Automate the part of release process where we send informative messages to Slack

### ISSUE THREAD

**Issue by sugat009** [medic/cht-core#9336]
**What feature do you want to improve?**/ **Describe the improvement you'd like**
This is not a feature improvement request but an improvement in the release process in which we send messages to Slack channels for information. Sending these messages could be automated and triggered through an event probably.

**Additional context**

![image](https://github.com/user-attachments/assets/d41e4ca5-a5e2-4ef9-8da0-4976cd80a581)

Adding the ticket link for context. #9333

**Comment by mrjones-plip** [comment]
Thanks for filing this!  `Features` are for user facing tickets. what we want here is a `technical issue`:

>  **Technical issue**
> Suggest an improvement users won't notice

I've updated the ticket.

**Comment by mrjones-plip** [comment]
@sugat009 - after chatting with @garethbowen - I'm going to close this ticket.  With A) our move to CD and B) our move to community being able to release, it won't make sense in the long term to have this feature.  

Sorry for any waste of your time!
