### ISSUE TITLE
Add password reveal to change password form

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#9354]
**What feature do you want to improve?**

When changing password through the app it would be useful to have a button to reveal the password the same way we do on the login page, added in #8311

**Describe the improvement you'd like**

Add an icon which shows the password in plaintext so the user can see there are no typos.

**Describe alternatives you've considered**

Make password resets easy, but this requires more infra (eg: ability to send email/sms/something)

**Additional context**

Requested by MoH Kenya, cc @PhilipNgari

**Comment by chiragkhatri19** [comment]
Can I help with this improvement Gareth?

**Comment by garethbowen** [comment]
@chiragkhatri19 Yes please! I've assigned you to it.

The code should look roughly the same as the login page which was done in issue https://github.com/medic/cht-core/issues/8311 - the main difference is the password change form is in Angular whereas the login page is pure JavaScript.

To set up a developer environment follow the documentation: https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/

To get to the page in question,

1. Login as a non-admin user (admin's aren't allowed to change their password for technical reasons)
2. Go to the hamburger menu > User Settings
3. Select "Change password"

If you have any further questions please reach out!

**Comment by garethbowen** [comment]
@chiragkhatri19 How are you getting on? Anything I can help you with?

**Comment by fenedara** [comment]
Hi.  I have started looking into handling this issue, but I am new to the CHT, so I'm not sure yet if I will be successful.  I will post here again as I make progress.

**Comment by latin-panda** [comment]
Thanks for taking the time to look into this issue! We really appreciate your contribution ✨

If you run into any block or have questions, please don't hesitate to post here, or feel free to join us on [the CHT forum](https://forum.communityhealthtoolkit.org/c/support/development/7). We're happy to help in any way we can.

The first step is [to setup the development environment](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/) and see the current user experience of that page. This Angular application is located [in the webapp folder](https://github.com/medic/cht-core/tree/master/webapp), and you'll find [here the modals for user settings](https://github.com/medic/cht-core/tree/master/webapp/src/ts/modals/edit-user)

Best of luck!

**Comment by fenedara** [comment]
I got this working in the 'App Management' part of the app, but I'm still working on the 'Update password' modal that's under 'User Settings'.  Once I finish that, I'll just need to make a branch for it.

**Comment by jkuester** [comment]
>  I haven't done a pull request on GitHub before.

:+1: no worries.  GitHub does read/write permissions on a repo-by-repo basis.  `medic/cht-core` is _readable_ by anyone, but only specific users can _write_ to it.  This is why you are getting that error.

Instead of trying to push your branch to `medic/cht-core`, you should [fork the `cht-core` repository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo).  This creates a remote copy of the repo _for your user_ (where you should have full read/write permissions): `fenedara/cht-core`.  You should push your branch to the  `fenedara/cht-core` fork (FYI, forked repos on GitHub are simply considered by `git` to be [separate remotes](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes)).  Then, you can [create a PR from your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back into the `medic/cht-core` repo.

**Comment by fenedara** [comment]
Got it.  Thanks.
I created the pull request and it is here:  https://github.com/medic/cht-core/pull/9422

**Comment by fenedara** [comment]
It looks like I may still need to run and update the unit tests.  I'll look into that next.

**Comment by latin-panda** [comment]
Thank you! You can find the commands to run the unit tests [in this link](https://docs.communityhealthtoolkit.org/contribute/code/core/build-commands/#development-test-commands)

**Comment by fenedara** [comment]
I fixed a few issues with the PR, but there are still 2 SonarCloud security hotspot issues that I think are false positives.  SonarCloud seems to think that when I am setting 'passwordFieldType' to 'password', the value 'password' is a password itself that shouldn't be hard-coded in the source code.  Please let me know how I should proceed.  Does someone with more permissions just need to mark the issues as 'Safe'?

**Comment by latin-panda** [comment]
Hi @fenedara, that's right. It's an HTML input `type`, not an actual password representing risk. The Sonar should be good now.

**Comment by fenedara** [comment]
Is there anything else I should do for this currently?  Is it just waiting on review by developers?

**Comment by latin-panda** [comment]
Awesome, thanks @fenedara!✨ We're going to review the pull request and get back to you in a couple of days max

**Comment by fenedara** [comment]
Ok, got it.  No rush.
