### ISSUE TITLE
Research community use of search

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#9365]
**Describe the issue**
We don't know how search is used, so we're not sure how hosting TCO efforts to reduce free text search might impact search.

**Describe the improvement you'd like**
UXR team to decide best how to validate search use, but: We should reach out to App Services, program managers, 3rd party app devs and anyone else we think would help inform us of how search is used.  Are there workflows that CHWs are trained on that use search?  Are there deployments where reports tab is hidden so this search doesn't work? 

Some info to inform our research is:

### update from Care Teams

Excerpt from a [slack thread](https://medic.slack.com/archives/C02GME3BQE6/p1722904248162379?thread_ts=1722887181.632989&cid=C02GME3BQE6):

> > which ones use it?  (telemetry?)
> 
> Here are two posts re: search on [Reports](https://forum.communityhealthtoolkit.org/t/telemetry-questions-about-the-reports-tab-search/2018) and [Contacts](https://forum.communityhealthtoolkit.org/t/telemetry-questions-about-the-contacts-tab-search/2651) pages.  I [just pulled some data](https://docs.google.com/spreadsheets/d/1LZhRpnC1R3YRmkhDgPNA3cEgrCNLQuTidgSEltBRuo8/edit?gid=427600872#gid=427600872) based on the search:contacts:search and search:reports:search keys for a handful of projects. I can't guarantee that these keys only count freetext searches but I believe so.  We can chat tomorrow about the details if you like.

> > how many hide it? (eg hide reports tab)
> 
> Also included in the same spreadsheet as above. Pretty much everyone has access to the Contacts Page, some users don't have access to Reports, but most do.
> 
> Worth noting that there's a difference between (a) being able to see the page at all, and (b) whether it shows up as a tab or in the hamburger menu. The data I pulled relates to being able to see the page at all
> 
> > train on it?
> 
> Not sure. 

Another excerpt from the same thread:

> Looking at [telemetry](https://docs.google.com/spreadsheets/d/1LZhRpnC1R3YRmkhDgPNA3cEgrCNLQuTidgSEltBRuo8/edit?gid=427600872#gid=427600872) ,percentage of total CHWs is between   0.07% and 50%  - search is very much being used!

### Fields we're planning on indexing

Contacts
* name
* notes
* patient_name

Reports:
* ? TK ?

### Search results analysis
* ? TK google doc link (private) ?

### Care Teams Updates

**Comment by mrjones-plip** [comment]
@jkuester - can you fill out the fields section above?  There were a lot less fields than I expected in [Mokhtar's PR](https://github.com/medic/cht-core/pull/9308/files) - so wanted to get a core eng to validate what I saw (and fill out reports section ;) 

@ZiitheH - I'll look to do fill out the  search results analysis section above - per our chat this will be stored in a private google doc as it will likely contain PII/PHI

**Comment by jkuester** [comment]
:+1: Still in the process of doing a deep dive into our current functionality and how search is being used programmatically.  The output of this will be a list of fields that I believe should be indexed.  I plan to complete this tomorrow and will followup on this issue with the list.

**Comment by jkuester** [comment]
Okay, see this comment: https://github.com/medic/cht-core/issues/9293#issuecomment-2307407027 for my proposed fields to index.  TLDR would allow searching for contacts by name, DoB, phone, and short-code and searching for reports by short-code.
