### ISSUE TITLE
Only 50 reports are passed to the contact summary which is passed to enketo

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9429]
**Describe the bug**
After https://github.com/medic/cht-core/issues/8815 (4.7),  the contact-summary.templated.js code is passed the contact's latest 500 reports.  But in this specific scenario, the contact-summary is passed only 50 reports.

**To Reproduce**
1. Create a CHT place
2. Create 100 reports at this place
3. Create a contact-summary.templated.js which outputs the value of `console.log(reports.length);`
4. Navigate to the CHT place and view the value of reports. You see `100` (good)
5. Complete an action at the place
6. When the action loads, contact-summary is calculated again with the result passed to enketo and this time says `50` (bad)

**Expected behavior**
The data passed to the contact-summary should be consistent every time it is calculated

**Environment**
- Instance: eCHIS Kenya
- App: webapp
- Version: master 4.11

**Additional context**
This is causing data quality problems for eCHIS Kenya digital payments work. If a CHP completes more than 50 forms between their performance-assessment and their performance-verification, then their supervisor sees that their performance-assessment was not completed (not found).

**Comment by mrjones-plip** [comment]
@kennsippell  - can you confirm if https://github.com/medic/cht-core/issues/9025  would have been a fix had it not been closed?

**Comment by kennsippell** [comment]
@mrjones-plip It could be batched, but it isn't necessarily a fix for it... This isn't a user-facing problem perse like #9025.

**Comment by dianabarsan** [comment]
Merged to master and backported to 4.11
