### ISSUE TITLE
Merge ensureTaskFreshness and  ensureTargetFreshness into single event

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9432]
**Describe the performance issue**
In `rules-engine.service.ts` there are two background events which trigger after 120seconds. One of these background events (ensureTaskFreshness) refreshes tasks, and the other (ensureTargetFreshness) refreshes targets.  

Under the covers, refreshing tasks and targets is mostly the work to `refreshRulesEmissionForContacts` + some minor task/target specific things. 

Can we avoid redundant calls to refreshRulesEmissionForContacts?

**Describe the improvement you'd like**
Probably just a single call to new interface like `fetchAll` which writes task docs and target doc. Also, there is some evidence to suspect that this may be linked to an intermittent unreproduced functional bug: 

1. There are numerous reports of users who navigate to the analytics tab and intermittently experience all zeros.  
2. When analyzing a set of two users who have targetDocs in the erroneous state of having all 0s (not representative of correct target calculations), both user's telemetry docs had `rules-engine:ensureTargetFreshness:cancel` events their telemetry events the day the target doc was written.

So there are maybe some problems introduced by these async managed and _concurrent_ calls to `refreshRulesEmissionForContacts`.  Don't know how rules-engine handles multiple concurrent calls (?)

**Describe alternatives you've considered**
We could remove these background threads completely since it isn't clear how they impact the user experience or freshness and it's somewhat risky&complex to do this kind of thing. Or we could reconsider when they happen - like it may be preferrable to run these after launching an enketo form; it is more likely no other heavy activity is happening then vs just a random 120seconds.

**Measurements**
Unknown

**Environment**
- App: webapp
- Version: 4.11 master

**Additional context**

**Comment by dianabarsan** [comment]
I'm adding this to 4.13. Due to the changes necessary to ensure target doc accuracy, this has become a very easy change.

**Comment by dianabarsan** [comment]
Merged to master and backported to 4.13.x
