### ISSUE TITLE
REST Endpoint `/api/v1/users/{{username}}` throwing Server error when updating `contact`

### ISSUE THREAD

**Issue by sugat009** [medic/cht-core#9433]
**Describe the bug**

When requesting the REST API endpoint `/api/v1/users/{{username}}` to update a contact `500 - Server Error` is being thrown. The error seems to be starting from CHT version 4.9.0.

**To Reproduce**

Use the following request to reproduce the error:
```
curl --location 'http://localhost:5988/api/v1/users/<username>' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic <token>' \
--data '{
    "contact": "<contact_id>"
}'
```

**Expected behavior**

Contact should be updated for the given user if it is valid.

**Logs**

**Screenshots**

1. CHT version 4.8.0
![Screenshot_20240912_185758](https://github.com/user-attachments/assets/ddff1b1b-8f71-4468-ad77-69a9be7f1f76)

![Screenshot_20240912_185950](https://github.com/user-attachments/assets/5c10acfc-29ee-48fc-b305-7c9601b48070)
2. CHT version 4.9.0
![Screenshot_20240912_190027](https://github.com/user-attachments/assets/60b061ed-e567-4328-9df8-adad15c20c6a)

![Screenshot_20240912_190038](https://github.com/user-attachments/assets/e3fb1907-74c2-4436-9dfb-be41d1663d80)

**Environment**
- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: API
- Version: 4.9.0

**Additional context**

N/A

**Comment by jkuester** [comment]
[Slack thread](https://medic.slack.com/archives/C024KTGRW/p1726137437682739) for context.
