### ISSUE TITLE
Docker helper failing to run cht on later versions

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9442]
**Describe the bug**
We are not able to run docker-helper-4x on latest version of CHT as it fails to pull required images. 

**To Reproduce**
1. Run docker helper.
2. When prompted if you want to start new project, say yes. 
3. When prompted if you want to run latest version of CHT Core (4.10.0), say yes. 
4. Give your project a name. 
5. Wait for your project to fail. 

**Expected behavior**
Docker helper should successfully start the instance. 

**Logs**

If you inspect the upgrade service logs, you would see that docker helper is unable to pull required manifests. 

This is the log I got from trying to start 4.10.0 instance: 

```
sentinel Pulled 
couchdb Error 
nginx Error 
api Error 
haproxy Error

Error response from daemon: Head "https://public.ecr.aws/v2/medic/cht-couchdb/manifests/4.10.0": proxyconnect tcp: dial tcp 192.168.65.1:3128: i/o timeout

    at ChildProcess.<anonymous> (/app/src/docker-compose-cli.js:35:25)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

This is the log I got from trying to start latest master: 
```
Error response from daemon: Head "https://public.ecr.aws/v2/medic/cht-sentinel/manifests/4.11.0-alpha": Get "https://public.ecr.aws/token/?scope=repository%3Amedic%2Fcht-sentinel%3Apull&service=public.ecr.aws": context deadline exceeded

    at ChildProcess.<anonymous> (/app/src/docker-compose-cli.js:35:25)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

**Screenshots**

**Environment**
- Instance: Local
- Browser: Any
- Client platform: MacOS (But I guess it's everywhere)
- App: webapp, sentinel, api, couchdb
- Version: 4.10.0 and latest master

**Additional context**
This works on older version of the CHT (4.9.0), so I tested that and [suggested](https://forum.communityhealthtoolkit.org/t/docker-helper-failed-to-start/4016/6?u=yuv) a forum user to work with 4.9.0

I suspect either a) we are not publishing image or manifests correctly, b) the permission has changed

**Comment by m5r** [comment]
I haven't been able to reproduce on linux (EndeavourOS), it seems to be specific to MacOS. What Docker and Docker Compose versions are you running?

**Comment by mrjones-plip** [comment]
I confirm on Ubuntu `22.04` running CHT `4.10.0` works as expected on these versions of docker:

```
docker --version && docker compose version
Docker version 27.2.1, build 9e34c9b
Docker Compose version v2.23.0-desktop.1
```

@1yuv - did you try and upgrade an instance? There is a known issue with [docker helper and upgrading](https://github.com/medic/cht-core/issues/9235).

**Comment by mrjones-plip** [comment]
@1yuv - looking at this a bit more closely, i see two errors:

* `Error response from daemon: Head "https://public.ecr.aws/v2/medic/cht-couchdb/manifests/4.10.0": proxyconnect tcp: dial tcp 192.168.65.1:3128: i/o timeout`
* `Error response from daemon: Head "https://public.ecr.aws/v2/medic/cht-sentinel/manifests/4.11.0-alpha": Get "https://public.ecr.aws/token/?scope=repository%3Amedic%2Fcht-sentinel%3Apull&service=public.ecr.aws": context deadline exceeded`

One is in CouchDB (`i/o timeout`) on `4.10.0` and one is in Sentinel (`context deadline exceeded`) on ~`master`.  This seems odd. I would have expected them to fail in the same way. 

Given it works for two other engineers, I wonder if this is an intermittent networking issue?  Do you know if you had the `4.9.0` images cached already?

Can you try deleting the any cached `4.9.0` images and see if the issue resurfaces there? This should work (but will kill *all* containers!): `docker kill $(docker ps -q)&&docker image rm -f $(docker image ls -qf "reference=public.ecr.aws/medic/*:4.9.0")`

alternately you may try pulling all the images first for `4.10.0` and then trying to run docker helper to see if that fixes it or finds network based errors:

```
docker pull public.ecr.aws/medic/cht-haproxy:4.10.0
docker pull public.ecr.aws/medic/cht-haproxy-healthcheck:4.10.0
docker pull public.ecr.aws/medic/cht-api:4.10.0
docker pull public.ecr.aws/medic/cht-sentinel:4.10.0
docker pull public.ecr.aws/medic/cht-nginx:4.10.0
docker pull public.ecr.aws/medic/cht-couchdb:4.10.0
```
```

**Comment by 1yuv** [comment]
Hi @mrjones-plip , 
I checked again and tried to create instance from 4.10.0, and this succeded. This looks like an intermittent networking issue at that time.
