### ISSUE TITLE
Failure when mounting pre-existing data to the CHT

### ISSUE THREAD

**Issue by henokgetachew** [medic/cht-core#9468]
**Describe the bug**

When trying to mount pre-existing data to the CHT, it comes up with a fresh instance and not the existing instance that's on disk.
**To Reproduce**

This [link](https://github.com/medic/cht-docs/pull/1502) has clear steps to reproduce the problem.

**Expected behavior**

Pre-existing data should mount cleanly.

**Comment by dianabarsan** [comment]
I believe this was fixed. Please reopen if not.
