### ISSUE TITLE
UI Nav Work Image Replacement - Contact and User Management

### ISSUE THREAD

**Issue by lorerod** [medic/cht-core#9471]
Cover the UI navigation image updates and start generating screenshots for that work based on the [Google doc shared](https://docs.google.com/document/d/1MHOynkEhWU63TMJo4x8JCuJDapjBk1LW3OnjTXXhi0c/edit#heading=h.ou7i848wdrk1).

This issue will cover the images for:
[Contact and User management](https://docs.communityhealthtoolkit.org/building/contact-management/)
- [x] [Contacts and Users](https://docs.communityhealthtoolkit.org/building/contact-management/contacts/)
- [x] [Contact and User Management - Part 1](https://docs.communityhealthtoolkit.org/building/contact-management/contact-and-users-1/)
- [x] [Contact and User Management - Part 2](https://docs.communityhealthtoolkit.org/building/contact-management/contact-and-users-2/)
- [ ] [Moving Contacts within the Hierarchy](https://docs.communityhealthtoolkit.org/building/contact-management/moving-contacts/)
- [ ] [CHT User Management tool](https://docs.communityhealthtoolkit.org/building/contact-management/user-management-tool/)

The work will be based on [9327-update-nav](https://github.com/medic/cht-core/tree/9327-update-nav) branch. So the screenshots generated will be of the new nav.

**Comment by lorerod** [comment]
@n-orlowski @ZiitheH @esthermmoturi, the PR for this work is almost ready for review. But before sending it for code review to a developer, I would like you to review the [generated screenshots](https://drive.google.com/drive/folders/199yh8keP9G0ORMzrVGF9s8Bx9ROh-Hg9) and let me know if there is any improvement/change you suggest. 
If I understood correctly there are no images to be generated for:
- [Contact and User Management - Part 2](https://docs.communityhealthtoolkit.org/building/contact-management/contact-and-users-2/)
- [Moving Contacts within the Hierarchy](https://docs.communityhealthtoolkit.org/building/contact-management/moving-contacts/)
- [CHT User Management tool](https://docs.communityhealthtoolkit.org/building/contact-management/user-management-tool/)

Please confirm. 
Thanks!

**Comment by esthermmoturi** [comment]
Hey @lorerod , thanks for the updates. For the image in the [Contact and user 2 ](https://docs.communityhealthtoolkit.org/building/contact-management/contact-and-users-2/)page, with the _reports ,messaging and tasks bar_ at the top, should that remain as is?

**Comment by lorerod** [comment]
Hi @esthermmoturi, sorry I missed this. Using WebdriverIO to take screenshots, including the URL, is not possible. I can take the screenshot for this case manually, running the automated test in debug mode, but this image will not be part of the automation.

**Comment by lorerod** [comment]
@esthermmoturi created manually [this](https://drive.google.com/file/d/1P2-ihFwp5fAoE7xlEvOkztqQ0PFmQBjj/view?usp=drive_link) screenshot.
