### ISSUE TITLE
Improve Sidebar Menu's button and label placement 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9481]
**Describe the issue**
During exploration testing we got 2 feedback for improving the Sidebar Menu. 

**Describe the improvement you'd like**
1.. It would be nice to be able to close the hamburger menu from the same position without having to move the cursor to the left. 
 - Make the clickable area of the close icon bigger, that way, we don't need to change the alignment of the close icon and other icons in the sidebar. 

https://github.com/user-attachments/assets/752aa77f-b94f-47e2-917b-751b486829b3

2.. When I chose Bamanankan (Bambara) , on Desktop, the word for messages is too long, and it needs to be cut. I think it is great that nav bar still looks the same, but I was wondering if it ok to cut the work/phrase?
  - Maybe wrap the label to second line and also add ellipsis if it still doesn't fit on second line (we do this with breadcrumbs) 
  
![image (4)](https://github.com/user-attachments/assets/f61cad5c-90a9-4c50-8b5e-4f19aae37589)

Mobile is okay: 
![image (5)](https://github.com/user-attachments/assets/4d5ba977-b1b9-46bf-9327-563ba1c331d7)

**Comment by GallyTi** [comment]
Hi @latin-panda I would like to contribute to this issue if I can.

Thank you

**Comment by latin-panda** [comment]
Thanks @GallyTi. We need a quick confirmation from our designer @n-orlowski to ensure the proposed solution is okay. 

@n-orlowski, are these solutions explained okay?

**Comment by latin-panda** [comment]
@GallyTi, sorry to hear about the problems, I appreciate your efforts in setting up the environment. 
I would like to understand the issues better:

1. What version of NodeJs and NPM have you installed? We recommend using NodeJS 20 and npm 10
2. Can you try running `npm ci` in the root folder of CHT?  It will show many warnings and vulnerabilities but should not show errors. For example, this is my output after running the command: 

<img width="997" alt="Screenshot 2024-10-04 at 10 30 33 AM" src="https://github.com/user-attachments/assets/cd2d2456-0672-434e-87a7-01eb223c578e">


3. If after running the command, errors show. Please post the screenshot here; then we can help assess the problem further

**Comment by GallyTi** [comment]
Yes, as you mentioned, i was on old Version of node.js 12.22.29.

So after updating a node.js to version 20.18.0
and npm on version:10.8.2

So then i run npm ci --legacy-peer-deps in ~/cht-core which resulted to install some deppendencies BUT:

As you can see the npm ci gives me this:

![image](https://github.com/user-attachments/assets/f52507fa-c6bd-49bc-9dc9-db5ed7829b87)


And when i tried to run a  **npm run build-dev** I do get this:
![image](https://github.com/user-attachments/assets/70018b98-5d35-411f-ba12-b4b20036b664)


So any recommendation? Thank you 😄

**Comment by latin-panda** [comment]
> So i thought about clean install. So i removed cht-core and downloaded it again, after running right commends it looks like it is working, so yes it was a error on my side. But i don't know why I was getting those errors, because, when i was trying it first, i had a version 20 of node. After i was trying to install everything i asked a chatgpt, and he replied to downgrading a node.js so really. I don't know what happened.
>
> So after reinstalling it is working properly

@GallyTi Thanks for trying it out again, I'm glad it's working now. 
Looking at the logs you shared, this piece seems suspicious:

```sh
> npm error npm warn old lockfile The package-lock.json file was created with an old version of npm,
> npm error npm warn old lockfile so supplemental metadata must be fetched from the registry.
```

CHT has its own [package-lock.js](https://github.com/medic/cht-core/blob/master/package-lock.json), which is very important because it ensures the installation of dependencies with the correct version by using `npm ci` command. At some point, something seemed to create a `package-lock.json` with an old version producing those errors; in most cases, this error is produced by something running `npm install` command. Removing `node_modules` folders, reverting any change in any of the CHT's `package.json` and `package-lock.js` files and then running `npm ci` in the root folder usually fixes that error.

**Comment by GallyTi** [comment]
So, i tried to install it as you described, and fully clean install, where i will attach 2 txt files with full terminal. Both of them are unsuccessful. So solution for windows is not working, i mean on my machine. Without opening these files you can see same problem for nstalling-cht-core-on-ubuntu-windows-log-from-terminal.txt ass you mentioned.

[installing-cht-core-without-package-lock-json.txt](https://github.com/user-attachments/files/17276369/installing-cht-core-without-package-lock-json.txt)
[installing-cht-core-on-ubuntu-windows-log-from-terminal.txt](https://github.com/user-attachments/files/17276370/installing-cht-core-on-ubuntu-windows-log-from-terminal.txt)


Btw, i can work on these changes in this issue, so i will wait for response from your designer. Thanks, for your support and sorry for troubles... @latin-panda  :)

**Comment by GallyTi** [comment]
Okay, you can assignee this to me. I will try to improve this, and as soon as i will have a solution for this i will provide it by screenshots.

**Comment by latin-panda** [comment]
Thanks @GallyTi for picking this up! You can find documentation that [can help you get started ](https://docs.communityhealthtoolkit.org/contribute/code/#submitting-code). 

If you have any questions, let us know!

**Comment by GallyTi** [comment]
Hi @latin-panda and @n-orlowski. So i made these changes, as you requested:
![Image](https://github.com/user-attachments/assets/8859ab0a-c722-4a67-a273-23404081ae80)
As you mentioned I made a two lines plus ellipses

For the first solution, I have made as close as unopened state, so the Close button is same width and same clickable size as burger menu. Also i have made the adjustments for the menu items so they align properly with close button.
![Image](https://github.com/user-attachments/assets/61663ca3-8353-4ede-88e3-b46d871630f9)

Same changes for mobile menu, where it is aligned to burger menu:
![Image](https://github.com/user-attachments/assets/02295d33-ebf8-4b4b-bd8c-369123974043)

If you have anything to change tell me, i will make a pull request.

**Comment by n-orlowski** [comment]
Thanks @GallyTi ! The double lines in the side nav looks great 🎉  The menu title and text in the drawer is a little far from their corresponding icons, can we keep the original spacing? 🙏

**Comment by GallyTi** [comment]
Hi, @n-orlowski. So I've made the changes you requested. For now it look like this:

The mobile menu:
![Image](https://github.com/user-attachments/assets/fb6cf405-727b-4ee5-a0bd-efb4d90ac22f)

The Desktop menu:
![Image](https://github.com/user-attachments/assets/3ea8fb68-f727-4c12-b4d6-d8efe2eec8e4)

Is it good, or? Thank you :)

**Comment by n-orlowski** [comment]
Looks good to me! Thanks for your help @GallyTi 💪

**Comment by latin-panda** [comment]
@GallyTi I'll be reviewing your PR tomorrow 🤩

**Comment by latin-panda** [comment]
@GallyTi Thanks for contributing to this feature. Your code has been merged! 🤩

@lorerod this will be part of v4.14

**Comment by GallyTi** [comment]
Thank you guys for this opportunity 🤩
