### ISSUE TITLE
Can't edit report on desktop with new UI

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9490]
**Describe the bug**
Open an existing report and edit it in the new UI On a desktop PC. I have a resolution of with 2560px width. There is an invisible element on the right side of the page called `sidebar-filter` with a higher z-index than the content of the page, and this element covers the `Next`/`Submit` button in enketo forms. 

**To Reproduce**
1. Load CHT 4.12
2. Open a form. 
3. Try to submit / go to next page. 
4. Notice that the button isn't clickable and doesn't do anything. 

**Expected behavior**
Should be able to progress in the form.

**Screenshots**
![image](https://github.com/user-attachments/assets/b487c465-0484-46d6-93fe-2e9393a45fd4)

**Environment**
- Instance: local
- Browser: Chrome
- App: webapp
- Version: 4.12

**Comment by latin-panda** [comment]
I see it working at a max of 2348, which is super wide. Adding this to Care Teams board


https://github.com/user-attachments/assets/2b990c70-5483-4e6c-b199-763b448dcae2

**Comment by dianabarsan** [comment]
`2348` is not super wide. Anyone which a QHD screen has more than this. Does it work in 4k?

**Comment by mrjones-plip** [comment]
I'm able to reproduce this, but only by editing an existing report.  The issue does not manifest when creating a new contact or a new place.  

The width of the window seems to 100% obscure the button at 2500 pixels:

![image](https://github.com/user-attachments/assets/5ed8e248-615a-4941-9981-e6e1330085b5)
