### ISSUE TITLE
Identify flaky tests from the last five releases (<= 4.12)

### ISSUE THREAD

**Issue by andrablaj** [medic/cht-core#9497]
**Describe the issue**
There is a [list of tickets](https://github.com/medic/cht-core/issues?q=is%3Aopen+is%3Aissue+label%3AFlaky) about flaky tests. Some were open many years ago and might not be relevant anymore. Some others link to dead links. 

**Describe the improvement you'd like**
We should have a list of flaky tickets during the last five releases (Note: the current release is 4.12). 

Review the flaky tests in the last five releases, open tickets for the new flaky tests, update tickets if they already exist, or close tickets if the tests are not flaky anymore.

**Comment by tatilepizs** [comment]
We closed some tickets and opened new ones according to the recent failures.

Closed tickets:
- [Flaky e2e test Message tab breadcrumbs](https://github.com/medic/cht-core/issues/7969)
- [Flaky test: Test Contact Search Functionality search by NON empty string should display results with contains match and clears search](https://github.com/medic/cht-core/issues/8230)
- [Flaky e2e test should display correct due dates with taskDaysOverdue setting and should display correct due dates with taskDaysOverdue setting and simple translation](https://github.com/medic/cht-core/issues/8257)
- [Flaky test: Contact summary info should load contact summary](https://github.com/medic/cht-core/issues/8342)
- [Flaky test: RepeatForm “before all” hook for RepeatForm](https://github.com/medic/cht-core/issues/8411)

Relevant open tickets:

- [Flaky test Service worker cache branding updates trigger login page refresh](https://github.com/medic/cht-core/issues/8936)
- [Workflows repeatedly fail in e2e tests for muting and unmuting](https://github.com/medic/cht-core/issues/9391)
- [Flaky e2e test: incorrect-locale has been failing constantly in "after each" hook](https://github.com/medic/cht-core/issues/9543)
