### ISSUE TITLE
Sidebar menu does not close if clicking on the current page link

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#9514]
**Describe the bug**
The sidebar menu stays open when trying to access the same page as the one that is currently opened. This is really confusing, especially since the sidebar menu obscures the current page title, so you're not actually aware of what is happening. 

**To Reproduce**
1. Open sidebar menu. 
2. Go to the about page. 
3. Open sidebar menu and click the about page again. 
4. Nothing happens, sidebar menu is still visible and you don't see that you're actually already on the about page. 

**Expected behavior**
Sidebar menu should close regardless of the link clicked. 

**Screenshots**
![image](https://github.com/user-attachments/assets/439937cc-2aa2-4ccb-b4ee-73c1d8f64fca)

**Environment**
- App: Webapp
- Version: 4.12

**Comment by TechGeekRahul** [comment]
hi @dianabarsan  I want to work on this issue.can you assign it to me?
