### ISSUE TITLE
Translations not loaded properly

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9573]
**Describe the bug**
On 4.12.0, we added [Nepali translations](https://github.com/medic/cht-core/pull/9219) for missing keys and it was expected those keys to be translated to Nepali language after upgrade. However, even after upgrading an instance to 4.12.0, there are many translation keys that are not showing the translated text. 

**To Reproduce**
1. Start any instance or upgrade to 4.12.
2. Ensure your CHT language is set to Nepali.
3. Go to admin section and go to SMS configuration (configuration.sms)
4. Go to the third tab (configuration.sms.test.title). You'll see translations missing as shown on screenshot below.

**Expected behavior**
All translation keys, that have the translation available should display the label on the properly translated text. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/4f312bd7-c3f4-4cb4-aaf2-7dcc2d02213a)

**Environment**
- Instance: any
- Browser: Chrome
- Client platform: Mac
- App: Webapp/Admin
- Version: 4.12

**Additional context**
- This can also be checked on NSSD production instance. 
- This could be an issue with other languages as well.

**Comment by 1yuv** [comment]
**Update:**

This could be not an issue with CHT itself. Looks like the instance with issue has translations like this, where a translation was explicitely specified previoulsy when we had missing translation keys. 

```properties
configuration.sms.settings = configuration.sms.settings
configuration.sms.test.description = configuration.sms.test.description
configuration.sms.test.message.description = configuration.sms.test.message.description
configuration.sms.test.number.validation.description = configuration.sms.test.number.validation.description
```

**Comment by 1yuv** [comment]
Confirming that translations are loaded and the original issue was caused by [this](https://github.com/medic/cht-core/issues/9573#issuecomment-2429942423).

**Comment by garethbowen** [comment]
@1yuv The link in the comment just references back to this same issue - was there a different cause?

**Comment by 1yuv** [comment]
Hi @garethbowen , that was intentional, citing the reason mentioned in earlier comment as the cause, so I was referencing that specific comment.
