### ISSUE TITLE
Update cht-datasource `bind` in webapp so it returns a wrapper function instead of a Promise

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#9582]
**Describe the issue**

Currently the experience of consuming the `CHTDatasourceService` in webapp is annoying.  Both the `get` and `bind` methods on the service are async and so code must await them before going on to make _another async call_ to get the data they actually want.

```ts
const datasource = await this.chtDatasourceService.get();
const person = await datasource.v1.person.getByUuid(id);

// OR

const getPerson = await this.chtDatasourceService.bind(Person.v1.get);
const person = await getPerson(Qualifier.byUuid(id));
```

It is annoying to have to `await` twice and it really limits the re-usability of the "bound" functions since they cannot be initialized in a the constructor of a consuming class.  

**Describe the improvement you'd like**
Thanks to the wonders of TypeScript and the built-in [Parameters](https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype) and [ReturnType](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype) types, it is pretty simple to update the `CHTDatasourceService.bind` method to return a function (not a Promise) that wraps the provided function in a type-safe manner. 

```ts
Person.v1.get
// (context: DataContext) => (qualifier: Readonly<{ uuid: string; }>) => Promise<Nullable<Person. v1.Person>>

const getPerson = chtDatasourceService.bind(Person.v1.get);
// (qualifier: Readonly<{   uuid: string }>) => Promise<Nullable<Person.v1.Person>>

const person = await getPerson(Qualifier.byUuid(id));
// Nullable<Person.v1.Person>
``` 

The wrapper function preserves all the typing from the provided function, but basically delays the async dataContext binding until the function is actually called.

**Comment by garethbowen** [comment]
@jkuester Remember to add this to a release milestone.
