### ISSUE TITLE
SMS "integer" validation always returns false

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9604]
**Describe the bug**
Existing functionality of the validations is broken when parsing custom sms fields like bsYear, bsMonth, bsDay. 

**To Reproduce**
1. Configure sms form on base_settings.json and add validations such that it also checks on the data type of the field. 
```json
{
"form": "L",
"events": [],
"validations": {
        "join_responses": false,
        "list": [
          {
            "property": "lmp_year",
            "rule": "(integer && min(2078) && max(2090))",
            "translation_key": "registration.lmp_date.year.incorrect"
          },
          {
            "property": "lmp_month",
            "rule": "(integer && min(1) && max(12))",
            "translation_key": "registration.lmp_date.month.incorrect"
          }
        ]
      }
}
```
2. On forms.json, define these fields and specify type to: `bsYear` for lmp_year and `bsMonth` for month. 
3. Compile and load app settings to the instance. 
4. Submit `L` form with valid integer numbers for year and month.
5. Error is thrown mentioning that the input for year/month/day is not valid. 

![Image](https://github.com/user-attachments/assets/d92781a8-7f3f-489d-8f7b-6068d705f7de)

**Expected behavior**
These fields should be available as an integer type as well and existing validations should work.

**Logs**

**Screenshots**

**Environment**
- Instance: Local development
- Browser: Any
- Client platform: Any
- App: Webapp
- Version: Latest Master (This is not an issue until 4.13.0 release). I suspect this might have been raised after [this change](https://github.com/medic/cht-core/pull/9524) where we changed validation codes. This was first seen on this [PR](https://github.com/medic/cht-core/pull/9602), but later confirmed that this also exists on latest master. 

**Additional context**
This was tested with `bsDate` data type defined on cht-core. There could be similar issue with other types.

**Comment by garethbowen** [comment]
After a little investigation I've confirm this regression and updated the title - specifically this is due to the `integer` validation function. Previously it passed for the string value "2080" but now it fails because of a bug introduced during the [inlining of pupil](https://github.com/medic/cht-core/pull/9524).
