### ISSUE TITLE
Searching report doesn't populate all reports

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9631]
**Describe the bug**
Searching for reports by medic id doesn't populate app forms. Only sms forms are populated on search result. 

**To Reproduce**
1. Have a configuration where both SMS forms and App forms can be submitted for patient.
2. Register/Create a patient, note patient's medic id. 
3. Submit SMS form(s) and webapp form for that patient. 
4. Go to reports tab and search by providing Medic id from step 2. 
5. Only sms froms will be populated on the results and web app form won't be populated on the results. 

**Expected behavior**
If we are searching on reports tab by medic id, result should populate all reports (sms and app forms).

**Logs**

**Screenshots**

**Environment**
- Instance: gandaki prod
- Browser: Any
- App: webapp
- Version: 4.10.0

**Comment by dianabarsan** [comment]
@1yuv 
Which webapp form are you submitting? The connection between report and patient is done through `patient_uuid` and `patient_id` fields, but these are configured within the form itself and aren't added automatically. If your form doesn't store `patient_id`, then there will be no reference to the patient contact through that string. 

Can you share the JSON body of the XML report that you expected to see as a search result, please?

**Comment by 1yuv** [comment]
Hi @dianabarsan , the XML report had `patient_id` set to empty. Which may be the reason why that form didn't come on as a search result. How about searching from patient name? The patient name is in both SMS form and xml form. Is it because they may be stored in different json path?

**Comment by dianabarsan** [comment]
If the report didn't have a patient_id, this is expected behavior and not a bug. 
The report form itself is responsible with populating these fields. 

Are you not getting the XML report when searching by name?

**Comment by dianabarsan** [comment]
Any updates here @1yuv ? Did you find another behavior which is not expected?

**Comment by 1yuv** [comment]
Hi @dianabarsan , I am seeing strange search result on local instance. Sometimes Sms forms are not coming on search result and sometimes xml form are not coming on. Below is the example of sms form not coming on as a result. 

Search result showing xml form only:
![Image](https://github.com/user-attachments/assets/1bccd5c5-c225-49aa-98b2-36a7f09a32e3)

Patient's contact page with 1 xml form and 1 sms form:
![Image](https://github.com/user-attachments/assets/826d7480-fba6-441e-992c-44757b74a3cf)

Let's keep this issue open for a while and observe it on other instances.

**Comment by 1yuv** [comment]
> If the report didn't have a patient_id, this is expected behavior and not a bug. The report form itself is responsible with populating these fields.
> 
> Are you not getting the XML report when searching by name?

I think for the name field also same thing applies. If `name` is not on the field of the other reports, it won't be populated on search result.

**Comment by dianabarsan** [comment]
>  If name is not on the field of the other reports, it won't be populated on search result.

This applies on any field. Search uses fields in the reports alone, and doesn't do any smart connection to contacts.
