### ISSUE TITLE
Users having multiple facility_ids lose all but one facility_id during password reset

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#9669]
**Describe the bug**
Users having multiple facility_ids lose all but one facility_id during password reset

**To Reproduce**
1. Create a user with multiple facility ids
2. Reset the user's password through admin concole

**Expected behavior**
They should still have multiple facility ids

**Environment**
- Instance: nairobi
- App: admin
- Version: 4.13

**Comment by dianabarsan** [comment]
Can't reproduce: https://github.com/user-attachments/assets/853ab3e4-d884-4911-935c-b5e8d371536e

**Comment by kennsippell** [comment]
Sorry. I'll check again and reopen when I find the repro.
